{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSItem/Attributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "c:objc(cs)FSItemAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Attributes"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Attributes"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "FSItem.Attributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Attributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSItem": {
      "abstract": [
        {
          "text": "A distinct object in a file hierarchy, such as a file, directory, symlink, socket, and more.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSItem"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSItem"
        }
      ],
      "role": "symbol",
      "title": "FSItem",
      "type": "topic",
      "url": "/documentation/fskit/fsitem"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attribute": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "FSItem.Attribute",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attribute"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attributes"
        }
      ],
      "role": "symbol",
      "title": "FSItem.Attributes",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/accessTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/accessTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessTime"
        }
      ],
      "role": "symbol",
      "title": "accessTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/accesstime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/addedTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addedTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/addedTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addedTime"
        }
      ],
      "role": "symbol",
      "title": "addedTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/addedtime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/allocSize": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/allocSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allocSize"
        }
      ],
      "role": "symbol",
      "title": "allocSize",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/allocsize"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/backupTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backupTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/backupTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backupTime"
        }
      ],
      "role": "symbol",
      "title": "backupTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/backuptime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/birthTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/birthTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "birthTime"
        }
      ],
      "role": "symbol",
      "title": "birthTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/birthtime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/changeTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/changeTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeTime"
        }
      ],
      "role": "symbol",
      "title": "changeTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/changetime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/fileID": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemID",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/fileID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileID"
        }
      ],
      "role": "symbol",
      "title": "fileID",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/fileid"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/flags": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/flags"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/gid": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/gid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gid"
        }
      ],
      "role": "symbol",
      "title": "gid",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/gid"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/inhibitKernelOffloadedIO": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inhibitKernelOffloadedIO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/inhibitKernelOffloadedIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inhibitKernelOffloadedIO"
        }
      ],
      "role": "symbol",
      "title": "inhibitKernelOffloadedIO",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/inhibitkerneloffloadedio"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/invalidateAllProperties()": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateAllProperties"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/invalidateAllProperties()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateAllProperties"
        }
      ],
      "role": "symbol",
      "title": "invalidateAllProperties()",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/invalidateallproperties()"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/isValid(_:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isValid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemAttribute",
          "text": "Attribute"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/isValid(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isValid:"
        }
      ],
      "role": "symbol",
      "title": "isValid(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/isvalid(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/linkCount": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/linkCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkCount"
        }
      ],
      "role": "symbol",
      "title": "linkCount",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/linkcount"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/mode": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/mode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mode"
        }
      ],
      "role": "symbol",
      "title": "mode",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/mode"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/modifyTime": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modifyTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@timespec",
          "text": "timespec"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/modifyTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modifyTime"
        }
      ],
      "role": "symbol",
      "title": "modifyTime",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/modifytime"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/parentID": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemID",
          "text": "Identifier"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/parentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parentID"
        }
      ],
      "role": "symbol",
      "title": "parentID",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/parentid"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/size": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/size"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/supportsLimitedXAttrs": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsLimitedXAttrs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/supportsLimitedXAttrs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsLimitedXAttrs"
        }
      ],
      "role": "symbol",
      "title": "supportsLimitedXAttrs",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/supportslimitedxattrs"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/type": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSItem",
          "text": "FSItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@FSItemType",
          "text": "ItemType"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/type"
    },
    "doc://FSKit/documentation/FSKit/FSItem/Attributes/uid": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/Attributes/uid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uid"
        }
      ],
      "role": "symbol",
      "title": "uid",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/attributes/uid"
    },
    "doc://FSKit/documentation/FSKit/FSItem/GetAttributesRequest": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GetAttributesRequest"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/GetAttributesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GetAttributesRequest"
        }
      ],
      "role": "symbol",
      "title": "FSItem.GetAttributesRequest",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/getattributesrequest"
    },
    "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAttributesRequest"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SetAttributesRequest"
        }
      ],
      "role": "symbol",
      "title": "FSItem.SetAttributesRequest",
      "type": "topic",
      "url": "/documentation/fskit/fsitem/setattributesrequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-attributes",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSItem/Attribute",
        "doc://FSKit/documentation/FSKit/FSItem/GetAttributesRequest",
        "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest"
      ],
      "title": "Working with attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/accessTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/addedTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/allocSize",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/backupTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/birthTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/changeTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/fileID",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/flags",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/gid",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/inhibitKernelOffloadedIO",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/linkCount",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/mode",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/modifyTime",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/parentID",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/size",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/supportsLimitedXAttrs",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/type",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/uid"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/invalidateAllProperties()",
        "doc://FSKit/documentation/FSKit/FSItem/Attributes/isValid(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FSItemAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://FSKit/documentation/FSKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/accessTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/addedTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/allocSize",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/backupTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/birthTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/changeTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/fileID",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/flags",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/gid",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/inhibitKernelOffloadedIO",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/linkCount",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/mode",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/modifyTime",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/parentID",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/size",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/supportsLimitedXAttrs",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/type",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/uid"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/invalidateAllProperties()",
                "doc://FSKit/documentation/FSKit/FSItem/Attributes/isValid(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-attributes",
              "generated": true,
              "identifiers": [
                "doc://FSKit/documentation/FSKit/FSItem/Attribute",
                "doc://FSKit/documentation/FSKit/FSItem/GetAttributesRequest",
                "doc://FSKit/documentation/FSKit/FSItem/SetAttributesRequest"
              ],
              "title": "Working with attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "FSItemAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1linkCount/title",
          "value": "linkCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1linkCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1invalidateAllProperties()/title",
          "value": "invalidateAllProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1invalidateAllProperties()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateAllProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem/title",
          "value": "FSItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1allocSize/title",
          "value": "allocSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1allocSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allocSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1fileID/title",
          "value": "fileID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1fileID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fileID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1gid/title",
          "value": "gid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1gid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1birthTime/title",
          "value": "birthTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1birthTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "birthTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1GetAttributesRequest/title",
          "value": "FSItemGetAttributesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1GetAttributesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemGetAttributesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1GetAttributesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemGetAttributesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attribute/title",
          "value": "FSItemAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1accessTime/title",
          "value": "accessTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1accessTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1SetAttributesRequest/title",
          "value": "FSItemSetAttributesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1SetAttributesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemSetAttributesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1SetAttributesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemSetAttributesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1uid/title",
          "value": "uid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1uid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1backupTime/title",
          "value": "backupTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1backupTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backupTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1supportsLimitedXAttrs/title",
          "value": "supportsLimitedXAttrs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1supportsLimitedXAttrs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsLimitedXAttrs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1isValid(_:)/title",
          "value": "isValid:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1isValid(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isValid:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1inhibitKernelOffloadedIO/title",
          "value": "inhibitKernelOffloadedIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1inhibitKernelOffloadedIO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inhibitKernelOffloadedIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1changeTime/title",
          "value": "changeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1changeTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "changeTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1mode/title",
          "value": "mode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1mode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes/title",
          "value": "FSItemAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSItemAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1parentID/title",
          "value": "parentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1parentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1addedTime/title",
          "value": "addedTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1addedTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "addedTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1modifyTime/title",
          "value": "modifyTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSItem~1Attributes~1modifyTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modifyTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsitem/attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fskit/fsitem/attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
