{
  "abstract": [
    {
      "text": "Returns the color object associated with the specified key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColorList"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColorList/color(withKey:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColorList(im)colorWithKey:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "color"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSColor",
        "text": "NSColor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSColorName",
        "text": "Name"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSColor",
        "text": "NSColor"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "colorWithKey:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "color(withKey:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "color"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSColor",
              "text": "NSColor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/Name",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSColorName",
              "text": "Name"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSColor",
              "text": "NSColor"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key for which to retrieve the color.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The color associated with the given key or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if there is none.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/Name": {
      "abstract": [
        {
          "text": "The name of a color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/Name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSColor.Name",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList": {
      "abstract": [
        {
          "text": "An ordered list of color objects, identified by keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorList"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorList"
        }
      ],
      "role": "symbol",
      "title": "NSColorList",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList/allKeys": {
      "abstract": [
        {
          "text": "An array of the keys by which the color objects are stored in the color list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList/allKeys",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "role": "symbol",
      "title": "allKeys",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist/allkeys"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList/color(withKey:)": {
      "abstract": [
        {
          "text": "Returns the color object associated with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList/color(withKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorWithKey:"
        }
      ],
      "role": "symbol",
      "title": "color(withKey:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist/color(withkey:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList/insertColor(_:key:at:)": {
      "abstract": [
        {
          "text": "Inserts the specified color at the specified location in the color list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insertColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList/insertColor(_:key:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "insertColor:key:atIndex:"
        }
      ],
      "role": "symbol",
      "title": "insertColor(_:key:at:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist/insertcolor(_:key:at:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList/removeColor(withKey:)": {
      "abstract": [
        {
          "text": "Removes the color associated with the specified key from the color list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList/removeColor(withKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeColorWithKey:"
        }
      ],
      "role": "symbol",
      "title": "removeColor(withKey:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist/removecolor(withkey:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorList/setColor(_:forKey:)": {
      "abstract": [
        {
          "text": "Associates the specified color object with the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorName",
          "text": "Name"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorList/setColor(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setColor:forKey:"
        }
      ],
      "role": "symbol",
      "title": "setColor(_:forKey:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolorlist/setcolor(_:forkey:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Colors-By-Key",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColorList/allKeys",
        "doc://com.apple.appkit/documentation/AppKit/NSColorList/insertColor(_:key:at:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorList/removeColor(withKey:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColorList/setColor(_:forKey:)"
      ],
      "title": "Managing Colors By Key"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "colorWithKey:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorWithKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColorList"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Colors-By-Key",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColorList/allKeys",
                "doc://com.apple.appkit/documentation/AppKit/NSColorList/insertColor(_:key:at:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorList/removeColor(withKey:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColorList/setColor(_:forKey:)"
              ],
              "title": "Managing Colors By Key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSColor",
                    "text": "NSColor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "colorWithKey:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/Name",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSColorName",
                    "text": "NSColorName"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "key"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The key for which to retrieve the color.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "key"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The color associated with the given key or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if there is none.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1insertColor(_:key:at:)/title",
          "value": "insertColor:key:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1insertColor(_:key:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "insertColor:key:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1color(withKey:)/title",
          "value": "colorWithKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1color(withKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorWithKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/title",
          "value": "NSColorList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1removeColor(withKey:)/title",
          "value": "removeColorWithKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1removeColor(withKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeColorWithKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1allKeys/title",
          "value": "allKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1allKeys/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/title",
          "value": "NSColorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1Name/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1setColor(_:forKey:)/title",
          "value": "setColor:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorList~1setColor(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setColor:forKey:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolorlist/color(withkey:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolorlist/color(withkey:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
