{
  "abstract": [
    {
      "text": "The corresponding value is an ",
      "type": "text"
    },
    {
      "code": "NSNumber",
      "type": "codeVoice"
    },
    {
      "text": " object containing an integer that gives the bit depth of the window’s raster image (2-bit, 8-bit, and so forth).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/bitsPerSample"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSDeviceBitsPerSample",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bitsPerSample"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
        "text": "NSDeviceDescriptionKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDeviceBitsPerSample"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bitsPerSample"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bitsPerSample"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey": {
      "abstract": [
        {
          "text": "These constants are the keys for device description dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceDescriptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/bitsPerSample": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object containing an integer that gives the bit depth of the window’s raster image (2-bit, 8-bit, and so forth).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitsPerSample"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/bitsPerSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceBitsPerSample"
        }
      ],
      "role": "symbol",
      "title": "bitsPerSample",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/bitspersample"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/colorSpaceName": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": " object giving the name of the window’s color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/colorSpaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceColorSpaceName"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceName",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/colorspacename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isPrinter": {
      "abstract": [
        {
          "text": "If there is a corresponding value, this indicates that the display device is a printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPrinter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceIsPrinter"
        }
      ],
      "role": "symbol",
      "title": "isPrinter",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/isprinter"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isScreen": {
      "abstract": [
        {
          "text": "If there is a corresponding value, this indicates that the display device is a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceIsScreen"
        }
      ],
      "role": "symbol",
      "title": "isScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/isscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/resolution": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing a value of type ",
          "type": "text"
        },
        {
          "code": "NSSize",
          "type": "codeVoice"
        },
        {
          "text": " that describes the window’s raster resolution in dots per inch (dpi).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/resolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceResolution"
        }
      ],
      "role": "symbol",
      "title": "resolution",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/resolution"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/size": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSValue",
          "type": "codeVoice"
        },
        {
          "text": " object containing a value of type ",
          "type": "text"
        },
        {
          "code": "NSSize",
          "type": "codeVoice"
        },
        {
          "text": " that gives the size of the window’s frame rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceSize"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey/size"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/colorSpaceName",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isPrinter",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isScreen",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/resolution",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/size"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDeviceBitsPerSample"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceBitsPerSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/colorSpaceName",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isPrinter",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/isScreen",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/resolution",
                "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey/size"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
                    "text": "NSDeviceDescriptionKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSDeviceBitsPerSample"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1bitsPerSample/title",
          "value": "NSDeviceBitsPerSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1bitsPerSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceBitsPerSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1isScreen/title",
          "value": "NSDeviceIsScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1isScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceIsScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1isPrinter/title",
          "value": "NSDeviceIsPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1isPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceIsPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/title",
          "value": "NSDeviceDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1colorSpaceName/title",
          "value": "NSDeviceColorSpaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1colorSpaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceColorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1resolution/title",
          "value": "NSDeviceResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1resolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1size/title",
          "value": "NSDeviceSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdevicedescriptionkey/bitspersample"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdevicedescriptionkey/bitspersample"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
