{
  "abstract": [
    {
      "text": "The extension context provided by the host app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/extensionContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FPUIActionExtensionViewController(py)extensionContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extensionContext"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)FPUIActionExtensionContext",
        "text": "FPUIActionExtensionContext"
      }
    ],
    "modules": [
      {
        "name": "File Provider UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "extensionContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "extensionContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)FPUIActionExtensionContext",
              "text": "FPUIActionExtensionContext"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI": {
      "abstract": [
        {
          "text": "Add actions to the document browser’s context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider UI",
      "type": "topic",
      "url": "/documentation/fileproviderui"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext": {
      "abstract": [
        {
          "text": "An extension context provided to File Provider UI extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "FPUIActionExtensionContext",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensioncontext"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController": {
      "abstract": [
        {
          "text": "The custom user interface used to perform a selected action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionViewController"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionViewController"
        }
      ],
      "role": "symbol",
      "title": "FPUIActionExtensionViewController",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensionviewcontroller"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/extensionContext": {
      "abstract": [
        {
          "text": "The extension context provided by the host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FPUIActionExtensionContext",
          "text": "FPUIActionExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/extensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensionContext"
        }
      ],
      "role": "symbol",
      "title": "extensionContext",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensionviewcontroller/extensioncontext"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forAction:itemIdentifiers:)": {
      "abstract": [
        {
          "text": "Performs any necessary setup or configuration for the specified action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderItemIdentifier",
          "text": "NSFileProviderItemIdentifier"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forAction:itemIdentifiers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareForActionWithIdentifier:itemIdentifiers:"
        }
      ],
      "role": "symbol",
      "title": "prepare(forAction:itemIdentifiers:)",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensionviewcontroller/prepare(foraction:itemidentifiers:)"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forError:)": {
      "abstract": [
        {
          "text": "Performs any necessary setup or configuration when an authentication error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareForError:"
        }
      ],
      "role": "symbol",
      "title": "prepare(forError:)",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensionviewcontroller/prepare(forerror:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forAction:itemIdentifiers:)",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forError:)",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext"
      ],
      "title": "Working with Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "extensionContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forAction:itemIdentifiers:)",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionViewController/prepare(forError:)",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext"
              ],
              "title": "Working with Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)FPUIActionExtensionContext",
                    "text": "FPUIActionExtensionContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "extensionContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/title",
          "value": "FPUIActionExtensionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1extensionContext/title",
          "value": "extensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1extensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/title",
          "value": "FPUIActionExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1prepare(forAction:itemIdentifiers:)/title",
          "value": "prepareForActionWithIdentifier:itemIdentifiers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1prepare(forAction:itemIdentifiers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareForActionWithIdentifier:itemIdentifiers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1prepare(forError:)/title",
          "value": "prepareForError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionViewController~1prepare(forError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareForError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileproviderui/fpuiactionextensionviewcontroller/extensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileproviderui/fpuiactionextensionviewcontroller/extensioncontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
