{
  "abstract": [
    {
      "text": "An unknown state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INAddMediaIntentResponseCode@INAddMediaIntentResponseCodeUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INAddMediaIntentResponseCodeUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INAddMediaIntentResponseCode.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode": {
      "abstract": [
        {
          "text": "Codes returned by an app or Intents app extension when handling or confirming an add media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "The app was unable to add the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch the app to add media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/handleInApp": {
      "abstract": [
        {
          "text": "The system should launch the app in the background to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/handleInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeHandleInApp"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.handleInApp",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/handleinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "The app is currently trying to process the add media request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "The app is ready to add media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/success": {
      "abstract": [
        {
          "text": "The app successfully added the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "An unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inaddmediaintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/handleInApp",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failureRequiringAppLaunch"
      ],
      "title": "Response Code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INAddMediaIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/handleInApp",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaIntentResponseCode/failureRequiringAppLaunch"
              ],
              "title": "Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INAddMediaIntentResponseCodeUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1success/title",
          "value": "INAddMediaIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1handleInApp/title",
          "value": "INAddMediaIntentResponseCodeHandleInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1handleInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeHandleInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1ready/title",
          "value": "INAddMediaIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1unspecified/title",
          "value": "INAddMediaIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INAddMediaIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1inProgress/title",
          "value": "INAddMediaIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode/title",
          "value": "INAddMediaIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1failure/title",
          "value": "INAddMediaIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaIntentResponseCodeFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inaddmediaintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inaddmediaintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
