{
  "abstract": [
    {
      "text": "Audio media type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.medialibrary/documentation/MediaLibrary",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/audio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLMediaType@MLMediaTypeAudio",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "audio"
      }
    ],
    "modules": [
      {
        "name": "Media Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLMediaTypeAudio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.15",
        "introducedAt": "10.9",
        "message": "MediaLibrary.framework will be removed in a future OS version. Use Photos.framework or iTunesLibrary.framework instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLMediaType.audio"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "audio"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary": {
      "abstract": [
        {
          "text": "Access read-only collections of the user’s multimedia content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Library",
      "type": "topic",
      "url": "/documentation/medialibrary"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/mediaType": {
      "abstract": [
        {
          "text": "The media object’s type of media (image, audio, or movie).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MLMediaType",
          "text": "MLMediaType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediaobject/mediatype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType": {
      "abstract": [
        {
          "text": "Specifies the media type associated with a particular media object. These constants are used to specify a media object’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaObject/mediaType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMediaType"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaType"
        }
      ],
      "role": "symbol",
      "title": "MLMediaType",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediatype"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/audio": {
      "abstract": [
        {
          "text": "Audio media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "MLMediaType.audio",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediatype/audio"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/image": {
      "abstract": [
        {
          "text": "Image media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaTypeImage"
        }
      ],
      "role": "symbol",
      "title": "MLMediaType.image",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediatype/image"
    },
    "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/movie": {
      "abstract": [
        {
          "text": "Video media type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        }
      ],
      "identifier": "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMediaTypeMovie"
        }
      ],
      "role": "symbol",
      "title": "MLMediaType.movie",
      "type": "topic",
      "url": "/documentation/medialibrary/mlmediatype/movie"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/image",
        "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/movie"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.15",
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLMediaTypeAudio"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.medialibrary/documentation/MediaLibrary",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/image",
                "doc://com.apple.medialibrary/documentation/MediaLibrary/MLMediaType/movie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLMediaTypeAudio"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObject~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaObject~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1movie/title",
          "value": "MLMediaTypeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaTypeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1audio/title",
          "value": "MLMediaTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1image/title",
          "value": "MLMediaTypeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaTypeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType/title",
          "value": "MLMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.medialibrary~1documentation~1MediaLibrary~1MLMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMediaType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/medialibrary/mlmediatype/audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/medialibrary/mlmediatype/audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
