{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()"},"sections":[],"seeAlsoSections":[{"anchor":"Supporting-Accessibility","title":"Supporting Accessibility","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()"],"generated":true}],"metadata":{"modules":[{"name":"AppKit"}],"externalID":"c:objc(pl)NSAccessibilityTable(im)accessibilityVisibleCells","navigatorTitle":[{"text":"accessibilityVisibleCells","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleCells","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"title":"accessibilityVisibleCells()"},"abstract":[{"type":"text","text":"Returns the visible cells for the table."}],"variants":[{"paths":["/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecells()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecells()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityVisibleCells"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An array containing the currently visible cells."}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"text":"This method is the getter for the ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference","isActive":true},{"text":" protocol’s ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCells","type":"reference","isActive":true},{"text":" property.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSArray":{"title":"NSArray","url":"/documentation/foundation/nsarray","fragments":[{"text":"class ","kind":"text"},{"text":"NSArray","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics."}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable":{"abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a table view."}],"type":"topic","title":"NSAccessibilityTable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityTable"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityTable"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","abstract":[{"text":"Returns the row header accessibility elements for the table.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityRowHeaderUIElements","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"title":"accessibilityRowHeaderUIElements()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityrowheaderuielements()","type":"topic","navigatorTitle":[{"text":"accessibilityRowHeaderUIElements","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","abstract":[{"text":"Returns the visible columns for the table.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"accessibilityVisibleColumns","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleColumns","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"title":"accessibilityVisibleColumns()","kind":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecolumns()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityLabel"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"accessibilityLabel()","url":"/documentation/appkit/nsaccessibilitytable/accessibilitylabel()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","type":"topic","abstract":[{"text":"Returns a short description of the table.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityLabel"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()":{"abstract":[{"text":"The currently selected cells for the table.","type":"text"}],"navigatorTitle":[{"text":"accessibilitySelectedCells","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedcells()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedCells","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","title":"accessibilitySelectedCells()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()":{"url":"/documentation/appkit/nsaccessibilitytable/accessibilityrows()","title":"accessibilityRows()","kind":"symbol","required":true,"abstract":[{"text":"Returns the row accessibility elements for the table.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityRows","kind":"identifier"},{"kind":"text","text":"() -> [any "},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityRows"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedRows","kind":"identifier"},{"text":"() -> [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","abstract":[{"text":"Returns the currently selected rows for the table.","type":"text"}],"type":"topic","title":"accessibilitySelectedRows()","kind":"symbol","navigatorTitle":[{"text":"accessibilitySelectedRows","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedrows()","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()":{"abstract":[{"text":"Returns the column accessibility elements for the table.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"accessibilityColumns"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","url":"/documentation/appkit/nsaccessibilitytable/accessibilitycolumns()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityColumns"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"role":"symbol","title":"accessibilityColumns()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()":{"abstract":[{"text":"Returns the visible cells for the table.","type":"text"}],"type":"topic","title":"accessibilityVisibleCells()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleCells","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleCells()","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblecells()","navigatorTitle":[{"text":"accessibilityVisibleCells","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","abstract":[{"type":"text","text":"Returns the column header accessibility elements for the table."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"title":"accessibilityColumnHeaderUIElements()","kind":"symbol","url":"/documentation/appkit/nsaccessibilitytable/accessibilitycolumnheaderuielements()","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()":{"abstract":[{"text":"Returns the currently selected columns for the table.","type":"text"}],"navigatorTitle":[{"text":"accessibilitySelectedColumns","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityselectedcolumns()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilitySelectedColumns","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"role":"symbol","title":"accessibilitySelectedColumns()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityHeaderGroup","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"accessibilityHeaderGroup()","url":"/documentation/appkit/nsaccessibilitytable/accessibilityheadergroup()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()","type":"topic","abstract":[{"text":"Returns the header group for the table.","type":"text"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"text":"accessibilityHeaderGroup","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityVisibleRows","kind":"identifier"},{"text":"() -> [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSAccessibilityRow","text":"NSAccessibilityRow","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","abstract":[{"text":"Returns the visible rows for the table.","type":"text"}],"url":"/documentation/appkit/nsaccessibilitytable/accessibilityvisiblerows()","title":"accessibilityVisibleRows()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"accessibilityVisibleRows","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)":{"abstract":[{"text":"Sets the table’s currently selected rows.","type":"text"}],"type":"topic","title":"setAccessibilitySelectedRows(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAccessibilitySelectedRows","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"NSAccessibilityRow","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSAccessibilityRow"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","role":"symbol","url":"/documentation/appkit/nsaccessibilitytable/setaccessibilityselectedrows(_:)","navigatorTitle":[{"text":"setAccessibilitySelectedRows:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCells":{"type":"topic","title":"accessibilityVisibleCells","role":"symbol","url":"/documentation/appkit/nsaccessibility-c.protocol/accessibilityvisiblecells","fragments":[{"text":"accessibilityVisibleCells","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCells","abstract":[{"type":"text","text":"The visible cells for the table."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"accessibilityVisibleCells"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityVisibleCells"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityVisibleCells"],"anchor":"Related-Documentation","title":"Related Documentation"},{"title":"Supporting Accessibility","anchor":"Supporting-Accessibility","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumnHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityLabel()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRowHeaderUIElements()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedCells()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilitySelectedRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleColumns()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityVisibleRows()","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/setAccessibilitySelectedRows(_:)","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityTable/accessibilityHeaderGroup()"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSArray","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"accessibilityVisibleCells"},{"kind":"text","text":";"}]}]}},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"An array containing the currently visible cells."}],"type":"paragraph"}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract","value":[{"type":"text","text":"A static ordered collection of objects."}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/title","value":"NSAccessibilityTable"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/fragments","value":[{"kind":"identifier","text":"NSAccessibilityTable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable/navigatorTitle","value":[{"text":"NSAccessibilityTable","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRowHeaderUIElements()/title","value":"accessibilityRowHeaderUIElements"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRowHeaderUIElements()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityRowHeaderUIElements"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleColumns()/title","value":"accessibilityVisibleColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleColumns()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityVisibleColumns","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityLabel()/title","value":"accessibilityLabel"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityLabel()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilityLabel","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedCells()/title","value":"accessibilitySelectedCells"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedCells()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessibilitySelectedCells","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRows()/title","value":"accessibilityRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityRows()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityRows"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedRows()/title","value":"accessibilitySelectedRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedRows()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilitySelectedRows"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumns()/title","value":"accessibilityColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumns()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityColumns"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleCells()/title","value":"accessibilityVisibleCells"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleCells()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityVisibleCells"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumnHeaderUIElements()/title","value":"accessibilityColumnHeaderUIElements"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityColumnHeaderUIElements()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityColumnHeaderUIElements"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedColumns()/title","value":"accessibilitySelectedColumns"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilitySelectedColumns()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilitySelectedColumns"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityHeaderGroup()/title","value":"accessibilityHeaderGroup"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityHeaderGroup()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityHeaderGroup"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleRows()/title","value":"accessibilityVisibleRows"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1accessibilityVisibleRows()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityVisibleRows"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1setAccessibilitySelectedRows(_:)/title","value":"setAccessibilitySelectedRows:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityTable~1setAccessibilitySelectedRows(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAccessibilitySelectedRows:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}