{
  "abstract": [
    {
      "text": "A style indicating that the date pickers displays as an inline, editable field.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/inline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDatePickerStyle@UIDatePickerStyleInline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inline"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDatePickerStyleInline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIDatePickerStyle.inline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inline"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this style when you want to let users edit the date picker value without having to tap the label shown in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/compact",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can’t use this style with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePicker/Mode/countDownTimer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePicker/Mode/countDownTimer": {
      "abstract": [
        {
          "text": "A mode that displays hour and minute values, for example, “1 | 53”. The application must set a timer to fire at the proper interval and set the date picker as the seconds tick down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countDownTimer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePicker/Mode/countDownTimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerModeCountDownTimer"
        }
      ],
      "role": "symbol",
      "title": "UIDatePicker.Mode.countDownTimer",
      "type": "topic",
      "url": "/documentation/uikit/uidatepicker/mode/countdowntimer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle": {
      "abstract": [
        {
          "text": "Styles that determine the appearance of a date picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDatePickerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIDatePickerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uidatepickerstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system picks the concrete style based on the current platform and date picker mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UIDatePickerStyle.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uidatepickerstyle/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/compact": {
      "abstract": [
        {
          "text": "A style indicating that the date picker displays as a label that when tapped displays a calendar-style editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compact"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/compact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerStyleCompact"
        }
      ],
      "role": "symbol",
      "title": "UIDatePickerStyle.compact",
      "type": "topic",
      "url": "/documentation/uikit/uidatepickerstyle/compact"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/inline": {
      "abstract": [
        {
          "text": "A style indicating that the date pickers displays as an inline, editable field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/inline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerStyleInline"
        }
      ],
      "role": "symbol",
      "title": "UIDatePickerStyle.inline",
      "type": "topic",
      "url": "/documentation/uikit/uidatepickerstyle/inline"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/wheels": {
      "abstract": [
        {
          "text": "A style indicating that the date picker displays as a wheel picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wheels"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/wheels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDatePickerStyleWheels"
        }
      ],
      "role": "symbol",
      "title": "UIDatePickerStyle.wheels",
      "type": "topic",
      "url": "/documentation/uikit/uidatepickerstyle/wheels"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/compact",
        "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/wheels"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDatePickerStyleInline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyleInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/compact",
                "doc://com.apple.uikit/documentation/UIKit/UIDatePickerStyle/wheels"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIDatePickerStyleInline"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1automatic/title",
          "value": "UIDatePickerStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePicker~1Mode~1countDownTimer/title",
          "value": "UIDatePickerModeCountDownTimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePicker~1Mode~1countDownTimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerModeCountDownTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle/title",
          "value": "UIDatePickerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1wheels/title",
          "value": "UIDatePickerStyleWheels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1wheels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyleWheels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1compact/title",
          "value": "UIDatePickerStyleCompact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1compact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyleCompact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1inline/title",
          "value": "UIDatePickerStyleInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDatePickerStyle~1inline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDatePickerStyleInline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidatepickerstyle/inline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidatepickerstyle/inline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
