{
  "abstract": [
    {
      "text": "Elliptical collision bounds. The shape of the ellipse is determined by the width and height of the item’s ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/bounds",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/ellipse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDynamicItemCollisionBoundsType@UIDynamicItemCollisionBoundsTypeEllipse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ellipse"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDynamicItemCollisionBoundsTypeEllipse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIDynamicItemCollisionBoundsType.ellipse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ellipse"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBezierPath": {
      "abstract": [
        {
          "text": "A path that consists of straight and curved line segments that you can render in your custom views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBezierPath"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBezierPath"
        }
      ],
      "role": "symbol",
      "title": "UIBezierPath",
      "type": "topic",
      "url": "/documentation/uikit/uibezierpath"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/bounds": {
      "abstract": [
        {
          "text": "Called when a dynamic animator needs the bounds of the dynamic item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/bounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounds"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitem/bounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/collisionBoundingPath": {
      "abstract": [
        {
          "text": "The path-based shape to use for the collision bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBoundingPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBezierPath",
          "text": "UIBezierPath"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/collisionBoundingPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBoundingPath"
        }
      ],
      "role": "symbol",
      "title": "collisionBoundingPath",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitem/collisionboundingpath"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType": {
      "abstract": [
        {
          "text": "Constants that indicate the shape of the item’s collision bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItemCollisionBoundsType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemCollisionBoundsType"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemCollisionBoundsType",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitemcollisionboundstype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/ellipse": {
      "abstract": [
        {
          "text": "Elliptical collision bounds. The shape of the ellipse is determined by the width and height of the item’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/bounds",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ellipse"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/ellipse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemCollisionBoundsTypeEllipse"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemCollisionBoundsType.ellipse",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitemcollisionboundstype/ellipse"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/path": {
      "abstract": [
        {
          "text": "Path-based collision bounds. For this type, the shape is a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBezierPath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object stored in the item’s ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem/collisionBoundingPath",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property. See the description of that property for information about how to configure the path itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "path"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/path",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemCollisionBoundsTypePath"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemCollisionBoundsType.path",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitemcollisionboundstype/path"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/rectangle": {
      "abstract": [
        {
          "text": "Rectangular collision bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/rectangle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemCollisionBoundsTypeRectangle"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemCollisionBoundsType.rectangle",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitemcollisionboundstype/rectangle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/rectangle",
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/path"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDynamicItemCollisionBoundsTypeEllipse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsTypeEllipse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/rectangle",
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemCollisionBoundsType/path"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIDynamicItemCollisionBoundsTypeEllipse"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType/title",
          "value": "UIDynamicItemCollisionBoundsType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1rectangle/title",
          "value": "UIDynamicItemCollisionBoundsTypeRectangle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1rectangle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsTypeRectangle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/title",
          "value": "UIBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem~1bounds/title",
          "value": "bounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem~1bounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1path/title",
          "value": "UIDynamicItemCollisionBoundsTypePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1path/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsTypePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem~1collisionBoundingPath/title",
          "value": "collisionBoundingPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem~1collisionBoundingPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collisionBoundingPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1ellipse/title",
          "value": "UIDynamicItemCollisionBoundsTypeEllipse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemCollisionBoundsType~1ellipse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemCollisionBoundsTypeEllipse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidynamicitemcollisionboundstype/ellipse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidynamicitemcollisionboundstype/ellipse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
