{
  "abstract": [
    {
      "text": "Constants that define the supported ducking levels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@E@AVAudioVoiceProcessingOtherAudioDuckingLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Level"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Level"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Level"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration": {
      "abstract": [
        {
          "text": "The configuration of ducking non-voice audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level": {
      "abstract": [
        {
          "text": "Constants that define the supported ducking levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Level"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default": {
      "abstract": [
        {
          "text": "The default ducking level for typical voice chat.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.default",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/default"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max": {
      "abstract": [
        {
          "text": "Applies maximum ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.max",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/max"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid": {
      "abstract": [
        {
          "text": "Applies medium ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mid"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.mid",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/mid"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min": {
      "abstract": [
        {
          "text": "Applies minimum ducking to other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
        }
      ],
      "role": "symbol",
      "title": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration.Level.min",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level/min"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/duckingLevel": {
      "abstract": [
        {
          "text": "The ducking level of other audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duckingLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVAudioVoiceProcessingOtherAudioDuckingConfiguration",
          "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioVoiceProcessingOtherAudioDuckingLevel",
          "text": "Level"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/duckingLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duckingLevel"
        }
      ],
      "role": "symbol",
      "title": "duckingLevel",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/duckinglevel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/enableAdvancedDucking": {
      "abstract": [
        {
          "text": "Enables advanced ducking which ducks other audio based on the presence of voice activity from local and remote chat participants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableAdvancedDucking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/enableAdvancedDucking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableAdvancedDucking"
        }
      ],
      "role": "symbol",
      "title": "enableAdvancedDucking",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/enableadvancedducking"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-ducking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/enableAdvancedDucking",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/duckingLevel"
      ],
      "title": "Configuring ducking"
    }
  ],
  "topicSections": [
    {
      "anchor": "Ducking-levels",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min"
      ],
      "title": "Ducking levels"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Ducking-levels",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/default",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/max",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/mid",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/Level/min"
              ],
              "title": "Ducking levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-ducking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/enableAdvancedDucking",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioVoiceProcessingOtherAudioDuckingConfiguration/duckingLevel"
              ],
              "title": "Configuring ducking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1min/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1max/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1enableAdvancedDucking/title",
          "value": "enableAdvancedDucking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1enableAdvancedDucking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enableAdvancedDucking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1duckingLevel/title",
          "value": "duckingLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1duckingLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duckingLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1default/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1mid/title",
          "value": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioVoiceProcessingOtherAudioDuckingConfiguration~1Level~1mid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioVoiceProcessingOtherAudioDuckingLevelMid"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiovoiceprocessingotheraudioduckingconfiguration/level"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
