{"metadata":{"roleHeading":"Instance Method","platforms":[{"beta":false,"name":"watchOS","introducedAt":"2.0","unavailable":false,"deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAnnotation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKInterfaceMapPinColor","preciseIdentifier":"c:@E@WKInterfaceMapPinColor"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addAnnotation:withPinColor:"}],"role":"symbol","symbolKind":"method","modules":[{"name":"WatchKit"}],"title":"addAnnotation(_:with:)","externalID":"c:objc(cs)WKInterfaceMap(im)addAnnotation:withPinColor:"},"seeAlsoSections":[{"anchor":"Managing-Map-Annotations","generated":true,"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()"],"title":"Managing Map Annotations"}],"identifier":{"url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"Adds a pin to the map at the specified location.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/watchkit/wkinterfacemap/addannotation(_:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/watchkit/wkinterfacemap/addannotation(_:with:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAnnotation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pinColor"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","text":"WKInterfaceMapPinColor","kind":"typeIdentifier","preciseIdentifier":"c:@E@WKInterfaceMapPinColor"},{"text":")","kind":"text"}],"platforms":["watchOS"]}]},{"kind":"parameters","parameters":[{"name":"location","content":[{"type":"paragraph","inlineContent":[{"text":"The location at which to display the pin.","type":"text"}]}]},{"name":"pinColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The color of the pin. For a list of possible values, see "},{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","type":"reference","isActive":true},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The pin is positioned so that the base of the pin sits on top of the specified coordinate."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D":{"type":"topic","url":"/documentation/CoreLocation/CLLocationCoordinate2D","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CLLocationCoordinate2D","kind":"identifier"}],"role":"symbol","title":"CLLocationCoordinate2D","kind":"symbol","abstract":[{"text":"The latitude and longitude associated with a location, specified using the WGS 84 reference frame.","type":"text"}]},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap":{"abstract":[{"type":"text","text":"An interface element that displays a noninteractive map for the location you specify."}],"url":"/documentation/watchkit/wkinterfacemap","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WKInterfaceMap"}],"role":"symbol","navigatorTitle":[{"text":"WKInterfaceMap","kind":"identifier"}],"title":"WKInterfaceMap","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)":{"title":"addAnnotation(_:withImageNamed:centerOffset:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAnnotation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withImageNamed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"centerOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/watchkit/wkinterfacemap/addannotation(_:withimagenamed:centeroffset:)","abstract":[{"text":"Displays an image from the WatchKit app’s bundle on top of the map.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"addAnnotation:withImageNamed:centerOffset:","kind":"identifier"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)","type":"topic"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)":{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:)","url":"/documentation/watchkit/wkinterfacemap/addannotation(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addAnnotation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKInterfaceMapPinColor","preciseIdentifier":"c:@E@WKInterfaceMapPinColor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Adds a pin to the map at the specified location."}],"navigatorTitle":[{"text":"addAnnotation:withPinColor:","kind":"identifier"}],"role":"symbol","title":"addAnnotation(_:with:)"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor":{"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","url":"/documentation/watchkit/wkinterfacemappincolor","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"WKInterfaceMapPinColor","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Constants for map pin colors."}],"navigatorTitle":[{"text":"WKInterfaceMapPinColor","kind":"identifier"}],"role":"symbol","title":"WKInterfaceMapPinColor"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllAnnotations"},{"kind":"text","text":"()"}],"abstract":[{"text":"Removes all annotations from the map.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeAllAnnotations"}],"url":"/documentation/watchkit/wkinterfacemap/removeallannotations()","title":"removeAllAnnotations()","type":"topic","kind":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()","role":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAnnotation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"centerOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Displays the specified image on top of the map.","type":"text"}],"navigatorTitle":[{"text":"addAnnotation:withImage:centerOffset:","kind":"identifier"}],"url":"/documentation/watchkit/wkinterfacemap/addannotation(_:with:centeroffset:)","title":"addAnnotation(_:with:centerOffset:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"addAnnotation:withPinColor:"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"addAnnotation:withPinColor:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Managing-Map-Annotations","title":"Managing Map Annotations","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:with:centerOffset:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/addAnnotation(_:withImageNamed:centerOffset:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMap/removeAllAnnotations()"],"generated":true}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"addAnnotation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationCoordinate2D","identifier":"doc://com.externally.resolved.symbol/c:@S@CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withPinColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKInterfaceMapPinColor","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor","preciseIdentifier":"c:@E@WKInterfaceMapPinColor","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pinColor","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["watchOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"location","content":[{"inlineContent":[{"type":"text","text":"The location at which to display the pin."}],"type":"paragraph"}]},{"name":"pinColor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The color of the pin. For a list of possible values, see "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceMapPinColor"},{"type":"text","text":"."}]}]}],"kind":"parameters"},"op":"replace"},{"value":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"identifier"},{"text":";","kind":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@S@CLLocationCoordinate2D/fragments"},{"value":"WKInterfaceMap","op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/title"},{"value":[{"kind":"identifier","text":"WKInterfaceMap"}],"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/fragments"},{"value":[{"kind":"identifier","text":"WKInterfaceMap"}],"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap/navigatorTitle"},{"value":"addAnnotation:withImageNamed:centerOffset:","op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:withImageNamed:centerOffset:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addAnnotation:withImageNamed:centerOffset:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:withImageNamed:centerOffset:)/fragments"},{"value":"addAnnotation:withPinColor:","op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addAnnotation:withPinColor:"}],"op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:)/fragments"},{"value":"WKInterfaceMapPinColor","op":"replace","path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/title"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/fragments","value":[{"text":"WKInterfaceMapPinColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMapPinColor/navigatorTitle","value":[{"text":"WKInterfaceMapPinColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1removeAllAnnotations()/title","value":"removeAllAnnotations","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1removeAllAnnotations()/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllAnnotations","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:centerOffset:)/title","value":"addAnnotation:withImage:centerOffset:","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceMap~1addAnnotation(_:with:centerOffset:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addAnnotation:withImage:centerOffset:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}