{
  "abstract": [
    {
      "text": "A Smart Album that groups all RAW assets in the photo library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHAssetCollectionSubtype@PHAssetCollectionSubtypeSmartAlbumRAW",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "smartAlbumRAW"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHAssetCollectionSubtype.smartAlbumRAW"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "smartAlbumRAW"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype": {
      "abstract": [
        {
          "text": "The subtype of the asset collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetCollectionSubtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionSubtype",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetCollectionSubtype"
        }
      ],
      "role": "symbol",
      "title": "assetCollectionSubtype",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/assetcollectionsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)": {
      "abstract": [
        {
          "text": "Retrieves asset collections of the specified type and subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchAssetCollections"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionType",
          "text": "PHAssetCollectionType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHAssetCollectionSubtype",
          "text": "PHAssetCollectionSubtype"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchOptions",
          "text": "PHFetchOptions"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHFetchResult",
          "text": "PHFetchResult"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAssetCollection",
          "text": "PHAssetCollection"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchAssetCollectionsWithType:subtype:options:"
        }
      ],
      "role": "symbol",
      "title": "fetchAssetCollections(with:subtype:options:)",
      "type": "topic",
      "url": "/documentation/photos/phassetcollection/fetchassetcollections(with:subtype:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype": {
      "abstract": [
        {
          "text": "Minor distinctions between kinds of asset collections, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/assetCollectionSubtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollection/fetchAssetCollections(with:subtype:options:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtype"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets hidden from the Moments view in the Photos app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumAllHidden"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumAllHidden",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumallhidden"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated": {
      "abstract": [
        {
          "text": "A Smart Album that groups all image animation assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumAnimated"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumAnimated"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumAnimated",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumanimated"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts": {
      "abstract": [
        {
          "text": "A Smart Album that groups all burst photo sequences in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumBursts"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumBursts"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumBursts",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumbursts"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic": {
      "abstract": [
        {
          "text": "A Smart Album that groups all cinematic photo assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumCinematic"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumCinematic"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumCinematic",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumcinematic"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect": {
      "abstract": [
        {
          "text": "A Smart Album that groups all images captured using the Depth Effect camera mode on compatible devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumDepthEffect"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumDepthEffect",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumdeptheffect"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites": {
      "abstract": [
        {
          "text": "A Smart Album that groups all assets that the user marks as favorites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumFavorites"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumFavorites"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumFavorites",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumfavorites"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric": {
      "abstract": [
        {
          "text": "A Smart Album without a more-specific subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumGeneric"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumGeneric"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumGeneric",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumgeneric"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Live Photos assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumLivePhotos"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumLivePhotos",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumlivephotos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Live Photos assets where the Long Exposure variation is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumLongExposures"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumLongExposures",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumlongexposures"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas": {
      "abstract": [
        {
          "text": "A Smart Album that groups all panorama photos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumPanoramas"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumPanoramas",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumpanoramas"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW": {
      "abstract": [
        {
          "text": "A Smart Album that groups all RAW assets in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumRAW"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRAW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumRAW",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumraw"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded": {
      "abstract": [
        {
          "text": "A Smart Album that groups all recently added assets in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumRecentlyAdded"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumRecentlyAdded",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumrecentlyadded"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots": {
      "abstract": [
        {
          "text": "A Smart Album that groups all images captured using the device’s screenshot function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumScreenshots"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumScreenshots",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumscreenshots"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits": {
      "abstract": [
        {
          "text": "A Smart Album that groups all photos and videos captured using the device’s front-facing camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumSelfPortraits"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumSelfPortraits",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumselfportraits"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos": {
      "abstract": [
        {
          "text": "A Smart Album that groups all Slow-Mo videos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumSlomoVideos"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumSlomoVideos",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumslomovideos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses": {
      "abstract": [
        {
          "text": "A Smart Album that groups all time-lapse videos in the photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smartAlbumTimelapses"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
        }
      ],
      "role": "symbol",
      "title": "PHAssetCollectionSubtype.smartAlbumTimelapses",
      "type": "topic",
      "url": "/documentation/photos/phassetcollectionsubtype/smartalbumtimelapses"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Smart-Album-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
        "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses"
      ],
      "title": "Smart Album Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumRAW"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Smart-Album-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAllHidden",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumAnimated",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumBursts",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumCinematic",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumDepthEffect",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumFavorites",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumGeneric",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLivePhotos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumLongExposures",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumPanoramas",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumRecentlyAdded",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumScreenshots",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSelfPortraits",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumSlomoVideos",
                "doc://com.apple.photokit/documentation/Photos/PHAssetCollectionSubtype/smartAlbumTimelapses"
              ],
              "title": "Smart Album Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumDepthEffect/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumDepthEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumDepthEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAllHidden/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAllHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumAllHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumScreenshots/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumScreenshots/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumScreenshots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionSubtype/title",
          "value": "assetCollectionSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1assetCollectionSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumFavorites/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumFavorites"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumFavorites/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumFavorites"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumBursts/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumBursts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumBursts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumBursts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumTimelapses/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumTimelapses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumTimelapses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRAW/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumRAW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRAW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumRAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumGeneric/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSlomoVideos/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSlomoVideos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumSlomoVideos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumCinematic/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumCinematic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumCinematic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumCinematic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumPanoramas/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumPanoramas/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumPanoramas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSelfPortraits/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumSelfPortraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumSelfPortraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLongExposures/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLongExposures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumLongExposures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLivePhotos/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumLivePhotos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumLivePhotos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/title",
          "value": "PHAssetCollectionSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAnimated/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumAnimated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumAnimated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumAnimated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRecentlyAdded/title",
          "value": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollectionSubtype~1smartAlbumRecentlyAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAssetCollectionSubtypeSmartAlbumRecentlyAdded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollections(with:subtype:options:)/title",
          "value": "fetchAssetCollectionsWithType:subtype:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection~1fetchAssetCollections(with:subtype:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchAssetCollectionsWithType:subtype:options:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phassetcollectionsubtype/smartalbumraw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phassetcollectionsubtype/smartalbumraw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
