{
  "abstract": [
    {
      "text": "The requested Live Photo quality and delivery priority.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/deliveryMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHLivePhotoRequestOptions(py)deliveryMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deliveryMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
        "text": "PHImageRequestOptionsDeliveryMode"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deliveryMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "deliveryMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deliveryMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
              "text": "PHImageRequestOptionsDeliveryMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to tell Photos to provide a Live Photo quickly (possibly sacrificing image quality), to provide a high-quality Live Photo (possibly sacrificing speed), or to provide both automatically if needed. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode": {
      "abstract": [
        {
          "text": "The requested image quality and delivery priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deliveryMode"
        }
      ],
      "role": "symbol",
      "title": "deliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions/deliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode": {
      "abstract": [
        {
          "text": "Options for delivering requested image data, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions/deliveryMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptionsDeliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptionsdeliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of Live Photo assets you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHLivePhotoRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHLivePhotoRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestoptions"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/deliveryMode": {
      "abstract": [
        {
          "text": "The requested Live Photo quality and delivery priority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
          "text": "PHImageRequestOptionsDeliveryMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/deliveryMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deliveryMode"
        }
      ],
      "role": "symbol",
      "title": "deliveryMode",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestoptions/deliverymode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/version": {
      "abstract": [
        {
          "text": "The version of the Live Photo to be requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageRequestOptionsVersion",
          "text": "PHImageRequestOptionsVersion"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/photos/phlivephotorequestoptions/version"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Image-Request-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/version"
      ],
      "title": "Specifying Image Request Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deliveryMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Image-Request-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHLivePhotoRequestOptions/version"
              ],
              "title": "Specifying Image Request Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptionsDeliveryMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PHImageRequestOptionsDeliveryMode",
                    "text": "PHImageRequestOptionsDeliveryMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "deliveryMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions~1deliveryMode/title",
          "value": "deliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions~1deliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/title",
          "value": "PHImageRequestOptionsDeliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptionsDeliveryMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptionsDeliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1deliveryMode/title",
          "value": "deliveryMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions~1deliveryMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deliveryMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/title",
          "value": "PHLivePhotoRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhotoRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHLivePhotoRequestOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phlivephotorequestoptions/deliverymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phlivephotorequestoptions/deliverymode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
