{
  "abstract": [
    {
      "text": "The associated domains for specific services, such as shared web credentials, universal links, and App Clips.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.associated-domains",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.associated-domains"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "Associated Domains Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Associated Domains Entitlement",
        "name": "com.apple.developer.associated-domains",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key specifies a list of domains for each enabled service. Add an associated domain to the list in the following format:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<service>:<fully qualified domain>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Services include:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use this service for shared web credentials.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "webcredentials",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use this service for universal links.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "applinks",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use this service for Handoff.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "activitycontinuation",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Use this service for an App Clip.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "appclips",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In macOS 11 and later and iOS 14 and later, apps request ",
                  "type": "text"
                },
                {
                  "code": "apple-app-site-association",
                  "type": "codeVoice"
                },
                {
                  "text": " files from an Apple-managed content delivery network (CDN) specifically for associated domains, instead of directly from your web server. If the CDN has an old version of the file, or doesn’t already have a copy of the file, it connects to your web server to obtain the latest version.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If you use a private web server, which is unreachable from the public internet, while developing your app, enable the alternate mode feature to bypass the CDN and connect directly to your server. To do this, add a query string to your associated domains entitlement, as shown in the following example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<service>:<fully qualified domain>?mode=<alternate mode>"
          ],
          "syntax": "console",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Where ",
              "type": "text"
            },
            {
              "code": "alternate mode",
              "type": "codeVoice"
            },
            {
              "text": " is one of the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies that only devices in developer mode can access the domain. In this mode, you can use any valid SSL certificate on your web server, including a certificate that the system doesn’t trust. Make sure you don’t expose your users to security issues, such as machine-in-the-middle attacks. As an additional precaution, only apps that you sign with a development profile can use developer mode, and users must opt-in on any device they use.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "developer",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies that only devices using a mobile device management (MDM) profile can access the domain. This mode requires consent from the MDM administrator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "managed",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies that only devices that are in both ",
                        "type": "text"
                      },
                      {
                        "code": "developer",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and ",
                        "type": "text"
                      },
                      {
                        "code": "managed",
                        "type": "codeVoice"
                      },
                      {
                        "text": " modes can access the domain.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "developer+managed",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "To enable associated domains, add the Associated Domains capability to your target in Xcode. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For watchOS apps, you must add the Associated Domains capability to the WatchKit Extension target.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains": {
      "abstract": [
        {
          "text": "The associated domains for specific services, such as shared web credentials, universal links, and App Clips.",
          "type": "text"
        }
      ],
      "ideTitle": "Associated Domains Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
      "kind": "symbol",
      "name": "com.apple.developer.associated-domains",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.associated-domains"
        }
      ],
      "role": "symbol",
      "title": "Associated Domains Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use universal links.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
      "kind": "symbol",
      "name": "com.apple.developer.associated-domains.applinks.read-write",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.associated-domains.applinks.read-write"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.associated-domains.applinks.read-write",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains.applinks.read-write"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use ThreadNetwork.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
      "kind": "symbol",
      "name": "com.apple.developer.networking.manage-thread-network-credentials",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.manage-thread-network-credentials"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.manage-thread-network-credentials",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.manage-thread-network-credentials"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can send or receive IP multicast traffic.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
      "kind": "symbol",
      "name": "com.apple.developer.networking.multicast",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.multicast"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.multicast",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.multicast"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension": {
      "abstract": [
        {
          "text": "The APIs an app can use to customize networking features.",
          "type": "text"
        }
      ],
      "ideTitle": "Network Extensions Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
      "kind": "symbol",
      "name": "com.apple.developer.networking.networkextension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.networkextension"
        }
      ],
      "role": "symbol",
      "title": "Network Extensions Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.networkextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory": {
      "abstract": [
        {
          "text": "The key that defines the app category entitlement to enable Cellular Network Slicing.",
          "type": "text"
        }
      ],
      "ideTitle": "5G Network Slicing App Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
      "kind": "symbol",
      "name": "com.apple.developer.networking.slicing.appcategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.slicing.appcategory"
        }
      ],
      "role": "symbol",
      "title": "5G Network Slicing App Category",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.slicing.appcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory": {
      "abstract": [
        {
          "text": "The key that defines the traffic category entitlement to enable Cellular Network Slicing.",
          "type": "text"
        }
      ],
      "ideTitle": "5G Network Slicing Traffic Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
      "kind": "symbol",
      "name": "com.apple.developer.networking.slicing.trafficcategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.slicing.trafficcategory"
        }
      ],
      "role": "symbol",
      "title": "5G Network Slicing Traffic Category",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.slicing.trafficcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet",
      "kind": "symbol",
      "name": "com.apple.developer.networking.vmnet",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.vmnet"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.vmnet",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.vmnet"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api": {
      "abstract": [
        {
          "text": "The API an app can use to create and control a custom system VPN configuration.",
          "type": "text"
        }
      ],
      "ideTitle": "Personal VPN Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api",
      "kind": "symbol",
      "name": "com.apple.developer.networking.vpn.api",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.vpn.api"
        }
      ],
      "role": "symbol",
      "title": "Personal VPN Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.vpn.api"
    },
    "doc://com.apple.documentation/documentation/AppClip/creating-an-app-clip-with-xcode": {
      "abstract": [
        {
          "text": "Add an App Clip target to your Xcode project and share code between the App Clip and its corresponding full app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppClip/creating-an-app-clip-with-xcode",
      "kind": "article",
      "role": "article",
      "title": "Creating an App Clip with Xcode",
      "type": "topic",
      "url": "/documentation/AppClip/creating-an-app-clip-with-xcode"
    },
    "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app": {
      "abstract": [
        {
          "text": "Configure your target to include and customize capabilities that provide access to Apple’s app services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/adding-capabilities-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding capabilities to your app",
      "type": "topic",
      "url": "/documentation/Xcode/adding-capabilities-to-your-app"
    },
    "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains": {
      "abstract": [
        {
          "text": "Connect your app and a website to provide both a native app and a browser experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
      "kind": "article",
      "role": "article",
      "title": "Supporting associated domains",
      "type": "topic",
      "url": "/documentation/Xcode/supporting-associated-domains"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
        "doc://com.apple.documentation/documentation/AppClip/creating-an-app-clip-with-xcode"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Networking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet"
      ],
      "title": "Networking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Associated Domains Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.associated-domains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Xcode/supporting-associated-domains",
                "doc://com.apple.documentation/documentation/AppClip/creating-an-app-clip-with-xcode"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Networking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet"
              ],
              "title": "Networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.vmnet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.vmnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.vpn.api/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.vpn.api"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.slicing.trafficcategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.slicing.trafficcategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.manage-thread-network-credentials/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.manage-thread-network-credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.multicast/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.multicast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.slicing.appcategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.slicing.appcategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.networkextension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.networkextension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.associated-domains/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.associated-domains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.associated-domains.applinks.read-write/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.associated-domains.applinks.read-write"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
