{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether to match the driver against block storage devices that use custom drivers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.driverkit.family.block-storage-device",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.driverkit.family.block-storage-device"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.driverkit.family.block-storage-device"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.driverkit.family.block-storage-device",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add this entitlement to every BlockStorageDeviceDriverKit driver you create. You must request this entitlement from Apple. For information about how to request the entitlement, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/system-extensions/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports audio functionality.",
          "type": "text"
        }
      ],
      "ideTitle": "DriverKit Audio Family",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.audio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.audio"
        }
      ],
      "role": "symbol",
      "title": "DriverKit Audio Family",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.audio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against block storage devices that use custom drivers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.block-storage-device",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.block-storage-device"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.block-storage-device",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.block-storage-device"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices that support MIDI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.midi",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.midi"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.midi",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.midi"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices that communicate using networking protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.networking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.networking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.networking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.networking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices with SCSI controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.scsicontroller",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.scsicontroller"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.scsicontroller",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.scsicontroller"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices with serial communication interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.serial",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.serial"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.serial",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.serial"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci": {
      "abstract": [
        {
          "text": "An array of PCI device descriptors that your custom driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.transport.pci",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.transport.pci"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.transport.pci",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.pci"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb": {
      "abstract": [
        {
          "text": "An array of dictionaries that identify the USB devices the driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.transport.usb",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.transport.usb"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.transport.usb",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/system-extensions/": {
      "identifier": "https://developer.apple.com/system-extensions/",
      "title": "System Extensions and DriverKit",
      "titleInlineContent": [
        {
          "text": "System Extensions and DriverKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/system-extensions/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "DriverKit-family-entitlements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb"
      ],
      "title": "DriverKit family entitlements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.driverkit.family.block-storage-device"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.block-storage-device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "DriverKit-family-entitlements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb"
              ],
              "title": "DriverKit family entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.networking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.audio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.serial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.serial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.pci/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.pci"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.midi/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.midi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.block-storage-device/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.block-storage-device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.usb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.scsicontroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.scsicontroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.block-storage-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.block-storage-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
