{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether your app can include a link that directs people to a website to make an external purchase.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.storekit.external-purchase-link",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.storekit.external-purchase-link"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.storekit.external-purchase-link"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.storekit.external-purchase-link",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement enables qualifying apps to include a link that directs people using the app to a website to make an external purchase. For more information about qualifying apps and to request this entitlement, see:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/go/?id=storekit-external-purchase-eu",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/storekit-external-entitlement/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-us/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives this entitlement, which is also known as the StoreKit External Purchase Link entitlement, you can add it to your app by opening the project’s ",
              "type": "text"
            },
            {
              "code": ".entitlements",
              "type": "codeVoice"
            },
            {
              "text": " file in Xcode. Then add the following key and set the corresponding value to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<plist>",
            "<dict>",
            "    <key>com.apple.developer.storekit.external-purchase-link</key>",
            "    <true/>",
            "</dict>",
            "</plist>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can link to an external website for account creation or management.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-link.account",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-link.account"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-link.account",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-link.account"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-purchase",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-purchase"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can include a link that directs people to a website to make an external purchase.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase-link",
      "kind": "symbol",
      "name": "com.apple.developer.storekit.external-purchase-link",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.storekit.external-purchase-link"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.storekit.external-purchase-link",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase-link"
    },
    "doc://com.apple.documentation/documentation/StoreKit/external-purchase": {
      "abstract": [
        {
          "text": "Enable qualifying apps to offer external purchases.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/external-purchase",
      "kind": "article",
      "role": "article",
      "title": "External Purchase",
      "type": "topic",
      "url": "/documentation/StoreKit/external-purchase"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/": {
      "identifier": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/",
      "title": "Distributing apps in Russia that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing apps in Russia that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/storekit-external-entitlement-ru/"
    },
    "https://developer.apple.com/go/?id=storekit-external-purchase-eu": {
      "identifier": "https://developer.apple.com/go/?id=storekit-external-purchase-eu",
      "title": "Using alternative payment options on the App Store in the European Union",
      "titleInlineContent": [
        {
          "text": "Using alternative payment options on the App Store in the European Union",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/go/?id=storekit-external-purchase-eu"
    },
    "https://developer.apple.com/support/music-streaming-services-entitlement-eea/": {
      "identifier": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/",
      "title": "Distributing music streaming apps in the EEA that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing music streaming apps in the EEA that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/music-streaming-services-entitlement-eea/"
    },
    "https://developer.apple.com/support/storekit-external-entitlement-us/": {
      "identifier": "https://developer.apple.com/support/storekit-external-entitlement-us/",
      "title": "Distributing apps in the U.S. that provide an external purchase link",
      "titleInlineContent": [
        {
          "text": "Distributing apps in the U.S. that provide an external purchase link",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/storekit-external-entitlement-us/"
    },
    "https://developer.apple.com/support/storekit-external-entitlement/": {
      "identifier": "https://developer.apple.com/support/storekit-external-entitlement/",
      "title": "Distributing dating apps in the Netherlands",
      "titleInlineContent": [
        {
          "text": "Distributing dating apps in the Netherlands",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/storekit-external-entitlement/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "StoreKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase"
      ],
      "title": "StoreKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.1",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.storekit.external-purchase-link"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-purchase-link"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "StoreKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-link.account",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.storekit.external-purchase"
              ],
              "title": "StoreKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-purchase-link/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-purchase-link"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-purchase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-purchase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.storekit.external-link.account/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.storekit.external-link.account"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase-link"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.storekit.external-purchase-link"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
