{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.proximity-reader.identity.display",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.proximity-reader.identity.display"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "ID Verifier - Display Only"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "ID Verifier - Display Only",
        "name": "com.apple.developer.proximity-reader.identity.display",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-identity-presentment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-identity-presentment"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.in-app-identity-presentment",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-identity-presentment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-identity-presentment.merchant-identifiers"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments": {
      "abstract": [
        {
          "text": "A list of merchant IDs your app uses for Apple Pay support.",
          "type": "text"
        }
      ],
      "ideTitle": "Merchant IDs Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-payments",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-payments"
        }
      ],
      "role": "symbol",
      "title": "Merchant IDs Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-payments"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers": {
      "abstract": [
        {
          "text": "A list of identifiers that specify pass types that your app can access in Wallet.",
          "type": "text"
        }
      ],
      "ideTitle": "Pass Type IDs Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.pass-type-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.pass-type-identifiers"
        }
      ],
      "role": "symbol",
      "title": "Pass Type IDs Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.pass-type-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display": {
      "abstract": [],
      "ideTitle": "ID Verifier - Display Only",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display",
      "kind": "symbol",
      "name": "com.apple.developer.proximity-reader.identity.display",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.proximity-reader.identity.display"
        }
      ],
      "role": "symbol",
      "title": "ID Verifier - Display Only",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.display"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read": {
      "abstract": [],
      "ideTitle": "ID Verifier - Data Transfer",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read",
      "kind": "symbol",
      "name": "com.apple.developer.proximity-reader.identity.read",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.proximity-reader.identity.read"
        }
      ],
      "role": "symbol",
      "title": "ID Verifier - Data Transfer",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.read"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Wallet",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read"
      ],
      "title": "Wallet"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ID Verifier - Display Only"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.proximity-reader.identity.display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Wallet",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read"
              ],
              "title": "Wallet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.proximity-reader.identity.display/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.proximity-reader.identity.display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-identity-presentment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-identity-presentment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-identity-presentment.merchant-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-identity-presentment.merchant-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.pass-type-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.pass-type-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.proximity-reader.identity.read/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.proximity-reader.identity.read"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-payments/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-payments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.display"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.display"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
