{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.accessibility.merchant-api-control"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.accessibility.merchant-api-control",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.accessibility.merchant-api-control"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.accessibility.merchant-api-control"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Merchant Accessibility API Control",
        "name": "com.apple.developer.accessibility.merchant-api-control",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.accessibility.merchant-api-control": {
      "abstract": [],
      "ideTitle": "Merchant Accessibility API Control",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.accessibility.merchant-api-control",
      "kind": "symbol",
      "name": "com.apple.developer.accessibility.merchant-api-control",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.accessibility.merchant-api-control"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.accessibility.merchant-api-control",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.accessibility.merchant-api-control"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.accessibility.merchant-api-control"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.accessibility.merchant-api-control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.accessibility.merchant-api-control/title",
          "value": "com.apple.developer.accessibility.merchant-api-control"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.accessibility.merchant-api-control/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.accessibility.merchant-api-control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.accessibility.merchant-api-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.accessibility.merchant-api-control"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
