{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the app creates and manages virtual machines.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.security.hypervisor",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.security.hypervisor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.security.hypervisor"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.security.hypervisor",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The entitlement is required to use the Hypervisor APIs in any process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your app has a deployment target of macOS 10.15 or earlier, add the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " entitlement to your app in addition to this entitlement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app creates and manages virtual machines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor",
      "kind": "symbol",
      "name": "com.apple.security.hypervisor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.hypervisor"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.hypervisor",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.hypervisor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can use the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization",
      "kind": "symbol",
      "name": "com.apple.security.virtualization",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.virtualization"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.virtualization",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.virtualization"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app captures USB devices and uses them in the guest-operating system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
      "kind": "symbol",
      "name": "com.apple.vm.device-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.device-access"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.device-access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.device-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app creates and manages virtual machines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
      "kind": "symbol",
      "name": "com.apple.vm.hypervisor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.hypervisor"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.hypervisor",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.hypervisor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the app manages virtual network interfaces without escalating privileges to the root user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking",
      "kind": "symbol",
      "name": "com.apple.vm.networking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.networking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.networking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.networking"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Hypervisor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization"
      ],
      "title": "Hypervisor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.security.hypervisor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Hypervisor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization"
              ],
              "title": "Hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.networking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.hypervisor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.hypervisor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.device-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.device-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.virtualization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.virtualization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.hypervisor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.hypervisor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
