{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether an app may create an assessment session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.automatic-assessment-configuration",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.automatic-assessment-configuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.automatic-assessment-configuration"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.automatic-assessment-configuration",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AutomaticAssessmentConfiguration/AEAssessmentSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance to put a device into a state that prevents users from accessing certain system features during high-stakes assessment activities, such as administering an exam. Your app needs the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement to create an assessment session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add the entitlement to your app, set the entitlement’s type to Boolean in the Xcode property list editor, and the corresponding value to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3540004",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before your app can use this entitlement, you must first get permission to use it. Request permission by filling in the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/contact/request/automatic-assessment-configuration/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " form.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your app has a deployment target earlier than macOS 11, to use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " entitlement, your app also needs the ",
                  "type": "text"
                },
                {
                  "code": "com.apple.security.temporary-exception.mach-lookup.global-name",
                  "type": "codeVoice"
                },
                {
                  "text": " entitlement. Add this to your app’s entitlements file with a corresponding value that’s an array of strings containing the string ",
                  "type": "text"
                },
                {
                  "code": "com.apple.assessmentagent",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment": {
      "abstract": [
        {
          "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
          "type": "text"
        }
      ],
      "ideTitle": "ClassKit Environment Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
      "kind": "symbol",
      "name": "com.apple.developer.ClassKit-environment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.ClassKit-environment"
        }
      ],
      "role": "symbol",
      "title": "ClassKit Environment Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.classkit-environment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app may create an assessment session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration",
      "kind": "symbol",
      "name": "com.apple.developer.automatic-assessment-configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.automatic-assessment-configuration"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.automatic-assessment-configuration",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.automatic-assessment-configuration"
    },
    "doc://com.apple.documentation/documentation/AutomaticAssessmentConfiguration/AEAssessmentSession": {
      "abstract": [
        {
          "text": "A session that your app uses to protect an assessment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AEAssessmentSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AutomaticAssessmentConfiguration/AEAssessmentSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AEAssessmentSession",
      "type": "topic",
      "url": "/documentation/AutomaticAssessmentConfiguration/AEAssessmentSession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/contact/request/automatic-assessment-configuration/": {
      "identifier": "https://developer.apple.com/contact/request/automatic-assessment-configuration/",
      "title": "Automatic Assessment Configuration Entitlement Request",
      "titleInlineContent": [
        {
          "text": "Automatic Assessment Configuration Entitlement Request",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/automatic-assessment-configuration/"
    },
    "media-3540004": {
      "alt": "A screenshot of Xcode with a project’s entitlements file in the property list editor, showing the com.apple.developer.automatic-assessment-configuration entitlement.",
      "identifier": "media-3540004",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/55ccfc9accd23ff31a26e363d366dfc9/media-3540004@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cacca8643378fecd221ceb76c01fef3b/media-3540004~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Education",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
      ],
      "title": "Education"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.automatic-assessment-configuration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.automatic-assessment-configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Education",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
              ],
              "title": "Education"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.ClassKit-environment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.ClassKit-environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AutomaticAssessmentConfiguration~1AEAssessmentSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AEAssessmentSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.automatic-assessment-configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.automatic-assessment-configuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.automatic-assessment-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.automatic-assessment-configuration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
