{
  "abstract": [
    {
      "text": "The entitlement that enables an app to vend other apps as an alternative app marketplace.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.marketplace.app-installation",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.marketplace.app-installation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.marketplace.app-installation"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.marketplace.app-installation",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system requires that your app have this entitlement to implement an app marketplace and install other apps using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Apple approves your use of this entitlement based on a set of criteria. To request the entitlement, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/support/alternative-app-marketplace-in-the-eu/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives this entitlement, provision your app with the entitlement according to: ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This entitlement isn’t available for Enterprise or Developer ID distributed apps.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation": {
      "abstract": [
        {
          "text": "The entitlement that enables an app to vend other apps as an alternative app marketplace.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation",
      "kind": "symbol",
      "name": "com.apple.developer.marketplace.app-installation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.marketplace.app-installation"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.marketplace.app-installation",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.marketplace.app-installation"
    },
    "doc://com.apple.documentation/documentation/MarketplaceKit": {
      "abstract": [
        {
          "text": "Create an alternative app marketplace, distribute your app on an alternative app marketplace, or distribute your app from your website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MarketplaceKit",
      "type": "topic",
      "url": "/documentation/MarketplaceKit"
    },
    "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace": {
      "abstract": [
        {
          "text": "Enable the distribution of other third-party apps from within your marketplace app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace",
      "kind": "article",
      "role": "article",
      "title": "Creating an alternative app marketplace",
      "type": "topic",
      "url": "/documentation/appdistribution/creating-an-alternative-app-marketplace"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/": {
      "identifier": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/",
      "title": "Provisioning with managed capabilities",
      "titleInlineContent": [
        {
          "text": "Provisioning with managed capabilities",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/"
    },
    "https://developer.apple.com/support/alternative-app-marketplace-in-the-eu/": {
      "identifier": "https://developer.apple.com/support/alternative-app-marketplace-in-the-eu/",
      "title": "Getting started as an alternative app marketplace in the European Union",
      "titleInlineContent": [
        {
          "text": "Getting started as an alternative app marketplace in the European Union",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/alternative-app-marketplace-in-the-eu/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.marketplace.app-installation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.marketplace.app-installation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.marketplace.app-installation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.marketplace.app-installation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.marketplace.app-installation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.marketplace.app-installation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
