{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the app can use Unified Payments Interface (UPI) device enrollment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.upi-device-validation",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.upi-device-validation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.upi-device-validation"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.upi-device-validation",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With this entitlement, you can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/messageui/mfmessagecomposeviewcontroller/4240039-setupiverificationcodesendcomple",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which configures the instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MessageUI/MFMessageComposeViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with non-editable recipients and body fields.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You must be an account holder of a development team to get permission to use this entitlement. To request access, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/contact/request/upi-device-validation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Add the entitlement to your app in the Xcode property list editor. Set the entitlement’s type to Boolean, and the corresponding value to YES.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use Unified Payments Interface (UPI) device enrollment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.upi-device-validation",
      "kind": "symbol",
      "name": "com.apple.developer.upi-device-validation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.upi-device-validation"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.upi-device-validation",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.upi-device-validation"
    },
    "doc://com.apple.documentation/documentation/MessageUI/MFMessageComposeViewController": {
      "abstract": [
        {
          "text": "A standard view controller whose interface lets the user compose and send SMS or MMS messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MFMessageComposeViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MessageUI/MFMessageComposeViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "MFMessageComposeViewController",
      "type": "topic",
      "url": "/documentation/MessageUI/MFMessageComposeViewController"
    },
    "doc://com.apple.documentation/documentation/messageui/mfmessagecomposeviewcontroller/4240039-setupiverificationcodesendcomple": {
      "abstract": [
        {
          "text": "Configures the instance of a view for Unified Payments Interface (UPI) device validation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/messageui/mfmessagecomposeviewcontroller/4240039-setupiverificationcodesendcomple",
      "kind": "symbol",
      "role": "symbol",
      "title": "setUPIVerificationCodeSendCompletion:",
      "type": "topic",
      "url": "/documentation/messageui/mfmessagecomposeviewcontroller/4240039-setupiverificationcodesendcomple"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/contact/request/upi-device-validation": {
      "identifier": "https://developer.apple.com/contact/request/upi-device-validation",
      "title": "UPI device validation Entitlement Request",
      "titleInlineContent": [
        {
          "text": "UPI device validation Entitlement Request",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/upi-device-validation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.upi-device-validation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.upi-device-validation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MessageUI~1MFMessageComposeViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MFMessageComposeViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UINavigationController",
              "text": "UINavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.upi-device-validation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.upi-device-validation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.upi-device-validation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.upi-device-validation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
