{
  "abstract": [
    {
      "text": "A Boolean value indicating whether your app can use the hotspot manager to configure Wi-Fi networks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.networking.HotspotConfiguration",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.networking.HotspotConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "Hotspot Configuration Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Hotspot Configuration Entitlement",
        "name": "com.apple.developer.networking.HotspotConfiguration",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key indicates whether your app may use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes to configure Wi-Fi networks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the Hotspot Configuration capability in Xcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can use the hotspot manager to configure Wi-Fi networks.",
          "type": "text"
        }
      ],
      "ideTitle": "Hotspot Configuration Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration",
      "kind": "symbol",
      "name": "com.apple.developer.networking.HotspotConfiguration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.HotspotConfiguration"
        }
      ],
      "role": "symbol",
      "title": "Hotspot Configuration Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.hotspotconfiguration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may use Multipath protocols to seamlessly transition between Wi-Fi and cellular networks.",
          "type": "text"
        }
      ],
      "ideTitle": "Multipath Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
      "kind": "symbol",
      "name": "com.apple.developer.networking.multipath",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.multipath"
        }
      ],
      "role": "symbol",
      "title": "Multipath Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.multipath"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can access information about the connected Wi-Fi network.",
          "type": "text"
        }
      ],
      "ideTitle": "Access Wi-Fi Information Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
      "kind": "symbol",
      "name": "com.apple.developer.networking.wifi-info",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.wifi-info"
        }
      ],
      "role": "symbol",
      "title": "Access Wi-Fi Information Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.wifi-info"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can use the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can be a default app for contactless NFC with the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce.default-contactless-app",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce.default-contactless-app"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce.default-contactless-app",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce.default-contactless-app"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes": {
      "abstract": [
        {
          "text": "An array of identifier strings the app handles with the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats": {
      "abstract": [
        {
          "text": "The Near Field Communication data formats an app can read.",
          "type": "text"
        }
      ],
      "ideTitle": "Near Field Communication Tag Reader Session Formats Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.readersession.formats",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.readersession.formats"
        }
      ],
      "role": "symbol",
      "title": "Near Field Communication Tag Reader Session Formats Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.readersession.formats"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app may configure MFi Wi-Fi accessories.",
          "type": "text"
        }
      ],
      "ideTitle": "Wireless Accessory Configuration Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
      "kind": "symbol",
      "name": "com.apple.external-accessory.wireless-configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.external-accessory.wireless-configuration"
        }
      ],
      "role": "symbol",
      "title": "Wireless Accessory Configuration Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.external-accessory.wireless-configuration"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfiguration": {
      "abstract": [
        {
          "text": "Configuration settings for a Wi-Fi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEHotspotConfiguration",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEHotspotConfiguration"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationManager": {
      "abstract": [
        {
          "text": "A manager that applies and removes hotspot configurations of Wi-Fi networks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotConfigurationManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotConfigurationManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEHotspotConfigurationManager",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEHotspotConfigurationManager"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotHelper": {
      "abstract": [
        {
          "text": "A class to register a hotspot helper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotHelper"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotHelper",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEHotspotHelper",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEHotspotHelper"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotHelper"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Wireless-interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app"
      ],
      "title": "Wireless interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Hotspot Configuration Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.HotspotConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/NetworkExtension/NEHotspotHelper"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Wireless-interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app"
              ],
              "title": "Wireless interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.external-accessory.wireless-configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.external-accessory.wireless-configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.wifi-info/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.wifi-info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.readersession.formats/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.readersession.formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEHotspotConfigurationManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.multipath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.multipath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.HotspotConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.HotspotConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEHotspotConfiguration/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce.default-contactless-app/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce.default-contactless-app"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEHotspotHelper/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEHotspotHelper"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.networking.hotspotconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.networking.hotspotconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
