{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.embedded-web-browser-engine"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.embedded-web-browser-engine",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.embedded-web-browser-engine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.embedded-web-browser-engine"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.embedded-web-browser-engine",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.embedded-web-browser-engine": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.embedded-web-browser-engine",
      "kind": "symbol",
      "name": "com.apple.developer.embedded-web-browser-engine",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.embedded-web-browser-engine"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.embedded-web-browser-engine",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.embedded-web-browser-engine"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_accept": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_accept",
      "kind": "symbol",
      "name": "com.apple.developer.memory.transfer_accept",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.memory.transfer_accept"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.memory.transfer_accept",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.memory.transfer_accept"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_send": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_send",
      "kind": "symbol",
      "name": "com.apple.developer.memory.transfer_send",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.memory.transfer_send"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.memory.transfer_send",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.memory.transfer_send"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.host": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.host",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser-engine.host",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser-engine.host"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser-engine.host",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser-engine.host"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.networking": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.networking",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser-engine.networking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser-engine.networking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser-engine.networking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser-engine.networking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.rendering": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.rendering",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser-engine.rendering",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser-engine.rendering"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser-engine.rendering",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser-engine.rendering"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.webcontent": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.webcontent",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser-engine.webcontent",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser-engine.webcontent"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser-engine.webcontent",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser-engine.webcontent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "BrowserEngineKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_accept",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_send",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.host",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.networking",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.rendering",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.webcontent"
      ],
      "title": "BrowserEngineKit"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.embedded-web-browser-engine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.embedded-web-browser-engine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "BrowserEngineKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_accept",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.memory.transfer_send",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.host",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.networking",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.rendering",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser-engine.webcontent"
              ],
              "title": "BrowserEngineKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser-engine.webcontent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser-engine.webcontent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.memory.transfer_send/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.memory.transfer_send"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser-engine.host/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser-engine.host"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.memory.transfer_accept/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.memory.transfer_accept"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.embedded-web-browser-engine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.embedded-web-browser-engine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser-engine.rendering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser-engine.rendering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser-engine.networking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser-engine.networking"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.embedded-web-browser-engine"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.embedded-web-browser-engine"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
