{
  "abstract": [
    {
      "text": "An array of dictionaries that identify the USB devices the driver supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.driverkit.transport.usb",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.driverkit.transport.usb"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "com.apple.developer.driverkit.transport.usb"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.driverkit.transport.usb",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "dictionary "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each element in the array is a dictionary whose keys and values identify a specific type of supported device. The keys in the dictionary correspond to field names of the device descriptor associated with the USB device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device supports audio functionality.",
          "type": "text"
        }
      ],
      "ideTitle": "DriverKit Audio Family",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.audio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.audio"
        }
      ],
      "role": "symbol",
      "title": "DriverKit Audio Family",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.audio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against block storage devices that use custom drivers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.block-storage-device",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.block-storage-device"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.block-storage-device",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.block-storage-device"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices that support MIDI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.midi",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.midi"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.midi",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.midi"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices that communicate using networking protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.networking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.networking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.networking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.networking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices with SCSI controllers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.scsicontroller",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.scsicontroller"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.scsicontroller",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.scsicontroller"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to match the driver against devices with serial communication interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.family.serial",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.family.serial"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.family.serial",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.family.serial"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci": {
      "abstract": [
        {
          "text": "An array of PCI device descriptors that your custom driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.transport.pci",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.transport.pci"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.transport.pci",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.pci"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb": {
      "abstract": [
        {
          "text": "An array of dictionaries that identify the USB devices the driver supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb",
      "kind": "symbol",
      "name": "com.apple.developer.driverkit.transport.usb",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.driverkit.transport.usb"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.driverkit.transport.usb",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bConfigurationValue": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bConfigurationValue",
      "kind": "symbol",
      "name": "bConfigurationValue",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bConfigurationValue"
        }
      ],
      "role": "symbol",
      "title": "bConfigurationValue",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/bconfigurationvalue"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceClass": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceClass",
      "kind": "symbol",
      "name": "bDeviceClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bDeviceClass"
        }
      ],
      "role": "symbol",
      "title": "bDeviceClass",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/bdeviceclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceProtocol": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceProtocol",
      "kind": "symbol",
      "name": "bDeviceProtocol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bDeviceProtocol"
        }
      ],
      "role": "symbol",
      "title": "bDeviceProtocol",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/bdeviceprotocol"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceSubClass": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceSubClass",
      "kind": "symbol",
      "name": "bDeviceSubClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bDeviceSubClass"
        }
      ],
      "role": "symbol",
      "title": "bDeviceSubClass",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/bdevicesubclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceClass": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceClass",
      "kind": "symbol",
      "name": "bInterfaceClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bInterfaceClass"
        }
      ],
      "role": "symbol",
      "title": "bInterfaceClass",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/binterfaceclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceNumber": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceNumber",
      "kind": "symbol",
      "name": "bInterfaceNumber",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bInterfaceNumber"
        }
      ],
      "role": "symbol",
      "title": "bInterfaceNumber",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/binterfacenumber"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceProtocol": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceProtocol",
      "kind": "symbol",
      "name": "bInterfaceProtocol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bInterfaceProtocol"
        }
      ],
      "role": "symbol",
      "title": "bInterfaceProtocol",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/binterfaceprotocol"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceSubClass": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceSubClass",
      "kind": "symbol",
      "name": "bInterfaceSubClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bInterfaceSubClass"
        }
      ],
      "role": "symbol",
      "title": "bInterfaceSubClass",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/binterfacesubclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bcdDevice": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bcdDevice",
      "kind": "symbol",
      "name": "bcdDevice",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bcdDevice"
        }
      ],
      "role": "symbol",
      "title": "bcdDevice",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/bcddevice"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProduct": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProduct",
      "kind": "symbol",
      "name": "idProduct",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "idProduct"
        }
      ],
      "role": "symbol",
      "title": "idProduct",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/idproduct"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductArray": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductArray",
      "kind": "symbol",
      "name": "idProductArray",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "idProductArray"
        }
      ],
      "role": "symbol",
      "title": "idProductArray",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/idproductarray"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductMask": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductMask",
      "kind": "symbol",
      "name": "idProductMask",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "idProductMask"
        }
      ],
      "role": "symbol",
      "title": "idProductMask",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/idproductmask"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idVendor": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idVendor",
      "kind": "symbol",
      "name": "idVendor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "idVendor"
        }
      ],
      "role": "symbol",
      "title": "idVendor",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb/idvendor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "DriverKit-family-entitlements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci"
      ],
      "title": "DriverKit family entitlements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Property-List-Keys",
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bConfigurationValue",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceProtocol",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceSubClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceNumber",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceProtocol",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceSubClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bcdDevice",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProduct",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductArray",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductMask",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idVendor"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.driverkit.transport.usb"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.usb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bConfigurationValue",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceProtocol",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bDeviceSubClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceNumber",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceProtocol",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bInterfaceSubClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/bcdDevice",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProduct",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductArray",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idProductMask",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.usb/idVendor"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "DriverKit-family-entitlements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.audio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.block-storage-device",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.midi",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.networking",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.scsicontroller",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.family.serial",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.driverkit.transport.pci"
              ],
              "title": "DriverKit family entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.midi/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.midi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bDeviceClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bDeviceClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.networking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bInterfaceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bInterfaceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bDeviceProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bDeviceProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.serial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.serial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bInterfaceSubClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bInterfaceSubClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.usb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bInterfaceClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bInterfaceClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.pci/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.transport.pci"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bInterfaceNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bInterfaceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1idProduct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "idProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.scsicontroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.scsicontroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.audio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bDeviceSubClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bDeviceSubClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1idProductArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "idProductArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bConfigurationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bConfigurationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.family.block-storage-device/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.driverkit.family.block-storage-device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1idProductMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "idProductMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1idVendor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "idVendor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.driverkit.transport.usb~1bcdDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bcdDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.driverkit.transport.usb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
