{
  "abstract": [
    {
      "text": "The entitlement that enables a browser to install alternative-distribution apps from a website.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.browser.app-installation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.browser.app-installation",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.browser.app-installation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.browser.app-installation"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.browser.app-installation",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system requires that your browser app have this entitlement to install alternative marketplace apps from a webpage using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Browser apps that render with either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/WebKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " need the entitlement. Apple enables it on your account along with the default browser entitlement (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Request the default browser entitlement by filling out the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/contact/request/default-browser-entitlement/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". In that form you can also request this entitlement. If you do that and your request for the default browser entitlement is accepted you get both the default browser entitlement and the app-installation entitlement for your browser app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Your browser app needs to enforce specific webpage criteria as part of using this entitlement. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/appdistribution/enabling-alternative-distribution-app-installation-in-a-browser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your account receives this entitlement, provision your app with the entitlement according to: ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This entitlement isn’t available for Enterprise or Developer ID distributed apps.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.browser.app-installation": {
      "abstract": [
        {
          "text": "The entitlement that enables a browser to install alternative-distribution apps from a website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.browser.app-installation",
      "kind": "symbol",
      "name": "com.apple.developer.browser.app-installation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.browser.app-installation"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.browser.app-installation",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.browser.app-installation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the app can act as the user’s default web browser.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser.public-key-credential": {
      "abstract": [
        {
          "text": "A Boolean value that lets your app make registration and assertion requests for passkeys and security keys for any relying party identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser.public-key-credential",
      "kind": "symbol",
      "name": "com.apple.developer.web-browser.public-key-credential",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.web-browser.public-key-credential"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.web-browser.public-key-credential",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.web-browser.public-key-credential"
    },
    "doc://com.apple.documentation/documentation/BrowserEngineKit": {
      "abstract": [
        {
          "text": "Create a browser that renders content using an alternative browser engine.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BrowserEngineKit",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineKit",
      "type": "topic",
      "url": "/documentation/BrowserEngineKit"
    },
    "doc://com.apple.documentation/documentation/MarketplaceKit": {
      "abstract": [
        {
          "text": "Create an alternative app marketplace, distribute your app on an alternative app marketplace, or distribute your app from your website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MarketplaceKit",
      "type": "topic",
      "url": "/documentation/MarketplaceKit"
    },
    "doc://com.apple.documentation/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/WebKit"
    },
    "doc://com.apple.documentation/documentation/appdistribution/enabling-alternative-distribution-app-installation-in-a-browser": {
      "abstract": [
        {
          "text": "Add support for browser apps to install alternative distribution apps from websites.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appdistribution/enabling-alternative-distribution-app-installation-in-a-browser",
      "kind": "article",
      "role": "article",
      "title": "Enabling alternative distribution app installation in a browser",
      "type": "topic",
      "url": "/documentation/appdistribution/enabling-alternative-distribution-app-installation-in-a-browser"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/contact/request/default-browser-entitlement/": {
      "identifier": "https://developer.apple.com/contact/request/default-browser-entitlement/",
      "title": "Default browser entitlement request form",
      "titleInlineContent": [
        {
          "text": "Default browser entitlement request form",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/contact/request/default-browser-entitlement/"
    },
    "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/": {
      "identifier": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/",
      "title": "Provisioning with managed capabilities",
      "titleInlineContent": [
        {
          "text": "Provisioning with managed capabilities",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/help/account/reference/provisioning-with-managed-capabilities/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Web-browsers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser.public-key-credential"
      ],
      "title": "Web browsers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.browser.app-installation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.browser.app-installation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Web-browsers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.web-browser.public-key-credential"
              ],
              "title": "Web browsers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.web-browser.public-key-credential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.web-browser.public-key-credential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.browser.app-installation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.browser.app-installation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.browser.app-installation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.browser.app-installation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
