{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether an app can use ARKit to detect, position, and decode barcode and QR codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.arkit.barcode-detection.allow",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.arkit.barcode-detection.allow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "Spatial barcode and QR code scanning"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Spatial barcode and QR code scanning",
        "name": "com.apple.developer.arkit.barcode-detection.allow",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Spatial barcode & QR code scanning are only available in an immersive space. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to learn more about opening an immersive space and requesting authorization for ARKit data access. To learn more about best practices for privacy, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/visionOS/adopting-best-practices-for-privacy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category": {
      "abstract": [
        {
          "text": "An entitlement that allows an app to adjust thresholds that balance thermal dissipation and performance against fan noise and other factors.",
          "type": "text"
        }
      ],
      "ideTitle": "Increased performance headroom",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
      "kind": "symbol",
      "name": "com.apple.developer.app-compute-category",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.app-compute-category"
        }
      ],
      "role": "symbol",
      "title": "Increased performance headroom",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.app-compute-category"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use ARKit to detect, position, and decode barcode and QR codes.",
          "type": "text"
        }
      ],
      "ideTitle": "Spatial barcode and QR code scanning",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.barcode-detection.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.barcode-detection.allow"
        }
      ],
      "role": "symbol",
      "title": "Spatial barcode and QR code scanning",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.barcode-detection.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use ARKit to access the main cameras on Apple Vision Pro.",
          "type": "text"
        }
      ],
      "ideTitle": "Main camera access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.main-camera-access.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.main-camera-access.allow"
        }
      ],
      "role": "symbol",
      "title": "Main camera access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.main-camera-access.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow": {
      "abstract": [
        {
          "text": "A Boolean value that allows an app to use ARKit to track more objects with a higher frequency.",
          "type": "text"
        }
      ],
      "ideTitle": "Object-tracking parameter adjustment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
        }
      ],
      "role": "symbol",
      "title": "Object-tracking parameter adjustment",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can stream USB UVC devices connected to the Developer strap.",
          "type": "text"
        }
      ],
      "ideTitle": "UVC Device Access on visionOS",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access",
      "kind": "symbol",
      "name": "com.apple.developer.avfoundation.uvc-device-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.avfoundation.uvc-device-access"
        }
      ],
      "role": "symbol",
      "title": "UVC Device Access on visionOS",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.avfoundation.uvc-device-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use the Apple Neural Engine to speed up CoreML.",
          "type": "text"
        }
      ],
      "ideTitle": "Apple Neural Engine access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
      "kind": "symbol",
      "name": "com.apple.developer.coreml.neural-engine-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.coreml.neural-engine-access"
        }
      ],
      "role": "symbol",
      "title": "Apple Neural Engine access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.coreml.neural-engine-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can include passthrough in screen capture.",
          "type": "text"
        }
      ],
      "ideTitle": "Passthrough in screen capture",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
      "kind": "symbol",
      "name": "com.apple.developer.screen-capture.include-passthrough",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.screen-capture.include-passthrough"
        }
      ],
      "role": "symbol",
      "title": "Passthrough in screen capture",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.screen-capture.include-passthrough"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/adopting-best-practices-for-privacy": {
      "abstract": [
        {
          "text": "Minimize your use of sensitive information and provide a clear statement of what information you do use and how you use it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/adopting-best-practices-for-privacy",
      "kind": "article",
      "role": "article",
      "title": "Adopting best practices for privacy and user preferences",
      "type": "topic",
      "url": "/documentation/visionOS/adopting-best-practices-for-privacy"
    },
    "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data": {
      "abstract": [
        {
          "text": "Check whether your app can use ARKit and respect people’s privacy.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/setting-up-access-to-arkit-data",
      "kind": "article",
      "role": "article",
      "title": "Setting up access to ARKit data",
      "type": "topic",
      "url": "/documentation/visionOS/setting-up-access-to-arkit-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enterprise",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access"
      ],
      "title": "Enterprise"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Spatial barcode and QR code scanning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.barcode-detection.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enterprise",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access"
              ],
              "title": "Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.screen-capture.include-passthrough/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.screen-capture.include-passthrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.main-camera-access.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.main-camera-access.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.avfoundation.uvc-device-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.avfoundation.uvc-device-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.app-compute-category/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.app-compute-category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.barcode-detection.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.barcode-detection.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.coreml.neural-engine-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.coreml.neural-engine-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.object-tracking-parameter-adjustment.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.arkit.barcode-detection.allow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.arkit.barcode-detection.allow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
