{
  "abstract": [
    {
      "text": "The container identifiers for the iCloud production environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.icloud-container-identifiers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.icloud-container-identifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "iCloud Container Identifiers Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "iCloud Container Identifiers Entitlement",
        "name": "com.apple.developer.icloud-container-identifiers",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the iCloud capability in Xcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-development-container-identifiers": {
      "abstract": [
        {
          "text": "The container identifiers for the iCloud development environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-development-container-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.icloud-container-development-container-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.icloud-container-development-container-identifiers"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.icloud-container-development-container-identifiers",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.icloud-container-development-container-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-environment": {
      "abstract": [
        {
          "text": "The development or production environment to use for the iCloud containers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-environment",
      "kind": "symbol",
      "name": "com.apple.developer.icloud-container-environment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.icloud-container-environment"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.icloud-container-environment",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.icloud-container-environment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers": {
      "abstract": [
        {
          "text": "The container identifiers for the iCloud production environment.",
          "type": "text"
        }
      ],
      "ideTitle": "iCloud Container Identifiers Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.icloud-container-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.icloud-container-identifiers"
        }
      ],
      "role": "symbol",
      "title": "iCloud Container Identifiers Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.icloud-container-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services": {
      "abstract": [
        {
          "text": "The iCloud services used by the app.",
          "type": "text"
        }
      ],
      "ideTitle": "iCloud Services Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services",
      "kind": "symbol",
      "name": "com.apple.developer.icloud-services",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.icloud-services"
        }
      ],
      "role": "symbol",
      "title": "iCloud Services Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.icloud-services"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier": {
      "abstract": [
        {
          "text": "The container identifier to use for iCloud key-value storage.",
          "type": "text"
        }
      ],
      "ideTitle": "iCloud Key-Value Store Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier",
      "kind": "symbol",
      "name": "com.apple.developer.ubiquity-kvstore-identifier",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.ubiquity-kvstore-identifier"
        }
      ],
      "role": "symbol",
      "title": "iCloud Key-Value Store Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.ubiquity-kvstore-identifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iCloud",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-development-container-identifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-environment",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier"
      ],
      "title": "iCloud"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "iCloud Container Identifiers Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.icloud-container-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "iCloud",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-development-container-identifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-container-environment",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.icloud-services",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ubiquity-kvstore-identifier"
              ],
              "title": "iCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.icloud-container-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.icloud-container-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.icloud-container-development-container-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.icloud-container-development-container-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.icloud-services/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.icloud-services"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.ubiquity-kvstore-identifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.ubiquity-kvstore-identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.icloud-container-environment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.icloud-container-environment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.icloud-container-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.icloud-container-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
