{
  "abstract": [
    {
      "text": "A Boolean value indicating whether your app may interact with USB devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.usb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.security.device.usb",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.security.device.usb"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.security.device.usb"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.security.device.usb",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key to allow your sandboxed app to interact with USB devices through USB device access APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the App Sandbox capability in Xcode, and under Hardware, select USB.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.app-sandbox": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may use access control technology to contain damage to the system and user data if an app is compromised.",
          "type": "text"
        }
      ],
      "ideTitle": "App Sandbox Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.app-sandbox",
      "kind": "symbol",
      "name": "com.apple.security.app-sandbox",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.app-sandbox"
        }
      ],
      "role": "symbol",
      "title": "App Sandbox Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.app-sandbox"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.bluetooth": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may interact with Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.bluetooth",
      "kind": "symbol",
      "name": "com.apple.security.device.bluetooth",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.device.bluetooth"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.device.bluetooth",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.device.bluetooth"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.camera": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may interact with the built-in and external cameras, and capture movies and still images.",
          "type": "text"
        }
      ],
      "ideTitle": "Camera Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
      "kind": "symbol",
      "name": "com.apple.security.device.camera",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.device.camera"
        }
      ],
      "role": "symbol",
      "title": "Camera entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.device.camera"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.microphone": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may use the microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.microphone",
      "kind": "symbol",
      "name": "com.apple.security.device.microphone",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.device.microphone"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.device.microphone",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.device.microphone"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.usb": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may interact with USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.usb",
      "kind": "symbol",
      "name": "com.apple.security.device.usb",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.device.usb"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.device.usb",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.device.usb"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-only": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-only access to the Downloads folder.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-only",
      "kind": "symbol",
      "name": "com.apple.security.files.downloads.read-only",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.files.downloads.read-only"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.files.downloads.read-only",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.files.downloads.read-only"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-write": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to the Downloads folder.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-write",
      "kind": "symbol",
      "name": "com.apple.security.files.downloads.read-write",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.files.downloads.read-write"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.files.downloads.read-write",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.files.downloads.read-write"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-only": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-only access to files the user has selected using an Open or Save dialog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-only",
      "kind": "symbol",
      "name": "com.apple.security.files.user-selected.read-only",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.files.user-selected.read-only"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.files.user-selected.read-only",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.files.user-selected.read-only"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to files the user has selected using an Open or Save dialog.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write",
      "kind": "symbol",
      "name": "com.apple.security.files.user-selected.read-write",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.files.user-selected.read-write"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.files.user-selected.read-write",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.files.user-selected.read-write"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.client": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may open outgoing network connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.client",
      "kind": "symbol",
      "name": "com.apple.security.network.client",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.network.client"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.network.client",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.network.client"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.server": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may listen for incoming network connections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.server",
      "kind": "symbol",
      "name": "com.apple.security.network.server",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.network.server"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.network.server",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.network.server"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to contacts in the user’s address book.",
          "type": "text"
        }
      ],
      "ideTitle": "Address Book Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
      "kind": "symbol",
      "name": "com.apple.security.personal-information.addressbook",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.personal-information.addressbook"
        }
      ],
      "role": "symbol",
      "title": "Address book entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.personal-information.addressbook"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may have read-write access to the user’s calendar.",
          "type": "text"
        }
      ],
      "ideTitle": "Calendars Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
      "kind": "symbol",
      "name": "com.apple.security.personal-information.calendars",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.personal-information.calendars"
        }
      ],
      "role": "symbol",
      "title": "Calendars entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.personal-information.calendars"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may access location information from Location Services.",
          "type": "text"
        }
      ],
      "ideTitle": "Location Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
      "kind": "symbol",
      "name": "com.apple.security.personal-information.location",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.personal-information.location"
        }
      ],
      "role": "symbol",
      "title": "Location entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.personal-information.location"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may print a document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print",
      "kind": "symbol",
      "name": "com.apple.security.print",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.print"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.print",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.print"
    },
    "doc://com.apple.documentation/documentation/Security/app-sandbox": {
      "abstract": [
        {
          "text": "Restrict access to system resources and user data in macOS apps to contain damage if an app becomes compromised.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/app-sandbox",
      "kind": "article",
      "role": "article",
      "title": "App Sandbox",
      "type": "topic",
      "url": "/documentation/Security/app-sandbox"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Security",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Security/app-sandbox",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.app-sandbox",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.server",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.client",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.microphone",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.bluetooth",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-only",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-only",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-write"
      ],
      "title": "Security"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.security.device.usb"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.device.usb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Security",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/Security/app-sandbox",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.app-sandbox",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.server",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.network.client",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.camera",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.microphone",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.print",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.device.bluetooth",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.addressbook",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.location",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.personal-information.calendars",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-only",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.user-selected.read-write",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-only",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.files.downloads.read-write"
              ],
              "title": "Security"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.user-selected.read-only/title",
          "value": "com.apple.security.files.user-selected.read-only"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.user-selected.read-only/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.files.user-selected.read-only"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.usb/title",
          "value": "com.apple.security.device.usb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.usb/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.device.usb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.microphone/title",
          "value": "com.apple.security.device.microphone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.microphone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.device.microphone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.personal-information.location/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.personal-information.location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.bluetooth/title",
          "value": "com.apple.security.device.bluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.bluetooth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.device.bluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.network.server/title",
          "value": "com.apple.security.network.server"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.network.server/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.network.server"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.personal-information.calendars/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.personal-information.calendars"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.print/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.print"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.device.camera/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.device.camera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.user-selected.read-write/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.files.user-selected.read-write"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.downloads.read-write/title",
          "value": "com.apple.security.files.downloads.read-write"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.downloads.read-write/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.files.downloads.read-write"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.app-sandbox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.app-sandbox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.personal-information.addressbook/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.personal-information.addressbook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.downloads.read-only/title",
          "value": "com.apple.security.files.downloads.read-only"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.files.downloads.read-only/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.files.downloads.read-only"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.network.client/title",
          "value": "com.apple.security.network.client"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.network.client/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.network.client"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.device.usb"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.device.usb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
