{
  "abstract": [
    {
      "text": "A list of identifiers that specify pass types that your app can access in Wallet.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.pass-type-identifiers",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.pass-type-identifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "Pass Type IDs Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Pass Type IDs Entitlement",
        "name": "com.apple.developer.pass-type-identifiers",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value for this key is an array of pass type identifiers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the Wallet capability in Xcode. If your provisioning profile is associated with multiple pass type identifiers, specify which of the identifiers your app can interact with. Use ",
              "type": "text"
            },
            {
              "code": "$(TeamIdentifierPrefix)*",
              "type": "codeVoice"
            },
            {
              "text": " to access all of the passes for your team.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devfc3f493bb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In iOS 17 and later, App Clips can use the Wallet capability. For more information on functionality that’s available to App Clips, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-identity-presentment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-identity-presentment"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.in-app-identity-presentment",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-identity-presentment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-identity-presentment.merchant-identifiers"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.in-app-identity-presentment.merchant-identifiers",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments": {
      "abstract": [
        {
          "text": "A list of merchant IDs your app uses for Apple Pay support.",
          "type": "text"
        }
      ],
      "ideTitle": "Merchant IDs Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
      "kind": "symbol",
      "name": "com.apple.developer.in-app-payments",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.in-app-payments"
        }
      ],
      "role": "symbol",
      "title": "Merchant IDs Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.in-app-payments"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers": {
      "abstract": [
        {
          "text": "A list of identifiers that specify pass types that your app can access in Wallet.",
          "type": "text"
        }
      ],
      "ideTitle": "Pass Type IDs Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.pass-type-identifiers",
      "kind": "symbol",
      "name": "com.apple.developer.pass-type-identifiers",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.pass-type-identifiers"
        }
      ],
      "role": "symbol",
      "title": "Pass Type IDs Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.pass-type-identifiers"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display": {
      "abstract": [],
      "ideTitle": "ID Verifier - Display Only",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display",
      "kind": "symbol",
      "name": "com.apple.developer.proximity-reader.identity.display",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.proximity-reader.identity.display"
        }
      ],
      "role": "symbol",
      "title": "ID Verifier - Display Only",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.display"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read": {
      "abstract": [],
      "ideTitle": "ID Verifier - Data Transfer",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read",
      "kind": "symbol",
      "name": "com.apple.developer.proximity-reader.identity.read",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.proximity-reader.identity.read"
        }
      ],
      "role": "symbol",
      "title": "ID Verifier - Data Transfer",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.proximity-reader.identity.read"
    },
    "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip": {
      "abstract": [
        {
          "text": "Review frameworks available to App Clips and identify functionality that makes a great App Clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip",
      "kind": "article",
      "role": "article",
      "title": "Choosing the right functionality for your App Clip",
      "type": "topic",
      "url": "/documentation/AppClip/choosing-the-right-functionality-for-your-app-clip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/xcode/mac/current/#/devfc3f493bb": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devfc3f493bb",
      "title": "Configure Wallet (iOS, watchOS)",
      "titleInlineContent": [
        {
          "text": "Configure Wallet (iOS, watchOS)",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devfc3f493bb"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Wallet",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read"
      ],
      "title": "Wallet"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Pass Type IDs Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.pass-type-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Wallet",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-payments",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.in-app-identity-presentment.merchant-identifiers",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.display",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.proximity-reader.identity.read"
              ],
              "title": "Wallet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-identity-presentment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-identity-presentment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.pass-type-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.pass-type-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-identity-presentment.merchant-identifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-identity-presentment.merchant-identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.in-app-payments/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.in-app-payments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.proximity-reader.identity.display/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.proximity-reader.identity.display"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.proximity-reader.identity.read/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.proximity-reader.identity.read"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.pass-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.pass-type-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
