{
  "abstract": [
    {
      "text": "The necessary entitlement to access sensor data that’s required by your app’s preapproved research study.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.sensorkit.reader.allow",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.sensorkit.reader.allow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.sensorkit.reader.allow"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.sensorkit.reader.allow",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that describes the watch’s position on the wrist.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "on-wrist"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides ambient light information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ambient-light-sensor"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides acceleration motion data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "motion-accelerometer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides rotation motion data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "motion-rotation-rate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides information about the user’s frequently visited locations.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "visits"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides information about the user’s steps.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pedometer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides information about the user’s device usage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "device-usage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides information about the user’s Messages app usage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "messages-usage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that reports the amount of time that the user is on phone calls.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "phone-usage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides information about the user’s keyboard usage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "keyboard-metrics"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides data describing a user’s speech during phone calls.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "speech-metrics-telephony"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that provides data describing a user’s speech to Siri.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "speech-metrics-siri"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A sensor that describes the pressure and temperature of the user’s environment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ambient-pressure"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An app can read sensor data from devices on a per-team basis, and the system closes your app if its code signature lacks this entitlement. To attain it, submit your research study to Apple as described in ",
              "type": "text"
            },
            {
              "identifier": "https://www.researchandcare.org/resources/accessing-sensorkit-data/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If Apple approves your study, you can create a provisioning profile that signs code with this entitlement. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow": {
      "abstract": [
        {
          "text": "The necessary entitlement to access sensor data that’s required by your app’s preapproved research study.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.sensorkit.reader.allow",
      "kind": "symbol",
      "name": "com.apple.developer.sensorkit.reader.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.sensorkit.reader.allow"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.sensorkit.reader.allow",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.sensorkit.reader.allow"
    },
    "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading": {
      "abstract": [
        {
          "text": "Add metadata to your app to attain system and user permission to access sensor data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/configuring-your-project-for-sensor-reading",
      "kind": "article",
      "role": "article",
      "title": "Configuring your project for sensor reading",
      "type": "topic",
      "url": "/documentation/SensorKit/configuring-your-project-for-sensor-reading"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://www.researchandcare.org/resources/accessing-sensorkit-data/": {
      "identifier": "https://www.researchandcare.org/resources/accessing-sensorkit-data/",
      "title": "Accessing SensorKit Data",
      "titleInlineContent": [
        {
          "text": "Accessing SensorKit Data",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.researchandcare.org/resources/accessing-sensorkit-data/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.sensorkit.reader.allow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.sensorkit.reader.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.sensorkit.reader.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.sensorkit.reader.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.sensorkit.reader.allow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.sensorkit.reader.allow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
