{
  "abstract": [
    {
      "text": "A Boolean value that determines whether your app can recalibrate the prediction algorithm used to calculate supported sample types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.recalibrate-estimates"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.healthkit.recalibrate-estimates",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.healthkit.recalibrate-estimates"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.healthkit.recalibrate-estimates"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.healthkit.recalibrate-estimates",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps can recalibrate HealthKitʼs prediction algorithms after an event that may significantly affect their results. For example, you can recalibrate the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3552083-sixminutewalktestdistance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type to use only data collected after a mobility-impacting health event, such as surgery or an injury.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To check whether a sample type supports recalibration, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/healthkit/hksampletype/3801678-allowsrecalibrationforestimates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To recalibrate the sample, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/3801677-recalibrateestimates",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may request user authorization to access health and activity data that appears in the Health app.",
          "type": "text"
        }
      ],
      "ideTitle": "HealthKit Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit",
      "kind": "symbol",
      "name": "com.apple.developer.healthkit",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.healthkit"
        }
      ],
      "role": "symbol",
      "title": "HealthKit Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.healthkit"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.access": {
      "abstract": [
        {
          "text": "Health data types that require additional permission.",
          "type": "text"
        }
      ],
      "ideTitle": "HealthKit Capabilities Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.access",
      "kind": "symbol",
      "name": "com.apple.developer.healthkit.access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.healthkit.access"
        }
      ],
      "role": "symbol",
      "title": "HealthKit Capabilities Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.healthkit.access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.background-delivery": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether observer queries receive updates while running in the background.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.background-delivery",
      "kind": "symbol",
      "name": "com.apple.developer.healthkit.background-delivery",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.healthkit.background-delivery"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.healthkit.background-delivery",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.healthkit.background-delivery"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.recalibrate-estimates": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether your app can recalibrate the prediction algorithm used to calculate supported sample types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.recalibrate-estimates",
      "kind": "symbol",
      "name": "com.apple.developer.healthkit.recalibrate-estimates",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.healthkit.recalibrate-estimates"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.healthkit.recalibrate-estimates",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.healthkit.recalibrate-estimates"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/3801677-recalibrateestimates": {
      "abstract": [
        {
          "text": "Recalibrates the prediction algorithm used to calculate the specified sample type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "recalibrateEstimates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "sampleType"
        },
        {
          "kind": "text",
          "text": ": HKSampleType, "
        },
        {
          "kind": "identifier",
          "text": "date"
        },
        {
          "kind": "text",
          "text": ": Date, "
        },
        {
          "kind": "identifier",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (Bool, (any Error)?) -> Void)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/3801677-recalibrateestimates",
      "kind": "symbol",
      "role": "symbol",
      "title": "recalibrateEstimates(sampleType:date:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/3801677-recalibrateestimates"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3552083-sixminutewalktestdistance": {
      "abstract": [
        {
          "text": "A quantity sample type that stores the distance a user can walk during a six-minute walk test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "sixMinuteWalkTestDistance"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3552083-sixminutewalktestdistance",
      "kind": "symbol",
      "role": "symbol",
      "title": "sixMinuteWalkTestDistance",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/3552083-sixminutewalktestdistance"
    },
    "doc://com.apple.documentation/documentation/healthkit/hksampletype/3801678-allowsrecalibrationforestimates": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether HealthKit supports recalibrating the prediction algorithm used to produce estimates for this sample type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "allowsRecalibrationForEstimates"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hksampletype/3801678-allowsrecalibrationforestimates",
      "kind": "symbol",
      "role": "symbol",
      "title": "allowsRecalibrationForEstimates",
      "type": "topic",
      "url": "/documentation/healthkit/hksampletype/3801678-allowsrecalibrationforestimates"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Health",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.access",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.background-delivery"
      ],
      "title": "Health"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.healthkit.recalibrate-estimates"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.healthkit.recalibrate-estimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Health",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.access",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.healthkit.background-delivery"
              ],
              "title": "Health"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkhealthstore~13801677-recalibrateestimates/title",
          "value": "recalibrateEstimatesForSampleType:atDate:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~13552083-sixminutewalktestdistance/title",
          "value": "HKQuantityTypeIdentifierSixMinuteWalkTestDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.healthkit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.healthkit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.healthkit.access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.healthkit.access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.healthkit.recalibrate-estimates/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.healthkit.recalibrate-estimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.healthkit.background-delivery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.healthkit.background-delivery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.healthkit.recalibrate-estimates"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.healthkit.recalibrate-estimates"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
