{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-messaging"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.carplay-messaging",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.carplay-messaging"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.carplay-messaging"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.carplay-messaging",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-audio": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-audio",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-audio",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-audio"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-audio",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-audio"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-charging": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-charging",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-charging",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-charging"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-charging",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-charging"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-communication": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-communication",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-communication",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-communication"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-communication",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-communication"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-maps": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-maps",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-maps",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-maps"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-maps",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-maps"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-messaging": {
      "abstract": [],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-messaging",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-messaging",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-messaging"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-messaging",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-messaging"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-parking": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-parking",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-parking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-parking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-parking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-parking"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-quick-ordering": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-quick-ordering",
      "kind": "symbol",
      "name": "com.apple.developer.carplay-quick-ordering",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.carplay-quick-ordering"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.carplay-quick-ordering",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.carplay-quick-ordering"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.playable-content": {
      "abstract": [],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.playable-content",
      "kind": "symbol",
      "name": "com.apple.developer.playable-content",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.playable-content"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.playable-content",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.playable-content"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-audio",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-charging",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-communication",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-maps",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-parking",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-quick-ordering",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.playable-content"
      ],
      "title": "CarPlay"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.carplay-messaging"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-messaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-audio",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-charging",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-communication",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-maps",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-parking",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.carplay-quick-ordering",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.playable-content"
              ],
              "title": "CarPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-parking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-parking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.playable-content/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.playable-content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-audio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-quick-ordering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-quick-ordering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-charging/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-charging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-maps/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-maps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-messaging/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-messaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.carplay-communication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.carplay-communication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.carplay-messaging"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.carplay-messaging"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
