{
  "abstract": [
    {
      "text": "A Boolean value indicating whether your app can use the card session API.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.nfc.hce",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.nfc.hce"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.developer.nfc.hce"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.developer.nfc.hce",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "NO"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app must have this entitlement or else initializing a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreNFC/CardSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " raises ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information and to apply for this entitlement, visit ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/support/hce-payment-transactions-in-payment-apps/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can use the hotspot manager to configure Wi-Fi networks.",
          "type": "text"
        }
      ],
      "ideTitle": "Hotspot Configuration Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration",
      "kind": "symbol",
      "name": "com.apple.developer.networking.HotspotConfiguration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.HotspotConfiguration"
        }
      ],
      "role": "symbol",
      "title": "Hotspot Configuration Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.hotspotconfiguration"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app may use Multipath protocols to seamlessly transition between Wi-Fi and cellular networks.",
          "type": "text"
        }
      ],
      "ideTitle": "Multipath Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
      "kind": "symbol",
      "name": "com.apple.developer.networking.multipath",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.multipath"
        }
      ],
      "role": "symbol",
      "title": "Multipath Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.multipath"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can access information about the connected Wi-Fi network.",
          "type": "text"
        }
      ],
      "ideTitle": "Access Wi-Fi Information Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
      "kind": "symbol",
      "name": "com.apple.developer.networking.wifi-info",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.wifi-info"
        }
      ],
      "role": "symbol",
      "title": "Access Wi-Fi Information Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.wifi-info"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can use the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can be a default app for contactless NFC with the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce.default-contactless-app",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce.default-contactless-app"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce.default-contactless-app",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce.default-contactless-app"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes": {
      "abstract": [
        {
          "text": "An array of identifier strings the app handles with the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats": {
      "abstract": [
        {
          "text": "The Near Field Communication data formats an app can read.",
          "type": "text"
        }
      ],
      "ideTitle": "Near Field Communication Tag Reader Session Formats Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
      "kind": "symbol",
      "name": "com.apple.developer.nfc.readersession.formats",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.nfc.readersession.formats"
        }
      ],
      "role": "symbol",
      "title": "Near Field Communication Tag Reader Session Formats Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.nfc.readersession.formats"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app may configure MFi Wi-Fi accessories.",
          "type": "text"
        }
      ],
      "ideTitle": "Wireless Accessory Configuration Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
      "kind": "symbol",
      "name": "com.apple.external-accessory.wireless-configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.external-accessory.wireless-configuration"
        }
      ],
      "role": "symbol",
      "title": "Wireless Accessory Configuration Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.external-accessory.wireless-configuration"
    },
    "doc://com.apple.documentation/documentation/CoreNFC/CardSession": {
      "abstract": [
        {
          "text": "An ISO 7816 card emulation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CardSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreNFC/CardSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "CardSession",
      "type": "topic",
      "url": "/documentation/CoreNFC/CardSession"
    },
    "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)": {
      "abstract": [
        {
          "text": "Unconditionally prints a given message and stops execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalError"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "message"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "attribute",
          "text": "@autoclosure "
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " = String(), "
        },
        {
          "kind": "externalParam",
          "text": "file"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "keyword",
          "text": "#file"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "line"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "keyword",
          "text": "#line"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/fatalError(_:file:line:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fatalError(_:file:line:)",
      "type": "topic",
      "url": "/documentation/Swift/fatalError(_:file:line:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/support/hce-payment-transactions-in-payment-apps/": {
      "identifier": "https://developer.apple.com/support/hce-payment-transactions-in-payment-apps/",
      "title": "HCE-based contactless transactions for banking and wallet apps in the European Economic Area",
      "titleInlineContent": [
        {
          "text": "HCE-based contactless transactions for banking and wallet apps in the European Economic Area",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/hce-payment-transactions-in-payment-apps/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Wireless-interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app"
      ],
      "title": "Wireless interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.developer.nfc.hce"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Wireless-interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.wifi-info",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.external-accessory.wireless-configuration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multipath",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.HotspotConfiguration",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.readersession.formats",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app"
              ],
              "title": "Wireless interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.wifi-info/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.wifi-info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.readersession.formats/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.readersession.formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.multipath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.multipath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce.default-contactless-app/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce.default-contactless-app"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.nfc.hce.iso7816.select-identifier-prefixes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.HotspotConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.HotspotConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.external-accessory.wireless-configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.external-accessory.wireless-configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.nfc.hce"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
