{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether your app can use the Virtualization framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.security.virtualization",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.security.virtualization"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "com.apple.security.virtualization"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "com.apple.security.virtualization",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can read the ",
              "type": "text"
            },
            {
              "code": "VZVirtualMachine",
              "type": "codeVoice"
            },
            {
              "text": " property ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Virtualization/VZMacHardwareModel/isSupported",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to check for the availability of virtualization on the system. Calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Virtualization/VZVirtualMachineConfiguration/validate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " checks for the availability of the entitlement the framework requires to run guest OSes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app creates and manages virtual machines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor",
      "kind": "symbol",
      "name": "com.apple.security.hypervisor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.hypervisor"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.hypervisor",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.hypervisor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app can use the Virtualization framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.virtualization",
      "kind": "symbol",
      "name": "com.apple.security.virtualization",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.security.virtualization"
        }
      ],
      "role": "symbol",
      "title": "com.apple.security.virtualization",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.security.virtualization"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app captures USB devices and uses them in the guest-operating system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
      "kind": "symbol",
      "name": "com.apple.vm.device-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.device-access"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.device-access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.device-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app creates and manages virtual machines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
      "kind": "symbol",
      "name": "com.apple.vm.hypervisor",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.hypervisor"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.hypervisor",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.hypervisor"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the app manages virtual network interfaces without escalating privileges to the root user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking",
      "kind": "symbol",
      "name": "com.apple.vm.networking",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.vm.networking"
        }
      ],
      "role": "symbol",
      "title": "com.apple.vm.networking",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.vm.networking"
    },
    "doc://com.apple.documentation/documentation/Virtualization/VZMacHardwareModel/isSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the host supports this hardware model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Virtualization/VZMacHardwareModel/isSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSupported",
      "type": "topic",
      "url": "/documentation/Virtualization/VZMacHardwareModel/isSupported"
    },
    "doc://com.apple.documentation/documentation/Virtualization/VZVirtualMachineConfiguration/validate()": {
      "abstract": [
        {
          "text": "Validates the current configuration settings and reports any issues that might prevent the successful initialization of the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Virtualization/VZVirtualMachineConfiguration/validate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "validate()",
      "type": "topic",
      "url": "/documentation/Virtualization/VZVirtualMachineConfiguration/validate()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Hypervisor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking"
      ],
      "title": "Hypervisor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "com.apple.security.virtualization"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.virtualization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Hypervisor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.security.hypervisor",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.hypervisor",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.device-access",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.vm.networking"
              ],
              "title": "Hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.virtualization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.virtualization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.hypervisor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.security.hypervisor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.security.hypervisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validate()/title",
          "value": "validateWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Virtualization~1VZVirtualMachineConfiguration~1validate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "validateWithError:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.device-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.device-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.vm.networking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.vm.networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Virtualization~1VZMacHardwareModel~1isSupported/title",
          "value": "supported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Virtualization~1VZMacHardwareModel~1isSupported/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isSupported"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "supported"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.virtualization"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.security.virtualization"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
