{
  "abstract": [
    {
      "text": "The API an app can use to create and control a custom system VPN configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.networking.vpn.api",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.networking.vpn.api"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "Personal VPN Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Personal VPN Entitlement",
        "name": "com.apple.developer.networking.vpn.api",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": true,
            "baseType": "string "
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "allow-vpn"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enabled, your app can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEVPNManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to manage a Personal VPN configuration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the Personal VPN capability in Xcode. When the entitlement is enabled, Xcode sets the value to ",
              "type": "text"
            },
            {
              "code": "allow-vpn",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains": {
      "abstract": [
        {
          "text": "The associated domains for specific services, such as shared web credentials, universal links, and App Clips.",
          "type": "text"
        }
      ],
      "ideTitle": "Associated Domains Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
      "kind": "symbol",
      "name": "com.apple.developer.associated-domains",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.associated-domains"
        }
      ],
      "role": "symbol",
      "title": "Associated Domains Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use universal links.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
      "kind": "symbol",
      "name": "com.apple.developer.associated-domains.applinks.read-write",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.associated-domains.applinks.read-write"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.associated-domains.applinks.read-write",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.associated-domains.applinks.read-write"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can use ThreadNetwork.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
      "kind": "symbol",
      "name": "com.apple.developer.networking.manage-thread-network-credentials",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.manage-thread-network-credentials"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.manage-thread-network-credentials",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.manage-thread-network-credentials"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can send or receive IP multicast traffic.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
      "kind": "symbol",
      "name": "com.apple.developer.networking.multicast",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.multicast"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.multicast",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.multicast"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension": {
      "abstract": [
        {
          "text": "The APIs an app can use to customize networking features.",
          "type": "text"
        }
      ],
      "ideTitle": "Network Extensions Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
      "kind": "symbol",
      "name": "com.apple.developer.networking.networkextension",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.networkextension"
        }
      ],
      "role": "symbol",
      "title": "Network Extensions Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.networkextension"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory": {
      "abstract": [
        {
          "text": "The key that defines the app category entitlement to enable Cellular Network Slicing.",
          "type": "text"
        }
      ],
      "ideTitle": "5G Network Slicing App Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
      "kind": "symbol",
      "name": "com.apple.developer.networking.slicing.appcategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.slicing.appcategory"
        }
      ],
      "role": "symbol",
      "title": "5G Network Slicing App Category",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.slicing.appcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory": {
      "abstract": [
        {
          "text": "The key that defines the traffic category entitlement to enable Cellular Network Slicing.",
          "type": "text"
        }
      ],
      "ideTitle": "5G Network Slicing Traffic Category",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
      "kind": "symbol",
      "name": "com.apple.developer.networking.slicing.trafficcategory",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.slicing.trafficcategory"
        }
      ],
      "role": "symbol",
      "title": "5G Network Slicing Traffic Category",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.slicing.trafficcategory"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet",
      "kind": "symbol",
      "name": "com.apple.developer.networking.vmnet",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.vmnet"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.networking.vmnet",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.vmnet"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api": {
      "abstract": [
        {
          "text": "The API an app can use to create and control a custom system VPN configuration.",
          "type": "text"
        }
      ],
      "ideTitle": "Personal VPN Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vpn.api",
      "kind": "symbol",
      "name": "com.apple.developer.networking.vpn.api",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.networking.vpn.api"
        }
      ],
      "role": "symbol",
      "title": "Personal VPN Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.networking.vpn.api"
    },
    "doc://com.apple.documentation/documentation/NetworkExtension/NEVPNManager": {
      "abstract": [
        {
          "text": "An object to create and manage a Personal VPN configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NetworkExtension/NEVPNManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "NEVPNManager",
      "type": "topic",
      "url": "/documentation/NetworkExtension/NEVPNManager"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Networking",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet"
      ],
      "title": "Networking"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Personal VPN Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.vpn.api"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Networking",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.networkextension",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.multicast",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.associated-domains.applinks.read-write",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.manage-thread-network-credentials",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.appcategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.slicing.trafficcategory",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.networking.vmnet"
              ],
              "title": "Networking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.slicing.trafficcategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.slicing.trafficcategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.slicing.appcategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.slicing.appcategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.vmnet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.vmnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.vpn.api/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.vpn.api"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.associated-domains.applinks.read-write/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.associated-domains.applinks.read-write"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NetworkExtension~1NEVPNManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NEVPNManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.associated-domains/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.associated-domains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.networkextension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.networkextension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.multicast/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.multicast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.networking.manage-thread-network-credentials/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.networking.manage-thread-network-credentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.networking.vpn.api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.networking.vpn.api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
