{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the app can stream USB UVC devices connected to the Developer strap.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.avfoundation.uvc-device-access",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.avfoundation.uvc-device-access"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UVC Device Access on visionOS"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "UVC Device Access on visionOS",
        "name": "com.apple.developer.avfoundation.uvc-device-access",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": false,
            "baseType": "boolean"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On visionOS, your app must have the this entitlement to discover and use devices of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct/external",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This feature only supports USB2 devices drawing a maximum 500mA and supports the use of up to 1 hub.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category": {
      "abstract": [
        {
          "text": "An entitlement that allows an app to adjust thresholds that balance thermal dissipation and performance against fan noise and other factors.",
          "type": "text"
        }
      ],
      "ideTitle": "Increased performance headroom",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
      "kind": "symbol",
      "name": "com.apple.developer.app-compute-category",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.app-compute-category"
        }
      ],
      "role": "symbol",
      "title": "Increased performance headroom",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.app-compute-category"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use ARKit to detect, position, and decode barcode and QR codes.",
          "type": "text"
        }
      ],
      "ideTitle": "Spatial barcode and QR code scanning",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.barcode-detection.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.barcode-detection.allow"
        }
      ],
      "role": "symbol",
      "title": "Spatial barcode and QR code scanning",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.barcode-detection.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use ARKit to access the main cameras on Apple Vision Pro.",
          "type": "text"
        }
      ],
      "ideTitle": "Main camera access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.main-camera-access.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.main-camera-access.allow"
        }
      ],
      "role": "symbol",
      "title": "Main camera access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.main-camera-access.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow": {
      "abstract": [
        {
          "text": "A Boolean value that allows an app to use ARKit to track more objects with a higher frequency.",
          "type": "text"
        }
      ],
      "ideTitle": "Object-tracking parameter adjustment",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
      "kind": "symbol",
      "name": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
        }
      ],
      "role": "symbol",
      "title": "Object-tracking parameter adjustment",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app can stream USB UVC devices connected to the Developer strap.",
          "type": "text"
        }
      ],
      "ideTitle": "UVC Device Access on visionOS",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.avfoundation.uvc-device-access",
      "kind": "symbol",
      "name": "com.apple.developer.avfoundation.uvc-device-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.avfoundation.uvc-device-access"
        }
      ],
      "role": "symbol",
      "title": "UVC Device Access on visionOS",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.avfoundation.uvc-device-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can use the Apple Neural Engine to speed up CoreML.",
          "type": "text"
        }
      ],
      "ideTitle": "Apple Neural Engine access",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
      "kind": "symbol",
      "name": "com.apple.developer.coreml.neural-engine-access",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.coreml.neural-engine-access"
        }
      ],
      "role": "symbol",
      "title": "Apple Neural Engine access",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.coreml.neural-engine-access"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app can include passthrough in screen capture.",
          "type": "text"
        }
      ],
      "ideTitle": "Passthrough in screen capture",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
      "kind": "symbol",
      "name": "com.apple.developer.screen-capture.include-passthrough",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.screen-capture.include-passthrough"
        }
      ],
      "role": "symbol",
      "title": "Passthrough in screen capture",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.screen-capture.include-passthrough"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct/external": {
      "abstract": [
        {
          "text": "An external device type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "external"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureDeviceType",
          "text": "DeviceType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct/external",
      "kind": "symbol",
      "role": "symbol",
      "title": "external",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/DeviceType-swift.struct/external"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession": {
      "abstract": [
        {
          "text": "An object that finds capture devices that match specific search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice.DiscoverySession",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/DiscoverySession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enterprise",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow"
      ],
      "title": "Enterprise"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UVC Device Access on visionOS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.avfoundation.uvc-device-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enterprise",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.coreml.neural-engine-access",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.app-compute-category",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.screen-capture.include-passthrough",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.main-camera-access.allow",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.object-tracking-parameter-adjustment.allow",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.arkit.barcode-detection.allow"
              ],
              "title": "Enterprise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/title",
          "value": "AVCaptureDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceDiscoverySession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.coreml.neural-engine-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.coreml.neural-engine-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.main-camera-access.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.main-camera-access.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.object-tracking-parameter-adjustment.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.object-tracking-parameter-adjustment.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.app-compute-category/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.app-compute-category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.screen-capture.include-passthrough/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.screen-capture.include-passthrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.avfoundation.uvc-device-access/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.avfoundation.uvc-device-access"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.arkit.barcode-detection.allow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.arkit.barcode-detection.allow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct~1external/title",
          "value": "AVCaptureDeviceTypeExternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DeviceType-swift.struct~1external/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVCaptureDeviceType",
              "text": "AVCaptureDeviceType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceTypeExternal"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.avfoundation.uvc-device-access"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.avfoundation.uvc-device-access"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
