{
  "abstract": [
    {
      "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "entitlements:Entitlements.com.apple.developer.ClassKit-environment",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "com.apple.developer.ClassKit-environment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "ClassKit Environment Entitlement"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "ClassKit Environment Entitlement",
        "name": "com.apple.developer.ClassKit-environment",
        "platforms": [],
        "titleStyle": "title",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The environment used to develop and test your app locally, without requiring a Managed Apple ID issued by an educational institution.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "development"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The environment used by customers of your app who have a Managed Apple ID. This enviroment enables teachers and students to share data through iCloud.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "production"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key specifies the ClassKit environment your app uses to share data with Apple’s Schoolwork app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To support testing locally, Xcode sets the value to ",
              "type": "text"
            },
            {
              "code": "development",
              "type": "codeVoice"
            },
            {
              "text": " by default. When you upload your app to the App Store, Xcode changes the value to ",
              "type": "text"
            },
            {
              "code": "production",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add this entitlement to your app, enable the ClassKit capability in Xcode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements": {
      "abstract": [
        {
          "text": "Key-value pairs that grant an executable permission to use a service or technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements",
      "kind": "symbol",
      "name": "Entitlements",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entitlements"
        }
      ],
      "role": "symbol",
      "title": "Entitlements",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment": {
      "abstract": [
        {
          "text": "The ClassKit development or production environment for an education app that works with the Schoolwork app.",
          "type": "text"
        }
      ],
      "ideTitle": "ClassKit Environment Entitlement",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.ClassKit-environment",
      "kind": "symbol",
      "name": "com.apple.developer.ClassKit-environment",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.ClassKit-environment"
        }
      ],
      "role": "symbol",
      "title": "ClassKit Environment Entitlement",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.classkit-environment"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an app may create an assessment session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration",
      "kind": "symbol",
      "name": "com.apple.developer.automatic-assessment-configuration",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "com.apple.developer.automatic-assessment-configuration"
        }
      ],
      "role": "symbol",
      "title": "com.apple.developer.automatic-assessment-configuration",
      "titleStyle": "title",
      "type": "topic",
      "url": "/documentation/bundleresources/entitlements/com.apple.developer.automatic-assessment-configuration"
    },
    "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app": {
      "abstract": [
        {
          "text": "Prepare your app and your development environment to adopt ClassKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Enabling ClassKit in your app",
      "type": "topic",
      "url": "/documentation/ClassKit/enabling-classkit-in-your-app"
    },
    "doc://com.apple.documentation/documentation/ClassKit/testing-your-classkit-app-during-development": {
      "abstract": [
        {
          "text": "Use development mode to test your app without a Managed Apple ID.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ClassKit/testing-your-classkit-app-during-development",
      "kind": "article",
      "role": "article",
      "title": "Testing your ClassKit app during development",
      "type": "topic",
      "url": "/documentation/ClassKit/testing-your-classkit-app-during-development"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app",
        "doc://com.apple.documentation/documentation/ClassKit/testing-your-classkit-app-during-development"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Education",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration"
      ],
      "title": "Education"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ClassKit Environment Entitlement"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.ClassKit-environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/ClassKit/enabling-classkit-in-your-app",
                "doc://com.apple.documentation/documentation/ClassKit/testing-your-classkit-app-during-development"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Education",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Entitlements/com.apple.developer.automatic-assessment-configuration"
              ],
              "title": "Education"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/title",
          "value": "Entitlements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Entitlements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.ClassKit-environment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.ClassKit-environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Entitlements~1com.apple.developer.automatic-assessment-configuration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "com.apple.developer.automatic-assessment-configuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.classkit-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/entitlements/com.apple.developer.classkit-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
