{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "c:objc(cs)PKShareablePassMetadataPreview",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Preview"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Preview"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "PKShareablePassMetadata.Preview"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Preview"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AsyncShareablePassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AsyncShareablePassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/asyncshareablepassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview": {
      "abstract": [
        {
          "text": "A preview object that contains information representing the pass you add to Wallet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassMetadataPreview"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassMetadataPreview"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassMetadataPreview",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassmetadatapreview"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController": {
      "abstract": [
        {
          "text": "Lets your app show a pass and prompt the user to add that pass to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddPassesViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddPassesViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddpassesviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration": {
      "abstract": [
        {
          "text": "An object that describes the configuration of a secure element payment pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassConfiguration"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassConfiguration",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassconfiguration"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the addition of secure element payment passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAddSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKAddSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pkaddsecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPass": {
      "abstract": [
        {
          "text": "An object that represents a single pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPass"
        }
      ],
      "role": "symbol",
      "title": "PKPass",
      "type": "topic",
      "url": "/documentation/passkit/pkpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass": {
      "abstract": [
        {
          "text": "A pass with a credential that the device stores in a certified payment information chip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKSecureElementPass"
        }
      ],
      "role": "symbol",
      "title": "PKSecureElementPass",
      "type": "topic",
      "url": "/documentation/passkit/pksecureelementpass"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassResult"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassResult",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewController"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewController",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontroller"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareSecureElementPassViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "PKShareSecureElementPassViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/passkit/pksharesecureelementpassviewcontrollerdelegate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata": {
      "abstract": [
        {
          "text": "Information that you use to configure the sharing sheet for a pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKShareablePassMetadata"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKShareablePassMetadata"
        }
      ],
      "role": "symbol",
      "title": "PKShareablePassMetadata",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Preview"
        }
      ],
      "role": "symbol",
      "title": "PKShareablePassMetadata.Preview",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/init(templateIdentifier:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "templateIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/init(templateIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTemplateIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "init(templateIdentifier:)",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class/init(templateidentifier:)"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/ownerDisplayName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ownerDisplayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/ownerDisplayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ownerDisplayName"
        }
      ],
      "role": "symbol",
      "title": "ownerDisplayName",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class/ownerdisplayname"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/provisioningTemplateIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "provisioningTemplateIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/provisioningTemplateIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "provisioningTemplateIdentifier"
        }
      ],
      "role": "symbol",
      "title": "provisioningTemplateIdentifier",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadata/preview-swift.class/provisioningtemplateidentifier"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadataPreview/previewWithTemplateIdentifier:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "previewWithTemplateIdentifier:"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadataPreview/previewWithTemplateIdentifier:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewWithTemplateIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "previewWithTemplateIdentifier:",
      "type": "topic",
      "url": "/documentation/passkit/pkshareablepassmetadatapreview/previewwithtemplateidentifier:"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-purpose-passes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKPass",
        "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
        "doc://com.apple.passkit/documentation/PassKit/AsyncShareablePassConfiguration",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
        "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
      ],
      "title": "General purpose passes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/init(templateIdentifier:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/ownerDisplayName",
        "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/provisioningTemplateIdentifier"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKShareablePassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/ownerDisplayName",
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/provisioningTemplateIdentifier"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadata/Preview-swift.class/init(templateIdentifier:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKShareablePassMetadataPreview/previewWithTemplateIdentifier:"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-purpose-passes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKSecureElementPass",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassConfiguration",
                "doc://com.apple.passkit/documentation/PassKit/PKAddSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKPass",
                "doc://com.apple.passkit/documentation/PassKit/PKAddPassesViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewController",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassViewControllerDelegate",
                "doc://com.apple.passkit/documentation/PassKit/PKShareSecureElementPassResult"
              ],
              "title": "General purpose passes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKShareablePassMetadataPreview"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAddPassMetadataPreview",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PKAddPassMetadataPreview",
                    "text": "PKAddPassMetadataPreview"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/title",
          "value": "PKShareablePassMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/title",
          "value": "PKAddPassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassMetadataPreview/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/title",
          "value": "PKShareSecureElementPassResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/title",
          "value": "PKAddSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1ownerDisplayName/title",
          "value": "ownerDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1ownerDisplayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ownerDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/title",
          "value": "PKShareSecureElementPassViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1provisioningTemplateIdentifier/title",
          "value": "provisioningTemplateIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1provisioningTemplateIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "provisioningTemplateIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/title",
          "value": "PKAddSecureElementPassConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddSecureElementPassConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddSecureElementPassConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1init(templateIdentifier:)/title",
          "value": "initWithTemplateIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class~1init(templateIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTemplateIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/title",
          "value": "PKSecureElementPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKSecureElementPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKSecureElementPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/title",
          "value": "PKAddPassesViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAddPassesViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAddPassesViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/title",
          "value": "PKShareablePassMetadataPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareablePassMetadata~1Preview-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareablePassMetadataPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/title",
          "value": "PKPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/title",
          "value": "PKShareSecureElementPassViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKShareSecureElementPassViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKShareSecureElementPassViewControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkshareablepassmetadata/preview-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkshareablepassmetadata/preview-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
