{
  "abstract": [
    {
      "text": "Provides the top-level entry point for an app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WatchKit",
    "externalID": "s:So21WKApplicationDelegateP8WatchKitE4mainyyFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "main"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "main()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "main"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides an implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method that serves as the main entry point for your watchOS app. The system calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to launch your app; you never call it yourself. Your app can have exactly one entry point, which you mark with the ",
              "type": "text"
            },
            {
              "code": "@main",
              "type": "codeVoice"
            },
            {
              "text": " attribute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate": {
      "abstract": [
        {
          "text": "A collection of methods that manages the app-level behavior for a single-target watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKApplicationDelegate",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()": {
      "abstract": [
        {
          "text": "Tells the delegate that the watchOS app is visible and processing events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive"
        }
      ],
      "role": "symbol",
      "title": "applicationDidBecomeActive()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidbecomeactive()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has transitioned from the foreground to the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidEnterBackground"
        }
      ],
      "role": "symbol",
      "title": "applicationDidEnterBackground()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidenterbackground()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()": {
      "abstract": [
        {
          "text": "Tells the delegate that the launch process is almost done and the app is almost ready to run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidFinishLaunching"
        }
      ],
      "role": "symbol",
      "title": "applicationDidFinishLaunching()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationdidfinishlaunching()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()": {
      "abstract": [
        {
          "text": "Tells the delegate that the app is about to transition from the background to the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground"
        }
      ],
      "role": "symbol",
      "title": "applicationWillEnterForeground()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationwillenterforeground()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()": {
      "abstract": [
        {
          "text": "Tells the delegate that the system is about to deactivate the watchOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillResignActive"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillResignActive"
        }
      ],
      "role": "symbol",
      "title": "applicationWillResignActive()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/applicationwillresignactive()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()": {
      "abstract": [
        {
          "text": "Tells the delegate that the device’s orientation has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOrientationDidChange"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceOrientationDidChange"
        }
      ],
      "role": "symbol",
      "title": "deviceOrientationDidChange()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/deviceorientationdidchange()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()": {
      "abstract": [
        {
          "text": "Provides the top-level entry point for an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/main()",
      "kind": "symbol",
      "role": "symbol",
      "title": "main()",
      "type": "topic",
      "url": "/documentation/watchkit/wkapplicationdelegate/main()"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle": {
      "abstract": [
        {
          "text": "Learn how the watchOS app life cycle operates and responds to life cycle notification methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle",
      "kind": "article",
      "role": "article",
      "title": "Working with the watchOS app life cycle",
      "type": "topic",
      "url": "/documentation/watchkit/working-with-the-watchos-app-life-cycle"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Monitoring-state-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/working-with-the-watchos-app-life-cycle",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidFinishLaunching()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidBecomeActive()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillResignActive()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationWillEnterForeground()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/applicationDidEnterBackground()",
        "doc://com.apple.watchkit/documentation/WatchKit/WKApplicationDelegate/deviceOrientationDidChange()"
      ],
      "title": "Monitoring state changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidEnterBackground()/title",
          "value": "applicationDidEnterBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidEnterBackground()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidEnterBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/title",
          "value": "WKApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidBecomeActive()/title",
          "value": "applicationDidBecomeActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidBecomeActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidBecomeActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/title",
          "value": "applicationDidFinishLaunching"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationDidFinishLaunching()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidFinishLaunching"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillResignActive()/title",
          "value": "applicationWillResignActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillResignActive()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillResignActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillEnterForeground()/title",
          "value": "applicationWillEnterForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1applicationWillEnterForeground()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillEnterForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1deviceOrientationDidChange()/title",
          "value": "deviceOrientationDidChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKApplicationDelegate~1deviceOrientationDidChange()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceOrientationDidChange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkapplicationdelegate/main()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
