{
  "abstract": [
    {
      "text": "Returns the barcode symbologies that the request supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNDetectBarcodesRequest(im)supportedSymbologiesAndReturnError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "supportedSymbologies"
      },
      {
        "kind": "text",
        "text": "() "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@VNBarcodeSymbology",
        "text": "VNBarcodeSymbology"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "supportedSymbologiesAndReturnError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "supportedSymbologies()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "supportedSymbologies"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> ["
            },
            {
              "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@VNBarcodeSymbology",
              "text": "VNBarcodeSymbology"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of symbologies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology": {
      "abstract": [
        {
          "text": "The barcode symbologies that the framework detects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNBarcodeSymbology"
        }
      ],
      "role": "symbol",
      "title": "VNBarcodeSymbology",
      "type": "topic",
      "url": "/documentation/vision/vnbarcodesymbology"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest": {
      "abstract": [
        {
          "text": "A request that detects barcodes in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNDetectBarcodesRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNDetectBarcodesRequest"
        }
      ],
      "role": "symbol",
      "title": "VNDetectBarcodesRequest",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to coalesce multiple codes based on the symbology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coalesceCompositeSymbologies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coalesceCompositeSymbologies"
        }
      ],
      "role": "symbol",
      "title": "coalesceCompositeSymbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/coalescecompositesymbologies"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies": {
      "abstract": [
        {
          "text": "The array of barcode symbologies that the request supports.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        }
      ],
      "role": "symbol",
      "title": "supportedSymbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()": {
      "abstract": [
        {
          "text": "Returns the barcode symbologies that the request supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedSymbologies"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedSymbologiesAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "supportedSymbologies()",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies()"
    },
    "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies": {
      "abstract": [
        {
          "text": "The barcode symbologies that the request detects in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbologies"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@VNBarcodeSymbology",
          "text": "VNBarcodeSymbology"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbologies"
        }
      ],
      "role": "symbol",
      "title": "symbologies",
      "type": "topic",
      "url": "/documentation/vision/vndetectbarcodesrequest/symbologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Symbologies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
        "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
        "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies"
      ],
      "title": "Specifying Symbologies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "supportedSymbologiesAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportedSymbologiesAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Symbologies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/symbologies",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/coalesceCompositeSymbologies",
                "doc://com.apple.vision/documentation/Vision/VNBarcodeSymbology",
                "doc://com.apple.vision/documentation/Vision/VNDetectBarcodesRequest/supportedSymbologies"
              ],
              "title": "Specifying Symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "supportedSymbologiesAndReturnError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On output, a pointer to an error object that describes why the method failed, or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if no error occurred. If you are not interested in the error information, pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of symbologies.",
                    "type": "text"
                  },
                  {
                    "text": " On failure, this method returns ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies()/title",
          "value": "supportedSymbologiesAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportedSymbologiesAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1symbologies/title",
          "value": "symbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1symbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/title",
          "value": "VNBarcodeSymbology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNBarcodeSymbology/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNBarcodeSymbology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1coalesceCompositeSymbologies/title",
          "value": "coalesceCompositeSymbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1coalesceCompositeSymbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "coalesceCompositeSymbologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest/title",
          "value": "VNDetectBarcodesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectBarcodesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNDetectBarcodesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies/title",
          "value": "supportedSymbologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNDetectBarcodesRequest~1supportedSymbologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedSymbologies"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vndetectbarcodesrequest/supportedsymbologies()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
