{
  "abstract": [
    {
      "text": "User tapped the reload button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIWebViewNavigationType@UIWebViewNavigationTypeReload",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "reload"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIWebViewNavigationTypeReload"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIWebView.NavigationType.reload"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reload"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView": {
      "abstract": [
        {
          "text": "A view that embeds web content in your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "role": "symbol",
      "title": "UIWebView",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType": {
      "abstract": [
        {
          "text": "Constant indicating the user’s action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NavigationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NavigationType"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward": {
      "abstract": [
        {
          "text": "User tapped the back or forward button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeBackForward"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.backForward",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/backforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted": {
      "abstract": [
        {
          "text": "User resubmitted a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formResubmitted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeFormResubmitted"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.formResubmitted",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/formresubmitted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted": {
      "abstract": [
        {
          "text": "User submitted a form.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formSubmitted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeFormSubmitted"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.formSubmitted",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/formsubmitted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked": {
      "abstract": [
        {
          "text": "User tapped a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkClicked"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeLinkClicked"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.linkClicked",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/linkclicked"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other": {
      "abstract": [
        {
          "text": "Some other action occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeOther"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.other",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/other"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload": {
      "abstract": [
        {
          "text": "User tapped the reload button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebViewNavigationTypeReload"
        }
      ],
      "role": "symbol",
      "title": "UIWebView.NavigationType.reload",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview/navigationtype/reload"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIWebViewNavigationTypeReload"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeReload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/linkClicked",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formSubmitted",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/backForward",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/formResubmitted",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView/NavigationType/other"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIWebViewNavigationTypeReload"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/title",
          "value": "UIWebViewNavigationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1reload/title",
          "value": "UIWebViewNavigationTypeReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeReload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/title",
          "value": "UIWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1backForward/title",
          "value": "UIWebViewNavigationTypeBackForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1backForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeBackForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formSubmitted/title",
          "value": "UIWebViewNavigationTypeFormSubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formSubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeFormSubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formResubmitted/title",
          "value": "UIWebViewNavigationTypeFormResubmitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1formResubmitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeFormResubmitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1linkClicked/title",
          "value": "UIWebViewNavigationTypeLinkClicked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1linkClicked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeLinkClicked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1other/title",
          "value": "UIWebViewNavigationTypeOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView~1NavigationType~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebViewNavigationTypeOther"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwebview/navigationtype/reload"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwebview/navigationtype/reload"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
