{
  "abstract": [
    {
      "text": "CloudKit can’t determine the status of the user’s iCloud account.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/couldNotDetermine"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKAccountStatus@CKAccountStatusCouldNotDetermine",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "couldNotDetermine"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKAccountStatusCouldNotDetermine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CKAccountStatus.couldNotDetermine"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "couldNotDetermine"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the availability of the user’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKAccountStatus"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatus"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/available": {
      "abstract": [
        {
          "text": "The user’s iCloud account is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "available"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/available",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatusAvailable"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus.available",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus/available"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/couldNotDetermine": {
      "abstract": [
        {
          "text": "CloudKit can’t determine the status of the user’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "couldNotDetermine"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/couldNotDetermine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatusCouldNotDetermine"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus.couldNotDetermine",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus/couldnotdetermine"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/noAccount": {
      "abstract": [
        {
          "text": "The device doesn’t have an iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccount"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/noAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatusNoAccount"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus.noAccount",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus/noaccount"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/restricted": {
      "abstract": [
        {
          "text": "The system denies access to the user’s iCloud account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus.restricted",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus/restricted"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/temporarilyUnavailable": {
      "abstract": [
        {
          "text": "The user’s iCloud account is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/temporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKAccountStatusTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CKAccountStatus.temporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/cloudkit/ckaccountstatus/temporarilyunavailable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Account-Statuses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/available",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/noAccount",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/restricted",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/temporarilyUnavailable"
      ],
      "title": "Account Statuses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKAccountStatusCouldNotDetermine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusCouldNotDetermine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Account-Statuses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/available",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/noAccount",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/restricted",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKAccountStatus/temporarilyUnavailable"
              ],
              "title": "Account Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKAccountStatusCouldNotDetermine"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1restricted/title",
          "value": "CKAccountStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1temporarilyUnavailable/title",
          "value": "CKAccountStatusTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1temporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus/title",
          "value": "CKAccountStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1couldNotDetermine/title",
          "value": "CKAccountStatusCouldNotDetermine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1couldNotDetermine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusCouldNotDetermine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1available/title",
          "value": "CKAccountStatusAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1available/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1noAccount/title",
          "value": "CKAccountStatusNoAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKAccountStatus~1noAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKAccountStatusNoAccount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckaccountstatus/couldnotdetermine"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckaccountstatus/couldnotdetermine"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
