{
  "abstract": [
    {
      "text": "The device allows subscription to the Apple Music catalog.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogSubscriptionEligible"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKCloudServiceCapability@SKCloudServiceCapabilityMusicCatalogSubscriptionEligible",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "musicCatalogSubscriptionEligible"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SKCloudServiceCapability",
        "text": "SKCloudServiceCapability"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "10.1",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "10.1",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "10.1",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "message": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "musicCatalogSubscriptionEligible"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "musicCatalogSubscriptionEligible"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SKCloudServiceCapability",
              "text": "SKCloudServiceCapability"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
        "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability": {
      "abstract": [
        {
          "text": "Constants that specify the current capabilities of the customer’s Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceCapability",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/addToCloudMusicLibrary": {
      "abstract": [
        {
          "text": "The device allows tracks to be added to the user’s music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addToCloudMusicLibrary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceCapability",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/addToCloudMusicLibrary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilityAddToCloudMusicLibrary"
        }
      ],
      "role": "symbol",
      "title": "addToCloudMusicLibrary",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability/addtocloudmusiclibrary"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogPlayback": {
      "abstract": [
        {
          "text": "The device allows playback of Apple Music catalog tracks.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicCatalogPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceCapability",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilityMusicCatalogPlayback"
        }
      ],
      "role": "symbol",
      "title": "musicCatalogPlayback",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability/musiccatalogplayback"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogSubscriptionEligible": {
      "abstract": [
        {
          "text": "The device allows subscription to the Apple Music catalog.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicCatalogSubscriptionEligible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKCloudServiceCapability",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogSubscriptionEligible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
        }
      ],
      "role": "symbol",
      "title": "musicCatalogSubscriptionEligible",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability/musiccatalogsubscriptioneligible"
    },
    "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities": {
      "abstract": [
        {
          "text": "Determine which Apple Music capabilities are available on a customer’s device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
      "kind": "article",
      "role": "article",
      "title": "Determining a person’s Apple Music capabilities",
      "type": "topic",
      "url": "/documentation/storekit/determining-a-person-s-apple-music-capabilities"
    },
    "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app": {
      "abstract": [
        {
          "text": "Allow eligible customers to subscribe to Apple Music.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/offering-apple-music-subscription-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Apple Music Subscription in Your App",
      "type": "topic",
      "url": "/documentation/storekit/offering-apple-music-subscription-in-your-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-Cloud-Service-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogPlayback",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/addToCloudMusicLibrary"
      ],
      "title": "Identifying Cloud Service Capabilities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "10.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "10.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "10.1",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-Cloud-Service-Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/musicCatalogPlayback",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/addToCloudMusicLibrary"
              ],
              "title": "Identifying Cloud Service Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the canBecomeSubscriber property of MusicSubscription from MusicKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/title",
          "value": "SKCloudServiceCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1addToCloudMusicLibrary/title",
          "value": "SKCloudServiceCapabilityAddToCloudMusicLibrary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1addToCloudMusicLibrary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapabilityAddToCloudMusicLibrary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1musicCatalogPlayback/title",
          "value": "SKCloudServiceCapabilityMusicCatalogPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1musicCatalogPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapabilityMusicCatalogPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1musicCatalogSubscriptionEligible/title",
          "value": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability~1musicCatalogSubscriptionEligible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapabilityMusicCatalogSubscriptionEligible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skcloudservicecapability/musiccatalogsubscriptioneligible"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skcloudservicecapability/musiccatalogsubscriptioneligible"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
