{
  "abstract": [
    {
      "text": "The device does not allow playback of Apple Music content or the addition of tracks to the music library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/SKCloudServiceCapabilityNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKCloudServiceCapability@SKCloudServiceCapabilityNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceCapabilityNone"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceCapabilityNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "name": "iOS"
      },
      {
        "beta": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "name": "tvOS"
      },
      {
        "beta": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "SKCloudServiceCapabilityNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapabilityNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability": {
      "abstract": [
        {
          "text": "Constants that specify the current capabilities of the customer’s Music library on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapability"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceCapability",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/SKCloudServiceCapabilityNone": {
      "abstract": [
        {
          "text": "The device does not allow playback of Apple Music content or the addition of tracks to the music library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceCapabilityNone"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceCapability/SKCloudServiceCapabilityNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKCloudServiceCapabilityNone",
      "type": "topic",
      "url": "/documentation/storekit/skcloudservicecapability/skcloudservicecapabilitynone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/title",
          "value": "SKCloudServiceCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceCapability"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skcloudservicecapability/skcloudservicecapabilitynone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
