{
  "abstract": [
    {
      "text": "The mathematical terms for computing the noise in this sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/noiseTerms-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SensorKit",
    "externalID": "s:So33SRPhotoplethysmogramOpticalSampleC9SensorKitE10noiseTermsAbCE05NoiseG0VSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noiseTerms"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
        "text": "SRPhotoplethysmogramOpticalSample"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So33SRPhotoplethysmogramOpticalSampleC9SensorKitE10NoiseTermsV",
        "text": "NoiseTerms"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "noiseTerms"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noiseTerms"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
              "text": "SRPhotoplethysmogramOpticalSample"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/NoiseTerms-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So33SRPhotoplethysmogramOpticalSampleC9SensorKitE10NoiseTermsV",
              "text": "NoiseTerms"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the sensor data is invalid, this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nil-2gl": {
      "abstract": [
        {
          "text": "Defines the `id` of a null instance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nil-2gl",
      "kind": "symbol",
      "role": "symbol",
      "title": "nil",
      "type": "topic",
      "url": "/documentation/objectivec/nil-2gl"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample": {
      "abstract": [
        {
          "text": "A data sample from the photoplethysmogram (PPG) optical sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition": {
      "abstract": [
        {
          "text": "The conditions that may occur when recording photoplethysmogram optical data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Condition"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample.Condition",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/condition"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/NoiseTerms-swift.struct": {
      "abstract": [
        {
          "text": "The mathematical terms that you use to compute the photoplethysmogram (PPG) noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NoiseTerms"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/NoiseTerms-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NoiseTerms"
        }
      ],
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample.NoiseTerms",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/noiseterms-swift.struct"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/activePhotodiodeIndexes": {
      "abstract": [
        {
          "text": "The set of photodiodes in use during the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activePhotodiodeIndexes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/activePhotodiodeIndexes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activePhotodiodeIndexes"
        }
      ],
      "role": "symbol",
      "title": "activePhotodiodeIndexes",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/activephotodiodeindexes"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/conditions": {
      "abstract": [
        {
          "text": "The sensor context or conditions that may affect the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
          "text": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRPhotoplethysmogramOpticalSampleCondition",
          "text": "Condition"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/conditions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "conditions"
        }
      ],
      "role": "symbol",
      "title": "conditions",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/conditions"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/effectiveWavelength": {
      "abstract": [
        {
          "text": "A temperature-compensated wavelength estimate in nanometers that the emitter produces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveWavelength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/effectiveWavelength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveWavelength"
        }
      ],
      "role": "symbol",
      "title": "effectiveWavelength",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/effectivewavelength"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/emitter": {
      "abstract": [
        {
          "text": "The index of the LED in use during the sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/emitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emitter"
        }
      ],
      "role": "symbol",
      "title": "emitter",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/emitter"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nanosecondsSinceStart": {
      "abstract": [
        {
          "text": "The time in nanoseconds since the system turns on the sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nanosecondsSinceStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nanosecondsSinceStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nanosecondsSinceStart"
        }
      ],
      "role": "symbol",
      "title": "nanosecondsSinceStart",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/nanosecondssincestart"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/noiseTerms-swift.property": {
      "abstract": [
        {
          "text": "The mathematical terms for computing the noise in this sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noiseTerms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SRPhotoplethysmogramOpticalSample",
          "text": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So33SRPhotoplethysmogramOpticalSampleC9SensorKitE10NoiseTermsV",
          "text": "NoiseTerms"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/noiseTerms-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "noiseTerms",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/noiseterms-swift.property"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nominalWavelength": {
      "abstract": [
        {
          "text": "The wavelength in nanometers that the emitter produces while operating at a specific temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalWavelength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nominalWavelength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nominalWavelength"
        }
      ],
      "role": "symbol",
      "title": "nominalWavelength",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/nominalwavelength"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/normalizedReflectance-15f2k": {
      "abstract": [
        {
          "text": "The normalized photoplethysmogram (PPG) waveform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedReflectance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/normalizedReflectance-15f2k",
      "kind": "symbol",
      "role": "symbol",
      "title": "normalizedReflectance",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/normalizedreflectance-15f2k"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/samplingFrequency": {
      "abstract": [
        {
          "text": "The sampling frequency of the photoplethysmogram (PPG) data in hertz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplingFrequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitFrequency",
          "text": "UnitFrequency"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/samplingFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplingFrequency"
        }
      ],
      "role": "symbol",
      "title": "samplingFrequency",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/samplingfrequency"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/signalIdentifier": {
      "abstract": [
        {
          "text": "The identifier for a signal that photodiodes and emitters produce.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/signalIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "signalIdentifier",
      "type": "topic",
      "url": "/documentation/sensorkit/srphotoplethysmogramopticalsample/signalidentifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-optical-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/emitter",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/activePhotodiodeIndexes",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/signalIdentifier",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nominalWavelength",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/effectiveWavelength",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/samplingFrequency",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/nanosecondsSinceStart",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/conditions",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/Condition",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/NoiseTerms-swift.struct",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRPhotoplethysmogramOpticalSample/normalizedReflectance-15f2k"
      ],
      "title": "Accessing optical data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1activePhotodiodeIndexes/title",
          "value": "activePhotodiodeIndexes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1activePhotodiodeIndexes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activePhotodiodeIndexes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1nominalWavelength/title",
          "value": "nominalWavelength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1nominalWavelength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nominalWavelength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1samplingFrequency/title",
          "value": "samplingFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1samplingFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "samplingFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/title",
          "value": "SRPhotoplethysmogramOpticalSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1conditions/title",
          "value": "conditions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1conditions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "conditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1signalIdentifier/title",
          "value": "signalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1signalIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/title",
          "value": "SRPhotoplethysmogramOpticalSampleCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1Condition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSampleCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1effectiveWavelength/title",
          "value": "effectiveWavelength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1effectiveWavelength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveWavelength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1nanosecondsSinceStart/title",
          "value": "nanosecondsSinceStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1nanosecondsSinceStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nanosecondsSinceStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1emitter/title",
          "value": "emitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample~1emitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emitter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srphotoplethysmogramopticalsample/noiseterms-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
