{
  "abstract": [
    {
      "text": "An action that toggles the display of the color palette.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPencilPreferredAction@UIPencilPreferredActionShowColorPalette",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "showColorPalette"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPencilPreferredActionShowColorPalette"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIPencilPreferredAction.showColorPalette"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "showColorPalette"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction": {
      "abstract": [
        {
          "text": "The actions Apple Pencil can perform after a person performs a double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredAction"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore": {
      "abstract": [
        {
          "text": "An action that does nothing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignore"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionIgnore"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.ignore",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/ignore"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut": {
      "abstract": [
        {
          "text": "An action that runs a system shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runSystemShortcut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionRunSystemShortcut"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.runSystemShortcut",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/runsystemshortcut"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette": {
      "abstract": [
        {
          "text": "An action that toggles the display of the color palette.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showColorPalette"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowColorPalette"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showColorPalette",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showcolorpalette"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette": {
      "abstract": [
        {
          "text": "An action that toggles shows a contextual palette of markup tools, or undo and redo options if tools aren’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showContextualPalette"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowContextualPalette"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showContextualPalette",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showcontextualpalette"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes": {
      "abstract": [
        {
          "text": "An action that toggles the display of the selected tool’s ink attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showInkAttributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowInkAttributes"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showInkAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showinkattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser": {
      "abstract": [
        {
          "text": "An action that switches between the current tool and the eraser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchEraser"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionSwitchEraser"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.switchEraser",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/switcheraser"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious": {
      "abstract": [
        {
          "text": "An action that switches between the current tool and the last used tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchPrevious"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionSwitchPrevious"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.switchPrevious",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/switchprevious"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Preferred-actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut"
      ],
      "title": "Preferred actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPencilPreferredActionShowColorPalette"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowColorPalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Preferred-actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut"
              ],
              "title": "Preferred actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPencilPreferredActionShowColorPalette"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/title",
          "value": "UIPencilPreferredAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showInkAttributes/title",
          "value": "UIPencilPreferredActionShowInkAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showInkAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowInkAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchEraser/title",
          "value": "UIPencilPreferredActionSwitchEraser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchEraser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionSwitchEraser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchPrevious/title",
          "value": "UIPencilPreferredActionSwitchPrevious"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchPrevious/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionSwitchPrevious"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showColorPalette/title",
          "value": "UIPencilPreferredActionShowColorPalette"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showColorPalette/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowColorPalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showContextualPalette/title",
          "value": "UIPencilPreferredActionShowContextualPalette"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showContextualPalette/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowContextualPalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1ignore/title",
          "value": "UIPencilPreferredActionIgnore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1ignore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionIgnore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1runSystemShortcut/title",
          "value": "UIPencilPreferredActionRunSystemShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1runSystemShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionRunSystemShortcut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipencilpreferredaction/showcolorpalette"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipencilpreferredaction/showcolorpalette"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
