{
  "abstract": [
    {
      "text": "An error state that indicates the commands in the command buffer are the cause of an error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/faulted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCommandEncoderErrorState@MTLCommandEncoderErrorStateFaulted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "faulted"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLCommandEncoderErrorStateFaulted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLCommandEncoderErrorState.faulted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "faulted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState": {
      "abstract": [
        {
          "text": "Possible error conditions for the command encoder’s commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorState"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorState"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/affected": {
      "abstract": [
        {
          "text": "An error state that indicates the GPU failed to fully execute the commands because of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "affected"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/affected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorStateAffected"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState.affected",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate/affected"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/completed": {
      "abstract": [
        {
          "text": "A state that indicates the GPU successfully executed the commands without any errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorStateCompleted"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState.completed",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate/completed"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/faulted": {
      "abstract": [
        {
          "text": "An error state that indicates the commands in the command buffer are the cause of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faulted"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/faulted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorStateFaulted"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState.faulted",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate/faulted"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/pending": {
      "abstract": [
        {
          "text": "An error state that indicates the GPU didn’t execute the commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorStatePending"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState.pending",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate/pending"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/unknown": {
      "abstract": [
        {
          "text": "An error state that indicates the command buffer doesn’t know the state of its commands on the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoderErrorStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoderErrorState.unknown",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencodererrorstate/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Error-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/completed",
        "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/pending",
        "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/affected",
        "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/unknown"
      ],
      "title": "Getting the Error State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCommandEncoderErrorStateFaulted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStateFaulted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Error-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/completed",
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/pending",
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/affected",
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoderErrorState/unknown"
              ],
              "title": "Getting the Error State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLCommandEncoderErrorStateFaulted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1faulted/title",
          "value": "MTLCommandEncoderErrorStateFaulted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1faulted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStateFaulted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1affected/title",
          "value": "MTLCommandEncoderErrorStateAffected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1affected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStateAffected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1pending/title",
          "value": "MTLCommandEncoderErrorStatePending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStatePending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState/title",
          "value": "MTLCommandEncoderErrorState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1unknown/title",
          "value": "MTLCommandEncoderErrorStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1completed/title",
          "value": "MTLCommandEncoderErrorStateCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoderErrorState~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoderErrorStateCompleted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommandencodererrorstate/faulted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcommandencodererrorstate/faulted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
