{
  "abstract": [
    {
      "text": "The display state for the preview item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklookui/documentation/QuickLookUI",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemDisplayState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)QLPreviewItem(py)previewItemDisplayState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "previewItemDisplayState"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Quick Look UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "previewItemDisplayState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "previewItemDisplayState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "previewItemDisplayState"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "! { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The display state is an opaque object used by the preview panel. You typically use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to retrieve the display state which you save for later use in the preview item. This way you can preserve the display state when the panel moves from or to another controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property is optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look UI",
      "type": "topic",
      "url": "/documentation/quicklookui"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem": {
      "abstract": [
        {
          "text": "A protocol that defines a set of properties you implement to make a preview of your application’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemDisplayState": {
      "abstract": [
        {
          "text": "The display state for the preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewItemDisplayState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemDisplayState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewItemDisplayState"
        }
      ],
      "role": "symbol",
      "title": "previewItemDisplayState",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem/previewitemdisplaystate"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemTitle": {
      "abstract": [
        {
          "text": "The title to display for the preview item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewItemTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewItemTitle"
        }
      ],
      "role": "symbol",
      "title": "previewItemTitle",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem/previewitemtitle"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemURL": {
      "abstract": [
        {
          "text": "The URL of the item to preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewItemURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewItemURL"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "previewItemURL",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewitem/previewitemurl"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel": {
      "abstract": [
        {
          "text": "A class that implements the Quick Look preview panel to display a preview of a list of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPanel"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPanel",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel"
    },
    "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState": {
      "abstract": [
        {
          "text": "The preview panel’s display state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewPanel/displayState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayState"
        }
      ],
      "role": "symbol",
      "title": "displayState",
      "type": "topic",
      "url": "/documentation/quicklookui/qlpreviewpanel/displaystate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemTitle",
        "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemURL"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "previewItemDisplayState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItemDisplayState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklookui/documentation/QuickLookUI",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemTitle",
                "doc://com.apple.quicklookui/documentation/QuickLookUI/QLPreviewItem/previewItemURL"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "previewItemDisplayState"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemDisplayState/title",
          "value": "previewItemDisplayState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemDisplayState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItemDisplayState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemURL/title",
          "value": "previewItemURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItemURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1displayState/title",
          "value": "displayState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel~1displayState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/title",
          "value": "QLPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemTitle/title",
          "value": "previewItemTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewItem~1previewItemTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewItemTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/title",
          "value": "QLPreviewPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklookui~1documentation~1QuickLookUI~1QLPreviewPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPanel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewitem/previewitemdisplaystate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklookui/qlpreviewitem/previewitemdisplaystate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
