{
  "abstract": [
    {
      "text": "Creates a diffable data source with the specified item provider, and connects it to the specified collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCollectionViewDiffableDataSource(im)initWithCollectionView:itemProvider:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "collectionView"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSCollectionView",
        "text": "NSCollectionView"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "itemProvider"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
        "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithCollectionView:itemProvider:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(collectionView:itemProvider:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "collectionView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCollectionView",
              "text": "NSCollectionView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "itemProvider"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
              "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The initialized collection view object to connect to the diffable data source.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "collectionView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure that creates and returns each of the items for the collection view from the data the diffable data source provides.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "itemProvider"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionView": {
      "abstract": [
        {
          "text": "An ordered collection of data items displayed in a customizable layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionView"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionView",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference": {
      "abstract": [
        {
          "text": "The object you use to manage data and provide items for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReference"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewDiffableDataSourceReference",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdiffabledatasourcereference"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)": {
      "abstract": [
        {
          "text": "Creates a diffable data source with the specified item provider, and connects it to the specified collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionView",
          "text": "NSCollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference/init(collectionView:itemProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCollectionView:itemProvider:"
        }
      ],
      "role": "symbol",
      "title": "init(collectionView:itemProvider:)",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdiffabledatasourcereference/init(collectionview:itemprovider:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider": {
      "abstract": [
        {
          "text": "A closure that configures and returns an item for a collection view from its diffable data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionViewDiffableDataSourceReferenceItemProvider"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionViewDiffableDataSourceReferenceItemProvider",
      "type": "topic",
      "url": "/documentation/appkit/nscollectionviewdiffabledatasourcereferenceitemprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Diffable-Data-Source",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider"
      ],
      "title": "Creating a Diffable Data Source"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithCollectionView:itemProvider:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCollectionView:itemProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReference"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Diffable-Data-Source",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider"
              ],
              "title": "Creating a Diffable Data Source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithCollectionView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSCollectionView",
                    "text": "NSCollectionView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "collectionView"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "itemProvider:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCollectionViewDiffableDataSourceReferenceItemProvider",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSCollectionViewDiffableDataSourceItemProvider",
                    "text": "NSCollectionViewDiffableDataSourceItemProvider"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "itemProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The initialized collection view object to connect to the diffable data source.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "collectionView"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A closure that creates and returns each of the items for the collection view from the data the diffable data source provides.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "itemProvider"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference~1init(collectionView:itemProvider:)/title",
          "value": "initWithCollectionView:itemProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference~1init(collectionView:itemProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCollectionView:itemProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference/title",
          "value": "NSCollectionViewDiffableDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/title",
          "value": "NSCollectionViewDiffableDataSourceItemProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionViewDiffableDataSourceReferenceItemProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionViewDiffableDataSourceItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/title",
          "value": "NSCollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscollectionviewdiffabledatasourcereference/init(collectionview:itemprovider:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscollectionviewdiffabledatasourcereference/init(collectionview:itemprovider:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
