{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"explicitlyIncluded"}],"symbolKind":"property","platforms":[{"introducedAt":"10.11","deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSDictionaryControllerKeyValuePair(py)explicitlyIncluded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExplicitlyIncluded","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isExplicitlyIncluded"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsdictionarycontrollerkeyvaluepair/isexplicitlyincluded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsdictionarycontrollerkeyvaluepair/isexplicitlyincluded"]}],"seeAlsoSections":[{"anchor":"Instance-Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/key","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/localizedKey","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/value"],"generated":true,"title":"Instance Properties"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/isExplicitlyIncluded","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isExplicitlyIncluded","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/localizedKey":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"/documentation/appkit/nsdictionarycontrollerkeyvaluepair/localizedkey","title":"localizedKey","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/localizedKey","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"localizedKey"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair":{"url":"/documentation/appkit/nsdictionarycontrollerkeyvaluepair","kind":"symbol","abstract":[{"text":"A set of methods implemented by arranged objects to give access to information about those objects.","type":"text"}],"title":"NSDictionaryControllerKeyValuePair","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDictionaryControllerKeyValuePair"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSDictionaryControllerKeyValuePair"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/isExplicitlyIncluded":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExplicitlyIncluded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"/documentation/appkit/nsdictionarycontrollerkeyvaluepair/isexplicitlyincluded","title":"isExplicitlyIncluded","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/isExplicitlyIncluded","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"explicitlyIncluded"}]},"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/key":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"/documentation/appkit/nsdictionarycontrollerkeyvaluepair/key","title":"key","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/key","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"key"}]},"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/value":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"type":"topic","url":"/documentation/appkit/nsdictionarycontrollerkeyvaluepair/value","title":"value","identifier":"doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/value","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"introducedAt":"10.11","name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"explicitlyIncluded","path":"/metadata/title"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"explicitlyIncluded"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Instance Properties","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/key","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/localizedKey","doc://com.apple.appkit/documentation/AppKit/NSDictionaryControllerKeyValuePair/value"],"anchor":"Instance-Properties","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isExplicitlyIncluded"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitlyIncluded"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1localizedKey/title","value":"localizedKey"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1localizedKey/fragments","value":[{"kind":"identifier","text":"localizedKey"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/title","value":"NSDictionaryControllerKeyValuePair"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/fragments","value":[{"kind":"identifier","text":"NSDictionaryControllerKeyValuePair"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair/navigatorTitle","value":[{"text":"NSDictionaryControllerKeyValuePair","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1isExplicitlyIncluded/title","value":"explicitlyIncluded"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1isExplicitlyIncluded/fragments","value":[{"kind":"identifier","text":"explicitlyIncluded"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1key/title","value":"key"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1key/fragments","value":[{"text":"key","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1value/title","value":"value"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDictionaryControllerKeyValuePair~1value/fragments","value":[{"text":"value","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}