{
  "abstract": [
    {
      "text": "The device is in landscape mode, with the device held upright and the home button on the left side.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLDeviceOrientation@CLDeviceOrientationLandscapeRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "landscapeRight"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLDeviceOrientationLandscapeRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLDeviceOrientation.landscapeRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "landscapeRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation": {
      "abstract": [
        {
          "text": "Constants indicating the physical orientation of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLDeviceOrientation"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientation"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing downwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceDown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationFaceDown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.faceDown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/facedown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing upwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceUp"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationFaceUp"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.faceUp",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/faceup"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the home button on the right side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeLeft"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationLandscapeLeft"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.landscapeLeft",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/landscapeleft"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the home button on the left side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeRight"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationLandscapeRight"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.landscapeRight",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/landscaperight"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait": {
      "abstract": [
        {
          "text": "The device is in portrait mode, with the device held upright and the home button at the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationPortrait"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.portrait",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/portrait"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown": {
      "abstract": [
        {
          "text": "The device is in portrait mode but upside down, with the device held upright and the home button at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitUpsideDown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationPortraitUpsideDown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.portraitUpsideDown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/portraitupsidedown"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown": {
      "abstract": [
        {
          "text": "The orientation is currently not known.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLDeviceOrientationUnknown"
        }
      ],
      "role": "symbol",
      "title": "CLDeviceOrientation.unknown",
      "type": "topic",
      "url": "/documentation/corelocation/cldeviceorientation/unknown"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Device-Orientations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown"
      ],
      "title": "Device Orientations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLDeviceOrientationLandscapeRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationLandscapeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corelocation/documentation/CoreLocation",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Device-Orientations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/unknown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portrait",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/portraitUpsideDown",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/landscapeLeft",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceUp",
                "doc://com.apple.corelocation/documentation/CoreLocation/CLDeviceOrientation/faceDown"
              ],
              "title": "Device Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLDeviceOrientationLandscapeRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portraitUpsideDown/title",
          "value": "CLDeviceOrientationPortraitUpsideDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portraitUpsideDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationPortraitUpsideDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceUp/title",
          "value": "CLDeviceOrientationFaceUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationFaceUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeLeft/title",
          "value": "CLDeviceOrientationLandscapeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationLandscapeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeRight/title",
          "value": "CLDeviceOrientationLandscapeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1landscapeRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationLandscapeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceDown/title",
          "value": "CLDeviceOrientationFaceDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1faceDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationFaceDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1unknown/title",
          "value": "CLDeviceOrientationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/title",
          "value": "CLDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portrait/title",
          "value": "CLDeviceOrientationPortrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLDeviceOrientation~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLDeviceOrientationPortrait"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/cldeviceorientation/landscaperight"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocation/cldeviceorientation/landscaperight"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
