{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgColor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!"}],"navigatorTitle":[{"text":"bgColor","kind":"identifier"}],"modules":[{"name":"WebKit"}],"role":"symbol","externalID":"c:objc(cs)DOMHTMLTableRowElement(py)bgColor","roleHeading":"Instance Property","platforms":[{"deprecatedAt":"10.14","unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.4"}],"title":"bgColor","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement"]]},"variants":[{"paths":["/documentation/webkit/domhtmltablerowelement/bgcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/webkit/domhtmltablerowelement/bgcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"sections":[],"references":{"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"role":"symbol","kind":"symbol","title":"String","url":"/documentation/Swift/String"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"role":"symbol","kind":"symbol","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor":{"url":"/documentation/webkit/domhtmltablerowelement/bgcolor","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!"}],"deprecated":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bgColor"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement/bgColor","type":"topic","title":"bgColor"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement":{"kind":"symbol","title":"DOMHTMLTableRowElement","role":"symbol","abstract":[],"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement","navigatorTitle":[{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMHTMLTableRowElement","kind":"identifier"}],"type":"topic","url":"/documentation/webkit/domhtmltablerowelement","deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","deprecatedAt":"10.14","introducedAt":"10.4","deprecated":false,"beta":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","value":"bgColor","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"bgColor","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/DOMHTMLTableRowElement"]]},"path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bgColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1bgColor/title","op":"replace","value":"bgColor"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement~1bgColor/fragments","op":"replace","value":[{"text":"bgColor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/title","op":"replace","value":"DOMHTMLTableRowElement"},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/fragments","op":"replace","value":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}]},{"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMHTMLTableRowElement/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOMHTMLTableRowElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}