{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags/kMusicSequenceFileFlags_Default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MusicSequenceFileFlags@kMusicSequenceFileFlags_Default",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kMusicSequenceFileFlags_Default"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMusicSequenceFileFlags_Default"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kMusicSequenceFileFlags_Default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kMusicSequenceFileFlags_Default"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a MIDI file from the events in a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreate"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreate(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreate(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a data object containing the events from a music sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MusicSequence",
          "text": "MusicSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileTypeID",
          "text": "MusicSequenceFileTypeID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MusicSequenceFileFlags",
          "text": "MusicSequenceFileFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileCreateData"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileCreateData(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefilecreatedata(_:_:_:_:_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags": {
      "abstract": [
        {
          "text": "Flags that configure the behavior of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreate(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileCreateData(_:_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MusicSequenceFileFlags"
        }
      ],
      "role": "symbol",
      "title": "MusicSequenceFileFlags",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileflags"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags/kMusicSequenceFileFlags_Default": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMusicSequenceFileFlags_Default"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/MusicSequenceFileFlags/kMusicSequenceFileFlags_Default",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMusicSequenceFileFlags_Default",
      "type": "topic",
      "url": "/documentation/audiotoolbox/musicsequencefileflags/kmusicsequencefileflags_default"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreate(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/title",
          "value": "MusicSequenceFileFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/title",
          "value": "MusicSequenceFileCreateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1MusicSequenceFileCreateData(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MusicSequenceFileCreateData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/musicsequencefileflags/kmusicsequencefileflags_default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
