{
  "abstract": [
    {
      "text": "A policy where a web view that’s not in a window limits processing, but does not fully suspend tasks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKInactiveSchedulingPolicy@WKInactiveSchedulingPolicyThrottle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "throttle"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKInactiveSchedulingPolicyThrottle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKPreferences.InactiveSchedulingPolicy.throttle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "throttle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences": {
      "abstract": [
        {
          "text": "An object that encapsulates the standard behaviors to apply to websites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKPreferences"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum": {
      "abstract": [
        {
          "text": "An enumeration that lists policies for how a web view that’s not in a window handles tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InactiveSchedulingPolicy"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InactiveSchedulingPolicy"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window runs tasks normally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicyNone"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.none",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/none"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window fully suspends tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspend"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicySuspend"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.suspend",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/suspend"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle": {
      "abstract": [
        {
          "text": "A policy where a web view that’s not in a window limits processing, but does not fully suspend tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "throttle"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/throttle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInactiveSchedulingPolicyThrottle"
        }
      ],
      "role": "symbol",
      "title": "WKPreferences.InactiveSchedulingPolicy.throttle",
      "type": "topic",
      "url": "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/throttle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scheduling-policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
        "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend"
      ],
      "title": "Scheduling policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKInactiveSchedulingPolicyThrottle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicyThrottle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scheduling-policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/none",
                "doc://com.apple.webkit/documentation/WebKit/WKPreferences/InactiveSchedulingPolicy-swift.enum/suspend"
              ],
              "title": "Scheduling policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKInactiveSchedulingPolicyThrottle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1throttle/title",
          "value": "WKInactiveSchedulingPolicyThrottle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1throttle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicyThrottle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/title",
          "value": "WKInactiveSchedulingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/title",
          "value": "WKPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1none/title",
          "value": "WKInactiveSchedulingPolicyNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicyNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1suspend/title",
          "value": "WKInactiveSchedulingPolicySuspend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKPreferences~1InactiveSchedulingPolicy-swift.enum~1suspend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInactiveSchedulingPolicySuspend"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/throttle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkpreferences/inactiveschedulingpolicy-swift.enum/throttle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
