{
  "abstract": [
    {
      "text": "The mouse is over an icon.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFAreaOfInterest@kPDFIconArea",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "iconArea"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PDFAreaOfInterest",
        "text": "PDFAreaOfInterest"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kPDFIconArea"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "iconArea"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "iconArea"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PDFAreaOfInterest",
              "text": "PDFAreaOfInterest"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest": {
      "abstract": [
        {
          "text": "The mouse position over PDF view areas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAreaOfInterest"
        }
      ],
      "role": "symbol",
      "title": "PDFAreaOfInterest",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea": {
      "abstract": [
        {
          "text": "The mouse is over an annotation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "annotationArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFAnnotationArea"
        }
      ],
      "role": "symbol",
      "title": "annotationArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/annotationarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea": {
      "abstract": [
        {
          "text": "The mouse is over a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFControlArea"
        }
      ],
      "role": "symbol",
      "title": "controlArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/controlarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea": {
      "abstract": [
        {
          "text": "The mouse is over an icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/iconArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFIconArea"
        }
      ],
      "role": "symbol",
      "title": "iconArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/iconarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea": {
      "abstract": [
        {
          "text": "The mouse is over an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFImageArea"
        }
      ],
      "role": "symbol",
      "title": "imageArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/imagearea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea": {
      "abstract": [
        {
          "text": "The mouse is over an undefined area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kPDFNoArea"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea",
      "kind": "symbol",
      "role": "symbol",
      "title": "kPDFNoArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/kpdfnoarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea": {
      "abstract": [
        {
          "text": "The mouse is over a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFLinkArea"
        }
      ],
      "role": "symbol",
      "title": "linkArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/linkarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea": {
      "abstract": [
        {
          "text": "The mouse is over a page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFPageArea"
        }
      ],
      "role": "symbol",
      "title": "pageArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/pagearea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea": {
      "abstract": [
        {
          "text": "The mouse is over a popup menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popupArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFPopupArea"
        }
      ],
      "role": "symbol",
      "title": "popupArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/popuparea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea": {
      "abstract": [
        {
          "text": "The mouse is over text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextArea"
        }
      ],
      "role": "symbol",
      "title": "textArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/textarea"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea": {
      "abstract": [
        {
          "text": "The mouse is over a text field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textFieldArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PDFAreaOfInterest",
          "text": "PDFAreaOfInterest"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFTextFieldArea"
        }
      ],
      "role": "symbol",
      "title": "textFieldArea",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfareaofinterest/textfieldarea"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kPDFIconArea"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFIconArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/kPDFNoArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/pageArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/annotationArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/linkArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/controlArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/textFieldArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/popupArea",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAreaOfInterest/imageArea"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kPDFIconArea"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1controlArea/title",
          "value": "kPDFControlArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1controlArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFControlArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1annotationArea/title",
          "value": "kPDFAnnotationArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1annotationArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFAnnotationArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1linkArea/title",
          "value": "kPDFLinkArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1linkArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFLinkArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1popupArea/title",
          "value": "kPDFPopupArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1popupArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFPopupArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textArea/title",
          "value": "kPDFTextArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textFieldArea/title",
          "value": "kPDFTextFieldArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1textFieldArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFTextFieldArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1iconArea/title",
          "value": "kPDFIconArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1iconArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFIconArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1imageArea/title",
          "value": "kPDFImageArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1imageArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFImageArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/title",
          "value": "PDFAreaOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAreaOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1pageArea/title",
          "value": "kPDFPageArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAreaOfInterest~1pageArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFPageArea"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfareaofinterest/iconarea"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfareaofinterest/iconarea"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
