{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the canvas accepts input from the user’s finger in addition to Apple Pencil.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/allowsFingerDrawing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PKCanvasView(py)allowsFingerDrawing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowsFingerDrawing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "allowsFingerDrawing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "message": "Use 'drawingPolicy' property.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.0",
        "message": "Use 'drawingPolicy' property.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "message": "Use 'drawingPolicy' property.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use 'drawingPolicy' property.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "allowsFingerDrawing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowsFingerDrawing"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView": {
      "abstract": [
        {
          "text": "A view that captures Apple Pencil input and displays the rendered results in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasView"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasView",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/allowsFingerDrawing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the canvas accepts input from the user’s finger in addition to Apple Pencil.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsFingerDrawing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/allowsFingerDrawing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsFingerDrawing"
        }
      ],
      "role": "symbol",
      "title": "allowsFingerDrawing",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/allowsfingerdrawing"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy": {
      "abstract": [
        {
          "text": "The policy that controls the types of touches allowed when drawing on the canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawingPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKCanvasViewDrawingPolicy",
          "text": "PKCanvasViewDrawingPolicy"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawingPolicy"
        }
      ],
      "role": "symbol",
      "title": "drawingPolicy",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/drawingpolicy"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/isRulerActive": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a ruler view is visible on the canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRulerActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/isRulerActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rulerActive"
        }
      ],
      "role": "symbol",
      "title": "isRulerActive",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/isruleractive"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-1kj57": {
      "abstract": [
        {
          "text": "The currently selected tool used for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tool"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit6PKToolP",
          "text": "PKTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-1kj57",
      "kind": "symbol",
      "role": "symbol",
      "title": "tool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/tool-1kj57"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-6str6": {
      "abstract": [
        {
          "text": "The currently selected tool used for drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "tool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-6str6",
      "kind": "symbol",
      "role": "symbol",
      "title": "tool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasview/tool-6str6"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDrawingPolicy": {
      "abstract": [
        {
          "text": "Constants that you use to specify the type of drawing gestures your app permits while the user draws on the canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKCanvasViewDrawingPolicy"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDrawingPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKCanvasViewDrawingPolicy"
        }
      ],
      "role": "symbol",
      "title": "PKCanvasViewDrawingPolicy",
      "type": "topic",
      "url": "/documentation/pencilkit/pkcanvasviewdrawingpolicy"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-drawing-environment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-1kj57",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/isRulerActive",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDrawingPolicy"
      ],
      "title": "Configuring the drawing environment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "allowsFingerDrawing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsFingerDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pencilkit/documentation/PencilKit",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-drawing-environment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/tool-6str6",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/isRulerActive",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy",
                "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasViewDrawingPolicy"
              ],
              "title": "Configuring the drawing environment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "allowsFingerDrawing"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKCanvasView/drawingPolicy",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/title",
          "value": "PKCanvasView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1allowsFingerDrawing/title",
          "value": "allowsFingerDrawing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1allowsFingerDrawing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsFingerDrawing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDrawingPolicy/title",
          "value": "PKCanvasViewDrawingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDrawingPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDrawingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasViewDrawingPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKCanvasViewDrawingPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1isRulerActive/title",
          "value": "rulerActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1isRulerActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rulerActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1drawingPolicy/title",
          "value": "drawingPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKCanvasView~1drawingPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "drawingPolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pkcanvasview/allowsfingerdrawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pencilkit/pkcanvasview/allowsfingerdrawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
