{
  "abstract": [
    {
      "text": "An option specifying that views should hide their text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideText"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSUserInterfaceCompressionOptions(cpy)hideTextOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hideText"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
        "text": "NSUserInterfaceCompressionOptions"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "hideTextOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "hideText"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hideText"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
              "text": "NSUserInterfaceCompressionOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions": {
      "abstract": [
        {
          "text": "An object that specifies how user interface elements resize themselves when space is constrained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "role": "symbol",
      "title": "NSUserInterfaceCompressionOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/breakEqualWidths": {
      "abstract": [
        {
          "text": "An option specifying that views should no longer maintain equal width constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breakEqualWidths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/breakEqualWidths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "breakEqualWidthsOption"
        }
      ],
      "role": "symbol",
      "title": "breakEqualWidths",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions/breakequalwidths"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideImages": {
      "abstract": [
        {
          "text": "An option specifying that views should hide their images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hideImagesOption"
        }
      ],
      "role": "symbol",
      "title": "hideImages",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions/hideimages"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideText": {
      "abstract": [
        {
          "text": "An option specifying that views should hide their text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hideText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hideTextOption"
        }
      ],
      "role": "symbol",
      "title": "hideText",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions/hidetext"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/reduceMetrics": {
      "abstract": [
        {
          "text": "An option specifying that views should reduce their internal metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduceMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/reduceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reduceMetricsOption"
        }
      ],
      "role": "symbol",
      "title": "reduceMetrics",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions/reducemetrics"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/standardOptions": {
      "abstract": [
        {
          "text": "An option that represents the union of all standard compression options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standardOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
          "text": "NSUserInterfaceCompressionOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/standardOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardOptions"
        }
      ],
      "role": "symbol",
      "title": "standardOptions",
      "type": "topic",
      "url": "/documentation/appkit/nsuserinterfacecompressionoptions/standardoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-standard-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideImages",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/reduceMetrics",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/breakEqualWidths",
        "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/standardOptions"
      ],
      "title": "Creating standard options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "hideTextOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hideTextOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-standard-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/hideImages",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/reduceMetrics",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/breakEqualWidths",
                "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions/standardOptions"
              ],
              "title": "Creating standard options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSUserInterfaceCompressionOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSUserInterfaceCompressionOptions",
                    "text": "NSUserInterfaceCompressionOptions"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "hideTextOption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1breakEqualWidths/title",
          "value": "breakEqualWidthsOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1breakEqualWidths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "breakEqualWidthsOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/title",
          "value": "NSUserInterfaceCompressionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUserInterfaceCompressionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1hideImages/title",
          "value": "hideImagesOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1hideImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hideImagesOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1standardOptions/title",
          "value": "standardOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1standardOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1hideText/title",
          "value": "hideTextOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1hideText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hideTextOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1reduceMetrics/title",
          "value": "reduceMetricsOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSUserInterfaceCompressionOptions~1reduceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reduceMetricsOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsuserinterfacecompressionoptions/hidetext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsuserinterfacecompressionoptions/hidetext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
