{
  "abstract": [
    {
      "text": "Signifies the system added a collaborator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/addedCollaborator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SWHighlightMembershipEventTrigger@SWHighlightMembershipEventTriggerAddedCollaborator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "addedCollaborator"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWHighlightMembershipEventTriggerAddedCollaborator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SWHighlightMembershipEventTrigger.addedCollaborator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "addedCollaborator"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger": {
      "abstract": [
        {
          "text": "The type of membership event for the highlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightMembershipEventTrigger"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightMembershipEventTrigger"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightMembershipEventTrigger",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightmembershipeventtrigger"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/addedCollaborator": {
      "abstract": [
        {
          "text": "Signifies the system added a collaborator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addedCollaborator"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/addedCollaborator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightMembershipEventTriggerAddedCollaborator"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightMembershipEventTrigger.addedCollaborator",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightmembershipeventtrigger/addedcollaborator"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/removedCollaborator": {
      "abstract": [
        {
          "text": "Signifies the system removed a collaborator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removedCollaborator"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/removedCollaborator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightMembershipEventTriggerRemovedCollaborator"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightMembershipEventTrigger.removedCollaborator",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightmembershipeventtrigger/removedcollaborator"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app": {
      "abstract": [
        {
          "text": "Integrate your custom collaboration app with Messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-custom-collaboration-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding custom collaboration to your app",
      "type": "topic",
      "url": "/documentation/sharedwithyou/adding-custom-collaboration-to-your-app"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app": {
      "abstract": [
        {
          "text": "Manage shared content collaboration in your app using CloudKit and iCloud Drive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/adding-shared-content-collaboration-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding shared content collaboration to your app",
      "type": "topic",
      "url": "/documentation/sharedwithyou/adding-shared-content-collaboration-to-your-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collaborator-actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/removedCollaborator"
      ],
      "title": "Collaborator actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWHighlightMembershipEventTriggerAddedCollaborator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightMembershipEventTriggerAddedCollaborator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collaborator-actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightMembershipEventTrigger/removedCollaborator"
              ],
              "title": "Collaborator actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SWHighlightMembershipEventTriggerAddedCollaborator"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger/title",
          "value": "SWHighlightMembershipEventTrigger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightMembershipEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightMembershipEventTrigger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger~1removedCollaborator/title",
          "value": "SWHighlightMembershipEventTriggerRemovedCollaborator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger~1removedCollaborator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightMembershipEventTriggerRemovedCollaborator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger~1addedCollaborator/title",
          "value": "SWHighlightMembershipEventTriggerAddedCollaborator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightMembershipEventTrigger~1addedCollaborator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightMembershipEventTriggerAddedCollaborator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightmembershipeventtrigger/addedcollaborator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightmembershipeventtrigger/addedcollaborator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
