{
  "abstract": [
    {
      "text": "A performance measurement where a larger value, relative to a set baseline, indicates better performance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCTPerformanceMeasurementPolarity@XCTPerformanceMeasurementPolarityPrefersLarger",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "prefersLarger"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "XCTPerformanceMeasurement.Polarity.prefersLarger"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "prefersLarger"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement": {
      "abstract": [
        {
          "text": "A measurement from a single iteration of a performance test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurement"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum": {
      "abstract": [
        {
          "text": "Constants that state whether larger or smaller measurements, relative to a set baseline, indicate better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Polarity"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger": {
      "abstract": [
        {
          "text": "A performance measurement where a larger value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersLarger"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersLarger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.prefersLarger",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferslarger"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller": {
      "abstract": [
        {
          "text": "A performance measurement where a smaller value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersSmaller"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityPrefersSmaller"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.prefersSmaller",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferssmaller"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified": {
      "abstract": [
        {
          "text": "A performance measurement that doesn’t specify whether a larger or smaller value, relative to a set baseline, indicates better performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCTPerformanceMeasurementPolarityUnspecified"
        }
      ],
      "role": "symbol",
      "title": "XCTPerformanceMeasurement.Polarity.unspecified",
      "type": "topic",
      "url": "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Polarity-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
        "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified"
      ],
      "title": "Polarity Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCTPerformanceMeasurementPolarityPrefersLarger"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Polarity-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/prefersSmaller",
                "doc://com.apple.xctest/documentation/XCTest/XCTPerformanceMeasurement/Polarity-swift.enum/unspecified"
              ],
              "title": "Polarity Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersLarger/title",
          "value": "XCTPerformanceMeasurementPolarityPrefersLarger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersLarger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityPrefersLarger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/title",
          "value": "XCTPerformanceMeasurementPolarity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/title",
          "value": "XCTPerformanceMeasurement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1unspecified/title",
          "value": "XCTPerformanceMeasurementPolarityUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersSmaller/title",
          "value": "XCTPerformanceMeasurementPolarityPrefersSmaller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCTPerformanceMeasurement~1Polarity-swift.enum~1prefersSmaller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCTPerformanceMeasurementPolarityPrefersSmaller"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferslarger"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xctperformancemeasurement/polarity-swift.enum/preferslarger"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
