{
  "abstract": [
    {
      "text": "User resolutions for fall detection events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMotion",
    "externalID": "c:@E@CMFallDetectionEventUserResolution",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UserResolution"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UserResolution"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CMFallDetectionEvent.UserResolution"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UserResolution"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The resolution of an event reflects the user’s action in response to the fall detection notification. For example, the user might tap a button to respond inside the notification, or press the digital crown to dismiss the notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent": {
      "abstract": [
        {
          "text": "An object that contains data about a fall detection event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFallDetectionEvent"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEvent"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution": {
      "abstract": [
        {
          "text": "User resolutions for fall detection events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UserResolution"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UserResolution"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent.UserResolution",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/confirmed": {
      "abstract": [
        {
          "text": "The user confirmed the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmed"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/confirmed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEventUserResolutionConfirmed"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent.UserResolution.confirmed",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution/confirmed"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/dismissed": {
      "abstract": [
        {
          "text": "The user dismissed the fall event alert, but didn’t explicitly confirm or reject the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissed"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/dismissed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEventUserResolutionDismissed"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent.UserResolution.dismissed",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution/dismissed"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution/init(rawvalue:)"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/rejected": {
      "abstract": [
        {
          "text": "The user rejected the fall event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rejected"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/rejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEventUserResolutionRejected"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent.UserResolution.rejected",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution/rejected"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/unresponsive": {
      "abstract": [
        {
          "text": "The user didn’t respond to the fall event and the system hasn’t detected recovery motions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unresponsive"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/unresponsive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFallDetectionEventUserResolutionUnresponsive"
        }
      ],
      "role": "symbol",
      "title": "CMFallDetectionEvent.UserResolution.unresponsive",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/userresolution/unresponsive"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/resolution": {
      "abstract": [
        {
          "text": "The event’s resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CMFallDetectionEvent",
          "text": "CMFallDetectionEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMFallDetectionEventUserResolution",
          "text": "UserResolution"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/resolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolution"
        }
      ],
      "role": "symbol",
      "title": "resolution",
      "type": "topic",
      "url": "/documentation/coremotion/cmfalldetectionevent/resolution"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Fall-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/resolution"
      ],
      "title": "Accessing Fall Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolutions",
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/confirmed",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/dismissed",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/rejected",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/unresponsive"
      ],
      "title": "Resolutions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMFallDetectionEventUserResolution"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolutions",
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/confirmed",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/dismissed",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/rejected",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/UserResolution/unresponsive"
              ],
              "title": "Resolutions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Fall-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMFallDetectionEvent/resolution"
              ],
              "title": "Accessing Fall Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMFallDetectionEventUserResolution"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/title",
          "value": "CMFallDetectionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1rejected/title",
          "value": "CMFallDetectionEventUserResolutionRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1rejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolutionRejected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution/title",
          "value": "CMFallDetectionEventUserResolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1dismissed/title",
          "value": "CMFallDetectionEventUserResolutionDismissed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1dismissed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolutionDismissed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1resolution/title",
          "value": "resolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1resolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1confirmed/title",
          "value": "CMFallDetectionEventUserResolutionConfirmed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1confirmed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolutionConfirmed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1unresponsive/title",
          "value": "CMFallDetectionEventUserResolutionUnresponsive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMFallDetectionEvent~1UserResolution~1unresponsive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFallDetectionEventUserResolutionUnresponsive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmfalldetectionevent/userresolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmfalldetectionevent/userresolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
