{
  "abstract": [
    {
      "text": "Learn about important changes to AVFoundation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/AVFoundation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "AVFoundation updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFoundation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "June-2024",
          "level": 2,
          "text": "June 2024",
          "type": "heading"
        },
        {
          "anchor": "Assets",
          "level": 3,
          "text": "Assets",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Preserve HDR data when generating images with ",
                      "type": "text"
                    },
                    {
                      "code": "AVAssetImageGenerator",
                      "type": "codeVoice"
                    },
                    {
                      "text": " by setting the value of its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to match the source video.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Export media asynchronously using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/export(to:as:isolation:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". You can monitor the progress of an export by calling the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/states(updateInterval:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method and awaiting its results.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Determine whether an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " decodes its data using a Media Extension by inspecting its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Camera",
          "level": 3,
          "text": "Camera",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Show your camera app on the Lock Screen by adopting the  ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/LockedCameraCapture",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " framework.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Capture photos in constant color by configuring a photo output’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCapturePhotoOutput/isConstantColorEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Continue background audio playback while performing audio and video capture by enabling a capture session’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/configuresApplicationAudioSessionToMixWithOthers",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pause and resume video recording in iOS when using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureFileOutput",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Support enhanced video stabilization using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure a capture device to automatically adjust its frame rate based on lighting conditions by enabling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isAutoVideoFrameRateEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure a capture device to replace background content in macOS by enabling its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isBackgroundReplacementEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Playback",
          "level": 3,
          "text": "Playback",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Build playback apps using the latest Swift Concurrency features due to enhanced ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Swift/Sendable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " adoption throughout the playback APIs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Capture performance and playback metrics using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetrics",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Receive rendered captions for the currently playing media using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Simplify handling of interstitial content by using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send Common Media Client Data (CMCD) as HTTP headers by enabling the new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader/sendsCommonMediaClientDataAsHTTPHeaders",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.Updates/documentation/Updates/CoreLocation": {
      "abstract": [
        {
          "text": "Learn about important changes to Core Location.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/CoreLocation",
      "kind": "article",
      "role": "article",
      "title": "Core Location updates",
      "type": "topic",
      "url": "/documentation/updates/corelocation"
    },
    "doc://com.apple.documentation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/AVFoundation"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession": {
      "abstract": [
        {
          "text": "An object that exports assets in a format that you specify using an export preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetExportSession",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetExportSession"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/export(to:as:isolation:)": {
      "abstract": [
        {
          "text": "Exports the asset to the output location in the specified file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "export"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "fileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isolation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "isolated"
        },
        {
          "kind": "text",
          "text": " (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ScA",
          "text": "Actor"
        },
        {
          "kind": "text",
          "text": ")? = #isolation) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/export(to:as:isolation:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "export(to:as:isolation:)",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetExportSession/export(to:as:isolation:)"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/states(updateInterval:)": {
      "abstract": [
        {
          "text": "Monitors the progress state of an export operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "states"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "updateInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": " = .infinity) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sci",
          "text": "AsyncSequence"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetExportSession",
          "text": "AVAssetExportSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So20AVAssetExportSessionC12AVFoundationE5StateO",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        },
        {
          "kind": "text",
          "text": ">\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetExportSession/states(updateInterval:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "states(updateInterval:)",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetExportSession/states(updateInterval:)"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property": {
      "abstract": [
        {
          "text": "The dynamic range policy to use when generating images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamicRangePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetImageGenerator",
          "text": "AVAssetImageGenerator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAssetImageGeneratorDynamicRangePolicy",
          "text": "DynamicRangePolicy"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "dynamicRangePolicy",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetImageGenerator/dynamicRangePolicy-swift.property"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader": {
      "abstract": [
        {
          "text": "An object that mediates resource requests from a URL asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetResourceLoader"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAssetResourceLoader",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetResourceLoader"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader/sendsCommonMediaClientDataAsHTTPHeaders": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to enable attaching Common Media Client Data as HTTP request headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendsCommonMediaClientDataAsHTTPHeaders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAssetResourceLoader/sendsCommonMediaClientDataAsHTTPHeaders",
      "kind": "symbol",
      "role": "symbol",
      "title": "sendsCommonMediaClientDataAsHTTPHeaders",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAssetResourceLoader/sendsCommonMediaClientDataAsHTTPHeaders"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isAutoVideoFrameRateEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the capture device performs automatic video frame rate adjustments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAutoVideoFrameRateEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isAutoVideoFrameRateEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAutoVideoFrameRateEnabled",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/isAutoVideoFrameRateEnabled"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isBackgroundReplacementEnabled": {
      "abstract": [
        {
          "text": "A class property that indicates whether a person enables the Background Replacement feature for this app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBackgroundReplacementEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/isBackgroundReplacementEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isBackgroundReplacementEnabled",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/isBackgroundReplacementEnabled"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureFileOutput": {
      "abstract": [
        {
          "text": "The abstract superclass for capture outputs that can record captured data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutput"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureFileOutput",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureFileOutput",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureFileOutput"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCapturePhotoOutput/isConstantColorEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the photo output configures the render pipeline to perform constant color capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isConstantColorEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCapturePhotoOutput/isConstantColorEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isConstantColorEnabled",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCapturePhotoOutput/isConstantColorEnabled"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/configuresApplicationAudioSessionToMixWithOthers": {
      "abstract": [
        {
          "text": "A Boolean value that Indicates whether the capture session configures the app’s audio session to mix with others.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuresApplicationAudioSessionToMixWithOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureSession/configuresApplicationAudioSessionToMixWithOthers",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuresApplicationAudioSessionToMixWithOthers",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureSession/configuresApplicationAudioSessionToMixWithOthers"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced": {
      "abstract": [
        {
          "text": "A mode that stabilizes video using the enhanced extended cinematic stabilization algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cinematicExtendedEnhanced"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureVideoStabilizationMode.cinematicExtendedEnhanced",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureVideoStabilizationMode/cinematicExtendedEnhanced"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetricEvent",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetrics",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVMetrics"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline": {
      "abstract": [
        {
          "text": "An object that models the timeline and playback sequence of a primary player item and scheduled interstitial events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemIntegratedTimeline"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemIntegratedTimeline",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerItemIntegratedTimeline",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItemIntegratedTimeline"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput": {
      "abstract": [
        {
          "text": "A player item output that vends media with a legible characteristic as rendered pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemRenderedLegibleOutput"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerItemRenderedLegibleOutput",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset": {
      "abstract": [
        {
          "text": "An asset that represents media at a local or remote URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVURLAsset",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVURLAsset"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties": {
      "abstract": [
        {
          "text": "The properties of the media extension format reader that decodes the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaExtensionProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaExtensionProperties",
          "text": "AVMediaExtensionProperties"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaExtensionProperties",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties"
    },
    "doc://com.apple.documentation/documentation/LockedCameraCapture": {
      "abstract": [
        {
          "text": "Capture content with your app’s camera experience when the device is locked.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/LockedCameraCapture",
      "kind": "symbol",
      "role": "collection",
      "title": "LockedCameraCapture",
      "type": "topic",
      "url": "/documentation/LockedCameraCapture"
    },
    "doc://com.apple.documentation/documentation/Swift/Sendable": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Sendable",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI",
        "doc://com.apple.Updates/documentation/Updates/CoreLocation"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVAssetExportSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/title",
          "value": "AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureVideoStabilizationMode~1cinematicExtendedEnhanced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureVideoStabilizationModeCinematicExtendedEnhanced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItemIntegratedTimeline/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItemIntegratedTimeline"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItemRenderedLegibleOutput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVPlayerItemOutput",
              "text": "AVPlayerItemOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isConstantColorEnabled/title",
          "value": "constantColorEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1isConstantColorEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isConstantColorEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "constantColorEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoVideoFrameRateEnabled/title",
          "value": "autoVideoFrameRateEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoVideoFrameRateEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isAutoVideoFrameRateEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "autoVideoFrameRateEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureSession~1configuresApplicationAudioSessionToMixWithOthers/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configuresApplicationAudioSessionToMixWithOthers"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVAssetResourceLoader/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAssetResourceLoader"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVURLAsset/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAsset",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVAssetImageGenerator~1dynamicRangePolicy-swift.property/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVAssetImageGeneratorDynamicRangePolicy",
              "text": "AVAssetImageGeneratorDynamicRangePolicy"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dynamicRangePolicy"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureFileOutput/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutput"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureOutput",
              "text": "AVCaptureOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVURLAsset~1mediaExtensionProperties/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVMediaExtensionProperties",
              "text": "AVMediaExtensionProperties"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "mediaExtensionProperties"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVAssetResourceLoader~1sendsCommonMediaClientDataAsHTTPHeaders/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sendsCommonMediaClientDataAsHTTPHeaders"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1isBackgroundReplacementEnabled/title",
          "value": "backgroundReplacementEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1isBackgroundReplacementEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isBackgroundReplacementEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "backgroundReplacementEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/avfoundation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
