{
  "abstract": [
    {
      "text": "Learn about the latest changes to enabling your app to be the system default.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/DefaultApps"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Default apps updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Build apps and extensions that people can configure as the default app for many common tasks. Browse ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that enable your apps to declare that they can be set as the system default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/openSettingsURLString",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to link directly to your app’s settings, including the Default App option, where applicable. The new ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/openDefaultApplicationsSettingsURLString",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " option in ",
                      "type": "text"
                    },
                    {
                      "code": "UIKit",
                      "type": "codeVoice"
                    },
                    {
                      "text": " opens the global Default Apps settings panel.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "2025",
          "level": 2,
          "text": "2025",
          "type": "heading"
        },
        {
          "anchor": "Navigation-apps",
          "level": 3,
          "text": "Navigation apps",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Read ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to see how to register your app to be the default responder to navigation requests for users in the European Union. This article explains how to use the ",
                      "type": "text"
                    },
                    {
                      "code": "geo-navigation://",
                      "type": "codeVoice"
                    },
                    {
                      "text": " URL scheme to handle navigation queries the user initiates from other apps.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Translation-apps",
          "level": 3,
          "text": "Translation apps",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Learn about",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/TranslationUIProvider/Preparing-your-app-to-be-the-default-translation-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " so that your translation app can respond to user requests to perform text translation.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "2024",
          "level": 2,
          "text": "2024",
          "type": "heading"
        },
        {
          "anchor": "Alternative-app-marketplaces",
          "level": 3,
          "text": "Alternative app marketplaces",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Alternative app marketplace apps for iOS or iPadOS enable users to install other third-party apps in the European Union. Developers can distribute their marketplace app on the web, and users can then select the alternative marketplace as their default, if desired. Apple provides the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework that facilitates the secure installation of apps that your marketplace distributes. Read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to learn how to build your own marketplace.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Learn about the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement used by alternative app marketplaces.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Read  ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/appdistribution/distributing-your-app-from-your-website",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to learn how to ship the alternative app marketplace.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Calling-apps",
          "level": 3,
          "text": "Calling apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS and iPadOS 18.2 and later, a user may select an app other than the Phone or FaceTime apps to place calls. If your app places phone calls, for instance using services such as Voice over IP (VoIP), and you wish to optionally become the default calling app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Contactless-NFC-and-SE-platform-apps",
          "level": 3,
          "text": "Contactless NFC and SE platform apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS 18.1 introduced APIs that support secure contactless transactions within compatible iOS apps using the NFC & SE Platform for in-store payments, car keys, closed-loop transit, corporate badges, student IDs, home keys, hotel keys, merchant loyalty and rewards, and event tickets, with government IDs to be available at a later date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The NFC & SE Platform is a secure solution developed by Apple that enables authorized developers to provide capabilities, such as securely adding, storing, and presenting a contactless card for NFC use cases, from within their iOS app. Supported NFC and SE platform apps can be selected by users as their default handler for these transactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To learn more about the NFC and SE Platform see  ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/support/nfc-se-platform/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Manage and employ Secure Element credentials with contactless transaction capabilities using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SecureElementCredential",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enable your app to be the default app for contactless NFC and SE Platform transactions with the    ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.secure-element-credential.default-contactless-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "HCE-based-contactless-transactions-for-apps",
          "level": 3,
          "text": "HCE-based contactless transactions for apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS 17.4 introduced APIs that support contactless transactions for in-store payments, car keys, tickets, and more uses from within compatible iOS apps using host card emulation (HCE) in the European Economic Area (EEA).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreNFC/CardSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " API in the CoreNFC framework enables authorized developers to perform contactless transactions from within their app. Supported ",
              "type": "text"
            },
            {
              "code": "CardSession",
              "type": "codeVoice"
            },
            {
              "text": " apps can be selected by users as their default handler for these transactions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Learn about host card emulation apps by reading ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/support/hce-transactions-in-apps/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreNFC/CardSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to enable host card emulation (HCE) transactions in your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Enable your app to be the default app for HCE-based contactless NFC with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Messaging-apps",
          "level": 3,
          "text": "Messaging apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS and iPadOS 18.2 and later, a user may select an app other than the Messages app to send instant messages. The system launches the default messaging app to handle when a user taps an ",
              "type": "text"
            },
            {
              "code": "im:",
              "type": "codeVoice"
            },
            {
              "text": " link from another app. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes how to enable your app to optionally be selected as the default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "2023-and-earlier",
          "level": 2,
          "text": "2023 and earlier",
          "type": "heading"
        },
        {
          "anchor": "Call-Directory-app-extensions",
          "level": 3,
          "text": "Call Directory app extensions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Build a Call Directory app extension so a user’s device can automatically use your app to look up incoming callers, present useful caller ID information, or block unwanted callers. Read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CallKit/identifying-and-blocking-calls",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information on creating these app extensions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can specify that your Call Directory app extension adds identification and blocks phone numbers in its implementation of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryProvider/beginRequest(with:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To block incoming calls for a specific phone number, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryExtensionContext/addBlockingEntry(withNextSequentialPhoneNumber:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method in the implementation of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryProvider/beginRequest(with:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Keyboard-apps",
          "level": 3,
          "text": "Keyboard apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use custom keyboard apps and extensions to replace the system keyboard for users that want different text-entry capabilities, such as a novel input method. People can choose to have this custom keyboard available systemwide, and select the default keyboard used in text fields. Read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-a-custom-keyboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for information on how to build and configure your custom keyboard app and extension project.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For more information on handling expected system behaviors in your custom keyboard, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/configuring-a-custom-keyboard-interface",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Mail-apps",
          "level": 3,
          "text": "Mail apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system launches the default mail client whenever a user opens a ",
              "type": "text"
            },
            {
              "code": "mailto:",
              "type": "codeVoice"
            },
            {
              "text": " link. Signal your app’s intent to be available as a default mail client by using the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.mail-client",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Password-credential-and-verification-code-apps",
          "level": 3,
          "text": "Password, credential, and verification code apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Password managers, verification code providers, and other secure credential apps can include a Password AutoFill app extension to enable their app to automatically fill in a name and password within Safari and other apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Register the ",
                      "type": "text"
                    },
                    {
                      "code": "otpauth://",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "otpauth-migration://",
                      "type": "codeVoice"
                    },
                    {
                      "text": " URL scheme within your app to enable setup of verification codes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use Xcode to add a new extension target of type ",
                      "type": "text"
                    },
                    {
                      "code": "AutoFill Credential Provider",
                      "type": "codeVoice"
                    },
                    {
                      "text": " to your app’s project to enable AutoFill for secure credentials throughout the system.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For your app and app extension, use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to ask someone for permission to fill in the credentials.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Web-browser-apps",
          "level": 3,
          "text": "Web browser apps",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users can select an app to be their default web browser. To make your app available as the default browser app, confirm that your app meets the requirements below, then request a managed entitlement. See  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/preparing-your-app-to-be-the-default-browser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to learn more.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In iOS 18.2 and iPadOS 18.2, the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/isDefault(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " API allows a browser app to check if it is currently the default browser app. To reduce the likelihood that users will face continuous requests to set a browser as their default, this API will only tell the browser app if it is the default once per year.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SafariServices/importing-data-exported-from-safari",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to see how your browser app can import data the user exported from Safari.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " entitlement to enable your app to be the default web browser.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app may, with user permission, provide user names and passwords for AutoFill in Safari and other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider",
      "kind": "symbol",
      "role": "symbol",
      "title": "AutoFill Credential Provider Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.authentication-services.autofill-credential-provider"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.mail-client": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the app can act as a user’s default email client.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.mail-client",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.mail-client",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.mail-client"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation": {
      "abstract": [
        {
          "text": "The entitlement that enables an app to vend other apps as an alternative app marketplace.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.marketplace.app-installation",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.marketplace.app-installation"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether your app can be a default app for contactless NFC with the card session API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.nfc.hce.default-contactless-app",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.nfc.hce.default-contactless-app"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.secure-element-credential.default-contactless-app": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app that uses the SecureElementCredential framework can become the default contactless app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.secure-element-credential.default-contactless-app",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.secure-element-credential.default-contactless-app",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.secure-element-credential.default-contactless-app"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.web-browser": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the app can act as the user’s default web browser.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.web-browser",
      "kind": "symbol",
      "role": "symbol",
      "title": "com.apple.developer.web-browser",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.web-browser"
    },
    "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryExtensionContext/addBlockingEntry(withNextSequentialPhoneNumber:)": {
      "abstract": [
        {
          "text": "Adds a blocking entry with the specified phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addBlockingEntry"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withNextSequentialPhoneNumber"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CXCallDirectoryPhoneNumber",
          "text": "CXCallDirectoryPhoneNumber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryExtensionContext/addBlockingEntry(withNextSequentialPhoneNumber:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "addBlockingEntry(withNextSequentialPhoneNumber:)",
      "type": "topic",
      "url": "/documentation/CallKit/CXCallDirectoryExtensionContext/addBlockingEntry(withNextSequentialPhoneNumber:)"
    },
    "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryProvider/beginRequest(with:)": {
      "abstract": [
        {
          "text": "Tells the extension to prepare for a host app’s request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CXCallDirectoryExtensionContext",
          "text": "CXCallDirectoryExtensionContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit/CXCallDirectoryProvider/beginRequest(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "beginRequest(with:)",
      "type": "topic",
      "url": "/documentation/CallKit/CXCallDirectoryProvider/beginRequest(with:)"
    },
    "doc://com.apple.documentation/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app": {
      "abstract": [
        {
          "text": "Configure your CallKit or LiveCommunicationKit app so people can set it as the default calling app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default calling app",
      "type": "topic",
      "url": "/documentation/CallKit/Preparing-your-app-to-be-the-default-calling-app"
    },
    "doc://com.apple.documentation/documentation/CallKit/identifying-and-blocking-calls": {
      "abstract": [
        {
          "text": "Create a Call Directory app extension to identify and block incoming callers by their phone number.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CallKit/identifying-and-blocking-calls",
      "kind": "article",
      "role": "article",
      "title": "Identifying and blocking calls",
      "type": "topic",
      "url": "/documentation/CallKit/identifying-and-blocking-calls"
    },
    "doc://com.apple.documentation/documentation/CoreNFC/CardSession": {
      "abstract": [
        {
          "text": "An ISO 7816 card emulation session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CardSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreNFC/CardSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "CardSession",
      "type": "topic",
      "url": "/documentation/CoreNFC/CardSession"
    },
    "doc://com.apple.documentation/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app": {
      "abstract": [
        {
          "text": "Configure your navigation app so people can set it as the default on their devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default navigation app",
      "type": "topic",
      "url": "/documentation/MapKit/preparing-your-app-to-be-the-default-navigation-app"
    },
    "doc://com.apple.documentation/documentation/MarketplaceKit": {
      "abstract": [
        {
          "text": "Create an alternative app marketplace, distribute your app on an alternative app marketplace, or distribute your app from your website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MarketplaceKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MarketplaceKit",
      "type": "topic",
      "url": "/documentation/MarketplaceKit"
    },
    "doc://com.apple.documentation/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app": {
      "abstract": [
        {
          "text": "Configure your messaging app so people can set it as the default on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default messaging app",
      "type": "topic",
      "url": "/documentation/Messages/Preparing-your-app-to-be-the-default-messaging-app"
    },
    "doc://com.apple.documentation/documentation/SafariServices/importing-data-exported-from-safari": {
      "abstract": [
        {
          "text": "Transfer bookmarks, saved passwords, and other information between browsers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SafariServices/importing-data-exported-from-safari",
      "kind": "article",
      "role": "article",
      "title": "Importing data exported from Safari",
      "type": "topic",
      "url": "/documentation/SafariServices/importing-data-exported-from-safari"
    },
    "doc://com.apple.documentation/documentation/SecureElementCredential": {
      "abstract": [
        {
          "text": "Allow access to credentials inside the Secure Element on device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SecureElementCredential",
      "kind": "symbol",
      "role": "collection",
      "title": "SecureElementCredential",
      "type": "topic",
      "url": "/documentation/SecureElementCredential"
    },
    "doc://com.apple.documentation/documentation/TranslationUIProvider/Preparing-your-app-to-be-the-default-translation-app": {
      "abstract": [
        {
          "text": "Configure your app so people can set it as the default translation app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/TranslationUIProvider/Preparing-your-app-to-be-the-default-translation-app",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default translation app",
      "type": "topic",
      "url": "/documentation/TranslationUIProvider/Preparing-your-app-to-be-the-default-translation-app"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication/isDefault(_:)": {
      "abstract": [
        {
          "text": "Reports whether this app is the person’s default app in the given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDefault"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIApplicationCategory",
          "text": "Category"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/isDefault(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDefault(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication/isDefault(_:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication/openDefaultApplicationsSettingsURLString": {
      "abstract": [
        {
          "text": "The URL string used to select a default app in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openDefaultApplicationsSettingsURLString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/openDefaultApplicationsSettingsURLString",
      "kind": "symbol",
      "role": "symbol",
      "title": "openDefaultApplicationsSettingsURLString",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication/openDefaultApplicationsSettingsURLString"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplication/openSettingsURLString": {
      "abstract": [
        {
          "text": "The URL string you use to deep link to your app’s custom settings in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openSettingsURLString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplication/openSettingsURLString",
      "kind": "symbol",
      "role": "symbol",
      "title": "openSettingsURLString",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplication/openSettingsURLString"
    },
    "doc://com.apple.documentation/documentation/UIKit/configuring-a-custom-keyboard-interface": {
      "abstract": [
        {
          "text": "Design a flexible, functional, and responsive interface for editing text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/configuring-a-custom-keyboard-interface",
      "kind": "article",
      "role": "article",
      "title": "Configuring a custom keyboard interface",
      "type": "topic",
      "url": "/documentation/UIKit/configuring-a-custom-keyboard-interface"
    },
    "doc://com.apple.documentation/documentation/UIKit/creating-a-custom-keyboard": {
      "abstract": [
        {
          "text": "Add an extension to your Xcode project to provide systemwide customized text input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/creating-a-custom-keyboard",
      "kind": "article",
      "role": "article",
      "title": "Creating a custom keyboard",
      "type": "topic",
      "url": "/documentation/UIKit/creating-a-custom-keyboard"
    },
    "doc://com.apple.documentation/documentation/Xcode/preparing-your-app-to-be-the-default-browser": {
      "abstract": [
        {
          "text": "Configure your browser app so users can set it as the default on their device instead of Safari.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/preparing-your-app-to-be-the-default-browser",
      "kind": "article",
      "role": "article",
      "title": "Preparing your app to be the default web browser",
      "type": "topic",
      "url": "/documentation/Xcode/preparing-your-app-to-be-the-default-browser"
    },
    "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace": {
      "abstract": [
        {
          "text": "Enable the distribution of other third-party apps from within your marketplace app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appdistribution/creating-an-alternative-app-marketplace",
      "kind": "article",
      "role": "article",
      "title": "Creating an alternative app marketplace",
      "type": "topic",
      "url": "/documentation/appdistribution/creating-an-alternative-app-marketplace"
    },
    "doc://com.apple.documentation/documentation/appdistribution/distributing-your-app-from-your-website": {
      "abstract": [
        {
          "text": "Configure your app and website to enable people to install your app on their devices from your website.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appdistribution/distributing-your-app-from-your-website",
      "kind": "article",
      "role": "article",
      "title": "Distributing your app from your website",
      "type": "topic",
      "url": "/documentation/appdistribution/distributing-your-app-from-your-website"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    },
    "https://developer.apple.com/documentation/bundleresources/entitlements": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/entitlements",
      "title": "entitlements",
      "titleInlineContent": [
        {
          "text": "entitlements",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/entitlements"
    },
    "https://developer.apple.com/support/hce-transactions-in-apps/": {
      "identifier": "https://developer.apple.com/support/hce-transactions-in-apps/",
      "title": "https://developer.apple.com/support/hce-transactions-in-apps/",
      "titleInlineContent": [
        {
          "text": "https://developer.apple.com/support/hce-transactions-in-apps/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/hce-transactions-in-apps/"
    },
    "https://developer.apple.com/support/nfc-se-platform/": {
      "identifier": "https://developer.apple.com/support/nfc-se-platform/",
      "title": "https://developer.apple.com/support/nfc-se-platform/",
      "titleInlineContent": [
        {
          "text": "https://developer.apple.com/support/nfc-se-platform/",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/nfc-se-platform/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1openDefaultApplicationsSettingsURLString/title",
          "value": "UIApplicationOpenDefaultApplicationsSettingsURLString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1openDefaultApplicationsSettingsURLString/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationOpenDefaultApplicationsSettingsURLString"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1openSettingsURLString/title",
          "value": "UIApplicationOpenSettingsURLString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplication~1openSettingsURLString/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationOpenSettingsURLString"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CallKit~1CXCallDirectoryExtensionContext~1addBlockingEntry(withNextSequentialPhoneNumber:)/title",
          "value": "addBlockingEntryWithNextSequentialPhoneNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CallKit~1CXCallDirectoryExtensionContext~1addBlockingEntry(withNextSequentialPhoneNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "addBlockingEntryWithNextSequentialPhoneNumber:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CXCallDirectoryPhoneNumber",
              "text": "CXCallDirectoryPhoneNumber"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "phoneNumber"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CallKit~1CXCallDirectoryProvider~1beginRequest(with:)/title",
          "value": "beginRequestWithExtensionContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CallKit~1CXCallDirectoryProvider~1beginRequest(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "beginRequestWithExtensionContext:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CXCallDirectoryExtensionContext",
              "text": "CXCallDirectoryExtensionContext"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/defaultapps"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
