{
  "abstract": [
    {
      "text": "Learn about important changes to GameKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/GameKit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "GameKit updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GameKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "June-2024",
          "level": 2,
          "text": "June 2024",
          "type": "heading"
        },
        {
          "anchor": "Dashboard",
          "level": 3,
          "text": "Dashboard",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " initializer to display a set of leaderboards in the dashboard.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(player:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " initializer to display a player’s profile in the dashboard.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Voice-chat",
          "level": 3,
          "text": "Voice chat",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use SharePlay to allow voice chat in your real-time games instead of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKVoiceChat",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " which is deprecated. When you present a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchmakerViewController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, it automatically shows a SharePlay button on iOS. To implement a custom SharePlay experience, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchmaker#4110693",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/GameKit"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController": {
      "abstract": [
        {
          "text": "The dashboard that allows players to access their Game Center data in your game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKGameCenterViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKGameCenterViewController",
      "type": "topic",
      "url": "/documentation/GameKit/GKGameCenterViewController"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a leaderboard set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "leaderboardSetID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(leaderboardSetID:)",
      "type": "topic",
      "url": "/documentation/GameKit/GKGameCenterViewController/init(leaderboardSetID:)"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(player:)": {
      "abstract": [
        {
          "text": "Creates a view controller that presents a player’s Game Center profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "player"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKPlayer",
          "text": "GKPlayer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKGameCenterViewController/init(player:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(player:)",
      "type": "topic",
      "url": "/documentation/GameKit/GKGameCenterViewController/init(player:)"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKMatchmaker#4110693": {
      "abstract": [
        {
          "text": "An object that creates matches with other players without presenting an interface to the players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchmaker"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchmaker#4110693",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKMatchmaker",
      "type": "topic",
      "url": "/documentation/GameKit/GKMatchmaker"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKMatchmakerViewController": {
      "abstract": [
        {
          "text": "An interface that allows a player to invite other players to a real-time game and automatch to fill any empty slots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKMatchmakerViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKMatchmakerViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKMatchmakerViewController",
      "type": "topic",
      "url": "/documentation/GameKit/GKMatchmakerViewController"
    },
    "doc://com.apple.documentation/documentation/GameKit/GKVoiceChat": {
      "abstract": [
        {
          "text": "A voice channel that allows players to speak with each other in a multiplayer game.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKVoiceChat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GameKit/GKVoiceChat",
      "kind": "symbol",
      "role": "symbol",
      "title": "GKVoiceChat",
      "type": "topic",
      "url": "/documentation/GameKit/GKVoiceChat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardSetID:)/title",
          "value": "initWithLeaderboardSetID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKGameCenterViewController~1init(leaderboardSetID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithLeaderboardSetID:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "leaderboardSetID"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKGameCenterViewController~1init(player:)/title",
          "value": "initWithPlayer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKGameCenterViewController~1init(player:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithPlayer:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)GKPlayer",
              "text": "GKPlayer"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "player"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKMatchmaker#4110693/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKMatchmaker"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKGameCenterViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKGameCenterViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UINavigationController",
              "text": "UINavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKVoiceChat/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKVoiceChat"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1GameKit~1GKMatchmakerViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GKMatchmakerViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSViewController",
              "text": "NSViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/gamekit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
