{
  "abstract": [
    {
      "text": "Learn about important changes to HealthKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/HealthKit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "HealthKit updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/HealthKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "September-2024",
          "level": 2,
          "text": "September 2024",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apple Watch Series 10 supports the Shallow Depth and Pressure capability. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to read depth and temperature data from shallow dives.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2024",
          "level": 2,
          "text": "June 2024",
          "type": "heading"
        },
        {
          "anchor": "General",
          "level": 3,
          "text": "General",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create HealthKit apps for VisionOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Associate perceived and estimated exertion values with workouts. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338081-workouteffortscore",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338078-estimatedworkouteffortscore",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to read and write exertion data. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/4337961-relateworkouteffortsample",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to associate exertion data with a workout, and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutEffortRelationshipQuery",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to query for associated exertion data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Access water temperature data from swimming workouts. Any Apple Watch Ultra records ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " samples during swimming workouts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Read and write mental well-being samples using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKStateOfMind",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKPHQ9Assessment",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKGAD7Assessment",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " data types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Track menstrual flow and intermenstrual bleeding during pregnancy using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338072-bleedingduringpregnancy",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338071-bleedingafterpregnancy",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " data types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2023",
          "level": 3,
          "text": "June 2023",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Now available in iPadOS. Health data automatically synchronizes between a person’s iPhone, iPad, and Apple Watch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create custom, interval-based workouts. You can use either distance or time for the intervals, and sync the intervals to a group, such as a workout class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Mirror workout sessions in your iOS app. This includes the ability to control the workout session from the iOS app, and the ability to send data between the iOS and watchOS apps during an active workout session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Access batches of higher-rate motion data from Apple Watch. New Core Motion APIs provide 800 Hz accelerometer data and 200 Hz device motion data. Use this data to analyze someone’s motion after performing an action, like swinging a golf club.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Measure time spent outdoors and average light intensity with new data types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Track cycling with new data types for tracking someone’s power, speed, cadence, and functional threshold power.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/HealthKit"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKGAD7Assessment": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKGAD7Assessment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKGAD7Assessment",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKGAD7Assessment",
      "type": "topic",
      "url": "/documentation/HealthKit/HKGAD7Assessment"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKPHQ9Assessment": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKPHQ9Assessment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKPHQ9Assessment",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKPHQ9Assessment",
      "type": "topic",
      "url": "/documentation/HealthKit/HKPHQ9Assessment"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKStateOfMind": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKStateOfMind"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKStateOfMind",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKStateOfMind",
      "type": "topic",
      "url": "/documentation/HealthKit/HKStateOfMind"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutEffortRelationshipQuery": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutEffortRelationshipQuery"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutEffortRelationshipQuery",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKWorkoutEffortRelationshipQuery",
      "type": "topic",
      "url": "/documentation/HealthKit/HKWorkoutEffortRelationshipQuery"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338071-bleedingafterpregnancy": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "bleedingAfterPregnancy"
        },
        {
          "kind": "text",
          "text": ": HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338071-bleedingafterpregnancy",
      "kind": "symbol",
      "role": "symbol",
      "title": "bleedingAfterPregnancy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/4338071-bleedingafterpregnancy"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338072-bleedingduringpregnancy": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "bleedingDuringPregnancy"
        },
        {
          "kind": "text",
          "text": ": HKCategoryTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkcategorytypeidentifier/4338072-bleedingduringpregnancy",
      "kind": "symbol",
      "role": "symbol",
      "title": "bleedingDuringPregnancy",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategorytypeidentifier/4338072-bleedingduringpregnancy"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/4337961-relateworkouteffortsample": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "relateWorkoutEffortSample"
        },
        {
          "kind": "text",
          "text": "(HKSample, "
        },
        {
          "kind": "identifier",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": HKWorkout, "
        },
        {
          "kind": "identifier",
          "text": "activity"
        },
        {
          "kind": "text",
          "text": ": HKWorkoutActivity?, "
        },
        {
          "kind": "identifier",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (Bool, (any Error)?) -> Void)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/4337961-relateworkouteffortsample",
      "kind": "symbol",
      "role": "symbol",
      "title": "relateWorkoutEffortSample(_:with:activity:completion:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/4337961-relateworkouteffortsample"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth": {
      "abstract": [
        {
          "text": "A quantity sample that records a person’s depth underwater.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "underwaterDepth"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth",
      "kind": "symbol",
      "role": "symbol",
      "title": "underwaterDepth",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature": {
      "abstract": [
        {
          "text": "A quantity sample that records the water temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "waterTemperature"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
      "kind": "symbol",
      "role": "symbol",
      "title": "waterTemperature",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338078-estimatedworkouteffortscore": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "estimatedWorkoutEffortScore"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338078-estimatedworkouteffortscore",
      "kind": "symbol",
      "role": "symbol",
      "title": "estimatedWorkoutEffortScore",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/4338078-estimatedworkouteffortscore"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338081-workouteffortscore": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "workoutEffortScore"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/4338081-workouteffortscore",
      "kind": "symbol",
      "role": "symbol",
      "title": "workoutEffortScore",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/4338081-workouteffortscore"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~14338081-workouteffortscore/title",
          "value": "HKQuantityTypeIdentifierWorkoutEffortScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkcategorytypeidentifier~14338072-bleedingduringpregnancy/title",
          "value": "HKCategoryTypeIdentifierBleedingDuringPregnancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~13958703-underwaterdepth/title",
          "value": "HKQuantityTypeIdentifierUnderwaterDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~14338078-estimatedworkouteffortscore/title",
          "value": "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkhealthstore~14337961-relateworkouteffortsample/title",
          "value": "relateWorkoutEffortSample:withWorkout:activity:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKStateOfMind/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKStateOfMind"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKSample",
              "text": "HKSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKPHQ9Assessment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKPHQ9Assessment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKScoredAssessment",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkcategorytypeidentifier~14338071-bleedingafterpregnancy/title",
          "value": "HKCategoryTypeIdentifierBleedingAfterPregnancy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKGAD7Assessment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKGAD7Assessment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKScoredAssessment",
              "text": "HKScoredAssessment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKWorkoutEffortRelationshipQuery/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKWorkoutEffortRelationshipQuery"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKQuery",
              "text": "HKQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~13958704-watertemperature/title",
          "value": "HKQuantityTypeIdentifierWaterTemperature"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/healthkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
