{
  "abstract": [
    {
      "text": "Learn about important changes to SensorKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/SensorKit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "SensorKit updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SensorKit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "March-2024",
          "level": 2,
          "text": "March 2024",
          "type": "heading"
        },
        {
          "anchor": "Sensors",
          "level": 3,
          "text": "Sensors",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/electrocardiogram",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to collect electrocardiogram (ECG) data samples, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/pedometerData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/photoplethysmogram",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to collect photoplethysmogram (PPG) data samples, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramSample",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " classes to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2023",
          "level": 2,
          "text": "June 2023",
          "type": "heading"
        },
        {
          "anchor": "Sensors",
          "level": 3,
          "text": "Sensors",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/faceMetrics",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to analyze a person’s facial expressions, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRFaceMetrics",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/heartRate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to collect a person’s heart rate from devices, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/odometer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to analyze movements during workouts, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/siriSpeechMetrics",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to collect data about a person’s voice — such as tenor, pitch, and cadence — and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSpeechMetrics",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data. People who previously authorized speech metric data collection need to reauthorize before data collection can continue.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/wristTemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property to collect sequential wrist temperatures while a person is sleeping, and the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRWristTemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class to get the data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Configuration",
          "level": 3,
          "text": "Configuration",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To opt out of collecting data for user activity from sensors in your app, set the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SRResearchDataGeneration",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key to ",
                      "type": "text"
                    },
                    {
                      "code": "NO",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SRResearchDataGeneration": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether use of an app contributes data to SensorKit while the user is enrolled in a health research study.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/SRResearchDataGeneration",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRResearchDataGeneration",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/SRResearchDataGeneration"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData": {
      "abstract": [
        {
          "text": "A class that represents heart rate data collected at 1 Hz.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMHighFrequencyHeartRateData",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateData",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMHighFrequencyHeartRateData"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData": {
      "abstract": [
        {
          "text": "A class that represents odometer data for workouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMOdometerData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMOdometerData",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMOdometerData",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMOdometerData"
    },
    "doc://com.apple.documentation/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/SensorKit"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRFaceMetrics": {
      "abstract": [
        {
          "text": "An object that represents metrics about the user’s face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRFaceMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRFaceMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRFaceMetrics",
      "type": "topic",
      "url": "/documentation/SensorKit/SRFaceMetrics"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramOpticalSample": {
      "abstract": [
        {
          "text": "A data sample from the photoplethysmogram (PPG) optical sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramOpticalSample"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramOpticalSample",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRPhotoplethysmogramOpticalSample",
      "type": "topic",
      "url": "/documentation/SensorKit/SRPhotoplethysmogramOpticalSample"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramSample": {
      "abstract": [
        {
          "text": "The sample photoplethysmogram (PPG) sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRPhotoplethysmogramSample"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRPhotoplethysmogramSample",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRPhotoplethysmogramSample",
      "type": "topic",
      "url": "/documentation/SensorKit/SRPhotoplethysmogramSample"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/electrocardiogram": {
      "abstract": [
        {
          "text": "A sensor that streams sample ECG sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electrocardiogram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/electrocardiogram",
      "kind": "symbol",
      "role": "symbol",
      "title": "electrocardiogram",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/electrocardiogram"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/faceMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides data describing a user’s face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/faceMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "faceMetrics",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/faceMetrics"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/heartRate": {
      "abstract": [
        {
          "text": "A sensor that provides the user’s heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heartRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/heartRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "heartRate",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/heartRate"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/odometer": {
      "abstract": [
        {
          "text": "A sensor that provides information about speed and slope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "odometer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/odometer",
      "kind": "symbol",
      "role": "symbol",
      "title": "odometer",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/odometer"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/pedometerData": {
      "abstract": [
        {
          "text": "A sensor that provides information about the user’s steps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pedometerData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/pedometerData",
      "kind": "symbol",
      "role": "symbol",
      "title": "pedometerData",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/pedometerData"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/photoplethysmogram": {
      "abstract": [
        {
          "text": "A sensor that streams sample PPG sensor data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoplethysmogram"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/photoplethysmogram",
      "kind": "symbol",
      "role": "symbol",
      "title": "photoplethysmogram",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/photoplethysmogram"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/siriSpeechMetrics": {
      "abstract": [
        {
          "text": "A sensor that provides data describing a user’s speech to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "siriSpeechMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/siriSpeechMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "siriSpeechMetrics",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/siriSpeechMetrics"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSensor/wristTemperature": {
      "abstract": [
        {
          "text": "A sensor that provides wrist temperature while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wristTemperature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SRSensor",
          "text": "SRSensor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSensor/wristTemperature",
      "kind": "symbol",
      "role": "symbol",
      "title": "wristTemperature",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSensor/wristTemperature"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRSpeechMetrics": {
      "abstract": [
        {
          "text": "An object that represents metrics about a range of speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRSpeechMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRSpeechMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRSpeechMetrics",
      "type": "topic",
      "url": "/documentation/SensorKit/SRSpeechMetrics"
    },
    "doc://com.apple.documentation/documentation/SensorKit/SRWristTemperature": {
      "abstract": [
        {
          "text": "The temperature of the user’s wrist while the user sleeps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRWristTemperature"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SensorKit/SRWristTemperature",
      "kind": "symbol",
      "role": "symbol",
      "title": "SRWristTemperature",
      "type": "topic",
      "url": "/documentation/SensorKit/SRWristTemperature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMOdometerData/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMOdometerData"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRWristTemperature/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRWristTemperature"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRPhotoplethysmogramSample/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramSample"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSpeechMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSpeechMetrics"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1wristTemperature/title",
          "value": "SRSensorWristTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1wristTemperature/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorWristTemperature"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1odometer/title",
          "value": "SRSensorOdometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1odometer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorOdometer"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/title",
          "value": "SRSensorSiriSpeechMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1siriSpeechMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorSiriSpeechMetrics"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1heartRate/title",
          "value": "SRSensorHeartRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1heartRate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorHeartRate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1pedometerData/title",
          "value": "SRSensorPedometerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1pedometerData/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorPedometerData"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1electrocardiogram/title",
          "value": "SRSensorElectrocardiogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1electrocardiogram/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorElectrocardiogram"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1faceMetrics/title",
          "value": "SRSensorFaceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1faceMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorFaceMetrics"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRFaceMetrics/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRFaceMetrics"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRPhotoplethysmogramOpticalSample/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRPhotoplethysmogramOpticalSample"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMHighFrequencyHeartRateData/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateData"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CMLogItem",
              "text": "CMLogItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/title",
          "value": "SRSensorPhotoplethysmogram"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1SensorKit~1SRSensor~1photoplethysmogram/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SRSensor",
              "text": "SRSensor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SRSensorPhotoplethysmogram"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/sensorkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
