{
  "abstract": [
    {
      "text": "Learn about important changes to watchOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/watchos"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "watchOS updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "September-2024",
          "level": 2,
          "text": "September 2024",
          "type": "heading"
        },
        {
          "anchor": "Watch-sizes",
          "level": 3,
          "text": "Watch sizes",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apple Watch Series 10 are larger and have a different aspect ratio than previous watches. The watch is 1mm larger than the Series 9 (42mm and 46mm), but the screen gains more width than height. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/scenePadding(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to align text with the text margins, and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/ignoresSafeArea(_:edges:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to extend content beyond the watch’s safe area.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Shallow-dives",
          "level": 3,
          "text": "Shallow dives",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apple Watch Series 10 supports the Shallow Depth and Pressure capability. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMWaterSubmersionManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to start a shallow dive session, and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to read depth and temperature samples from HealthKit.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2024",
          "level": 2,
          "text": "June 2024",
          "type": "heading"
        },
        {
          "anchor": "Water-temperature",
          "level": 3,
          "text": "Water temperature",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Access water temperature data from swimming workouts. Apple Watch Ultra records ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " samples during swimming workouts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Double-tap",
          "level": 3,
          "text": "Double tap",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify which control responds to the double tap gesture using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/handGestureShortcut(_:isEnabled:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " view modifier, passing ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HandGestureShortcut/primaryAction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " as the parameter. Double tap can interact with any buttonlike controls, such as buttons or toggles.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Creating-workouts",
          "level": 3,
          "text": "Creating workouts",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create custom pool swimming workouts with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutActivityType/swimming",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " activity.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set a distance-with-time goal for custom swimming workouts with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutGoal/poolSwimDistanceWithTime(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " goal.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide a custom name to a workout step using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " structure’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep/displayName",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Preview workouts on Apple Watch using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/workoutPreview(_:isPresented:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " view modifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set average power goals for cycling and running with ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/PowerThresholdAlert",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/PowerRangeAlert",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set pace goals for indoor running with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/SpeedThresholdAlert",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/SpeedRangeAlert",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " targets.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "September-2023",
          "level": 2,
          "text": "September 2023",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When someone performs a Double Tap gesture while viewing",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "a notification on Apple Watch Series 9 or Apple Watch Ultra 2,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "the system invokes the first nondestructive action. A nondestructive action doesn’t include the",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationActionOptions/destructive",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "option, and won’t delete user data or change the app irrevocably.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2023",
          "level": 2,
          "text": "June 2023",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the new watchOS user interface design to simplify navigation, better use the Digital Crown, and enrich the app experience. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/designing-for-watchos",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update your WidgetKit-based complications to take advantage of the Smart Stack on Apple Watch. People can scroll down to see relevant widgets directly on the watch face using the Digital Crown. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use curved text along the bevel or around the corners in WidgetKit-based complications.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add state preservation and restoration to watchOS apps. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/preserving-your-app-s-ui-across-launches",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use WorkoutKit to create goal, pacer, multisport, and fully custom interval workouts. Display a preview of the workout that shows the workout details, and sync workouts with a paired Apple Watch. For more information, see   ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Access batches of high-frequency accelerometer and device motion data during workouts. Use this data to analyze motion — such as a golf or baseball swing — after the action occurs. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use Core Motion’s water submersion manager to monitor shallow dives on Apple Watch Ultra. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Support Bluetooth cycling sensors. People can pair power, cadence, and speed sensors to Apple Watch to enhance their cycling workouts. You can access this data using HealthKit for live and historical workouts.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/design/Human-Interface-Guidelines/designing-for-watchos": {
      "abstract": [
        {
          "text": "When people glance at their Apple Watch, they know they can access essential information and perform simple, timely tasks whether they’re stationary or in motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/design/Human-Interface-Guidelines/designing-for-watchos",
      "images": [
        {
          "identifier": "watchos.svg",
          "type": "icon"
        },
        {
          "identifier": "platforms-designing-for-watchos-thumbnail.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Designing for watchOS",
      "type": "topic",
      "url": "/design/Human-Interface-Guidelines/designing-for-watchos"
    },
    "doc://com.apple.documentation/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/CoreMotion"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMWaterSubmersionManager": {
      "abstract": [
        {
          "text": "An object for managing the collection of pressure and temperature data during submersion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMWaterSubmersionManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMWaterSubmersionManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMWaterSubmersionManager",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMWaterSubmersionManager"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutActivityType/swimming": {
      "abstract": [
        {
          "text": "The constant for swimming.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "swimming"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKWorkoutActivityType/swimming",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKWorkoutActivityType.swimming",
      "type": "topic",
      "url": "/documentation/HealthKit/HKWorkoutActivityType/swimming"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/HandGestureShortcut/primaryAction": {
      "abstract": [
        {
          "text": "The hand gesture shortcut for the primary action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19HandGestureShortcutV",
          "text": "HandGestureShortcut"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/HandGestureShortcut/primaryAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "primaryAction",
      "type": "topic",
      "url": "/documentation/SwiftUI/HandGestureShortcut/primaryAction"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/handGestureShortcut(_:isEnabled:)": {
      "abstract": [
        {
          "text": "Assigns a hand gesture shortcut to the modified control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handGestureShortcut"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "shortcut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19HandGestureShortcutV",
          "text": "HandGestureShortcut"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " = true) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/handGestureShortcut(_:isEnabled:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "handGestureShortcut(_:isEnabled:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/handGestureShortcut(_:isEnabled:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/ignoresSafeArea(_:edges:)": {
      "abstract": [
        {
          "text": "Expands the safe area of a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresSafeArea"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "regions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15SafeAreaRegionsV",
          "text": "SafeAreaRegions"
        },
        {
          "kind": "text",
          "text": " = .all, "
        },
        {
          "kind": "externalParam",
          "text": "edges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO",
          "text": "Edge"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO3SetV",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": " = .all) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/ignoresSafeArea(_:edges:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ignoresSafeArea(_:edges:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/ignoresSafeArea(_:edges:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/scenePadding(_:)": {
      "abstract": [
        {
          "text": "Adds padding to the specified edges of this view using an amount that’s appropriate for the current scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scenePadding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "edges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO",
          "text": "Edge"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4EdgeO3SetV",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": " = .all) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/scenePadding(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "scenePadding(_:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/scenePadding(_:)"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/View/workoutPreview(_:isPresented:)": {
      "abstract": [
        {
          "text": "Presents a preview of the workout contents as a modal sheet",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "nonisolated"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "workout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10WorkoutKit0A4PlanV",
          "text": "WorkoutPlan"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isPresented"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI7BindingV",
          "text": "Binding"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": "\n"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/View/workoutPreview(_:isPresented:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "workoutPreview(_:isPresented:)",
      "type": "topic",
      "url": "/documentation/SwiftUI/View/workoutPreview(_:isPresented:)"
    },
    "doc://com.apple.documentation/documentation/UIKit/preserving-your-app-s-ui-across-launches": {
      "abstract": [
        {
          "text": "Return your app to its previous state after the system terminates it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/preserving-your-app-s-ui-across-launches",
      "kind": "article",
      "role": "article",
      "title": "Preserving your app’s UI across launches",
      "type": "topic",
      "url": "/documentation/UIKit/preserving-your-app-s-ui-across-launches"
    },
    "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationActionOptions/destructive": {
      "abstract": [
        {
          "text": "The action performs a destructive task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destructive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UNNotificationActionOptions",
          "text": "UNNotificationActionOptions"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationActionOptions/destructive",
      "kind": "symbol",
      "role": "symbol",
      "title": "destructive",
      "type": "topic",
      "url": "/documentation/UserNotifications/UNNotificationActionOptions/destructive"
    },
    "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks": {
      "abstract": [
        {
          "text": "Donate intents and indicate relevance to automatically show your widget in Smart Stacks when it has useful information to display.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks",
      "kind": "article",
      "role": "article",
      "title": "Increasing the visibility of widgets in Smart Stacks",
      "type": "topic",
      "url": "/documentation/WidgetKit/Widget-Suggestions-In-Smart-Stacks"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit": {
      "abstract": [
        {
          "text": "Create, preview, and sync workout compositions to the Workout app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WorkoutKit",
      "type": "topic",
      "url": "/documentation/WorkoutKit"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/PowerRangeAlert": {
      "abstract": [
        {
          "text": "An alert for a range of power values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PowerRangeAlert"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/PowerRangeAlert",
      "kind": "symbol",
      "role": "symbol",
      "title": "PowerRangeAlert",
      "type": "topic",
      "url": "/documentation/WorkoutKit/PowerRangeAlert"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/PowerThresholdAlert": {
      "abstract": [
        {
          "text": "An alert for a power threshold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PowerThresholdAlert"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/PowerThresholdAlert",
      "kind": "symbol",
      "role": "symbol",
      "title": "PowerThresholdAlert",
      "type": "topic",
      "url": "/documentation/WorkoutKit/PowerThresholdAlert"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/SpeedRangeAlert": {
      "abstract": [
        {
          "text": "An alert for a range of speed values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SpeedRangeAlert"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/SpeedRangeAlert",
      "kind": "symbol",
      "role": "symbol",
      "title": "SpeedRangeAlert",
      "type": "topic",
      "url": "/documentation/WorkoutKit/SpeedRangeAlert"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/SpeedThresholdAlert": {
      "abstract": [
        {
          "text": "An alert for a speed threshold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SpeedThresholdAlert"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/SpeedThresholdAlert",
      "kind": "symbol",
      "role": "symbol",
      "title": "SpeedThresholdAlert",
      "type": "topic",
      "url": "/documentation/WorkoutKit/SpeedThresholdAlert"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutGoal/poolSwimDistanceWithTime(_:_:)": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "poolSwimDistanceWithTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitLength",
          "text": "UnitLength"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitDuration",
          "text": "UnitDuration"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutGoal/poolSwimDistanceWithTime(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "WorkoutGoal.poolSwimDistanceWithTime(_:_:)",
      "type": "topic",
      "url": "/documentation/WorkoutKit/WorkoutGoal/poolSwimDistanceWithTime(_:_:)"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep": {
      "abstract": [
        {
          "text": "A step in a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WorkoutStep"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep",
      "kind": "symbol",
      "role": "symbol",
      "title": "WorkoutStep",
      "type": "topic",
      "url": "/documentation/WorkoutKit/WorkoutStep"
    },
    "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep/displayName": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WorkoutKit/WorkoutStep/displayName",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/WorkoutKit/WorkoutStep/displayName"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth": {
      "abstract": [
        {
          "text": "A quantity sample that records a person’s depth underwater.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "underwaterDepth"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth",
      "kind": "symbol",
      "role": "symbol",
      "title": "underwaterDepth",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/3958703-underwaterdepth"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature": {
      "abstract": [
        {
          "text": "A quantity sample that records the water temperature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "waterTemperature"
        },
        {
          "kind": "text",
          "text": ": HKQuantityTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature",
      "kind": "symbol",
      "role": "symbol",
      "title": "waterTemperature",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantitytypeidentifier/3958704-watertemperature"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/watchOS-Apps": {
      "abstract": [
        {
          "text": "Build watchOS apps that combine complications, notifications, and Siri to create a personal experience on Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps",
      "images": [
        {
          "identifier": "watchOSApps-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "collection",
      "title": "watchOS apps",
      "type": "topic",
      "url": "/documentation/watchOS-Apps"
    },
    "doc://com.apple.documentation/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10": {
      "abstract": [
        {
          "text": "Provide an even more streamlined, consistent, and glanceable user experience with new design features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10",
      "kind": "article",
      "role": "article",
      "title": "Creating an intuitive and effective UI in watchOS 10",
      "type": "topic",
      "url": "/documentation/watchOS-Apps/creating-an-intuitive-and-effective-ui-in-watchos-10"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    },
    "platforms-designing-for-watchos-thumbnail.png": {
      "alt": null,
      "identifier": "platforms-designing-for-watchos-thumbnail.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0686f93dddf6ba103cc46001a38ee538/platforms-designing-for-watchos-thumbnail~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dd69cccef7898c67b4c69998b9a766a3/platforms-designing-for-watchos-thumbnail@2x.png"
        }
      ]
    },
    "watchOSApps-PageImage-card.png": {
      "alt": null,
      "identifier": "watchOSApps-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2e82e5f258fb084d7b684889cabbe515/watchOSApps-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5e043ca96ec9c9e5579649124c448c35/watchOSApps-PageImage-card@2x.png"
        }
      ]
    },
    "watchos.svg": {
      "alt": null,
      "identifier": "watchos.svg",
      "type": "image",
      "variants": [
        {
          "svgID": "watchos",
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e3afc34edc848f8ea56d5cc1cb2b7495/watchos.svg"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~13958704-watertemperature/title",
          "value": "HKQuantityTypeIdentifierWaterTemperature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkquantitytypeidentifier~13958703-underwaterdepth/title",
          "value": "HKQuantityTypeIdentifierUnderwaterDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNNotificationActionOptions~1destructive/title",
          "value": "UNNotificationActionOptionDestructive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNNotificationActionOptions~1destructive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationActionOptionDestructive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMWaterSubmersionManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMWaterSubmersionManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKWorkoutActivityType~1swimming/title",
          "value": "HKWorkoutActivityTypeSwimming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKWorkoutActivityType~1swimming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutActivityTypeSwimming"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/watchos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
