{
  "abstract": [
    {
      "text": "Learn about important changes to XPC.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Updates/documentation/Updates"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Updates/documentation/Updates/XPC"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Updates"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "XPC updates"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Browse notable changes in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/xpc",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "March-2024",
          "level": 2,
          "text": "March 2024",
          "type": "heading"
        },
        {
          "anchor": "Security",
          "level": 3,
          "text": "Security",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Test whether the peer executable that communicates with your app over an XPC connection has an expected entitlement by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and whether it has a specific value for an entitlement by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Test whether the peer executable that communicates with your app over an XPC connection is an Apple platform binary with a given signing identifier by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Test whether your Apple Developer team signed the peer executable that communicates with your app over an XPC connection by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Test whether the peer executable that communicates with your app over an XPC connection satisfies a lightweight code requirement by calling ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "June-2023",
          "level": 2,
          "text": "June 2023",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create XPC services using native Swift syntax. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/XPCListener",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to create an XPC server that listens for messages from other processes. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/XPCSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to create clients that connect to servers and exchange messages.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For C and Objective-C projects, use the corresponding ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_listener_t",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_session_t-10if0",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " APIs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Xcode, use the updated XPC services target template to choose whether you want to use the high-level ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpcconnection",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or the low-level ",
                      "type": "text"
                    },
                    {
                      "code": "libXPC",
                      "type": "codeVoice"
                    },
                    {
                      "text": " APIs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "Apple-Intelligence-updates-page-PageImage-card.png": {
      "alt": "A stylistic image of the Apple Intelligence logo.",
      "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/582fe08f6f69a366c2f1b35cd91e3c52/Apple-Intelligence-updates-page-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d4b11a932a5a2c7880eccd8043a1c524/Apple-Intelligence-updates-page-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Updates/documentation/Updates": {
      "abstract": [
        {
          "text": "View major documentation updates and highlights from WWDC, browse ongoing updates from a set of framework releases over time, and jump to the latest release notes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates",
      "images": [
        {
          "identifier": "featured.svg",
          "type": "icon"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Updates",
      "type": "topic",
      "url": "/documentation/updates"
    },
    "doc://com.apple.Updates/documentation/Updates/ARKit": {
      "abstract": [
        {
          "text": "Learn about important changes to ARKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ARKit",
      "kind": "article",
      "role": "article",
      "title": "ARKit updates",
      "type": "topic",
      "url": "/documentation/updates/arkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFAudio": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFAudio.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFAudio",
      "kind": "article",
      "role": "article",
      "title": "AVFAudio updates",
      "type": "topic",
      "url": "/documentation/updates/avfaudio"
    },
    "doc://com.apple.Updates/documentation/Updates/AVFoundation": {
      "abstract": [
        {
          "text": "Learn about important changes to AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AVFoundation",
      "kind": "article",
      "role": "article",
      "title": "AVFoundation updates",
      "type": "topic",
      "url": "/documentation/updates/avfoundation"
    },
    "doc://com.apple.Updates/documentation/Updates/Accelerate": {
      "abstract": [
        {
          "text": "Learn about important changes to Accelerate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accelerate",
      "kind": "article",
      "role": "article",
      "title": "Accelerate updates",
      "type": "topic",
      "url": "/documentation/updates/accelerate"
    },
    "doc://com.apple.Updates/documentation/Updates/Accessibility": {
      "abstract": [
        {
          "text": "Learn about important changes to Accessibility.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Accessibility",
      "kind": "article",
      "role": "article",
      "title": "Accessibility updates",
      "type": "topic",
      "url": "/documentation/updates/accessibility"
    },
    "doc://com.apple.Updates/documentation/Updates/ActivityKit": {
      "abstract": [
        {
          "text": "Learn about important changes in ActivityKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ActivityKit",
      "kind": "article",
      "role": "article",
      "title": "ActivityKit updates",
      "type": "topic",
      "url": "/documentation/updates/activitykit"
    },
    "doc://com.apple.Updates/documentation/Updates/AdAttributionKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AdAttributionKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
      "kind": "article",
      "role": "article",
      "title": "AdAttributionKit Updates",
      "type": "topic",
      "url": "/documentation/updates/adattributionkit"
    },
    "doc://com.apple.Updates/documentation/Updates/AppIntents": {
      "abstract": [
        {
          "text": "Learn about important changes in App Intents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppIntents",
      "kind": "article",
      "role": "article",
      "title": "App Intents updates",
      "type": "topic",
      "url": "/documentation/updates/appintents"
    },
    "doc://com.apple.Updates/documentation/Updates/AppKit": {
      "abstract": [
        {
          "text": "Learn about important changes to AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AppKit",
      "kind": "article",
      "role": "article",
      "title": "AppKit updates",
      "type": "topic",
      "url": "/documentation/updates/appkit"
    },
    "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Intelligence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
      "images": [
        {
          "identifier": "Apple-Intelligence-updates-page-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Apple Intelligence updates",
      "type": "topic",
      "url": "/documentation/updates/apple-intelligence"
    },
    "doc://com.apple.Updates/documentation/Updates/ApplePencil": {
      "abstract": [
        {
          "text": "Learn about important changes to Apple Pencil.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ApplePencil",
      "kind": "article",
      "role": "article",
      "title": "Apple Pencil updates",
      "type": "topic",
      "url": "/documentation/updates/applepencil"
    },
    "doc://com.apple.Updates/documentation/Updates/AudioToolbox": {
      "abstract": [
        {
          "text": "Learn about important changes to Audio Toolbox.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
      "kind": "article",
      "role": "article",
      "title": "Audio Toolbox updates",
      "type": "topic",
      "url": "/documentation/updates/audiotoolbox"
    },
    "doc://com.apple.Updates/documentation/Updates/AuthenticationServices": {
      "abstract": [
        {
          "text": "Learn about important changes to AuthenticationServices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
      "kind": "article",
      "role": "article",
      "title": "AuthenticationServices updates",
      "type": "topic",
      "url": "/documentation/updates/authenticationservices"
    },
    "doc://com.apple.Updates/documentation/Updates/BundleResources": {
      "abstract": [
        {
          "text": "Learn about important changes to Bundle Resources.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/BundleResources",
      "kind": "article",
      "role": "article",
      "title": "Bundle Resources updates",
      "type": "topic",
      "url": "/documentation/updates/bundleresources"
    },
    "doc://com.apple.Updates/documentation/Updates/ContactsUI": {
      "abstract": [
        {
          "text": "Learn about important changes to ContactsUI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Updates/documentation/Updates/ContactsUI",
      "kind": "article",
      "role": "article",
      "title": "ContactsUI updates",
      "type": "topic",
      "url": "/documentation/updates/contactsui"
    },
    "doc://com.apple.documentation/documentation/XPC/XPCListener": {
      "abstract": [
        {
          "text": "A type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCListener"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/XPCListener",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPCListener",
      "type": "topic",
      "url": "/documentation/XPC/XPCListener"
    },
    "doc://com.apple.documentation/documentation/XPC/XPCSession": {
      "abstract": [
        {
          "text": "A type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XPCSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/XPCSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "XPCSession",
      "type": "topic",
      "url": "/documentation/XPC/XPCSession"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "entitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_exists_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_entitlement_exists_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that contains an entitlement with a specific value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "entitlement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that matches the lightweight code requirement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_lightweight_code_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "lwcr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_object_t",
          "text": "xpc_object_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_lightweight_code_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_lightweight_code_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature that identifies it as an Apple-signed binary with the given signing identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "signing_identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_platform_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_platform_identity_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)": {
      "abstract": [
        {
          "text": "Sets a requirement that the executable for the peer process has a valid code signature and is signed by the same team identifier as the calling process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@xpc_connection_t",
          "text": "xpc_connection_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "signing_identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_connection_set_peer_team_identity_requirement(_:_:)",
      "type": "topic",
      "url": "/documentation/XPC/xpc_connection_set_peer_team_identity_requirement(_:_:)"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_listener_t": {
      "abstract": [
        {
          "text": "A C type that performs tasks for clients across process boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_listener_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_xpc_listener",
          "text": "OS_xpc_listener"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_listener_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_listener_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_listener_t"
    },
    "doc://com.apple.documentation/documentation/XPC/xpc_session_t-10if0": {
      "abstract": [
        {
          "text": "A C type that sends messages to a server process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "xpc_session_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_xpc_session",
          "text": "OS_xpc_session"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/XPC/xpc_session_t-10if0",
      "kind": "symbol",
      "role": "symbol",
      "title": "xpc_session_t",
      "type": "topic",
      "url": "/documentation/XPC/xpc_session_t-10if0"
    },
    "doc://com.apple.documentation/documentation/foundation/nsxpcconnection": {
      "abstract": [
        {
          "text": "A bidirectional communication channel between two processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSXPCConnection"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsxpcconnection",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSXPCConnection",
      "type": "topic",
      "url": "/documentation/foundation/nsxpcconnection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "featured.svg": {
      "alt": "An icon, with a star and a speech bubble around it, representing updates.",
      "identifier": "featured.svg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/70c10a18eb39cac81bd40849ad68cbff/featured.svg"
        }
      ]
    },
    "https://developer.apple.com/documentation/xpc": {
      "identifier": "https://developer.apple.com/documentation/xpc",
      "title": "XPC",
      "titleInlineContent": [
        {
          "text": "XPC",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/xpc"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Technology-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Updates/documentation/Updates/Accelerate",
        "doc://com.apple.Updates/documentation/Updates/Accessibility",
        "doc://com.apple.Updates/documentation/Updates/ActivityKit",
        "doc://com.apple.Updates/documentation/Updates/AdAttributionKit",
        "doc://com.apple.Updates/documentation/Updates/AppIntents",
        "doc://com.apple.Updates/documentation/Updates/AppKit",
        "doc://com.apple.Updates/documentation/Updates/Apple-Intelligence",
        "doc://com.apple.Updates/documentation/Updates/ApplePencil",
        "doc://com.apple.Updates/documentation/Updates/ARKit",
        "doc://com.apple.Updates/documentation/Updates/AudioToolbox",
        "doc://com.apple.Updates/documentation/Updates/AuthenticationServices",
        "doc://com.apple.Updates/documentation/Updates/AVFAudio",
        "doc://com.apple.Updates/documentation/Updates/AVFoundation",
        "doc://com.apple.Updates/documentation/Updates/BundleResources",
        "doc://com.apple.Updates/documentation/Updates/ContactsUI"
      ],
      "title": "Technology updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_team_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_team_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_team_identity_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "signing_identifier"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_listener_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_listener",
              "text": "NSObject<OS_xpc_listener>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "xpc_listener_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_platform_identity_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_platform_identity_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_platform_identity_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "signing_identifier"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_matches_value_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_matches_value_requirement(_:_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_matches_value_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "entitlement"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_session_t-10if0/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_xpc_session",
              "text": "NSObject<OS_xpc_session>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "xpc_session_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_lightweight_code_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_lightweight_code_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_lightweight_code_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_lightweight_code_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_object_t",
              "text": "xpc_object_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "lwcr"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/title",
          "value": "xpc_connection_set_peer_entitlement_exists_requirement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1XPC~1xpc_connection_set_peer_entitlement_exists_requirement(_:_:)/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:I",
              "text": "int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "xpc_connection_set_peer_entitlement_exists_requirement"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@xpc_connection_t",
              "text": "xpc_connection_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "entitlement"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/updates/xpc"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
