{
  "abstract": [
    {
      "text": "Retrieves the resolved dimensions of the semantic segmentation mattes that the photo output delivers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureResolvedPhotoSettings(im)dimensionsForSemanticSegmentationMatteOfType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dimensionsForSemanticSegmentationMatte"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "ofType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
        "text": "AVSemanticSegmentationMatte"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
        "text": "MatteType"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMVideoDimensions",
        "text": "CMVideoDimensions"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dimensionsForSemanticSegmentationMatteOfType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "dimensionsForSemanticSegmentationMatte(ofType:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dimensionsForSemanticSegmentationMatte"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "ofType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "semanticSegmentationMatteType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
              "text": "AVSemanticSegmentationMatte"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte/MatteType-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
              "text": "MatteType"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMVideoDimensions",
              "text": "CMVideoDimensions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The segmentation matte type for which to retrieve dimensions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "semanticSegmentationMatteType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMVideoDimensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure that provides the height and width of the image mattes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings": {
      "abstract": [
        {
          "text": "A description of the features and settings in use for an in-progress or complete photo capture request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureResolvedPhotoSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions": {
      "abstract": [
        {
          "text": "The resolved dimensions of the photo proxy when using deferred photo delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredPhotoProxyDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deferredPhotoProxyDimensions"
        }
      ],
      "role": "symbol",
      "title": "deferredPhotoProxyDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/deferredphotoproxydimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)": {
      "abstract": [
        {
          "text": "Retrieves the resolved dimensions of the semantic segmentation mattes that the photo output delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensionsForSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
          "text": "AVSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
          "text": "MatteType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimensionsForSemanticSegmentationMatteOfType:"
        }
      ],
      "role": "symbol",
      "title": "dimensionsForSemanticSegmentationMatte(ofType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/dimensionsforsemanticsegmentationmatte(oftype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the thumbnail image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "embeddedThumbnailDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "embeddedThumbnailDimensions"
        }
      ],
      "role": "symbol",
      "title": "embeddedThumbnailDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/embeddedthumbnaildimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the Live Photo movie content that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhotoMovieDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "livePhotoMovieDimensions"
        }
      ],
      "role": "symbol",
      "title": "livePhotoMovieDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/livephotomoviedimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the photo image (in a processed format, such as JPEG) that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoDimensions"
        }
      ],
      "role": "symbol",
      "title": "photoDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/photodimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange": {
      "abstract": [
        {
          "text": "The time range in which to expect the system to deliver the photo to the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoProcessingTimeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoProcessingTimeRange"
        }
      ],
      "role": "symbol",
      "title": "photoProcessingTimeRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/photoprocessingtimerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the portrait effects matte that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteDimensions"
        }
      ],
      "role": "symbol",
      "title": "portraitEffectsMatteDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/portraiteffectsmattedimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the preview image that the system delivers with the capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewDimensions"
        }
      ],
      "role": "symbol",
      "title": "previewDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/previewdimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the RAW-format embedded thumbnail image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawEmbeddedThumbnailDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawEmbeddedThumbnailDimensions"
        }
      ],
      "role": "symbol",
      "title": "rawEmbeddedThumbnailDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/rawembeddedthumbnaildimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the RAW-format photo image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawPhotoDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawPhotoDimensions"
        }
      ],
      "role": "symbol",
      "title": "rawPhotoDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/rawphotodimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte": {
      "abstract": [
        {
          "text": "An object that wraps a matting image for a particular semantic segmentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSemanticSegmentationMatte"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSemanticSegmentationMatte"
        }
      ],
      "role": "symbol",
      "title": "AVSemanticSegmentationMatte",
      "type": "topic",
      "url": "/documentation/avfoundation/avsemanticsegmentationmatte"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte/MatteType-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the types of segmentation matte images that you can capture along with the primary image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MatteType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte/MatteType-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MatteType"
        }
      ],
      "role": "symbol",
      "title": "AVSemanticSegmentationMatte.MatteType",
      "type": "topic",
      "url": "/documentation/avfoundation/avsemanticsegmentationmatte/mattetype-swift.struct"
    },
    "doc://com.apple.documentation/documentation/CoreMedia/CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMVideoDimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMVideoDimensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMVideoDimensions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Examining-Output-Dimensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange"
      ],
      "title": "Examining Output Dimensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dimensionsForSemanticSegmentationMatteOfType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dimensionsForSemanticSegmentationMatteOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Examining-Output-Dimensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange"
              ],
              "title": "Examining Output Dimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMVideoDimensions",
                    "text": "CMVideoDimensions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "dimensionsForSemanticSegmentationMatteOfType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte/MatteType-swift.struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
                    "text": "AVSemanticSegmentationMatteType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "semanticSegmentationMatteType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The segmentation matte type for which to retrieve dimensions.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "semanticSegmentationMatteType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/CoreMedia/CMVideoDimensions",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " structure that provides the height and width of the image mattes.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/title",
          "value": "AVCaptureResolvedPhotoSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1deferredPhotoProxyDimensions/title",
          "value": "deferredPhotoProxyDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1deferredPhotoProxyDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deferredPhotoProxyDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawEmbeddedThumbnailDimensions/title",
          "value": "rawEmbeddedThumbnailDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawEmbeddedThumbnailDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawEmbeddedThumbnailDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoProcessingTimeRange/title",
          "value": "photoProcessingTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoProcessingTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoProcessingTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/title",
          "value": "AVSemanticSegmentationMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte~1MatteType-swift.struct/title",
          "value": "AVSemanticSegmentationMatteType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte~1MatteType-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatteType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte~1MatteType-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatteType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1embeddedThumbnailDimensions/title",
          "value": "embeddedThumbnailDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1embeddedThumbnailDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "embeddedThumbnailDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1portraitEffectsMatteDimensions/title",
          "value": "portraitEffectsMatteDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1portraitEffectsMatteDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "portraitEffectsMatteDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1livePhotoMovieDimensions/title",
          "value": "livePhotoMovieDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1livePhotoMovieDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "livePhotoMovieDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1dimensionsForSemanticSegmentationMatte(ofType:)/title",
          "value": "dimensionsForSemanticSegmentationMatteOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1dimensionsForSemanticSegmentationMatte(ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dimensionsForSemanticSegmentationMatteOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoDimensions/title",
          "value": "photoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1previewDimensions/title",
          "value": "previewDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1previewDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawPhotoDimensions/title",
          "value": "rawPhotoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawPhotoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawPhotoDimensions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureresolvedphotosettings/dimensionsforsemanticsegmentationmatte(oftype:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureresolvedphotosettings/dimensionsforsemanticsegmentationmatte(oftype:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
