{
  "abstract": [
    {
      "text": "The size, in pixels, of the photo image (in a processed format, such as JPEG) that the capture delivers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureResolvedPhotoSettings(py)photoDimensions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "photoDimensions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMVideoDimensions",
        "text": "CMVideoDimensions"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "photoDimensions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "photoDimensions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "photoDimensions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMVideoDimensions",
              "text": "CMVideoDimensions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The output dimensions of a captured image are set at the moment of capture, depending on device orientation and capture session configuration. (For example, when the capture session includes a video output and video stabilization is in use, captured photos are smaller.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This property provides the dimensions of the image to be delivered in the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Use this property in earlier delegate methods to find the size of the image before delivery.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not request capture in a processed format (that is, if you request capture in RAW format only), this property’s value has zero width and zero height.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate with the captured image and associated metadata resulting from a photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingPhoto:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingPhoto:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessingphoto:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings": {
      "abstract": [
        {
          "text": "A description of the features and settings in use for an in-progress or complete photo capture request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureResolvedPhotoSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions": {
      "abstract": [
        {
          "text": "The resolved dimensions of the photo proxy when using deferred photo delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferredPhotoProxyDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deferredPhotoProxyDimensions"
        }
      ],
      "role": "symbol",
      "title": "deferredPhotoProxyDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/deferredphotoproxydimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)": {
      "abstract": [
        {
          "text": "Retrieves the resolved dimensions of the semantic segmentation mattes that the photo output delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dimensionsForSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
          "text": "AVSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
          "text": "MatteType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dimensionsForSemanticSegmentationMatteOfType:"
        }
      ],
      "role": "symbol",
      "title": "dimensionsForSemanticSegmentationMatte(ofType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/dimensionsforsemanticsegmentationmatte(oftype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the thumbnail image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "embeddedThumbnailDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "embeddedThumbnailDimensions"
        }
      ],
      "role": "symbol",
      "title": "embeddedThumbnailDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/embeddedthumbnaildimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the Live Photo movie content that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhotoMovieDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "livePhotoMovieDimensions"
        }
      ],
      "role": "symbol",
      "title": "livePhotoMovieDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/livephotomoviedimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the photo image (in a processed format, such as JPEG) that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoDimensions"
        }
      ],
      "role": "symbol",
      "title": "photoDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/photodimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange": {
      "abstract": [
        {
          "text": "The time range in which to expect the system to deliver the photo to the delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoProcessingTimeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoProcessingTimeRange"
        }
      ],
      "role": "symbol",
      "title": "photoProcessingTimeRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/photoprocessingtimerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the portrait effects matte that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteDimensions"
        }
      ],
      "role": "symbol",
      "title": "portraitEffectsMatteDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/portraiteffectsmattedimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the preview image that the system delivers with the capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewDimensions"
        }
      ],
      "role": "symbol",
      "title": "previewDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/previewdimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the RAW-format embedded thumbnail image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawEmbeddedThumbnailDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawEmbeddedThumbnailDimensions"
        }
      ],
      "role": "symbol",
      "title": "rawEmbeddedThumbnailDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/rawembeddedthumbnaildimensions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions": {
      "abstract": [
        {
          "text": "The size, in pixels, of the RAW-format photo image that the capture delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawPhotoDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMVideoDimensions",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rawPhotoDimensions"
        }
      ],
      "role": "symbol",
      "title": "rawPhotoDimensions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings/rawphotodimensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMVideoDimensions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Examining-Output-Dimensions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange"
      ],
      "title": "Examining Output Dimensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "photoDimensions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Examining-Output-Dimensions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/deferredPhotoProxyDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawPhotoDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/previewDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/embeddedThumbnailDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/rawEmbeddedThumbnailDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/livePhotoMovieDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/portraitEffectsMatteDimensions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/dimensionsForSemanticSegmentationMatte(ofType:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings/photoProcessingTimeRange"
              ],
              "title": "Examining Output Dimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMVideoDimensions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMVideoDimensions",
                    "text": "CMVideoDimensions"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "photoDimensions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawEmbeddedThumbnailDimensions/title",
          "value": "rawEmbeddedThumbnailDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawEmbeddedThumbnailDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawEmbeddedThumbnailDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1deferredPhotoProxyDimensions/title",
          "value": "deferredPhotoProxyDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1deferredPhotoProxyDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deferredPhotoProxyDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoDimensions/title",
          "value": "photoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawPhotoDimensions/title",
          "value": "rawPhotoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1rawPhotoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rawPhotoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1embeddedThumbnailDimensions/title",
          "value": "embeddedThumbnailDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1embeddedThumbnailDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "embeddedThumbnailDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1previewDimensions/title",
          "value": "previewDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1previewDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/title",
          "value": "captureOutput:didFinishProcessingPhoto:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingPhoto:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/title",
          "value": "AVCaptureResolvedPhotoSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1livePhotoMovieDimensions/title",
          "value": "livePhotoMovieDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1livePhotoMovieDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "livePhotoMovieDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1portraitEffectsMatteDimensions/title",
          "value": "portraitEffectsMatteDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1portraitEffectsMatteDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "portraitEffectsMatteDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1dimensionsForSemanticSegmentationMatte(ofType:)/title",
          "value": "dimensionsForSemanticSegmentationMatteOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1dimensionsForSemanticSegmentationMatte(ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dimensionsForSemanticSegmentationMatteOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoProcessingTimeRange/title",
          "value": "photoProcessingTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings~1photoProcessingTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "photoProcessingTimeRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureresolvedphotosettings/photodimensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureresolvedphotosettings/photodimensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
