{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_UNSPEC","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The unspecified address type."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_UNSPEC"},"variants":[{"paths":["/documentation/gss/gss_c_af_unspec"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/gss/gss_c_af_unspec"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Global Variable","platforms":[{"beta":false,"introducedAt":"5.0","unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"introducedAt":"5.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"introducedAt":"10.14","unavailable":false,"deprecated":false,"name":"macOS"},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_UNSPEC"}],"title":"GSS_C_AF_UNSPEC","externalID":"c:@macro@GSS_C_AF_UNSPEC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_UNSPEC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"symbolKind":"var","role":"symbol","modules":[{"name":"GSS"}]},"seeAlsoSections":[{"generated":true,"anchor":"Address-Families","title":"Address Families","identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"kind":"symbol","references":{"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP":{"abstract":[{"text":"The PUP protocols (for example, BSP) address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_pup","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_PUP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_PUP","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_PUP","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","abstract":[{"text":"The ECMA address type.","type":"text"}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_ECMA","url":"/documentation/gss/gss_c_af_ecma","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"GSS_C_AF_ECMA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_ECMA","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25":{"url":"/documentation/gss/gss_c_af_x25","navigatorTitle":[{"text":"GSS_C_AF_X25","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","role":"symbol","abstract":[{"type":"text","text":"The X.25 address type."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_X25","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_X25","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","abstract":[{"type":"text","text":"The LAT address type."}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_LAT","url":"/documentation/gss/gss_c_af_lat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_LAT","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_LAT","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET6","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET6","url":"/documentation/gss/gss_c_af_inet6","navigatorTitle":[{"text":"GSS_C_AF_INET6","kind":"identifier"}],"abstract":[{"type":"text","text":"The IPv6 address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","abstract":[{"type":"text","text":"The MIT CHAOS protocol address type."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_CHAOS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_CHAOS","role":"symbol","url":"/documentation/gss/gss_c_af_chaos","navigatorTitle":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA":{"abstract":[{"text":"The IBM SNA address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_sna","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_SNA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_SNA","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_SNA","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_UNSPEC":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_UNSPEC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_UNSPEC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","title":"GSS_C_AF_UNSPEC","url":"/documentation/gss/gss_c_af_unspec","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_UNSPEC"}],"abstract":[{"text":"The unspecified address type.","type":"text"}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","abstract":[{"type":"text","text":"The direct data link interface address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_DLI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_DLI","role":"symbol","url":"/documentation/gss/gss_c_af_dli","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS":{"type":"topic","title":"GSS_C_AF_NS","role":"symbol","abstract":[{"text":"The Xerox NS address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_NS","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_NS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_ns","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET","url":"/documentation/gss/gss_c_af_inet","navigatorTitle":[{"text":"GSS_C_AF_INET","kind":"identifier"}],"abstract":[{"type":"text","text":"The Internet (for example, IP) address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS":{"abstract":[{"text":"The distributed system services address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_dss","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_DSS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_DSS","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_DSS","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC":{"url":"/documentation/gss/gss_c_af_bsc","navigatorTitle":[{"text":"GSS_C_AF_BSC","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","role":"symbol","abstract":[{"text":"The BISYNC 2780/3780 address type.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_BSC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_BSC","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_CCITT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","title":"GSS_C_AF_CCITT","url":"/documentation/gss/gss_c_af_ccitt","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_CCITT"}],"abstract":[{"type":"text","text":"The CCITT protocols address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","abstract":[{"type":"text","text":"The nbs address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_NBS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_NBS","role":"symbol","url":"/documentation/gss/gss_c_af_nbs","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_NBS"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI":{"type":"topic","title":"GSS_C_AF_OSI","role":"symbol","abstract":[{"text":"The OSI TP4 address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_OSI","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_OSI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_osi","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"introducedAt":"5.0","deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"introducedAt":"5.0","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"introducedAt":"10.14","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GSS_C_AF_UNSPEC","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"GSS_C_AF_UNSPEC","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"],"anchor":"Address-Families","title":"Address Families"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_UNSPEC","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"GSS_C_AF_PUP","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_PUP"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/fragments"},{"value":"GSS_C_AF_ECMA","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_ECMA"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/fragments"},{"value":"GSS_C_AF_X25","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/title"},{"value":[{"text":"GSS_C_AF_X25","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/fragments"},{"value":"GSS_C_AF_LAT","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_LAT"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/fragments"},{"value":"GSS_C_AF_INET6","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/title"},{"value":[{"text":"GSS_C_AF_INET6","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/fragments"},{"value":"GSS_C_AF_CHAOS","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/title"},{"value":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/fragments"},{"value":"GSS_C_AF_SNA","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_SNA"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/fragments"},{"value":"GSS_C_AF_UNSPEC","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_UNSPEC/title"},{"value":[{"text":"GSS_C_AF_UNSPEC","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_UNSPEC/fragments"},{"value":"GSS_C_AF_DLI","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/fragments"},{"value":"GSS_C_AF_NS","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_NS"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/fragments"},{"value":"GSS_C_AF_INET","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/title"},{"value":[{"text":"GSS_C_AF_INET","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/fragments"},{"value":"GSS_C_AF_DSS","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_DSS"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/fragments"},{"value":"GSS_C_AF_BSC","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_BSC"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/fragments"},{"value":"GSS_C_AF_CCITT","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_CCITT"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/fragments"},{"value":"GSS_C_AF_NBS","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_NBS"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/fragments"},{"value":"GSS_C_AF_OSI","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/title"},{"value":[{"kind":"identifier","text":"GSS_C_AF_OSI"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}