{
  "abstract": [
    {
      "text": "Acquires a credential for use in establishing a security context using a password.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@gss_acquire_cred_with_password",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_acquire_cred_with_password"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_name_t",
        "text": "gss_name_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_buffer_t",
        "text": "gss_buffer_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_OID_set",
        "text": "gss_OID_set"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_usage_t",
        "text": "gss_cred_usage_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": "?>, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_OID_set",
        "text": "gss_OID_set"
      },
      {
        "kind": "text",
        "text": "?>?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_acquire_cred_with_password"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_acquire_cred_with_password"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "minor_status"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "desired_name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_name_t",
              "text": "gss_name_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "password"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_buffer_t",
              "text": "gss_buffer_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "time_req"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "desired_mechs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_OID_set",
              "text": "gss_OID_set"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cred_usage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_usage_t",
              "text": "gss_cred_usage_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "output_cred_handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": "?>, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "actual_mechs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_OID_set",
              "text": "gss_OID_set"
            },
            {
              "kind": "text",
              "text": "?>?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "time_rec"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the secondary status result that provides additional information in case of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "minor_status"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the principal whose credential should be acquired. Specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to get a generic credential or use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to obtain a name object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "desired_name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The password.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "password"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time in seconds that the credential should remain valid. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to indicate the maximum allowed duration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "time_req"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The set of underlying security mechanisms to use with the credential. Use ",
                  "type": "text"
                },
                {
                  "code": "GSS_C_NO_OID_SET",
                  "type": "codeVoice"
                },
                {
                  "text": " to get the default set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "desired_mechs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A flag that indicates how the credential will be used. Specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for context initiation, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for context acceptance, or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for both.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cred_usage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the credential. Release the credential’s memory with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "output_cred_handle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the actual mechanisms used by the credential. Set to ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output. If you do receive a set of mechanisms, use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to release its memory when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "actual_mechs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the actual number of seconds for which the credential is valid. Set to ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "time_rec"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A status code set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on success. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a description of other status outputs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)": {
      "abstract": [
        {
          "text": "Returns the name describing the credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyName"
        }
      ],
      "role": "symbol",
      "title": "GSSCredentialCopyName(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscredentialcopyname(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)": {
      "abstract": [
        {
          "text": "Returns a copy of the universally unique identifier corresponding to a GSS credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyUUID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyUUID"
        }
      ],
      "role": "symbol",
      "title": "GSSCredentialCopyUUID(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscredentialcopyuuid(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can accept a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_ACCEPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_ACCEPT"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_ACCEPT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_accept"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can both initiate and accept security contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_BOTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_BOTH"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_BOTH",
      "type": "topic",
      "url": "/documentation/gss/gss_c_both"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE": {
      "abstract": [
        {
          "text": "The value that indicates the maximum permitted lifetime when used in a time request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INDEFINITE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_indefinite"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can initiate a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INITIATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INITIATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INITIATE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_initiate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME": {
      "abstract": [
        {
          "text": "An empty name object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE": {
      "abstract": [
        {
          "text": "The operation completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_COMPLETE",
      "type": "topic",
      "url": "/documentation/gss/gss_s_complete"
    },
    "doc://com.apple.gss/documentation/GSS/OM_uint32": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "role": "symbol",
      "title": "OM_uint32",
      "type": "topic",
      "url": "/documentation/gss/om_uint32"
    },
    "doc://com.apple.gss/documentation/GSS/function-status": {
      "abstract": [
        {
          "text": "Evaluate return values that most GSS-API functions use to indicate the outcome of an operation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Function Status",
      "type": "topic",
      "url": "/documentation/gss/function-status"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set": {
      "abstract": [
        {
          "text": "A pointer to a descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a new credential using a password or certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_aapl_initial_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_aapl_initial_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_aapl_initial_cred(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_aapl_initial_cred(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a credential for use in establishing a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_acquire_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_acquire_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_acquire_cred(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_acquire_cred(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a credential for use in establishing a security context using a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_acquire_cred_with_password"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_acquire_cred_with_password"
        }
      ],
      "role": "symbol",
      "title": "gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_t": {
      "abstract": [
        {
          "text": "A pointer to a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t": {
      "abstract": [
        {
          "text": "A credential usage value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_usage_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_usage_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_usage_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_usage_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a name in contiguous octet format to the internal name format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_import_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_import_name"
        }
      ],
      "role": "symbol",
      "title": "gss_import_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_import_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_name_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a pseudo-random byte stream for keying.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_pseudo_random"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_pseudo_random"
        }
      ],
      "role": "symbol",
      "title": "gss_pseudo_random(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_pseudo_random(_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory of a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_release_cred(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_cred(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory associated with an OID set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_oid_set"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_oid_set"
        }
      ],
      "role": "symbol",
      "title": "gss_release_oid_set(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_oid_set(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Acquisition",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
        "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
        "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)"
      ],
      "title": "Acquisition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_acquire_cred_with_password"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_acquire_cred_with_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Acquisition",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
                "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
                "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)"
              ],
              "title": "Acquisition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_acquire_cred_with_password"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "minor_status"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_name_t",
                    "text": "gss_name_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "desired_name"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_buffer_t",
                    "text": "gss_buffer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "password"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "time_req"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_OID_set",
                    "text": "gss_OID_set"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "desired_mechs"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_usage_t",
                    "text": "gss_cred_usage_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cred_usage"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_id_t",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "output_cred_handle"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_OID_set",
                    "text": "gss_OID_set"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "actual_mechs"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "time_rec"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to the secondary status result that provides additional information in case of failure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "minor_status"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the principal whose credential should be acquired. Specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to get a generic credential or use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to obtain a name object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "desired_name"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The password.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "password"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The time in seconds that the credential should remain valid. Use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to indicate the maximum allowed duration.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "time_req"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The set of underlying security mechanisms to use with the credential. Use ",
                        "type": "text"
                      },
                      {
                        "code": "GSS_C_NO_OID_SET",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to get the default set.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "desired_mechs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A flag that indicates how the credential will be used. Specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for context initiation, ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for context acceptance, or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for both.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cred_usage"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the credential. Release the credential’s memory with ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "output_cred_handle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the actual mechanisms used by the credential. Set to ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output. If you do receive a set of mechanisms, use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to release its memory when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "actual_mechs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the actual number of seconds for which the credential is valid. Set to ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "time_rec"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A status code set to ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " on success. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for a description of other status outputs.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid_set(_:_:)/title",
          "value": "gss_release_oid_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid_set(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_oid_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/title",
          "value": "gss_import_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_import_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title",
          "value": "GSS_S_COMPLETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_COMPLETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_pseudo_random(_:_:_:_:_:_:)/title",
          "value": "gss_pseudo_random"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_pseudo_random(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_pseudo_random"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)/title",
          "value": "gss_acquire_cred_with_password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_acquire_cred_with_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred(_:_:_:_:_:_:_:_:)/title",
          "value": "gss_acquire_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_acquire_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/title",
          "value": "GSS_C_INITIATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INITIATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/title",
          "value": "GSS_C_BOTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_BOTH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/title",
          "value": "gss_release_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_initial_cred(_:_:_:_:_:)/title",
          "value": "gss_aapl_initial_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_initial_cred(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_aapl_initial_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title",
          "value": "OM_uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/title",
          "value": "gss_cred_usage_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_usage_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_usage_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/title",
          "value": "gss_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/title",
          "value": "gss_OID_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/title",
          "value": "GSS_C_INDEFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INDEFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyName(_:)/title",
          "value": "GSSCredentialCopyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialCopyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title",
          "value": "gss_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/title",
          "value": "GSS_C_ACCEPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_ACCEPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyUUID(_:)/title",
          "value": "GSSCredentialCopyUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyUUID(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialCopyUUID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
