{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DECnet"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"],"title":"Address Families","anchor":"Address-Families"}],"abstract":[{"text":"The DECnet address type.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_DECnet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["/documentation/gss/gss_c_af_decnet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/gss/gss_c_af_decnet"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Global Variable","modules":[{"name":"GSS"}],"platforms":[{"beta":false,"introducedAt":"5.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"5.0","unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"Mac Catalyst","deprecated":false},{"name":"macOS","introducedAt":"10.14","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false}],"externalID":"c:@macro@GSS_C_AF_DECnet","navigatorTitle":[{"text":"GSS_C_AF_DECnet","kind":"identifier"}],"symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_DECnet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"GSS_C_AF_DECnet","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","abstract":[{"type":"text","text":"The LAT address type."}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_LAT","url":"/documentation/gss/gss_c_af_lat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_LAT","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_LAT","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP":{"abstract":[{"text":"The PUP protocols (for example, BSP) address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_pup","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_PUP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_PUP","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_PUP","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC":{"url":"/documentation/gss/gss_c_af_bsc","navigatorTitle":[{"text":"GSS_C_AF_BSC","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","role":"symbol","abstract":[{"text":"The BISYNC 2780/3780 address type.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_BSC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_BSC","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_CCITT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","title":"GSS_C_AF_CCITT","url":"/documentation/gss/gss_c_af_ccitt","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_CCITT"}],"abstract":[{"type":"text","text":"The CCITT protocols address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS":{"type":"topic","title":"GSS_C_AF_NS","role":"symbol","abstract":[{"text":"The Xerox NS address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_NS","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_NS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_ns","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET","url":"/documentation/gss/gss_c_af_inet","navigatorTitle":[{"text":"GSS_C_AF_INET","kind":"identifier"}],"abstract":[{"type":"text","text":"The Internet (for example, IP) address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA":{"abstract":[{"text":"The IBM SNA address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_sna","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_SNA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_SNA","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_SNA","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","abstract":[{"type":"text","text":"The direct data link interface address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_DLI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_DLI","role":"symbol","url":"/documentation/gss/gss_c_af_dli","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI":{"type":"topic","title":"GSS_C_AF_OSI","role":"symbol","abstract":[{"text":"The OSI TP4 address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_OSI","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_OSI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_osi","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","abstract":[{"text":"The ECMA address type.","type":"text"}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_ECMA","url":"/documentation/gss/gss_c_af_ecma","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"GSS_C_AF_ECMA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_ECMA","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25":{"url":"/documentation/gss/gss_c_af_x25","navigatorTitle":[{"text":"GSS_C_AF_X25","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","role":"symbol","abstract":[{"type":"text","text":"The X.25 address type."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_X25","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_X25","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS":{"abstract":[{"text":"The distributed system services address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_dss","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_DSS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_DSS","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_DSS","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DECnet":{"url":"/documentation/gss/gss_c_af_decnet","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_DECnet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"GSS_C_AF_DECnet","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DECnet","title":"GSS_C_AF_DECnet","abstract":[{"type":"text","text":"The DECnet address type."}],"role":"symbol","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET6","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET6","url":"/documentation/gss/gss_c_af_inet6","navigatorTitle":[{"text":"GSS_C_AF_INET6","kind":"identifier"}],"abstract":[{"type":"text","text":"The IPv6 address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","abstract":[{"type":"text","text":"The MIT CHAOS protocol address type."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_CHAOS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_CHAOS","role":"symbol","url":"/documentation/gss/gss_c_af_chaos","navigatorTitle":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","abstract":[{"type":"text","text":"The nbs address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_NBS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_NBS","role":"symbol","url":"/documentation/gss/gss_c_af_nbs","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_NBS"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"unavailable":false,"introducedAt":"5.0","beta":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"5.0","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","introducedAt":"10.14","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false}],"op":"replace"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GSS_C_AF_DECnet","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_DECnet"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Address-Families","title":"Address Families","identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_DECnet"}]}],"kind":"declarations"}},{"op":"replace","value":"GSS_C_AF_LAT","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_LAT"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/fragments"},{"op":"replace","value":"GSS_C_AF_PUP","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/title"},{"op":"replace","value":[{"text":"GSS_C_AF_PUP","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/fragments"},{"op":"replace","value":"GSS_C_AF_BSC","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_BSC"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/fragments"},{"op":"replace","value":"GSS_C_AF_CCITT","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_CCITT"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/fragments"},{"op":"replace","value":"GSS_C_AF_NS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/title"},{"op":"replace","value":[{"text":"GSS_C_AF_NS","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/fragments"},{"op":"replace","value":"GSS_C_AF_INET","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/title"},{"op":"replace","value":[{"text":"GSS_C_AF_INET","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/fragments"},{"op":"replace","value":"GSS_C_AF_SNA","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/title"},{"op":"replace","value":[{"text":"GSS_C_AF_SNA","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/fragments"},{"op":"replace","value":"GSS_C_AF_DLI","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/fragments"},{"op":"replace","value":"GSS_C_AF_OSI","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/title"},{"op":"replace","value":[{"text":"GSS_C_AF_OSI","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/fragments"},{"op":"replace","value":"GSS_C_AF_ECMA","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/title"},{"op":"replace","value":[{"text":"GSS_C_AF_ECMA","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/fragments"},{"op":"replace","value":"GSS_C_AF_X25","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_X25"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/fragments"},{"op":"replace","value":"GSS_C_AF_DSS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/title"},{"op":"replace","value":[{"text":"GSS_C_AF_DSS","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/fragments"},{"op":"replace","value":"GSS_C_AF_DECnet","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DECnet/title"},{"op":"replace","value":[{"text":"GSS_C_AF_DECnet","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DECnet/fragments"},{"op":"replace","value":"GSS_C_AF_INET6","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/title"},{"op":"replace","value":[{"kind":"identifier","text":"GSS_C_AF_INET6"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/fragments"},{"op":"replace","value":"GSS_C_AF_CHAOS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/title"},{"op":"replace","value":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/fragments"},{"op":"replace","value":"GSS_C_AF_NBS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/title"},{"op":"replace","value":[{"text":"GSS_C_AF_NBS","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}