{
  "abstract": [
    {
      "text": "The structure for a vectored I/O buffer and its defined type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@gss_iov_buffer_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_iov_buffer_t"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_iov_buffer_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "gss_iov_buffer_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@gss_iov_buffer_desc_struct",
              "text": "gss_iov_buffer_desc_struct"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_EMPTY_BUFFER": {
      "abstract": [
        {
          "text": "The GSS buffer object has no value, and its length set to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_EMPTY_BUFFER"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_EMPTY_BUFFER",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_EMPTY_BUFFER",
      "type": "topic",
      "url": "/documentation/gss/gss_c_empty_buffer"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER": {
      "abstract": [
        {
          "text": "The GSS buffer object has no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_BUFFER"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_BUFFER",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_buffer"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER_SET": {
      "abstract": [
        {
          "text": "The GSS buffer set object has no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_BUFFER_SET"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER_SET",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_BUFFER_SET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_buffer_set"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_IOV_BUFFER": {
      "abstract": [
        {
          "text": "The GSS IOV buffer object has no value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_IOV_BUFFER"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_IOV_BUFFER",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_IOV_BUFFER",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_iov_buffer"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID": {
      "abstract": [
        {
          "text": "A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_desc": {
      "abstract": [
        {
          "text": "The buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct": {
      "abstract": [
        {
          "text": "The structure for a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc": {
      "abstract": [
        {
          "text": "The descriptor that you use to manage an array of buffer descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_set_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_set_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_set_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_set_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc_struct": {
      "abstract": [
        {
          "text": "The structure for a buffer set descriptor that you use to manage an array of buffer descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_set_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_set_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_set_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_set_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_set_t": {
      "abstract": [
        {
          "text": "A pointer to the descriptor that you use to manage an array of buffer descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_set_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_set_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_set_t"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_set_t",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_set_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_t": {
      "abstract": [
        {
          "text": "A pointer to a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_buffer_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_const_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc": {
      "abstract": [
        {
          "text": "The structure for a vectored I/O buffer and its defined type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_iov_buffer_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct": {
      "abstract": [
        {
          "text": "The structure for a vectored I/O buffer and its defined type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_iov_buffer_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_t": {
      "abstract": [
        {
          "text": "The structure for a vectored I/O buffer and its defined type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_iov_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_iov_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_qop_t": {
      "abstract": [
        {
          "text": "A quality of protection setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_qop_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_qop_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_qop_t"
        }
      ],
      "role": "symbol",
      "title": "gss_qop_t",
      "type": "topic",
      "url": "/documentation/gss/gss_qop_t"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Buffer-Data-Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_qop_t",
        "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc",
        "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
        "doc://com.apple.gss/documentation/GSS/gss_const_buffer_t",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_set_t",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_desc",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc",
        "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc_struct"
      ],
      "title": "Buffer Data Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_iov_buffer_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Buffer-Data-Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_BUFFER_SET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_EMPTY_BUFFER",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_IOV_BUFFER",
                "doc://com.apple.gss/documentation/GSS/gss_qop_t",
                "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc",
                "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
                "doc://com.apple.gss/documentation/GSS/gss_const_buffer_t",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_set_t",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_desc",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_desc_struct",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc",
                "doc://com.apple.gss/documentation/GSS/gss_buffer_set_desc_struct"
              ],
              "title": "Buffer Data Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_iov_buffer_desc_struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@gss_iov_buffer_desc_struct",
                    "text": "gss_iov_buffer_desc_struct"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_iov_buffer_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_qop_t/title",
          "value": "gss_qop_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_qop_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_qop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_qop_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_qop_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc/title",
          "value": "gss_iov_buffer_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_t/title",
          "value": "gss_iov_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_buffer_t/title",
          "value": "gss_const_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/title",
          "value": "gss_buffer_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc_struct/title",
          "value": "gss_buffer_set_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_t/title",
          "value": "gss_buffer_set_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title",
          "value": "gss_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc_struct/title",
          "value": "gss_iov_buffer_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iov_buffer_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iov_buffer_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/title",
          "value": "gss_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/title",
          "value": "gss_buffer_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc/title",
          "value": "gss_buffer_set_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_set_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_set_desc"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_iov_buffer_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_iov_buffer_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
