{
  "abstract": [
    {
      "text": "The Xerox NS address type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_C_AF_NS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSS_C_AF_NS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_C_AF_NS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GSS_C_AF_NS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_C_AF_NS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC": {
      "abstract": [
        {
          "text": "The BISYNC 2780/3780 address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_BSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_BSC"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_BSC",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_bsc"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT": {
      "abstract": [
        {
          "text": "The CCITT protocols address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_CCITT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_CCITT"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_CCITT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_ccitt"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS": {
      "abstract": [
        {
          "text": "The MIT CHAOS protocol address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_CHAOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_CHAOS"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_CHAOS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_chaos"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI": {
      "abstract": [
        {
          "text": "The direct data link interface address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_DLI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_DLI"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_DLI",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_dli"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS": {
      "abstract": [
        {
          "text": "The distributed system services address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_DSS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_DSS"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_DSS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_dss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA": {
      "abstract": [
        {
          "text": "The ECMA address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_ECMA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_ECMA"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_ECMA",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_ecma"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET": {
      "abstract": [
        {
          "text": "The Internet (for example, IP) address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_INET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_INET"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_INET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_inet"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6": {
      "abstract": [
        {
          "text": "The IPv6 address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_INET6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_INET6"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_INET6",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_inet6"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT": {
      "abstract": [
        {
          "text": "The LAT address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_LAT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_LAT"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_LAT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_lat"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LOCAL": {
      "abstract": [
        {
          "text": "The host-local address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_LOCAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LOCAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_LOCAL"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_LOCAL",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_local"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS": {
      "abstract": [
        {
          "text": "The nbs address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_NBS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_NBS"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_NBS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_nbs"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS": {
      "abstract": [
        {
          "text": "The Xerox NS address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_NS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_NS"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_NS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_ns"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI": {
      "abstract": [
        {
          "text": "The OSI TP4 address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_OSI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_OSI"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_OSI",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_osi"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP": {
      "abstract": [
        {
          "text": "The PUP protocols (for example, BSP) address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_PUP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_PUP"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_PUP",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_pup"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA": {
      "abstract": [
        {
          "text": "The IBM SNA address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_SNA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_SNA"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_SNA",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_sna"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25": {
      "abstract": [
        {
          "text": "The X.25 address type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_AF_X25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_AF_X25"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_AF_X25",
      "type": "topic",
      "url": "/documentation/gss/gss_c_af_x25"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Address-Families",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6",
        "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LOCAL"
      ],
      "title": "Address Families"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSS_C_AF_NS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_NS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Address-Families",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6",
                "doc://com.apple.gss/documentation/GSS/GSS_C_AF_LOCAL"
              ],
              "title": "Address Families"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSS_C_AF_NS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/title",
          "value": "GSS_C_AF_BSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_BSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/title",
          "value": "GSS_C_AF_INET6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_INET6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/title",
          "value": "GSS_C_AF_PUP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_PUP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/title",
          "value": "GSS_C_AF_NBS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_NBS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/title",
          "value": "GSS_C_AF_OSI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_OSI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/title",
          "value": "GSS_C_AF_CHAOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_CHAOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/title",
          "value": "GSS_C_AF_CCITT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_CCITT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/title",
          "value": "GSS_C_AF_INET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_INET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/title",
          "value": "GSS_C_AF_ECMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_ECMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/title",
          "value": "GSS_C_AF_X25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_X25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/title",
          "value": "GSS_C_AF_LAT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_LAT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/title",
          "value": "GSS_C_AF_SNA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_SNA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/title",
          "value": "GSS_C_AF_DSS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_DSS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/title",
          "value": "GSS_C_AF_DLI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_DLI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LOCAL/title",
          "value": "GSS_C_AF_LOCAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LOCAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_LOCAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/title",
          "value": "GSS_C_AF_NS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_AF_NS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_c_af_ns"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_c_af_ns"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
