{
  "abstract": [
    {
      "text": "Accepts a security context initiated by a peer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@gss_accept_sec_context",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_accept_sec_context"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_ctx_id_t",
        "text": "gss_ctx_id_t"
      },
      {
        "kind": "text",
        "text": "?>, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_buffer_t",
        "text": "gss_buffer_t"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_channel_bindings_t",
        "text": "gss_channel_bindings_t"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_name_t",
        "text": "gss_name_t"
      },
      {
        "kind": "text",
        "text": "?>?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_OID",
        "text": "gss_OID"
      },
      {
        "kind": "text",
        "text": "?>?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_buffer_t",
        "text": "gss_buffer_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": "?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_accept_sec_context"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_accept_sec_context"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "minor_status"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "context_handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_ctx_id_t",
              "text": "gss_ctx_id_t"
            },
            {
              "kind": "text",
              "text": "?>, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "acceptor_cred_handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "input_token"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_buffer_t",
              "text": "gss_buffer_t"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "input_chan_bindings"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_channel_bindings_t",
              "text": "gss_channel_bindings_t"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "src_name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_name_t",
              "text": "gss_name_t"
            },
            {
              "kind": "text",
              "text": "?>?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mech_type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_OID",
              "text": "gss_OID"
            },
            {
              "kind": "text",
              "text": "?>?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "output_token"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_buffer_t",
              "text": "gss_buffer_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ret_flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "time_rec"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "delegated_cred_handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": "?>?) -> "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the secondary status result that provides additional information in case of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "minor_status"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the context. Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for first call and use the value returned by the first call in continuation calls. Release the context’s resources using the  ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context_handle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The credential claimed by the acceptor. Specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to use the default credential.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "acceptor_cred_handle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The token obtained from the peer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "input_token"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Channel bindings to use. Pass  ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " if channel bindings are not used.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "input_chan_bindings"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the authenticated name of the context initiator. Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "src_name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the mechanism used by the context. Do ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "not",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " free this object because it is held in static memory.  Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mech_type"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A buffer the function fills with a token to transmit to the peer. If the buffer length is zero, there is no token to pass. Otherwise, free the token buffer’s memory using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_buffer(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "output_token"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the flags supported by the context. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/context-services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for a list of possible values. Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ret_flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the number of seconds for which the context is valid. Specify ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this output.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "time_rec"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer the function uses to return the credentials of the initiator. The function returns ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " unless the ",
                  "type": "text"
                },
                {
                  "code": "ret_flags",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter includes ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". If the credential exists, release its memory with ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "delegated_cred_handle"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG": {
      "abstract": [
        {
          "text": "A flag that permits delegation of the initiator’s credentials by the acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_DELEG_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_deleg_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CHANNEL_BINDINGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CHANNEL_BINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_channel_bindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT": {
      "abstract": [
        {
          "text": "A macro that indicates an empty context id object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CONTEXT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CONTEXT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_context"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL": {
      "abstract": [
        {
          "text": "The value that indicates an empty credential object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CREDENTIAL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CREDENTIAL",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_credential"
    },
    "doc://com.apple.gss/documentation/GSS/OM_uint32": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "role": "symbol",
      "title": "OM_uint32",
      "type": "topic",
      "url": "/documentation/gss/om_uint32"
    },
    "doc://com.apple.gss/documentation/GSS/context-services": {
      "abstract": [
        {
          "text": "Use context services to manage secure operations between endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/context-services",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Context Services",
      "type": "topic",
      "url": "/documentation/gss/context-services"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID": {
      "abstract": [
        {
          "text": "A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Accepts a security context initiated by a peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_accept_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_channel_bindings_t",
          "text": "gss_channel_bindings_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_accept_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_t": {
      "abstract": [
        {
          "text": "A pointer to a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t": {
      "abstract": [
        {
          "text": "A pointer to a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_t",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate context pointers with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_ctx_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_ctx_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)": {
      "abstract": [
        {
          "text": "Deletes a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_delete_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_delete_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gss_delete_sec_context(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_delete_sec_context(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Initiates a security context with a peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_init_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_channel_bindings_t",
          "text": "gss_channel_bindings_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_init_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_name_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_process_context_token(_:_:_:)": {
      "abstract": [
        {
          "text": "Processes a token from a peer asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_process_context_token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_process_context_token(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_process_context_token"
        }
      ],
      "role": "symbol",
      "title": "gss_process_context_token(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_process_context_token(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_buffer(_:_:)": {
      "abstract": [
        {
          "text": "Frees the memory associated with a single buffer descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_buffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_buffer(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_buffer"
        }
      ],
      "role": "symbol",
      "title": "gss_release_buffer(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_buffer(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory of a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_release_cred(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_cred(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_set_sec_context_option(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets an option on a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_set_sec_context_option"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_set_sec_context_option(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_set_sec_context_option"
        }
      ],
      "role": "symbol",
      "title": "gss_set_sec_context_option(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_set_sec_context_option(_:_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creation-and-Deletion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_process_context_token(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_set_sec_context_option(_:_:_:_:)"
      ],
      "title": "Creation and Deletion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_accept_sec_context"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_accept_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creation-and-Deletion",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_process_context_token(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_set_sec_context_option(_:_:_:_:)"
              ],
              "title": "Creation and Deletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_accept_sec_context"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "minor_status"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_ctx_id_t",
                    "text": "gss_ctx_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "context_handle"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_id_t",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "acceptor_cred_handle"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_buffer_t",
                    "text": "gss_buffer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "input_token"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_channel_bindings_t",
                    "text": "gss_channel_bindings_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "input_chan_bindings"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_name_t",
                    "text": "gss_name_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "src_name"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_OID",
                    "text": "gss_OID"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mech_type"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_buffer_t",
                    "text": "gss_buffer_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "output_token"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ret_flags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "time_rec"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_id_t",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "delegated_cred_handle"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to the secondary status result that provides additional information in case of failure.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "minor_status"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the context. Pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for first call and use the value returned by the first call in continuation calls. Release the context’s resources using the  ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_delete_sec_context(_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "context_handle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The credential claimed by the acceptor. Specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to use the default credential.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "acceptor_cred_handle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The token obtained from the peer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "input_token"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Channel bindings to use. Pass  ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " if channel bindings are not used.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "input_chan_bindings"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the authenticated name of the context initiator. Specify ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "src_name"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the mechanism used by the context. Do ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "not",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " free this object because it is held in static memory.  Specify ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mech_type"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A buffer the function fills with a token to transmit to the peer. If the buffer length is zero, there is no token to pass. Otherwise, free the token buffer’s memory using ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_buffer(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "output_token"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the flags supported by the context. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/context-services",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for a list of possible values. Specify ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "ret_flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the number of seconds for which the context is valid. Specify ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this output.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "time_rec"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer the function uses to return the credentials of the initiator. The function returns ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " unless the ",
                        "type": "text"
                      },
                      {
                        "code": "ret_flags",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter includes ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". If the credential exists, release its memory with ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "delegated_cred_handle"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_set_sec_context_option(_:_:_:_:)/title",
          "value": "gss_set_sec_context_option"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_set_sec_context_option(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_set_sec_context_option"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title",
          "value": "gss_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_delete_sec_context(_:_:_:)/title",
          "value": "gss_delete_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_delete_sec_context(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_delete_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/title",
          "value": "gss_channel_bindings_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "gss_accept_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_accept_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title",
          "value": "OM_uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title",
          "value": "gss_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/title",
          "value": "gss_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/title",
          "value": "gss_ctx_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_buffer(_:_:)/title",
          "value": "gss_release_buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_buffer(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_process_context_token(_:_:_:)/title",
          "value": "gss_process_context_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_process_context_token(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_process_context_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/title",
          "value": "gss_release_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/title",
          "value": "GSS_C_DELEG_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_DELEG_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "gss_init_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_init_sec_context"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
