{
  "abstract": [
    {
      "text": "Indicates a ",
      "type": "text"
    },
    {
      "code": "NULL",
      "type": "codeVoice"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_C_NO_CHANNEL_BINDINGS",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GSS_C_NO_CHANNEL_BINDINGS"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_C_NO_CHANNEL_BINDINGS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "GSS_C_NO_CHANNEL_BINDINGS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_C_NO_CHANNEL_BINDINGS"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CHANNEL_BINDINGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CHANNEL_BINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_channel_bindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT": {
      "abstract": [
        {
          "text": "A macro that indicates an empty context id object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CONTEXT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CONTEXT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_context"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct": {
      "abstract": [
        {
          "text": "The structure defining a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t": {
      "abstract": [
        {
          "text": "A pointer to a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_t",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable channel bindings descriptor that you use to specify the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_channel_bindings_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_channel_bindings_t"
        }
      ],
      "role": "symbol",
      "title": "gss_const_channel_bindings_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_channel_bindings_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable opaque type that you use to communicate context pointers with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_const_ctx_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_const_ctx_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_ctx_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate context pointers with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_ctx_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_ctx_id_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Channel-Bindings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
        "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t",
        "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
        "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t"
      ],
      "title": "Channel Bindings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/title",
          "value": "gss_channel_bindings_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/title",
          "value": "gss_const_channel_bindings_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/title",
          "value": "gss_ctx_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/title",
          "value": "gss_channel_bindings_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_c_no_channel_bindings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
