{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@gss_krb5_lucid_context_v1",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_krb5_lucid_context_v1"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_krb5_lucid_context_v1"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "gss_krb5_lucid_context_v1"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_cfx_keydata",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_cfx_keydata"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_v1",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/cfx_kd": {
      "abstract": [
        {
          "text": "The key data structure for Kerberos 5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cfx_kd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_krb5_cfx_keydata_t",
          "text": "gss_krb5_cfx_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/cfx_kd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cfx_kd"
        }
      ],
      "role": "symbol",
      "title": "cfx_kd",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/cfx_kd"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/endtime": {
      "abstract": [
        {
          "text": "The expiration time of the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endtime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/endtime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endtime"
        }
      ],
      "role": "symbol",
      "title": "endtime",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/endtime"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/init()"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init(version:initiate:endtime:send_seq:recv_seq:protocol:rfc1964_kd:cfx_kd:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "initiate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endtime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "send_seq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint64",
          "text": "OM_uint64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recv_seq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint64",
          "text": "OM_uint64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rfc1964_kd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_krb5_rfc1964_keydata_t",
          "text": "gss_krb5_rfc1964_keydata_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cfx_kd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_krb5_cfx_keydata_t",
          "text": "gss_krb5_cfx_keydata_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init(version:initiate:endtime:send_seq:recv_seq:protocol:rfc1964_kd:cfx_kd:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:initiate:endtime:send_seq:recv_seq:protocol:rfc1964_kd:cfx_kd:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/init(version:initiate:endtime:send_seq:recv_seq:protocol:rfc1964_kd:cfx_kd:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/initiate": {
      "abstract": [
        {
          "text": "The flag indicating if the role is initiator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/initiate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiate"
        }
      ],
      "role": "symbol",
      "title": "initiate",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/initiate"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/protocol": {
      "abstract": [
        {
          "text": "The protocol to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`protocol`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "protocol"
        }
      ],
      "role": "symbol",
      "title": "protocol",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/protocol"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/recv_seq": {
      "abstract": [
        {
          "text": "The receive sequence number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recv_seq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint64",
          "text": "OM_uint64"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/recv_seq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recv_seq"
        }
      ],
      "role": "symbol",
      "title": "recv_seq",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/recv_seq"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/rfc1964_kd": {
      "abstract": [
        {
          "text": "The RFC-1964 key data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfc1964_kd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_krb5_rfc1964_keydata_t",
          "text": "gss_krb5_rfc1964_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/rfc1964_kd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfc1964_kd"
        }
      ],
      "role": "symbol",
      "title": "rfc1964_kd",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/rfc1964_kd"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/send_seq": {
      "abstract": [
        {
          "text": "The send sequence number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send_seq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint64",
          "text": "OM_uint64"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/send_seq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "send_seq"
        }
      ],
      "role": "symbol",
      "title": "send_seq",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/send_seq"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/version": {
      "abstract": [
        {
          "text": "The structure version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1/version"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_version",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_key",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_key"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_rfc1964_keydata",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_rfc1964_keydata"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init()",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/init(version:initiate:endtime:send_seq:recv_seq:protocol:rfc1964_kd:cfx_kd:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/cfx_kd",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/endtime",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/initiate",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/protocol",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/recv_seq",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/rfc1964_kd",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/send_seq",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_krb5_lucid_context_v1"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/cfx_kd",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/endtime",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/initiate",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/protocol",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/recv_seq",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/rfc1964_kd",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/send_seq",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_krb5_lucid_context_v1"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1rfc1964_kd/title",
          "value": "rfc1964_kd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1rfc1964_kd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rfc1964_kd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1cfx_kd/title",
          "value": "cfx_kd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1cfx_kd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cfx_kd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/title",
          "value": "gss_krb5_rfc1964_keydata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1protocol/title",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "protocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/title",
          "value": "gss_krb5_lucid_context_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1endtime/title",
          "value": "endtime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1endtime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endtime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1recv_seq/title",
          "value": "recv_seq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1recv_seq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recv_seq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/title",
          "value": "gss_krb5_lucid_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1send_seq/title",
          "value": "send_seq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1send_seq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "send_seq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/title",
          "value": "gss_krb5_cfx_keydata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1initiate/title",
          "value": "initiate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1~1initiate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/title",
          "value": "gss_krb5_lucid_context_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_krb5_lucid_context_v1"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_krb5_lucid_context_v1"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
