{
  "abstract": [
    {
      "text": "The offset of the supplementary information field within the major status code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_OFFSET"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_C_SUPPLEMENTARY_OFFSET",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSS_C_SUPPLEMENTARY_OFFSET"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_C_SUPPLEMENTARY_OFFSET"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GSS_C_SUPPLEMENTARY_OFFSET"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_C_SUPPLEMENTARY_OFFSET"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_MASK": {
      "abstract": [
        {
          "text": "A mask with a width that matches the calling error field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_CALLING_ERROR_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_CALLING_ERROR_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_CALLING_ERROR_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_c_calling_error_mask"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_OFFSET": {
      "abstract": [
        {
          "text": "The offset of the calling error field within the major status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_CALLING_ERROR_OFFSET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_OFFSET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_CALLING_ERROR_OFFSET"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_CALLING_ERROR_OFFSET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_calling_error_offset"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_MASK": {
      "abstract": [
        {
          "text": "A mask with a width that matches the routine error field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_ROUTINE_ERROR_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_ROUTINE_ERROR_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_ROUTINE_ERROR_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_c_routine_error_mask"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_OFFSET": {
      "abstract": [
        {
          "text": "The offset of the routine error field within the major status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_ROUTINE_ERROR_OFFSET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_OFFSET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_ROUTINE_ERROR_OFFSET"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_ROUTINE_ERROR_OFFSET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_routine_error_offset"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_MASK": {
      "abstract": [
        {
          "text": "A mask with a width that matches the supplementary information field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_SUPPLEMENTARY_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_SUPPLEMENTARY_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_SUPPLEMENTARY_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_c_supplementary_mask"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_OFFSET": {
      "abstract": [
        {
          "text": "The offset of the supplementary information field within the major status code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_SUPPLEMENTARY_OFFSET"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_OFFSET",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_SUPPLEMENTARY_OFFSET"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_SUPPLEMENTARY_OFFSET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_supplementary_offset"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Masks-and-Offsets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_MASK",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_OFFSET",
        "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_MASK",
        "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_OFFSET",
        "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_MASK"
      ],
      "title": "Masks and Offsets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSS_C_SUPPLEMENTARY_OFFSET"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_SUPPLEMENTARY_OFFSET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Masks-and-Offsets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_MASK",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CALLING_ERROR_OFFSET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_MASK",
                "doc://com.apple.gss/documentation/GSS/GSS_C_ROUTINE_ERROR_OFFSET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_SUPPLEMENTARY_MASK"
              ],
              "title": "Masks and Offsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSS_C_SUPPLEMENTARY_OFFSET"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CALLING_ERROR_OFFSET/title",
          "value": "GSS_C_CALLING_ERROR_OFFSET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CALLING_ERROR_OFFSET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_CALLING_ERROR_OFFSET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CALLING_ERROR_MASK/title",
          "value": "GSS_C_CALLING_ERROR_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CALLING_ERROR_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_CALLING_ERROR_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SUPPLEMENTARY_OFFSET/title",
          "value": "GSS_C_SUPPLEMENTARY_OFFSET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SUPPLEMENTARY_OFFSET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_SUPPLEMENTARY_OFFSET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ROUTINE_ERROR_OFFSET/title",
          "value": "GSS_C_ROUTINE_ERROR_OFFSET"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ROUTINE_ERROR_OFFSET/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_ROUTINE_ERROR_OFFSET"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SUPPLEMENTARY_MASK/title",
          "value": "GSS_C_SUPPLEMENTARY_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SUPPLEMENTARY_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_SUPPLEMENTARY_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ROUTINE_ERROR_MASK/title",
          "value": "GSS_C_ROUTINE_ERROR_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ROUTINE_ERROR_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_ROUTINE_ERROR_MASK"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_c_supplementary_offset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_c_supplementary_offset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
