{
  "abstract": [
    {
      "text": "A flag that makes integrity services (that is, cryptographic signatures) available for transferred messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_C_INTEG_FLAG",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSS_C_INTEG_FLAG"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_C_INTEG_FLAG"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GSS_C_INTEG_FLAG"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_C_INTEG_FLAG"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When set, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions to sign and verify the data transferred. When the flag is not set, you can create and test your own cryptographic signatures, but the GSS-API does not provide this service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG": {
      "abstract": [
        {
          "text": "A flag that ensures the initiator remains anonymous to the acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_ANON_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_ANON_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_ANON_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_anon_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG": {
      "abstract": [
        {
          "text": "A flag that makes confidentiality services (that is, encryption) available for transferred messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_CONF_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_CONF_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_CONF_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_conf_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE": {
      "abstract": [
        {
          "text": "A flag that causes an extra AP reply to be sent from the client back to the server after receiving the server’s AP reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_DCE_STYLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_DCE_STYLE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_DCE_STYLE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_dce_style"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG": {
      "abstract": [
        {
          "text": "A flag that permits delegation of the initiator’s credentials by the acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_DELEG_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_deleg_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG": {
      "abstract": [
        {
          "text": "A flag that indicates delegation is permissible if the mechanism policy allows it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_POLICY_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_DELEG_POLICY_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_DELEG_POLICY_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_deleg_policy_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG": {
      "abstract": [
        {
          "text": "A flag that indicates that the client wants to be informed of extended error information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_EXTENDED_ERROR_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_EXTENDED_ERROR_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_EXTENDED_ERROR_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_extended_error_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG": {
      "abstract": [
        {
          "text": "A flag that indicates identification of the client by name and ID only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_IDENTIFY_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_IDENTIFY_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_IDENTIFY_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_identify_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG": {
      "abstract": [
        {
          "text": "A flag that makes integrity services (that is, cryptographic signatures) available for transferred messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INTEG_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INTEG_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INTEG_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_integ_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG": {
      "abstract": [
        {
          "text": "A flag that authenticates the credentials of both initiator and acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_MUTUAL_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_MUTUAL_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_MUTUAL_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_mutual_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG": {
      "abstract": [
        {
          "text": "A flag that provides an early indication of the availability of confidentiality and integrity services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_PROT_READY_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_PROT_READY_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_PROT_READY_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_prot_ready_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG": {
      "abstract": [
        {
          "text": "A flag that detects repeated messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_REPLAY_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_REPLAY_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_REPLAY_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_replay_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG": {
      "abstract": [
        {
          "text": "A flag that detects out of sequence messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_SEQUENCE_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_SEQUENCE_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_SEQUENCE_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_sequence_flag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG": {
      "abstract": [
        {
          "text": "A flag that indicates that a context can is exportable, for example to transfer it to another process on the same machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_TRANS_FLAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_TRANS_FLAG"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_TRANS_FLAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_trans_flag"
    },
    "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a token that contains the MIC for a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_get_mic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_get_mic"
        }
      ],
      "role": "symbol",
      "title": "gss_get_mic(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_get_mic(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns an indication of whether the integrity of a message is intact, given its MIC token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_verify_mic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_verify_mic"
        }
      ],
      "role": "symbol",
      "title": "gss_verify_mic(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_verify_mic(_:_:_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE",
        "doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG"
      ],
      "title": "Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSS_C_INTEG_FLAG"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INTEG_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Flags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG"
              ],
              "title": "Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSS_C_INTEG_FLAG"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MUTUAL_FLAG/title",
          "value": "GSS_C_MUTUAL_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MUTUAL_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_MUTUAL_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SEQUENCE_FLAG/title",
          "value": "GSS_C_SEQUENCE_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SEQUENCE_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_SEQUENCE_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ANON_FLAG/title",
          "value": "GSS_C_ANON_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ANON_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_ANON_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_IDENTIFY_FLAG/title",
          "value": "GSS_C_IDENTIFY_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_IDENTIFY_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_IDENTIFY_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_POLICY_FLAG/title",
          "value": "GSS_C_DELEG_POLICY_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_POLICY_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_DELEG_POLICY_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DCE_STYLE/title",
          "value": "GSS_C_DCE_STYLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DCE_STYLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_DCE_STYLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_TRANS_FLAG/title",
          "value": "GSS_C_TRANS_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_TRANS_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_TRANS_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CONF_FLAG/title",
          "value": "GSS_C_CONF_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CONF_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_CONF_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_get_mic(_:_:_:_:_:)/title",
          "value": "gss_get_mic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_get_mic(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_get_mic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_EXTENDED_ERROR_FLAG/title",
          "value": "GSS_C_EXTENDED_ERROR_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_EXTENDED_ERROR_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_EXTENDED_ERROR_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INTEG_FLAG/title",
          "value": "GSS_C_INTEG_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INTEG_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INTEG_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_PROT_READY_FLAG/title",
          "value": "GSS_C_PROT_READY_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_PROT_READY_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_PROT_READY_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_REPLAY_FLAG/title",
          "value": "GSS_C_REPLAY_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_REPLAY_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_REPLAY_FLAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify_mic(_:_:_:_:_:)/title",
          "value": "gss_verify_mic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify_mic(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_verify_mic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/title",
          "value": "GSS_C_DELEG_FLAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_DELEG_FLAG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_c_integ_flag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_c_integ_flag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
