{"seeAlsoSections":[{"title":"Status and Error Creation","identifiers":["doc://com.apple.gss/documentation/GSS/OM_uint32","doc://com.apple.gss/documentation/GSS/OM_uint64","doc://com.apple.gss/documentation/GSS/gss_uint32","doc://com.apple.gss/documentation/GSS/gss_status_id_t","doc://com.apple.gss/documentation/GSS/GSS_C_MECH_CODE","doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","doc://com.apple.gss/documentation/GSS/gss_display_status(_:_:_:_:_:_:)","doc://com.apple.gss/documentation/GSS/GSSCreateError(_:_:_:)"],"generated":true,"anchor":"Status-and-Error-Creation"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_GSS_CODE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/GSS_C_GSS_CODE"},"sections":[],"variants":[{"paths":["/documentation/gss/gss_c_gss_code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/gss/gss_c_gss_code"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A flag that indicates the named status code comes from a GSS-API call.","type":"text"}],"metadata":{"roleHeading":"Global Variable","role":"symbol","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"5.0","unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"5.0","unavailable":false},{"introducedAt":"13.0","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"10.14","unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"externalID":"c:@macro@GSS_C_GSS_CODE","symbolKind":"var","modules":[{"name":"GSS"}],"title":"GSS_C_GSS_CODE","navigatorTitle":[{"kind":"identifier","text":"GSS_C_GSS_CODE"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_GSS_CODE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"kind":"symbol","references":{"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.apple.gss/documentation/GSS/GSSCreateError(_:_:_:)":{"identifier":"doc://com.apple.gss/documentation/GSS/GSSCreateError(_:_:_:)","abstract":[{"type":"text","text":"Returns an error object based on GSS-API major and minor status codes."}],"kind":"symbol","type":"topic","role":"symbol","url":"/documentation/gss/gsscreateerror(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSSCreateError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"gss_const_OID","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_const_OID"},{"text":", ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":", ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":") -> ","kind":"text"},{"text":"Unmanaged","kind":"typeIdentifier","preciseIdentifier":"s:s9UnmanagedV"},{"text":"<","kind":"text"},{"text":"CFError","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFErrorRef"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"GSSCreateError","kind":"identifier"}],"title":"GSSCreateError(_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_display_status(_:_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_display_status(_:_:_:_:_:_:)","title":"gss_display_status(_:_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_display_status","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@gss_OID","text":"gss_OID","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_buffer_t","text":"gss_buffer_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Returns a human readable string for a status code.","type":"text"}],"navigatorTitle":[{"text":"gss_display_status","kind":"identifier"}],"url":"/documentation/gss/gss_display_status(_:_:_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_uint32":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_uint32","kind":"identifier"}],"url":"/documentation/gss/gss_uint32","type":"topic","abstract":[{"type":"text","text":"A 32-bit unsigned integer."}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_uint32","navigatorTitle":[{"text":"gss_uint32","kind":"identifier"}],"kind":"symbol","title":"gss_uint32"},"doc://com.apple.gss/documentation/GSS/gss_status_id_t":{"abstract":[{"type":"text","text":"A pointer to a status result."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"gss_status_id_t"}],"title":"gss_status_id_t","kind":"symbol","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_status_id_t","url":"/documentation/gss/gss_status_id_t","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_status_id_t"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_GSS_CODE":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_GSS_CODE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GSS_C_GSS_CODE","kind":"identifier"}],"url":"/documentation/gss/gss_c_gss_code","abstract":[{"type":"text","text":"A flag that indicates the named status code comes from a GSS-API call."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_GSS_CODE","title":"GSS_C_GSS_CODE"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/OM_uint32":{"url":"/documentation/gss/om_uint32","navigatorTitle":[{"kind":"identifier","text":"OM_uint32"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OM_uint32"}],"abstract":[{"type":"text","text":"A 32-bit unsigned integer."}],"title":"OM_uint32","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE":{"navigatorTitle":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"abstract":[{"text":"The operation completed without error.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_COMPLETE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","title":"GSS_S_COMPLETE","type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_complete"},"doc://com.apple.gss/documentation/GSS/GSS_C_MECH_CODE":{"url":"/documentation/gss/gss_c_mech_code","navigatorTitle":[{"text":"GSS_C_MECH_CODE","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_MECH_CODE","role":"symbol","abstract":[{"text":"A flag that indicates the status code comes from a call to an underlying mechanism, such as Kerberos.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_MECH_CODE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_MECH_CODE","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/OM_uint64":{"title":"OM_uint64","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint64","abstract":[{"text":"A 64-bit unsigned integer.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OM_uint64"}],"url":"/documentation/gss/om_uint64","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OM_uint64"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"5.0"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"5.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.0"},{"introducedAt":"10.14","unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Macro","path":"/metadata/roleHeading","op":"replace"},{"value":"GSS_C_GSS_CODE","path":"/metadata/title","op":"replace"},{"value":"macro","path":"/metadata/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"GSS_C_GSS_CODE","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"value":[{"title":"Status and Error Creation","generated":true,"anchor":"Status-and-Error-Creation","identifiers":["doc://com.apple.gss/documentation/GSS/OM_uint32","doc://com.apple.gss/documentation/GSS/OM_uint64","doc://com.apple.gss/documentation/GSS/gss_uint32","doc://com.apple.gss/documentation/GSS/gss_status_id_t","doc://com.apple.gss/documentation/GSS/GSS_C_MECH_CODE","doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","doc://com.apple.gss/documentation/GSS/gss_display_status(_:_:_:_:_:_:)","doc://com.apple.gss/documentation/GSS/GSSCreateError(_:_:_:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_GSS_CODE"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"GSSCreateError","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateError(_:_:_:)/title"},{"value":[{"text":"GSSCreateError","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateError(_:_:_:)/fragments","op":"replace"},{"value":"gss_display_status","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_status(_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"text":"gss_display_status","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_status(_:_:_:_:_:_:)/fragments","op":"replace"},{"value":"gss_uint32","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_uint32/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_uint32"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_uint32/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"gss_uint32"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_uint32/navigatorTitle","op":"replace"},{"value":"gss_status_id_t","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_status_id_t/title","op":"replace"},{"value":[{"text":"gss_status_id_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_status_id_t/fragments","op":"replace"},{"value":[{"text":"gss_status_id_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_status_id_t/navigatorTitle","op":"replace"},{"value":"GSS_C_GSS_CODE","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_GSS_CODE/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_GSS_CODE"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_GSS_CODE/fragments","op":"replace"},{"value":"OM_uint32","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title","op":"replace"},{"value":[{"kind":"identifier","text":"OM_uint32"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OM_uint32"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle","op":"replace"},{"value":"GSS_S_COMPLETE","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title","op":"replace"},{"value":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments","op":"replace"},{"value":"GSS_C_MECH_CODE","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MECH_CODE/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_MECH_CODE"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MECH_CODE/fragments","op":"replace"},{"value":"OM_uint64","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint64/title","op":"replace"},{"value":[{"text":"OM_uint64","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint64/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OM_uint64"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint64/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}