{"seeAlsoSections":[{"generated":true,"anchor":"Credential-Masks-and-Macros","title":"Credential Masks and Macros","identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE","doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity","doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE","doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL","doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE","doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE","doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT","doc://com.apple.gss/documentation/GSS/GSS_C_BOTH","doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK","doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI","doc://com.apple.gss/documentation/GSS/gss_auth_identity_t","doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t","doc://com.apple.gss/documentation/GSS/gss_cred_id_t","doc://com.apple.gss/documentation/GSS/gss_cred_usage_t"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_CRED_PASSWORD","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD"},"sections":[],"variants":[{"paths":["/documentation/gss/gss_c_cred_password"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The value that indicates a password-based credential.","type":"text"}],"metadata":{"platforms":[{"deprecated":false,"beta":false,"introducedAt":"5.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"5.0","name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"10.14","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false}],"navigatorTitle":[{"text":"GSS_C_CRED_PASSWORD","kind":"identifier"}],"role":"symbol","externalID":"c:@macro@GSS_C_CRED_PASSWORD","symbolKind":"macro","title":"GSS_C_CRED_PASSWORD","modules":[{"name":"GSS"}],"fragments":[{"text":"GSS_C_CRED_PASSWORD","kind":"identifier"}],"roleHeading":"Macro"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"kind":"symbol","references":{"doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gss_const_cred_id_t"}],"url":"/documentation/gss/gss_const_cred_id_t","navigatorTitle":[{"kind":"identifier","text":"gss_const_cred_id_t"}],"title":"gss_const_cred_id_t","kind":"symbol","abstract":[{"type":"text","text":"A pointer to an immutable opaque type that you use to exchange a credential object with GSS-API functions."}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t","role":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD":{"fragments":[{"text":"GSS_C_CRED_PASSWORD","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The value that indicates a password-based credential."}],"title":"GSS_C_CRED_PASSWORD","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD","role":"symbol","url":"/documentation/gss/gss_c_cred_password"},"doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_ACCEPT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"abstract":[{"text":"The value that indicates a credential that can accept a security context.","type":"text"}],"title":"GSS_C_ACCEPT","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GSS_C_ACCEPT"}],"url":"/documentation/gss/gss_c_accept"},"doc://com.apple.gss/documentation/GSS/GSS_C_BOTH":{"title":"GSS_C_BOTH","kind":"symbol","url":"/documentation/gss/gss_c_both","navigatorTitle":[{"text":"GSS_C_BOTH","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_BOTH","abstract":[{"type":"text","text":"The value that indicates a credential that can both initiate and accept security contexts."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_BOTH","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.apple.gss/documentation/GSS/gss_cred_usage_t":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_cred_usage_t"}],"url":"/documentation/gss/gss_cred_usage_t","type":"topic","abstract":[{"text":"A credential usage value.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_cred_usage_t","navigatorTitle":[{"kind":"identifier","text":"gss_cred_usage_t"}],"kind":"symbol","title":"gss_cred_usage_t"},"doc://com.apple.gss/documentation/GSS/gss_cred_id_t":{"title":"gss_cred_id_t","abstract":[{"text":"A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.","type":"text"}],"navigatorTitle":[{"text":"gss_cred_id_t","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_cred_id_t","kind":"identifier"}],"type":"topic","kind":"symbol","url":"/documentation/gss/gss_cred_id_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_cred_id_t","role":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE":{"fragments":[{"text":"GSS_C_CRED_HEIMBASE","kind":"identifier"}],"url":"/documentation/gss/gss_c_cred_heimbase","title":"GSS_C_CRED_HEIMBASE","kind":"symbol","abstract":[{"type":"text","text":"The value that indicates a Heimdal-based credential."}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE","role":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE":{"abstract":[{"type":"text","text":"The value that indicates a certificate-based credential."}],"fragments":[{"kind":"identifier","text":"GSS_C_CRED_CERTIFICATE"}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE","url":"/documentation/gss/gss_c_cred_certificate","kind":"symbol","title":"GSS_C_CRED_CERTIFICATE","role":"symbol"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL":{"abstract":[{"type":"text","text":"The value that indicates an empty credential object."}],"url":"/documentation/gss/gss_c_no_credential","kind":"symbol","title":"GSS_C_NO_CREDENTIAL","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL","type":"topic","fragments":[{"kind":"identifier","text":"GSS_C_NO_CREDENTIAL"}]},"doc://com.apple.gss/documentation/GSS/gss_auth_identity_t":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_auth_identity_t"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A pointer to an opaque object used to manage authentication identities."}],"title":"gss_auth_identity_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_auth_identity_t","navigatorTitle":[{"kind":"identifier","text":"gss_auth_identity_t"}],"role":"symbol","url":"/documentation/gss/gss_auth_identity_t"},"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity":{"abstract":[{"type":"text","text":"The value that indicates a security identity-based credential."}],"fragments":[{"kind":"identifier","text":"GSS_C_CRED_SecIdentity"}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity","url":"/documentation/gss/gss_c_cred_secidentity","kind":"symbol","title":"GSS_C_CRED_SecIdentity","role":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_OPTION_MASK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The masking constant for options."}],"title":"GSS_C_OPTION_MASK","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK","navigatorTitle":[{"kind":"identifier","text":"GSS_C_OPTION_MASK"}],"role":"symbol","url":"/documentation/gss/gss_c_option_mask"},"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI":{"abstract":[{"type":"text","text":"The value that indicates no UI."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_CRED_NO_UI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI","url":"/documentation/gss/gss_c_cred_no_ui","kind":"symbol","title":"GSS_C_CRED_NO_UI","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GSS_C_CRED_NO_UI"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE":{"abstract":[{"type":"text","text":"The value that indicates a credential that can initiate a security context."}],"url":"/documentation/gss/gss_c_initiate","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_INITIATE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_INITIATE","role":"symbol","navigatorTitle":[{"text":"GSS_C_INITIATE","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE"},"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_INDEFINITE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"url":"/documentation/gss/gss_c_indefinite","type":"topic","abstract":[{"text":"The value that indicates the maximum permitted lifetime when used in a time request.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE","navigatorTitle":[{"kind":"identifier","text":"GSS_C_INDEFINITE"}],"kind":"symbol","title":"GSS_C_INDEFINITE"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/title","value":"gss_const_cred_id_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/fragments","value":[{"text":"gss_const_cred_id_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/navigatorTitle","value":[{"text":"gss_const_cred_id_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/title","value":"GSS_C_ACCEPT"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/fragments","value":[{"text":"GSS_C_ACCEPT","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/title","value":"GSS_C_BOTH"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/fragments","value":[{"kind":"identifier","text":"GSS_C_BOTH"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/title","value":"gss_cred_usage_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/fragments","value":[{"text":"gss_cred_usage_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/navigatorTitle","value":[{"text":"gss_cred_usage_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title","value":"gss_cred_id_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments","value":[{"kind":"identifier","text":"gss_cred_id_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle","value":[{"text":"gss_cred_id_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/title","value":"gss_auth_identity_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/fragments","value":[{"text":"gss_auth_identity_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/navigatorTitle","value":[{"text":"gss_auth_identity_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_OPTION_MASK/title","value":"GSS_C_OPTION_MASK"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_OPTION_MASK/fragments","value":[{"kind":"identifier","text":"GSS_C_OPTION_MASK"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CRED_NO_UI/title","value":"GSS_C_CRED_NO_UI"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CRED_NO_UI/fragments","value":[{"kind":"identifier","text":"GSS_C_CRED_NO_UI"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/title","value":"GSS_C_INITIATE"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/fragments","value":[{"text":"GSS_C_INITIATE","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/title","value":"GSS_C_INDEFINITE"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/fragments","value":[{"text":"GSS_C_INDEFINITE","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}