{
  "abstract": [
    {
      "text": "The structure defining a channel bindings descriptor that specifies the communications channel used to carry a context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@gss_channel_bindings_struct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_channel_bindings_struct"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_channel_bindings_struct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "gss_channel_bindings_struct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS": {
      "abstract": [
        {
          "text": "Indicates a ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CHANNEL_BINDINGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CHANNEL_BINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_channel_bindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT": {
      "abstract": [
        {
          "text": "A macro that indicates an empty context id object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CONTEXT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CONTEXT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_context"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct": {
      "abstract": [
        {
          "text": "The structure defining a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address": {
      "abstract": [
        {
          "text": "The network address of the acceptor, in the form specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptor_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptor_address"
        }
      ],
      "role": "symbol",
      "title": "acceptor_address",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/acceptor_address"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype": {
      "abstract": [
        {
          "text": "The type of address contained in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acceptor_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "acceptor_addrtype"
        }
      ],
      "role": "symbol",
      "title": "acceptor_addrtype",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/acceptor_addrtype"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data": {
      "abstract": [
        {
          "text": "Application specific data for use in communicating a channel binding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application_data"
        }
      ],
      "role": "symbol",
      "title": "application_data",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/application_data"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init()": {
      "abstract": [
        {
          "text": "Initialize a new, empty channel bindings structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/init()"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init(initiator_addrtype:initiator_address:acceptor_addrtype:acceptor_address:application_data:)": {
      "abstract": [
        {
          "text": "Initialize a new channel bindings structure with the given configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "initiator_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "initiator_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "acceptor_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "acceptor_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "application_data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init(initiator_addrtype:initiator_address:acceptor_addrtype:acceptor_address:application_data:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(initiator_addrtype:initiator_address:acceptor_addrtype:acceptor_address:application_data:)",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/init(initiator_addrtype:initiator_address:acceptor_addrtype:acceptor_address:application_data:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address": {
      "abstract": [
        {
          "text": "The network address of the acceptor, in the form specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiator_address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_desc",
          "text": "gss_buffer_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiator_address"
        }
      ],
      "role": "symbol",
      "title": "initiator_address",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/initiator_address"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype": {
      "abstract": [
        {
          "text": "The type of address contained in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initiator_addrtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initiator_addrtype"
        }
      ],
      "role": "symbol",
      "title": "initiator_addrtype",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_struct/initiator_addrtype"
    },
    "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t": {
      "abstract": [
        {
          "text": "A pointer to a channel bindings descriptor that specifies the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_channel_bindings_t"
        }
      ],
      "role": "symbol",
      "title": "gss_channel_bindings_t",
      "type": "topic",
      "url": "/documentation/gss/gss_channel_bindings_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable channel bindings descriptor that you use to specify the communications channel used to carry a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_channel_bindings_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_channel_bindings_t"
        }
      ],
      "role": "symbol",
      "title": "gss_const_channel_bindings_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_channel_bindings_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable opaque type that you use to communicate context pointers with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_const_ctx_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_const_ctx_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_ctx_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate context pointers with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_ctx_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_ctx_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_ctx_id_t"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Channel-Bindings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
        "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t"
      ],
      "title": "Channel Bindings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Initialization",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init()",
        "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/init(initiator_addrtype:initiator_address:acceptor_addrtype:acceptor_address:application_data:)"
      ],
      "title": "Initialization"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_channel_bindings_struct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_addrtype",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/initiator_address",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_addrtype",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/acceptor_address",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_struct/application_data"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Channel-Bindings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CHANNEL_BINDINGS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CONTEXT",
                "doc://com.apple.gss/documentation/GSS/gss_const_ctx_id_t",
                "doc://com.apple.gss/documentation/GSS/gss_ctx_id_t",
                "doc://com.apple.gss/documentation/GSS/gss_channel_bindings_t",
                "doc://com.apple.gss/documentation/GSS/gss_const_channel_bindings_t"
              ],
              "title": "Channel Bindings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_channel_bindings_struct"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/title",
          "value": "gss_channel_bindings_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/title",
          "value": "gss_const_channel_bindings_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_channel_bindings_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_channel_bindings_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/title",
          "value": "gss_ctx_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_ctx_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_address/title",
          "value": "acceptor_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptor_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1application_data/title",
          "value": "application_data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1application_data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "application_data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/title",
          "value": "gss_channel_bindings_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_channel_bindings_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_addrtype/title",
          "value": "initiator_addrtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_addrtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiator_addrtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_address/title",
          "value": "initiator_address"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1initiator_address/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initiator_address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_addrtype/title",
          "value": "acceptor_addrtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_channel_bindings_struct~1acceptor_addrtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "acceptor_addrtype"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_channel_bindings_struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_channel_bindings_struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
