{
  "abstract": [
    {
      "text": "Returns a flag that indicates if a given user is authorized.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@gss_userok",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_userok"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_name_t",
        "text": "gss_name_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_userok"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "gss_userok(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_userok"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_name_t",
              "text": "gss_name_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "user"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A name object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A C string that is first imported as a name object with name type ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and then authorized against the name object given by the first parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "user"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A non-zero integer when the user is authorized and zero otherwise.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME": {
      "abstract": [
        {
          "text": "A name that specifies a user on a local system in the username format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_USER_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_USER_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_user_name"
    },
    "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Changes the password associated with a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_aapl_change_password"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_aapl_change_password"
        }
      ],
      "role": "symbol",
      "title": "gss_aapl_change_password(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_aapl_change_password(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates if two names in internal name format refer to the same entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_compare_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_compare_name"
        }
      ],
      "role": "symbol",
      "title": "gss_compare_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_compare_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a name in the internal format to an octet string and the associated name type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_display_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_display_name"
        }
      ],
      "role": "symbol",
      "title": "gss_display_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_display_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an internal name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_duplicate_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_duplicate_name"
        }
      ],
      "role": "symbol",
      "title": "gss_duplicate_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_duplicate_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a list of mechanisms that support a particular name type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_mechs_for_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_mechs_for_name"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_mechs_for_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_mechs_for_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns information about a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_set_t",
          "text": "gss_buffer_set_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_name"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_name(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_name(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a list of name types that a given mechanism supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_names_for_mech"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_names_for_mech"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_names_for_mech(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_names_for_mech(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_name_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates if a given user is authorized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_userok"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_userok"
        }
      ],
      "role": "symbol",
      "title": "gss_userok(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_userok(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inquiries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)"
      ],
      "title": "Inquiries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_userok"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_userok"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inquiries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)"
              ],
              "title": "Inquiries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_userok"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_name_t",
                    "text": "gss_name_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "name"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:C",
                    "text": "char"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "user"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A name object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "name"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A C string that is first imported as a name object with name type ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " and then authorized against the name object given by the first parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "user"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A non-zero integer when the user is authorized and zero otherwise.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/title",
          "value": "gss_inquire_mechs_for_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_mechs_for_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/title",
          "value": "gss_inquire_names_for_mech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_names_for_mech"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/title",
          "value": "gss_userok"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_userok"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/title",
          "value": "gss_inquire_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/title",
          "value": "gss_aapl_change_password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_aapl_change_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/title",
          "value": "gss_display_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_display_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/title",
          "value": "gss_duplicate_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_duplicate_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/title",
          "value": "gss_compare_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_compare_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title",
          "value": "gss_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_userok(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_userok(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
