{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/gss/gss_c_af_implink"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gss/gss_c_af_implink"]}],"abstract":[{"type":"text","text":"ARPAnet IMP address type."}],"kind":"symbol","metadata":{"roleHeading":"Global Variable","role":"symbol","title":"GSS_C_AF_IMPLINK","symbolKind":"var","externalID":"c:@macro@GSS_C_AF_IMPLINK","modules":[{"name":"GSS"}],"platforms":[{"introducedAt":"5.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"5.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"name":"macOS","introducedAt":"10.14","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_IMPLINK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_IMPLINK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_IMPLINK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_IMPLINK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"],"title":"Address Families","anchor":"Address-Families"}],"references":{"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","abstract":[{"type":"text","text":"The nbs address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_NBS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_NBS","role":"symbol","url":"/documentation/gss/gss_c_af_nbs","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_NBS"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC":{"url":"/documentation/gss/gss_c_af_bsc","navigatorTitle":[{"text":"GSS_C_AF_BSC","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","role":"symbol","abstract":[{"text":"The BISYNC 2780/3780 address type.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_BSC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_BSC","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_IMPLINK":{"type":"topic","kind":"symbol","role":"symbol","url":"/documentation/gss/gss_c_af_implink","abstract":[{"type":"text","text":"ARPAnet IMP address type."}],"title":"GSS_C_AF_IMPLINK","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_IMPLINK"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GSS_C_AF_IMPLINK","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_IMPLINK"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS":{"type":"topic","title":"GSS_C_AF_NS","role":"symbol","abstract":[{"text":"The Xerox NS address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_NS","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_NS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_ns","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET","url":"/documentation/gss/gss_c_af_inet","navigatorTitle":[{"text":"GSS_C_AF_INET","kind":"identifier"}],"abstract":[{"type":"text","text":"The Internet (for example, IP) address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","abstract":[{"text":"The ECMA address type.","type":"text"}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_ECMA","url":"/documentation/gss/gss_c_af_ecma","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"GSS_C_AF_ECMA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_ECMA","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_INET6","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","title":"GSS_C_AF_INET6","url":"/documentation/gss/gss_c_af_inet6","navigatorTitle":[{"text":"GSS_C_AF_INET6","kind":"identifier"}],"abstract":[{"type":"text","text":"The IPv6 address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP":{"abstract":[{"text":"The PUP protocols (for example, BSP) address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_pup","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_PUP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_PUP","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_PUP","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI":{"type":"topic","title":"GSS_C_AF_OSI","role":"symbol","abstract":[{"text":"The OSI TP4 address type.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_AF_OSI","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_OSI","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_c_af_osi","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS":{"abstract":[{"text":"The distributed system services address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_dss","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_DSS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_DSS","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_DSS","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25":{"url":"/documentation/gss/gss_c_af_x25","navigatorTitle":[{"text":"GSS_C_AF_X25","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","role":"symbol","abstract":[{"type":"text","text":"The X.25 address type."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_X25","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_X25","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","abstract":[{"type":"text","text":"The MIT CHAOS protocol address type."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_CHAOS","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_CHAOS","role":"symbol","url":"/documentation/gss/gss_c_af_chaos","navigatorTitle":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_CCITT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"type":"topic","title":"GSS_C_AF_CCITT","url":"/documentation/gss/gss_c_af_ccitt","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_CCITT"}],"abstract":[{"type":"text","text":"The CCITT protocols address type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","abstract":[{"type":"text","text":"The LAT address type."}],"role":"symbol","kind":"symbol","title":"GSS_C_AF_LAT","url":"/documentation/gss/gss_c_af_lat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_LAT","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_AF_LAT","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","abstract":[{"type":"text","text":"The direct data link interface address type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_DLI"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_AF_DLI","role":"symbol","url":"/documentation/gss/gss_c_af_dli","navigatorTitle":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA":{"abstract":[{"text":"The IBM SNA address type.","type":"text"}],"url":"/documentation/gss/gss_c_af_sna","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_AF_SNA","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"GSS_C_AF_SNA","role":"symbol","navigatorTitle":[{"text":"GSS_C_AF_SNA","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"5.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"5.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.0"},{"deprecated":false,"name":"macOS","unavailable":false,"beta":false,"introducedAt":"10.14"},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Macro","op":"replace"},{"path":"/metadata/title","value":"GSS_C_AF_IMPLINK","op":"replace"},{"path":"/metadata/symbolKind","value":"macro","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"GSS_C_AF_IMPLINK","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Address-Families","title":"Address Families","identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_AF_NS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_BSC","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DLI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_DSS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_LAT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_NBS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_OSI","doc://com.apple.gss/documentation/GSS/GSS_C_AF_PUP","doc://com.apple.gss/documentation/GSS/GSS_C_AF_SNA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_X25","doc://com.apple.gss/documentation/GSS/GSS_C_AF_ECMA","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CCITT","doc://com.apple.gss/documentation/GSS/GSS_C_AF_CHAOS","doc://com.apple.gss/documentation/GSS/GSS_C_AF_INET6"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_AF_IMPLINK"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/title","value":"GSS_C_AF_NBS"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NBS/fragments","value":[{"text":"GSS_C_AF_NBS","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/title","value":"GSS_C_AF_BSC"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_BSC/fragments","value":[{"text":"GSS_C_AF_BSC","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_IMPLINK/title","value":"GSS_C_AF_IMPLINK"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_IMPLINK/fragments","value":[{"kind":"identifier","text":"GSS_C_AF_IMPLINK"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/title","value":"GSS_C_AF_NS"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_NS/fragments","value":[{"kind":"identifier","text":"GSS_C_AF_NS"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/title","value":"GSS_C_AF_INET"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET/fragments","value":[{"text":"GSS_C_AF_INET","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/title","value":"GSS_C_AF_ECMA"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_ECMA/fragments","value":[{"kind":"identifier","text":"GSS_C_AF_ECMA"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/title","value":"GSS_C_AF_INET6"},{"value":[{"text":"GSS_C_AF_INET6","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_INET6/fragments","op":"replace"},{"value":"GSS_C_AF_PUP","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_AF_PUP"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_PUP/fragments","op":"replace"},{"value":"GSS_C_AF_OSI","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_AF_OSI"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_OSI/fragments","op":"replace"},{"value":"GSS_C_AF_DSS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_AF_DSS"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DSS/fragments","op":"replace"},{"value":"GSS_C_AF_X25","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_AF_X25"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_X25/fragments","op":"replace"},{"value":"GSS_C_AF_CHAOS","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/title","op":"replace"},{"value":[{"text":"GSS_C_AF_CHAOS","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CHAOS/fragments","op":"replace"},{"value":"GSS_C_AF_CCITT","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/title","op":"replace"},{"value":[{"text":"GSS_C_AF_CCITT","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_CCITT/fragments","op":"replace"},{"value":"GSS_C_AF_LAT","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/title","op":"replace"},{"value":[{"text":"GSS_C_AF_LAT","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_LAT/fragments","op":"replace"},{"value":"GSS_C_AF_DLI","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_AF_DLI"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_DLI/fragments","op":"replace"},{"value":"GSS_C_AF_SNA","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/title","op":"replace"},{"value":[{"text":"GSS_C_AF_SNA","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_AF_SNA/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}