{"kind":"symbol","abstract":[{"type":"text","text":"No valid security context."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT"},"seeAlsoSections":[{"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS","doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED","doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN","doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL","doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED","doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED","doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP","doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED"],"anchor":"Routine-Errors","generated":true,"title":"Routine Errors"}],"variants":[{"paths":["/documentation/gss/gss_s_no_context"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/gss/gss_s_no_context"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"metadata":{"symbolKind":"var","roleHeading":"Global Variable","role":"symbol","platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"5.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"5.0"},{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.14","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"introducedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS","unavailable":false}],"externalID":"c:@macro@GSS_S_NO_CONTEXT","title":"GSS_S_NO_CONTEXT","modules":[{"name":"GSS"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_S_NO_CONTEXT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_S_NO_CONTEXT"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_NO_CONTEXT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_NO_CONTEXT","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_s_no_context","type":"topic","abstract":[{"type":"text","text":"No valid security context."}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT","navigatorTitle":[{"text":"GSS_S_NO_CONTEXT","kind":"identifier"}],"kind":"symbol","title":"GSS_S_NO_CONTEXT"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG":{"url":"/documentation/gss/gss_s_bad_sig","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_SIG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GSS_S_BAD_SIG","kind":"identifier"}],"type":"topic","abstract":[{"text":"Failed token integrity check.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG","role":"symbol","title":"GSS_S_BAD_SIG","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE","abstract":[{"text":"An unspecified error.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_FAILURE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"title":"GSS_S_FAILURE","role":"symbol","url":"/documentation/gss/gss_s_failure","navigatorTitle":[{"text":"GSS_S_FAILURE","kind":"identifier"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC":{"kind":"symbol","url":"/documentation/gss/gss_s_bad_mic","type":"topic","navigatorTitle":[{"text":"GSS_S_BAD_MIC","kind":"identifier"}],"title":"GSS_S_BAD_MIC","role":"symbol","abstract":[{"text":"Failed token integrity check.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_MIC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED":{"title":"GSS_S_CREDENTIALS_EXPIRED","abstract":[{"text":"Expired credential.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_S_CREDENTIALS_EXPIRED"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_S_CREDENTIALS_EXPIRED"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_credentials_expired","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED","role":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED":{"url":"/documentation/gss/gss_s_context_expired","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_CONTEXT_EXPIRED","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"GSS_S_CONTEXT_EXPIRED","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Expired context."}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED","role":"symbol","title":"GSS_S_CONTEXT_EXPIRED","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP":{"navigatorTitle":[{"text":"GSS_S_BAD_QOP","kind":"identifier"}],"abstract":[{"text":"Unsupported QOP value.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_QOP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"role":"symbol","title":"GSS_S_BAD_QOP","type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_bad_qop"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH":{"url":"/documentation/gss/gss_s_bad_mech","navigatorTitle":[{"text":"GSS_S_BAD_MECH","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH","role":"symbol","abstract":[{"text":"Unsupported mechanism.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GSS_S_BAD_MECH"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"title":"GSS_S_BAD_MECH","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS":{"url":"/documentation/gss/gss_s_bad_bindings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_S_BAD_BINDINGS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_S_BAD_BINDINGS"}],"type":"topic","abstract":[{"type":"text","text":"Channel bindings mismatch."}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS","role":"symbol","title":"GSS_S_BAD_BINDINGS","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_S_UNAUTHORIZED"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_S_UNAUTHORIZED"}],"url":"/documentation/gss/gss_s_unauthorized","abstract":[{"type":"text","text":"Unauthorized operation."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED","title":"GSS_S_UNAUTHORIZED"},"doc://com.externally.resolved.symbol/s:Su":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Su","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UInt","kind":"identifier"}],"type":"topic","title":"UInt","url":"/documentation/Swift/UInt","abstract":[{"type":"text","text":"An unsigned integer value type."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS":{"url":"/documentation/gss/gss_s_bad_status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_STATUS","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GSS_S_BAD_STATUS","kind":"identifier"}],"type":"topic","abstract":[{"text":"Invalid status selector.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS","role":"symbol","title":"GSS_S_BAD_STATUS","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL":{"navigatorTitle":[{"text":"GSS_S_DEFECTIVE_CREDENTIAL","kind":"identifier"}],"abstract":[{"type":"text","text":"Defective credential."}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_DEFECTIVE_CREDENTIAL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","title":"GSS_S_DEFECTIVE_CREDENTIAL","type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_defective_credential"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE","abstract":[{"text":"Unsupported name type.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_NAMETYPE","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"title":"GSS_S_BAD_NAMETYPE","role":"symbol","url":"/documentation/gss/gss_s_bad_nametype","navigatorTitle":[{"text":"GSS_S_BAD_NAMETYPE","kind":"identifier"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_DEFECTIVE_TOKEN","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_s_defective_token","type":"topic","abstract":[{"text":"Defective token.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN","navigatorTitle":[{"text":"GSS_S_DEFECTIVE_TOKEN","kind":"identifier"}],"kind":"symbol","title":"GSS_S_DEFECTIVE_TOKEN"},"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME":{"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_BAD_NAME","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"type":"topic","title":"GSS_S_BAD_NAME","url":"/documentation/gss/gss_s_bad_name","navigatorTitle":[{"text":"GSS_S_BAD_NAME","kind":"identifier"}],"abstract":[{"type":"text","text":"Invalid name."}],"kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED":{"kind":"symbol","url":"/documentation/gss/gss_s_no_cred","type":"topic","navigatorTitle":[{"text":"GSS_S_NO_CRED","kind":"identifier"}],"title":"GSS_S_NO_CRED","role":"symbol","abstract":[{"text":"No valid credentials.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_NO_CRED","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"5.0"},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"5.0"},{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.14","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Macro","path":"/metadata/roleHeading"},{"op":"replace","value":"GSS_S_NO_CONTEXT","path":"/metadata/title"},{"op":"replace","value":"macro","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"GSS_S_NO_CONTEXT"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS","doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED","doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN","doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL","doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED","doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED","doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE","doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP","doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED"],"title":"Routine Errors","anchor":"Routine-Errors","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_S_NO_CONTEXT"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CONTEXT/title","value":"GSS_S_NO_CONTEXT","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CONTEXT/fragments","value":[{"kind":"identifier","text":"GSS_S_NO_CONTEXT"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_SIG/title","value":"GSS_S_BAD_SIG","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_SIG/fragments","value":[{"text":"GSS_S_BAD_SIG","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_FAILURE/title","value":"GSS_S_FAILURE","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_FAILURE/fragments","value":[{"text":"GSS_S_FAILURE","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MIC/title","value":"GSS_S_BAD_MIC","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MIC/fragments","value":[{"text":"GSS_S_BAD_MIC","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CREDENTIALS_EXPIRED/title","value":"GSS_S_CREDENTIALS_EXPIRED","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CREDENTIALS_EXPIRED/fragments","value":[{"text":"GSS_S_CREDENTIALS_EXPIRED","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CONTEXT_EXPIRED/title","value":"GSS_S_CONTEXT_EXPIRED","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CONTEXT_EXPIRED/fragments","value":[{"text":"GSS_S_CONTEXT_EXPIRED","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_QOP/title","value":"GSS_S_BAD_QOP","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_QOP/fragments","value":[{"kind":"identifier","text":"GSS_S_BAD_QOP"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MECH/title","value":"GSS_S_BAD_MECH","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MECH/fragments","value":[{"text":"GSS_S_BAD_MECH","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_BINDINGS/title","value":"GSS_S_BAD_BINDINGS","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_BINDINGS/fragments","value":[{"text":"GSS_S_BAD_BINDINGS","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_UNAUTHORIZED/title","value":"GSS_S_UNAUTHORIZED","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_UNAUTHORIZED/fragments","value":[{"kind":"identifier","text":"GSS_S_UNAUTHORIZED"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_STATUS/title","value":"GSS_S_BAD_STATUS","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_STATUS/fragments","value":[{"kind":"identifier","text":"GSS_S_BAD_STATUS"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_CREDENTIAL/title","value":"GSS_S_DEFECTIVE_CREDENTIAL","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_CREDENTIAL/fragments","value":[{"kind":"identifier","text":"GSS_S_DEFECTIVE_CREDENTIAL"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAMETYPE/title","value":"GSS_S_BAD_NAMETYPE","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAMETYPE/fragments","value":[{"text":"GSS_S_BAD_NAMETYPE","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_TOKEN/title","value":"GSS_S_DEFECTIVE_TOKEN","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_TOKEN/fragments","value":[{"kind":"identifier","text":"GSS_S_DEFECTIVE_TOKEN"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAME/title","value":"GSS_S_BAD_NAME","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAME/fragments","value":[{"text":"GSS_S_BAD_NAME","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CRED/title","value":"GSS_S_NO_CRED","op":"replace"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CRED/fragments","value":[{"text":"GSS_S_NO_CRED","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}