{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Returns information about a security context.","type":"text"}],"identifier":{"url":"doc://com.apple.gss/documentation/GSS/gss_inquire_context(_:_:_:_:_:_:_:_:_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/gss/gss_inquire_context(_:_:_:_:_:_:_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gss/gss_inquire_context(_:_:_:_:_:_:_:_:_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_inquire_context"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"minor_status"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context_handle"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_ctx_id_t","preciseIdentifier":"c:@T@gss_ctx_id_t","kind":"typeIdentifier","text":"gss_ctx_id_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"src_name"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"targ_name"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lifetime_rec"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mech_type"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_OID","preciseIdentifier":"c:@T@gss_OID","kind":"typeIdentifier","text":"gss_OID"},{"kind":"text","text":"?>?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ctx_flags"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locally_initiated"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"xopen"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":">?) -> "},{"identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier","text":"OM_uint32"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"minor_status","content":[{"type":"paragraph","inlineContent":[{"text":"A pointer to the secondary status result that provides additional information in case of failure.","type":"text"}]}]},{"name":"context_handle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context to obtain information about."}]}]},{"name":"src_name","content":[{"inlineContent":[{"text":"A pointer the function uses to return the name of the initiator. Free the name object’s memory with a call to ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","isActive":true,"type":"reference"},{"text":" when you are done with it. Specify ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore this output.","type":"text"}],"type":"paragraph"}]},{"name":"targ_name","content":[{"type":"paragraph","inlineContent":[{"text":"A pointer the function uses to return the name of the acceptor. Free the name object’s memory with a call to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"},{"text":" when you are done with it. Specify ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore this output.","type":"text"}]}]},{"name":"lifetime_rec","content":[{"type":"paragraph","inlineContent":[{"text":"A pointer the function uses to return the number of seconds before the context expires, or zero if it has already expired. If the context does not support expiration, it returns ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE"},{"text":". Specify ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore this output.","type":"text"}]}]},{"name":"mech_type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer the function uses to return the mechanism providing the context. Do not release the OID object, because it is held in static memory. Specify "},{"code":"NULL","type":"codeVoice"},{"type":"text","text":" to ignore this output."}]}]},{"name":"ctx_flags","content":[{"inlineContent":[{"type":"text","text":"A pointer the function uses to return the flags associated with the context. See "},{"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/context-services","isActive":true},{"type":"text","text":" for a description of available flags. Specify NULL to ignore this output."}],"type":"paragraph"}]},{"name":"locally_initiated","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer the function uses to return an indicator of the context’s point of origin. The value is zero when the function is called by context’s acceptor and non-zero otherwise. Specify NULL to ignore this output."}]}]},{"name":"xopen","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer the function uses to return an indicator of the context’s current state. The value is non-zero when the context if fully established and zero otherwise. Specify NULL to ignore this output."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A status code set to "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE"},{"type":"text","text":" on success. See "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/function-status"},{"type":"text","text":" for a description of other status outputs."}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"The context must exist but need not be fully established for the inquiry to succeed."}],"type":"paragraph"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.gss/documentation/GSS/gss_context_time(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_sec_context_by_oid(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_wrap_size_limit(_:_:_:_:_:_:)"],"anchor":"Inquiry-and-Limits","generated":true,"title":"Inquiry and Limits"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"sections":[],"metadata":{"modules":[{"name":"GSS"}],"role":"symbol","navigatorTitle":[{"text":"gss_inquire_context","kind":"identifier"}],"roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_inquire_context","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_ctx_id_t","text":"gss_ctx_id_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"gss_OID","preciseIdentifier":"c:@T@gss_OID","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"}],"symbolKind":"func","title":"gss_inquire_context(_:_:_:_:_:_:_:_:_:)","externalID":"c:@F@gss_inquire_context","platforms":[{"beta":false,"unavailable":false,"introducedAt":"5.0","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"5.0","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"10.7","name":"macOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}]},"references":{"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_INDEFINITE"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"url":"/documentation/gss/gss_c_indefinite","type":"topic","abstract":[{"text":"The value that indicates the maximum permitted lifetime when used in a time request.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE","navigatorTitle":[{"kind":"identifier","text":"GSS_C_INDEFINITE"}],"kind":"symbol","title":"GSS_C_INDEFINITE"},"doc://com.apple.gss/documentation/GSS/gss_context_time(_:_:_:)":{"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_context_time(_:_:_:)","navigatorTitle":[{"text":"gss_context_time","kind":"identifier"}],"title":"gss_context_time(_:_:_:)","abstract":[{"text":"Returns the amount of time remaining before a context expires.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_context_time","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"gss_ctx_id_t","preciseIdentifier":"c:@T@gss_ctx_id_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_context_time(_:_:_:)","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/function-status":{"title":"Function Status","abstract":[{"text":"Evaluate return values that most GSS-API functions use to indicate the outcome of an operation.","type":"text"}],"type":"topic","kind":"article","url":"/documentation/gss/function-status","identifier":"doc://com.apple.gss/documentation/GSS/function-status","role":"collectionGroup"},"doc://com.apple.gss/documentation/GSS/gss_wrap_size_limit(_:_:_:_:_:_:)":{"kind":"symbol","url":"/documentation/gss/gss_wrap_size_limit(_:_:_:_:_:_:)","type":"topic","navigatorTitle":[{"text":"gss_wrap_size_limit","kind":"identifier"}],"title":"gss_wrap_size_limit(_:_:_:_:_:_:)","role":"symbol","abstract":[{"type":"text","text":"Returns the largest allowable wrap size for a given set of constraints."}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_wrap_size_limit(_:_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_wrap_size_limit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"gss_ctx_id_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_ctx_id_t"},{"text":", ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"gss_qop_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_qop_t"},{"text":", ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}]},"doc://com.apple.gss/documentation/GSS/gss_ctx_id_t":{"type":"topic","title":"gss_ctx_id_t","role":"symbol","abstract":[{"type":"text","text":"A pointer to an opaque type that you use to communicate context pointers with GSS-API functions."}],"navigatorTitle":[{"text":"gss_ctx_id_t","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"gss_ctx_id_t","kind":"identifier"}],"url":"/documentation/gss/gss_ctx_id_t","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_ctx_id_t"},"doc://com.apple.gss/documentation/GSS/gss_name_t":{"kind":"symbol","url":"/documentation/gss/gss_name_t","type":"topic","navigatorTitle":[{"text":"gss_name_t","kind":"identifier"}],"title":"gss_name_t","role":"symbol","abstract":[{"text":"A pointer to an opaque type that you use to communicate name objects with GSS-API functions.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"gss_name_t","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE":{"navigatorTitle":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"abstract":[{"text":"The operation completed without error.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_COMPLETE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","title":"GSS_S_COMPLETE","type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_complete"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.externally.resolved.symbol/s:Sp":{"title":"UnsafeMutablePointer","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"kind":"symbol","url":"/documentation/Swift/UnsafeMutablePointer","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sp","abstract":[{"type":"text","text":"A pointer for accessing and manipulating data of a specific type."}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/OM_uint32":{"url":"/documentation/gss/om_uint32","navigatorTitle":[{"kind":"identifier","text":"OM_uint32"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OM_uint32"}],"abstract":[{"type":"text","text":"A 32-bit unsigned integer."}],"title":"OM_uint32","type":"topic"},"doc://com.apple.gss/documentation/GSS/gss_inquire_sec_context_by_oid(_:_:_:_:)":{"role":"symbol","navigatorTitle":[{"text":"gss_inquire_sec_context_by_oid","kind":"identifier"}],"title":"gss_inquire_sec_context_by_oid(_:_:_:_:)","kind":"symbol","abstract":[{"text":"Returns information about a particular part of a context.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_inquire_sec_context_by_oid","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"gss_ctx_id_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_ctx_id_t"},{"text":", ","kind":"text"},{"text":"gss_OID","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_buffer_set_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_buffer_set_t"},{"text":">?) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_inquire_sec_context_by_oid(_:_:_:_:)","url":"/documentation/gss/gss_inquire_sec_context_by_oid(_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_inquire_context(_:_:_:_:_:_:_:_:_:)":{"url":"/documentation/gss/gss_inquire_context(_:_:_:_:_:_:_:_:_:)","abstract":[{"text":"Returns information about a security context.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_inquire_context"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_ctx_id_t","text":"gss_ctx_id_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":"?>?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":"?>?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID","text":"gss_OID"},{"kind":"text","text":"?>?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":">?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_inquire_context(_:_:_:_:_:_:_:_:_:)","kind":"symbol","title":"gss_inquire_context(_:_:_:_:_:_:_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"gss_inquire_context"}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/context-services":{"identifier":"doc://com.apple.gss/documentation/GSS/context-services","title":"Context Services","role":"collectionGroup","url":"/documentation/gss/context-services","type":"topic","abstract":[{"text":"Use context services to manage secure operations between endpoints.","type":"text"}],"kind":"article"},"doc://com.apple.gss/documentation/GSS/gss_OID":{"abstract":[{"type":"text","text":"A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions."}],"url":"/documentation/gss/gss_oid","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_OID","kind":"identifier"}],"title":"gss_OID","role":"symbol","navigatorTitle":[{"text":"gss_OID","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_OID"},"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)":{"navigatorTitle":[{"text":"gss_release_name","kind":"identifier"}],"title":"gss_release_name(_:_:)","abstract":[{"type":"text","text":"Frees the resources associated with a name object."}],"url":"/documentation/gss/gss_release_name(_:_:)","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_release_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","unavailable":false,"introducedAt":"5.0","deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"introducedAt":"5.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false},{"name":"macOS","unavailable":false,"introducedAt":"10.7","deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"gss_inquire_context"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"gss_inquire_context"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","value":[{"anchor":"Inquiry-and-Limits","generated":true,"title":"Inquiry and Limits","identifiers":["doc://com.apple.gss/documentation/GSS/gss_context_time(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_sec_context_by_oid(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_wrap_size_limit(_:_:_:_:_:_:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"],"tokens":[{"preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_inquire_context"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"minor_status"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_ctx_id_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_ctx_id_t","kind":"typeIdentifier","text":"gss_ctx_id_t"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context_handle"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"src_name"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"targ_name"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"lifetime_rec"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_OID","identifier":"doc://com.apple.gss/documentation/GSS/gss_OID","kind":"typeIdentifier","text":"gss_OID"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"mech_type"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","text":"OM_uint32"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"ctx_flags"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"locally_initiated"},{"kind":"text","text":", "},{"preciseIdentifier":"c:I","kind":"typeIdentifier","text":"int"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"xopen"},{"kind":"text","text":");"}]}]},"op":"replace"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer to the secondary status result that provides additional information in case of failure."}]}],"name":"minor_status"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context to obtain information about."}]}],"name":"context_handle"},{"content":[{"inlineContent":[{"type":"text","text":"A pointer the function uses to return the name of the initiator. Free the name object’s memory with a call to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"},{"type":"text","text":" when you are done with it. Specify "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" to ignore this output."}],"type":"paragraph"}],"name":"src_name"},{"content":[{"inlineContent":[{"text":"A pointer the function uses to return the name of the acceptor. Free the name object’s memory with a call to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","type":"reference"},{"text":" when you are done with it. Specify ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore this output.","type":"text"}],"type":"paragraph"}],"name":"targ_name"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer the function uses to return the number of seconds before the context expires, or zero if it has already expired. If the context does not support expiration, it returns "},{"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE","isActive":true},{"type":"text","text":". Specify "},{"code":"NULL","type":"codeVoice"},{"type":"text","text":" to ignore this output."}]}],"name":"lifetime_rec"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A pointer the function uses to return the mechanism providing the context. Do not release the OID object, because it is held in static memory. Specify ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore this output.","type":"text"}]}],"name":"mech_type"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer the function uses to return the flags associated with the context. See "},{"identifier":"doc://com.apple.gss/documentation/GSS/context-services","type":"reference","isActive":true},{"type":"text","text":" for a description of available flags. Specify NULL to ignore this output."}]}],"name":"ctx_flags"},{"content":[{"inlineContent":[{"type":"text","text":"A pointer the function uses to return an indicator of the context’s point of origin. The value is zero when the function is called by context’s acceptor and non-zero otherwise. Specify NULL to ignore this output."}],"type":"paragraph"}],"name":"locally_initiated"},{"content":[{"inlineContent":[{"text":"A pointer the function uses to return an indicator of the context’s current state. The value is non-zero when the context if fully established and zero otherwise. Specify NULL to ignore this output.","type":"text"}],"type":"paragraph"}],"name":"xopen"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A status code set to ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","isActive":true,"type":"reference"},{"text":" on success. See ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/function-status","isActive":true,"type":"reference"},{"text":" for a description of other status outputs.","type":"text"}]}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"value":"GSS_C_INDEFINITE","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/title","op":"replace"},{"value":[{"text":"GSS_C_INDEFINITE","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/fragments","op":"replace"},{"value":"gss_context_time","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_context_time(_:_:_:)/title","op":"replace"},{"value":[{"text":"gss_context_time","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_context_time(_:_:_:)/fragments","op":"replace"},{"value":"gss_wrap_size_limit","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_wrap_size_limit(_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_wrap_size_limit"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_wrap_size_limit(_:_:_:_:_:_:)/fragments","op":"replace"},{"value":"gss_ctx_id_t","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/title","op":"replace"},{"value":[{"text":"gss_ctx_id_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/fragments","op":"replace"},{"value":[{"text":"gss_ctx_id_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_ctx_id_t/navigatorTitle","op":"replace"},{"value":"gss_name_t","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_name_t"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments","op":"replace"},{"value":[{"text":"gss_name_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle","op":"replace"},{"value":"GSS_S_COMPLETE","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title","op":"replace"},{"value":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments","op":"replace"},{"value":"OM_uint32","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title","op":"replace"},{"value":[{"text":"OM_uint32","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OM_uint32"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle","op":"replace"},{"value":"gss_inquire_sec_context_by_oid","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_sec_context_by_oid(_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_inquire_sec_context_by_oid"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_sec_context_by_oid(_:_:_:_:)/fragments","op":"replace"},{"value":"gss_inquire_context","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_context(_:_:_:_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_inquire_context"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_context(_:_:_:_:_:_:_:_:_:)/fragments","op":"replace"},{"value":"gss_OID","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title","op":"replace"},{"value":[{"text":"gss_OID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"gss_OID"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle","op":"replace"},{"value":"gss_release_name","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_release_name"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}