{
  "abstract": [
    {
      "text": "Iterates over all credentials with a user context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_iter_creds_f(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@gss_iter_creds_f",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_iter_creds_f"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_const_OID",
        "text": "gss_const_OID"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?, ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_OID",
        "text": "gss_OID"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_iter_creds_f"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "gss_iter_creds_f(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_iter_creds_f"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "min_stat"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mech"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_const_OID",
              "text": "gss_const_OID"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "userctx"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "useriter"
            },
            {
              "kind": "text",
              "text": ": ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_OID",
              "text": "gss_OID"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "No flags are currently defined. Pass 0 for this parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The mechanism type of credentials to iterate over. Pass in ",
                  "type": "text"
                },
                {
                  "code": "GSS_C_NO_OID_SET",
                  "type": "codeVoice"
                },
                {
                  "text": " to iterate over all credentials.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mech"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A user context that you use to keep track of callbacks.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "userctx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that is called once for each credential. The block receives the user context that you specified with the ",
                  "type": "text"
                },
                {
                  "code": "userctx",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter, the credential’s mechanism, and a copy of the credential as input on each iteration. Free the copy’s memory with a call to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " when you are done with it. The block is called one final time with a ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " credential upon reaching the end of the list.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "useriter"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A status code set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on success. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a description of other status outputs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_iter_creds(_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function if you don’t need the user context parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE": {
      "abstract": [
        {
          "text": "The operation completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_COMPLETE",
      "type": "topic",
      "url": "/documentation/gss/gss_s_complete"
    },
    "doc://com.apple.gss/documentation/GSS/OM_uint32": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "role": "symbol",
      "title": "OM_uint32",
      "type": "topic",
      "url": "/documentation/gss/om_uint32"
    },
    "doc://com.apple.gss/documentation/GSS/function-status": {
      "abstract": [
        {
          "text": "Evaluate return values that most GSS-API functions use to indicate the outcome of an operation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Function Status",
      "type": "topic",
      "url": "/documentation/gss/function-status"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID": {
      "abstract": [
        {
          "text": "A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID": {
      "abstract": [
        {
          "text": "A pointer to an immutable OID descriptor exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iter_creds(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Iterates over all credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_iter_creds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iter_creds(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_iter_creds"
        }
      ],
      "role": "symbol",
      "title": "gss_iter_creds(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_iter_creds(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iter_creds_f(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Iterates over all credentials with a user context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_iter_creds_f"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iter_creds_f(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_iter_creds_f"
        }
      ],
      "role": "symbol",
      "title": "gss_iter_creds_f(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_iter_creds_f(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory of a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_release_cred(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_cred(_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Iteration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_iter_creds(_:_:_:_:)"
      ],
      "title": "Iteration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_iter_creds_f"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iter_creds_f"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Iteration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_iter_creds(_:_:_:_:)"
              ],
              "title": "Iteration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_iter_creds_f"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "min_stat"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_const_OID",
                    "text": "gss_const_OID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mech"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "userctx"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:*Fv(#*v#*$@S@gss_OID_desc_struct#*$@S@gss_cred_id_t_desc_struct)",
                    "text": "void (*)(void *, struct gss_OID_desc_struct *, struct gss_cred_id_t_desc_struct *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "useriter"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "No flags are currently defined. Pass 0 for this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The mechanism type of credentials to iterate over. Pass in ",
                        "type": "text"
                      },
                      {
                        "code": "GSS_C_NO_OID_SET",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to iterate over all credentials.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mech"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A user context that you use to keep track of callbacks.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "userctx"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block that is called once for each credential. The block receives the user context that you specified with the ",
                        "type": "text"
                      },
                      {
                        "code": "userctx",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter, the credential’s mechanism, and a copy of the credential as input on each iteration. Free the copy’s memory with a call to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " when you are done with it. The block is called one final time with a ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " credential upon reaching the end of the list.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "useriter"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A status code set to ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " on success. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/function-status",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for a description of other status outputs.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iter_creds_f(_:_:_:_:_:)/title",
          "value": "gss_iter_creds_f"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iter_creds_f(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iter_creds_f"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/title",
          "value": "gss_const_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title",
          "value": "OM_uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title",
          "value": "gss_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/title",
          "value": "gss_release_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title",
          "value": "GSS_S_COMPLETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_COMPLETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iter_creds(_:_:_:_:)/title",
          "value": "gss_iter_creds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_iter_creds(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_iter_creds"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_iter_creds_f(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_iter_creds_f(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
