{
  "abstract": [
    {
      "text": "Acquires a new credential using a password or certificate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@gss_aapl_initial_cred",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_aapl_initial_cred"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_name_t",
        "text": "gss_name_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_const_OID",
        "text": "gss_const_OID"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": "?>, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s9UnmanagedV",
        "text": "Unmanaged"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFErrorRef",
        "text": "CFError"
      },
      {
        "kind": "text",
        "text": ">?>?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_aapl_initial_cred"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "gss_aapl_initial_cred(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_aapl_initial_cred"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "desired_name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_name_t",
              "text": "gss_name_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "desired_mech"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_const_OID",
              "text": "gss_const_OID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "attributes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "output_cred_handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": "?>, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s9UnmanagedV",
              "text": "Unmanaged"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFErrorRef",
              "text": "CFError"
            },
            {
              "kind": "text",
              "text": ">?>?) -> "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name to use to acquire the credential. Import the name using ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Ensure that the mechanism specified by the ",
                  "type": "text"
                },
                {
                  "code": "desired_mech",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter supports the name type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "desired_name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The mechanism to use to acquire the credential, for example ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to get a complete list of supported mechanisms.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "desired_mech"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that includes either the key ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to specify a password or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to name a certificate for use in acquiring the credential. It may also contain any of the other keys listed in Initial Credential Keys in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/credential-management",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to optionally condition the operation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attributes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A credential pointer that the function sets to point at the new credential on success, or sets to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " on failure. Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gss/documentation/GSS/gss_destroy_cred(_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to release the credential’s memory when you are done with it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "output_cred_handle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An error pointer that the function sets to point at a new error object if the function call fails. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to ignore this error. When an error does exist, it describes the reason for the failure, and you are responsible for releasing it with ",
                  "type": "text"
                },
                {
                  "code": "CFRelease",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A status code set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the call succeeds, or some other value indicating the reason for failure if not.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t call this function on a UI update thread because it may block on network activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)": {
      "abstract": [
        {
          "text": "Returns the name describing the credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyName"
        }
      ],
      "role": "symbol",
      "title": "GSSCredentialCopyName(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscredentialcopyname(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)": {
      "abstract": [
        {
          "text": "Returns a copy of the universally unique identifier corresponding to a GSS credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyUUID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFUUIDRef",
          "text": "CFUUID"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCredentialCopyUUID"
        }
      ],
      "role": "symbol",
      "title": "GSSCredentialCopyUUID(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscredentialcopyuuid(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL": {
      "abstract": [
        {
          "text": "The value that indicates an empty credential object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CREDENTIAL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CREDENTIAL",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_credential"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM": {
      "abstract": [
        {
          "text": "The Kerberos Version 5 Mechanism (KRB5).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM": {
      "abstract": [
        {
          "text": "The Microsoft NT LAN Manager Mechanism (NTLM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NTLM_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NTLM_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_ntlm_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE": {
      "abstract": [
        {
          "text": "The operation completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_COMPLETE"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_COMPLETE",
      "type": "topic",
      "url": "/documentation/gss/gss_s_complete"
    },
    "doc://com.apple.gss/documentation/GSS/OM_uint32": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "role": "symbol",
      "title": "OM_uint32",
      "type": "topic",
      "url": "/documentation/gss/om_uint32"
    },
    "doc://com.apple.gss/documentation/GSS/credential-management": {
      "abstract": [
        {
          "text": "Securely establish connections between endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/credential-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Credential Management",
      "type": "topic",
      "url": "/documentation/gss/credential-management"
    },
    "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a new credential using a password or certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_aapl_initial_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_aapl_initial_cred(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_aapl_initial_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_aapl_initial_cred(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_aapl_initial_cred(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a credential for use in establishing a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_acquire_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_acquire_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_acquire_cred(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_acquire_cred(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Acquires a credential for use in establishing a security context using a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_acquire_cred_with_password"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_acquire_cred_with_password"
        }
      ],
      "role": "symbol",
      "title": "gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID": {
      "abstract": [
        {
          "text": "A pointer to an immutable OID descriptor exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_destroy_cred(_:_:)": {
      "abstract": [
        {
          "text": "Purges a credential from memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_destroy_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_destroy_cred(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_destroy_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_destroy_cred(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_destroy_cred(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a name in contiguous octet format to the internal name format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_import_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_import_name"
        }
      ],
      "role": "symbol",
      "title": "gss_import_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_import_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of supported underlying security mechanisms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs"
        }
      ],
      "role": "symbol",
      "title": "gss_indicate_mechs(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_indicate_mechs(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_name_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a pseudo-random byte stream for keying.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_pseudo_random"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_pseudo_random"
        }
      ],
      "role": "symbol",
      "title": "gss_pseudo_random(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_pseudo_random(_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory of a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_release_cred(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_cred(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICCertificate": {
      "abstract": [
        {
          "text": "The value that indicates a certificate to use with PKINIT/PKU2U.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICCertificate"
        }
      ],
      "role": "symbol",
      "title": "kGSSICCertificate",
      "type": "topic",
      "url": "/documentation/gss/kgssiccertificate"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICPassword": {
      "abstract": [
        {
          "text": "The value is a string that indicates a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICPassword"
        }
      ],
      "role": "symbol",
      "title": "kGSSICPassword",
      "type": "topic",
      "url": "/documentation/gss/kgssicpassword"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFErrorRef": {
      "abstract": [
        {
          "text": "A reference to a CFError object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFError",
      "type": "topic",
      "url": "/documentation/corefoundation/cferror"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s9UnmanagedV": {
      "abstract": [
        {
          "text": "A type for propagating an unmanaged object reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Instance"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9UnmanagedV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Unmanaged",
      "type": "topic",
      "url": "/documentation/Swift/Unmanaged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Acquisition",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
        "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
        "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)"
      ],
      "title": "Acquisition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_aapl_initial_cred"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_aapl_initial_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Acquisition",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_acquire_cred(_:_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyUUID(_:)",
                "doc://com.apple.gss/documentation/GSS/GSSCredentialCopyName(_:)",
                "doc://com.apple.gss/documentation/GSS/gss_pseudo_random(_:_:_:_:_:_:)"
              ],
              "title": "Acquisition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_aapl_initial_cred"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_name_t",
                    "text": "gss_name_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "desired_name"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_const_OID",
                    "text": "gss_const_OID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "desired_mech"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attributes"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_id_t",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "output_cred_handle"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFErrorRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFErrorRef",
                    "text": "CFErrorRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name to use to acquire the credential. Import the name using ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Ensure that the mechanism specified by the ",
                        "type": "text"
                      },
                      {
                        "code": "desired_mech",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter supports the name type.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "desired_name"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The mechanism to use to acquire the credential, for example ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". Use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to get a complete list of supported mechanisms.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "desired_mech"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that includes either the key ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to specify a password or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to name a certificate for use in acquiring the credential. It may also contain any of the other keys listed in Initial Credential Keys in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/credential-management",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to optionally condition the operation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attributes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A credential pointer that the function sets to point at the new credential on success, or sets to ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " on failure. Use ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_cred(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.gss/documentation/GSS/gss_destroy_cred(_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to release the credential’s memory when you are done with it.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "output_cred_handle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An error pointer that the function sets to point at a new error object if the function call fails. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to ignore this error. When an error does exist, it describes the reason for the failure, and you are responsible for releasing it with ",
                        "type": "text"
                      },
                      {
                        "code": "CFRelease",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A status code set to ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the call succeeds, or some other value indicating the reason for failure if not.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/title",
          "value": "gss_const_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCertificate/title",
          "value": "kGSSICCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_destroy_cred(_:_:)/title",
          "value": "gss_destroy_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_destroy_cred(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_destroy_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title",
          "value": "OM_uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyName(_:)/title",
          "value": "GSSCredentialCopyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialCopyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/title",
          "value": "gss_release_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_cred(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICPassword/title",
          "value": "kGSSICPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_initial_cred(_:_:_:_:_:)/title",
          "value": "gss_aapl_initial_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_initial_cred(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_aapl_initial_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title",
          "value": "CFErrorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title",
          "value": "gss_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs(_:_:)/title",
          "value": "gss_indicate_mechs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_indicate_mechs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title",
          "value": "GSS_S_COMPLETE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_COMPLETE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)/title",
          "value": "gss_acquire_cred_with_password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred_with_password(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_acquire_cred_with_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_pseudo_random(_:_:_:_:_:_:)/title",
          "value": "gss_pseudo_random"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_pseudo_random(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_pseudo_random"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyUUID(_:)/title",
          "value": "GSSCredentialCopyUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialCopyUUID(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialCopyUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred(_:_:_:_:_:_:_:_:)/title",
          "value": "gss_acquire_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_acquire_cred(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_acquire_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/title",
          "value": "gss_import_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_import_name"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_aapl_initial_cred(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_aapl_initial_cred(_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
