{"seeAlsoSections":[{"title":"Flags","anchor":"Flags","generated":true,"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE","doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Establishing a context requires a back and forth over a network connection between initiator and acceptor, typically involving multiple calls to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"},{"text":" functions. The ","type":"text"},{"code":"GSS_C_PROT_READY_FLAG","type":"codeVoice"},{"text":" flag, when set by either function as a return flag, indicates that although the context is not yet ready, the forthcoming availability of confidentiality and integrity services is already known and reported by the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG"},{"text":" flags, respectively. This allows you to begin using the various protection functions if reported as available, without waiting for the context to complete.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the flag is not set, you can’t assume anything about the availability of the protection services until the context is complete."}]}],"kind":"content"}],"metadata":{"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"5.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"5.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.14"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"modules":[{"name":"GSS"}],"title":"GSS_C_PROT_READY_FLAG","symbolKind":"var","role":"symbol","externalID":"c:@macro@GSS_C_PROT_READY_FLAG","navigatorTitle":[{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"}],"roleHeading":"Global Variable"},"identifier":{"url":"doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG","interfaceLanguage":"swift"},"abstract":[{"text":"A flag that provides an early indication of the availability of confidentiality and integrity services.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/gss/gss_c_prot_ready_flag"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gss/gss_c_prot_ready_flag"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"sections":[],"references":{"doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG","abstract":[{"text":"A flag that indicates that the client wants to be informed of extended error information.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"/documentation/gss/gss_c_extended_error_flag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_EXTENDED_ERROR_FLAG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_C_EXTENDED_ERROR_FLAG"}],"title":"GSS_C_EXTENDED_ERROR_FLAG"},"doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG":{"navigatorTitle":[{"text":"GSS_C_MUTUAL_FLAG","kind":"identifier"}],"title":"GSS_C_MUTUAL_FLAG","abstract":[{"type":"text","text":"A flag that authenticates the credentials of both initiator and acceptor."}],"url":"/documentation/gss/gss_c_mutual_flag","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_MUTUAL_FLAG"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_CONF_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GSS_C_CONF_FLAG","kind":"identifier"}],"url":"/documentation/gss/gss_c_conf_flag","abstract":[{"text":"A flag that makes confidentiality services (that is, encryption) available for transferred messages.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG","title":"GSS_C_CONF_FLAG"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG","abstract":[{"text":"A flag that permits delegation of the initiator’s credentials by the acceptor.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"/documentation/gss/gss_c_deleg_flag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_DELEG_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"GSS_C_DELEG_FLAG","kind":"identifier"}],"title":"GSS_C_DELEG_FLAG"},"doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)":{"abstract":[{"text":"Accepts a security context initiated by a peer.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_accept_sec_context","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_ctx_id_t","text":"gss_ctx_id_t"},{"kind":"text","text":"?>, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_cred_id_t","text":"gss_cred_id_t"},{"text":"?, ","kind":"text"},{"text":"gss_buffer_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_buffer_t"},{"text":"?, ","kind":"text"},{"text":"gss_channel_bindings_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_channel_bindings_t"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>?, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_OID","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID"},{"text":"?>?, ","kind":"text"},{"text":"gss_buffer_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_buffer_t"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">?, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">?, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_cred_id_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_cred_id_t"},{"text":"?>?) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)","navigatorTitle":[{"text":"gss_accept_sec_context","kind":"identifier"}],"url":"/documentation/gss/gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)","title":"gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG":{"navigatorTitle":[{"kind":"identifier","text":"GSS_C_ANON_FLAG"}],"title":"GSS_C_ANON_FLAG","abstract":[{"type":"text","text":"A flag that ensures the initiator remains anonymous to the acceptor."}],"url":"/documentation/gss/gss_c_anon_flag","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_ANON_FLAG"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG","abstract":[{"text":"A flag that makes integrity services (that is, cryptographic signatures) available for transferred messages.","type":"text"}],"role":"symbol","kind":"symbol","title":"GSS_C_INTEG_FLAG","url":"/documentation/gss/gss_c_integ_flag","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_INTEG_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"GSS_C_INTEG_FLAG","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG":{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG","abstract":[{"type":"text","text":"A flag that indicates delegation is permissible if the mechanism policy allows it."}],"role":"symbol","kind":"symbol","title":"GSS_C_DELEG_POLICY_FLAG","url":"/documentation/gss/gss_c_deleg_policy_flag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_DELEG_POLICY_FLAG"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GSS_C_DELEG_POLICY_FLAG"}]},"doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_TRANS_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GSS_C_TRANS_FLAG","kind":"identifier"}],"url":"/documentation/gss/gss_c_trans_flag","abstract":[{"type":"text","text":"A flag that indicates that a context can is exportable, for example to transfer it to another process on the same machine."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG","title":"GSS_C_TRANS_FLAG"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG":{"url":"/documentation/gss/gss_c_replay_flag","navigatorTitle":[{"text":"GSS_C_REPLAY_FLAG","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG","role":"symbol","abstract":[{"text":"A flag that detects repeated messages.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_REPLAY_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"title":"GSS_C_REPLAY_FLAG","type":"topic","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG":{"url":"/documentation/gss/gss_c_prot_ready_flag","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_PROT_READY_FLAG"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"GSS_C_PROT_READY_FLAG"}],"type":"topic","abstract":[{"text":"A flag that provides an early indication of the availability of confidentiality and integrity services.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_PROT_READY_FLAG","role":"symbol","title":"GSS_C_PROT_READY_FLAG","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_DCE_STYLE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"text":"GSS_C_DCE_STYLE","kind":"identifier"}],"url":"/documentation/gss/gss_c_dce_style","abstract":[{"text":"A flag that causes an extra AP reply to be sent from the client back to the server after receiving the server’s AP reply.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE","title":"GSS_C_DCE_STYLE"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Int32","kind":"identifier"}],"url":"/documentation/Swift/Int32","type":"topic","abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","kind":"symbol","title":"Int32"},"doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)":{"identifier":"doc://com.apple.gss/documentation/GSS/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"gss_init_sec_context"}],"abstract":[{"type":"text","text":"Initiates a security context with a peer."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_init_sec_context"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_cred_id_t","text":"gss_cred_id_t","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_ctx_id_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_ctx_id_t"},{"text":"?>, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID","text":"gss_OID"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"gss_channel_bindings_t","preciseIdentifier":"c:@T@gss_channel_bindings_t"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"gss_buffer_t","preciseIdentifier":"c:@T@gss_buffer_t"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"gss_OID","preciseIdentifier":"c:@T@gss_OID"},{"kind":"text","text":"?>?, "},{"kind":"typeIdentifier","text":"gss_buffer_t","preciseIdentifier":"c:@T@gss_buffer_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"}],"title":"gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)","url":"/documentation/gss/gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)","role":"symbol","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG":{"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG","title":"GSS_C_IDENTIFY_FLAG","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_IDENTIFY_FLAG","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"A flag that indicates identification of the client by name and ID only.","type":"text"}],"navigatorTitle":[{"text":"GSS_C_IDENTIFY_FLAG","kind":"identifier"}],"url":"/documentation/gss/gss_c_identify_flag"},"doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG":{"navigatorTitle":[{"kind":"identifier","text":"GSS_C_SEQUENCE_FLAG"}],"title":"GSS_C_SEQUENCE_FLAG","abstract":[{"type":"text","text":"A flag that detects out of sequence messages."}],"url":"/documentation/gss/gss_c_sequence_flag","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSS_C_SEQUENCE_FLAG"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"5.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"5.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.14","unavailable":false},{"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Macro"},{"value":"GSS_C_PROT_READY_FLAG","op":"replace","path":"/metadata/title"},{"value":"macro","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_MUTUAL_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_REPLAY_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_SEQUENCE_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_CONF_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_INTEG_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_ANON_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_TRANS_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_DCE_STYLE","doc://com.apple.gss/documentation/GSS/GSS_C_IDENTIFY_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_EXTENDED_ERROR_FLAG","doc://com.apple.gss/documentation/GSS/GSS_C_DELEG_POLICY_FLAG"],"generated":true,"anchor":"Flags","title":"Flags"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"GSS_C_EXTENDED_ERROR_FLAG","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_EXTENDED_ERROR_FLAG/title"},{"value":[{"text":"GSS_C_EXTENDED_ERROR_FLAG","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_EXTENDED_ERROR_FLAG/fragments","op":"replace"},{"value":"GSS_C_MUTUAL_FLAG","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MUTUAL_FLAG/title","op":"replace"},{"value":[{"text":"GSS_C_MUTUAL_FLAG","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_MUTUAL_FLAG/fragments","op":"replace"},{"value":"GSS_C_CONF_FLAG","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CONF_FLAG/title","op":"replace"},{"value":[{"kind":"identifier","text":"GSS_C_CONF_FLAG"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CONF_FLAG/fragments","op":"replace"},{"value":"GSS_C_DELEG_FLAG","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/title","op":"replace"},{"value":[{"text":"GSS_C_DELEG_FLAG","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_FLAG/fragments","op":"replace"},{"value":"gss_accept_sec_context","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"gss_accept_sec_context"}],"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_accept_sec_context(_:_:_:_:_:_:_:_:_:_:_:)/fragments","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ANON_FLAG/title","value":"GSS_C_ANON_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ANON_FLAG/fragments","value":[{"kind":"identifier","text":"GSS_C_ANON_FLAG"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INTEG_FLAG/title","value":"GSS_C_INTEG_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INTEG_FLAG/fragments","value":[{"kind":"identifier","text":"GSS_C_INTEG_FLAG"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_POLICY_FLAG/title","value":"GSS_C_DELEG_POLICY_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DELEG_POLICY_FLAG/fragments","value":[{"text":"GSS_C_DELEG_POLICY_FLAG","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_TRANS_FLAG/title","value":"GSS_C_TRANS_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_TRANS_FLAG/fragments","value":[{"text":"GSS_C_TRANS_FLAG","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_REPLAY_FLAG/title","value":"GSS_C_REPLAY_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_REPLAY_FLAG/fragments","value":[{"text":"GSS_C_REPLAY_FLAG","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_PROT_READY_FLAG/title","value":"GSS_C_PROT_READY_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_PROT_READY_FLAG/fragments","value":[{"text":"GSS_C_PROT_READY_FLAG","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DCE_STYLE/title","value":"GSS_C_DCE_STYLE"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_DCE_STYLE/fragments","value":[{"kind":"identifier","text":"GSS_C_DCE_STYLE"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)/title","value":"gss_init_sec_context"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_init_sec_context(_:_:_:_:_:_:_:_:_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"gss_init_sec_context"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_IDENTIFY_FLAG/title","value":"GSS_C_IDENTIFY_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_IDENTIFY_FLAG/fragments","value":[{"text":"GSS_C_IDENTIFY_FLAG","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SEQUENCE_FLAG/title","value":"GSS_C_SEQUENCE_FLAG"},{"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_SEQUENCE_FLAG/fragments","value":[{"text":"GSS_C_SEQUENCE_FLAG","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}