{
  "abstract": [
    {
      "text": "The buffer contains a mechanism trailer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_IOV_BUFFER_TYPE_TRAILER",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GSS_IOV_BUFFER_TYPE_TRAILER"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE": {
      "abstract": [
        {
          "text": "GSS should perform the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_FLAG_ALLOCATE",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_flag_allocate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED": {
      "abstract": [
        {
          "text": "The caller should free the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_FLAG_ALLOCATED",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_flag_allocated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA": {
      "abstract": [
        {
          "text": "The buffer type is packet data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_DATA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_DATA"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_DATA",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_data"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY": {
      "abstract": [
        {
          "text": "The buffer type is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_EMPTY",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_empty"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE": {
      "abstract": [
        {
          "text": "GSS should perform the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_allocate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED": {
      "abstract": [
        {
          "text": "The caller should free the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_allocated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK": {
      "abstract": [
        {
          "text": "The buffer type is a flag mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_mask"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER": {
      "abstract": [
        {
          "text": "The buffer type is a mechanism header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_HEADER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_HEADER"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_HEADER",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_header"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS": {
      "abstract": [
        {
          "text": "The buffer contains mechanism-specific parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_mech_params"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING": {
      "abstract": [
        {
          "text": "The buffer contains padding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_PADDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_PADDING"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_PADDING",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_padding"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY": {
      "abstract": [
        {
          "text": "The buffer contains sign-only packet data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_sign_only"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM": {
      "abstract": [
        {
          "text": "The buffer contains a complete wrap token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_STREAM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_STREAM"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_STREAM",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_stream"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER": {
      "abstract": [
        {
          "text": "The buffer contains a mechanism trailer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_TRAILER",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_trailer"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Buffer-Flags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM"
      ],
      "title": "Buffer Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSS_IOV_BUFFER_TYPE_TRAILER"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Buffer-Flags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM"
              ],
              "title": "Buffer Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_MASK/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_TRAILER/title",
          "value": "GSS_IOV_BUFFER_TYPE_TRAILER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_TRAILER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATED/title",
          "value": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_DATA/title",
          "value": "GSS_IOV_BUFFER_TYPE_DATA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_DATA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_DATA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATE/title",
          "value": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_EMPTY/title",
          "value": "GSS_IOV_BUFFER_TYPE_EMPTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_EMPTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_STREAM/title",
          "value": "GSS_IOV_BUFFER_TYPE_STREAM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_STREAM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_STREAM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_HEADER/title",
          "value": "GSS_IOV_BUFFER_TYPE_HEADER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_HEADER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_HEADER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_PADDING/title",
          "value": "GSS_IOV_BUFFER_TYPE_PADDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_PADDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_PADDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_SIGN_ONLY/title",
          "value": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_SIGN_ONLY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_MECH_PARAMS/title",
          "value": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_MECH_PARAMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_iov_buffer_type_trailer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_iov_buffer_type_trailer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
