{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Function","externalID":"c:@F@gss_duplicate_name","modules":[{"name":"GSS"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false,"introducedAt":"5.0"},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"5.0"},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.7"},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_duplicate_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}],"symbolKind":"func","navigatorTitle":[{"text":"gss_duplicate_name","kind":"identifier"}],"title":"gss_duplicate_name(_:_:_:)"},"abstract":[{"text":"Returns a copy of an internal name.","type":"text"}],"variants":[{"paths":["/documentation/gss/gss_duplicate_name(_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/gss/gss_duplicate_name(_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_duplicate_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"minor_status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","identifier":"doc://com.externally.resolved.symbol/s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"src_name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dest_name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","identifier":"doc://com.externally.resolved.symbol/s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"minor_status","content":[{"type":"paragraph","inlineContent":[{"text":"A pointer to the secondary status result that provides additional information in case of failure.","type":"text"}]}]},{"name":"src_name","content":[{"inlineContent":[{"type":"text","text":"The name to duplicate."}],"type":"paragraph"}]},{"name":"dest_name","content":[{"inlineContent":[{"text":"A pointer the function uses to return the copied name. Release the name using a call to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"},{"text":" function when you are done with it.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A status code set to "},{"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","isActive":true},{"type":"text","text":" on success. See "},{"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/function-status","isActive":true},{"type":"text","text":" for a complete enumeration of status outputs."}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)"],"generated":true,"anchor":"Inquiries","title":"Inquiries"}],"references":{"doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)":{"title":"gss_duplicate_name(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)","abstract":[{"text":"Returns a copy of an internal name.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"gss_duplicate_name","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}],"url":"/documentation/gss/gss_duplicate_name(_:_:_:)","role":"symbol","navigatorTitle":[{"text":"gss_duplicate_name","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/gss_name_t":{"kind":"symbol","url":"/documentation/gss/gss_name_t","type":"topic","navigatorTitle":[{"text":"gss_name_t","kind":"identifier"}],"title":"gss_name_t","role":"symbol","abstract":[{"text":"A pointer to an opaque type that you use to communicate name objects with GSS-API functions.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"gss_name_t","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)":{"navigatorTitle":[{"text":"gss_release_name","kind":"identifier"}],"title":"gss_release_name(_:_:)","abstract":[{"type":"text","text":"Frees the resources associated with a name object."}],"url":"/documentation/gss/gss_release_name(_:_:)","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_release_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}]},"doc://com.apple.gss/documentation/GSS/function-status":{"title":"Function Status","abstract":[{"text":"Evaluate return values that most GSS-API functions use to indicate the outcome of an operation.","type":"text"}],"type":"topic","kind":"article","url":"/documentation/gss/function-status","identifier":"doc://com.apple.gss/documentation/GSS/function-status","role":"collectionGroup"},"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE":{"navigatorTitle":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"abstract":[{"text":"The operation completed without error.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSS_S_COMPLETE","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"role":"symbol","title":"GSS_S_COMPLETE","type":"topic","kind":"symbol","url":"/documentation/gss/gss_s_complete"},"doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)":{"identifier":"doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)","abstract":[{"type":"text","text":"Returns a list of name types that a given mechanism supports."}],"kind":"symbol","type":"topic","role":"symbol","url":"/documentation/gss/gss_inquire_names_for_mech(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gss_inquire_names_for_mech"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_const_OID","kind":"typeIdentifier","text":"gss_const_OID"},{"kind":"text","text":", "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"gss_OID_set","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID_set"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}],"navigatorTitle":[{"text":"gss_inquire_names_for_mech","kind":"identifier"}],"title":"gss_inquire_names_for_mech(_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)","title":"gss_inquire_name(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_inquire_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"gss_OID","preciseIdentifier":"c:@T@gss_OID","kind":"typeIdentifier"},{"text":"?>?, ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"gss_buffer_set_t","preciseIdentifier":"c:@T@gss_buffer_set_t"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Returns information about a name.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"gss_inquire_name"}],"url":"/documentation/gss/gss_inquire_name(_:_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"gss_inquire_mechs_for_name","kind":"identifier"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)","url":"/documentation/gss/gss_inquire_mechs_for_name(_:_:_:)","abstract":[{"text":"Returns a list of mechanisms that support a particular name type.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_inquire_mechs_for_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"gss_OID_set","preciseIdentifier":"c:@T@gss_OID_set","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"}],"title":"gss_inquire_mechs_for_name(_:_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)":{"navigatorTitle":[{"text":"gss_userok","kind":"identifier"}],"title":"gss_userok(_:_:)","abstract":[{"type":"text","text":"Returns a flag that indicates if a given user is authorized."}],"url":"/documentation/gss/gss_userok(_:_:)","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_userok","kind":"identifier"},{"text":"(","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}]},"doc://com.apple.gss/documentation/GSS/OM_uint32":{"url":"/documentation/gss/om_uint32","navigatorTitle":[{"kind":"identifier","text":"OM_uint32"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"OM_uint32"}],"abstract":[{"type":"text","text":"A 32-bit unsigned integer."}],"title":"OM_uint32","type":"topic"},"doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)","title":"gss_compare_name(_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_compare_name"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns a flag that indicates if two names in internal name format refer to the same entity."}],"navigatorTitle":[{"kind":"identifier","text":"gss_compare_name"}],"url":"/documentation/gss/gss_compare_name(_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)":{"type":"topic","title":"gss_aapl_change_password(_:_:_:_:)","role":"symbol","abstract":[{"type":"text","text":"Changes the password associated with a name."}],"navigatorTitle":[{"kind":"identifier","text":"gss_aapl_change_password"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_aapl_change_password"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"gss_const_OID","preciseIdentifier":"c:@T@gss_const_OID"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CFDictionary","preciseIdentifier":"c:@T@CFDictionaryRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CFError","preciseIdentifier":"c:@T@CFErrorRef"},{"kind":"text","text":">?>?) -> "},{"kind":"typeIdentifier","text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32"}],"url":"/documentation/gss/gss_aapl_change_password(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)":{"kind":"symbol","url":"/documentation/gss/gss_display_name(_:_:_:_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"gss_display_name"}],"title":"gss_display_name(_:_:_:_:)","role":"symbol","abstract":[{"text":"Converts a name in the internal format to an octet string and the associated name type.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_display_name"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_buffer_t","text":"gss_buffer_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_OID","text":"gss_OID"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32","text":"OM_uint32"}]},"doc://com.externally.resolved.symbol/s:Sp":{"title":"UnsafeMutablePointer","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"kind":"symbol","url":"/documentation/Swift/UnsafeMutablePointer","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sp","abstract":[{"type":"text","text":"A pointer for accessing and manipulating data of a specific type."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"5.0","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"5.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.7","unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Function"},{"op":"replace","path":"/metadata/title","value":"gss_duplicate_name"},{"op":"replace","path":"/metadata/symbolKind","value":"func"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"gss_duplicate_name"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)"],"title":"Inquiries","anchor":"Inquiries","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"text":"OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":" ","kind":"text"},{"text":"gss_duplicate_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OM_uint32","identifier":"doc://com.apple.gss/documentation/GSS/OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":" * ","kind":"text"},{"text":"minor_status","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"src_name","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":" * ","kind":"text"},{"text":"dest_name","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A pointer to the secondary status result that provides additional information in case of failure.","type":"text"}]}],"name":"minor_status"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name to duplicate.","type":"text"}]}],"name":"src_name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A pointer the function uses to return the copied name. Release the name using a call to the ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","isActive":true,"type":"reference"},{"text":" function when you are done with it.","type":"text"}]}],"name":"dest_name"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A status code set to ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_S_COMPLETE","isActive":true,"type":"reference"},{"text":" on success. See ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/function-status","isActive":true,"type":"reference"},{"text":" for a complete enumeration of status outputs.","type":"text"}],"type":"paragraph"}]}},{"value":"gss_duplicate_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/title"},{"value":[{"text":"gss_duplicate_name","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/fragments"},{"value":"gss_name_t","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title"},{"value":[{"kind":"identifier","text":"gss_name_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments"},{"value":[{"kind":"identifier","text":"gss_name_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle"},{"value":"gss_release_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/title"},{"value":[{"kind":"identifier","text":"gss_release_name"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/fragments"},{"value":"GSS_S_COMPLETE","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/title"},{"value":[{"text":"GSS_S_COMPLETE","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_COMPLETE/fragments"},{"value":"gss_inquire_names_for_mech","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/title"},{"value":[{"text":"gss_inquire_names_for_mech","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/fragments"},{"value":"gss_inquire_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/title"},{"value":[{"text":"gss_inquire_name","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/fragments"},{"value":"gss_inquire_mechs_for_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/title"},{"value":[{"text":"gss_inquire_mechs_for_name","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/fragments"},{"value":"gss_userok","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/title"},{"value":[{"kind":"identifier","text":"gss_userok"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/fragments"},{"value":"OM_uint32","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title"},{"value":[{"text":"OM_uint32","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments"},{"value":[{"kind":"identifier","text":"OM_uint32"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle"},{"value":"gss_compare_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/title"},{"value":[{"text":"gss_compare_name","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/fragments"},{"value":"gss_aapl_change_password","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/title"},{"value":[{"kind":"identifier","text":"gss_aapl_change_password"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/fragments"},{"value":"gss_display_name","op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/title"},{"value":[{"text":"gss_display_name","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}