{
  "abstract": [
    {
      "text": "The structure for determining the returned Kerberos lucid context structure version.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@gss_krb5_lucid_context_version_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_krb5_lucid_context_version_t"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_krb5_lucid_context_version_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "gss_krb5_lucid_context_version_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@gss_krb5_lucid_context_version",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t": {
      "abstract": [
        {
          "text": "The structure of a Kerberos context and acceptor-asserted key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_cfx_keydata_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_cfx_keydata_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t": {
      "abstract": [
        {
          "text": "The structure of a Kerberos context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_v1_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_version",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version/version": {
      "abstract": [
        {
          "text": "The structure version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version/version"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t": {
      "abstract": [
        {
          "text": "The structure for determining the returned Kerberos lucid context structure version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_version_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t": {
      "abstract": [
        {
          "text": "The structure for a Kerberos encryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_key_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_key_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t": {
      "abstract": [
        {
          "text": "The structure for an RFC 1964-compliant Kerberos encryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_rfc1964_keydata_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_rfc1964_keydata_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contexts-and-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t"
      ],
      "title": "Contexts and Keys"
    }
  ],
  "topicSections": [
    {
      "anchor": "Context-Members",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version/version"
      ],
      "title": "Context Members"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_krb5_lucid_context_version_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Context-Members",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version/version"
              ],
              "title": "Context Members"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contexts-and-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t"
              ],
              "title": "Contexts and Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@gss_krb5_lucid_context_version",
                    "text": "gss_krb5_lucid_context_version"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_krb5_lucid_context_version_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/title",
          "value": "gss_krb5_rfc1964_keydata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/title",
          "value": "gss_krb5_cfx_keydata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/title",
          "value": "gss_krb5_lucid_context_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/title",
          "value": "gss_krb5_lucid_context_v1_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/title",
          "value": "gss_krb5_lucid_context_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/title",
          "value": "gss_krb5_lucid_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_krb5_lucid_context_version_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_krb5_lucid_context_version_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
