{
  "abstract": [
    {
      "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@gss_cred_id_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_cred_id_t"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_cred_id_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "gss_cred_id_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can accept a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_ACCEPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_ACCEPT"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_ACCEPT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_accept"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can both initiate and accept security contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_BOTH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_BOTH"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_BOTH",
      "type": "topic",
      "url": "/documentation/gss/gss_c_both"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE": {
      "abstract": [
        {
          "text": "The value that indicates a certificate-based credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_CERTIFICATE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_CERTIFICATE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_certificate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE": {
      "abstract": [
        {
          "text": "The value that indicates a Heimdal-based credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_HEIMBASE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_HEIMBASE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_heimbase"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI": {
      "abstract": [
        {
          "text": "The value that indicates no UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_NO_UI"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_NO_UI"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_CRED_NO_UI",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_no_ui"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD": {
      "abstract": [
        {
          "text": "The value that indicates a password-based credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_PASSWORD"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_PASSWORD",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_password"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity": {
      "abstract": [
        {
          "text": "The value that indicates a security identity-based credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_SecIdentity"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_SecIdentity",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_secidentity"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE": {
      "abstract": [
        {
          "text": "The value that indicates the maximum permitted lifetime when used in a time request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INDEFINITE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_indefinite"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE": {
      "abstract": [
        {
          "text": "The value that indicates a credential that can initiate a security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INITIATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INITIATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INITIATE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_initiate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL": {
      "abstract": [
        {
          "text": "The value that indicates an empty credential object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_CREDENTIAL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_CREDENTIAL",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_credential"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK": {
      "abstract": [
        {
          "text": "The masking constant for options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_OPTION_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_OPTION_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_OPTION_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_c_option_mask"
    },
    "doc://com.apple.gss/documentation/GSS/gss_auth_identity_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque object used to manage authentication identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_auth_identity_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_auth_identity_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_auth_identity_t"
        }
      ],
      "role": "symbol",
      "title": "gss_auth_identity_t",
      "type": "topic",
      "url": "/documentation/gss/gss_auth_identity_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_const_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t": {
      "abstract": [
        {
          "text": "A credential usage value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_usage_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_usage_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_usage_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_usage_t"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Credential-Masks-and-Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
        "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
        "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
        "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
        "doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI",
        "doc://com.apple.gss/documentation/GSS/gss_auth_identity_t",
        "doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t",
        "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t"
      ],
      "title": "Credential Masks and Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Credential-Masks-and-Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_PASSWORD",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_CERTIFICATE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SecIdentity",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_HEIMBASE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_CREDENTIAL",
                "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_INITIATE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_ACCEPT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_BOTH",
                "doc://com.apple.gss/documentation/GSS/GSS_C_OPTION_MASK",
                "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_NO_UI",
                "doc://com.apple.gss/documentation/GSS/gss_auth_identity_t",
                "doc://com.apple.gss/documentation/GSS/gss_const_cred_id_t",
                "doc://com.apple.gss/documentation/GSS/gss_cred_usage_t"
              ],
              "title": "Credential Masks and Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@gss_cred_id_t_desc_struct",
                    "text": "gss_cred_id_t_desc_struct"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/title",
          "value": "GSS_C_INDEFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INDEFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/title",
          "value": "gss_const_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/title",
          "value": "gss_auth_identity_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_auth_identity_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_auth_identity_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_auth_identity_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_OPTION_MASK/title",
          "value": "GSS_C_OPTION_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_OPTION_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_OPTION_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/title",
          "value": "GSS_C_BOTH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_BOTH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_BOTH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/title",
          "value": "gss_cred_usage_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_usage_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_usage_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_usage_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CRED_NO_UI/title",
          "value": "GSS_C_CRED_NO_UI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_CRED_NO_UI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_CRED_NO_UI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/title",
          "value": "GSS_C_ACCEPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_ACCEPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_ACCEPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/title",
          "value": "GSS_C_INITIATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INITIATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INITIATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_cred_id_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_cred_id_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
