{
  "abstract": [
    {
      "text": "Failed token integrity check.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GSS_S_BAD_SIG",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSS_S_BAD_SIG"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Su",
        "text": "UInt"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSS_S_BAD_SIG"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "GSS_S_BAD_SIG"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_SIG"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Su",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Su",
              "text": "UInt"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value is an alias for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS": {
      "abstract": [
        {
          "text": "Channel bindings mismatch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_BINDINGS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_BINDINGS"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_BINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_bindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH": {
      "abstract": [
        {
          "text": "Unsupported mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_MECH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_MECH"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_MECH",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_mech"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC": {
      "abstract": [
        {
          "text": "Failed token integrity check.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_MIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_MIC"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_MIC",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_mic"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME": {
      "abstract": [
        {
          "text": "Invalid name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_NAME"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_NAME"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE": {
      "abstract": [
        {
          "text": "Unsupported name type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_NAMETYPE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_NAMETYPE"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_NAMETYPE",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_nametype"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP": {
      "abstract": [
        {
          "text": "Unsupported QOP value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_QOP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_QOP"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_QOP",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_qop"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG": {
      "abstract": [
        {
          "text": "Failed token integrity check.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_SIG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_SIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_SIG"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_SIG",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_sig"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS": {
      "abstract": [
        {
          "text": "Invalid status selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_STATUS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_BAD_STATUS"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_BAD_STATUS",
      "type": "topic",
      "url": "/documentation/gss/gss_s_bad_status"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED": {
      "abstract": [
        {
          "text": "Expired context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_CONTEXT_EXPIRED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_CONTEXT_EXPIRED"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_CONTEXT_EXPIRED",
      "type": "topic",
      "url": "/documentation/gss/gss_s_context_expired"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED": {
      "abstract": [
        {
          "text": "Expired credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_CREDENTIALS_EXPIRED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_CREDENTIALS_EXPIRED"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_CREDENTIALS_EXPIRED",
      "type": "topic",
      "url": "/documentation/gss/gss_s_credentials_expired"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL": {
      "abstract": [
        {
          "text": "Defective credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_DEFECTIVE_CREDENTIAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_DEFECTIVE_CREDENTIAL"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_DEFECTIVE_CREDENTIAL",
      "type": "topic",
      "url": "/documentation/gss/gss_s_defective_credential"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN": {
      "abstract": [
        {
          "text": "Defective token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_DEFECTIVE_TOKEN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_DEFECTIVE_TOKEN"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_DEFECTIVE_TOKEN",
      "type": "topic",
      "url": "/documentation/gss/gss_s_defective_token"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE": {
      "abstract": [
        {
          "text": "An unspecified error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_FAILURE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_FAILURE"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_FAILURE",
      "type": "topic",
      "url": "/documentation/gss/gss_s_failure"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT": {
      "abstract": [
        {
          "text": "No valid security context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_NO_CONTEXT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_NO_CONTEXT"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_NO_CONTEXT",
      "type": "topic",
      "url": "/documentation/gss/gss_s_no_context"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED": {
      "abstract": [
        {
          "text": "No valid credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_NO_CRED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_NO_CRED"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_NO_CRED",
      "type": "topic",
      "url": "/documentation/gss/gss_s_no_cred"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED": {
      "abstract": [
        {
          "text": "Unauthorized operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_S_UNAUTHORIZED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_S_UNAUTHORIZED"
        }
      ],
      "role": "symbol",
      "title": "GSS_S_UNAUTHORIZED",
      "type": "topic",
      "url": "/documentation/gss/gss_s_unauthorized"
    },
    "doc://com.externally.resolved.symbol/s:Su": {
      "abstract": [
        {
          "text": "An unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Su",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt",
      "type": "topic",
      "url": "/documentation/Swift/UInt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Routine-Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS",
        "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED",
        "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT",
        "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN",
        "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL",
        "doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED",
        "doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED",
        "doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE",
        "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP",
        "doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED"
      ],
      "title": "Routine Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSS_S_BAD_SIG"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_SIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Routine-Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MECH",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_NAMETYPE",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_MIC",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_STATUS",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_BINDINGS",
                "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CRED",
                "doc://com.apple.gss/documentation/GSS/GSS_S_NO_CONTEXT",
                "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_TOKEN",
                "doc://com.apple.gss/documentation/GSS/GSS_S_DEFECTIVE_CREDENTIAL",
                "doc://com.apple.gss/documentation/GSS/GSS_S_CREDENTIALS_EXPIRED",
                "doc://com.apple.gss/documentation/GSS/GSS_S_CONTEXT_EXPIRED",
                "doc://com.apple.gss/documentation/GSS/GSS_S_FAILURE",
                "doc://com.apple.gss/documentation/GSS/GSS_S_BAD_QOP",
                "doc://com.apple.gss/documentation/GSS/GSS_S_UNAUTHORIZED"
              ],
              "title": "Routine Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSS_S_BAD_SIG"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MECH/title",
          "value": "GSS_S_BAD_MECH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MECH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_MECH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CONTEXT/title",
          "value": "GSS_S_NO_CONTEXT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CONTEXT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_NO_CONTEXT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CRED/title",
          "value": "GSS_S_NO_CRED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_NO_CRED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_NO_CRED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_CREDENTIAL/title",
          "value": "GSS_S_DEFECTIVE_CREDENTIAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_CREDENTIAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_DEFECTIVE_CREDENTIAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_SIG/title",
          "value": "GSS_S_BAD_SIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_SIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_SIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_TOKEN/title",
          "value": "GSS_S_DEFECTIVE_TOKEN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_DEFECTIVE_TOKEN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_DEFECTIVE_TOKEN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CREDENTIALS_EXPIRED/title",
          "value": "GSS_S_CREDENTIALS_EXPIRED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CREDENTIALS_EXPIRED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_CREDENTIALS_EXPIRED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_BINDINGS/title",
          "value": "GSS_S_BAD_BINDINGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_BINDINGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_BINDINGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_FAILURE/title",
          "value": "GSS_S_FAILURE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_FAILURE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_FAILURE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MIC/title",
          "value": "GSS_S_BAD_MIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_MIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_MIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAME/title",
          "value": "GSS_S_BAD_NAME"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAME/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_NAME"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAMETYPE/title",
          "value": "GSS_S_BAD_NAMETYPE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_NAMETYPE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_NAMETYPE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_STATUS/title",
          "value": "GSS_S_BAD_STATUS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_STATUS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_STATUS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_UNAUTHORIZED/title",
          "value": "GSS_S_UNAUTHORIZED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_UNAUTHORIZED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_UNAUTHORIZED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_QOP/title",
          "value": "GSS_S_BAD_QOP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_BAD_QOP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_BAD_QOP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CONTEXT_EXPIRED/title",
          "value": "GSS_S_CONTEXT_EXPIRED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_S_CONTEXT_EXPIRED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_S_CONTEXT_EXPIRED"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_s_bad_sig"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_s_bad_sig"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
