{
  "abstract": [
    {
      "text": "A pointer to a descriptor that manages an array of OID descriptors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/gss_OID_set"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@gss_OID_set",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gss_OID_set"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gss_OID_set"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "gss_OID_set"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@gss_OID_set_desc_struct",
              "text": "gss_OID_set_desc_struct"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects": {
      "abstract": [
        {
          "text": "Manage memory and object lifetimes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/allocating-and-releasing-objects",
      "kind": "article",
      "role": "article",
      "title": "Allocating and Releasing Objects",
      "type": "topic",
      "url": "/documentation/gss/allocating-and-releasing-objects"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID": {
      "abstract": [
        {
          "text": "A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_desc": {
      "abstract": [
        {
          "text": "The OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct": {
      "abstract": [
        {
          "text": "The structure for an OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set": {
      "abstract": [
        {
          "text": "A pointer to a descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc": {
      "abstract": [
        {
          "text": "The descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct": {
      "abstract": [
        {
          "text": "The structure for an OID set descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID": {
      "abstract": [
        {
          "text": "A pointer to an immutable OID descriptor exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID_set": {
      "abstract": [
        {
          "text": "A pointer to an immutable descriptor manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID_set"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID_set"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID_set",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid_set"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Object-IDs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_OID",
        "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
        "doc://com.apple.gss/documentation/GSS/gss_const_OID",
        "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
        "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
        "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
        "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct"
      ],
      "title": "Object IDs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gss_OID_set"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Object-IDs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_OID",
                "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
                "doc://com.apple.gss/documentation/GSS/gss_const_OID",
                "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
                "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
                "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
                "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct"
              ],
              "title": "Object IDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@gss_OID_set_desc_struct",
                    "text": "gss_OID_set_desc_struct"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "gss_OID_set"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/title",
          "value": "gss_OID_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/title",
          "value": "gss_const_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/title",
          "value": "gss_OID_set_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/title",
          "value": "gss_OID_set_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/title",
          "value": "gss_OID_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/title",
          "value": "gss_const_OID_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/title",
          "value": "gss_OID_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title",
          "value": "gss_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gss_oid_set"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gss_oid_set"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
