{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSSCreateName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFTypeRef","text":"CFTypeRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFTypeRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name_type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.gss/documentation/GSS/gss_const_OID","preciseIdentifier":"c:@T@gss_const_OID","text":"gss_const_OID"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sp","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"identifier":"doc://com.externally.resolved.symbol/s:s9UnmanagedV","kind":"typeIdentifier","preciseIdentifier":"s:s9UnmanagedV","text":"Unmanaged"},{"kind":"text","text":"<"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFErrorRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFErrorRef","text":"CFError"},{"kind":"text","text":">?>?) -> "},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":"?"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},{"parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A name buffer describing the credential. The buffer is either a "},{"type":"codeVoice","code":"CFDataRef"},{"type":"text","text":" or a "},{"type":"codeVoice","code":"CFStringRef"},{"type":"text","text":" containing the name."}]}]},{"name":"name_type","content":[{"inlineContent":[{"type":"text","text":"An OID name type constant, such as "},{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"A ","type":"text"},{"code":"CFErrorRef","type":"codeVoice"},{"text":" pointer that the function sets to point at a new error object if the function call fails, or ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore the error. If the error exists, it describes the reason for the failure, and you are responsible for releasing it with ","type":"text"},{"code":"CFRelease","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A GSS name for the given buffer and type, or ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" on failure. Release this object with a call to ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","isActive":true,"type":"reference"},{"text":" when you are done with it.","type":"text"}]}]}],"abstract":[{"text":"Returns a GSS name given a buffer and a type.","type":"text"}],"identifier":{"url":"doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Creation-and-Destruction","title":"Creation and Destruction","identifiers":["doc://com.apple.gss/documentation/GSS/gss_name_t","doc://com.apple.gss/documentation/GSS/gss_const_name_t","doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)","doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"],"generated":true}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Function","externalID":"c:@F@GSSCreateName","title":"GSSCreateName(_:_:_:)","symbolKind":"func","navigatorTitle":[{"kind":"identifier","text":"GSSCreateName"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSSCreateName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFTypeRef","text":"CFTypeRef"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_const_OID","text":"gss_const_OID"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"Unmanaged","kind":"typeIdentifier","preciseIdentifier":"s:s9UnmanagedV"},{"text":"<","kind":"text"},{"text":"CFError","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFErrorRef"},{"text":">?>?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t"},{"kind":"text","text":"?"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"7.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"7.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"10.9","name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"}],"modules":[{"name":"GSS"}],"role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/gss/gsscreatename(_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gss/gsscreatename(_:_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:Sp":{"title":"UnsafeMutablePointer","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"kind":"symbol","url":"/documentation/Swift/UnsafeMutablePointer","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sp","abstract":[{"type":"text","text":"A pointer for accessing and manipulating data of a specific type."}],"type":"topic"},"doc://com.apple.gss/documentation/GSS/gss_name_t":{"kind":"symbol","url":"/documentation/gss/gss_name_t","type":"topic","navigatorTitle":[{"text":"gss_name_t","kind":"identifier"}],"title":"gss_name_t","role":"symbol","abstract":[{"text":"A pointer to an opaque type that you use to communicate name objects with GSS-API functions.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"gss_name_t","kind":"identifier"}]},"doc://com.apple.gss/documentation/GSS/gss_const_OID":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"gss_const_OID"}],"url":"/documentation/gss/gss_const_oid","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"gss_const_OID"}],"abstract":[{"text":"A pointer to an immutable OID descriptor exchanges object identifiers with many GSS-API functions.","type":"text"}],"identifier":"doc://com.apple.gss/documentation/GSS/gss_const_OID","type":"topic","title":"gss_const_OID","kind":"symbol"},"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)":{"navigatorTitle":[{"text":"gss_release_name","kind":"identifier"}],"title":"gss_release_name(_:_:)","abstract":[{"type":"text","text":"Frees the resources associated with a name object."}],"url":"/documentation/gss/gss_release_name(_:_:)","role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_release_name","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"},{"text":">, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"gss_name_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","kind":"typeIdentifier","preciseIdentifier":"c:@T@OM_uint32"}]},"doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)":{"navigatorTitle":[{"text":"gss_canonicalize_name","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)","abstract":[{"text":"Converts an internal name into a mechanism name.","type":"text"}],"role":"symbol","title":"gss_canonicalize_name(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gss_canonicalize_name","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier","text":"gss_name_t"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_OID","kind":"typeIdentifier","text":"gss_OID"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t","kind":"typeIdentifier"},{"text":"?>) -> ","kind":"text"},{"text":"OM_uint32","preciseIdentifier":"c:@T@OM_uint32","kind":"typeIdentifier"}],"url":"/documentation/gss/gss_canonicalize_name(_:_:_:_:)"},"doc://com.apple.gss/documentation/GSS":{"identifier":"doc://com.apple.gss/documentation/GSS","abstract":[{"text":"Conduct secure, authenticated network transactions.","type":"text"}],"role":"collection","kind":"symbol","title":"GSS","url":"/documentation/gss","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)":{"role":"symbol","navigatorTitle":[{"text":"GSSCreateName","kind":"identifier"}],"url":"/documentation/gss/gsscreatename(_:_:_:)","abstract":[{"type":"text","text":"Returns a GSS name given a buffer and a type."}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)","title":"GSSCreateName(_:_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"GSSCreateName","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CFTypeRef","kind":"typeIdentifier","text":"CFTypeRef"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@gss_const_OID","kind":"typeIdentifier","text":"gss_const_OID"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s9UnmanagedV","text":"Unmanaged","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CFError","preciseIdentifier":"c:@T@CFErrorRef","kind":"typeIdentifier"},{"text":">?>?) -> ","kind":"text"},{"text":"gss_name_t","preciseIdentifier":"c:@T@gss_name_t","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic","role":"overview","url":"/documentation/technologies","title":"Technologies"},"doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME":{"url":"/documentation/gss/gss_c_nt_user_name","abstract":[{"type":"text","text":"A name that specifies a user on a local system in the username format."}],"fragments":[{"kind":"identifier","text":"GSS_C_NT_USER_NAME"}],"role":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME","kind":"symbol","title":"GSS_C_NT_USER_NAME","type":"topic"},"doc://com.apple.gss/documentation/GSS/gss_const_name_t":{"role":"symbol","navigatorTitle":[{"text":"gss_const_name_t","kind":"identifier"}],"url":"/documentation/gss/gss_const_name_t","abstract":[{"type":"text","text":"A pointer to an immutable version of the opaque descriptor used to exchange name objects with GSS-API functions."}],"type":"topic","identifier":"doc://com.apple.gss/documentation/GSS/gss_const_name_t","title":"gss_const_name_t","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"gss_const_name_t","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@CFErrorRef":{"type":"topic","abstract":[{"text":"A reference to a CFError object.","type":"text"}],"kind":"symbol","url":"/documentation/corefoundation/cferror","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CFError"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CFErrorRef","title":"CFError","role":"symbol"},"doc://com.externally.resolved.symbol/s:s9UnmanagedV":{"abstract":[{"type":"text","text":"A type for propagating an unmanaged object reference."}],"identifier":"doc://com.externally.resolved.symbol/s:s9UnmanagedV","kind":"symbol","type":"topic","url":"/documentation/Swift/Unmanaged","title":"Unmanaged","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Unmanaged"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Instance"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Instance"},{"kind":"text","text":" : AnyObject"}]},"doc://com.externally.resolved.symbol/c:@T@CFTypeRef":{"abstract":[{"type":"text","text":"An untyped \"generic\" reference to any Core Foundation object."}],"url":"/documentation/corefoundation/cftyperef","title":"CFTypeRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFTypeRef","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"CFTypeRef"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)":{"abstract":[{"type":"text","text":"Returns a string suitable for displaying to the user from a GSS name."}],"type":"topic","url":"/documentation/gss/gssnamecreatedisplaystring(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GSSNameCreateDisplayString"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GSSNameCreateDisplayString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@gss_name_t","text":"gss_name_t","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Unmanaged","preciseIdentifier":"s:s9UnmanagedV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"title":"GSSNameCreateDisplayString(_:)","kind":"symbol","identifier":"doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"7.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"7.0"},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.9"},{"beta":false,"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Function","path":"/metadata/roleHeading"},{"value":"GSSCreateName","path":"/metadata/title","op":"replace"},{"value":"func","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"GSSCreateName"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gss/documentation/GSS"]]},"path":"/hierarchy","op":"replace"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.gss/documentation/GSS/gss_name_t","doc://com.apple.gss/documentation/GSS/gss_const_name_t","doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)","doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)","doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"],"title":"Creation and Destruction","anchor":"Creation-and-Destruction","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:@T@gss_name_t","identifier":"doc://com.apple.gss/documentation/GSS/gss_name_t","text":"gss_name_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"GSSCreateName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFTypeRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFTypeRef","text":"CFTypeRef"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"gss_const_OID","preciseIdentifier":"c:@T@gss_const_OID","kind":"typeIdentifier","identifier":"doc://com.apple.gss/documentation/GSS/gss_const_OID"},{"text":" ","kind":"text"},{"text":"name_type","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"CFErrorRef","preciseIdentifier":"c:@T@CFErrorRef","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@CFErrorRef"},{"text":" * ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A name buffer describing the credential. The buffer is either a ","type":"text"},{"code":"CFDataRef","type":"codeVoice"},{"text":" or a ","type":"text"},{"type":"codeVoice","code":"CFStringRef"},{"type":"text","text":" containing the name."}]}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An OID name type constant, such as ","type":"text"},{"identifier":"doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"name":"name_type"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"CFErrorRef","type":"codeVoice"},{"text":" pointer that the function sets to point at a new error object if the function call fails, or ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to ignore the error. If the error exists, it describes the reason for the failure, and you are responsible for releasing it with ","type":"text"},{"code":"CFRelease","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"error"}]}},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A GSS name for the given buffer and type, or ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":" on failure. Release this object with a call to ","type":"text"},{"type":"reference","identifier":"doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)","isActive":true},{"text":" when you are done with it.","type":"text"}],"type":"paragraph"}]}},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title","op":"replace","value":"gss_name_t"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments","op":"replace","value":[{"text":"gss_name_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle","op":"replace","value":[{"text":"gss_name_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/title","op":"replace","value":"gss_const_OID"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/fragments","op":"replace","value":[{"text":"gss_const_OID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/navigatorTitle","op":"replace","value":[{"text":"gss_const_OID","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/title","op":"replace","value":"gss_release_name"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/fragments","op":"replace","value":[{"text":"gss_release_name","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_canonicalize_name(_:_:_:_:)/title","op":"replace","value":"gss_canonicalize_name"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_canonicalize_name(_:_:_:_:)/fragments","op":"replace","value":[{"text":"gss_canonicalize_name","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateName(_:_:_:)/title","op":"replace","value":"GSSCreateName"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateName(_:_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"GSSCreateName"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/title","op":"replace","value":"gss_const_name_t"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/fragments","op":"replace","value":[{"text":"gss_const_name_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"gss_const_name_t"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFErrorRef/title","op":"replace","value":"CFErrorRef"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSNameCreateDisplayString(_:)/title","op":"replace","value":"GSSNameCreateDisplayString"},{"path":"/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSNameCreateDisplayString(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"GSSNameCreateDisplayString"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}