{
  "abstract": [
    {
      "text": "Returns the remaining time in seconds before the credential expires.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/GSSCredentialGetLifetime(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@GSSCredentialGetLifetime",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "GSSCredentialGetLifetime"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gss_cred_id_t",
        "text": "gss_cred_id_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OM_uint32",
        "text": "OM_uint32"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GSSCredentialGetLifetime"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "GSSCredentialGetLifetime(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GSSCredentialGetLifetime"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "cred"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gss_cred_id_t",
              "text": "gss_cred_id_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OM_uint32",
              "text": "OM_uint32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The credential to inspect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "cred"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The time in seconds that the credential has before it expires. The time is 0 if the call fails, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the credential never expires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCredentialGetLifetime(_:)": {
      "abstract": [
        {
          "text": "Returns the remaining time in seconds before the credential expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCredentialGetLifetime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCredentialGetLifetime(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCredentialGetLifetime"
        }
      ],
      "role": "symbol",
      "title": "GSSCredentialGetLifetime(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscredentialgetlifetime(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE": {
      "abstract": [
        {
          "text": "The value that indicates the maximum permitted lifetime when used in a time request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_INDEFINITE"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_INDEFINITE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_indefinite"
    },
    "doc://com.apple.gss/documentation/GSS/OM_uint32": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OM_uint32"
        }
      ],
      "role": "symbol",
      "title": "OM_uint32",
      "type": "topic",
      "url": "/documentation/gss/om_uint32"
    },
    "doc://com.apple.gss/documentation/GSS/gss_cred_id_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to exchange a credential object with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_cred_id_t"
        }
      ],
      "role": "symbol",
      "title": "gss_cred_id_t",
      "type": "topic",
      "url": "/documentation/gss/gss_cred_id_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_cred(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains information about a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_cred"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_cred(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_cred"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_cred(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_cred(_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Obtains per-mechanism information about a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_cred_by_mech"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_usage_t",
          "text": "gss_cred_usage_t"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_cred_by_mech"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_oid(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Inquires about a particular characteristic of a credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_cred_by_oid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_set_t",
          "text": "gss_buffer_set_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_oid(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_cred_by_oid"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_cred_by_oid(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_cred_by_oid(_:_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inquiries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_inquire_cred(_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_oid(_:_:_:_:)"
      ],
      "title": "Inquiries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GSSCredentialGetLifetime"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialGetLifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inquiries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_inquire_cred(_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_cred_by_oid(_:_:_:_:)"
              ],
              "title": "Inquiries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/OM_uint32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OM_uint32",
                    "text": "OM_uint32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "GSSCredentialGetLifetime"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/gss_cred_id_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gss_cred_id_t",
                    "text": "gss_cred_id_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "cred"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The credential to inspect.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "cred"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The time in seconds that the credential has before it expires. The time is 0 if the call fails, or ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INDEFINITE",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the credential never expires.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred(_:_:_:_:_:_:)/title",
          "value": "gss_inquire_cred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_cred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialGetLifetime(_:)/title",
          "value": "GSSCredentialGetLifetime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCredentialGetLifetime(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCredentialGetLifetime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/title",
          "value": "gss_cred_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_cred_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_cred_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/title",
          "value": "OM_uint32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1OM_uint32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OM_uint32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/title",
          "value": "GSS_C_INDEFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_INDEFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_INDEFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred_by_oid(_:_:_:_:)/title",
          "value": "gss_inquire_cred_by_oid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred_by_oid(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_cred_by_oid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)/title",
          "value": "gss_inquire_cred_by_mech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_cred_by_mech(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_cred_by_mech"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/gsscredentialgetlifetime(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/gsscredentialgetlifetime(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
