{
  "abstract": [
    {
      "text": "Establish secure connections using the Kerberos implementation of GSS-API.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Kerberos Implementation"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_ccache_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the internal Kerberos 5 credential cache name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_ccache_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_ccache_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_ccache_name"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_ccache_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_ccache_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t": {
      "abstract": [
        {
          "text": "The structure of a Kerberos context and acceptor-asserted key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_cfx_keydata_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_cfx_keydata_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_copy_ccache(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies Kerberos 5 credentials into the passed cache.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_copy_ccache"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_copy_ccache(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_copy_ccache"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_copy_ccache(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_copy_ccache(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_export_lucid_sec_context(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a non-opaque version of the internal context information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_export_lucid_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_export_lucid_sec_context(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_export_lucid_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_export_lucid_sec_context(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_export_lucid_sec_context(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_free_lucid_sec_context(_:_:)": {
      "abstract": [
        {
          "text": "Frees allocated storage associated with an exported context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_free_lucid_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_free_lucid_sec_context(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_free_lucid_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_free_lucid_sec_context(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_free_lucid_sec_context(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t": {
      "abstract": [
        {
          "text": "The structure of a Kerberos context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_v1_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t": {
      "abstract": [
        {
          "text": "The structure for determining the returned Kerberos lucid context structure version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_version_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t": {
      "abstract": [
        {
          "text": "The structure for a Kerberos encryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_key_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_key_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t": {
      "abstract": [
        {
          "text": "The structure for an RFC 1964-compliant Kerberos encryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata_t"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_rfc1964_keydata_t",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_rfc1964_keydata_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_set_allowable_enctypes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Limits the keys that can be exported to the specified types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_set_allowable_enctypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_cred_id_t",
          "text": "gss_cred_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_set_allowable_enctypes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_set_allowable_enctypes"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_set_allowable_enctypes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_set_allowable_enctypes(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Extracts Kerberos authorization data stored within the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gsskrb5_extract_authz_data_from_sec_context"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gsskrb5_extract_authz_data_from_sec_context"
        }
      ],
      "role": "symbol",
      "title": "gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gsskrb5_register_acceptor_identity(_:)": {
      "abstract": [
        {
          "text": "Sets the Kerberos 5 file-based key that the acceptor will use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gsskrb5_register_acceptor_identity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gsskrb5_register_acceptor_identity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gsskrb5_register_acceptor_identity"
        }
      ],
      "role": "symbol",
      "title": "gsskrb5_register_acceptor_identity(_:)",
      "type": "topic",
      "url": "/documentation/gss/gsskrb5_register_acceptor_identity(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/krb5_gss_register_acceptor_identity(_:)": {
      "abstract": [
        {
          "text": "Sets the Kerberos 5 file-based key that the acceptor will use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "krb5_gss_register_acceptor_identity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/krb5_gss_register_acceptor_identity(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "krb5_gss_register_acceptor_identity"
        }
      ],
      "role": "symbol",
      "title": "krb5_gss_register_acceptor_identity(_:)",
      "type": "topic",
      "url": "/documentation/gss/krb5_gss_register_acceptor_identity(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/message-protection": {
      "abstract": [
        {
          "text": "Provide cryptographic protection to secure message integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/message-protection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Protection",
      "type": "topic",
      "url": "/documentation/gss/message-protection"
    },
    "doc://com.apple.gss/documentation/GSS/token-management": {
      "abstract": [
        {
          "text": "Establish secure communication with tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/token-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Token Management",
      "type": "topic",
      "url": "/documentation/gss/token-management"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/token-management",
        "doc://com.apple.gss/documentation/GSS/message-protection"
      ],
      "title": "Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Contexts-and-Keys",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t"
      ],
      "title": "Contexts and Keys"
    },
    {
      "anchor": "Identity-and-Settings",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_export_lucid_sec_context(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_ccache_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_free_lucid_sec_context(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_set_allowable_enctypes(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gsskrb5_register_acceptor_identity(_:)",
        "doc://com.apple.gss/documentation/GSS/krb5_gss_register_acceptor_identity(_:)",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_copy_ccache(_:_:_:)"
      ],
      "title": "Identity and Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Contexts-and-Keys",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key_t",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata_t"
              ],
              "title": "Contexts and Keys"
            },
            {
              "anchor": "Identity-and-Settings",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_krb5_export_lucid_sec_context(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_ccache_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_free_lucid_sec_context(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_set_allowable_enctypes(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gsskrb5_register_acceptor_identity(_:)",
                "doc://com.apple.gss/documentation/GSS/krb5_gss_register_acceptor_identity(_:)",
                "doc://com.apple.gss/documentation/GSS/gss_krb5_copy_ccache(_:_:_:)"
              ],
              "title": "Identity and Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/token-management",
                "doc://com.apple.gss/documentation/GSS/message-protection"
              ],
              "title": "Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/title",
          "value": "gss_krb5_lucid_context_version_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_free_lucid_sec_context(_:_:)/title",
          "value": "gss_krb5_free_lucid_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_free_lucid_sec_context(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_free_lucid_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/title",
          "value": "gss_krb5_lucid_context_v1_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_copy_ccache(_:_:_:)/title",
          "value": "gss_krb5_copy_ccache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_copy_ccache(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_copy_ccache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1krb5_gss_register_acceptor_identity(_:)/title",
          "value": "krb5_gss_register_acceptor_identity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1krb5_gss_register_acceptor_identity(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "krb5_gss_register_acceptor_identity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/title",
          "value": "gss_krb5_rfc1964_keydata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gsskrb5_register_acceptor_identity(_:)/title",
          "value": "gsskrb5_register_acceptor_identity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gsskrb5_register_acceptor_identity(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gsskrb5_register_acceptor_identity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/title",
          "value": "gss_krb5_cfx_keydata_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_set_allowable_enctypes(_:_:_:_:)/title",
          "value": "gss_krb5_set_allowable_enctypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_set_allowable_enctypes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_set_allowable_enctypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)/title",
          "value": "gsskrb5_extract_authz_data_from_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gsskrb5_extract_authz_data_from_sec_context(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gsskrb5_extract_authz_data_from_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_export_lucid_sec_context(_:_:_:_:)/title",
          "value": "gss_krb5_export_lucid_sec_context"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_export_lucid_sec_context(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_export_lucid_sec_context"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/title",
          "value": "gss_krb5_lucid_key_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_ccache_name(_:_:_:)/title",
          "value": "gss_krb5_ccache_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_ccache_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_ccache_name"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/kerberos-implementation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/kerberos-implementation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
