{
  "abstract": [
    {
      "text": "The value indicates how to use the credential.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/kGSSCredentialUsage"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kGSSCredentialUsage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kGSSCredentialUsage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kGSSCredentialUsage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kGSSCredentialUsage"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kGSSCredentialUsage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set to one of the following: ",
              "type": "text"
            },
            {
              "code": "kGSS_C_INITIATE",
              "type": "codeVoice"
            },
            {
              "text": " (the default), ",
              "type": "text"
            },
            {
              "code": "kGSS_C_ACCEPT",
              "type": "codeVoice"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "kGSS_C_BOTH",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSCredentialUsage": {
      "abstract": [
        {
          "text": "The value indicates how to use the credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSCredentialUsage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSCredentialUsage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSCredentialUsage"
        }
      ],
      "role": "symbol",
      "title": "kGSSCredentialUsage",
      "type": "topic",
      "url": "/documentation/gss/kgsscredentialusage"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICAppIdentifierACL": {
      "abstract": [
        {
          "text": "The value is an array of strings containing the list of bundle ID prefixes allowed to access this credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICAppIdentifierACL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICAppIdentifierACL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICAppIdentifierACL"
        }
      ],
      "role": "symbol",
      "title": "kGSSICAppIdentifierACL",
      "type": "topic",
      "url": "/documentation/gss/kgssicappidentifieracl"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICAppleSourceApp": {
      "abstract": [
        {
          "text": "The value is a dictionary indicating attributes of the app that the credential is for (only applies to AppVPN).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICAppleSourceApp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICAppleSourceApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICAppleSourceApp"
        }
      ],
      "role": "symbol",
      "title": "kGSSICAppleSourceApp",
      "type": "topic",
      "url": "/documentation/gss/kgssicapplesourceapp"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICAuthenticationContext": {
      "abstract": [
        {
          "text": "The value indicates whether to allow the authentication UI or a context to pass a pre-evaluated authentication context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICAuthenticationContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICAuthenticationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICAuthenticationContext"
        }
      ],
      "role": "symbol",
      "title": "kGSSICAuthenticationContext",
      "type": "topic",
      "url": "/documentation/gss/kgssicauthenticationcontext"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICCertificate": {
      "abstract": [
        {
          "text": "The value that indicates a certificate to use with PKINIT/PKU2U.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICCertificate"
        }
      ],
      "role": "symbol",
      "title": "kGSSICCertificate",
      "type": "topic",
      "url": "/documentation/gss/kgssiccertificate"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICCreateNewCredential": {
      "abstract": [
        {
          "text": "The value is a Boolean that indicates whether the caller wants to create a new credential and not overwrite a credential with the same name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICCreateNewCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICCreateNewCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICCreateNewCredential"
        }
      ],
      "role": "symbol",
      "title": "kGSSICCreateNewCredential",
      "type": "topic",
      "url": "/documentation/gss/kgssiccreatenewcredential"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICKerberosCacheName": {
      "abstract": [
        {
          "text": "The value is a string indicating the name of the cache created for use with the Kerberos mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICKerberosCacheName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICKerberosCacheName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICKerberosCacheName"
        }
      ],
      "role": "symbol",
      "title": "kGSSICKerberosCacheName",
      "type": "topic",
      "url": "/documentation/gss/kgssickerberoscachename"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICLKDCHostname": {
      "abstract": [
        {
          "text": "The value is a string indicating the LKDC hostname.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICLKDCHostname"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICLKDCHostname",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICLKDCHostname"
        }
      ],
      "role": "symbol",
      "title": "kGSSICLKDCHostname",
      "type": "topic",
      "url": "/documentation/gss/kgssiclkdchostname"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICPassword": {
      "abstract": [
        {
          "text": "The value is a string that indicates a password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICPassword"
        }
      ],
      "role": "symbol",
      "title": "kGSSICPassword",
      "type": "topic",
      "url": "/documentation/gss/kgssicpassword"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICSiteName": {
      "abstract": [
        {
          "text": "The value is a string that is the name of site you are authenticating with, used for load balancing in DNS in Kerberos.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICSiteName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICSiteName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICSiteName"
        }
      ],
      "role": "symbol",
      "title": "kGSSICSiteName",
      "type": "topic",
      "url": "/documentation/gss/kgssicsitename"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredential": {
      "abstract": [
        {
          "text": "The value indicates whether to validate the credential with a trusted source to ensure there was no machine-in-the-middle attack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICVerifyCredential"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICVerifyCredential"
        }
      ],
      "role": "symbol",
      "title": "kGSSICVerifyCredential",
      "type": "topic",
      "url": "/documentation/gss/kgssicverifycredential"
    },
    "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredentialAcceptorName": {
      "abstract": [
        {
          "text": "The value is a string indicating the name of the acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kGSSICVerifyCredentialAcceptorName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredentialAcceptorName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kGSSICVerifyCredentialAcceptorName"
        }
      ],
      "role": "symbol",
      "title": "kGSSICVerifyCredentialAcceptorName",
      "type": "topic",
      "url": "/documentation/gss/kgssicverifycredentialacceptorname"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initial-Credential-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
        "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
        "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredential",
        "doc://com.apple.gss/documentation/GSS/kGSSICLKDCHostname",
        "doc://com.apple.gss/documentation/GSS/kGSSICKerberosCacheName",
        "doc://com.apple.gss/documentation/GSS/kGSSICSiteName",
        "doc://com.apple.gss/documentation/GSS/kGSSICAppIdentifierACL",
        "doc://com.apple.gss/documentation/GSS/kGSSICCreateNewCredential",
        "doc://com.apple.gss/documentation/GSS/kGSSICAppleSourceApp",
        "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredentialAcceptorName",
        "doc://com.apple.gss/documentation/GSS/kGSSICAuthenticationContext"
      ],
      "title": "Initial Credential Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kGSSCredentialUsage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSCredentialUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gss/documentation/GSS"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initial-Credential-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/kGSSICPassword",
                "doc://com.apple.gss/documentation/GSS/kGSSICCertificate",
                "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredential",
                "doc://com.apple.gss/documentation/GSS/kGSSICLKDCHostname",
                "doc://com.apple.gss/documentation/GSS/kGSSICKerberosCacheName",
                "doc://com.apple.gss/documentation/GSS/kGSSICSiteName",
                "doc://com.apple.gss/documentation/GSS/kGSSICAppIdentifierACL",
                "doc://com.apple.gss/documentation/GSS/kGSSICCreateNewCredential",
                "doc://com.apple.gss/documentation/GSS/kGSSICAppleSourceApp",
                "doc://com.apple.gss/documentation/GSS/kGSSICVerifyCredentialAcceptorName",
                "doc://com.apple.gss/documentation/GSS/kGSSICAuthenticationContext"
              ],
              "title": "Initial Credential Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kGSSCredentialUsage"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICLKDCHostname/title",
          "value": "kGSSICLKDCHostname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICLKDCHostname/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICLKDCHostname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCertificate/title",
          "value": "kGSSICCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCertificate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCreateNewCredential/title",
          "value": "kGSSICCreateNewCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICCreateNewCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICCreateNewCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICPassword/title",
          "value": "kGSSICPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSCredentialUsage/title",
          "value": "kGSSCredentialUsage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSCredentialUsage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSCredentialUsage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICKerberosCacheName/title",
          "value": "kGSSICKerberosCacheName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICKerberosCacheName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICKerberosCacheName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICVerifyCredential/title",
          "value": "kGSSICVerifyCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICVerifyCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICVerifyCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICSiteName/title",
          "value": "kGSSICSiteName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICSiteName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICSiteName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAppleSourceApp/title",
          "value": "kGSSICAppleSourceApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAppleSourceApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICAppleSourceApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAuthenticationContext/title",
          "value": "kGSSICAuthenticationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAuthenticationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICAuthenticationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAppIdentifierACL/title",
          "value": "kGSSICAppIdentifierACL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICAppIdentifierACL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICAppIdentifierACL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICVerifyCredentialAcceptorName/title",
          "value": "kGSSICVerifyCredentialAcceptorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1kGSSICVerifyCredentialAcceptorName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kGSSICVerifyCredentialAcceptorName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/kgsscredentialusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/kgsscredentialusage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
