{
  "abstract": [
    {
      "text": "Provide cryptographic protection to secure message integrity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/message-protection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Message Protection"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a token that contains the MIC for a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_get_mic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_get_mic"
        }
      ],
      "role": "symbol",
      "title": "gss_get_mic(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_get_mic(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_seal(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a secure message created by calculating and attaching a MIC to the input message, and then optionally encrypting it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_seal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_seal(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_seal"
        }
      ],
      "role": "symbol",
      "title": "gss_seal(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_seal(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_sign(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a digital signature for a message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_sign"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_sign(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_sign"
        }
      ],
      "role": "symbol",
      "title": "gss_sign(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_sign(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_unseal(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the original version of a secure message by optionally decrypting it and then extracting and verifying the attached MIC.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_unseal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_unseal(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_unseal"
        }
      ],
      "role": "symbol",
      "title": "gss_unseal(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_unseal(_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_unwrap(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the original version of a secure message by optionally decrypting it and then extracting and verifying the attached MIC.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_unwrap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_unwrap(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_unwrap"
        }
      ],
      "role": "symbol",
      "title": "gss_unwrap(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_unwrap(_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_verify(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates the integrity of a message’s digital signature.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_verify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_verify(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_verify"
        }
      ],
      "role": "symbol",
      "title": "gss_verify(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_verify(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns an indication of whether the integrity of a message is intact, given its MIC token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_verify_mic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_verify_mic"
        }
      ],
      "role": "symbol",
      "title": "gss_verify_mic(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_verify_mic(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_wrap(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a secure message created by calculating and attaching a MIC to the input message, and then optionally encrypting it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_wrap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_ctx_id_t",
          "text": "gss_ctx_id_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_qop_t",
          "text": "gss_qop_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_wrap(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_wrap"
        }
      ],
      "role": "symbol",
      "title": "gss_wrap(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_wrap(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/kerberos-implementation": {
      "abstract": [
        {
          "text": "Establish secure connections using the Kerberos implementation of GSS-API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kerberos-implementation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Kerberos Implementation",
      "type": "topic",
      "url": "/documentation/gss/kerberos-implementation"
    },
    "doc://com.apple.gss/documentation/GSS/token-management": {
      "abstract": [
        {
          "text": "Establish secure communication with tokens.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/token-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Token Management",
      "type": "topic",
      "url": "/documentation/gss/token-management"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/token-management",
        "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
      ],
      "title": "Messages"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Apply a Message Integrity Code (MIC) to a message to guarantee its integrity. Ensure confidentiality using encryption and decryption.",
          "type": "text"
        }
      ],
      "anchor": "Message-Wrapping-and-Verification",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_wrap(_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_unwrap(_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_sign(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_verify(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_seal(_:_:_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_unseal(_:_:_:_:_:_:)"
      ],
      "title": "Message Wrapping and Verification"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Apply a Message Integrity Code (MIC) to a message to guarantee its integrity. Ensure confidentiality using encryption and decryption.",
                  "type": "text"
                }
              ],
              "anchor": "Message-Wrapping-and-Verification",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_get_mic(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_verify_mic(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_wrap(_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_unwrap(_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_sign(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_verify(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_seal(_:_:_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_unseal(_:_:_:_:_:_:)"
              ],
              "title": "Message Wrapping and Verification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/token-management",
                "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
              ],
              "title": "Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify_mic(_:_:_:_:_:)/title",
          "value": "gss_verify_mic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify_mic(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_verify_mic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_seal(_:_:_:_:_:_:_:)/title",
          "value": "gss_seal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_seal(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_seal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify(_:_:_:_:_:)/title",
          "value": "gss_verify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_verify(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_verify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_wrap(_:_:_:_:_:_:_:)/title",
          "value": "gss_wrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_wrap(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_wrap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_sign(_:_:_:_:_:)/title",
          "value": "gss_sign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_sign(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_sign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_unseal(_:_:_:_:_:_:)/title",
          "value": "gss_unseal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_unseal(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_unseal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_get_mic(_:_:_:_:_:)/title",
          "value": "gss_get_mic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_get_mic(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_get_mic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_unwrap(_:_:_:_:_:_:)/title",
          "value": "gss_unwrap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_unwrap(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_unwrap"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/message-protection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/message-protection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
