{
  "abstract": [
    {
      "text": "Manage names for GSS-API principals such as a person, a machine, or an application.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/name-handling"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Name Handling"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a GSS name given a buffer and a type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSCreateName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSCreateName"
        }
      ],
      "role": "symbol",
      "title": "GSSCreateName(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gsscreatename(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)": {
      "abstract": [
        {
          "text": "Returns a string suitable for displaying to the user from a GSS name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSSNameCreateDisplayString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSSNameCreateDisplayString"
        }
      ],
      "role": "symbol",
      "title": "GSSNameCreateDisplayString(_:)",
      "type": "topic",
      "url": "/documentation/gss/gssnamecreatedisplaystring(_:)"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME": {
      "abstract": [
        {
          "text": "An empty name object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_ANONYMOUS": {
      "abstract": [
        {
          "text": "A name that refers to an anonymous principal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_ANONYMOUS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_ANONYMOUS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_ANONYMOUS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_anonymous"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_EXPORT_NAME": {
      "abstract": [
        {
          "text": "A name of the type exported by the export name function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_EXPORT_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_EXPORT_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_EXPORT_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_export_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE": {
      "abstract": [
        {
          "text": "A name used to specify services provided by host computers in the service/hostname format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_HOSTBASED_SERVICE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_HOSTBASED_SERVICE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_hostbased_service"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE_X": {
      "abstract": [
        {
          "text": "A service that is related to a particular host.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_HOSTBASED_SERVICE_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_HOSTBASED_SERVICE_X",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_hostbased_service_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_MACHINE_UID_NAME": {
      "abstract": [
        {
          "text": "A name used to specify a user on the local system by way of a numeric identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_MACHINE_UID_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_MACHINE_UID_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_MACHINE_UID_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_machine_uid_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_STRING_UID_NAME": {
      "abstract": [
        {
          "text": "A name that specifies a user on the local system by way of a string representation of a numeric identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_STRING_UID_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_STRING_UID_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_STRING_UID_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_string_uid_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME": {
      "abstract": [
        {
          "text": "A name that specifies a user on a local system in the username format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_USER_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_USER_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_user_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL": {
      "abstract": [
        {
          "text": "A name composed as a single-string representation of a Kerberos name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_PRINCIPAL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_PRINCIPAL",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_principal"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME": {
      "abstract": [
        {
          "text": "A name composed as a single-string representation of a Kerberos name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_PRINCIPAL_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_PRINCIPAL_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_principal_name"
    },
    "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Changes the password associated with a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_aapl_change_password"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_aapl_change_password"
        }
      ],
      "role": "symbol",
      "title": "gss_aapl_change_password(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_aapl_change_password(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts an internal name into a mechanism name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_canonicalize_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_canonicalize_name"
        }
      ],
      "role": "symbol",
      "title": "gss_canonicalize_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_canonicalize_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates if two names in internal name format refer to the same entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_compare_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_compare_name"
        }
      ],
      "role": "symbol",
      "title": "gss_compare_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_compare_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_name_t": {
      "abstract": [
        {
          "text": "A pointer to an immutable version of the opaque descriptor used to exchange name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_const_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_const_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a name in the internal format to an octet string and the associated name type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_display_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_display_name"
        }
      ],
      "role": "symbol",
      "title": "gss_display_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_display_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a copy of an internal name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_duplicate_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_duplicate_name"
        }
      ],
      "role": "symbol",
      "title": "gss_duplicate_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_duplicate_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_export_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a mechanism name in contiguous octet format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_export_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_export_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_export_name"
        }
      ],
      "role": "symbol",
      "title": "gss_export_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_export_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a name in contiguous octet format to the internal name format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_import_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_import_name"
        }
      ],
      "role": "symbol",
      "title": "gss_import_name(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_import_name(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a list of mechanisms that support a particular name type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_mechs_for_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_mechs_for_name"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_mechs_for_name(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_mechs_for_name(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns information about a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_set_t",
          "text": "gss_buffer_set_t"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_name"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_name(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_name(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a list of name types that a given mechanism supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_names_for_mech"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_names_for_mech"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_names_for_mech(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_names_for_mech(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_name_t": {
      "abstract": [
        {
          "text": "A pointer to an opaque type that you use to communicate name objects with GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_name_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_name_t"
        }
      ],
      "role": "symbol",
      "title": "gss_name_t",
      "type": "topic",
      "url": "/documentation/gss/gss_name_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)": {
      "abstract": [
        {
          "text": "Frees the resources associated with a name object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_name"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_name"
        }
      ],
      "role": "symbol",
      "title": "gss_release_name(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_name(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates if a given user is authorized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_userok"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_name_t",
          "text": "gss_name_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_userok"
        }
      ],
      "role": "symbol",
      "title": "gss_userok(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_userok(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/object-identifiers": {
      "abstract": [
        {
          "text": "Store security mechanisms, QOPs (Quality of Protection values), and name types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/object-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Object Identifiers",
      "type": "topic",
      "url": "/documentation/gss/object-identifiers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Names-and-Object-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/object-identifiers"
      ],
      "title": "Names and Object Identifiers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creation-and-Destruction",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_name_t",
        "doc://com.apple.gss/documentation/GSS/gss_const_name_t",
        "doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)",
        "doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"
      ],
      "title": "Creation and Destruction"
    },
    {
      "abstract": [
        {
          "text": "Create, compare, and examine names, the objects used to identify entities.",
          "type": "text"
        }
      ],
      "anchor": "Inquiries",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)"
      ],
      "title": "Inquiries"
    },
    {
      "anchor": "Imports-and-Exports",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_export_name(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)"
      ],
      "title": "Imports and Exports"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Name-Types",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_NO_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_USER_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_MACHINE_UID_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_STRING_UID_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE_X",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_HOSTBASED_SERVICE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_ANONYMOUS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_NT_EXPORT_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL"
              ],
              "title": "Name Types"
            },
            {
              "anchor": "Creation-and-Destruction",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_name_t",
                "doc://com.apple.gss/documentation/GSS/gss_const_name_t",
                "doc://com.apple.gss/documentation/GSS/gss_canonicalize_name(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/GSSNameCreateDisplayString(_:)",
                "doc://com.apple.gss/documentation/GSS/GSSCreateName(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_release_name(_:_:)"
              ],
              "title": "Creation and Destruction"
            },
            {
              "abstract": [
                {
                  "text": "Create, compare, and examine names, the objects used to identify entities.",
                  "type": "text"
                }
              ],
              "anchor": "Inquiries",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_display_name(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_compare_name(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_name(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_mechs_for_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_names_for_mech(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_duplicate_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_aapl_change_password(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_userok(_:_:)"
              ],
              "title": "Inquiries"
            },
            {
              "anchor": "Imports-and-Exports",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_export_name(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_import_name(_:_:_:_:)"
              ],
              "title": "Imports and Exports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Names-and-Object-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/object-identifiers"
              ],
              "title": "Names and Object Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSNameCreateDisplayString(_:)/title",
          "value": "GSSNameCreateDisplayString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSNameCreateDisplayString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSNameCreateDisplayString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/title",
          "value": "gss_inquire_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_name(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_export_name(_:_:_:)/title",
          "value": "gss_export_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_export_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_export_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/title",
          "value": "gss_userok"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_userok(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_userok"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_canonicalize_name(_:_:_:_:)/title",
          "value": "gss_canonicalize_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_canonicalize_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_canonicalize_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/title",
          "value": "gss_display_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_display_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/title",
          "value": "gss_inquire_mechs_for_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mechs_for_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_mechs_for_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/title",
          "value": "gss_aapl_change_password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_aapl_change_password(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_aapl_change_password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateName(_:_:_:)/title",
          "value": "GSSCreateName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSSCreateName(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSSCreateName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/title",
          "value": "gss_import_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_import_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_import_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/title",
          "value": "gss_release_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_name(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/title",
          "value": "gss_duplicate_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_name(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_duplicate_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/title",
          "value": "gss_const_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/title",
          "value": "gss_compare_name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_compare_name(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_compare_name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/title",
          "value": "gss_name_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_name_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_name_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/title",
          "value": "gss_inquire_names_for_mech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_names_for_mech(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_names_for_mech"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/name-handling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/name-handling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
