{
  "abstract": [
    {
      "text": "Store security mechanisms, QOPs (Quality of Protection values), and name types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/object-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Object Identifiers"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_QOP_DEFAULT": {
      "abstract": [
        {
          "text": "The default Quality of Protection for per-message services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_C_QOP_DEFAULT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_QOP_DEFAULT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_C_QOP_DEFAULT"
        }
      ],
      "role": "symbol",
      "title": "GSS_C_QOP_DEFAULT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_qop_default"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES": {
      "abstract": [
        {
          "text": "The Kerberos 5 Qualty of Service 56-bit DES encryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CONF_C_QOP_DES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CONF_C_QOP_DES"
        }
      ],
      "role": "symbol",
      "title": "GSS_KRB5_CONF_C_QOP_DES",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_conf_c_qop_des"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES3_KD": {
      "abstract": [
        {
          "text": "The Kerberos 5 Qualty of Service 168-bit DES3 encryption with key derivation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CONF_C_QOP_DES3_KD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES3_KD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CONF_C_QOP_DES3_KD"
        }
      ],
      "role": "symbol",
      "title": "GSS_KRB5_CONF_C_QOP_DES3_KD",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_conf_c_qop_des3_kd"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID": {
      "abstract": [
        {
          "text": "A pointer to the OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_desc": {
      "abstract": [
        {
          "text": "The OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct": {
      "abstract": [
        {
          "text": "The structure for an OID descriptor that exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set": {
      "abstract": [
        {
          "text": "A pointer to a descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc": {
      "abstract": [
        {
          "text": "The descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set_desc",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set_desc"
    },
    "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct": {
      "abstract": [
        {
          "text": "The structure for an OID set descriptor that manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc_struct"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_OID_set_desc_struct"
        }
      ],
      "role": "symbol",
      "title": "gss_OID_set_desc_struct",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_set_desc_struct"
    },
    "doc://com.apple.gss/documentation/GSS/gss_add_oid_set_member(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an object identifier into an OID set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_add_oid_set_member"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_add_oid_set_member(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_add_oid_set_member"
        }
      ],
      "role": "symbol",
      "title": "gss_add_oid_set_member(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_add_oid_set_member(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID": {
      "abstract": [
        {
          "text": "A pointer to an immutable OID descriptor exchanges object identifiers with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_const_OID_set": {
      "abstract": [
        {
          "text": "A pointer to an immutable descriptor manages an array of OID descriptors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_const_OID_set"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_const_OID_set"
        }
      ],
      "role": "symbol",
      "title": "gss_const_OID_set",
      "type": "topic",
      "url": "/documentation/gss/gss_const_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/gss_create_empty_oid_set(_:_:)": {
      "abstract": [
        {
          "text": "Allocates a new, empty set to hold object identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_create_empty_oid_set"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_create_empty_oid_set(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_create_empty_oid_set"
        }
      ],
      "role": "symbol",
      "title": "gss_create_empty_oid_set(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_create_empty_oid_set(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_duplicate_oid(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies an OID into a new object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_duplicate_oid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_duplicate_oid(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_duplicate_oid"
        }
      ],
      "role": "symbol",
      "title": "gss_duplicate_oid(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_duplicate_oid(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_oid_equal(_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates whether two object identifiers are the same.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_oid_equal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_oid_equal(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_oid_equal"
        }
      ],
      "role": "symbol",
      "title": "gss_oid_equal(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_equal(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_oid_to_str(_:_:_:)": {
      "abstract": [
        {
          "text": "Converts an OID object to a human-readable string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_oid_to_str"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_oid_to_str(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_oid_to_str"
        }
      ],
      "role": "symbol",
      "title": "gss_oid_to_str(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_oid_to_str(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_oid(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory associated with an object identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_oid"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_oid(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_oid"
        }
      ],
      "role": "symbol",
      "title": "gss_release_oid(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_oid(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)": {
      "abstract": [
        {
          "text": "Releases the memory associated with an OID set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_release_oid_set"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_release_oid_set"
        }
      ],
      "role": "symbol",
      "title": "gss_release_oid_set(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_release_oid_set(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_test_oid_set_member(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a flag that indicates if an OID is present in an OID set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_test_oid_set_member"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_test_oid_set_member(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_test_oid_set_member"
        }
      ],
      "role": "symbol",
      "title": "gss_test_oid_set_member(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_test_oid_set_member(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/name-handling": {
      "abstract": [
        {
          "text": "Manage names for GSS-API principals such as a person, a machine, or an application.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/name-handling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Name Handling",
      "type": "topic",
      "url": "/documentation/gss/name-handling"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Names-and-Object-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/name-handling"
      ],
      "title": "Names and Object Identifiers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Object-IDs",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_OID",
        "doc://com.apple.gss/documentation/GSS/gss_OID_set",
        "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
        "doc://com.apple.gss/documentation/GSS/gss_const_OID",
        "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
        "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
        "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
        "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct"
      ],
      "title": "Object IDs"
    },
    {
      "anchor": "Quality-of-Protection-Constants",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_C_QOP_DEFAULT",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES3_KD"
      ],
      "title": "Quality of Protection Constants"
    },
    {
      "anchor": "Creation-and-Release",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_create_empty_oid_set(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_add_oid_set_member(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_release_oid(_:_:)"
      ],
      "title": "Creation and Release"
    },
    {
      "anchor": "Conversion-and-Duplication",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_oid_to_str(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_test_oid_set_member(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_oid_equal(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_duplicate_oid(_:_:_:)"
      ],
      "title": "Conversion and Duplication"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Object-IDs",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_OID",
                "doc://com.apple.gss/documentation/GSS/gss_OID_set",
                "doc://com.apple.gss/documentation/GSS/gss_OID_desc",
                "doc://com.apple.gss/documentation/GSS/gss_const_OID",
                "doc://com.apple.gss/documentation/GSS/gss_const_OID_set",
                "doc://com.apple.gss/documentation/GSS/gss_OID_desc_struct",
                "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc",
                "doc://com.apple.gss/documentation/GSS/gss_OID_set_desc_struct"
              ],
              "title": "Object IDs"
            },
            {
              "anchor": "Quality-of-Protection-Constants",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_QOP_DEFAULT",
                "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES",
                "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CONF_C_QOP_DES3_KD"
              ],
              "title": "Quality of Protection Constants"
            },
            {
              "anchor": "Creation-and-Release",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_create_empty_oid_set(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_add_oid_set_member(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_release_oid_set(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_release_oid(_:_:)"
              ],
              "title": "Creation and Release"
            },
            {
              "anchor": "Conversion-and-Duplication",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_oid_to_str(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_test_oid_set_member(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_oid_equal(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_duplicate_oid(_:_:_:)"
              ],
              "title": "Conversion and Duplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Names-and-Object-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/name-handling"
              ],
              "title": "Names and Object Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_oid_to_str(_:_:_:)/title",
          "value": "gss_oid_to_str"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_oid_to_str(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_oid_to_str"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_create_empty_oid_set(_:_:)/title",
          "value": "gss_create_empty_oid_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_create_empty_oid_set(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_create_empty_oid_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_oid(_:_:_:)/title",
          "value": "gss_duplicate_oid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_duplicate_oid(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_duplicate_oid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/title",
          "value": "gss_OID_set_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_oid_equal(_:_:)/title",
          "value": "gss_oid_equal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_oid_equal(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_oid_equal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_QOP_DEFAULT/title",
          "value": "GSS_C_QOP_DEFAULT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_C_QOP_DEFAULT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_C_QOP_DEFAULT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/title",
          "value": "gss_OID_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_KRB5_CONF_C_QOP_DES/title",
          "value": "GSS_KRB5_CONF_C_QOP_DES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_KRB5_CONF_C_QOP_DES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_KRB5_CONF_C_QOP_DES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_add_oid_set_member(_:_:_:)/title",
          "value": "gss_add_oid_set_member"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_add_oid_set_member(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_add_oid_set_member"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_test_oid_set_member(_:_:_:_:)/title",
          "value": "gss_test_oid_set_member"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_test_oid_set_member(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_test_oid_set_member"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/title",
          "value": "gss_OID_set_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_set_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_set_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid_set(_:_:)/title",
          "value": "gss_release_oid_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid_set(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_oid_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/title",
          "value": "gss_OID_desc_struct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc_struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc_struct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/title",
          "value": "gss_const_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/title",
          "value": "gss_OID_desc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID_desc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID_desc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/title",
          "value": "gss_const_OID_set"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_const_OID_set/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_const_OID_set"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid(_:_:)/title",
          "value": "gss_release_oid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_release_oid(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_release_oid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/title",
          "value": "gss_OID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_OID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_OID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_KRB5_CONF_C_QOP_DES3_KD/title",
          "value": "GSS_KRB5_CONF_C_QOP_DES3_KD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_KRB5_CONF_C_QOP_DES3_KD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_KRB5_CONF_C_QOP_DES3_KD"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/object-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/object-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
