{
  "abstract": [
    {
      "text": "Provide a security mechanism for your implementation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/security-mechanisms"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Security Mechanisms"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on the attributes of a mechanism, see ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc5587",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_APPL_LKDC_SUPPORTED": {
      "abstract": [
        {
          "text": "Local KDC is supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_APPL_LKDC_SUPPORTED"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_APPL_LKDC_SUPPORTED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_APPL_LKDC_SUPPORTED",
      "type": "topic",
      "url": "/documentation/gss/gss_appl_lkdc_supported"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT": {
      "abstract": [
        {
          "text": "Support for authentication of initiator to acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_INIT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_INIT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_init"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_ANON": {
      "abstract": [
        {
          "text": "Anonymous support as a target principal name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_INIT_ANON"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_ANON",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_INIT_ANON",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_init_anon"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_INIT": {
      "abstract": [
        {
          "text": "Support for initial authentication of initiator to acceptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_INIT_INIT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_INIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_INIT_INIT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_init_init"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG": {
      "abstract": [
        {
          "text": "Support for authentication of acceptor to initiator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_TARG"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_TARG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_targ"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_ANON": {
      "abstract": [
        {
          "text": "Anonymous support as a target principal name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_TARG_ANON"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_ANON",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_TARG_ANON",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_targ_anon"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_INIT": {
      "abstract": [
        {
          "text": "Support for initial authentication of acceptor to initiator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_AUTH_TARG_INIT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_INIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_AUTH_TARG_INIT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_auth_targ_init"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CBINDINGS": {
      "abstract": [
        {
          "text": "Support for channel bindings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_CBINDINGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CBINDINGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_CBINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_cbindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_COMPRESS": {
      "abstract": [
        {
          "text": "Support for compression of data inputs to the wrap function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_COMPRESS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_COMPRESS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_COMPRESS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_compress"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CONF_PROT": {
      "abstract": [
        {
          "text": "Support for per-message confidentiality protection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_CONF_PROT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CONF_PROT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_CONF_PROT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_conf_prot"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CTX_TRANS": {
      "abstract": [
        {
          "text": "Support for security context importing and exporting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_CTX_TRANS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CTX_TRANS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_CTX_TRANS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_ctx_trans"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DELEG_CRED": {
      "abstract": [
        {
          "text": "Support for credential delegation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_DELEG_CRED"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DELEG_CRED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_DELEG_CRED",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_deleg_cred"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DEPRECATED": {
      "abstract": [
        {
          "text": "A mechanism that is no longer used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_DEPRECATED",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_deprecated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_INTEG_PROT": {
      "abstract": [
        {
          "text": "Support for per-message integrity protection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_INTEG_PROT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_INTEG_PROT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_INTEG_PROT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_integ_prot"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_ITOK_FRAMED": {
      "abstract": [
        {
          "text": "The given mechanism’s initial context tokens are properly framed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_ITOK_FRAMED"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_ITOK_FRAMED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_ITOK_FRAMED",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_itok_framed"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_COMPOSITE": {
      "abstract": [
        {
          "text": "A mechanism that is a composite of other mechanisms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_COMPOSITE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_COMPOSITE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_COMPOSITE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_composite"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_CONCRETE": {
      "abstract": [
        {
          "text": "A mechanism that is neither a psuedo-mechanism nor a composite mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_CONCRETE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_CONCRETE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_CONCRETE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_concrete"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_DESCRIPTION": {
      "abstract": [
        {
          "text": "The long description of the mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_DESCRIPTION"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_DESCRIPTION",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_DESCRIPTION",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_description"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_GLUE": {
      "abstract": [
        {
          "text": "An OID that is for the GSS-API rather than for a mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_GLUE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_GLUE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_GLUE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_glue"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NAME": {
      "abstract": [
        {
          "text": "The name of the GSS-API mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NEGO": {
      "abstract": [
        {
          "text": "A mechanism that negotiates other mechanisms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_NEGO"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NEGO",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_NEGO",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_nego"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_PSEUDO": {
      "abstract": [
        {
          "text": "A pseudo-mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MECH_PSEUDO"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_PSEUDO",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MECH_PSEUDO",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mech_pseudo"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MIC": {
      "abstract": [
        {
          "text": "Support for Message Integrity Code (MIC) tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_MIC"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MIC",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_MIC",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_mic"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_DFLT_MECH": {
      "abstract": [
        {
          "text": "A mechanism that is not suitable for use as a default mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_NOT_DFLT_MECH"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_DFLT_MECH",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_NOT_DFLT_MECH",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_not_dflt_mech"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_MECH": {
      "abstract": [
        {
          "text": "A known OID that is neither a GSS-API mechanism nor an identifier of the GSS-API itself.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_NOT_MECH"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_MECH",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_NOT_MECH",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_not_mech"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_OOS_DET": {
      "abstract": [
        {
          "text": "Support for out-of-sequence detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_OOS_DET"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_OOS_DET",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_OOS_DET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_oos_det"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PFS": {
      "abstract": [
        {
          "text": "Support for perfect forward security.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_PFS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PFS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_PFS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_pfs"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PROT_READY": {
      "abstract": [
        {
          "text": "Support for per-message protection prior to full context establishment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_PROT_READY"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PROT_READY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_PROT_READY",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_prot_ready"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_REPLAY_DET": {
      "abstract": [
        {
          "text": "Support for replay detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_REPLAY_DET"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_REPLAY_DET",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_REPLAY_DET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_replay_det"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_SASL_MECH_NAME": {
      "abstract": [
        {
          "text": "The name of the SASL mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_SASL_MECH_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_SASL_MECH_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_SASL_MECH_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_sasl_mech_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_MA_WRAP": {
      "abstract": [
        {
          "text": "Support for WRAP tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_MA_WRAP"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_MA_WRAP",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_MA_WRAP",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ma_wrap"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IAKERB_MECHANISM": {
      "abstract": [
        {
          "text": "The Initial and Pass Through Authentication Using Kerberos V5 and the GSS-API Mechanism (IAKERB).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_IAKERB_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IAKERB_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_IAKERB_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_iakerb_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM": {
      "abstract": [
        {
          "text": "The Kerberos Version 5 Mechanism (KRB5).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_MECHANISM": {
      "abstract": [
        {
          "text": "The Microsoft Net Logon Mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NETLOGON_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NETLOGON_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_netlogon_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_NT_NETBIOS_DNS_NAME": {
      "abstract": [
        {
          "text": "The Netlogon NetBIOS DNS name value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NETLOGON_NT_NETBIOS_DNS_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_NT_NETBIOS_DNS_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NETLOGON_NT_NETBIOS_DNS_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_netlogon_nt_netbios_dns_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SESSION_KEY_X": {
      "abstract": [
        {
          "text": "The Netlogon set session key value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NETLOGON_SET_SESSION_KEY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SESSION_KEY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NETLOGON_SET_SESSION_KEY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_netlogon_set_session_key_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SIGN_ALGORITHM_X": {
      "abstract": [
        {
          "text": "The Netlogon algorithm key value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NETLOGON_SET_SIGN_ALGORITHM_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SIGN_ALGORITHM_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NETLOGON_SET_SIGN_ALGORITHM_X",
      "type": "topic",
      "url": "/documentation/gss/gss_netlogon_set_sign_algorithm_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM": {
      "abstract": [
        {
          "text": "The Microsoft NT LAN Manager Mechanism (NTLM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NTLM_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NTLM_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_ntlm_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_PKU2U_MECHANISM": {
      "abstract": [
        {
          "text": "The Public Key Cryptography Based User-to-User Mechanism (PKU2U).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_PKU2U_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_PKU2U_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_PKU2U_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_pku2u_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_SASL_DIGEST_MD5_MECHANISM": {
      "abstract": [
        {
          "text": "The Simple Authentication and Security Layer (SASL) Mechanism with Digest-MD5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_SASL_DIGEST_MD5_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_SASL_DIGEST_MD5_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_SASL_DIGEST_MD5_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_sasl_digest_md5_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_SCRAM_MECHANISM": {
      "abstract": [
        {
          "text": "The Salted Challenge Response Authentication Mechanism (SCRAM).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_SCRAM_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_SCRAM_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_SCRAM_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_scram_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_SPNEGO_MECHANISM": {
      "abstract": [
        {
          "text": "The Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_SPNEGO_MECHANISM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_SPNEGO_MECHANISM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_SPNEGO_MECHANISM",
      "type": "topic",
      "url": "/documentation/gss/gss_spnego_mechanism"
    },
    "doc://com.apple.gss/documentation/GSS/credential-management": {
      "abstract": [
        {
          "text": "Securely establish connections between endpoints.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/credential-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Credential Management",
      "type": "topic",
      "url": "/documentation/gss/credential-management"
    },
    "doc://com.apple.gss/documentation/GSS/gss_display_mech_attr(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a human-readable name and description of a mechanism attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_display_mech_attr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_display_mech_attr(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_display_mech_attr"
        }
      ],
      "role": "symbol",
      "title": "gss_display_mech_attr(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_display_mech_attr(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)": {
      "abstract": [
        {
          "text": "Returns the list of supported underlying security mechanisms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs"
        }
      ],
      "role": "symbol",
      "title": "gss_indicate_mechs(_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_indicate_mechs(_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs_by_attrs(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the set of mechanisms that fulfill the given criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs_by_attrs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID_set",
          "text": "gss_const_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID_set",
          "text": "gss_const_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID_set",
          "text": "gss_const_OID_set"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs_by_attrs(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_indicate_mechs_by_attrs"
        }
      ],
      "role": "symbol",
      "title": "gss_indicate_mechs_by_attrs(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_indicate_mechs_by_attrs(_:_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_attrs_for_mech(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the supported attributes for one or all mechanisms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_attrs_for_mech"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID_set",
          "text": "gss_OID_set"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_attrs_for_mech(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_attrs_for_mech"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_attrs_for_mech(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_attrs_for_mech(_:_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_mech_for_saslname(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the GSS-API mechanism identifier for a given Simple Authentication and Security Layer (SASL) protocol name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_mech_for_saslname"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_mech_for_saslname(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_mech_for_saslname"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_mech_for_saslname(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_mech_for_saslname(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_inquire_saslname_for_mech(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the Simple Authentication and Security Layer (SASL) protocol name for a given GSS-API mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_inquire_saslname_for_mech"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_OID",
          "text": "gss_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_inquire_saslname_for_mech(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_inquire_saslname_for_mech"
        }
      ],
      "role": "symbol",
      "title": "gss_inquire_saslname_for_mech(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_inquire_saslname_for_mech(_:_:_:_:_:)"
    },
    "https://tools.ietf.org/html/rfc5587": {
      "identifier": "https://tools.ietf.org/html/rfc5587",
      "title": "RFC 5587",
      "titleInlineContent": [
        {
          "text": "RFC 5587",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc5587"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/credential-management"
      ],
      "title": "Credentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Queries",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs_by_attrs(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_display_mech_attr(_:_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_attrs_for_mech(_:_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_mech_for_saslname(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_inquire_saslname_for_mech(_:_:_:_:_:)"
      ],
      "title": "Queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "The underlying security mechanisms that GSS-API may use to provide secure communications.",
                  "type": "text"
                }
              ],
              "anchor": "Standard-Mechanisms",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_KRB5_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_NTLM_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_IAKERB_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_PKU2U_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_SPNEGO_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_SCRAM_MECHANISM"
              ],
              "title": "Standard Mechanisms"
            },
            {
              "anchor": "Heimdal-Mechanisms",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_SASL_DIGEST_MD5_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_MECHANISM",
                "doc://com.apple.gss/documentation/GSS/GSS_APPL_LKDC_SUPPORTED"
              ],
              "title": "Heimdal Mechanisms"
            },
            {
              "anchor": "Netlogon-Set",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SESSION_KEY_X",
                "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_SET_SIGN_ALGORITHM_X",
                "doc://com.apple.gss/documentation/GSS/GSS_NETLOGON_NT_NETBIOS_DNS_NAME"
              ],
              "title": "Netlogon Set"
            },
            {
              "anchor": "Mechanisms-and-Authentication",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_CONCRETE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_PSEUDO",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_COMPOSITE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NEGO",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_GLUE",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_MECH",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DEPRECATED",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_NOT_DFLT_MECH",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_ITOK_FRAMED",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_INIT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_INIT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_INIT_ANON",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_AUTH_TARG_ANON",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_DELEG_CRED",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_INTEG_PROT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CONF_PROT",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MIC",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_WRAP",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PROT_READY",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_REPLAY_DET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_OOS_DET",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CBINDINGS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_PFS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_COMPRESS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_CTX_TRANS",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_SASL_MECH_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_NAME",
                "doc://com.apple.gss/documentation/GSS/GSS_C_MA_MECH_DESCRIPTION"
              ],
              "title": "Mechanisms and Authentication"
            },
            {
              "anchor": "Queries",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs(_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_indicate_mechs_by_attrs(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_display_mech_attr(_:_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_attrs_for_mech(_:_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_mech_for_saslname(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_inquire_saslname_for_mech(_:_:_:_:_:)"
              ],
              "title": "Queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/credential-management"
              ],
              "title": "Credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs_by_attrs(_:_:_:_:_:)/title",
          "value": "gss_indicate_mechs_by_attrs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs_by_attrs(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_indicate_mechs_by_attrs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_attrs_for_mech(_:_:_:_:)/title",
          "value": "gss_inquire_attrs_for_mech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_attrs_for_mech(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_attrs_for_mech"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs(_:_:)/title",
          "value": "gss_indicate_mechs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_indicate_mechs(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_indicate_mechs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mech_for_saslname(_:_:_:)/title",
          "value": "gss_inquire_mech_for_saslname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_mech_for_saslname(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_mech_for_saslname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_mech_attr(_:_:_:_:_:)/title",
          "value": "gss_display_mech_attr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_display_mech_attr(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_display_mech_attr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_saslname_for_mech(_:_:_:_:_:)/title",
          "value": "gss_inquire_saslname_for_mech"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_inquire_saslname_for_mech(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_inquire_saslname_for_mech"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/security-mechanisms"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/security-mechanisms"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
