{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gss/documentation/GSS/structures-and-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Structures and macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSSKRB5_FUNCTION_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSSKRB5_FUNCTION_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSSKRB5_FUNCTION_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSSKRB5_FUNCTION_DEPRECATED",
      "type": "topic",
      "url": "/documentation/gss/gsskrb5_function_deprecated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_ATTR_LOCAL_LOGIN_USER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_ATTR_LOCAL_LOGIN_USER"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_ATTR_LOCAL_LOGIN_USER",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_ATTR_LOCAL_LOGIN_USER",
      "type": "topic",
      "url": "/documentation/gss/gss_c_attr_local_login_user"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_DIAG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_DIAG"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_DIAG",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_DIAG",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_diag"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_GET_DEFAULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_GET_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_GET_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_GET_DEFAULT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_get_default"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_RENEW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_RENEW"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_RENEW",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_RENEW",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_renew"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SET_DEFAULT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_SET_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SET_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_SET_DEFAULT",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_set_default"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_VALIDATE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CRED_VALIDATE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_VALIDATE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CRED_VALIDATE",
      "type": "topic",
      "url": "/documentation/gss/gss_c_cred_validate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_CTX_PFS_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_CTX_PFS_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_CTX_PFS_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_CTX_PFS_X",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ctx_pfs_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_SSPI_SESSION_KEY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_INQ_SSPI_SESSION_KEY"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_SSPI_SESSION_KEY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_INQ_SSPI_SESSION_KEY",
      "type": "topic",
      "url": "/documentation/gss/gss_c_inq_sspi_session_key"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_WIN2K_PAC_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_INQ_WIN2K_PAC_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_WIN2K_PAC_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_INQ_WIN2K_PAC_X",
      "type": "topic",
      "url": "/documentation/gss/gss_c_inq_win2k_pac_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID_SET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NO_OID_SET"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID_SET",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NO_OID_SET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_no_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_FORCE_V1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_FORCE_V1"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_FORCE_V1",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_FORCE_V1",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_force_v1"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_GUEST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_GUEST"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_GUEST",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_GUEST",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_guest"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_RESET_KEYS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_RESET_KEYS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_RESET_KEYS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_RESET_KEYS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_reset_keys"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SESSION_KEY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_SESSION_KEY"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SESSION_KEY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_SESSION_KEY",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_session_key"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_CHANNELBINDINGS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_SUPPORT_CHANNELBINDINGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_CHANNELBINDINGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_SUPPORT_CHANNELBINDINGS",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_support_channelbindings"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_LM2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_SUPPORT_LM2"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_LM2",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_SUPPORT_LM2",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_support_lm2"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_V1"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V1",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_V1",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_v1"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NTLM_V2"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V2",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NTLM_V2",
      "type": "topic",
      "url": "/documentation/gss/gss_c_ntlm_v2"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_DN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_DN"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_DN",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_DN",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_dn"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_NTLM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_NTLM"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_NTLM",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_NTLM",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_ntlm"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NT_UUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NT_UUID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NT_UUID",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NT_UUID",
      "type": "topic",
      "url": "/documentation/gss/gss_c_nt_uuid"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NULL_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NULL_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_c_null_oid"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID_SET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_NULL_OID_SET"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID_SET",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_NULL_OID_SET",
      "type": "topic",
      "url": "/documentation/gss/gss_c_null_oid_set"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_C_PEER_HAS_UPDATED_SPNEGO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_C_PEER_HAS_UPDATED_SPNEGO"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_C_PEER_HAS_UPDATED_SPNEGO",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_C_PEER_HAS_UPDATED_SPNEGO",
      "type": "topic",
      "url": "/documentation/gss/gss_c_peer_has_updated_spnego"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAGS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAGS"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAGS",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_FLAGS",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_flags"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CCACHE_NAME_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CCACHE_NAME_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CCACHE_NAME_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_CCACHE_NAME_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_ccache_name_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COMPAT_DES3_MIC_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_COMPAT_DES3_MIC_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COMPAT_DES3_MIC_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_COMPAT_DES3_MIC_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_compat_des3_mic_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COPY_CCACHE_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_COPY_CCACHE_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COPY_CCACHE_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_COPY_CCACHE_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_copy_ccache_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CRED_NO_CI_FLAGS_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_CRED_NO_CI_FLAGS_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CRED_NO_CI_FLAGS_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_CRED_NO_CI_FLAGS_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_cred_no_ci_flags_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_V1_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_EXPORT_LUCID_CONTEXT_V1_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_V1_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_EXPORT_LUCID_CONTEXT_V1_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_export_lucid_context_v1_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_EXPORT_LUCID_CONTEXT_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_EXPORT_LUCID_CONTEXT_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_export_lucid_context_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_extract_authz_data_from_sec_context_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_ACCEPTOR_SUBKEY_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_ACCEPTOR_SUBKEY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_ACCEPTOR_SUBKEY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_ACCEPTOR_SUBKEY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_acceptor_subkey_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_AUTHTIME_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_AUTHTIME_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_AUTHTIME_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_AUTHTIME_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_authtime_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_INITIATOR_SUBKEY_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_INITIATOR_SUBKEY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_INITIATOR_SUBKEY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_INITIATOR_SUBKEY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_initiator_subkey_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SERVICE_KEYBLOCK_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_SERVICE_KEYBLOCK_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SERVICE_KEYBLOCK_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_SERVICE_KEYBLOCK_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_service_keyblock_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SUBKEY_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_SUBKEY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SUBKEY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_SUBKEY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_subkey_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TIME_OFFSET_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_TIME_OFFSET_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TIME_OFFSET_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_TIME_OFFSET_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_time_offset_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TKT_FLAGS_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_GET_TKT_FLAGS_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TKT_FLAGS_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_GET_TKT_FLAGS_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_get_tkt_flags_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_IMPORT_CRED_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_IMPORT_CRED_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_IMPORT_CRED_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_IMPORT_CRED_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_import_cred_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_MACHINE_UID_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_MACHINE_UID_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_MACHINE_UID_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_MACHINE_UID_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_machine_uid_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME_REFERRAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_PRINCIPAL_NAME_REFERRAL"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME_REFERRAL",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_PRINCIPAL_NAME_REFERRAL",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_principal_name_referral"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_STRING_UID_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_STRING_UID_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_STRING_UID_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_STRING_UID_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_string_uid_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_USER_NAME": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_NT_USER_NAME"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_USER_NAME",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_NT_USER_NAME",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_user_name"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_PLUGIN_REGISTER_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_PLUGIN_REGISTER_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_PLUGIN_REGISTER_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_PLUGIN_REGISTER_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_plugin_register_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_REGISTER_ACCEPTOR_IDENTITY_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_REGISTER_ACCEPTOR_IDENTITY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_REGISTER_ACCEPTOR_IDENTITY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_REGISTER_ACCEPTOR_IDENTITY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_register_acceptor_identity_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SEND_TO_KDC_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_SEND_TO_KDC_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SEND_TO_KDC_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_SEND_TO_KDC_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_send_to_kdc_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_ALLOWABLE_ENCTYPES_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_SET_ALLOWABLE_ENCTYPES_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_ALLOWABLE_ENCTYPES_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_SET_ALLOWABLE_ENCTYPES_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_set_allowable_enctypes_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DEFAULT_REALM_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_SET_DEFAULT_REALM_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DEFAULT_REALM_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_SET_DEFAULT_REALM_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_set_default_realm_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DNS_CANONICALIZE_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_SET_DNS_CANONICALIZE_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DNS_CANONICALIZE_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_SET_DNS_CANONICALIZE_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_set_dns_canonicalize_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_TIME_OFFSET_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_KRB5_SET_TIME_OFFSET_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_TIME_OFFSET_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_KRB5_SET_TIME_OFFSET_X",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_set_time_offset_x"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_NTLM_GET_SESSION_KEY_X": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GSS_NTLM_GET_SESSION_KEY_X"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_NTLM_GET_SESSION_KEY_X",
      "kind": "symbol",
      "role": "symbol",
      "title": "GSS_NTLM_GET_SESSION_KEY_X",
      "type": "topic",
      "url": "/documentation/gss/gss_ntlm_get_session_key_x"
    },
    "doc://com.apple.gss/documentation/GSS/HEIMDAL_PRINTF_ATTRIBUTE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "HEIMDAL_PRINTF_ATTRIBUTE"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/HEIMDAL_PRINTF_ATTRIBUTE",
      "kind": "symbol",
      "role": "symbol",
      "title": "HEIMDAL_PRINTF_ATTRIBUTE",
      "type": "topic",
      "url": "/documentation/gss/heimdal_printf_attribute"
    },
    "doc://com.apple.gss/documentation/GSS/gss_iter_OID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_iter_OID"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_iter_OID",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_iter_OID",
      "type": "topic",
      "url": "/documentation/gss/gss_iter_oid"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_cfx_keydata"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_cfx_keydata",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_cfx_keydata"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_v1"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_v1",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_v1"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_context_version"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_context_version",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_context_version"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_lucid_key"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_lucid_key",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_lucid_key"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_nt_general_name": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_krb5_nt_general_name"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_nt_general_name",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_krb5_nt_general_name",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_nt_general_name"
    },
    "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_krb5_rfc1964_keydata"
        }
      ],
      "role": "symbol",
      "title": "gss_krb5_rfc1964_keydata",
      "type": "topic",
      "url": "/documentation/gss/gss_krb5_rfc1964_keydata"
    },
    "doc://com.apple.gss/documentation/GSS/gss_mech_krb5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_mech_krb5"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_mech_krb5",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_mech_krb5",
      "type": "topic",
      "url": "/documentation/gss/gss_mech_krb5"
    },
    "doc://com.apple.gss/documentation/GSS/gss_mech_spnego": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "gss_mech_spnego"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_mech_spnego",
      "kind": "symbol",
      "role": "symbol",
      "title": "gss_mech_spnego",
      "type": "topic",
      "url": "/documentation/gss/gss_mech_spnego"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_krb5_cfx_keydata",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_v1",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_context_version",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_lucid_key",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_rfc1964_keydata"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSSKRB5_FUNCTION_DEPRECATED",
        "doc://com.apple.gss/documentation/GSS/GSS_C_ATTR_LOCAL_LOGIN_USER",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_DIAG",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_GET_DEFAULT",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_RENEW",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_SET_DEFAULT",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CRED_VALIDATE",
        "doc://com.apple.gss/documentation/GSS/GSS_C_CTX_PFS_X",
        "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_SSPI_SESSION_KEY",
        "doc://com.apple.gss/documentation/GSS/GSS_C_INQ_WIN2K_PAC_X",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NO_OID_SET",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_FORCE_V1",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_GUEST",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_RESET_KEYS",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SESSION_KEY",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_CHANNELBINDINGS",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_SUPPORT_LM2",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V1",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NTLM_V2",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NT_DN",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NT_NTLM",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NT_UUID",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID",
        "doc://com.apple.gss/documentation/GSS/GSS_C_NULL_OID_SET",
        "doc://com.apple.gss/documentation/GSS/GSS_C_PEER_HAS_UPDATED_SPNEGO",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAGS",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CCACHE_NAME_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COMPAT_DES3_MIC_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_COPY_CCACHE_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_CRED_NO_CI_FLAGS_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_V1_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXPORT_LUCID_CONTEXT_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_EXTRACT_AUTHZ_DATA_FROM_SEC_CONTEXT_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_ACCEPTOR_SUBKEY_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_AUTHTIME_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_INITIATOR_SUBKEY_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SERVICE_KEYBLOCK_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_SUBKEY_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TIME_OFFSET_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_GET_TKT_FLAGS_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_IMPORT_CRED_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_MACHINE_UID_NAME",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_PRINCIPAL_NAME_REFERRAL",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_STRING_UID_NAME",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_NT_USER_NAME",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_PLUGIN_REGISTER_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_REGISTER_ACCEPTOR_IDENTITY_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SEND_TO_KDC_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_ALLOWABLE_ENCTYPES_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DEFAULT_REALM_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_DNS_CANONICALIZE_X",
        "doc://com.apple.gss/documentation/GSS/GSS_KRB5_SET_TIME_OFFSET_X",
        "doc://com.apple.gss/documentation/GSS/GSS_NTLM_GET_SESSION_KEY_X",
        "doc://com.apple.gss/documentation/GSS/HEIMDAL_PRINTF_ATTRIBUTE",
        "doc://com.apple.gss/documentation/GSS/gss_iter_OID",
        "doc://com.apple.gss/documentation/GSS/gss_krb5_nt_general_name",
        "doc://com.apple.gss/documentation/GSS/gss_mech_krb5",
        "doc://com.apple.gss/documentation/GSS/gss_mech_spnego"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/title",
          "value": "gss_krb5_lucid_context_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_v1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/title",
          "value": "gss_krb5_lucid_key"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_key/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_key"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/title",
          "value": "gss_krb5_cfx_keydata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_cfx_keydata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_cfx_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/title",
          "value": "gss_krb5_rfc1964_keydata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_rfc1964_keydata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_rfc1964_keydata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/title",
          "value": "gss_krb5_lucid_context_version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_krb5_lucid_context_version/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_krb5_lucid_context_version"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/structures-and-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
