{
  "abstract": [
    {
      "text": "Establish secure communication with tokens.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gss/documentation/GSS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gss/documentation/GSS/token-management"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "GSS"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Token Management"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The basic unit of currency in the GSS-API is the token. Applications using the GSS-API communicate with each other by using tokens, both for exchanging data and for making security arrangements. Tokens are declared as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data types and are opaque to applications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gss/documentation/GSS": {
      "abstract": [
        {
          "text": "Conduct secure, authenticated network transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS",
      "kind": "symbol",
      "role": "collection",
      "title": "GSS",
      "type": "topic",
      "url": "/documentation/gss"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE": {
      "abstract": [
        {
          "text": "GSS should perform the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_FLAG_ALLOCATE",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_flag_allocate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED": {
      "abstract": [
        {
          "text": "The caller should free the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_FLAG_ALLOCATED",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_flag_allocated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA": {
      "abstract": [
        {
          "text": "The buffer type is packet data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_DATA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_DATA"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_DATA",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_data"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY": {
      "abstract": [
        {
          "text": "The buffer type is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_EMPTY",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_empty"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE": {
      "abstract": [
        {
          "text": "GSS should perform the allocation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_allocate"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED": {
      "abstract": [
        {
          "text": "The caller should free the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_allocated"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK": {
      "abstract": [
        {
          "text": "The buffer type is a flag mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_FLAG_MASK",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_flag_mask"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER": {
      "abstract": [
        {
          "text": "The buffer type is a mechanism header.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_HEADER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_HEADER"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_HEADER",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_header"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS": {
      "abstract": [
        {
          "text": "The buffer contains mechanism-specific parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_mech_params"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING": {
      "abstract": [
        {
          "text": "The buffer contains padding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_PADDING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_PADDING"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_PADDING",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_padding"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY": {
      "abstract": [
        {
          "text": "The buffer contains sign-only packet data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_sign_only"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM": {
      "abstract": [
        {
          "text": "The buffer contains a complete wrap token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_STREAM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_STREAM"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_STREAM",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_stream"
    },
    "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER": {
      "abstract": [
        {
          "text": "The buffer contains a mechanism trailer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
        }
      ],
      "role": "symbol",
      "title": "GSS_IOV_BUFFER_TYPE_TRAILER",
      "type": "topic",
      "url": "/documentation/gss/gss_iov_buffer_type_trailer"
    },
    "doc://com.apple.gss/documentation/GSS/gss_buffer_t": {
      "abstract": [
        {
          "text": "A pointer to a buffer descriptor that you use to exchange octet streams with many GSS-API functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_buffer_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_buffer_t"
        }
      ],
      "role": "symbol",
      "title": "gss_buffer_t",
      "type": "topic",
      "url": "/documentation/gss/gss_buffer_t"
    },
    "doc://com.apple.gss/documentation/GSS/gss_decapsulate_token(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a token encapsulated in a buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_decapsulate_token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_buffer_t",
          "text": "gss_const_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_decapsulate_token(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_decapsulate_token"
        }
      ],
      "role": "symbol",
      "title": "gss_decapsulate_token(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_decapsulate_token(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/gss_encapsulate_token(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a buffer encapsulating the given token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gss_encapsulate_token"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_buffer_t",
          "text": "gss_const_buffer_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_const_OID",
          "text": "gss_const_OID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gss_buffer_t",
          "text": "gss_buffer_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OM_uint32",
          "text": "OM_uint32"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/gss_encapsulate_token(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gss_encapsulate_token"
        }
      ],
      "role": "symbol",
      "title": "gss_encapsulate_token(_:_:_:)",
      "type": "topic",
      "url": "/documentation/gss/gss_encapsulate_token(_:_:_:)"
    },
    "doc://com.apple.gss/documentation/GSS/kerberos-implementation": {
      "abstract": [
        {
          "text": "Establish secure connections using the Kerberos implementation of GSS-API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/kerberos-implementation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Kerberos Implementation",
      "type": "topic",
      "url": "/documentation/gss/kerberos-implementation"
    },
    "doc://com.apple.gss/documentation/GSS/message-protection": {
      "abstract": [
        {
          "text": "Provide cryptographic protection to secure message integrity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gss/documentation/GSS/message-protection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Protection",
      "type": "topic",
      "url": "/documentation/gss/message-protection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/message-protection",
        "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
      ],
      "title": "Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Buffer-Flags",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM",
        "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER"
      ],
      "title": "Buffer Flags"
    },
    {
      "abstract": [
        {
          "text": "Transfer tokens between peers by encapsulating and decapsulating them.",
          "type": "text"
        }
      ],
      "anchor": "Encapsulation-and-Decapsulation",
      "identifiers": [
        "doc://com.apple.gss/documentation/GSS/gss_encapsulate_token(_:_:_:)",
        "doc://com.apple.gss/documentation/GSS/gss_decapsulate_token(_:_:_:)"
      ],
      "title": "Encapsulation and Decapsulation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Buffer-Flags",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATE",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_FLAG_ALLOCATED",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_DATA",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_EMPTY",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_FLAG_MASK",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_HEADER",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_MECH_PARAMS",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_PADDING",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_SIGN_ONLY",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_STREAM",
                "doc://com.apple.gss/documentation/GSS/GSS_IOV_BUFFER_TYPE_TRAILER"
              ],
              "title": "Buffer Flags"
            },
            {
              "abstract": [
                {
                  "text": "Transfer tokens between peers by encapsulating and decapsulating them.",
                  "type": "text"
                }
              ],
              "anchor": "Encapsulation-and-Decapsulation",
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/gss_encapsulate_token(_:_:_:)",
                "doc://com.apple.gss/documentation/GSS/gss_decapsulate_token(_:_:_:)"
              ],
              "title": "Encapsulation and Decapsulation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gss/documentation/GSS/message-protection",
                "doc://com.apple.gss/documentation/GSS/kerberos-implementation"
              ],
              "title": "Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_MASK/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_MASK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_MASK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_MECH_PARAMS/title",
          "value": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_MECH_PARAMS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_MECH_PARAMS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_HEADER/title",
          "value": "GSS_IOV_BUFFER_TYPE_HEADER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_HEADER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_HEADER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_SIGN_ONLY/title",
          "value": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_SIGN_ONLY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_SIGN_ONLY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/title",
          "value": "gss_buffer_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_buffer_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_buffer_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_DATA/title",
          "value": "GSS_IOV_BUFFER_TYPE_DATA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_DATA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_DATA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_encapsulate_token(_:_:_:)/title",
          "value": "gss_encapsulate_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_encapsulate_token(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_encapsulate_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_EMPTY/title",
          "value": "GSS_IOV_BUFFER_TYPE_EMPTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_EMPTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_EMPTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_STREAM/title",
          "value": "GSS_IOV_BUFFER_TYPE_STREAM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_STREAM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_STREAM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATE/title",
          "value": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_FLAG_ALLOCATE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_decapsulate_token(_:_:_:)/title",
          "value": "gss_decapsulate_token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1gss_decapsulate_token(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gss_decapsulate_token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED/title",
          "value": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATED/title",
          "value": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_FLAG_ALLOCATED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_FLAG_ALLOCATED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_PADDING/title",
          "value": "GSS_IOV_BUFFER_TYPE_PADDING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_PADDING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_PADDING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_TRAILER/title",
          "value": "GSS_IOV_BUFFER_TYPE_TRAILER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gss~1documentation~1GSS~1GSS_IOV_BUFFER_TYPE_TRAILER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GSS_IOV_BUFFER_TYPE_TRAILER"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gss/token-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gss/token-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
