{
  "abstract": [
    {
      "text": "The authorization type cannot be determined.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use MusicAuthorization.Status from MusicKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/notDetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKCloudServiceAuthorizationStatus@SKCloudServiceAuthorizationStatusNotDetermined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notDetermined"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKCloudServiceAuthorizationStatusNotDetermined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.0",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.3",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "message": "Use MusicAuthorization.Status from MusicKit",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKCloudServiceAuthorizationStatus.notDetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notDetermined"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
        "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the type of authorization the customer has for accessing the Music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/authorized": {
      "abstract": [
        {
          "text": "The user authorizes playback of Apple Music tracks and the addition of tracks to their music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus.authorized",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus/authorized"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/denied": {
      "abstract": [
        {
          "text": "The user does not authorize any access to their music library.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus.denied",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus/denied"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/notDetermined": {
      "abstract": [
        {
          "text": "The authorization type cannot be determined.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus.notDetermined",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus/notdetermined"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/restricted": {
      "abstract": [
        {
          "text": "Access to the music library is restricted in a way that the user cannot change, so your app should not prompt for authorization. An example of this situation is if the device is in an education mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKCloudServiceAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "SKCloudServiceAuthorizationStatus.restricted",
      "type": "topic",
      "url": "/documentation/storekit/skcloudserviceauthorizationstatus/restricted"
    },
    "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities": {
      "abstract": [
        {
          "text": "Determine which Apple Music capabilities are available on a customer’s device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/determining-a-person-s-apple-music-capabilities",
      "kind": "article",
      "role": "article",
      "title": "Determining a person’s Apple Music capabilities",
      "type": "topic",
      "url": "/documentation/storekit/determining-a-person-s-apple-music-capabilities"
    },
    "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library": {
      "abstract": [
        {
          "text": "Prompt the customer to authorize access to Apple Music library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/requesting-access-to-apple-music-library",
      "kind": "article",
      "role": "article",
      "title": "Requesting Access to Apple Music Library",
      "type": "topic",
      "url": "/documentation/storekit/requesting-access-to-apple-music-library"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/denied",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/restricted",
        "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/authorized"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.3",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKCloudServiceAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/denied",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/restricted",
                "doc://com.apple.storekit/documentation/StoreKit/SKCloudServiceAuthorizationStatus/authorized"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKCloudServiceAuthorizationStatusNotDetermined"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use MusicAuthorization.Status from MusicKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1denied/title",
          "value": "SKCloudServiceAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1restricted/title",
          "value": "SKCloudServiceAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1authorized/title",
          "value": "SKCloudServiceAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/title",
          "value": "SKCloudServiceAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1notDetermined/title",
          "value": "SKCloudServiceAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKCloudServiceAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKCloudServiceAuthorizationStatusNotDetermined"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skcloudserviceauthorizationstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skcloudserviceauthorizationstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
