{
  "abstract": [
    {
      "text": "Resolves which defroster to change.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveDefroster(for:with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSetDefrosterSettingsInCarIntentHandling(im)resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resolveDefroster"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
        "text": "INSetDefrosterSettingsInCarIntent"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INCarDefrosterResolutionResult",
        "text": "INCarDefrosterResolutionResult"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetDefrosterSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetDefrosterSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetDefrosterSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetDefrosterSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resolveDefroster(for:with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveDefroster"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
              "text": "INSetDefrosterSettingsInCarIntent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INCarDefrosterResolutionResult",
              "text": "INCarDefrosterResolutionResult"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveDefroster"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
              "text": "INSetDefrosterSettingsInCarIntent"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INCarDefrosterResolutionResult",
              "text": "INCarDefrosterResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "intent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution object whose value contains the specified defroster. If the specified defroster isn’t available, create a resolution result that indicates the change isn’t supported.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "resolutionResult",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to resolve the which defroster to use. Use the intent object to identify the defroster specified by the user. If the car has more than one climate zone, use the intent’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to identify the correct defroster.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for which defroster to use in a car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarDefrosterResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarDefrosterResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarDefrosterResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incardefrosterresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the defroster settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetDefrosterSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster": {
      "abstract": [
        {
          "text": "The defroster to enable or disable.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defroster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarDefroster",
          "text": "INCarDefroster"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defroster"
        }
      ],
      "role": "symbol",
      "title": "defroster",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent/defroster"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s defroster settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetDefrosterSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveCarName(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the car name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCarName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
          "text": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableStringResolutionResult",
          "text": "INSpeakableStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveCarName(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCarNameForSetDefrosterSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCarName(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintenthandling/resolvecarname(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveDefroster(for:with:)": {
      "abstract": [
        {
          "text": "Resolves which defroster to change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDefroster"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
          "text": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCarDefrosterResolutionResult",
          "text": "INCarDefrosterResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveDefroster(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveDefroster(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintenthandling/resolvedefroster(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveEnable(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable or disable the defroster setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
          "text": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveEnable(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableForSetDefrosterSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnable(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintenthandling/resolveenable(for:with:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveEnable(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveCarName(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveEnable(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling/resolveCarName(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "resolveDefrosterForSetDefrosterSettingsInCar:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INSetDefrosterSettingsInCarIntent",
                    "text": "INSetDefrosterSettingsInCarIntent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "intent"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INCarDefrosterResolutionResult",
                    "text": "INCarDefrosterResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "intent"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution object whose value contains the specified defroster. If the specified defroster isn’t available, create a resolution result that indicates the change isn’t supported.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "resolutionResult",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveDefroster(for:with:)/title",
          "value": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveDefroster(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveDefrosterForSetDefrosterSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/title",
          "value": "INCarDefrosterResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarDefrosterResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarDefrosterResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/title",
          "value": "INSetDefrosterSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveEnable(for:with:)/title",
          "value": "resolveEnableForSetDefrosterSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveEnable(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableForSetDefrosterSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/title",
          "value": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/title",
          "value": "defroster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defroster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveCarName(for:with:)/title",
          "value": "resolveCarNameForSetDefrosterSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling~1resolveCarName(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCarNameForSetDefrosterSettingsInCar:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetdefrostersettingsincarintenthandling/resolvedefroster(for:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetdefrostersettingsincarintenthandling/resolvedefroster(for:with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
