{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICLegacyReturnCode@ICLegacyReturnCodeInvalidSessionErr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidSessionErr"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICLegacyReturnCodeInvalidSessionErr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICLegacyReturn.Code.invalidSessionErr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidSessionErr"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn": {
      "abstract": [
        {
          "text": "A legacy error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn",
      "kind": "article",
      "role": "collectionGroup",
      "title": "ICLegacyReturn",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotYieldDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeCannotYieldDevice"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.cannotYieldDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/cannotyielddevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "communicationErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeCommunicationErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.communicationErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/communicationerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataTypeNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDataTypeNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.dataTypeNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/datatypenotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceAlreadyOpenErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceAlreadyOpenErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicealreadyopenerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceGUIDNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceGUIDNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceguidnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceIOServicePathNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceIOServicePathNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceioservicepathnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInternalErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceInternalErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceInternalErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceinternalerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInvalidParamErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceInvalidParamErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceInvalidParamErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceinvalidparamerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceLocationIDNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceLocationIDNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicelocationidnotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceMemoryAllocationErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceMemoryAllocationErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicememoryallocationerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotFoundErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceNotFoundErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceNotFoundErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicenotfounderr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotOpenErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceNotOpenErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceNotOpenErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/devicenotopenerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeDeviceUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.deviceUnsupportedErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/deviceunsupportederr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionInternalErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeExtensionInternalErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.extensionInternalErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/extensioninternalerr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileCorruptedErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeFileCorruptedErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.fileCorruptedErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/filecorruptederr"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSessionErr"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/invalidSessionErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLegacyReturnCodeInvalidSessionErr"
        }
      ],
      "role": "symbol",
      "title": "ICLegacyReturn.Code.invalidSessionErr",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iclegacyreturn/code/invalidsessionerr"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICLegacyReturnCodeInvalidSessionErr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeInvalidSessionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/cannotYieldDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/communicationErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/dataTypeNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceAlreadyOpenErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceGUIDNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceIOServicePathNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInternalErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceInvalidParamErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceLocationIDNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceMemoryAllocationErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotFoundErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceNotOpenErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/deviceUnsupportedErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/extensionInternalErr",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICLegacyReturn/Code/fileCorruptedErr"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICLegacyReturnCodeInvalidSessionErr"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1extensionInternalErr/title",
          "value": "ICLegacyReturnCodeExtensionInternalErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1extensionInternalErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeExtensionInternalErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/title",
          "value": "ICLegacyReturnCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1fileCorruptedErr/title",
          "value": "ICLegacyReturnCodeFileCorruptedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1fileCorruptedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeFileCorruptedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceMemoryAllocationErr/title",
          "value": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceMemoryAllocationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceMemoryAllocationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1dataTypeNotFoundErr/title",
          "value": "ICLegacyReturnCodeDataTypeNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1dataTypeNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDataTypeNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceGUIDNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceGUIDNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceGUIDNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceAlreadyOpenErr/title",
          "value": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceAlreadyOpenErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceAlreadyOpenErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1cannotYieldDevice/title",
          "value": "ICLegacyReturnCodeCannotYieldDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1cannotYieldDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeCannotYieldDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1communicationErr/title",
          "value": "ICLegacyReturnCodeCommunicationErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1communicationErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeCommunicationErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotOpenErr/title",
          "value": "ICLegacyReturnCodeDeviceNotOpenErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceNotOpenErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceNotOpenErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceUnsupportedErr/title",
          "value": "ICLegacyReturnCodeDeviceUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidSessionErr/title",
          "value": "ICLegacyReturnCodeInvalidSessionErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1invalidSessionErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeInvalidSessionErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceLocationIDNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceLocationIDNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceLocationIDNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInvalidParamErr/title",
          "value": "ICLegacyReturnCodeDeviceInvalidParamErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInvalidParamErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceInvalidParamErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceIOServicePathNotFoundErr/title",
          "value": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceIOServicePathNotFoundErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceIOServicePathNotFoundErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInternalErr/title",
          "value": "ICLegacyReturnCodeDeviceInternalErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICLegacyReturn~1Code~1deviceInternalErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLegacyReturnCodeDeviceInternalErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/iclegacyreturn/code/invalidsessionerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/iclegacyreturn/code/invalidsessionerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
