{
  "abstract": [
    {
      "text": "Specifies whether the trust policy settings subview is disclosed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPoliciesDisclosed(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFCertificateView(im)setPoliciesDisclosed:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setPoliciesDisclosed"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setPoliciesDisclosed:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setPoliciesDisclosed(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setPoliciesDisclosed"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "disclosed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to display the certificate details, or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to hide them.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "disclosed"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The trust policy settings can be shown or hidden depending on whether the user clicks the disclosure triangle. This method sets the state of that disclosure triangle and the visibility of the corresponding view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView": {
      "abstract": [
        {
          "text": "A view that displays the contents of a certificate, with options to display certificate details, display trust settings, and allow users to edit a certificate’s trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificateView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCertificateView"
        }
      ],
      "role": "symbol",
      "title": "SFCertificateView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDetailsDisclosed(_:)": {
      "abstract": [
        {
          "text": "Sets whether the certificate details subview is disclosed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDetailsDisclosed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDetailsDisclosed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDetailsDisclosed:"
        }
      ],
      "role": "symbol",
      "title": "setDetailsDisclosed(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/setdetailsdisclosed(_:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayDetails(_:)": {
      "abstract": [
        {
          "text": "Specifies whether the user can see the certificate details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDisplayDetails"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayDetails(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDisplayDetails:"
        }
      ],
      "role": "symbol",
      "title": "setDisplayDetails(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/setdisplaydetails(_:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayTrust(_:)": {
      "abstract": [
        {
          "text": "Specifies whether the user can see the certificate’s trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDisplayTrust"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayTrust(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDisplayTrust:"
        }
      ],
      "role": "symbol",
      "title": "setDisplayTrust(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/setdisplaytrust(_:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setEditableTrust(_:)": {
      "abstract": [
        {
          "text": "Specifies whether the user can edit the certificate’s trust settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setEditableTrust"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setEditableTrust(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setEditableTrust:"
        }
      ],
      "role": "symbol",
      "title": "setEditableTrust(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/seteditabletrust(_:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPolicies(_:)": {
      "abstract": [
        {
          "text": "Specifies the policies to use when evaluating this certificate’s status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPolicies"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPolicies(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPolicies:"
        }
      ],
      "role": "symbol",
      "title": "setPolicies(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/setpolicies(_:)"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPoliciesDisclosed(_:)": {
      "abstract": [
        {
          "text": "Specifies whether the trust policy settings subview is disclosed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPoliciesDisclosed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPoliciesDisclosed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPoliciesDisclosed:"
        }
      ],
      "role": "symbol",
      "title": "setPoliciesDisclosed(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificateview/setpoliciesdisclosed(_:)"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-Appearance-and-Behavior-of-the-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDetailsDisclosed(_:)",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayDetails(_:)",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayTrust(_:)",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setEditableTrust(_:)",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPolicies(_:)"
      ],
      "title": "Customizing the Appearance and Behavior of the View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setPoliciesDisclosed:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPoliciesDisclosed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityinterface/documentation/SecurityInterface",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-Appearance-and-Behavior-of-the-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDetailsDisclosed(_:)",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayDetails(_:)",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setDisplayTrust(_:)",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setEditableTrust(_:)",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateView/setPolicies(_:)"
              ],
              "title": "Customizing the Appearance and Behavior of the View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setPoliciesDisclosed:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "disclosed"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to display the certificate details, or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to hide them.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "disclosed"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDetailsDisclosed(_:)/title",
          "value": "setDetailsDisclosed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDetailsDisclosed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDetailsDisclosed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setEditableTrust(_:)/title",
          "value": "setEditableTrust:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setEditableTrust(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setEditableTrust:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDisplayDetails(_:)/title",
          "value": "setDisplayDetails:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDisplayDetails(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDisplayDetails:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/title",
          "value": "SFCertificateView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setPolicies(_:)/title",
          "value": "setPolicies:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setPolicies(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPolicies:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDisplayTrust(_:)/title",
          "value": "setDisplayTrust:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setDisplayTrust(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDisplayTrust:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setPoliciesDisclosed(_:)/title",
          "value": "setPoliciesDisclosed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateView~1setPoliciesDisclosed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPoliciesDisclosed:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/sfcertificateview/setpoliciesdisclosed(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/sfcertificateview/setpoliciesdisclosed(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
