{
  "abstract": [
    {
      "text": "A Boolean value that determines whether the pipeline scales the tessellation factor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLRenderPipelineDescriptor(py)tessellationFactorScaleEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isTessellationFactorScaleEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "tessellationFactorScaleEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isTessellationFactorScaleEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isTessellationFactorScaleEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If this value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", a scale factor is applied to the tessellation factors after the patch cull check is performed but before the tessellation factors are clamped to the value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The scale factor is applied only if the patch is not culled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTessellationFactorScale(_:)": {
      "abstract": [
        {
          "text": "Configures the scale factor for per-patch tessellation factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTessellationFactorScale"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTessellationFactorScale(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTessellationFactorScale:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setTessellationFactorScale(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/settessellationfactorscale(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor": {
      "abstract": [
        {
          "text": "An argument of options you pass to a GPU device to get a render pipeline state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPipelineDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the pipeline scales the tessellation factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTessellationFactorScaleEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/isTessellationFactorScaleEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorScaleEnabled"
        }
      ],
      "role": "symbol",
      "title": "isTessellationFactorScaleEnabled",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/istessellationfactorscaleenabled"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor": {
      "abstract": [
        {
          "text": "The maximum tessellation factor that the tessellator uses when tessellating patches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxTessellationFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxTessellationFactor"
        }
      ],
      "role": "symbol",
      "title": "maxTessellationFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/maxtessellationfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType": {
      "abstract": [
        {
          "text": "The size of the control point indices in a control point index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationControlPointIndexType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationControlPointIndexType",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationControlPointIndexType"
        }
      ],
      "role": "symbol",
      "title": "tessellationControlPointIndexType",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationcontrolpointindextype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat": {
      "abstract": [
        {
          "text": "The format of the tessellation factors in the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationFactorFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationFactorFormat",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorFormat"
        }
      ],
      "role": "symbol",
      "title": "tessellationFactorFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationfactorformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction": {
      "abstract": [
        {
          "text": "The step function for determining the tessellation factors for a patch from the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationFactorStepFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationFactorStepFunction",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationFactorStepFunction"
        }
      ],
      "role": "symbol",
      "title": "tessellationFactorStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationfactorstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder": {
      "abstract": [
        {
          "text": "The winding order of triangles from the tessellator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationOutputWindingOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLWinding",
          "text": "MTLWinding"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationOutputWindingOrder"
        }
      ],
      "role": "symbol",
      "title": "tessellationOutputWindingOrder",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationoutputwindingorder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode": {
      "abstract": [
        {
          "text": "The partitioning mode that the tessellator uses to derive the number and spacing of segments for subdividing a corresponding edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationPartitionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTessellationPartitionMode",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationPartitionMode"
        }
      ],
      "role": "symbol",
      "title": "tessellationPartitionMode",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinedescriptor/tessellationpartitionmode"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType": {
      "abstract": [
        {
          "text": "Options for specifying the size of the control point indices in a control point index buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationControlPointIndexType"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationControlPointIndexType",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationcontrolpointindextype"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat": {
      "abstract": [
        {
          "text": "Options for specifying the format of the tessellation factors in a tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorFormat",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction": {
      "abstract": [
        {
          "text": "Options for specifying the step function that determines the tessellation factors for a patch from the tessellation factor buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationFactorStepFunction"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationFactorStepFunction",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationfactorstepfunction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode": {
      "abstract": [
        {
          "text": "Options for choosing the partition mode that the tessellator applies when deriving",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "the number and spacing of segments for subdividing a corresponding edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLTessellationPartitionMode"
        }
      ],
      "role": "symbol",
      "title": "MTLTessellationPartitionMode",
      "type": "topic",
      "url": "/documentation/metal/mtltessellationpartitionmode"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTessellationFactorScale(_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Specifying-Tessellation-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction",
        "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
      ],
      "title": "Specifying Tessellation State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "tessellationFactorScaleEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorScaleEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setTessellationFactorScale(_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Specifying-Tessellation-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/maxTessellationFactor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorFormat",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationControlPointIndexType",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationFactorStepFunction",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationOutputWindingOrder",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineDescriptor/tessellationPartitionMode",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorFormat",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationControlPointIndexType",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationFactorStepFunction",
                "doc://com.apple.metal/documentation/Metal/MTLTessellationPartitionMode"
              ],
              "title": "Specifying Tessellation State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isTessellationFactorScaleEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "tessellationFactorScaleEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationPartitionMode/title",
          "value": "tessellationPartitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationPartitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationOutputWindingOrder/title",
          "value": "tessellationOutputWindingOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationOutputWindingOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationOutputWindingOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/title",
          "value": "MTLTessellationFactorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/title",
          "value": "MTLTessellationPartitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationPartitionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationPartitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTessellationFactorScale(_:)/title",
          "value": "setTessellationFactorScale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setTessellationFactorScale(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTessellationFactorScale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationControlPointIndexType/title",
          "value": "tessellationControlPointIndexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationControlPointIndexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor/title",
          "value": "MTLRenderPipelineDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1isTessellationFactorScaleEnabled/title",
          "value": "tessellationFactorScaleEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1isTessellationFactorScaleEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorScaleEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/title",
          "value": "MTLTessellationControlPointIndexType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationControlPointIndexType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationControlPointIndexType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/title",
          "value": "MTLTessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLTessellationFactorStepFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorStepFunction/title",
          "value": "tessellationFactorStepFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorStepFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorStepFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1maxTessellationFactor/title",
          "value": "maxTessellationFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1maxTessellationFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxTessellationFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorFormat/title",
          "value": "tessellationFactorFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineDescriptor~1tessellationFactorFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationFactorFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrenderpipelinedescriptor/istessellationfactorscaleenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlrenderpipelinedescriptor/istessellationfactorscaleenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
