{
  "abstract": [
    {
      "text": "The name of a highlight group.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please use SwiftUI or UIKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvmlkit/documentation/TVMLKit",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/localizedName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVHighlightGroup(py)localizedName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "localizedName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "TVMLKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "localizedName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "12.0",
        "message": "Please use SwiftUI or UIKit",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "localizedName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "localizedName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit": {
      "abstract": [
        {
          "text": "Create client-server apps by incorporating JavaScript and TVML files in your binary app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVMLKit",
      "type": "topic",
      "url": "/documentation/tvmlkit"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem": {
      "abstract": [
        {
          "text": "A single audio or video item associated with the Apple TV JavaScript player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMediaItem"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/Highlight": {
      "abstract": [
        {
          "text": "An object that describes a media item highlight.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/Highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.Highlight",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlight"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup": {
      "abstract": [
        {
          "text": "A container for groups of highlights for a media item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HighlightGroup"
        }
      ],
      "role": "symbol",
      "title": "TVMediaItem.HighlightGroup",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroup"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/highlights": {
      "abstract": [
        {
          "text": "An array of the individual highlights that make up a group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlights"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVMediaItem",
          "text": "TVMediaItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVHighlight",
          "text": "Highlight"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/highlights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlights"
        }
      ],
      "role": "symbol",
      "title": "highlights",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroup/highlights"
    },
    "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/localizedName": {
      "abstract": [
        {
          "text": "The name of a highlight group.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/tvmlkit/tvmediaitem/highlightgroup/localizedname"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Highlights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/highlights",
        "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/Highlight"
      ],
      "title": "Accessing the Highlights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvmlkit/documentation/TVMLKit",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Highlights",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/HighlightGroup/highlights",
                "doc://com.apple.tvmlkit/documentation/TVMLKit/TVMediaItem/Highlight"
              ],
              "title": "Accessing the Highlights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "localizedName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please use SwiftUI or UIKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup~1highlights/title",
          "value": "highlights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup~1highlights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/title",
          "value": "TVMediaItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMediaItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1Highlight/title",
          "value": "TVHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1Highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1Highlight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/title",
          "value": "TVHighlightGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvmlkit~1documentation~1TVMLKit~1TVMediaItem~1HighlightGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVHighlightGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem/highlightgroup/localizedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvmlkit/tvmediaitem/highlightgroup/localizedname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
