{
  "abstract": [
    {
      "text": "The email is related to a purchase or transaction.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/transaction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIMailConversationEntryKind@UIMailConversationEntryKindTransaction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "transaction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIMailConversationEntryKindTransaction"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIMailConversationContext.MailEntry.Kind.transaction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "transaction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext": {
      "abstract": [
        {
          "text": "A class that represents an email conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMailConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry": {
      "abstract": [
        {
          "text": "A class that represents a specific email in an email thread.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MailEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MailEntry"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum": {
      "abstract": [
        {
          "text": "A set of categories for an email.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/news": {
      "abstract": [
        {
          "text": "The email is related to news or current events.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "news"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/news",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindNews"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.news",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/news"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/none": {
      "abstract": [
        {
          "text": "The email does not fit in a specific category.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindNone"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.none",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/personal": {
      "abstract": [
        {
          "text": "The email is personal correspondence.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "personal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/personal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindPersonal"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.personal",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/personal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/promotion": {
      "abstract": [
        {
          "text": "The email contains a promotional offer.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promotion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/promotion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindPromotion"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.promotion",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/promotion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/social": {
      "abstract": [
        {
          "text": "The email is related to social media.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "social"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/social",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindSocial"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.social",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/social"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/transaction": {
      "abstract": [
        {
          "text": "The email is related to a purchase or transaction.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transaction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/transaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationEntryKindTransaction"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry.Kind.transaction",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/transaction"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Kinds-of-email",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/news",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/none",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/personal",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/promotion",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/social"
      ],
      "title": "Kinds of email"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIMailConversationEntryKindTransaction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Kinds-of-email",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/news",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/none",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/personal",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/promotion",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry/Kind-swift.enum/social"
              ],
              "title": "Kinds of email"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIMailConversationEntryKindTransaction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1personal/title",
          "value": "UIMailConversationEntryKindPersonal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1personal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindPersonal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1news/title",
          "value": "UIMailConversationEntryKindNews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1news/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindNews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/title",
          "value": "UIMailConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1none/title",
          "value": "UIMailConversationEntryKindNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1social/title",
          "value": "UIMailConversationEntryKindSocial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1social/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindSocial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1promotion/title",
          "value": "UIMailConversationEntryKindPromotion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1promotion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindPromotion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1transaction/title",
          "value": "UIMailConversationEntryKindTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum~1transaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKindTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum/title",
          "value": "UIMailConversationEntryKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry~1Kind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntryKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/title",
          "value": "UIMailConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimailconversationcontext/mailentry/kind-swift.enum/transaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
