{
  "abstract": [
    {
      "text": "A bezel style for use with a vertically expanding and collapsing disclosure button.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSButton",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSBezelStyle@NSBezelStyleRoundedDisclosure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "roundedDisclosure"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSButton",
        "text": "NSButton"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSBezelStyle",
        "text": "BezelStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBezelStyleRoundedDisclosure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "renamed": "NSButton.BezelStyle.pushDisclosure",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "roundedDisclosure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "roundedDisclosure"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSButton",
              "text": "NSButton"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSBezelStyle",
              "text": "BezelStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The set of bezel styles to style buttons in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline": {
      "abstract": [
        {
          "text": "A button that has a solid round-rectangle border background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleInline"
        }
      ],
      "role": "symbol",
      "title": "inline",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/inline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use in scope bars and title bar accessories, similar to the bookmarks bar in Safari.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recessed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRecessed"
        }
      ],
      "role": "symbol",
      "title": "recessed",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/recessed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare": {
      "abstract": [
        {
          "text": "A rectangular button with a two-point border, designed for icons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularSquare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRegularSquare"
        }
      ],
      "role": "symbol",
      "title": "regularSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/regularsquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use as an action or auxiliary button in scope bars and title bar accessories.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roundRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRoundRect"
        }
      ],
      "role": "symbol",
      "title": "roundRect",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundrect"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded": {
      "abstract": [
        {
          "text": "A rounded rectangle button, designed for text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rounded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRounded"
        }
      ],
      "role": "symbol",
      "title": "rounded",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/rounded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure": {
      "abstract": [
        {
          "text": "A bezel style for use with a vertically expanding and collapsing disclosure button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roundedDisclosure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundedDisclosure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleRoundedDisclosure"
        }
      ],
      "role": "symbol",
      "title": "roundedDisclosure",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundeddisclosure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded": {
      "abstract": [
        {
          "text": "A bezel style appropriate for use in the toolbar or title bar regions of a window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texturedRounded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezelStyle",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleTexturedRounded"
        }
      ],
      "role": "symbol",
      "title": "texturedRounded",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/texturedrounded"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.4",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBezelStyleRoundedDisclosure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRoundedDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/inline",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/recessed",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/regularSquare",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/rounded",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/roundRect",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/texturedRounded"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSBezelStyleRoundedDisclosure"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1recessed/title",
          "value": "NSBezelStyleRecessed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1recessed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRecessed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedRounded/title",
          "value": "NSBezelStyleTexturedRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1texturedRounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleTexturedRounded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1regularSquare/title",
          "value": "NSBezelStyleRegularSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1regularSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRegularSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1inline/title",
          "value": "NSBezelStyleInline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1inline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleInline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundRect/title",
          "value": "NSBezelStyleRoundRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRoundRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1rounded/title",
          "value": "NSBezelStyleRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1rounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRounded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundedDisclosure/title",
          "value": "NSBezelStyleRoundedDisclosure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1roundedDisclosure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleRoundedDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundeddisclosure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbutton/bezelstyle-swift.enum/roundeddisclosure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
