{
  "abstract": [
    {
      "text": "Errors issued by the LocalAuthentication framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@LAError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Local Authentication"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "LAError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication": {
      "abstract": [
        {
          "text": "Authenticate users biometrically or with a passphrase they already know.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication",
      "type": "topic",
      "url": "/documentation/localauthentication"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryLockout"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotEnrolled"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorBiometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorbiometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable": {
      "abstract": [
        {
          "text": "Authentication could not start because there was no paired companion device nearby.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LAErrorCompanionNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "LAErrorCompanionNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-c.enum/laerrorcompanionnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAError"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAError"
        }
      ],
      "role": "symbol",
      "title": "LAError",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Errors issued by the LocalAuthentication framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/appCancel": {
      "abstract": [
        {
          "text": "The app canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appCancel"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/appCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorAppCancel"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.appCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/appcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/authenticationFailed": {
      "abstract": [
        {
          "text": "The user failed to provide valid credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/authenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.authenticationFailed",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/authenticationfailed"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but the paired accessory isn’t connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryDisconnected"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryDisconnected"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.biometryDisconnected",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrydisconnected"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryLockout",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotEnrolled",
      "kind": "symbol",
      "role": "symbol",
      "title": "biometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but no accessory is paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biometryNotPaired"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorBiometryNotPaired"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.biometryNotPaired",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/biometrynotpaired"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/companionNotAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "companionNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7LAErrorLeV",
          "text": "LAError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LAError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/companionNotAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "companionNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/companionnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidContext": {
      "abstract": [
        {
          "text": "The context was previously invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidContext"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorInvalidContext"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.invalidContext",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/invalidcontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidDimensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDimensions"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorInvalidDimensions"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.invalidDimensions",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/invaliddimensions"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/notInteractive": {
      "abstract": [
        {
          "text": "Displaying the required authentication user interface is forbidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notInteractive"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/notInteractive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorNotInteractive"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.notInteractive",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/notinteractive"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/passcodeNotSet": {
      "abstract": [
        {
          "text": "A passcode isn’t set on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passcodeNotSet"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/passcodeNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorPasscodeNotSet"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.passcodeNotSet",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/passcodenotset"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/systemCancel": {
      "abstract": [
        {
          "text": "The system canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemCancel"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/systemCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorSystemCancel"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.systemCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/systemcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout": {
      "abstract": [
        {
          "text": "Touch ID is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDLockout"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDLockout"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidlockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable": {
      "abstract": [
        {
          "text": "Touch ID is not available on the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled Touch ID fingers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchIDNotEnrolled"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorTouchIDNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.touchIDNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/touchidnotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userCancel": {
      "abstract": [
        {
          "text": "The user tapped the cancel button in the authentication dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCancel"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorUserCancel"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.userCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/usercancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userFallback": {
      "abstract": [
        {
          "text": "The user tapped the fallback button in the authentication dialog, but no fallback is available for the authentication policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userFallback"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userFallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorUserFallback"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.userFallback",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/userfallback"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/watchNotAvailable": {
      "abstract": [
        {
          "text": "An attempt to authenticate with Apple Watch failed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/watchNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorWatchNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "LAError.Code.watchNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/laerror-swift.struct/code/watchnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain": {
      "abstract": [
        {
          "text": "The error domain that the framework uses when issuing errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "LAErrorDomain",
      "type": "topic",
      "url": "/documentation/localauthentication/laerrordomain"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel": {
      "abstract": [
        {
          "text": "The app canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorAppCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorAppCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorAppCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorappcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed": {
      "abstract": [
        {
          "text": "The user failed to provide valid credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorAuthenticationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorauthenticationfailed"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but the paired accessory isn’t connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryDisconnected"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryDisconnected",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrydisconnected"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout": {
      "abstract": [
        {
          "text": "Biometry is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryLockout"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrylockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable": {
      "abstract": [
        {
          "text": "Biometry is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled biometric identities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired": {
      "abstract": [
        {
          "text": "The device supports biometry only using a removable accessory, but no accessory is paired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotPaired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorBiometryNotPaired"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorBiometryNotPaired",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorbiometrynotpaired"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain": {
      "abstract": [
        {
          "text": "The error domain used by LocalAuthentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorDomain",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrordomain"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext": {
      "abstract": [
        {
          "text": "The context was previously invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidContext"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorInvalidContext",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorinvalidcontext"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorInvalidDimensions"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorInvalidDimensions",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorinvaliddimensions"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorNotInteractive": {
      "abstract": [
        {
          "text": "Displaying the required authentication user interface is forbidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorNotInteractive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorNotInteractive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorNotInteractive"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorNotInteractive",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrornotinteractive"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorPasscodeNotSet": {
      "abstract": [
        {
          "text": "A passcode isn’t set on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorPasscodeNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorPasscodeNotSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorPasscodeNotSet"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorPasscodeNotSet",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorpasscodenotset"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel": {
      "abstract": [
        {
          "text": "The system canceled authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorSystemCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorSystemCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorSystemCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorsystemcancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout": {
      "abstract": [
        {
          "text": "Touch ID is locked because there were too many failed attempts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDLockout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDLockout"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDLockout",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidlockout"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable": {
      "abstract": [
        {
          "text": "Touch ID is not available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidnotavailable"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled": {
      "abstract": [
        {
          "text": "The user has no enrolled Touch ID fingers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotEnrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorTouchIDNotEnrolled"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorTouchIDNotEnrolled",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrortouchidnotenrolled"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel": {
      "abstract": [
        {
          "text": "The user tapped the cancel button in the authentication dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorUserCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorUserCancel"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorUserCancel",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorusercancel"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserFallback": {
      "abstract": [
        {
          "text": "The user tapped the fallback button in the authentication dialog, but no fallback is available for the authentication policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorUserFallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserFallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorUserFallback"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorUserFallback",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerroruserfallback"
    },
    "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable": {
      "abstract": [
        {
          "text": "An attempt to authenticate with Apple Watch failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kLAErrorWatchNotAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kLAErrorWatchNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "kLAErrorWatchNotAvailable",
      "type": "topic",
      "url": "/documentation/localauthentication/klaerrorwatchnotavailable"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Cancellation",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/appCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/systemCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userCancel"
      ],
      "title": "Cancellation"
    },
    {
      "anchor": "Biometry-failure",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled"
      ],
      "title": "Biometry failure"
    },
    {
      "anchor": "Other-errors",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/authenticationFailed",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidContext",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidDimensions",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/notInteractive",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/passcodeNotSet",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userFallback",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/watchNotAvailable"
      ],
      "title": "Other errors"
    },
    {
      "anchor": "Supporting-Constants",
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorNotInteractive",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorPasscodeNotSet",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserFallback",
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable"
      ],
      "title": "Supporting Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/companionNotAvailable"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LAError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Cancellation",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/appCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/systemCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userCancel"
              ],
              "title": "Cancellation"
            },
            {
              "anchor": "Biometry-failure",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryDisconnected",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorBiometryNotEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/biometryNotPaired",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/touchIDNotEnrolled"
              ],
              "title": "Biometry failure"
            },
            {
              "anchor": "Other-errors",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/authenticationFailed",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidContext",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/invalidDimensions",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/notInteractive",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/passcodeNotSet",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/userFallback",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-swift.struct/Code/watchNotAvailable"
              ],
              "title": "Other errors"
            },
            {
              "anchor": "Supporting-Constants",
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorDomain",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAppCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorSystemCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserCancel",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryDisconnected",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorBiometryNotPaired",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDLockout",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotAvailable",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorTouchIDNotEnrolled",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorAuthenticationFailed",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidContext",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorInvalidDimensions",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorNotInteractive",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorPasscodeNotSet",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorUserFallback",
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/kLAErrorWatchNotAvailable"
              ],
              "title": "Supporting Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAError-c.enum/LAErrorCompanionNotAvailable"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.localauthentication/documentation/LocalAuthentication/LAErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LAError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorDomain/title",
          "value": "kLAErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAErrorDomain/title",
          "value": "LAErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAuthenticationFailed/title",
          "value": "kLAErrorAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAuthenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryNotPaired/title",
          "value": "LAErrorBiometryNotPaired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryNotPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorBiometryNotPaired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotAvailable/title",
          "value": "LAErrorTouchIDNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotAvailable/title",
          "value": "kLAErrorTouchIDNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1watchNotAvailable/title",
          "value": "LAErrorWatchNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1watchNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorWatchNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1notInteractive/title",
          "value": "LAErrorNotInteractive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1notInteractive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorNotInteractive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorNotInteractive/title",
          "value": "kLAErrorNotInteractive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorNotInteractive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorNotInteractive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAppCancel/title",
          "value": "kLAErrorAppCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorAppCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorAppCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/title",
          "value": "LAError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1appCancel/title",
          "value": "LAErrorAppCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1appCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorAppCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidContext/title",
          "value": "kLAErrorInvalidContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorInvalidContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorWatchNotAvailable/title",
          "value": "kLAErrorWatchNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorWatchNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorWatchNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1authenticationFailed/title",
          "value": "LAErrorAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1authenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1userFallback/title",
          "value": "LAErrorUserFallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1userFallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorUserFallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotEnrolled/title",
          "value": "kLAErrorTouchIDNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryLockout/title",
          "value": "kLAErrorBiometryLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorPasscodeNotSet/title",
          "value": "kLAErrorPasscodeNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorPasscodeNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorPasscodeNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1invalidDimensions/title",
          "value": "LAErrorInvalidDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1invalidDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorInvalidDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserFallback/title",
          "value": "kLAErrorUserFallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserFallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorUserFallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDLockout/title",
          "value": "kLAErrorTouchIDLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorTouchIDLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorTouchIDLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorSystemCancel/title",
          "value": "kLAErrorSystemCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorSystemCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorSystemCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1passcodeNotSet/title",
          "value": "LAErrorPasscodeNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1passcodeNotSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorPasscodeNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserCancel/title",
          "value": "kLAErrorUserCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorUserCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorUserCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidDimensions/title",
          "value": "kLAErrorInvalidDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorInvalidDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorInvalidDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotEnrolled/title",
          "value": "kLAErrorBiometryNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDLockout/title",
          "value": "LAErrorTouchIDLockout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDLockout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDLockout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryDisconnected/title",
          "value": "kLAErrorBiometryDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1systemCancel/title",
          "value": "LAErrorSystemCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1systemCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorSystemCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1userCancel/title",
          "value": "LAErrorUserCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1userCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorUserCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotPaired/title",
          "value": "kLAErrorBiometryNotPaired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotPaired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotEnrolled/title",
          "value": "LAErrorTouchIDNotEnrolled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1touchIDNotEnrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorTouchIDNotEnrolled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryDisconnected/title",
          "value": "LAErrorBiometryDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1biometryDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorBiometryDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotAvailable/title",
          "value": "kLAErrorBiometryNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1kLAErrorBiometryNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kLAErrorBiometryNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1invalidContext/title",
          "value": "LAErrorInvalidContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.localauthentication~1documentation~1LocalAuthentication~1LAError-swift.struct~1Code~1invalidContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAErrorInvalidContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthentication/laerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthentication/laerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
