{
  "abstract": [
    {
      "text": "A natural log scale.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Accessibility/documentation/Accessibility",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/ln"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AXNumericDataAxisDescriptorScale@AXScaleTypeLn",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ln"
      }
    ],
    "modules": [
      {
        "name": "Accessibility"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXScaleTypeLn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AXNumericDataAxisDescriptor.ScaleType.ln"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ln"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "Accessibility-PageImage-card.png": {
      "alt": "",
      "identifier": "Accessibility-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/718b8a161d77a3423dde2dd53ac35ffb/Accessibility-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed433f19cfa41ebf0c9f495a066b6bbd/Accessibility-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.Accessibility/documentation/Accessibility": {
      "abstract": [
        {
          "text": "Make your apps accessible to everyone who uses Apple devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility",
      "images": [
        {
          "identifier": "Accessibility-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "Accessibility",
      "type": "topic",
      "url": "/documentation/accessibility"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor": {
      "abstract": [
        {
          "text": "An object that represents an axis of numerical data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNumericDataAxisDescriptor"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNumericDataAxisDescriptor"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the scale of a numeric axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScaleType"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScaleType"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor.ScaleType",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/linear": {
      "abstract": [
        {
          "text": "A linear scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXScaleTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor.ScaleType.linear",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum/linear"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/ln": {
      "abstract": [
        {
          "text": "A natural log scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ln"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/ln",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXScaleTypeLn"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor.ScaleType.ln",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum/ln"
    },
    "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/log10": {
      "abstract": [
        {
          "text": "A log scale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log10"
        }
      ],
      "identifier": "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/log10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXScaleTypeLog10"
        }
      ],
      "role": "symbol",
      "title": "AXNumericDataAxisDescriptor.ScaleType.log10",
      "type": "topic",
      "url": "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum/log10"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Scales",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/linear",
        "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/log10"
      ],
      "title": "Scales"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXScaleTypeLn"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXScaleTypeLn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Accessibility/documentation/Accessibility",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Scales",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/linear",
                "doc://com.apple.Accessibility/documentation/Accessibility/AXNumericDataAxisDescriptor/ScaleType-swift.enum/log10"
              ],
              "title": "Scales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AXScaleTypeLn"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/title",
          "value": "AXNumericDataAxisDescriptorScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptorScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptorScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1log10/title",
          "value": "AXScaleTypeLog10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1log10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXScaleTypeLog10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/title",
          "value": "AXNumericDataAxisDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNumericDataAxisDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1linear/title",
          "value": "AXScaleTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXScaleTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1ln/title",
          "value": "AXScaleTypeLn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Accessibility~1documentation~1Accessibility~1AXNumericDataAxisDescriptor~1ScaleType-swift.enum~1ln/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXScaleTypeLn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum/ln"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessibility/axnumericdataaxisdescriptor/scaletype-swift.enum/ln"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
