{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-27o4l"],"title":"Retrieving an Asset’s Data Resources","anchor":"Retrieving-an-Assets-Data-Resources","generated":true}],"metadata":{"navigatorTitle":[{"text":"assetResourcesForLivePhoto:","kind":"identifier"}],"role":"symbol","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"9.1"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"9.1"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.15"},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"10.0"},{"beta":false,"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"externalID":"c:objc(cs)PHAssetResource(cm)assetResourcesForLivePhoto:","modules":[{"name":"Photos"}],"title":"assetResources(for:)","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetResources","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHLivePhoto","text":"PHLivePhoto","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAssetResource","text":"PHAssetResource","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"method"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetResources","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"livePhoto","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PHLivePhoto","identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto","preciseIdentifier":"c:objc(cs)PHLivePhoto","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"PHAssetResource","identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetResource","preciseIdentifier":"c:objc(cs)PHAssetResource","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"livePhoto","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Live Photo object."}]}]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The underlying resources that constitute the Live Photo."}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A Live Photo is a picture, taken with a compatible device, that includes movement and sound from the moments just before and after its capture. A "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto"},{"type":"text","text":" object represents the displayable combination of image, motion, and sound data. You can obtain such objects from the Photos library using the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHImageManager"},{"type":"text","text":" class or construct them from asset resources exported from a Photos library using the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto"},{"type":"text","text":" class."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to export the underlying resources that constitute a Live Photo. For example, a social networking app can retrieve those data files and upload them to a server. Then, on another user’s device, the app downloads those data files and uses the "},{"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto","isActive":true},{"type":"text","text":" class to re-create a Live Photo object for display using the "},{"type":"reference","identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView","isActive":true},{"type":"text","text":" class."}]}],"kind":"content"}],"variants":[{"paths":["/documentation/photos/phassetresource/assetresources(for:)-2fedw"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/photos/phassetresource/assetresources(for:)-2fedw"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Returns the list of data resources associated with a Live Photo object.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-2fedw"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAssetResource"]]},"references":{"doc://com.apple.photokit/documentation/Photos/PHImageManager":{"title":"PHImageManager","navigatorTitle":[{"kind":"identifier","text":"PHImageManager"}],"url":"/documentation/photos/phimagemanager","type":"topic","abstract":[{"type":"text","text":"An object that facilitates retrieving or generating preview thumbnails and asset data."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHImageManager"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHImageManager"},"doc://com.apple.photokit/documentation/Photos/PHAssetResource":{"url":"/documentation/photos/phassetresource","abstract":[{"type":"text","text":"An underlying data resource associated with a photo, video, or Live Photo asset in the Photos library."}],"title":"PHAssetResource","type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetResource","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHAssetResource"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHAssetResource"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-2fedw":{"type":"topic","title":"assetResources(for:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetResources","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHLivePhoto","preciseIdentifier":"c:objc(cs)PHLivePhoto","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"PHAssetResource","preciseIdentifier":"c:objc(cs)PHAssetResource","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","url":"/documentation/photos/phassetresource/assetresources(for:)-2fedw","kind":"symbol","abstract":[{"type":"text","text":"Returns the list of data resources associated with a Live Photo object."}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-2fedw","navigatorTitle":[{"text":"assetResourcesForLivePhoto:","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHLivePhoto":{"role":"symbol","title":"PHLivePhoto","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHLivePhoto"}],"kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto","navigatorTitle":[{"kind":"identifier","text":"PHLivePhoto"}],"url":"/documentation/photos/phlivephoto","type":"topic","abstract":[{"type":"text","text":"A displayable representation of a Live Photo—a picture that includes motion and sound from the moments just before and after its capture."}]},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView":{"role":"symbol","title":"PHLivePhotoView","type":"topic","abstract":[{"text":"A view that displays a Live Photo—a picture that also includes motion and sound from the moments just before and after its capture.","type":"text"}],"navigatorTitle":[{"text":"PHLivePhotoView","kind":"identifier"}],"identifier":"doc://com.apple.photokit/documentation/PhotosUI/PHLivePhotoView","url":"/documentation/photosui/phlivephotoview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PHLivePhotoView","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-27o4l":{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-27o4l","type":"topic","abstract":[{"text":"Returns the list of data resources associated with an asset.","type":"text"}],"role":"symbol","title":"assetResources(for:)","url":"/documentation/photos/phassetresource/assetresources(for:)-27o4l","kind":"symbol","navigatorTitle":[{"text":"assetResourcesForAsset:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetResources","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAssetResource","text":"PHAssetResource","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"9.1"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"9.1"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1"},{"unavailable":false,"name":"macOS","deprecated":false,"beta":false,"introducedAt":"10.15"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"10.0"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"assetResourcesForLivePhoto:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"assetResourcesForLivePhoto:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAssetResource"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAssetResource/assetResources(for:)-27o4l"],"title":"Retrieving an Asset’s Data Resources","anchor":"Retrieving-an-Assets-Data-Resources","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<PHAssetResource *>"},{"text":" *) ","kind":"text"},{"text":"assetResourcesForLivePhoto:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PHLivePhoto","preciseIdentifier":"c:objc(cs)PHLivePhoto","kind":"typeIdentifier","identifier":"doc://com.apple.photokit/documentation/Photos/PHLivePhoto"},{"text":" *) ","kind":"text"},{"text":"livePhoto","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A Live Photo object.","type":"text"}]}],"name":"livePhoto"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The underlying resources that constitute the Live Photo.","type":"text"}]}]}},{"value":"PHImageManager","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/title","op":"replace"},{"value":[{"text":"PHImageManager","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PHImageManager"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager/navigatorTitle","op":"replace"},{"value":"PHAssetResource","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/title","op":"replace"},{"value":[{"kind":"identifier","text":"PHAssetResource"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PHAssetResource"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource/navigatorTitle","op":"replace"},{"value":"assetResourcesForLivePhoto:","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetResources(for:)-2fedw/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"assetResourcesForLivePhoto:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetResources(for:)-2fedw/fragments","op":"replace"},{"value":"PHLivePhoto","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/title","op":"replace"},{"value":[{"text":"PHLivePhoto","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PHLivePhoto"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHLivePhoto/navigatorTitle","op":"replace"},{"value":"PHLivePhotoView","path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/title","op":"replace"},{"value":[{"kind":"identifier","text":"PHLivePhotoView"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PHLivePhotoView"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHLivePhotoView/navigatorTitle","op":"replace"},{"value":"assetResourcesForAsset:","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetResources(for:)-27o4l/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"assetResourcesForAsset:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetResource~1assetResources(for:)-27o4l/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}