{
  "abstract": [
    {
      "text": "The menu object used to dynamically construct the search field’s pop-up icon menu.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSearchField(py)searchMenuTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "searchMenuTemplate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSMenu",
        "text": "NSMenu"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "searchMenuTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "searchMenuTemplate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "searchMenuTemplate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSMenu",
              "text": "NSMenu"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMenu": {
      "abstract": [
        {
          "text": "An object that manages an app’s menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenu"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMenu"
        }
      ],
      "role": "symbol",
      "title": "NSMenu",
      "type": "topic",
      "url": "/documentation/appkit/nsmenu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField": {
      "abstract": [
        {
          "text": "A text field optimized for performing text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchField"
        }
      ],
      "role": "symbol",
      "title": "NSSearchField",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item for clearing the current set of recent string searches in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearRecentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldClearRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "clearRecentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/clearrecentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item that describes a lack of recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noRecentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldNoRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "noRecentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/norecentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag": {
      "abstract": [
        {
          "text": "The location of recent search strings in the “recents” menu group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentsMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldRecentsMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "recentsMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentsmenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag": {
      "abstract": [
        {
          "text": "The menu item that provides the title of the menu group for recent search strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recentsTitleMenuItemTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSearchFieldRecentsTitleMenuItemTag"
        }
      ],
      "role": "symbol",
      "title": "recentsTitleMenuItemTag",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/recentstitlemenuitemtag"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate": {
      "abstract": [
        {
          "text": "The menu object used to dynamically construct the search field’s pop-up icon menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchMenuTemplate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMenu",
          "text": "NSMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSearchField/searchMenuTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchMenuTemplate"
        }
      ],
      "role": "symbol",
      "title": "searchMenuTemplate",
      "type": "topic",
      "url": "/documentation/appkit/nssearchfield/searchmenutemplate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SearchFields/SearchFields.html#//apple_ref/doc/uid/10000168i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SearchFields/SearchFields.html#//apple_ref/doc/uid/10000168i",
      "title": "Search Fields",
      "titleInlineContent": [
        {
          "text": "Search Fields",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SearchFields/SearchFields.html#//apple_ref/doc/uid/10000168i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SearchFields/SearchFields.html#//apple_ref/doc/uid/10000168i"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-Menu-Templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
        "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag"
      ],
      "title": "Managing Menu Templates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "searchMenuTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchMenuTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/SearchFields/SearchFields.html#//apple_ref/doc/uid/10000168i"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Managing-Menu-Templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/clearRecentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/noRecentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsMenuItemTag",
                "doc://com.apple.appkit/documentation/AppKit/NSSearchField/recentsTitleMenuItemTag"
              ],
              "title": "Managing Menu Templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMenu",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSMenu",
                    "text": "NSMenu"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "searchMenuTemplate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/title",
          "value": "NSSearchField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsMenuItemTag/title",
          "value": "NSSearchFieldRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/title",
          "value": "NSMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMenu/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1noRecentsMenuItemTag/title",
          "value": "NSSearchFieldNoRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1noRecentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldNoRecentsMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchMenuTemplate/title",
          "value": "searchMenuTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1searchMenuTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchMenuTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsTitleMenuItemTag/title",
          "value": "NSSearchFieldRecentsTitleMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1recentsTitleMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldRecentsTitleMenuItemTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1clearRecentsMenuItemTag/title",
          "value": "NSSearchFieldClearRecentsMenuItemTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSearchField~1clearRecentsMenuItemTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSearchFieldClearRecentsMenuItemTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssearchfield/searchmenutemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssearchfield/searchmenutemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
