{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct/KeyCacheHandle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@cssm_tp_certreclaim_output@FI@KeyCacheHandle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "KeyCacheHandle"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "KeyCacheHandle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "KeyCacheHandle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.security/documentation/Security/CSSM_LONG_HANDLE",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CSSM_LONG_HANDLE",
              "text": "CSSM_LONG_HANDLE"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "KeyCacheHandle"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/CSSM_LONG_HANDLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CSSM_LONG_HANDLE"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/CSSM_LONG_HANDLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CSSM_LONG_HANDLE"
        }
      ],
      "role": "symbol",
      "title": "CSSM_LONG_HANDLE",
      "type": "topic",
      "url": "/documentation/security/cssm_long_handle"
    },
    "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cssm_tp_certreclaim_output"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "cssm_tp_certreclaim_output",
      "type": "topic",
      "url": "/documentation/security/cssm_tp_certreclaim_output-c.struct"
    },
    "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct/KeyCacheHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "KeyCacheHandle"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/cssm_tp_certreclaim_output-c.struct/KeyCacheHandle",
      "kind": "symbol",
      "role": "symbol",
      "title": "KeyCacheHandle",
      "type": "topic",
      "url": "/documentation/security/cssm_tp_certreclaim_output-c.struct/keycachehandle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_LONG_HANDLE/title",
          "value": "CSSM_LONG_HANDLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_LONG_HANDLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_LONG_HANDLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1CSSM_LONG_HANDLE/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CSSM_LONG_HANDLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/cssm_tp_certreclaim_output-c.struct/keycachehandle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
