{
  "abstract": [
    {
      "text": "Train a machine learning model to tag individual words in natural language text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/creating-a-word-tagger-model"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating a word tagger model"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "word tagger",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a machine learning model that’s been trained to classify natural language text at the word level.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You train a word tagger by showing it multiple examples of sentences containing words you’ve already tagged — for example, Apple product names like ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "iPad",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "iPhone",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Import-your-data",
          "level": 3,
          "text": "Import your data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Start by gathering textual data and importing it into an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance. You can create a data table from JSON and CSV formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As an example, consider a JSON file containing sentences with words that you’ve tagged. Each entry contains a pair of keys—",
              "type": "text"
            },
            {
              "code": "tokens",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "labels",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The value for the ",
                      "type": "text"
                    },
                    {
                      "code": "tokens",
                      "type": "codeVoice"
                    },
                    {
                      "text": " key is an array of words and punctuation in an individual sentence.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The value for ",
                      "type": "text"
                    },
                    {
                      "code": "labels",
                      "type": "codeVoice"
                    },
                    {
                      "text": " is an array of corresponding labels, or tags, for each of those tokens.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The arrays are the same length, resulting in a one-to-one mapping between each token and its corresponding label.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The JSON snippet below shows three pairs of tokenized sentences with their associated labels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// JSON file",
            "[",
            "    {",
            "        \"tokens\": [\"AirPods\", \"are\", \"a\", \"fantastic\", \"Apple\", \"product\", \".\"],",
            "        \"labels\": [\"PROD\", \"NONE\", \"NONE\", \"NONE\", \"ORG\", \"NONE\", \"NONE\"]",
            "    },",
            "    {",
            "        \"tokens\": [\"The\", \"iPhone\", \"takes\", \"stunning\", \"photos\", \".\"],",
            "        \"labels\": [\"NONE\", \"PROD\", \"NONE\", \"NONE\", \"NONE\", \"NONE\"]",
            "    },",
            "    {",
            "        \"tokens\": [\"Start\", \"building\", \"a\", \"native\", \"Mac\", \"app\", \"from\", \"your\", \"current\", \"iPad\", \"app\", \"using\", \"Mac\", \"Catalyst\", \".\"],",
            "        \"labels\": [\"NONE\", \"NONE\", \"NONE\", \"NONE\", \"PROD\", \"NONE\", \"NONE\", \"NONE\", \"NONE\", \"PROD\", \"NONE\", \"NONE\", \"PROD\", \"PROD\", \"NONE\"]",
            "    }",
            "]"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In a macOS playground, create the data table using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable/init(contentsOf:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import CreateML",
            "",
            "let data = try MLDataTable(contentsOf:",
            "    URL(fileURLWithPath: \"<#/path/to/read/data.json#>\"))"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The resulting data table has two columns, named ",
              "type": "text"
            },
            {
              "code": "tokens",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "labels",
              "type": "codeVoice"
            },
            {
              "text": ", derived from the keys in the JSON file. The column names can be anything, as long as they’re meaningful to you, because you’ll use them as parameters in other methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You’ll use the data you gathered for two critical tasks: model training and evaluation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Prepare-your-data-for-training-and-evaluation",
          "level": 3,
          "text": "Prepare your data for training and evaluation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you train your word tagger model, you need to evaluate how good it’s at its tagging task. To test the model’s performance, set aside part of your data in a testing dataset. Training and testing data must be entirely separate, with no overlap. This way, the metrics you calculate based on your testing data tell you how well the classifier performs on examples it hasn’t already seen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Generally, the testing dataset is significantly smaller than the training dataset. You might want to use about 80 percent of your overall data to train the model, and 20 percent to test it. However, it’s more important that the testing data is high-quality: as close as possible to real-world examples, well-distributed, and balanced. Use your best data for your testing data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "One way to generate training and testing data from your dataset is to use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable/randomSplit(by:seed:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This method splits your data into two tables, one for training and the other for testing. Specify a ",
              "type": "text"
            },
            {
              "code": "0.8",
              "type": "codeVoice"
            },
            {
              "text": " split to create a training data table that contains 80 percent of your data, and a testing data table that contains the remaining 20 percent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let (trainingData, testingData) = data.randomSplit(by: 0.8, seed: 5)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Although ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable/randomSplit(by:seed:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides a quick way to split your dataset, consider creating separate training and testing datasets manually. That way, you can ensure that your testing data is high quality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-and-train-the-word-tagger",
          "level": 3,
          "text": "Create and train the word tagger",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with your training data table and the names of your columns. Training begins immediately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let wordTagger = try MLWordTagger(trainingData: trainingData,",
            "                             tokenColumn: \"tokens\",",
            "                             labelColumn: \"labels\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Word tagger training requires setting aside a small subset of the training data as a validation dataset, to help keep track of training progress. The validation data allows the training process to gauge the model’s performance on examples the model hasn’t been trained on. Depending on the validation accuracy, the training algorithm could adjust values within the model or even stop the training process, if the accuracy is high enough.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Training and validation data must be entirely separate, with no overlap. If you want to make this split yourself, you can set aside around 5 to 10 percent of your training data as your validation data, and provide that data by setting custom model parameters. If you don’t do the split yourself, Create ML automatically sets aside a small percentage of the training data to use for validating the model’s progress during the training phase. Because the data is split randomly, you might get a different result each time you train the model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To see how accurately the model performed on the training and validation data, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics/taggingError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the model’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/trainingMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/validationMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Training accuracy as a percentage",
            "let trainingAccuracy = (1.0 - wordTagger.trainingMetrics.taggingError) * 100",
            "",
            "// Validation accuracy as a percentage",
            "let validationAccuracy = (1.0 - wordTagger.validationMetrics.taggingError) * 100"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Evaluate-the-taggers-accuracy",
          "level": 3,
          "text": "Evaluate the tagger’s accuracy",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Next, evaluate your trained model’s performance by testing it against sentences it’s never seen before. Pass your testing data table to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which returns an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let evaluationMetrics = wordTagger.evaluation(on: testingData,",
            "                                              tokenColumn: \"tokens\",",
            "                                              labelColumn: \"labels\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To get the evaluation accuracy, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics/taggingError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the returned ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Evaluation accuracy as a percentage",
            "let evaluationAccuracy = (1.0 - evaluationMetrics.taggingError) * 100"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the evaluation performance isn’t good enough, you may need to retrain with more data or make other adjustments. For information about improving model performance, see ",
              "type": "text"
            },
            {
              "code": "Improving Your Model’s Accuracy",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Save-the-Core-ML-model",
          "level": 3,
          "text": "Save the Core ML model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your model is performing well enough, you’re ready to save it so you can use it in your app. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLTextClassifier/write(to:metadata:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to write the Core ML model file (in this example, ",
              "type": "text"
            },
            {
              "code": "AppleTagger.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": ") to disk. Provide any information about the model, like its author, version, or description, in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CreateML/MLModelMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let metadata = MLModelMetadata(author: \"Jane Appleseed\",",
            "                               shortDescription: \"A model trained to tag Apple products.\",",
            "                               version: \"1.0\")",
            "",
            "try wordTagger.write(to: URL(fileURLWithPath: \"<#/path/to/save/AppleTagger.mlmodel#>\"),",
            "                              metadata: metadata)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-the-model-to-your-app",
          "level": 3,
          "text": "Add the model to your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With your app open in Xcode, drag the ",
              "type": "text"
            },
            {
              "code": "AppleTagger.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": " file into the navigation pane. Xcode compiles the model and generates an ",
              "type": "text"
            },
            {
              "code": "AppleTagger",
              "type": "codeVoice"
            },
            {
              "text": " class for use in your app. Select the ",
              "type": "text"
            },
            {
              "code": "AppleTagger.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": " file in Xcode to view additional information about the model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the Natural Language framework from the ",
              "type": "text"
            },
            {
              "code": "AppleTagger",
              "type": "codeVoice"
            },
            {
              "text": " to ensure that the tokenization is consistent between training and deployment. Attach the model to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to tag sentences or paragraphs, using an existing or custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import NaturalLanguage ",
            "import CoreML",
            "",
            "let text = \"The iPad is my favorite Apple product.\"",
            "",
            "do {",
            "    let mlModel = try AppleTagger(configuration: MLModelConfiguration()).model",
            "",
            "    let customModel = try NLModel(mlModel: mlModel)",
            "    let customTagScheme = NLTagScheme(\"Apple\")",
            "    ",
            "    let tagger = NLTagger(tagSchemes: [.nameType, customTagScheme])",
            "    tagger.string = text",
            "    tagger.setModels([customModel], forTagScheme: customTagScheme)",
            "    ",
            "    tagger.enumerateTags(in: text.startIndex..<text.endIndex, unit: .word, ",
            "                         scheme: customTagScheme, options: .omitWhitespace) { tag, tokenRange  in",
            "        if let tag = tag {",
            "            print(\"\\(text[tokenRange]): \\(tag.rawValue)\")",
            "        }",
            "        return true",
            "    }",
            "} catch {",
            "    print(error)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CreateML/MLDataTable": {
      "abstract": [
        {
          "text": "A table of data for training or evaluating a machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLDataTable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLDataTable",
      "type": "topic",
      "url": "/documentation/CreateML/MLDataTable"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLDataTable/init(contentsOf:options:)": {
      "abstract": [
        {
          "text": "Creates a data table from an imported JSON or CSV file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "contentsOf"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV14ParsingOptionsV",
          "text": "ParsingOptions"
        },
        {
          "kind": "text",
          "text": " = ParsingOptions()) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable/init(contentsOf:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(contentsOf:options:)",
      "type": "topic",
      "url": "/documentation/CreateML/MLDataTable/init(contentsOf:options:)"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLDataTable/randomSplit(by:seed:)": {
      "abstract": [
        {
          "text": "Creates two mutually exclusive, randomly divided subsets of the table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "randomSplit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "by"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "proportion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "seed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " = 1) -> ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLDataTable/randomSplit(by:seed:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "randomSplit(by:seed:)",
      "type": "topic",
      "url": "/documentation/CreateML/MLDataTable/randomSplit(by:seed:)"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLModelMetadata": {
      "abstract": [
        {
          "text": "Information about a model that’s stored in a Core ML model file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelMetadata"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLModelMetadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLModelMetadata",
      "type": "topic",
      "url": "/documentation/CreateML/MLModelMetadata"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLTextClassifier/write(to:metadata:)": {
      "abstract": [
        {
          "text": "Exports the text classifier as a Core ML model file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "fileURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML15MLModelMetadataV",
          "text": "MLModelMetadata"
        },
        {
          "kind": "text",
          "text": "? = nil) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLTextClassifier/write(to:metadata:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "write(to:metadata:)",
      "type": "topic",
      "url": "/documentation/CreateML/MLTextClassifier/write(to:metadata:)"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTagger": {
      "abstract": [
        {
          "text": "A word-tagging model you train to classify natural language text at the word level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordTagger"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLWordTagger",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTagger"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l": {
      "abstract": [
        {
          "text": "Computes evaluation metrics.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "labeledTokens"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tokenColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluation(on:tokenColumn:labelColumn:)",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/trainingMetrics": {
      "abstract": [
        {
          "text": "Measurements of the tagger’s performance on the training data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trainingMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/trainingMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "trainingMetrics",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTagger/trainingMetrics"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/validationMetrics": {
      "abstract": [
        {
          "text": "Measurements of the tagger’s performance on the validation data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTagger/validationMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationMetrics",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTagger/validationMetrics"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics": {
      "abstract": [
        {
          "text": "Metrics you use to evaluate a word tagger’s performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLWordTaggerMetrics",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTaggerMetrics"
    },
    "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics/taggingError": {
      "abstract": [
        {
          "text": "The fraction of incorrectly tagged examples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "taggingError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/MLWordTaggerMetrics/taggingError",
      "kind": "symbol",
      "role": "symbol",
      "title": "taggingError",
      "type": "topic",
      "url": "/documentation/CreateML/MLWordTaggerMetrics/taggingError"
    },
    "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to classify natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a text classifier model",
      "type": "topic",
      "url": "/documentation/CreateML/creating-a-text-classifier-model"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel": {
      "abstract": [
        {
          "text": "A custom model trained to classify or tag natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "role": "symbol",
      "title": "NLModel",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlmodel"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme": {
      "abstract": [
        {
          "text": "Constants for the tag schemes specified when initializing a linguistic tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagScheme"
        }
      ],
      "role": "symbol",
      "title": "NLTagScheme",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagscheme"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger": {
      "abstract": [
        {
          "text": "A tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "role": "symbol",
      "title": "NLTagger",
      "type": "topic",
      "url": "/documentation/naturallanguage/nltagger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Natural-language-models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/CreateML/creating-a-text-classifier-model",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel"
      ],
      "title": "Natural language models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Natural-language-models",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLModel"
              ],
              "title": "Natural language models"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/title",
          "value": "NLModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/title",
          "value": "NLTagger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagger/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/title",
          "value": "NLTagScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLTagScheme/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLTagScheme"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/creating-a-word-tagger-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/creating-a-word-tagger-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
