{
  "abstract": [
    {
      "text": "The distance between two strings in a text embedding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NLDistance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NLDistance"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NLDistance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NLDistance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLDistance"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The meaning of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is directly related to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " you use when you call a method that uses it. For example, if you use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType/cosine",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the ",
              "type": "text"
            },
            {
              "code": "distanceType",
              "type": "codeVoice"
            },
            {
              "text": " parameter, the method calculates the cosine distance and returns it as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance": {
      "abstract": [
        {
          "text": "The distance between two strings in a text embedding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLDistance"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLDistance"
        }
      ],
      "role": "symbol",
      "title": "NLDistance",
      "type": "topic",
      "url": "/documentation/naturallanguage/nldistance"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType": {
      "abstract": [
        {
          "text": "The means of calculating a distance between two locations in a text embedding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLDistanceType"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLDistanceType"
        }
      ],
      "role": "symbol",
      "title": "NLDistanceType",
      "type": "topic",
      "url": "/documentation/naturallanguage/nldistancetype"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType/cosine": {
      "abstract": [
        {
          "text": "A method of calculating distance by using cosine similarity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosine"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType/cosine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLDistanceTypeCosine"
        }
      ],
      "role": "symbol",
      "title": "NLDistanceType.cosine",
      "type": "topic",
      "url": "/documentation/naturallanguage/nldistancetype/cosine"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distance(between:and:distanceType:)": {
      "abstract": [
        {
          "text": "Calculates the distance between two strings in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "between"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "and"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "distanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLDistanceType",
          "text": "NLDistanceType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLDistance",
          "text": "NLDistance"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distance(between:and:distanceType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "distance(between:and:distanceType:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/distance(between:and:distancetype:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:": {
      "abstract": [
        {
          "text": "Calculates the distance between two strings in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "distanceBetweenString:andString:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "distanceBetweenString:andString:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "distanceBetweenString:andString:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/distancebetweenstring:andstring:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-6dy4x": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a location in the vocabulary space to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighbors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "maximumCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "distanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLDistanceType",
          "text": "NLDistanceType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLDistance",
          "text": "NLDistance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-6dy4x",
      "kind": "symbol",
      "role": "symbol",
      "title": "enumerateNeighbors(for:maximumCount:distanceType:using:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighbors(for:maximumcount:distancetype:using:)-6dy4x"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-72jda": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a string in the vocabulary to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighbors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maximumCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "distanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLDistanceType",
          "text": "NLDistanceType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLDistance",
          "text": "NLDistance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-72jda",
      "kind": "symbol",
      "role": "symbol",
      "title": "enumerateNeighbors(for:maximumCount:distanceType:using:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighbors(for:maximumcount:distancetype:using:)-72jda"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a string in the vocabulary to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforstring:maximumcount:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings, within a radius of a string in the vocabulary, to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforstring:maximumcount:maximumdistance:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings of a location in the vocabulary space to a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforvector:maximumcount:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:": {
      "abstract": [
        {
          "text": "Passes the nearest strings, within a radius of a location in the vocabulary space, to a block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/enumerateneighborsforvector:maximumcount:maximumdistance:distancetype:usingblock:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8f1jc": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a string in the vocabulary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neighbors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maximumCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "distanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLDistanceType",
          "text": "NLDistanceType"
        },
        {
          "kind": "text",
          "text": ") -> [("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLDistance",
          "text": "NLDistance"
        },
        {
          "kind": "text",
          "text": ")]"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8f1jc",
      "kind": "symbol",
      "role": "symbol",
      "title": "neighbors(for:maximumCount:distanceType:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighbors(for:maximumcount:distancetype:)-8f1jc"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8lp4z": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a location in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neighbors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "maximumCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "distanceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NLDistanceType",
          "text": "NLDistanceType"
        },
        {
          "kind": "text",
          "text": ") -> [("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLDistance",
          "text": "NLDistance"
        },
        {
          "kind": "text",
          "text": ")]"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8lp4z",
      "kind": "symbol",
      "role": "symbol",
      "title": "neighbors(for:maximumCount:distanceType:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighbors(for:maximumcount:distancetype:)-8lp4z"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a string in the vocabulary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForString:maximumCount:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforstring:maximumcount:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings, within a radius of a string, in the vocabulary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForString:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForString:maximumCount:maximumDistance:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforstring:maximumcount:maximumdistance:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings near a location in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForVector:maximumCount:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforvector:maximumcount:distancetype:"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:": {
      "abstract": [
        {
          "text": "Retrieves a limited number of strings within a radius of a location in the vocabulary space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "neighborsForVector:maximumCount:maximumDistance:distanceType:"
        }
      ],
      "role": "symbol",
      "title": "neighborsForVector:maximumCount:maximumDistance:distanceType:",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlembedding/neighborsforvector:maximumcount:maximumdistance:distancetype:"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Finding-strings-and-their-distances-in-an-embedding",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8f1jc",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighbors(for:maximumCount:distanceType:)-8lp4z",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-72jda",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighbors(for:maximumCount:distanceType:using:)-6dy4x",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distance(between:and:distanceType:)"
      ],
      "title": "Finding strings and their distances in an embedding"
    }
  ],
  "topicSections": [
    {
      "anchor": "Calculating-Distance",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType"
      ],
      "title": "Calculating Distance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLDistance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Calculating-Distance",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLDistanceType"
              ],
              "title": "Calculating Distance"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Finding-strings-and-their-distances-in-an-embedding",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:distanceType:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForString:maximumCount:maximumDistance:distanceType:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:distanceType:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/neighborsForVector:maximumCount:maximumDistance:distanceType:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:distanceType:usingBlock:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForString:maximumCount:maximumDistance:distanceType:usingBlock:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:distanceType:usingBlock:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/enumerateNeighborsForVector:maximumCount:maximumDistance:distanceType:usingBlock:",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLEmbedding/distanceBetweenString:andString:distanceType:"
              ],
              "title": "Finding strings and their distances in an embedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLDistance"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/title",
          "value": "NLDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/title",
          "value": "NLDistanceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistanceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType~1cosine/title",
          "value": "NLDistanceTypeCosine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLDistanceType~1cosine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLDistanceTypeCosine"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nldistance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nldistance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
