{
  "abstract": [
    {
      "text": "The writing scripts that the Natural Language framework supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NLScript",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NLScript"
      }
    ],
    "modules": [
      {
        "name": "Natural Language"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NLScript"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NLScript"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/naturallanguage"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding": {
      "abstract": [
        {
          "text": "A model that computes sequences of embedding vectors for natural language utterances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLContextualEmbedding"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLContextualEmbedding"
        }
      ],
      "role": "symbol",
      "title": "NLContextualEmbedding",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlcontextualembedding"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey": {
      "abstract": [
        {
          "text": "Contextual embedding keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLContextualEmbeddingKey"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLContextualEmbeddingKey"
        }
      ],
      "role": "symbol",
      "title": "NLContextualEmbeddingKey",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlcontextualembeddingkey"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript": {
      "abstract": [
        {
          "text": "The writing scripts that the Natural Language framework supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScript"
        }
      ],
      "role": "symbol",
      "title": "NLScript",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Arabic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arabic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptArabic"
        }
      ],
      "role": "symbol",
      "title": "arabic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/arabic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian": {
      "abstract": [
        {
          "text": "The unique identifier string for the Armenian script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "armenian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptArmenian"
        }
      ],
      "role": "symbol",
      "title": "armenian",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/armenian"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali": {
      "abstract": [
        {
          "text": "The unique identifier string for the Bengali script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bengali"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptBengali"
        }
      ],
      "role": "symbol",
      "title": "bengali",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/bengali"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics": {
      "abstract": [
        {
          "text": "The unique identifier string for the Canadian Aboriginal Syllabics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canadianAboriginalSyllabics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCanadianAboriginalSyllabics"
        }
      ],
      "role": "symbol",
      "title": "canadianAboriginalSyllabics",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/canadianaboriginalsyllabics"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee": {
      "abstract": [
        {
          "text": "The unique identifier string for the Cherokee script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cherokee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCherokee"
        }
      ],
      "role": "symbol",
      "title": "cherokee",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/cherokee"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Cyrillic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cyrillic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptCyrillic"
        }
      ],
      "role": "symbol",
      "title": "cyrillic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/cyrillic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari": {
      "abstract": [
        {
          "text": "The unique identifier string for the Devanagari script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devanagari"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptDevanagari"
        }
      ],
      "role": "symbol",
      "title": "devanagari",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/devanagari"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic": {
      "abstract": [
        {
          "text": "The unique identifier string for the Ethiopic script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ethiopic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptEthiopic"
        }
      ],
      "role": "symbol",
      "title": "ethiopic",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/ethiopic"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian": {
      "abstract": [
        {
          "text": "The unique identifier string for the Georgian script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "georgian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGeorgian"
        }
      ],
      "role": "symbol",
      "title": "georgian",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/georgian"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek": {
      "abstract": [
        {
          "text": "The unique identifier string for the Greek script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "greek"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGreek"
        }
      ],
      "role": "symbol",
      "title": "greek",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/greek"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati": {
      "abstract": [
        {
          "text": "The unique identifier string for the Gujarati script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gujarati"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGujarati"
        }
      ],
      "role": "symbol",
      "title": "gujarati",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/gujarati"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi": {
      "abstract": [
        {
          "text": "The unique identifier string for the Gurmukhi script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gurmukhi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptGurmukhi"
        }
      ],
      "role": "symbol",
      "title": "gurmukhi",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/gurmukhi"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew": {
      "abstract": [
        {
          "text": "The unique identifier string for the Hebrew script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hebrew"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptHebrew"
        }
      ],
      "role": "symbol",
      "title": "hebrew",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/hebrew"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(_:)": {
      "abstract": [
        {
          "text": "Creates a language script with the given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/init(_:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a language script with the given string as its raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/init(rawvalue:)"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese": {
      "abstract": [
        {
          "text": "The unique identifier string for the Japanese script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "japanese"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptJapanese"
        }
      ],
      "role": "symbol",
      "title": "japanese",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/japanese"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada": {
      "abstract": [
        {
          "text": "The unique identifier string for the Kannada script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kannada"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptKannada"
        }
      ],
      "role": "symbol",
      "title": "kannada",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/kannada"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer": {
      "abstract": [
        {
          "text": "The unique identifier string for the Khmer script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "khmer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptKhmer"
        }
      ],
      "role": "symbol",
      "title": "khmer",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/khmer"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/korean": {
      "abstract": [
        {
          "text": "The unique identifier string for the Korean script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "korean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/korean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptKorean"
        }
      ],
      "role": "symbol",
      "title": "korean",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/korean"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/lao": {
      "abstract": [
        {
          "text": "The unique identifier string for the Lao script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lao"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/lao",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptLao"
        }
      ],
      "role": "symbol",
      "title": "lao",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/lao"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/latin": {
      "abstract": [
        {
          "text": "The unique identifier string for the Latin script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/latin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptLatin"
        }
      ],
      "role": "symbol",
      "title": "latin",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/latin"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/malayalam": {
      "abstract": [
        {
          "text": "The unique identifier string for the Malayalam script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "malayalam"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/malayalam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptMalayalam"
        }
      ],
      "role": "symbol",
      "title": "malayalam",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/malayalam"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/mongolian": {
      "abstract": [
        {
          "text": "The unique identifier string for the Mongolian script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mongolian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/mongolian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptMongolian"
        }
      ],
      "role": "symbol",
      "title": "mongolian",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/mongolian"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/myanmar": {
      "abstract": [
        {
          "text": "The unique identifier string for the Myanmar script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "myanmar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/myanmar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptMyanmar"
        }
      ],
      "role": "symbol",
      "title": "myanmar",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/myanmar"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/oriya": {
      "abstract": [
        {
          "text": "The unique identifier string for the Oriya script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oriya"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/oriya",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptOriya"
        }
      ],
      "role": "symbol",
      "title": "oriya",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/oriya"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/simplifiedChinese": {
      "abstract": [
        {
          "text": "The unique identifier string for the simplified Chinese script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simplifiedChinese"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/simplifiedChinese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptSimplifiedChinese"
        }
      ],
      "role": "symbol",
      "title": "simplifiedChinese",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/simplifiedchinese"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/sinhala": {
      "abstract": [
        {
          "text": "The unique identifier string for the Sinhala script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sinhala"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/sinhala",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptSinhala"
        }
      ],
      "role": "symbol",
      "title": "sinhala",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/sinhala"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tamil": {
      "abstract": [
        {
          "text": "The unique identifier string for the Tamil script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tamil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tamil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptTamil"
        }
      ],
      "role": "symbol",
      "title": "tamil",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/tamil"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/telugu": {
      "abstract": [
        {
          "text": "The unique identifier string for the Telugu script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telugu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/telugu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptTelugu"
        }
      ],
      "role": "symbol",
      "title": "telugu",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/telugu"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/thai": {
      "abstract": [
        {
          "text": "The unique identifier string for the Thai script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thai"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/thai",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptThai"
        }
      ],
      "role": "symbol",
      "title": "thai",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/thai"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tibetan": {
      "abstract": [
        {
          "text": "The unique identifier string for the Tibetan script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tibetan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tibetan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptTibetan"
        }
      ],
      "role": "symbol",
      "title": "tibetan",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/tibetan"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/traditionalChinese": {
      "abstract": [
        {
          "text": "The unique identifier string for the traditional Chinese script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traditionalChinese"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/traditionalChinese",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptTraditionalChinese"
        }
      ],
      "role": "symbol",
      "title": "traditionalChinese",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/traditionalchinese"
    },
    "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/undetermined": {
      "abstract": [
        {
          "text": "The unique identifier string for a script the Natural Language framework doesn’t recognize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undetermined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLScript",
          "text": "NLScript"
        }
      ],
      "identifier": "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/undetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NLScriptUndetermined"
        }
      ],
      "role": "symbol",
      "title": "undetermined",
      "type": "topic",
      "url": "/documentation/naturallanguage/nlscript/undetermined"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contextual-embedding",
      "generated": true,
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey"
      ],
      "title": "Contextual embedding"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-standard-scripts",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/korean",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/lao",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/latin",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/malayalam",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/mongolian",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/myanmar",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/oriya",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/simplifiedChinese",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/sinhala",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tamil",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/telugu",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/thai",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tibetan",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/traditionalChinese",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/undetermined"
      ],
      "title": "Getting standard scripts"
    },
    {
      "anchor": "Creating-custom-script-tags",
      "identifiers": [
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(_:)",
        "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/init(rawValue:)"
      ],
      "title": "Creating custom script tags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NLScript"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-standard-scripts",
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/arabic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/armenian",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/bengali",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/canadianAboriginalSyllabics",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cherokee",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/cyrillic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/devanagari",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/ethiopic",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/georgian",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/greek",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gujarati",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/gurmukhi",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/hebrew",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/japanese",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/kannada",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/khmer",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/korean",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/lao",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/latin",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/malayalam",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/mongolian",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/myanmar",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/oriya",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/simplifiedChinese",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/sinhala",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tamil",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/telugu",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/thai",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/tibetan",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/traditionalChinese",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLScript/undetermined"
              ],
              "title": "Getting standard scripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contextual-embedding",
              "generated": true,
              "identifiers": [
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbedding",
                "doc://com.apple.naturallanguage/documentation/NaturalLanguage/NLContextualEmbeddingKey"
              ],
              "title": "Contextual embedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NLScript"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/title",
          "value": "NLContextualEmbedding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbedding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbedding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1armenian/title",
          "value": "NLScriptArmenian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1armenian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptArmenian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1oriya/title",
          "value": "NLScriptOriya"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1oriya/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptOriya"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/title",
          "value": "NLScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1greek/title",
          "value": "NLScriptGreek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1greek/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGreek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1undetermined/title",
          "value": "NLScriptUndetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1undetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptUndetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/title",
          "value": "NLContextualEmbeddingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbeddingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLContextualEmbeddingKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NLContextualEmbeddingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1bengali/title",
          "value": "NLScriptBengali"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1bengali/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptBengali"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cyrillic/title",
          "value": "NLScriptCyrillic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cyrillic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCyrillic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1lao/title",
          "value": "NLScriptLao"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1lao/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptLao"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1traditionalChinese/title",
          "value": "NLScriptTraditionalChinese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1traditionalChinese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptTraditionalChinese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1sinhala/title",
          "value": "NLScriptSinhala"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1sinhala/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptSinhala"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1tibetan/title",
          "value": "NLScriptTibetan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1tibetan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptTibetan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1myanmar/title",
          "value": "NLScriptMyanmar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1myanmar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptMyanmar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1malayalam/title",
          "value": "NLScriptMalayalam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1malayalam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptMalayalam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1simplifiedChinese/title",
          "value": "NLScriptSimplifiedChinese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1simplifiedChinese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptSimplifiedChinese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1tamil/title",
          "value": "NLScriptTamil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1tamil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptTamil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gurmukhi/title",
          "value": "NLScriptGurmukhi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gurmukhi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGurmukhi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1mongolian/title",
          "value": "NLScriptMongolian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1mongolian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptMongolian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gujarati/title",
          "value": "NLScriptGujarati"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1gujarati/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGujarati"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cherokee/title",
          "value": "NLScriptCherokee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1cherokee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCherokee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1latin/title",
          "value": "NLScriptLatin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1latin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptLatin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1canadianAboriginalSyllabics/title",
          "value": "NLScriptCanadianAboriginalSyllabics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1canadianAboriginalSyllabics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptCanadianAboriginalSyllabics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1khmer/title",
          "value": "NLScriptKhmer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1khmer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKhmer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1devanagari/title",
          "value": "NLScriptDevanagari"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1devanagari/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptDevanagari"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1japanese/title",
          "value": "NLScriptJapanese"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1japanese/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptJapanese"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1thai/title",
          "value": "NLScriptThai"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1thai/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptThai"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1hebrew/title",
          "value": "NLScriptHebrew"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1hebrew/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptHebrew"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1korean/title",
          "value": "NLScriptKorean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1korean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKorean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1kannada/title",
          "value": "NLScriptKannada"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1kannada/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptKannada"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1ethiopic/title",
          "value": "NLScriptEthiopic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1ethiopic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptEthiopic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1georgian/title",
          "value": "NLScriptGeorgian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1georgian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptGeorgian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1arabic/title",
          "value": "NLScriptArabic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1arabic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptArabic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1telugu/title",
          "value": "NLScriptTelugu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.naturallanguage~1documentation~1NaturalLanguage~1NLScript~1telugu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NLScriptTelugu"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/naturallanguage/nlscript"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/naturallanguage/nlscript"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
