{
  "abstract": [
    {
      "text": "A characteristic type identifier for the user’s blood type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/bloodType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "c:@HKCharacteristicTypeIdentifierBloodType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bloodType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
        "text": "HKCharacteristicTypeIdentifier"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCharacteristicTypeIdentifierBloodType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bloodType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bloodType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
              "text": "HKCharacteristicTypeIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This type uses values from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enum.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType": {
      "abstract": [
        {
          "text": "Constants indicating the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodType"
        }
      ],
      "role": "symbol",
      "title": "HKBloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject": {
      "abstract": [
        {
          "text": "This class acts as a wrapper for the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " enumeration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBloodTypeObject"
        }
      ],
      "role": "symbol",
      "title": "HKBloodTypeObject",
      "type": "topic",
      "url": "/documentation/healthkit/hkbloodtypeobject"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType": {
      "abstract": [
        {
          "text": "A type that represents data that doesn’t typically change over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCharacteristicType"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicType"
        }
      ],
      "role": "symbol",
      "title": "HKCharacteristicType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier": {
      "abstract": [
        {
          "text": "The identifiers that create characteristic type objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "HKCharacteristicTypeIdentifier",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/activityMoveMode": {
      "abstract": [
        {
          "text": "A characteristic identifier for the user’s activity mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityMoveMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/activityMoveMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierActivityMoveMode"
        }
      ],
      "role": "symbol",
      "title": "activityMoveMode",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/activitymovemode"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/biologicalSex": {
      "abstract": [
        {
          "text": "A characteristic type identifier for the user’s sex.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "biologicalSex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/biologicalSex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierBiologicalSex"
        }
      ],
      "role": "symbol",
      "title": "biologicalSex",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/biologicalsex"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/bloodType": {
      "abstract": [
        {
          "text": "A characteristic type identifier for the user’s blood type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bloodType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/bloodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierBloodType"
        }
      ],
      "role": "symbol",
      "title": "bloodType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/bloodtype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/dateOfBirth": {
      "abstract": [
        {
          "text": "A characteristic type identifier for the user’s date of birth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateOfBirth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/dateOfBirth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierDateOfBirth"
        }
      ],
      "role": "symbol",
      "title": "dateOfBirth",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/dateofbirth"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/fitzpatrickSkinType": {
      "abstract": [
        {
          "text": "A characteristic type identifier for the user’s skin type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fitzpatrickSkinType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/fitzpatrickSkinType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierFitzpatrickSkinType"
        }
      ],
      "role": "symbol",
      "title": "fitzpatrickSkinType",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/fitzpatrickskintype"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/wheelchairUse": {
      "abstract": [
        {
          "text": "A characteristic identifier for the user’s use of a wheelchair.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wheelchairUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
          "text": "HKCharacteristicTypeIdentifier"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/wheelchairUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCharacteristicTypeIdentifierWheelchairUse"
        }
      ],
      "role": "symbol",
      "title": "wheelchairUse",
      "type": "topic",
      "url": "/documentation/healthkit/hkcharacteristictypeidentifier/wheelchairuse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Characteristic-identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/activityMoveMode",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/biologicalSex",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/dateOfBirth",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/fitzpatrickSkinType",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/wheelchairUse"
      ],
      "title": "Characteristic identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCharacteristicTypeIdentifierBloodType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBloodTypeObject"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Characteristic-identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/activityMoveMode",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/biologicalSex",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/dateOfBirth",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/fitzpatrickSkinType",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier/wheelchairUse"
              ],
              "title": "Characteristic identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCharacteristicTypeIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@HKCharacteristicTypeIdentifier",
                    "text": "HKCharacteristicTypeIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "HKCharacteristicTypeIdentifierBloodType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1activityMoveMode/title",
          "value": "HKCharacteristicTypeIdentifierActivityMoveMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1activityMoveMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierActivityMoveMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/title",
          "value": "HKCharacteristicType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier/title",
          "value": "HKCharacteristicTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/title",
          "value": "HKBloodTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodTypeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/title",
          "value": "HKBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBloodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1biologicalSex/title",
          "value": "HKCharacteristicTypeIdentifierBiologicalSex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1biologicalSex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierBiologicalSex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1dateOfBirth/title",
          "value": "HKCharacteristicTypeIdentifierDateOfBirth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1dateOfBirth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierDateOfBirth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1wheelchairUse/title",
          "value": "HKCharacteristicTypeIdentifierWheelchairUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1wheelchairUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierWheelchairUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1bloodType/title",
          "value": "HKCharacteristicTypeIdentifierBloodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1bloodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierBloodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1fitzpatrickSkinType/title",
          "value": "HKCharacteristicTypeIdentifierFitzpatrickSkinType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCharacteristicTypeIdentifier~1fitzpatrickSkinType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCharacteristicTypeIdentifierFitzpatrickSkinType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcharacteristictypeidentifier/bloodtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcharacteristictypeidentifier/bloodtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
