{
  "abstract": [
    {
      "text": "The media isn’t available in the user’s geographic location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/regionRestriction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPlayMediaMediaItemUnsupportedReason@INPlayMediaMediaItemUnsupportedReasonRegionRestriction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "regionRestriction"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INPlayMediaMediaItemUnsupportedReason.regionRestriction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "regionRestriction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason": {
      "abstract": [
        {
          "text": "Reasons the app can’t play the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/cellularDataSettings": {
      "abstract": [
        {
          "text": "The cellular data settings don’t allow the user to play the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularDataSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/cellularDataSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonCellularDataSettings"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.cellularDataSettings",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/cellulardatasettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/explicitContentSettings": {
      "abstract": [
        {
          "text": "The content settings don’t allow the user to play the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "explicitContentSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/explicitContentSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonExplicitContentSettings"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.explicitContentSettings",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/explicitcontentsettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/loginRequired": {
      "abstract": [
        {
          "text": "The user must log in to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loginRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/loginRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonLoginRequired"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.loginRequired",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/loginrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/regionRestriction": {
      "abstract": [
        {
          "text": "The media isn’t available in the user’s geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionRestriction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/regionRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.regionRestriction",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/regionrestriction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/restrictedContent": {
      "abstract": [
        {
          "text": "The media item is restricted content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/restrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.restrictedContent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/restrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/serviceUnavailable": {
      "abstract": [
        {
          "text": "The app can’t add the item because its media service isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/serviceunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/subscriptionRequired": {
      "abstract": [
        {
          "text": "The user must have a subscription to the app’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/subscriptionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonSubscriptionRequired"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.subscriptionRequired",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/subscriptionrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/unsupportedMediaType": {
      "abstract": [
        {
          "text": "The media’s type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/unsupportedMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaMediaItemUnsupportedReason.unsupportedMediaType",
      "type": "topic",
      "url": "/documentation/intents/inplaymediamediaitemunsupportedreason/unsupportedmediatype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Limitations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/loginRequired",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/subscriptionRequired",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/unsupportedMediaType",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/explicitContentSettings",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/cellularDataSettings",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/restrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/serviceUnavailable"
      ],
      "title": "Limitations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Limitations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/loginRequired",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/subscriptionRequired",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/unsupportedMediaType",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/explicitContentSettings",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/cellularDataSettings",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/restrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaMediaItemUnsupportedReason/serviceUnavailable"
              ],
              "title": "Limitations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1regionRestriction/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1regionRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1cellularDataSettings/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonCellularDataSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1cellularDataSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonCellularDataSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1serviceUnavailable/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1loginRequired/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonLoginRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1loginRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonLoginRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1subscriptionRequired/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1subscriptionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1explicitContentSettings/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonExplicitContentSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1explicitContentSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonExplicitContentSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason/title",
          "value": "INPlayMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1unsupportedMediaType/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1unsupportedMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonUnsupportedMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1restrictedContent/title",
          "value": "INPlayMediaMediaItemUnsupportedReasonRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaMediaItemUnsupportedReason~1restrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaMediaItemUnsupportedReasonRestrictedContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaymediamediaitemunsupportedreason/regionrestriction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaymediamediaitemunsupportedreason/regionrestriction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
