{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeSpeedLimitSetting:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPInstrumentClusterControllerDelegate(im)instrumentClusterController:didChangeSpeedLimitSetting:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "instrumentClusterController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
        "text": "CPInstrumentClusterController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didChangeSpeedLimitSetting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CPInstrumentClusterSetting",
        "text": "CPInstrumentClusterSetting"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "instrumentClusterController:didChangeSpeedLimitSetting:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "instrumentClusterController(_:didChangeSpeedLimitSetting:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "instrumentClusterController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
              "text": "CPInstrumentClusterController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didChangeSpeedLimitSetting"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "speedLimitSetting"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CPInstrumentClusterSetting",
              "text": "CPInstrumentClusterSetting"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterController"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterController"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterController",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontroller"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterControllerDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeCompassSetting:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
          "text": "CPInstrumentClusterController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChangeCompassSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPInstrumentClusterSetting",
          "text": "CPInstrumentClusterSetting"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeCompassSetting:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterController:didChangeCompassSetting:"
        }
      ],
      "role": "symbol",
      "title": "instrumentClusterController(_:didChangeCompassSetting:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontroller(_:didchangecompasssetting:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeSpeedLimitSetting:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
          "text": "CPInstrumentClusterController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didChangeSpeedLimitSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPInstrumentClusterSetting",
          "text": "CPInstrumentClusterSetting"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeSpeedLimitSetting:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterController:didChangeSpeedLimitSetting:"
        }
      ],
      "role": "symbol",
      "title": "instrumentClusterController(_:didChangeSpeedLimitSetting:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontroller(_:didchangespeedlimitsetting:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidConnect(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidConnect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidConnect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidConnectWindow:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "instrumentClusterControllerDidConnect(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontrollerdidconnect(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidDisconnectWindow(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidDisconnectWindow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidDisconnectWindow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidDisconnectWindow:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "instrumentClusterControllerDidDisconnectWindow(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontrollerdiddisconnectwindow(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoom(in:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidZoom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
          "text": "CPInstrumentClusterController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoom(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidZoomIn:"
        }
      ],
      "role": "symbol",
      "title": "instrumentClusterControllerDidZoom(in:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontrollerdidzoom(in:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoomOut(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidZoomOut"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
          "text": "CPInstrumentClusterController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoomOut(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instrumentClusterControllerDidZoomOut:"
        }
      ],
      "role": "symbol",
      "title": "instrumentClusterControllerDidZoomOut(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontrollerdidzoomout(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeCompassSetting:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidConnect(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidDisconnectWindow(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoom(in:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoomOut(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "instrumentClusterController:didChangeSpeedLimitSetting:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterController:didChangeSpeedLimitSetting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterController(_:didChangeCompassSetting:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidConnect(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidDisconnectWindow(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoom(in:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterControllerDelegate/instrumentClusterControllerDidZoomOut(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "instrumentClusterController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPInstrumentClusterController",
                    "text": "CPInstrumentClusterController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "instrumentClusterController"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didChangeSpeedLimitSetting:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CPInstrumentClusterSetting",
                    "text": "CPInstrumentClusterSetting"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "speedLimitSetting"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidZoomOut(_:)/title",
          "value": "instrumentClusterControllerDidZoomOut:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidZoomOut(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterControllerDidZoomOut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidDisconnectWindow(_:)/title",
          "value": "instrumentClusterControllerDidDisconnectWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidDisconnectWindow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterControllerDidDisconnectWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate/title",
          "value": "CPInstrumentClusterControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterController(_:didChangeSpeedLimitSetting:)/title",
          "value": "instrumentClusterController:didChangeSpeedLimitSetting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterController(_:didChangeSpeedLimitSetting:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterController:didChangeSpeedLimitSetting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterController/title",
          "value": "CPInstrumentClusterController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/title",
          "value": "CPInstrumentClusterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidConnect(_:)/title",
          "value": "instrumentClusterControllerDidConnectWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidConnect(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterControllerDidConnectWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterController(_:didChangeCompassSetting:)/title",
          "value": "instrumentClusterController:didChangeCompassSetting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterController(_:didChangeCompassSetting:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterController:didChangeCompassSetting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidZoom(in:)/title",
          "value": "instrumentClusterControllerDidZoomIn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterControllerDelegate~1instrumentClusterControllerDidZoom(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "instrumentClusterControllerDidZoomIn:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontroller(_:didchangespeedlimitsetting:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustercontrollerdelegate/instrumentclustercontroller(_:didchangespeedlimitsetting:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
