{
  "abstract": [
    {
      "text": "Allows the receiver to prepare resources in advance of capturing a still image bracket.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use AVCapturePhotoOutput setPreparedPhotoSettingsArray:completionHandler: instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:objc(cs)AVCaptureStillImageOutput(im)prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "prepareToCaptureStillImageBracket"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "from"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
        "text": "AVCaptureConnection"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "withSettingsArray"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
        "text": "AVCaptureBracketedStillImageSettings"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use AVCapturePhotoOutput setPreparedPhotoSettingsArray:completionHandler: instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use AVCapturePhotoOutput setPreparedPhotoSettingsArray:completionHandler: instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use AVCapturePhotoOutput setPreparedPhotoSettingsArray:completionHandler: instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "prepareToCaptureStillImageBracket"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "from"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "connection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureConnection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
              "text": "AVCaptureConnection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "withSettingsArray"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "settings"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
              "text": "AVCaptureBracketedStillImageSettings"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The connection through which the still image bracket should be captured.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "connection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects. All the array items must be of the same ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " subclass, or an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " exception is thrown.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "settings"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A user provided block that will be called asynchronously once resources have successfully been allocated for the specified bracketed capture operation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The block has two parameters:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "If sufficient resources could not be allocated, this parameter is ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.documentation/documentation/swift/false",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": ", and the ",
                            "type": "text"
                          },
                          {
                            "code": "error",
                            "type": "codeVoice"
                          },
                          {
                            "text": " parameter contains a non-",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " error value.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "prepared",
                        "type": "text"
                      }
                    ]
                  }
                },
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The value is non-",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " if an error is encountered.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "error",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            },
            {
              "inlineContent": [
                {
                  "text": "If the count of the ",
                  "type": "text"
                },
                {
                  "code": "settings",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter exceeds ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", then ",
                  "type": "text"
                },
                {
                  "code": "AVErrorMaximumStillImageCaptureRequestsExceeded",
                  "type": "codeVoice"
                },
                {
                  "text": " is returned.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "You should not assume that the completion handler will be called on a specific thread.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before taking a still image bracket, additional resources may need to be allocated. By calling this method first, you are able to know when the receiver is ready to capture the bracket with the specified settings array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings": {
      "abstract": [
        {
          "text": "The abstract superclass for bracketed photo capture settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureBracketedStillImageSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureBracketedStillImageSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureBracketedStillImageSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturebracketedstillimagesettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureConnection": {
      "abstract": [
        {
          "text": "An object that represents a connection from a capture input to a capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureConnection"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureConnection"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureConnection",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureconnection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput": {
      "abstract": [
        {
          "text": "A capture output for capturing still photos.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureStillImageOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureStillImageOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureStillImageOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageAsynchronously(from:completionHandler:)": {
      "abstract": [
        {
          "text": "Initiates a still image capture and returns immediately.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureStillImageAsynchronously"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
          "text": "AVCaptureConnection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageAsynchronously(from:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureStillImageAsynchronouslyFromConnection:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "captureStillImageAsynchronously(from:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/capturestillimageasynchronously(from:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)": {
      "abstract": [
        {
          "text": "Captures a still image bracket.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureStillImageBracketAsynchronously"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
          "text": "AVCaptureConnection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSettingsArray"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureStillImageBracketAsynchronouslyFromConnection:withSettingsArray:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/capturestillimagebracketasynchronously(from:withsettingsarray:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to stabilize the lens across the duration of a bracketed capture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLensStabilizationDuringBracketedCaptureEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lensStabilizationDuringBracketedCaptureEnabled"
        }
      ],
      "role": "symbol",
      "title": "isLensStabilizationDuringBracketedCaptureEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/islensstabilizationduringbracketedcaptureenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the capture output supports lens stabilization across the duration of a bracketed capture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLensStabilizationDuringBracketedCaptureSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lensStabilizationDuringBracketedCaptureSupported"
        }
      ],
      "role": "symbol",
      "title": "isLensStabilizationDuringBracketedCaptureSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/islensstabilizationduringbracketedcapturesupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount": {
      "abstract": [
        {
          "text": "Specifies the maximum number of still images that may be taken in a single bracket.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxBracketedCaptureStillImageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxBracketedCaptureStillImageCount"
        }
      ],
      "role": "symbol",
      "title": "maxBracketedCaptureStillImageCount",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/maxbracketedcapturestillimagecount"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)": {
      "abstract": [
        {
          "text": "Allows the receiver to prepare resources in advance of capturing a still image bracket.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareToCaptureStillImageBracket"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
          "text": "AVCaptureConnection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSettingsArray"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturestillimageoutput/preparetocapturestillimagebracket(from:withsettingsarray:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception": {
      "abstract": [
        {
          "text": "Name of an exception that occurs when you pass an invalid argument to a method, such as a `nil` pointer where a non-`nil` object is required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "invalidArgumentException"
        },
        {
          "kind": "text",
          "text": ": NSExceptionName"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidArgumentException",
      "type": "topic",
      "url": "/documentation/foundation/nsexceptionname/1415426-invalidargumentexception"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageAsynchronously(from:completionHandler:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Still-Image-Bracketed-Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureEnabled"
      ],
      "title": "Still Image Bracketed Capture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageAsynchronously(from:completionHandler:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Still-Image-Bracketed-Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/isLensStabilizationDuringBracketedCaptureEnabled"
              ],
              "title": "Still Image Bracketed Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "prepareToCaptureStillImageBracketFromConnection:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureConnection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCaptureConnection",
                    "text": "AVCaptureConnection"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "connection"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withSettingsArray:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<__kindof AVCaptureBracketedStillImageSettings *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "settings"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "prepared"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "handler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The connection through which the still image bracket should be captured.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "connection"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects. All the array items must be of the same ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " subclass, or an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname/1415426-invalidargumentexception",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " exception is thrown.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "settings"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A user provided block that will be called asynchronously once resources have successfully been allocated for the specified bracketed capture operation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The block has two parameters:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "If sufficient resources could not be allocated, this parameter is ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": ", and the ",
                                  "type": "text"
                                },
                                {
                                  "code": "error",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " parameter contains a non-",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " error value.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "prepared",
                              "type": "text"
                            }
                          ]
                        }
                      },
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The value is non-",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " if an error is encountered.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "error",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "If the count of the ",
                        "type": "text"
                      },
                      {
                        "code": "settings",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter exceeds ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput/maxBracketedCaptureStillImageCount",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", then ",
                        "type": "text"
                      },
                      {
                        "code": "AVErrorMaximumStillImageCaptureRequestsExceeded",
                        "type": "codeVoice"
                      },
                      {
                        "text": " is returned.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "You should not assume that the completion handler will be called on a specific thread.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "handler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use AVCapturePhotoOutput setPreparedPhotoSettingsArray:completionHandler: instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1isLensStabilizationDuringBracketedCaptureSupported/title",
          "value": "lensStabilizationDuringBracketedCaptureSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1isLensStabilizationDuringBracketedCaptureSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lensStabilizationDuringBracketedCaptureSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)/title",
          "value": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1prepareToCaptureStillImageBracket(from:withSettingsArray:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareToCaptureStillImageBracketFromConnection:withSettingsArray:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureConnection/title",
          "value": "AVCaptureConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1maxBracketedCaptureStillImageCount/title",
          "value": "maxBracketedCaptureStillImageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1maxBracketedCaptureStillImageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxBracketedCaptureStillImageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/title",
          "value": "AVCaptureBracketedStillImageSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1isLensStabilizationDuringBracketedCaptureEnabled/title",
          "value": "lensStabilizationDuringBracketedCaptureEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1isLensStabilizationDuringBracketedCaptureEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lensStabilizationDuringBracketedCaptureEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/title",
          "value": "AVCaptureStillImageOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureStillImageOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureStillImageOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11415426-invalidargumentexception/title",
          "value": "NSInvalidArgumentException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)/title",
          "value": "captureStillImageBracketAsynchronouslyFromConnection:withSettingsArray:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1captureStillImageBracketAsynchronously(from:withSettingsArray:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureStillImageBracketAsynchronouslyFromConnection:withSettingsArray:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1captureStillImageAsynchronously(from:completionHandler:)/title",
          "value": "captureStillImageAsynchronouslyFromConnection:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput~1captureStillImageAsynchronously(from:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureStillImageAsynchronouslyFromConnection:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturestillimageoutput/preparetocapturestillimagebracket(from:withsettingsarray:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturestillimageoutput/preparetocapturestillimagebracket(from:withsettingsarray:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
