{
  "abstract": [
    {
      "text": "An attribute that stores a decimal value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/decimalAttributeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSAttributeType@NSDecimalAttributeType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "decimalAttributeType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDecimalAttributeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSAttributeType.decimalAttributeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "decimalAttributeType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdecimalnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when reading and writing attributes of this type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType": {
      "abstract": [
        {
          "text": "The types of attribute that Core Data supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/URIAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a uniform resource identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "URIAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/URIAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSURIAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.URIAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/uriattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/UUIDAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a universally unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UUIDAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/UUIDAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUUIDAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.UUIDAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/uuidattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/binaryDataAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores binary data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "binaryDataAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/binaryDataAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBinaryDataAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.binaryDataAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/binarydataattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/booleanAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "booleanAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/booleanAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBooleanAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.booleanAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/booleanattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/compositeAttributeType": {
      "abstract": [
        {
          "text": "An attribute that derives its value by composing other attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositeAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/compositeAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositeAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.compositeAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/compositeattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/dateAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/dateAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDateAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.dateAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/dateattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/decimalAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a decimal value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decimalAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/decimalAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDecimalAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.decimalAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/decimalattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/doubleAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a double value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/doubleAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDoubleAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.doubleAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/doubleattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/floatAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a float value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/floatAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFloatAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.floatAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/floatattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer16AttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a 16-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer16AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer16AttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInteger16AttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.integer16AttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/integer16attributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer32AttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a 32-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer32AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer32AttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInteger32AttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.integer32AttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/integer32attributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer64AttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a 64-bit signed integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integer64AttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer64AttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInteger64AttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.integer64AttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/integer64attributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/objectIDAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a managed object’s ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectIDAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/objectIDAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSObjectIDAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.objectIDAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/objectidattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/stringAttributeType": {
      "abstract": [
        {
          "text": "An attribute that stores a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/stringAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.stringAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/stringattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/transformableAttributeType": {
      "abstract": [
        {
          "text": "An attribute that uses a value transformer to derive its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transformableAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/transformableAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTransformableAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.transformableAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/transformableattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/undefinedAttributeType": {
      "abstract": [
        {
          "text": "An attribute that doesn’t have an explicit type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefinedAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/undefinedAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUndefinedAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType.undefinedAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype/undefinedattributetype"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdecimalnumber": {
      "abstract": [
        {
          "text": "An object for representing and performing arithmetic on base-10 numbers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDecimalNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdecimalnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDecimalNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsdecimalnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Attribute-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/binaryDataAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/booleanAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/compositeAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/dateAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/doubleAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/floatAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer16AttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer32AttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer64AttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/objectIDAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/stringAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/transformableAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/undefinedAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/URIAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/UUIDAttributeType"
      ],
      "title": "Attribute types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDecimalAttributeType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDecimalAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Attribute-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/binaryDataAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/booleanAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/compositeAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/dateAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/doubleAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/floatAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer16AttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer32AttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/integer64AttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/objectIDAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/stringAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/transformableAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/undefinedAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/URIAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType/UUIDAttributeType"
              ],
              "title": "Attribute types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSDecimalAttributeType"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1booleanAttributeType/title",
          "value": "NSBooleanAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1booleanAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBooleanAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer16AttributeType/title",
          "value": "NSInteger16AttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer16AttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInteger16AttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/title",
          "value": "NSAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1doubleAttributeType/title",
          "value": "NSDoubleAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1doubleAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDoubleAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1decimalAttributeType/title",
          "value": "NSDecimalAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1decimalAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDecimalAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1compositeAttributeType/title",
          "value": "NSCompositeAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1compositeAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositeAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1stringAttributeType/title",
          "value": "NSStringAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1stringAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1floatAttributeType/title",
          "value": "NSFloatAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1floatAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFloatAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1UUIDAttributeType/title",
          "value": "NSUUIDAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1UUIDAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUUIDAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1objectIDAttributeType/title",
          "value": "NSObjectIDAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1objectIDAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSObjectIDAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1transformableAttributeType/title",
          "value": "NSTransformableAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1transformableAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTransformableAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1binaryDataAttributeType/title",
          "value": "NSBinaryDataAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1binaryDataAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBinaryDataAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1URIAttributeType/title",
          "value": "NSURIAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1URIAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSURIAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1undefinedAttributeType/title",
          "value": "NSUndefinedAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1undefinedAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUndefinedAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1dateAttributeType/title",
          "value": "NSDateAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1dateAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDateAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdecimalnumber/abstract",
          "value": [
            {
              "text": "An object for representing and performing arithmetic on base-10 numbers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer64AttributeType/title",
          "value": "NSInteger64AttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer64AttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInteger64AttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer32AttributeType/title",
          "value": "NSInteger32AttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType~1integer32AttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInteger32AttributeType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsattributetype/decimalattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsattributetype/decimalattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
