{"abstract":[{"text":"Called after the title bar accessory view controller’s view is removed from the window’s view hierarchy.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nstitlebaraccessoryviewcontroller/viewdiddisappear()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nstitlebaraccessoryviewcontroller/viewdiddisappear()"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"anchor":"Responding-to-View-Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidAppear()","doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewWillAppear()"],"generated":true,"title":"Responding to View Events"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"()"}]}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can override this method to perform tasks associated with removing the title bar accessory view controller’s view from the window’s view hierarchy—such as releasing resources not needed when the view is not visible or no longer part of the window—but you must call "},{"code":"super","type":"codeVoice"},{"type":"text","text":" in your implementation."}]}]}],"metadata":{"platforms":[{"name":"macOS","introducedAt":"10.10","deprecated":false,"beta":false,"unavailable":false}],"navigatorTitle":[{"text":"viewDidDisappear","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"AppKit"}],"title":"viewDidDisappear()","externalID":"c:objc(cs)NSTitlebarAccessoryViewController(im)viewDidDisappear","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidDisappear()"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidDisappear()":{"abstract":[{"text":"Called after the title bar accessory view controller’s view is removed from the window’s view hierarchy.","type":"text"}],"role":"symbol","title":"viewDidDisappear()","url":"/documentation/appkit/nstitlebaraccessoryviewcontroller/viewdiddisappear()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidDisappear()"},"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController":{"url":"/documentation/appkit/nstitlebaraccessoryviewcontroller","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController","navigatorTitle":[{"text":"NSTitlebarAccessoryViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTitlebarAccessoryViewController","kind":"identifier"}],"title":"NSTitlebarAccessoryViewController","abstract":[{"text":"An object that manages a custom view—known as an accessory view—in the title bar–toolbar area of a window.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidAppear()":{"abstract":[{"text":"Called when the title bar accessory view controller’s view is fully transitioned onto the screen.","type":"text"}],"role":"symbol","title":"viewDidAppear()","url":"/documentation/appkit/nstitlebaraccessoryviewcontroller/viewdidappear()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidAppear()"},"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewWillAppear()":{"navigatorTitle":[{"text":"viewWillAppear","kind":"identifier"}],"kind":"symbol","url":"/documentation/appkit/nstitlebaraccessoryviewcontroller/viewwillappear()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewWillAppear()","title":"viewWillAppear()","abstract":[{"text":"Called after the title bar accessory view controller’s view has been loaded into memory is about to be added to the view hierarchy in the window.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","introducedAt":"10.10","unavailable":false,"beta":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"viewDidDisappear","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewDidAppear()","doc://com.apple.appkit/documentation/AppKit/NSTitlebarAccessoryViewController/viewWillAppear()"],"title":"Responding to View Events","anchor":"Responding-to-View-Events","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"viewDidDisappear","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewDidDisappear()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewDidDisappear()/fragments"},{"op":"replace","value":"NSTitlebarAccessoryViewController","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/title"},{"op":"replace","value":[{"text":"NSTitlebarAccessoryViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/fragments"},{"op":"replace","value":[{"text":"NSTitlebarAccessoryViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController/navigatorTitle"},{"op":"replace","value":"viewDidAppear","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewDidAppear()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewDidAppear()/fragments"},{"op":"replace","value":"viewWillAppear","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewWillAppear()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTitlebarAccessoryViewController~1viewWillAppear()/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}