{
  "abstract": [
    {
      "text": "An error code that indicates that unspecified error occurred.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNError@NEVPNErrorConfigurationUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configurationUnknown"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNErrorConfigurationUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEVPNError.Code.configurationUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationUnknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct": {
      "abstract": [
        {
          "text": "Information about an error encountered while configuring or using a VPN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNError"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Codes that indicate the source of an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationDisabled": {
      "abstract": [
        {
          "text": "An error code indicating the VPN configuration associated with the VPN manager isn’t enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDisabled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConfigurationDisabled"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.configurationDisabled",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/configurationdisabled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code indicating the VPN configuration associated with the VPN manager object is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConfigurationInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationReadWriteFailed": {
      "abstract": [
        {
          "text": "An error code that indicates an error occurred while reading or writing the Network Extension preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationReadWriteFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationReadWriteFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConfigurationReadWriteFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.configurationReadWriteFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/configurationreadwritefailed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationStale": {
      "abstract": [
        {
          "text": "An error code that indicates another process modfied the VPN configuration since the last time the app loaded the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationStale"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationStale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConfigurationStale"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.configurationStale",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/configurationstale"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationUnknown": {
      "abstract": [
        {
          "text": "An error code that indicates that unspecified error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUnknown"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConfigurationUnknown"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.configurationUnknown",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/configurationunknown"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/connectionFailed": {
      "abstract": [
        {
          "text": "The connection to the VPN server failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionFailed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/connectionFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNErrorConnectionFailed"
        }
      ],
      "role": "symbol",
      "title": "NEVPNError.Code.connectionFailed",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnerror-swift.struct/code/connectionfailed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationDisabled",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/connectionFailed",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationStale",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationReadWriteFailed"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNErrorConfigurationUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationDisabled",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/connectionFailed",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationStale",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNError-swift.struct/Code/configurationReadWriteFailed"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEVPNErrorConfigurationUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationDisabled/title",
          "value": "NEVPNErrorConfigurationDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationReadWriteFailed/title",
          "value": "NEVPNErrorConfigurationReadWriteFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationReadWriteFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationReadWriteFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/title",
          "value": "NEVPNError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1connectionFailed/title",
          "value": "NEVPNErrorConnectionFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1connectionFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConnectionFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationStale/title",
          "value": "NEVPNErrorConfigurationStale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationStale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationStale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationInvalid/title",
          "value": "NEVPNErrorConfigurationInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationUnknown/title",
          "value": "NEVPNErrorConfigurationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNError-swift.struct~1Code~1configurationUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNErrorConfigurationUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnerror-swift.struct/code/configurationunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnerror-swift.struct/code/configurationunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
