{
  "abstract": [
    {
      "text": "A location that indicates the GPU is permanently connected to the system internally.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/builtIn"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLDeviceLocation@MTLDeviceLocationBuiltIn",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "builtIn"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLDeviceLocationBuiltIn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLDeviceLocation.builtIn"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "builtIn"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation": {
      "abstract": [
        {
          "text": "Indicates the location of the GPU relative to the system it’s connect to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocation"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/builtIn": {
      "abstract": [
        {
          "text": "A location that indicates the GPU is permanently connected to the system internally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "builtIn"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/builtIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocationBuiltIn"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation.builtIn",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation/builtin"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/external": {
      "abstract": [
        {
          "text": "A GPU location that indicates a person connected the GPU to the system with an external interface, such as Thunderbolt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "external"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/external",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocationExternal"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation.external",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation/external"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/slot": {
      "abstract": [
        {
          "text": "A GPU location that indicates a person connected the GPU to a system’s internal slot.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slot"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/slot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocationSlot"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation.slot",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation/slot"
    },
    "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/unspecified": {
      "abstract": [
        {
          "text": "A value that indicates the system can’t determine how the GPU connects to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLDeviceLocationUnspecified"
        }
      ],
      "role": "symbol",
      "title": "MTLDeviceLocation.unspecified",
      "type": "topic",
      "url": "/documentation/metal/mtldevicelocation/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-GPUs-Location",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/slot",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/external",
        "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/unspecified"
      ],
      "title": "Determining the GPU’s Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLDeviceLocationBuiltIn"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocationBuiltIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-the-GPUs-Location",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/slot",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/external",
                "doc://com.apple.metal/documentation/Metal/MTLDeviceLocation/unspecified"
              ],
              "title": "Determining the GPU’s Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLDeviceLocationBuiltIn"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1slot/title",
          "value": "MTLDeviceLocationSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1slot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocationSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1unspecified/title",
          "value": "MTLDeviceLocationUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocationUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1builtIn/title",
          "value": "MTLDeviceLocationBuiltIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1builtIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocationBuiltIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1external/title",
          "value": "MTLDeviceLocationExternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation~1external/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocationExternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/title",
          "value": "MTLDeviceLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLDeviceLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLDeviceLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtldevicelocation/builtin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtldevicelocation/builtin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
