{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.replaykit/documentation/ReplayKit",
        "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)RPScreenRecorder(im)init",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "init"
      }
    ],
    "modules": [
      {
        "name": "ReplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "init"
      }
    ],
    "platforms": [],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "init"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "init"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "init"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit": {
      "abstract": [
        {
          "text": "Record or stream video from the screen, and audio from the app and microphone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ReplayKit",
      "type": "topic",
      "url": "/documentation/replaykit"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder": {
      "abstract": [
        {
          "text": "The shared recorder object that provides the ability to record audio and video of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RPScreenRecorder"
        }
      ],
      "role": "symbol",
      "title": "RPScreenRecorder",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder"
    },
    "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.replaykit/documentation/ReplayKit/RPScreenRecorder/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/replaykit/rpscreenrecorder/init"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/title",
          "value": "RPScreenRecorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.replaykit~1documentation~1ReplayKit~1RPScreenRecorder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RPScreenRecorder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/replaykit/rpscreenrecorder/init"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
