{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentActions"}]}],"kind":"declarations"}],"abstract":[{"text":"The user wants to be presented with a list of actions that can be taken on the text item, such as opening the link in a different way or downloading content from the link.","type":"text"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"UITextItemInteractionPresentActions"}],"title":"UITextItemInteraction.presentActions","platforms":[{"deprecatedAt":"17.0","name":"iOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","beta":false,"deprecated":false,"unavailable":false},{"deprecatedAt":"17.0","name":"iPadOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","beta":false,"deprecated":false,"unavailable":false},{"deprecatedAt":"17.0","name":"Mac Catalyst","introducedAt":"13.1","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","beta":false,"deprecated":false,"unavailable":false},{"deprecatedAt":"17.0","name":"tvOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","beta":false,"deprecated":false,"unavailable":false},{"deprecatedAt":"1.0","name":"visionOS","introducedAt":"1.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","beta":false,"deprecated":false,"unavailable":false}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentActions"}],"externalID":"c:@E@UITextItemInteraction@UITextItemInteractionPresentActions","role":"symbol","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextiteminteraction/presentactions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextiteminteraction/presentactions"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction"]]},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview"],"anchor":"Constants","generated":true,"title":"Constants"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview":{"role":"symbol","title":"UITextItemInteraction.preview","navigatorTitle":[{"text":"UITextItemInteractionPreview","kind":"identifier"}],"type":"topic","deprecated":true,"url":"/documentation/uikit/uitextiteminteraction/preview","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview","abstract":[{"type":"text","text":"The user wants to get a preview of the content represented by the text item, such as by initiating a peek and pop on a link."}]},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction","navigatorTitle":[{"text":"UITextItemInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that indicate the type of interaction the user expects to have with a URL or text attachment."}],"kind":"symbol","title":"UITextItemInteraction","role":"symbol","url":"/documentation/uikit/uitextiteminteraction","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextItemInteraction","kind":"identifier"}],"deprecated":true},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions":{"url":"/documentation/uikit/uitextiteminteraction/presentactions","role":"symbol","navigatorTitle":[{"text":"UITextItemInteractionPresentActions","kind":"identifier"}],"title":"UITextItemInteraction.presentActions","deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentActions","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The user wants to be presented with a list of actions that can be taken on the text item, such as opening the link in a different way or downloading content from the link.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions"},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction":{"role":"symbol","title":"UITextItemInteraction.invokeDefaultAction","navigatorTitle":[{"text":"UITextItemInteractionInvokeDefaultAction","kind":"identifier"}],"type":"topic","deprecated":true,"url":"/documentation/uikit/uitextiteminteraction/invokedefaultaction","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invokeDefaultAction","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","abstract":[{"type":"text","text":"The user wants to perform the default action on the text item; for example, opening a URL."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","deprecated":false,"deprecatedAt":"17.0"},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"10.0","deprecated":false,"deprecatedAt":"17.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"deprecatedAt":"17.0"},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"10.0","deprecated":false,"deprecatedAt":"17.0"},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"deprecatedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"UITextItemInteractionPresentActions","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UITextItemInteractionPresentActions"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview"],"title":"Constants","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"UITextItemInteractionPresentActions","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":[],"op":"add","path":"/deprecationSummary"},{"op":"replace","value":"UITextItemInteractionPreview","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1preview/title"},{"op":"replace","value":[{"kind":"identifier","text":"UITextItemInteractionPreview"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1preview/fragments"},{"op":"replace","value":"UITextItemInteraction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/title"},{"op":"replace","value":[{"kind":"identifier","text":"UITextItemInteraction"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UITextItemInteraction"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/navigatorTitle"},{"op":"replace","value":"UITextItemInteractionPresentActions","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1presentActions/title"},{"op":"replace","value":[{"kind":"identifier","text":"UITextItemInteractionPresentActions"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1presentActions/fragments"},{"op":"replace","value":"UITextItemInteractionInvokeDefaultAction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1invokeDefaultAction/title"},{"op":"replace","value":[{"text":"UITextItemInteractionInvokeDefaultAction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1invokeDefaultAction/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}