{
  "abstract": [
    {
      "text": "An error code that indicates the extension encountered an error while parsing the media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/parsingFailure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MEError@MEErrorParsingFailure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parsingFailure"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEErrorParsingFailure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MEError.Code.parsingFailure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parsingFailure"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct": {
      "abstract": [
        {
          "text": "A MediaExtension framework error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEError"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEError"
        }
      ],
      "role": "symbol",
      "title": "MEError",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code": {
      "abstract": [
        {
          "text": "An enumeration that models media extension error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/allocationFailure": {
      "abstract": [
        {
          "text": "An error code that indicates the extension can’t allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocationFailure"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/allocationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorAllocationFailure"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.allocationFailure",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/allocationfailure"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/endOfStream": {
      "abstract": [
        {
          "text": "An error code that indicates the extension reached the end of the source file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endOfStream"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/endOfStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorEndOfStream"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.endOfStream",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/endofstream"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/internalFailure": {
      "abstract": [
        {
          "text": "An error code that indicates the extension encountered an internal operation failure, such as code loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFailure"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/internalFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorInternalFailure"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.internalFailure",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/internalfailure"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/invalidParameter": {
      "abstract": [
        {
          "text": "An error code that indicates the extension received an invalid parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/invalidparameter"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/locationNotAvailable": {
      "abstract": [
        {
          "text": "An error code that indicates specific sample isn’t contiguous, spans more than one file, or is for some other reason unsuitable for reading directly from a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/locationNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorLocationNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.locationNotAvailable",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/locationnotavailable"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSamples": {
      "abstract": [
        {
          "text": "An error code that indicates there are no samples in the track or a request to load a sample buffer fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSamples"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorNoSamples"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.noSamples",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/nosamples"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSuchEdit": {
      "abstract": [
        {
          "text": "An error code that indicates the plug-in track reader received a request to return an edit that’s out of range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchEdit"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSuchEdit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorNoSuchEdit"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.noSuchEdit",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/nosuchedit"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/parsingFailure": {
      "abstract": [
        {
          "text": "An error code that indicates the extension encountered an error while parsing the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parsingFailure"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/parsingFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorParsingFailure"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.parsingFailure",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/parsingfailure"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/permissionDenied": {
      "abstract": [
        {
          "text": "An error code that indicates the extension received a request to perform an invalid operation on a byte source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/permissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.permissionDenied",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/permissiondenied"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/propertyNotSupported": {
      "abstract": [
        {
          "text": "An error code that indicates the extension encountered a property it doesn’t support reading and writing to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyNotSupported"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/propertyNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorPropertyNotSupported"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.propertyNotSupported",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/propertynotsupported"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/referenceMissing": {
      "abstract": [
        {
          "text": "An error code that indicates the decoder received a request to decode a sample without decoding the required reference frame dependencies first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceMissing"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/referenceMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorReferenceMissing"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.referenceMissing",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/referencemissing"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/unsupportedFeature": {
      "abstract": [
        {
          "text": "An error code that indicates the extension doesn’t support an aspect of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedFeature"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/unsupportedFeature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEErrorUnsupportedFeature"
        }
      ],
      "role": "symbol",
      "title": "MEError.Code.unsupportedFeature",
      "type": "topic",
      "url": "/documentation/mediaextension/meerror-swift.struct/code/unsupportedfeature"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/allocationFailure",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/endOfStream",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/internalFailure",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/invalidParameter",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/locationNotAvailable",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSamples",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSuchEdit",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/permissionDenied",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/propertyNotSupported",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/referenceMissing",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/unsupportedFeature"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEErrorParsingFailure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorParsingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/allocationFailure",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/endOfStream",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/internalFailure",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/invalidParameter",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/locationNotAvailable",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSamples",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/noSuchEdit",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/permissionDenied",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/propertyNotSupported",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/referenceMissing",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEError-swift.struct/Code/unsupportedFeature"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MEErrorParsingFailure"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code/title",
          "value": "MEError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1invalidParameter/title",
          "value": "MEErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1internalFailure/title",
          "value": "MEErrorInternalFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1internalFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorInternalFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1parsingFailure/title",
          "value": "MEErrorParsingFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1parsingFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorParsingFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1permissionDenied/title",
          "value": "MEErrorPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1permissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1noSuchEdit/title",
          "value": "MEErrorNoSuchEdit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1noSuchEdit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorNoSuchEdit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1noSamples/title",
          "value": "MEErrorNoSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1noSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorNoSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1unsupportedFeature/title",
          "value": "MEErrorUnsupportedFeature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1unsupportedFeature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorUnsupportedFeature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1endOfStream/title",
          "value": "MEErrorEndOfStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1endOfStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorEndOfStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1referenceMissing/title",
          "value": "MEErrorReferenceMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1referenceMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorReferenceMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1allocationFailure/title",
          "value": "MEErrorAllocationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1allocationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorAllocationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1locationNotAvailable/title",
          "value": "MEErrorLocationNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1locationNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorLocationNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1propertyNotSupported/title",
          "value": "MEErrorPropertyNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEError-swift.struct~1Code~1propertyNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEErrorPropertyNotSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/meerror-swift.struct/code/parsingfailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/meerror-swift.struct/code/parsingfailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
