{
  "abstract": [
    {
      "text": "Calls the completion handler with the active tab in the target window.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.safariservices/documentation/SafariServices",
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/getActiveTab(completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFSafariWindow(im)getActiveTabWithCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "getActiveTab"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SFSafariTab",
        "text": "SFSafariTab"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Safari Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getActiveTabWithCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "getActiveTab(completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "getActiveTab"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFSafariTab",
              "text": "SFSafariTab"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "activeTab"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SFSafariTab",
              "text": "SFSafariTab"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block called after the active tab is retrieved.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func activeTab() async -> SFSafariTab?"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.safariservices/documentation/SafariServices": {
      "abstract": [
        {
          "text": "Enable web views and services in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Safari Services",
      "type": "topic",
      "url": "/documentation/safariservices"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab": {
      "abstract": [
        {
          "text": "A proxy for a tab in a Safari window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariTab"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariTab"
        }
      ],
      "role": "symbol",
      "title": "SFSafariTab",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafaritab"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow": {
      "abstract": [
        {
          "text": "A proxy for a Safari window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFSafariWindow"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFSafariWindow"
        }
      ],
      "role": "symbol",
      "title": "SFSafariWindow",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariwindow"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/getActiveTab(completionHandler:)": {
      "abstract": [
        {
          "text": "Calls the completion handler with the active tab in the target window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getActiveTab"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariTab",
          "text": "SFSafariTab"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/getActiveTab(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getActiveTabWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getActiveTab(completionHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariwindow/getactivetab(completionhandler:)"
    },
    "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/openTab(with:makeActiveIfPossible:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens a tab at the end of the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openTab"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "makeActiveIfPossible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SFSafariTab",
          "text": "SFSafariTab"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/openTab(with:makeActiveIfPossible:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openTabWithURL:makeActiveIfPossible:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openTab(with:makeActiveIfPossible:completionHandler:)",
      "type": "topic",
      "url": "/documentation/safariservices/sfsafariwindow/opentab(with:makeactiveifpossible:completionhandler:)"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Tabs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/openTab(with:makeActiveIfPossible:completionHandler:)"
      ],
      "title": "Working with Tabs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getActiveTabWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getActiveTabWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.safariservices/documentation/SafariServices",
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Tabs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.safariservices/documentation/SafariServices/SFSafariWindow/openTab(with:makeActiveIfPossible:completionHandler:)"
              ],
              "title": "Working with Tabs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "getActiveTabWithCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.safariservices/documentation/SafariServices/SFSafariTab",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SFSafariTab",
                    "text": "SFSafariTab"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "activeTab"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block called after the active tab is retrieved.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/title",
          "value": "SFSafariWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow~1getActiveTab(completionHandler:)/title",
          "value": "getActiveTabWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow~1getActiveTab(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getActiveTabWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow~1openTab(with:makeActiveIfPossible:completionHandler:)/title",
          "value": "openTabWithURL:makeActiveIfPossible:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariWindow~1openTab(with:makeActiveIfPossible:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openTabWithURL:makeActiveIfPossible:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/title",
          "value": "SFSafariTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.safariservices~1documentation~1SafariServices~1SFSafariTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFSafariTab"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/safariservices/sfsafariwindow/getactivetab(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/safariservices/sfsafariwindow/getactivetab(completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
