{
  "abstract": [
    {
      "text": "The device is in landscape mode, with the device upright and the Home button on the left.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIInterfaceOrientation@UIInterfaceOrientationLandscapeLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "landscapeLeft"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIInterfaceOrientationLandscapeLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIInterfaceOrientation.landscapeLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "landscapeLeft"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation": {
      "abstract": [
        {
          "text": "Constants that specify the orientation of the app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeLeft": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device upright and the Home button on the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationLandscapeLeft"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation.landscapeLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation/landscapeleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeRight": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device upright and the Home button on the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationLandscapeRight"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation.landscapeRight",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation/landscaperight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portrait": {
      "abstract": [
        {
          "text": "The device is in portrait mode, with the device upright and the Home button on the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationPortrait"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation.portrait",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation/portrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portraitUpsideDown": {
      "abstract": [
        {
          "text": "The device is in portrait mode but is upside down, with the device upright and the Home button at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitUpsideDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portraitUpsideDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationPortraitUpsideDown"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation.portraitUpsideDown",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation/portraitupsidedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/unknown": {
      "abstract": [
        {
          "text": "The orientation of the device is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationUnknown"
        }
      ],
      "role": "symbol",
      "title": "UIInterfaceOrientation.unknown",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientation/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Orientations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/unknown",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portrait",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portraitUpsideDown",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeRight"
      ],
      "title": "Orientations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIInterfaceOrientationLandscapeLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationLandscapeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Orientations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/unknown",
                "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portrait",
                "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/portraitUpsideDown",
                "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientation/landscapeRight"
              ],
              "title": "Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIInterfaceOrientationLandscapeLeft"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1landscapeRight/title",
          "value": "UIInterfaceOrientationLandscapeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1landscapeRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationLandscapeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/title",
          "value": "UIInterfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1portrait/title",
          "value": "UIInterfaceOrientationPortrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationPortrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1landscapeLeft/title",
          "value": "UIInterfaceOrientationLandscapeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1landscapeLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationLandscapeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1unknown/title",
          "value": "UIInterfaceOrientationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1portraitUpsideDown/title",
          "value": "UIInterfaceOrientationPortraitUpsideDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterfaceOrientation~1portraitUpsideDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterfaceOrientationPortraitUpsideDown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiinterfaceorientation/landscapeleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiinterfaceorientation/landscapeleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
