{
  "abstract": [
    {
      "text": "Constants that specify the contents of vImage buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/conversion",
        "doc://com.apple.accelerate/documentation/Accelerate/functions-that-perform-any-to-any-conversion"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/conversion",
        "doc://com.apple.accelerate/documentation/Accelerate/functions-that-perform-any-to-any-conversion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1399056-vimage-buffer-type-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "vImage Buffer Type Codes"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/conversion": {
      "abstract": [
        {
          "text": "Convert an image to a different format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion",
      "type": "topic",
      "url": "/documentation/accelerate/conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/functions-that-perform-any-to-any-conversion": {
      "abstract": [
        {
          "text": "Convert between Core Video or Core Graphics image data of arbitrary color spaces and bit depths.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/functions-that-perform-any-to-any-conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Functions that perform any-to-any conversion",
      "type": "topic",
      "url": "/documentation/accelerate/functions-that-perform-any-to-any-conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha": {
      "abstract": [
        {
          "text": "The buffer contains the alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Alpha"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Alpha",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_alpha"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat": {
      "abstract": [
        {
          "text": "The buffer contains data describable as a vImage Core Graphics image format as a single buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CGFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CGFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CGFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cgformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the black channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Black"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Black",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_black"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the cyan channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Cyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Cyan"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Cyan",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_cyan"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the magenta channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Magenta"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Magenta",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_magenta"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the yellow channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Yellow"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Yellow",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_yellow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr": {
      "abstract": [
        {
          "text": "The buffer contains luminance and both chroma channels interleaved according to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " image type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cvpixelbuffer_ycbcr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb": {
      "abstract": [
        {
          "text": "The buffer contains the blue chrominance channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cb"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma": {
      "abstract": [
        {
          "text": "The buffer contains both chrominance channels, interleaved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chroma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chroma"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Chroma",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_chroma"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky": {
      "abstract": [
        {
          "text": "The buffer contains chunky data not describable as a vImage Core Graphics image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chunky"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chunky"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Chunky",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_chunky"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel1",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel10",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel11",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel11"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel12",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel12"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel13",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel13"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel14"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel14"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel14",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel14"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel15"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel15",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel15"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel15",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel15"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel16"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel16",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel2"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel2",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel3"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel3",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel4"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel4",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel5"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel5",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel6"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel6",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel7"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel7",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel8"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel9"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel9",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel9"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cr": {
      "abstract": [
        {
          "text": "The buffer contains the red chrominance channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cr"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_EndOfList": {
      "abstract": [
        {
          "text": "End of list marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_EndOfList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_EndOfList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_EndOfList"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_EndOfList",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_endoflist"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Indexed": {
      "abstract": [
        {
          "text": "The buffer contains data in an indexed colorspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Indexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Indexed"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Indexed",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_indexed"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_A": {
      "abstract": [
        {
          "text": "If the image has a LAB color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "a*",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_A"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_LAB_A",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_lab_a"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_B": {
      "abstract": [
        {
          "text": "If the image has a LAB color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "b*",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_B"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_LAB_B",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_lab_b"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_L": {
      "abstract": [
        {
          "text": "If the image has a LAB color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "L*",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_L"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_L",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_LAB_L"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_LAB_L",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_lab_l"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Luminance": {
      "abstract": [
        {
          "text": "The buffer contains only luminance data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Luminance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Luminance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Luminance"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Luminance",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_luminance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Monochrome": {
      "abstract": [
        {
          "text": "The buffer contains a single color channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Monochrome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Monochrome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Monochrome"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Monochrome",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_monochrome"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Blue": {
      "abstract": [
        {
          "text": "If the image has a RGB color model, the buffer contains the blue channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Blue"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_RGB_Blue",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_rgb_blue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Green": {
      "abstract": [
        {
          "text": "If the image has a RGB color model, the buffer contains the green channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Green"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_RGB_Green",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_rgb_green"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Red": {
      "abstract": [
        {
          "text": "If the image has a RGB color model, the buffer contains the red channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_RGB_Red"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_RGB_Red",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_rgb_red"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_UniqueFormatCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_UniqueFormatCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_UniqueFormatCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_UniqueFormatCount"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_UniqueFormatCount",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_uniqueformatcount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_X": {
      "abstract": [
        {
          "text": "If the image has a XYZ color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "X",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_X"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_X"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_XYZ_X",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_xyz_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Y": {
      "abstract": [
        {
          "text": "If the image has a XYZ color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Y"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_XYZ_Y",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_xyz_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z": {
      "abstract": [
        {
          "text": "If the image has a XYZ color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Z",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Z"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_XYZ_Z",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_xyz_z"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageBufferTypeCode": {
      "abstract": [
        {
          "text": "Type codes, such as chrominance or luminance, for the contents of a vImage buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageBufferTypeCode"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageBufferTypeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageBufferTypeCode"
        }
      ],
      "role": "symbol",
      "title": "vImageBufferTypeCode",
      "type": "topic",
      "url": "/documentation/accelerate/vimagebuffertypecode"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat": {
      "abstract": [
        {
          "text": "An immutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageConstCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconstcvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_AnyToAny(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Converts the pixels in a vImage buffer to another format, using the specified converter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConvert_AnyToAny"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConverterRef",
          "text": "vImageConverter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_AnyToAny(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConvert_AnyToAny"
        }
      ],
      "role": "symbol",
      "title": "vImageConvert_AnyToAny(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconvert_anytoany(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPUs vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-a-conversion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_AnyToAny(_:_:_:_:_:)"
      ],
      "title": "Performing a conversion"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageBufferTypeCode"
      ],
      "title": "Type"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel14",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel15",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel16",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel2",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel3",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel4",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel5",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel6",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel7",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel9",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cr",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_EndOfList",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Indexed",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_A",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_B",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_LAB_L",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Luminance",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Monochrome",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Blue",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Green",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_RGB_Red",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_UniqueFormatCount",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_X",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Y",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel1/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel7/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Alpha/title",
          "value": "kvImageBufferTypeCode_Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/title",
          "value": "vImageConstCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cr/title",
          "value": "kvImageBufferTypeCode_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel14/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel6/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Blue/title",
          "value": "kvImageBufferTypeCode_RGB_Blue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_RGB_Blue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Black/title",
          "value": "kvImageBufferTypeCode_CMYK_Black"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Black"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Indexed/title",
          "value": "kvImageBufferTypeCode_Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel15/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel15"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel15/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel15"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel12/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_AnyToAny(_:_:_:_:_:)/title",
          "value": "vImageConvert_AnyToAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_AnyToAny(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConvert_AnyToAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel3/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Green/title",
          "value": "kvImageBufferTypeCode_RGB_Green"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_RGB_Green"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel11/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel5/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_A/title",
          "value": "kvImageBufferTypeCode_LAB_A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_LAB_A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel16/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Yellow/title",
          "value": "kvImageBufferTypeCode_CMYK_Yellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Yellow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel13/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_X/title",
          "value": "kvImageBufferTypeCode_XYZ_X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel9/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Cyan/title",
          "value": "kvImageBufferTypeCode_CMYK_Cyan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Cyan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Cyan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Y/title",
          "value": "kvImageBufferTypeCode_XYZ_Y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_Y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Luminance/title",
          "value": "kvImageBufferTypeCode_Luminance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Luminance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Luminance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cb/title",
          "value": "kvImageBufferTypeCode_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel10/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chroma/title",
          "value": "kvImageBufferTypeCode_Chroma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chroma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Chroma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CGFormat/title",
          "value": "kvImageBufferTypeCode_CGFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CGFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CGFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Monochrome/title",
          "value": "kvImageBufferTypeCode_Monochrome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Monochrome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Monochrome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_L/title",
          "value": "kvImageBufferTypeCode_LAB_L"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_L/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_LAB_L"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chunky/title",
          "value": "kvImageBufferTypeCode_Chunky"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chunky/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Chunky"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_EndOfList/title",
          "value": "kvImageBufferTypeCode_EndOfList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_EndOfList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_EndOfList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_UniqueFormatCount/title",
          "value": "kvImageBufferTypeCode_UniqueFormatCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_UniqueFormatCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_UniqueFormatCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel4/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageBufferTypeCode/title",
          "value": "vImageBufferTypeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageBufferTypeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageBufferTypeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageBufferTypeCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageBufferTypeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Red/title",
          "value": "kvImageBufferTypeCode_RGB_Red"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_RGB_Red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_RGB_Red"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Magenta/title",
          "value": "kvImageBufferTypeCode_CMYK_Magenta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Magenta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Magenta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel8/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Z/title",
          "value": "kvImageBufferTypeCode_XYZ_Z"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_Z"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_B/title",
          "value": "kvImageBufferTypeCode_LAB_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_LAB_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_LAB_B"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CVPixelBuffer_YCbCr/title",
          "value": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CVPixelBuffer_YCbCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel2/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
