{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Video Image Format Errors"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods": {
      "abstract": [
        {
          "text": "Specify the dithering method some vImage conversion functions use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dithering Methods",
      "type": "topic",
      "url": "/documentation/accelerate/1533233-dithering-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes": {
      "abstract": [
        {
          "text": "Error codes that vImage functions return when an operation fails.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error codes",
      "type": "topic",
      "url": "/documentation/accelerate/1578972-error-codes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags": {
      "abstract": [
        {
          "text": "Set flags on vImage operations to specify processing options.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Processing Flags",
      "type": "topic",
      "url": "/documentation/accelerate/1578976-processing-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/availability-flags": {
      "abstract": [
        {
          "text": "Obtain the availability of particular vImage features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Availability Flags",
      "type": "topic",
      "url": "/documentation/accelerate/availability-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/buffer-types": {
      "abstract": [
        {
          "text": "Look up buffer type codes vImage conversions provide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Types",
      "type": "topic",
      "url": "/documentation/accelerate/buffer-types"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants": {
      "abstract": [
        {
          "text": "Look up type aliases, data types, and constants the vImage library uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types and Constants",
      "type": "topic",
      "url": "/documentation/accelerate/data-types-and-constants"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays": {
      "abstract": [
        {
          "text": "Specify the decode array constant to use with 16Q12-formatted data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decode Arrays",
      "type": "topic",
      "url": "/documentation/accelerate/decode-arrays"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint": {
      "abstract": [
        {
          "text": "A hint that indicates the alpha channel is opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_AlphaIsOneHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_AlphaIsOneHint"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_AlphaIsOneHint",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_alphaisonehint"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting": {
      "abstract": [
        {
          "text": "An error code that indicates the chroma siting information is absent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ChromaSiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ChromaSiting"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ChromaSiting",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_chromasiting"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace": {
      "abstract": [
        {
          "text": "An error code that indicates the image’s color space is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ColorSpace",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_colorspace"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix": {
      "abstract": [
        {
          "text": "An error code that indicates the required conversion matrix is absent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ConversionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ConversionMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_conversionmatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError": {
      "abstract": [
        {
          "text": "An error code that indicates the conversion completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_NoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_NoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_NoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_noerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription": {
      "abstract": [
        {
          "text": "An error code that indicates the range and clipping information is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_VideoChannelDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_VideoChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_VideoChannelDescription",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_videochanneldescription"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormatError": {
      "abstract": [
        {
          "text": "Additional error codes for functions that use the vImageCVImageFormatRef",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormatError"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormatError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormatError"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormatError",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformaterror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType": {
      "abstract": [
        {
          "text": "An enumeration of RGB -> Y’CbCr conversion matrix types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "role": "symbol",
      "title": "vImageMatrixType",
      "type": "topic",
      "url": "/documentation/accelerate/vimagematrixtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation": {
      "abstract": [
        {
          "text": "Constants for selecting the interpolation mode",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "role": "symbol",
      "title": "vImage_WarpInterpolation",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_warpinterpolation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
        "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
        "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormatError"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/title",
          "value": "vImageMatrixType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ConversionMatrix/title",
          "value": "kvImageCVImageFormat_ConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ConversionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormatError/title",
          "value": "vImageCVImageFormatError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormatError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormatError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/title",
          "value": "vImage_WarpInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_NoError/title",
          "value": "kvImageCVImageFormat_NoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_NoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_NoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_VideoChannelDescription/title",
          "value": "kvImageCVImageFormat_VideoChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_VideoChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_VideoChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ColorSpace/title",
          "value": "kvImageCVImageFormat_ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_AlphaIsOneHint/title",
          "value": "kvImageCVImageFormat_AlphaIsOneHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_AlphaIsOneHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_AlphaIsOneHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ChromaSiting/title",
          "value": "kvImageCVImageFormat_ChromaSiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ChromaSiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ChromaSiting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
