{
  "abstract": [
    {
      "text": "The number of degrees to rotate an image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/image-rotation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1509228-rotation-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Rotation constants"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-rotation": {
      "abstract": [
        {
          "text": "Rotate images by arbitrary angles or by multiples of 90 degrees.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-rotation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image rotation",
      "type": "topic",
      "url": "/documentation/accelerate/image-rotation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 0° (that is, copy without rotating).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate0DegreesClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate0DegreesClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate0DegreesClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate0degreesclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesCounterClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 0° (that is, copy without rotating).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate0DegreesCounterClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesCounterClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate0DegreesCounterClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate0DegreesCounterClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate0degreescounterclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 180° clockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate180DegreesClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate180DegreesClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate180DegreesClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate180degreesclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesCounterClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 180° counterclockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate180DegreesCounterClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesCounterClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate180DegreesCounterClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate180DegreesCounterClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate180degreescounterclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 270° clockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate270DegreesClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate270DegreesClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate270DegreesClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate270degreesclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesCounterClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 270° counterclockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate270DegreesCounterClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesCounterClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate270DegreesCounterClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate270DegreesCounterClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate270degreescounterclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 90° clockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate90DegreesClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate90DegreesClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate90DegreesClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate90degreesclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesCounterClockwise": {
      "abstract": [
        {
          "text": "A constant that specifies rotation by 90° counterclockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kRotate90DegreesCounterClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesCounterClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kRotate90DegreesCounterClockwise"
        }
      ],
      "role": "symbol",
      "title": "kRotate90DegreesCounterClockwise",
      "type": "topic",
      "url": "/documentation/accelerate/krotate90degreescounterclockwise"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate0DegreesCounterClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate90DegreesCounterClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate180DegreesCounterClockwise",
        "doc://com.apple.accelerate/documentation/Accelerate/kRotate270DegreesCounterClockwise"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate180DegreesClockwise/title",
          "value": "kRotate180DegreesClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate180DegreesClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate180DegreesClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate90DegreesCounterClockwise/title",
          "value": "kRotate90DegreesCounterClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate90DegreesCounterClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate90DegreesCounterClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate0DegreesClockwise/title",
          "value": "kRotate0DegreesClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate0DegreesClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate0DegreesClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate90DegreesClockwise/title",
          "value": "kRotate90DegreesClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate90DegreesClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate90DegreesClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate270DegreesCounterClockwise/title",
          "value": "kRotate270DegreesCounterClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate270DegreesCounterClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate270DegreesCounterClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate180DegreesCounterClockwise/title",
          "value": "kRotate180DegreesCounterClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate180DegreesCounterClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate180DegreesCounterClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate0DegreesCounterClockwise/title",
          "value": "kRotate0DegreesCounterClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate0DegreesCounterClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate0DegreesCounterClockwise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate270DegreesClockwise/title",
          "value": "kRotate270DegreesClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kRotate270DegreesClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kRotate270DegreesClockwise"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
