{
  "abstract": [
    {
      "text": "Filtering algorithms to apply to image data before compressing the data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1515413-png-filter-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PNG Filter Types"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering": {
      "abstract": [
        {
          "text": "Filter data prior to decompression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decompression Filtering",
      "type": "topic",
      "url": "/documentation/accelerate/decompression-filtering"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG": {
      "abstract": [
        {
          "text": "A filter that predicts a pixel value from the average of the pixels to the left and above the predicted pixel location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_AVG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_AVG"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_AVG",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_avg"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE": {
      "abstract": [
        {
          "text": "No filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_NONE"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_NONE",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_none"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH": {
      "abstract": [
        {
          "text": "A filter that predicts a pixel value by applying a linear function to the pixels located to the left, above, and to the upper-left of the predicted pixel location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_PAETH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_PAETH"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_PAETH",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_paeth"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB": {
      "abstract": [
        {
          "text": "A filter that computes the difference between each byte of a pixel and the value of the corresponding byte of the pixel located to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_SUB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_SUB"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_SUB",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_sub"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP": {
      "abstract": [
        {
          "text": "A filter that computes the difference between each byte of a pixel and the value of the corresponding byte of the pixel located above.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_UP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_UP"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_UP",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_up"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_PAETH/title",
          "value": "kvImage_PNG_FILTER_VALUE_PAETH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_PAETH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_PAETH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_AVG/title",
          "value": "kvImage_PNG_FILTER_VALUE_AVG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_AVG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_AVG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_SUB/title",
          "value": "kvImage_PNG_FILTER_VALUE_SUB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_SUB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_SUB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_NONE/title",
          "value": "kvImage_PNG_FILTER_VALUE_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_UP/title",
          "value": "kvImage_PNG_FILTER_VALUE_UP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_UP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_UP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
