{
  "abstract": [
    {
      "text": "Error codes that vImage functions return when an operation fails.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error codes"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Image Format Errors",
      "type": "topic",
      "url": "/documentation/accelerate/1498271-core-video-image-format-errors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods": {
      "abstract": [
        {
          "text": "Specify the dithering method some vImage conversion functions use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dithering Methods",
      "type": "topic",
      "url": "/documentation/accelerate/1533233-dithering-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags": {
      "abstract": [
        {
          "text": "Set flags on vImage operations to specify processing options.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Processing Flags",
      "type": "topic",
      "url": "/documentation/accelerate/1578976-processing-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/availability-flags": {
      "abstract": [
        {
          "text": "Obtain the availability of particular vImage features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Availability Flags",
      "type": "topic",
      "url": "/documentation/accelerate/availability-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/buffer-types": {
      "abstract": [
        {
          "text": "Look up buffer type codes vImage conversions provide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Types",
      "type": "topic",
      "url": "/documentation/accelerate/buffer-types"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants": {
      "abstract": [
        {
          "text": "Look up type aliases, data types, and constants the vImage library uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types and Constants",
      "type": "topic",
      "url": "/documentation/accelerate/data-types-and-constants"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays": {
      "abstract": [
        {
          "text": "Specify the decode array constant to use with 16Q12-formatted data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decode Arrays",
      "type": "topic",
      "url": "/documentation/accelerate/decode-arrays"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch": {
      "abstract": [
        {
          "text": "The function requires the source and destination buffers to have the same height and the same width, but they do not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferSizeMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferSizeMismatch"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferSizeMismatch",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffersizemismatch"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint": {
      "abstract": [
        {
          "text": "A hint that indicates the alpha channel is opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_AlphaIsOneHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_AlphaIsOneHint"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_AlphaIsOneHint",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_alphaisonehint"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting": {
      "abstract": [
        {
          "text": "An error code that indicates the chroma siting information is absent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ChromaSiting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ChromaSiting"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ChromaSiting",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_chromasiting"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace": {
      "abstract": [
        {
          "text": "An error code that indicates the image’s color space is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ColorSpace"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ColorSpace",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_colorspace"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix": {
      "abstract": [
        {
          "text": "An error code that indicates the required conversion matrix is absent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ConversionMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_ConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_ConversionMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_conversionmatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError": {
      "abstract": [
        {
          "text": "An error code that indicates the conversion completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_NoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_NoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_NoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_noerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription": {
      "abstract": [
        {
          "text": "An error code that indicates the range and clipping information is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_VideoChannelDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCVImageFormat_VideoChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "kvImageCVImageFormat_VideoChannelDescription",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecvimageformat_videochanneldescription"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageColorSyncIsAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageColorSyncIsAbsent"
        }
      ],
      "role": "symbol",
      "title": "kvImageColorSyncIsAbsent",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecolorsyncisabsent"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCoreVideoIsAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCoreVideoIsAbsent"
        }
      ],
      "role": "symbol",
      "title": "kvImageCoreVideoIsAbsent",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecorevideoisabsent"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError": {
      "abstract": [
        {
          "text": "A serious error occured inside vImage, which prevented vImage from continuing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInternalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInternalError"
        }
      ],
      "role": "symbol",
      "title": "kvImageInternalError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinternalerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidCVImageFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidcvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle": {
      "abstract": [
        {
          "text": "The edge style specified is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidEdgeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidEdgeStyle",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidedgestyle"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageObject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageObject"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidImageObject",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidimageobject"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize": {
      "abstract": [
        {
          "text": "Either the kernel height, the kernel width, or both, are even.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidKernelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidKernelSize"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidKernelSize",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidkernelsize"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_X",
          "type": "codeVoice"
        },
        {
          "text": " parameter that specifies the left edge of the region of interest is greater than the width of the source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_X"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_X"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidOffset_X",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidoffset_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_Y",
          "type": "codeVoice"
        },
        {
          "text": " parameter that specifies the top edge of the region of interest is greater than the height of the source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_Y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_Y"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidOffset_Y",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidoffset_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter": {
      "abstract": [
        {
          "text": "Invalid parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidParameter",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidparameter"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidRowBytes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidRowBytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidRowBytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidRowBytes"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidRowBytes",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidrowbytes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError": {
      "abstract": [
        {
          "text": "An attempt to allocate memory failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageMemoryAllocationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageMemoryAllocationError"
        }
      ],
      "role": "symbol",
      "title": "kvImageMemoryAllocationError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagememoryallocationerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError": {
      "abstract": [
        {
          "text": "The vImage function completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageNoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenoerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument": {
      "abstract": [
        {
          "text": "A pointer parameter is ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " and it must not be.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNullPointerArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNullPointerArgument"
        }
      ],
      "role": "symbol",
      "title": "kvImageNullPointerArgument",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenullpointerargument"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageOutOfPlaceOperationRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageOutOfPlaceOperationRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageOutOfPlaceOperationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageOutOfPlaceOperationRequired"
        }
      ],
      "role": "symbol",
      "title": "kvImageOutOfPlaceOperationRequired",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageoutofplaceoperationrequired"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer": {
      "abstract": [
        {
          "text": "The region of interest, as specified by the ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_X",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_Y",
          "type": "codeVoice"
        },
        {
          "text": " parameters and the height and width of the destination buffer, extends beyond the bottom edge or right edge of the source buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageRoiLargerThanInputBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageRoiLargerThanInputBuffer"
        }
      ],
      "role": "symbol",
      "title": "kvImageRoiLargerThanInputBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageroilargerthaninputbuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit": {
      "abstract": [
        {
          "text": "The flag is not recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageUnknownFlagsBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageUnknownFlagsBit"
        }
      ],
      "role": "symbol",
      "title": "kvImageUnknownFlagsBit",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageunknownflagsbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnsupportedConversion": {
      "abstract": [
        {
          "text": "Some lower level conversion APIs only support conversion among a sparse matrix of image formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageUnsupportedConversion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnsupportedConversion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageUnsupportedConversion"
        }
      ],
      "role": "symbol",
      "title": "kvImageUnsupportedConversion",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageunsupportedconversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error": {
      "abstract": [
        {
          "text": "An error that occurs during a vImage operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "vImage.Error",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType": {
      "abstract": [
        {
          "text": "An enumeration of RGB -> Y’CbCr conversion matrix types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "role": "symbol",
      "title": "vImageMatrixType",
      "type": "topic",
      "url": "/documentation/accelerate/vimagematrixtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation": {
      "abstract": [
        {
          "text": "Constants for selecting the interpolation mode",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "role": "symbol",
      "title": "vImage_WarpInterpolation",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_warpinterpolation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
        "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
        "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageObject",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidRowBytes",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageOutOfPlaceOperationRequired",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnsupportedConversion"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Core-Video-Image-Format-Errors",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_NoError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ColorSpace",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ChromaSiting",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_AlphaIsOneHint",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_ConversionMatrix",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCVImageFormat_VideoChannelDescription"
      ],
      "title": "Core Video Image Format Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title",
          "value": "kvImageNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ChromaSiting/title",
          "value": "kvImageCVImageFormat_ChromaSiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ChromaSiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ChromaSiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidParameter/title",
          "value": "kvImageInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNullPointerArgument/title",
          "value": "kvImageNullPointerArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNullPointerArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNullPointerArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageObject/title",
          "value": "kvImageInvalidImageObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidImageObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ColorSpace/title",
          "value": "kvImageCVImageFormat_ColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_X/title",
          "value": "kvImageInvalidOffset_X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidOffset_X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidEdgeStyle/title",
          "value": "kvImageInvalidEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/title",
          "value": "vImage_WarpInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_NoError/title",
          "value": "kvImageCVImageFormat_NoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_NoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_NoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageOutOfPlaceOperationRequired/title",
          "value": "kvImageOutOfPlaceOperationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageOutOfPlaceOperationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageOutOfPlaceOperationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/title",
          "value": "vImageMatrixType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInternalError/title",
          "value": "kvImageInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInternalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidKernelSize/title",
          "value": "kvImageInvalidKernelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidKernelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidKernelSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnsupportedConversion/title",
          "value": "kvImageUnsupportedConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnsupportedConversion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageUnsupportedConversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageFormat/title",
          "value": "kvImageInvalidImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_AlphaIsOneHint/title",
          "value": "kvImageCVImageFormat_AlphaIsOneHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_AlphaIsOneHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_AlphaIsOneHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageMemoryAllocationError/title",
          "value": "kvImageMemoryAllocationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageMemoryAllocationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageMemoryAllocationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ConversionMatrix/title",
          "value": "kvImageCVImageFormat_ConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_ConversionMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_ConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidCVImageFormat/title",
          "value": "kvImageInvalidCVImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidCVImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnknownFlagsBit/title",
          "value": "kvImageUnknownFlagsBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnknownFlagsBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageUnknownFlagsBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageRoiLargerThanInputBuffer/title",
          "value": "kvImageRoiLargerThanInputBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageRoiLargerThanInputBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageRoiLargerThanInputBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_Y/title",
          "value": "kvImageInvalidOffset_Y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_Y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidOffset_Y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidRowBytes/title",
          "value": "kvImageInvalidRowBytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidRowBytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidRowBytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferSizeMismatch/title",
          "value": "kvImageBufferSizeMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferSizeMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferSizeMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCoreVideoIsAbsent/title",
          "value": "kvImageCoreVideoIsAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCoreVideoIsAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCoreVideoIsAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageColorSyncIsAbsent/title",
          "value": "kvImageColorSyncIsAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageColorSyncIsAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageColorSyncIsAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_VideoChannelDescription/title",
          "value": "kvImageCVImageFormat_VideoChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCVImageFormat_VideoChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCVImageFormat_VideoChannelDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
