{
  "abstract": [
    {
      "text": "Types of full- or half-precision gamma functions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/1584480-gamma-function-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Gamma function types"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping": {
      "abstract": [
        {
          "text": "Convert an RGB image to discrete luminance and chrominance channels, and apply color and contrast treatments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting saturation and applying tone mapping",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-saturation-and-applying-tone-mapping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_5_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 11/5 or 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_11_over_5_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_5_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_11_over_5_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_11_over_5_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_11_over_5_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_9_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 11/9 or (11/5)/(9/5).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_11_over_9_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_9_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_11_over_9_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_11_over_9_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_11_over_9_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_11_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 5/11 or 1/2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_5_over_11_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_11_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_5_over_11_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_5_over_11_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_5_over_11_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_9_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 5/9 or 1/1.8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_5_over_9_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_9_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_5_over_9_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_5_over_9_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_5_over_9_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_11_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 9/11 or (9/5)/(11/5).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_9_over_11_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_11_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_9_over_11_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_9_over_11_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_9_over_11_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_5_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using a gamma value of 9/5 or 1.8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_9_over_5_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_5_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_9_over_5_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_9_over_5_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_9_over_5_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_forward_half_precision": {
      "abstract": [
        {
          "text": "The ITU-R BT.709 standard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_BT709_forward_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_forward_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_BT709_forward_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_BT709_forward_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_bt709_forward_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_reverse_half_precision": {
      "abstract": [
        {
          "text": "The ITU-R BT.709 standard reverse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_BT709_reverse_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_reverse_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_BT709_reverse_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_BT709_reverse_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_bt709_reverse_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue": {
      "abstract": [
        {
          "text": "A user-defined gamma value with full-precision calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_UseGammaValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_UseGammaValue"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_UseGammaValue",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_usegammavalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue_half_precision": {
      "abstract": [
        {
          "text": "A user-defined gamma value with half-precision calculation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_UseGammaValue_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_UseGammaValue_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_UseGammaValue_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_usegammavalue_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_forward_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using the sRGB standard gamma value of 2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_sRGB_forward_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_forward_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_sRGB_forward_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_sRGB_forward_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_srgb_forward_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_reverse_half_precision": {
      "abstract": [
        {
          "text": "A half-precision calculation using the sRGB standard gamma value of 1/2.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageGamma_sRGB_reverse_half_precision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_reverse_half_precision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageGamma_sRGB_reverse_half_precision"
        }
      ],
      "role": "symbol",
      "title": "kvImageGamma_sRGB_reverse_half_precision",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagegamma_srgb_reverse_half_precision"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function": {
      "abstract": [
        {
          "text": "Use gamma functions to apply color transformations to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforming with a gamma function",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-with-a-gamma-function"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateGammaFunction(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a gamma function object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCreateGammaFunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GammaFunction",
          "text": "GammaFunction"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateGammaFunction(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCreateGammaFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageCreateGammaFunction(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecreategammafunction(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyGammaFunction(_:)": {
      "abstract": [
        {
          "text": "Destroys a gamma function object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageDestroyGammaFunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GammaFunction",
          "text": "GammaFunction"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyGammaFunction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageDestroyGammaFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageDestroyGammaFunction(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagedestroygammafunction(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_Planar8toPlanarF(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a gamma function to an 8-bit planar image to produce a 32-bit planar image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGamma_Planar8toPlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GammaFunction",
          "text": "GammaFunction"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_Planar8toPlanarF(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGamma_Planar8toPlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImageGamma_Planar8toPlanarF(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegamma_planar8toplanarf(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarF(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a gamma function to a PlanarF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGamma_PlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GammaFunction",
          "text": "GammaFunction"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarF(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGamma_PlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImageGamma_PlanarF(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegamma_planarf(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarFtoPlanar8(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a gamma function to a 32-bit planar image to produce an 8-bit planar image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGamma_PlanarFtoPlanar8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@GammaFunction",
          "text": "GammaFunction"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarFtoPlanar8(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGamma_PlanarFtoPlanar8"
        }
      ],
      "role": "symbol",
      "title": "vImageGamma_PlanarFtoPlanar8(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegamma_planarftoplanar8(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-a-gamma-function",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateGammaFunction(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_Planar8toPlanarF(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarFtoPlanar8(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGamma_PlanarF(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyGammaFunction(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping"
      ],
      "title": "Applying a gamma function"
    }
  ],
  "topicSections": [
    {
      "anchor": "User-defined-gamma-values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_UseGammaValue_half_precision"
      ],
      "title": "User-defined gamma values"
    },
    {
      "anchor": "Constant-gamma-values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_forward_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_BT709_reverse_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_forward_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_sRGB_reverse_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_9_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_5_over_11_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_5_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_9_over_11_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_5_half_precision",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageGamma_11_over_9_half_precision"
      ],
      "title": "Constant gamma values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_UseGammaValue_half_precision/title",
          "value": "kvImageGamma_UseGammaValue_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_UseGammaValue_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_UseGammaValue_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_9_over_5_half_precision/title",
          "value": "kvImageGamma_9_over_5_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_9_over_5_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_9_over_5_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_9_over_11_half_precision/title",
          "value": "kvImageGamma_9_over_11_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_9_over_11_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_9_over_11_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_BT709_reverse_half_precision/title",
          "value": "kvImageGamma_BT709_reverse_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_BT709_reverse_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_BT709_reverse_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_sRGB_reverse_half_precision/title",
          "value": "kvImageGamma_sRGB_reverse_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_sRGB_reverse_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_sRGB_reverse_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_5_over_11_half_precision/title",
          "value": "kvImageGamma_5_over_11_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_5_over_11_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_5_over_11_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_11_over_9_half_precision/title",
          "value": "kvImageGamma_11_over_9_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_11_over_9_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_11_over_9_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_UseGammaValue/title",
          "value": "kvImageGamma_UseGammaValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_UseGammaValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_UseGammaValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_PlanarFtoPlanar8(_:_:_:_:)/title",
          "value": "vImageGamma_PlanarFtoPlanar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_PlanarFtoPlanar8(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGamma_PlanarFtoPlanar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_PlanarF(_:_:_:_:)/title",
          "value": "vImageGamma_PlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_PlanarF(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGamma_PlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageDestroyGammaFunction(_:)/title",
          "value": "vImageDestroyGammaFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageDestroyGammaFunction(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageDestroyGammaFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateGammaFunction(_:_:_:)/title",
          "value": "vImageCreateGammaFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateGammaFunction(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCreateGammaFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_5_over_9_half_precision/title",
          "value": "kvImageGamma_5_over_9_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_5_over_9_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_5_over_9_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_11_over_5_half_precision/title",
          "value": "kvImageGamma_11_over_5_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_11_over_5_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_11_over_5_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_Planar8toPlanarF(_:_:_:_:)/title",
          "value": "vImageGamma_Planar8toPlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGamma_Planar8toPlanarF(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGamma_Planar8toPlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_BT709_forward_half_precision/title",
          "value": "kvImageGamma_BT709_forward_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_BT709_forward_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_BT709_forward_half_precision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_sRGB_forward_half_precision/title",
          "value": "kvImageGamma_sRGB_forward_half_precision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGamma_sRGB_forward_half_precision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageGamma_sRGB_forward_half_precision"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
