{
  "abstract": [
    {
      "text": "Perform operations on vectors that contain unsigned 32-bit integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/32-bit-unsigned-integer-vectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "32-Bit Unsigned Integer Vectors"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 16-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "16-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/16-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/64-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 64-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/64-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "64-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/64-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 8-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/8-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_uint16": {
      "abstract": [
        {
          "text": "A packed vector of sixteen 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_uint16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_uint16",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_uint16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_uint2": {
      "abstract": [
        {
          "text": "A packed vector of two 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_uint2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_uint2"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_uint2",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_uint2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_uint4": {
      "abstract": [
        {
          "text": "A packed vector of four 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_uint4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_uint4"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_uint4",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_uint4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_uint8": {
      "abstract": [
        {
          "text": "A packed vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_uint8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint1": {
      "abstract": [
        {
          "text": "A vector of one 32-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint1"
        }
      ],
      "role": "symbol",
      "title": "simd_uint1",
      "type": "topic",
      "url": "/documentation/simd/simd_uint1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint16": {
      "abstract": [
        {
          "text": "A vector of sixteen 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint16"
        }
      ],
      "role": "symbol",
      "title": "simd_uint16",
      "type": "topic",
      "url": "/documentation/simd/simd_uint16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint2": {
      "abstract": [
        {
          "text": "A vector of two 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint2"
        }
      ],
      "role": "symbol",
      "title": "simd_uint2",
      "type": "topic",
      "url": "/documentation/simd/simd_uint2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint3": {
      "abstract": [
        {
          "text": "A vector of three 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint3"
        }
      ],
      "role": "symbol",
      "title": "simd_uint3",
      "type": "topic",
      "url": "/documentation/simd/simd_uint3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint4": {
      "abstract": [
        {
          "text": "A vector of four 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint4"
        }
      ],
      "role": "symbol",
      "title": "simd_uint4",
      "type": "topic",
      "url": "/documentation/simd/simd_uint4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_uint8": {
      "abstract": [
        {
          "text": "A vector of eight 32-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_uint8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_uint8"
        }
      ],
      "role": "symbol",
      "title": "simd_uint8",
      "type": "topic",
      "url": "/documentation/simd/simd_uint8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unsigned-Integer-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/64-bit-unsigned-integer-vectors"
      ],
      "title": "Unsigned Integer Vectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_uint1",
        "doc://com.apple.accelerate/documentation/simd/simd_uint2",
        "doc://com.apple.accelerate/documentation/simd/simd_uint3",
        "doc://com.apple.accelerate/documentation/simd/simd_uint4",
        "doc://com.apple.accelerate/documentation/simd/simd_uint8",
        "doc://com.apple.accelerate/documentation/simd/simd_uint16"
      ],
      "title": "Vector Data Types"
    },
    {
      "anchor": "Packed-Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_packed_uint2",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_uint4",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_uint8",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_uint16"
      ],
      "title": "Packed Vector Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/title",
          "value": "simd_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint4/title",
          "value": "simd_packed_uint4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint2/title",
          "value": "simd_packed_uint2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/title",
          "value": "simd_uint2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint8/title",
          "value": "simd_packed_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/title",
          "value": "simd_uint3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/title",
          "value": "simd_uint1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/title",
          "value": "simd_uint8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint16/title",
          "value": "simd_packed_uint16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_uint16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_uint16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/title",
          "value": "simd_uint4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_uint4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_uint4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
