{
  "abstract": [
    {
      "text": "Obtain the availability of particular vImage features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/availability-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Availability Flags"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Image Format Errors",
      "type": "topic",
      "url": "/documentation/accelerate/1498271-core-video-image-format-errors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods": {
      "abstract": [
        {
          "text": "Specify the dithering method some vImage conversion functions use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dithering Methods",
      "type": "topic",
      "url": "/documentation/accelerate/1533233-dithering-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes": {
      "abstract": [
        {
          "text": "Error codes that vImage functions return when an operation fails.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error codes",
      "type": "topic",
      "url": "/documentation/accelerate/1578972-error-codes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags": {
      "abstract": [
        {
          "text": "Set flags on vImage operations to specify processing options.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Processing Flags",
      "type": "topic",
      "url": "/documentation/accelerate/1578976-processing-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE": {
      "abstract": [
        {
          "text": "Defined as ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " if double-precision affine transforms and related functions are supported on the current architecture and in the current SDK, else undefined. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_affinetransform_double_is_available"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE": {
      "abstract": [
        {
          "text": "Defined as ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " if Core Graphics affine transforms and related functions are supported on the current architecture and in the current SDK, else undefined. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_cgaffinetransform_is_available"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/buffer-types": {
      "abstract": [
        {
          "text": "Look up buffer type codes vImage conversions provide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Types",
      "type": "topic",
      "url": "/documentation/accelerate/buffer-types"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants": {
      "abstract": [
        {
          "text": "Look up type aliases, data types, and constants the vImage library uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/data-types-and-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Types and Constants",
      "type": "topic",
      "url": "/documentation/accelerate/data-types-and-constants"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays": {
      "abstract": [
        {
          "text": "Specify the decode array constant to use with 16Q12-formatted data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decode Arrays",
      "type": "topic",
      "url": "/documentation/accelerate/decode-arrays"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType": {
      "abstract": [
        {
          "text": "An enumeration of RGB -> Y’CbCr conversion matrix types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "role": "symbol",
      "title": "vImageMatrixType",
      "type": "topic",
      "url": "/documentation/accelerate/vimagematrixtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double": {
      "abstract": [
        {
          "text": "A structure for values that represent a double-precision affine transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_AffineTransform_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_AffineTransform_Double"
        }
      ],
      "role": "symbol",
      "title": "vImage_AffineTransform_Double",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_affinetransform_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform": {
      "abstract": [
        {
          "text": "A structure for values that represent a Core Graphics–compatible affine transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_CGAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "vImage_CGAffineTransform",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_cgaffinetransform"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation": {
      "abstract": [
        {
          "text": "Constants for selecting the interpolation mode",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "role": "symbol",
      "title": "vImage_WarpInterpolation",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_warpinterpolation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
        "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
        "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
        "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
        "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/title",
          "value": "vImage_WarpInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE/title",
          "value": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/title",
          "value": "vImageMatrixType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/title",
          "value": "vImage_CGAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_CGAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_CGAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE/title",
          "value": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/title",
          "value": "vImage_AffineTransform_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_AffineTransform_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_AffineTransform_Double"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
