{
  "abstract": [
    {
      "text": "An enumeration that acts as a namespace for Swift overlays to BLAS.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BLAS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:10Accelerate4BLASV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BLAS"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BLAS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BLAS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BLAS"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration provides methods and structures that offer a Swift-friendly API for Basic Linear Algebra Subprograms (BLAS) and Linear Algebra PACKage (LAPACK) operations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BLAS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS"
        }
      ],
      "role": "symbol",
      "title": "BLAS",
      "type": "topic",
      "url": "/documentation/accelerate/blas"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS/ThreadingModel-swift.struct": {
      "abstract": [
        {
          "text": "Constants that describe the BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ThreadingModel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS/ThreadingModel-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ThreadingModel"
        }
      ],
      "role": "symbol",
      "title": "BLAS.ThreadingModel",
      "type": "topic",
      "url": "/documentation/accelerate/blas/threadingmodel-swift.struct"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS/threadingModel-swift.type.property": {
      "abstract": [
        {
          "text": "The BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadingModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BLASV",
          "text": "BLAS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BLASV14ThreadingModelV",
          "text": "ThreadingModel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS/threadingModel-swift.type.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "threadingModel",
      "type": "topic",
      "url": "/documentation/accelerate/blas/threadingmodel-swift.type.property"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLASGetThreading()": {
      "abstract": [
        {
          "text": "Returns the current BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLASGetThreading"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BLAS_THREADING",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLASGetThreading()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLASGetThreading"
        }
      ],
      "role": "symbol",
      "title": "BLASGetThreading()",
      "type": "topic",
      "url": "/documentation/accelerate/blasgetthreading()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLASSetThreading(_:)": {
      "abstract": [
        {
          "text": "Sets the BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLASSetThreading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BLAS_THREADING",
          "text": "BLAS_THREADING"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLASSetThreading(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLASSetThreading"
        }
      ],
      "role": "symbol",
      "title": "BLASSetThreading(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/blassetthreading(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING": {
      "abstract": [
        {
          "text": "Constants that describe the BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS_THREADING"
        }
      ],
      "role": "symbol",
      "title": "BLAS_THREADING",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-threading-model",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BLASSetThreading(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BLASGetThreading()",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING"
      ],
      "title": "Specifying the threading model"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-the-BLAS-and-LAPACK-threading-model",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS/threadingModel-swift.type.property",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS/ThreadingModel-swift.struct"
      ],
      "title": "Setting the BLAS and LAPACK threading model"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLASSetThreading(_:)/title",
          "value": "BLASSetThreading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLASSetThreading(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLASSetThreading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLASGetThreading()/title",
          "value": "BLASGetThreading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLASGetThreading()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLASGetThreading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/title",
          "value": "BLAS_THREADING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/blas"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
