{
  "abstract": [
    {
      "text": "Constants that define the component filters of a fused layer.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSFilterType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSFilterType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSFilterType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSFilterType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedConvolutionNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a fused, convolution normalization layer and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FusedConvolutionNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedConvolutionNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FusedConvolutionNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.FusedConvolutionNormalizationLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fusedconvolutionnormalizationlayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedFullyConnectedNormalizationLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a fused, fully connected normalization layer and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FusedFullyConnectedNormalizationLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedFullyConnectedNormalizationLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FusedFullyConnectedNormalizationLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.FusedFullyConnectedNormalizationLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fusedfullyconnectednormalizationlayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedParametersLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a fused layer and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FusedParametersLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedParametersLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FusedParametersLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.FusedParametersLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fusedparameterslayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic": {
      "abstract": [
        {
          "text": "An arithmetic filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmetic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmetic"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm": {
      "abstract": [
        {
          "text": "A batch normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSBatchNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSBatchNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSBatchNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsbatchnorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution": {
      "abstract": [
        {
          "text": "A convolution filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSConvolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSConvolution"
        }
      ],
      "role": "symbol",
      "title": "BNNSConvolution",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsconvolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFusedLayer(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new fused layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateFusedLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFusedLayer(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateFusedLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterCreateFusedLayer(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltercreatefusedlayer(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType": {
      "abstract": [
        {
          "text": "Constants that define the component filters of a fused layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterType"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltertype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltertype/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltertype/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltertype/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected": {
      "abstract": [
        {
          "text": "A fully connected filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFullyConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFullyConnected"
        }
      ],
      "role": "symbol",
      "title": "BNNSFullyConnected",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfullyconnected"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a fused filter backward to generate input gradients.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBackwardBatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBackwardBatch"
        }
      ],
      "role": "symbol",
      "title": "BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfusedfilterapplybackwardbatch(_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a multiple-input fused filter backward to generate input gradients.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBackwardMultiInputBatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBackwardMultiInputBatch"
        }
      ],
      "role": "symbol",
      "title": "BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfusedfilterapplybackwardmultiinputbatch(_:_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a fused filter to a set of input objects, writing the result to a set of output objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyBatch"
        }
      ],
      "role": "symbol",
      "title": "BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfusedfilterapplybatch(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a multiple-input fused filter to a set of input objects, writing the result to a set of output objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyMultiInputBatch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFusedFilterApplyMultiInputBatch"
        }
      ],
      "role": "symbol",
      "title": "BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfusedfilterapplymultiinputbatch(_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm": {
      "abstract": [
        {
          "text": "A group normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGroupNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGroupNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSGroupNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgroupnorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm": {
      "abstract": [
        {
          "text": "An instance normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSInstanceNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSInstanceNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSInstanceNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsinstancenorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm": {
      "abstract": [
        {
          "text": "A layer normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSLayerNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSLayerNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSLayerNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnslayernorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization": {
      "abstract": [
        {
          "text": "A quantization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSQuantization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSQuantization"
        }
      ],
      "role": "symbol",
      "title": "BNNSQuantization",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsquantization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution": {
      "abstract": [
        {
          "text": "A transposed convolution filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSTransposedConvolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSTransposedConvolution"
        }
      ],
      "role": "symbol",
      "title": "BNNSTransposedConvolution",
      "type": "topic",
      "url": "/documentation/accelerate/bnnstransposedconvolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FusableLayerParameters": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FusableLayerParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FusableLayerParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FusableLayerParameters"
        }
      ],
      "role": "symbol",
      "title": "FusableLayerParameters",
      "type": "topic",
      "url": "/documentation/accelerate/fusablelayerparameters"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fused-layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/FusableLayerParameters",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedParametersLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedConvolutionNormalizationLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FusedFullyConnectedNormalizationLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFusedLayer(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)"
      ],
      "title": "Fused layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Layer-Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization"
      ],
      "title": "Layer Constants"
    },
    {
      "anchor": "Raw-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType/init(rawValue:)"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSFilterType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Layer-Constants",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization"
              ],
              "title": "Layer Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fused-layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFusedLayer(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)"
              ],
              "title": "Fused layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSFilterType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSQuantization/title",
          "value": "BNNSQuantization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSQuantization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSQuantization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateFusedLayer(_:_:_:_:)/title",
          "value": "BNNSFilterCreateFusedLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateFusedLayer(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateFusedLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTransposedConvolution/title",
          "value": "BNNSTransposedConvolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTransposedConvolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTransposedConvolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)/title",
          "value": "BNNSFusedFilterApplyMultiInputBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyMultiInputBatch(_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFusedFilterApplyMultiInputBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSInstanceNorm/title",
          "value": "BNNSInstanceNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSInstanceNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSInstanceNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnected/title",
          "value": "BNNSFullyConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFullyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSConvolution/title",
          "value": "BNNSConvolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSConvolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSConvolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerNorm/title",
          "value": "BNNSLayerNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGroupNorm/title",
          "value": "BNNSGroupNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGroupNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGroupNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "BNNSFusedFilterApplyBackwardMultiInputBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBackwardMultiInputBatch(_:_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFusedFilterApplyBackwardMultiInputBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/title",
          "value": "BNNSFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "BNNSFusedFilterApplyBackwardBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBackwardBatch(_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFusedFilterApplyBackwardBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSBatchNorm/title",
          "value": "BNNSBatchNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSBatchNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSBatchNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmetic/title",
          "value": "BNNSArithmetic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmetic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmetic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)/title",
          "value": "BNNSFusedFilterApplyBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFusedFilterApplyBatch(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFusedFilterApplyBatch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsfiltertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsfiltertype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
