{
  "abstract": [
    {
      "text": "An operation that calculates the element-wise sign of its input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSign"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSArithmeticFunction@BNNSArithmeticSign",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSArithmeticSign"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
        "text": "BNNSArithmeticFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSArithmeticSign"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSArithmeticSign"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSign"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
              "text": "BNNSArithmeticFunction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAbs": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise absolute of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticAbs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAbs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticAbs"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticAbs",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticabs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticCeil": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise ceiling of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticCeil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticCeil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticCeil"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticCeil",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticceil"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticErf": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise error function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticErf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticErf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticErf"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticErf",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticerf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloor": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise floor of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFloor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFloor"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticFloor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticfloor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction": {
      "abstract": [
        {
          "text": "Constants that define arithmetic operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticNegate": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise negation of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticNegate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticNegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticNegate"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticNegate",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticnegate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocal": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise reciprocal of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticReciprocal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticReciprocal"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticReciprocal",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticreciprocal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocalSquareRoot": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise reciprocal square root of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticReciprocalSquareRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocalSquareRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticReciprocalSquareRoot"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticReciprocalSquareRoot",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticreciprocalsquareroot"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticRound": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise rounding of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticRound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticRound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticRound"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticRound",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticround"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSign": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise sign of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSign"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSign",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSign"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticSign",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticsign"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquare": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise square of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSquare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSquare"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticSquare",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticsquare"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquareRoot": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise square root of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSquareRoot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquareRoot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSquareRoot"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticSquareRoot",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticsquareroot"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unary-Arithmetic-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticCeil",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquareRoot",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocalSquareRoot",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticRound",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAbs",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticErf",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticNegate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocal",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquare"
      ],
      "title": "Unary Arithmetic Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSArithmeticSign"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Unary-Arithmetic-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticCeil",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquareRoot",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocalSquareRoot",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticRound",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAbs",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticErf",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticNegate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticReciprocal",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSquare"
              ],
              "title": "Unary Arithmetic Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSArithmeticSign"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSign/title",
          "value": "BNNSArithmeticSign"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSign/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSign"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticRound/title",
          "value": "BNNSArithmeticRound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticRound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticRound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticNegate/title",
          "value": "BNNSArithmeticNegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticNegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticNegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticCeil/title",
          "value": "BNNSArithmeticCeil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticCeil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticCeil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSquare/title",
          "value": "BNNSArithmeticSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSquareRoot/title",
          "value": "BNNSArithmeticSquareRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSquareRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSquareRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticAbs/title",
          "value": "BNNSArithmeticAbs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticAbs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticAbs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticReciprocalSquareRoot/title",
          "value": "BNNSArithmeticReciprocalSquareRoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticReciprocalSquareRoot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticReciprocalSquareRoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticReciprocal/title",
          "value": "BNNSArithmeticReciprocal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticReciprocal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticReciprocal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/title",
          "value": "BNNSArithmeticFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticErf/title",
          "value": "BNNSArithmeticErf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticErf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticErf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFloor/title",
          "value": "BNNSArithmeticFloor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFloor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFloor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsarithmeticsign"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsarithmeticsign"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
