{"seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)"],"anchor":"Specifying-and-querying-a-contexts-properties","title":"Specifying and querying a context’s properties","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/accelerate/bnnsgraphcontextenablenanandinfchecks(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnsgraphcontextenablenanandinfchecks(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Specifies that the context checks intermediate tensors for NaNs and infinities.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextEnableNanAndInfChecks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","text":"bnns_graph_context_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"enable_check_for_nans_inf","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The graph context."}],"type":"paragraph"}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", specifies that the context checks intermediate tensors for NaNs and infinities.","type":"text"}]}],"name":"enable_check_for_nans_inf"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Don’t enable this option for production code.","type":"text"}],"type":"paragraph"}]}],"metadata":{"title":"BNNSGraphContextEnableNanAndInfChecks(_:_:)","navigatorTitle":[{"text":"BNNSGraphContextEnableNanAndInfChecks","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextEnableNanAndInfChecks","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_context_t","text":"bnns_graph_context_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Function","modules":[{"name":"Accelerate"}],"platforms":[{"introducedAt":"18.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"18.0","name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"18.0","name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"15.0","name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"18.0","name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"2.0","name":"visionOS","beta":false,"unavailable":false,"deprecated":false},{"introducedAt":"11.0","name":"watchOS","beta":false,"unavailable":false,"deprecated":false}],"symbolKind":"func","role":"symbol","externalID":"c:@F@BNNSGraphContextEnableNanAndInfChecks"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)"},"kind":"symbol","references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextgetworkspacesize(_:_:)","abstract":[{"text":"Returns the minimum size, in bytes, of the workspace that graph context execution requires.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextGetWorkspaceSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"BNNSGraphContextGetWorkspaceSize","kind":"identifier"}],"title":"BNNSGraphContextGetWorkspaceSize(_:_:)","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)":{"title":"BNNSGraphContextSetArgumentType(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetArgumentType"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextSetArgumentType"},{"text":"(","kind":"text"},{"text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentType","preciseIdentifier":"c:@EA@BNNSGraphArgumentType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"text":"Specifies the argument type for a graph context.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","url":"/documentation/accelerate/bnnsgraphcontextsetargumenttype(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","url":"/documentation/accelerate/bnnsgraphcontextsetbatchsize(_:_:_:)","kind":"symbol","navigatorTitle":[{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Sets the batch size for a graph.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphContextSetBatchSize(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_shape_t"}],"title":"bnns_graph_shape_t","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"abstract":[{"text":"The specification of the shape of an argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_shape_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextsetdynamicshapes(_:_:_:_:)","abstract":[{"text":"Specifies the dynamic shapes for a graph and, if possible, infers, the output shapes.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"BNNSGraphContextSetDynamicShapes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_shape_t","text":"bnns_graph_shape_t","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"}],"title":"BNNSGraphContextSetDynamicShapes(_:_:_:_:)","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentType","kind":"identifier"}],"title":"BNNSGraphArgumentType","kind":"symbol","navigatorTitle":[{"text":"BNNSGraphArgumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that specify the argument type for a graph context."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphargumenttype"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextsetstreamingadvancecount(_:_:)","abstract":[{"text":"Sets the streaming advancement amount for cases with dynamically shaped inputs.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextSetStreamingAdvanceCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetStreamingAdvanceCount"}],"title":"BNNSGraphContextSetStreamingAdvanceCount(_:_:)","beta":true,"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t":{"url":"/documentation/accelerate/bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","kind":"symbol","type":"topic","abstract":[{"text":"An object that wraps a compiled graph object.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_context_t"}],"role":"symbol","title":"bnns_graph_context_t","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_context_t"}]},"doc://com.externally.resolved.symbol/s:Sb":{"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"title":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","url":"/documentation/Swift/Bool","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"BNNSGraphContextEnableNanAndInfChecks(_:_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"}],"abstract":[{"text":"Specifies that the context checks intermediate tensors for NaNs and infinities.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphcontextenablenanandinfchecks(_:_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"18.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"15.0","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false},{"name":"watchOS","introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphContextEnableNanAndInfChecks","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Specifying and querying a context’s properties","anchor":"Specifying-and-querying-a-contexts-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextEnableNanAndInfChecks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","text":"bnns_graph_context_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:b","text":"bool"},{"kind":"text","text":" "},{"kind":"internalParam","text":"enable_check_for_nans_inf"},{"kind":"text","text":");"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"context","content":[{"type":"paragraph","inlineContent":[{"text":"The graph context.","type":"text"}]}]},{"name":"enable_check_for_nans_inf","content":[{"inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", specifies that the context checks intermediate tensors for NaNs and infinities.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"value":"BNNSGraphContextGetWorkspaceSize","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetWorkspaceSize(_:_:)/title"},{"value":[{"text":"BNNSGraphContextGetWorkspaceSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetWorkspaceSize(_:_:)/fragments"},{"value":"BNNSGraphContextSetArgumentType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetArgumentType(_:_:)/title"},{"value":[{"text":"BNNSGraphContextSetArgumentType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetArgumentType(_:_:)/fragments"},{"value":"BNNSGraphContextSetBatchSize","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetBatchSize(_:_:_:)/title"},{"value":[{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetBatchSize(_:_:_:)/fragments"},{"value":"bnns_graph_shape_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/title"},{"value":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/fragments"},{"value":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/navigatorTitle"},{"value":"BNNSGraphContextSetDynamicShapes","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetDynamicShapes(_:_:_:_:)/title"},{"value":[{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetDynamicShapes(_:_:_:_:)/fragments"},{"value":"BNNSGraphArgumentType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/title"},{"value":[{"kind":"identifier","text":"BNNSGraphArgumentType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/fragments"},{"value":[{"text":"BNNSGraphArgumentType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/navigatorTitle"},{"value":"BNNSGraphContextSetStreamingAdvanceCount","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetStreamingAdvanceCount(_:_:)/title"},{"value":[{"text":"BNNSGraphContextSetStreamingAdvanceCount","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetStreamingAdvanceCount(_:_:)/fragments"},{"value":"bnns_graph_context_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/title"},{"value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/fragments"},{"value":[{"kind":"identifier","text":"bnns_graph_context_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/navigatorTitle"},{"value":"BNNSGraphContextEnableNanAndInfChecks","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextEnableNanAndInfChecks(_:_:)/title"},{"value":[{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextEnableNanAndInfChecks(_:_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}