{"metadata":{"title":"BNNSGraphGetArgumentPosition(_:_:_:)","symbolKind":"func","modules":[{"name":"Accelerate"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"}],"roleHeading":"Function","role":"symbol","platforms":[{"name":"iOS","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"15.0","beta":false,"deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"18.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"2.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"11.0"}],"externalID":"c:@F@BNNSGraphGetArgumentPosition"},"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Querying-a-graphs-properties","title":"Querying a graph’s properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"]}],"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the index into the arguments array for the given function argument."}],"variants":[{"paths":["/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"graph"},{"text":": ","kind":"text"},{"text":"bnns_graph_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"function","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"argument","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The compiled graph object."}],"type":"paragraph"}],"name":"graph"},{"content":[{"inlineContent":[{"type":"text","text":"The function. Specify as "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the graph only contains one function."}],"type":"paragraph"}],"name":"function"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the input or output argument.","type":"text"}]}],"name":"argument"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the index into the arguments array for the given function argument, or "},{"type":"codeVoice","code":"SIZE_T_MAX"},{"type":"text","text":" if the query fails."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","abstract":[{"text":"Returns the number of input arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputCount"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"BNNSGraphGetInputCount(_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)":{"title":"BNNSGraphGetFunctionNames(_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphGetFunctionNames"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/accelerate/bnnsgraphgetfunctionnames(_:_:_:)","navigatorTitle":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Extracts the names of callable functions in the graph.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetOutputNames"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of output arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","title":"BNNSGraphGetOutputNames(_:_:_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentIntents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","text":"BNNSGraphArgumentIntent","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"BNNSGraphGetArgumentIntents(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","abstract":[{"text":"Extracts the intents of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentintents(_:_:_:_:)"},"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Int8","preciseIdentifier":"s:s4Int8V"}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"symbol","url":"/documentation/Swift/CChar","role":"symbol","abstract":[{"text":"The C ‘char’ type.","type":"text"}],"title":"CChar","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","abstract":[{"text":"Returns the number of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"url":"/documentation/accelerate/bnnsgraphargumentintent","abstract":[{"text":"Constants that describe argument intents.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","type":"topic","title":"BNNSGraphArgumentIntent"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":">?>, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","abstract":[{"text":"Returns the interleave factors for arguments, if present","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentinterleavefactors(_:_:_:_:_:)"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetOutputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetOutputCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","abstract":[{"text":"Returns the number of output arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t":{"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_t"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_t"}],"title":"bnns_graph_t","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","abstract":[{"text":"The compiled graph object.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputNames"},{"kind":"text","text":"("},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"BNNSGraphGetInputNames(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of input arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)":{"navigatorTitle":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetFunctionCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetFunctionCount(_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","abstract":[{"type":"text","text":"Returns the number of callable functions in the specified graph."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetfunctioncount(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentPosition(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","abstract":[{"type":"text","text":"Returns the index into the arguments array for the given function argument."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"url":"/documentation/accelerate/bnnsgraphgetargumentnames(_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","title":"BNNSGraphGetArgumentNames(_:_:_:_:)","abstract":[{"type":"text","text":"Extracts the names of arguments for the given function argument."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"18.0"},{"name":"iPadOS","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"15.0","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","introducedAt":"18.0","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"2.0","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","introducedAt":"11.0","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Function","path":"/metadata/roleHeading"},{"op":"replace","value":"BNNSGraphGetArgumentPosition","path":"/metadata/title"},{"op":"replace","value":"func","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"title":"Querying a graph’s properties","anchor":"Querying-a-graphs-properties"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"preciseIdentifier":"c:@T@size_t","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","text":"size_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@SA@bnns_graph_t","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","text":"bnns_graph_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"graph"},{"kind":"text","text":", "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"char","kind":"typeIdentifier","preciseIdentifier":"c:C"},{"text":" * ","kind":"text"},{"text":"function","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"char","kind":"typeIdentifier","preciseIdentifier":"c:C"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"argument"},{"kind":"text","text":");"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"graph","content":[{"type":"paragraph","inlineContent":[{"text":"The compiled graph object.","type":"text"}]}]},{"name":"function","content":[{"inlineContent":[{"text":"The function. Specify as ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the graph only contains one function.","type":"text"}],"type":"paragraph"}]},{"name":"argument","content":[{"inlineContent":[{"type":"text","text":"The name of the input or output argument."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Returns the index into the arguments array for the given function argument, or ","type":"text"},{"code":"SIZE_T_MAX","type":"codeVoice"},{"text":" if the query fails.","type":"text"}]}]},"path":"/primaryContentSections/2"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/title","value":"BNNSGraphGetInputCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/title","value":"BNNSGraphGetFunctionNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/fragments","value":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/title","value":"BNNSGraphGetOutputNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetOutputNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/title","value":"BNNSGraphGetArgumentIntents"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/title","value":"BNNSGraphGetArgumentCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/title","value":"BNNSGraphArgumentIntent"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/fragments","value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/navigatorTitle","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/title","value":"BNNSGraphGetArgumentInterleaveFactors"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/title","value":"BNNSGraphGetOutputCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/fragments","value":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/title","value":"bnns_graph_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/fragments","value":[{"text":"bnns_graph_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/navigatorTitle","value":[{"text":"bnns_graph_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/title","value":"BNNSGraphGetInputNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/title","value":"BNNSGraphGetFunctionCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphGetFunctionCount"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/title","value":"BNNSGraphGetArgumentPosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/title","value":"BNNSGraphGetArgumentNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentNames","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}