{
  "abstract": [
    {
      "text": "Constants that describe the data type of an n-dimensional array.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSDataLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSDataLayout"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSDataLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSDataLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSDataLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Shape": {
      "abstract": [
        {
          "text": "Constants that describe the size and data layout of an n-dimensional array descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Shape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Shape"
        }
      ],
      "role": "symbol",
      "title": "BNNS.Shape",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/shape"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout": {
      "abstract": [
        {
          "text": "Constants that describe the data type of an n-dimensional array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 1D first-major vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout1DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout1DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout1DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout1dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 1D last-major vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout1DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout1DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout1DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout1dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 2D first-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout2DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout2DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout2DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout2dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 2D last-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout2DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout2DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout2DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout2dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 3D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout3DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout3DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout3DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout3dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 3D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout3DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout3DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout3DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout3dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 4D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout4DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout4DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout4DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout4dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 4D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout4DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout4DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout4DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout4dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 5D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout5DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout5DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout5DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout5dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 5D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout5DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout5DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout5DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout5dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 6D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout6DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout6DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout6DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout6dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 6D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout6DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout6DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout6DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout6dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 7D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout7DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout7DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout7DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout7dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 7D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout7DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout7DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout7DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout7dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DFirstMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 8D first-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout8DFirstMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DFirstMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout8DFirstMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout8DFirstMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout8dfirstmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DLastMajor": {
      "abstract": [
        {
          "text": "A constant that represents a 8D last-major tensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayout8DLastMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DLastMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayout8DLastMajor"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayout8DLastMajor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayout8dlastmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutColumnMajorMatrix": {
      "abstract": [
        {
          "text": "A constant that represents a 2D column-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutColumnMajorMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutColumnMajorMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutColumnMajorMatrix"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutColumnMajorMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutcolumnmajormatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsIOHrWr": {
      "abstract": [
        {
          "text": "A constant that represents a 4D array of rotated convolution weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsIOHrWr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsIOHrWr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsIOHrWr"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutConvolutionWeightsIOHrWr",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutconvolutionweightsiohrwr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW": {
      "abstract": [
        {
          "text": "A constant that represents a 4D array of convolution weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutConvolutionWeightsOIHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutconvolutionweightsoihw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW_Pack32": {
      "abstract": [
        {
          "text": "A constant that represents a 4D array of packed convolution weights with 32-output channel packing and 128-byte array address alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHW_Pack32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW_Pack32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHW_Pack32"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutConvolutionWeightsOIHW_Pack32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutconvolutionweightsoihw_pack32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHrWr": {
      "abstract": [
        {
          "text": "A constant that represents a 4D array of rotated convolution weights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHrWr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHrWr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutConvolutionWeightsOIHrWr"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutConvolutionWeightsOIHrWr",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutconvolutionweightsoihrwr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutFullyConnectedSparse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutFullyConnectedSparse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutFullyConnectedSparse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutFullyConnectedSparse"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutFullyConnectedSparse",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutfullyconnectedsparse"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutGetRank(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutGetRank"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutGetRank(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutGetRank"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutGetRank(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutgetrank(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutImageCHW": {
      "abstract": [
        {
          "text": "A constant that represents a 3D image stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutImageCHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutImageCHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutImageCHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutImageCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutimagechw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutMHA_DHK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutMHA_DHK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutMHA_DHK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutMHA_DHK"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutMHA_DHK",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutmha_dhk"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutNSE": {
      "abstract": [
        {
          "text": "A constant that represents a 3D tensor with the size elements embedding dimension, sequence length, and batch size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutNSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutNSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutNSE"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutNSE",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutnse"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutRowMajorMatrix": {
      "abstract": [
        {
          "text": "A constant that represents a 2D row-major matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutRowMajorMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutRowMajorMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutRowMajorMatrix"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutRowMajorMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutrowmajormatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutSNE": {
      "abstract": [
        {
          "text": "A constant that represents a 3D tensor with the size elements embedding dimension, batch size, and sequence length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutSNE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutSNE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutSNE"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutSNE",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutsne"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutVector": {
      "abstract": [
        {
          "text": "A constant that represents a 1D vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutVector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataLayout",
          "text": "BNNSDataLayout"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutVector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataLayoutVector"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataLayoutVector",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatalayoutvector"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType": {
      "abstract": [
        {
          "text": "BNNS Data Types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerData": {
      "abstract": [
        {
          "text": "A structure containing common layer parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSLayerData"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSLayerData"
        }
      ],
      "role": "symbol",
      "title": "BNNSLayerData",
      "type": "topic",
      "url": "/documentation/accelerate/bnnslayerdata"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor": {
      "abstract": [
        {
          "text": "A structure that describes the shape, stride, data type, and, optionally, the memory location of an n-dimensional array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSNDArrayDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsndarraydescriptor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "N-dimensional-array-descriptor-essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerData",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Shape",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutGetRank(_:)"
      ],
      "title": "N-dimensional array descriptor essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "1D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutVector",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DLastMajor"
      ],
      "title": "1D Data Layouts"
    },
    {
      "anchor": "2D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutColumnMajorMatrix",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutRowMajorMatrix",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DLastMajor"
      ],
      "title": "2D Data Layouts"
    },
    {
      "anchor": "3D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutImageCHW",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DLastMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutSNE",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutNSE"
      ],
      "title": "3D Data Layouts"
    },
    {
      "anchor": "4D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsIOHrWr",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHrWr",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW_Pack32",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DLastMajor"
      ],
      "title": "4D Data Layouts"
    },
    {
      "anchor": "5D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DLastMajor"
      ],
      "title": "5D Data Layouts"
    },
    {
      "anchor": "6D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DLastMajor"
      ],
      "title": "6D Data Layouts"
    },
    {
      "anchor": "7D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DLastMajor"
      ],
      "title": "7D Data Layouts"
    },
    {
      "anchor": "8D-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DFirstMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DLastMajor"
      ],
      "title": "8D Data Layouts"
    },
    {
      "anchor": "Other-Data-Layouts",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutFullyConnectedSparse",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutMHA_DHK"
      ],
      "title": "Other Data Layouts"
    },
    {
      "anchor": "Raw-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout/rawValue"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSDataLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "1D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutVector",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout1DLastMajor"
              ],
              "title": "1D Data Layouts"
            },
            {
              "anchor": "2D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutColumnMajorMatrix",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutRowMajorMatrix",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout2DLastMajor"
              ],
              "title": "2D Data Layouts"
            },
            {
              "anchor": "3D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutImageCHW",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout3DLastMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutSNE",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutNSE"
              ],
              "title": "3D Data Layouts"
            },
            {
              "anchor": "4D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsIOHrWr",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHrWr",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutConvolutionWeightsOIHW_Pack32",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout4DLastMajor"
              ],
              "title": "4D Data Layouts"
            },
            {
              "anchor": "5D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout5DLastMajor"
              ],
              "title": "5D Data Layouts"
            },
            {
              "anchor": "6D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout6DLastMajor"
              ],
              "title": "6D Data Layouts"
            },
            {
              "anchor": "7D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout7DLastMajor"
              ],
              "title": "7D Data Layouts"
            },
            {
              "anchor": "8D-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DFirstMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayout8DLastMajor"
              ],
              "title": "8D Data Layouts"
            },
            {
              "anchor": "Other-Data-Layouts",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutFullyConnectedSparse",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutMHA_DHK"
              ],
              "title": "Other Data Layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "N-dimensional-array-descriptor-essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerData",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataLayoutGetRank(_:)"
              ],
              "title": "N-dimensional array descriptor essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSDataLayout"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout8DFirstMajor/title",
          "value": "BNNSDataLayout8DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout8DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout8DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHrWr/title",
          "value": "BNNSDataLayoutConvolutionWeightsOIHrWr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHrWr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutConvolutionWeightsOIHrWr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout5DFirstMajor/title",
          "value": "BNNSDataLayout5DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout5DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout5DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerData/title",
          "value": "BNNSLayerData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout/title",
          "value": "BNNSDataLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutRowMajorMatrix/title",
          "value": "BNNSDataLayoutRowMajorMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutRowMajorMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutRowMajorMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout6DFirstMajor/title",
          "value": "BNNSDataLayout6DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout6DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout6DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout4DLastMajor/title",
          "value": "BNNSDataLayout4DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout4DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout4DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutImageCHW/title",
          "value": "BNNSDataLayoutImageCHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutImageCHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutImageCHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout6DLastMajor/title",
          "value": "BNNSDataLayout6DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout6DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout6DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutFullyConnectedSparse/title",
          "value": "BNNSDataLayoutFullyConnectedSparse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutFullyConnectedSparse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutFullyConnectedSparse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsIOHrWr/title",
          "value": "BNNSDataLayoutConvolutionWeightsIOHrWr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsIOHrWr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutConvolutionWeightsIOHrWr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHW_Pack32/title",
          "value": "BNNSDataLayoutConvolutionWeightsOIHW_Pack32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHW_Pack32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutConvolutionWeightsOIHW_Pack32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHW/title",
          "value": "BNNSDataLayoutConvolutionWeightsOIHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutConvolutionWeightsOIHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutConvolutionWeightsOIHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout5DLastMajor/title",
          "value": "BNNSDataLayout5DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout5DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout5DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout4DFirstMajor/title",
          "value": "BNNSDataLayout4DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout4DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout4DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout2DLastMajor/title",
          "value": "BNNSDataLayout2DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout2DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout2DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout3DFirstMajor/title",
          "value": "BNNSDataLayout3DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout3DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout3DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutGetRank(_:)/title",
          "value": "BNNSDataLayoutGetRank"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutGetRank(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutGetRank"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutColumnMajorMatrix/title",
          "value": "BNNSDataLayoutColumnMajorMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutColumnMajorMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutColumnMajorMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutNSE/title",
          "value": "BNNSDataLayoutNSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutNSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutNSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title",
          "value": "BNNSDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout8DLastMajor/title",
          "value": "BNNSDataLayout8DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout8DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout8DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout7DFirstMajor/title",
          "value": "BNNSDataLayout7DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout7DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout7DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/title",
          "value": "BNNSNDArrayDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSNDArrayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSNDArrayDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSNDArrayDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout7DLastMajor/title",
          "value": "BNNSDataLayout7DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout7DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout7DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutMHA_DHK/title",
          "value": "BNNSDataLayoutMHA_DHK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutMHA_DHK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutMHA_DHK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutVector/title",
          "value": "BNNSDataLayoutVector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutVector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutVector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout3DLastMajor/title",
          "value": "BNNSDataLayout3DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout3DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout3DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout2DFirstMajor/title",
          "value": "BNNSDataLayout2DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout2DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout2DFirstMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout1DLastMajor/title",
          "value": "BNNSDataLayout1DLastMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout1DLastMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout1DLastMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutSNE/title",
          "value": "BNNSDataLayoutSNE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayoutSNE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayoutSNE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout1DFirstMajor/title",
          "value": "BNNSDataLayout1DFirstMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataLayout1DFirstMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataLayout1DFirstMajor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsdatalayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsdatalayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
