{"abstract":[{"text":"Returns the number of input arguments for the given function argument.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputCount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"graph","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"bnns_graph_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"function","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"graph","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The compiled graph object."}]}]},{"name":"function","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The function. Specify as "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the graph only contains one function."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The number of input arguments, or "},{"type":"codeVoice","code":"SIZE_T_MAX"},{"type":"text","text":" if the query fails."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)"},"sections":[],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"generated":true,"title":"Querying a graph’s properties","anchor":"Querying-a-graphs-properties"}],"metadata":{"roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetInputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"BNNSGraphGetInputCount","kind":"identifier"}],"title":"BNNSGraphGetInputCount(_:_:)","modules":[{"name":"Accelerate"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"macOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"visionOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"11.0","name":"watchOS","beta":false}],"symbolKind":"func","externalID":"c:@F@BNNSGraphGetInputCount","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"url":"/documentation/accelerate/bnnsgraphargumentintent","abstract":[{"text":"Constants that describe argument intents.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","type":"topic","title":"BNNSGraphArgumentIntent"},"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentIntents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","text":"BNNSGraphArgumentIntent","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"BNNSGraphGetArgumentIntents(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","abstract":[{"text":"Extracts the intents of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentintents(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputNames"},{"kind":"text","text":"("},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"BNNSGraphGetInputNames(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of input arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputnames(_:_:_:_:)"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","abstract":[{"text":"Returns the number of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":">?>, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","abstract":[{"text":"Returns the interleave factors for arguments, if present","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentinterleavefactors(_:_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetOutputNames"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of output arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","title":"BNNSGraphGetOutputNames(_:_:_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)":{"navigatorTitle":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetFunctionCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetFunctionCount(_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","abstract":[{"type":"text","text":"Returns the number of callable functions in the specified graph."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetfunctioncount(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","abstract":[{"text":"Returns the number of input arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputCount"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"BNNSGraphGetInputCount(_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetOutputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetOutputCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","abstract":[{"text":"Returns the number of output arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"url":"/documentation/accelerate/bnnsgraphgetargumentnames(_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","title":"BNNSGraphGetArgumentNames(_:_:_:_:)","abstract":[{"type":"text","text":"Extracts the names of arguments for the given function argument."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Int8","preciseIdentifier":"s:s4Int8V"}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"symbol","url":"/documentation/Swift/CChar","role":"symbol","abstract":[{"text":"The C ‘char’ type.","type":"text"}],"title":"CChar","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)":{"title":"BNNSGraphGetFunctionNames(_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphGetFunctionNames"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/accelerate/bnnsgraphgetfunctionnames(_:_:_:)","navigatorTitle":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Extracts the names of callable functions in the graph.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentPosition(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","abstract":[{"type":"text","text":"Returns the index into the arguments array for the given function argument."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t":{"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_t"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_t"}],"title":"bnns_graph_t","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","abstract":[{"text":"The compiled graph object.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_t"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"18.0","unavailable":false},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"18.0","unavailable":false},{"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0","unavailable":false},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"15.0","unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"18.0","unavailable":false},{"beta":false,"unavailable":false,"introducedAt":"2.0","name":"visionOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"11.0","name":"watchOS","deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"BNNSGraphGetInputCount"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"BNNSGraphGetInputCount","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"anchor":"Querying-a-graphs-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"generated":true,"title":"Querying a graph’s properties"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"size_t","preciseIdentifier":"c:@T@size_t","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetInputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t"},{"text":" ","kind":"text"},{"text":"graph","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"char","kind":"typeIdentifier","preciseIdentifier":"c:C"},{"text":" * ","kind":"text"},{"text":"function","kind":"internalParam"},{"text":");","kind":"text"}]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The compiled graph object.","type":"text"}],"type":"paragraph"}],"name":"graph"},{"content":[{"inlineContent":[{"text":"The function. Specify as ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the graph only contains one function.","type":"text"}],"type":"paragraph"}],"name":"function"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of input arguments, or "},{"code":"SIZE_T_MAX","type":"codeVoice"},{"type":"text","text":" if the query fails."}]}]}},{"value":"BNNSGraphArgumentIntent","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/fragments","op":"replace"},{"value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/navigatorTitle","op":"replace"},{"value":"BNNSGraphGetArgumentIntents","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetArgumentIntents","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetInputNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphGetInputNames"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetArgumentCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetArgumentInterleaveFactors","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetOutputNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetOutputNames","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetFunctionCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/fragments","op":"replace"},{"value":"BNNSGraphGetInputCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetInputCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetOutputCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/title","op":"replace"},{"value":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetArgumentNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetFunctionNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphGetFunctionNames"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphGetArgumentPosition","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/fragments","op":"replace"},{"value":"bnns_graph_t","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/title","op":"replace"},{"value":[{"text":"bnns_graph_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/fragments","op":"replace"},{"value":[{"text":"bnns_graph_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}