{"kind":"symbol","topicSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/rawValue"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"externalID":"c:@EA@BNNSTargetSystem","roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTargetSystem","kind":"identifier"}],"modules":[{"name":"Accelerate"}],"role":"symbol","title":"BNNSTargetSystem","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false},{"beta":false,"unavailable":false,"name":"watchOS","deprecated":false}],"symbolKind":"struct","navigatorTitle":[{"text":"BNNSTargetSystem","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSTargetSystem"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnstargetsystem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnstargetsystem"]}],"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"],"generated":true,"title":"Structures","anchor":"Structures"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor":{"title":"BNNSVectorDescriptor","navigatorTitle":[{"kind":"identifier","text":"BNNSVectorDescriptor"}],"type":"topic","kind":"symbol","url":"/documentation/accelerate/bnnsvectordescriptor","deprecated":true,"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSVectorDescriptor","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSSparsityType"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSSparsityType"}],"title":"BNNSSparsityType","url":"/documentation/accelerate/bnnssparsitytype","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","abstract":[]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(_:)":{"type":"topic","kind":"symbol","url":"/documentation/accelerate/bnnstargetsystem/init(_:)","title":"init(_:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(_:)","abstract":[],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/init(rawValue:)","url":"/documentation/accelerate/bnnstargetsystem/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t":{"type":"topic","abstract":[{"text":"Describes data associated with an input or output argument","type":"text"}],"title":"bnns_graph_argument_t","kind":"symbol","navigatorTitle":[{"text":"bnns_graph_argument_t","kind":"identifier"}],"url":"/documentation/accelerate/bnns_graph_argument_t","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bnns_graph_argument_t","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType":{"abstract":[{"type":"text","text":"BNNS Data Types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSDataType"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSDataType"}],"type":"topic","url":"/documentation/accelerate/bnnsdatatype","title":"BNNSDataType"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","url":"/documentation/accelerate/bnnssparsityparameters","navigatorTitle":[{"kind":"identifier","text":"BNNSSparsityParameters"}],"title":"BNNSSparsityParameters","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSSparsityParameters"}],"role":"symbol","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/rawValue":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem/rawValue","role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"}],"url":"/documentation/accelerate/bnnstargetsystem/rawvalue","abstract":[],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"kind":"symbol","abstract":[{"text":"","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"title":"Equatable","type":"topic"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","title":"Sendable","kind":"symbol","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"BNNSImageStackDescriptor","url":"/documentation/accelerate/bnnsimagestackdescriptor","navigatorTitle":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","role":"symbol","abstract":[],"deprecated":true},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","role":"symbol","kind":"symbol","url":"/documentation/Swift/RawRepresentable","identifier":"doc://com.externally.resolved.symbol/s:SY","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem":{"type":"topic","navigatorTitle":[{"text":"BNNSTargetSystem","kind":"identifier"}],"kind":"symbol","url":"/documentation/accelerate/bnnstargetsystem","title":"BNNSTargetSystem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTargetSystem","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem","abstract":[],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"title":"Hashable","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"kind":"text","text":" : "},{"text":"Equatable","preciseIdentifier":"s:SQ","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSTargetSystem","op":"replace","path":"/metadata/title"},{"value":"enum","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"BNNSTargetSystem","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"BNNSTargetSystem"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"anchor":"Structures","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"],"generated":true,"title":"Structures"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"BNNSTargetSystem","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"BNNSVectorDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/title"},{"value":[{"text":"BNNSVectorDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/fragments"},{"value":[{"kind":"identifier","text":"BNNSVectorDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/navigatorTitle"},{"value":"BNNSSparsityType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/title"},{"value":[{"text":"BNNSSparsityType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/fragments"},{"value":[{"kind":"identifier","text":"BNNSSparsityType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/navigatorTitle"},{"value":"bnns_graph_argument_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/title"},{"value":[{"text":"bnns_graph_argument_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/fragments"},{"value":[{"kind":"identifier","text":"bnns_graph_argument_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/navigatorTitle"},{"value":"BNNSDataType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title"},{"value":[{"kind":"identifier","text":"BNNSDataType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments"},{"value":[{"kind":"identifier","text":"BNNSDataType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle"},{"value":"BNNSSparsityParameters","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/title"},{"value":[{"text":"BNNSSparsityParameters","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/fragments"},{"value":[{"kind":"identifier","text":"BNNSSparsityParameters"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/navigatorTitle"},{"value":"BNNSImageStackDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/title"},{"value":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/fragments"},{"value":[{"kind":"identifier","text":"BNNSImageStackDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/navigatorTitle"},{"value":"BNNSTargetSystem","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/title"},{"value":[{"kind":"identifier","text":"BNNSTargetSystem"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/fragments"},{"value":[{"text":"BNNSTargetSystem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/navigatorTitle"}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]},"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}