{
  "abstract": [
    {
      "text": "The operator that indicates the logical NOT relationship.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSRelationalOperator@BNNSRelationalOperatorLogicalNOT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperatorLogicalNOT"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
        "text": "BNNSRelationalOperator"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperatorLogicalNOT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSRelationalOperatorLogicalNOT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOT"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
              "text": "BNNSRelationalOperator"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator": {
      "abstract": [
        {
          "text": "Constants that describe relational operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND": {
      "abstract": [
        {
          "text": "The operator that indicates the logical AND relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalAND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalAND"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalAND",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicaland"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NAND relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNAND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNAND"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNAND",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnand"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NOR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NOT relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOT"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNOT",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnot"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical OR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical XOR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalXOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalXOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalXOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalxor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Logical-Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR"
      ],
      "title": "Logical Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSRelationalOperatorLogicalNOT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Logical-Operators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR"
              ],
              "title": "Logical Operators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSRelationalOperatorLogicalNOT"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNAND/title",
          "value": "BNNSRelationalOperatorLogicalNAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalAND/title",
          "value": "BNNSRelationalOperatorLogicalAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/title",
          "value": "BNNSRelationalOperator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOT/title",
          "value": "BNNSRelationalOperatorLogicalNOT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalOR/title",
          "value": "BNNSRelationalOperatorLogicalOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOR/title",
          "value": "BNNSRelationalOperatorLogicalNOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalXOR/title",
          "value": "BNNSRelationalOperatorLogicalXOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalXOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalXOR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperatorlogicalnot"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperatorlogicalnot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
