{
  "abstract": [
    {
      "text": "An operation that calculates the element-wise maximum of its two inputs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMaximum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSArithmeticFunction@BNNSArithmeticMaximum",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSArithmeticMaximum"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
        "text": "BNNSArithmeticFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSArithmeticMaximum"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSArithmeticMaximum"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMaximum"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
              "text": "BNNSArithmeticFunction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAdd": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise sum of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticAdd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAdd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticAdd"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticAdd",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticadd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivide": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise division of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticDivide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticDivide"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticDivide",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticdivide"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivideNoNaN": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise division of its two inputs and returns zero if the divisor is zero, even if the first input is NaN or infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticDivideNoNaN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivideNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticDivideNoNaN"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticDivideNoNaN",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticdividenonan"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloorDivide": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise floor division of its inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFloorDivide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloorDivide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFloorDivide"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticFloorDivide",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticfloordivide"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction": {
      "abstract": [
        {
          "text": "Constants that define arithmetic operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMaximum": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise maximum of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMaximum"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticMaximum",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticmaximum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMinimum": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise minimum of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMinimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMinimum"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticMinimum",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticminimum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiply": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise product of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMultiply"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMultiply"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticMultiply",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticmultiply"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiplyNoNaN": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise product of its two inputs and returns zero, even if the first input is NaN or infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMultiplyNoNaN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiplyNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticMultiplyNoNaN"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticMultiplyNoNaN",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticmultiplynonan"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticPow": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise first input raised to the power of its second input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticPow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticPow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticPow"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticPow",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticpow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSubtract": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise difference of its two inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSubtract"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSubtract",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticSubtract"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticSubtract",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmeticsubtract"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncDivide": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise truncated division of its inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticTruncDivide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncDivide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticTruncDivide"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticTruncDivide",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmetictruncdivide"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncRemainder": {
      "abstract": [
        {
          "text": "An operation that calculates the element-wise remainder of truncated division of its inputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmeticTruncRemainder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSArithmeticFunction",
          "text": "BNNSArithmeticFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncRemainder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmeticTruncRemainder"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmeticTruncRemainder",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmetictruncremainder"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Binary-Arithmetic-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAdd",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSubtract",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivide",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivideNoNaN",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiply",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiplyNoNaN",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticPow",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMinimum",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloorDivide",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncDivide",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncRemainder"
      ],
      "title": "Binary Arithmetic Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSArithmeticMaximum"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Binary-Arithmetic-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticAdd",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticSubtract",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivide",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticDivideNoNaN",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiply",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMultiplyNoNaN",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticPow",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticMinimum",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticFloorDivide",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncDivide",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmeticTruncRemainder"
              ],
              "title": "Binary Arithmetic Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSArithmeticMaximum"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticPow/title",
          "value": "BNNSArithmeticPow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticPow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticPow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticTruncDivide/title",
          "value": "BNNSArithmeticTruncDivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticTruncDivide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticTruncDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticAdd/title",
          "value": "BNNSArithmeticAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticAdd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFloorDivide/title",
          "value": "BNNSArithmeticFloorDivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFloorDivide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFloorDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMinimum/title",
          "value": "BNNSArithmeticMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSubtract/title",
          "value": "BNNSArithmeticSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticSubtract/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticSubtract"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/title",
          "value": "BNNSArithmeticFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMaximum/title",
          "value": "BNNSArithmeticMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticDivide/title",
          "value": "BNNSArithmeticDivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticDivide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticTruncRemainder/title",
          "value": "BNNSArithmeticTruncRemainder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticTruncRemainder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticTruncRemainder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticDivideNoNaN/title",
          "value": "BNNSArithmeticDivideNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticDivideNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticDivideNoNaN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMultiply/title",
          "value": "BNNSArithmeticMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMultiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMultiplyNoNaN/title",
          "value": "BNNSArithmeticMultiplyNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmeticMultiplyNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmeticMultiplyNoNaN"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsarithmeticmaximum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsarithmeticmaximum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
