{
  "abstract": [
    {
      "text": "Constants that specify the mask for compile-time messages.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSGraphMessageLevel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSGraphMessageLevel"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSGraphMessageLevel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSGraphMessageLevel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies a customized callback function that reports compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
          "text": "bnns_graph_compile_message_fn_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
          "text": "bnns_user_message_data_t"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogcallback(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets mask for log messages that are logged (either via ",
          "type": "text"
        },
        {
          "code": "os_log",
          "type": "codeVoice"
        },
        {
          "text": " or the user specified callback)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_context_t",
          "text": "bnns_graph_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphContextSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcontextsetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel": {
      "abstract": [
        {
          "text": "Constants that specify the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevel",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/rawValue": {
      "abstract": [
        {
          "text": "The corresponding value of the raw type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelError": {
      "abstract": [
        {
          "text": "A constant that specifies error message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphMessageLevel",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelError"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevelError",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevelerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo": {
      "abstract": [
        {
          "text": "A constant that specifies information message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphMessageLevel",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevelInfo",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevelinfo"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelUnsupported": {
      "abstract": [
        {
          "text": "A constant that specifies unsupported function message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelUnsupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphMessageLevel",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelUnsupported"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevelUnsupported",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevelunsupported"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelWarning": {
      "abstract": [
        {
          "text": "A constant that specifies warning message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelWarning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphMessageLevel",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelWarning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelWarning"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevelWarning",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevelwarning"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t": {
      "abstract": [
        {
          "text": "The graph compile-message logging callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_compile_message_fn_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_message_fn_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t": {
      "abstract": [
        {
          "text": "Additional user-defined logging argument for message-logging callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_user_message_data_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-graphs-compile-time-message-callback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t"
      ],
      "title": "Specifying a graph’s compile-time message callback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Graph-message-levels",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/init(rawValue:)"
      ],
      "title": "Graph message levels"
    },
    {
      "anchor": "Instance-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelWarning",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelError",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelUnsupported"
      ],
      "title": "Instance properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSGraphMessageLevel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelWarning",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelError",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelUnsupported"
              ],
              "title": "Instance properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-graphs-compile-time-message-callback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t"
              ],
              "title": "Specifying a graph’s compile-time message callback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSGraphMessageLevel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphContextSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelWarning/title",
          "value": "BNNSGraphMessageLevelWarning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelWarning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevelWarning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/title",
          "value": "bnns_user_message_data_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelError/title",
          "value": "BNNSGraphMessageLevelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/title",
          "value": "bnns_graph_compile_message_fn_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelInfo/title",
          "value": "BNNSGraphMessageLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/title",
          "value": "BNNSGraphMessageLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelUnsupported/title",
          "value": "BNNSGraphMessageLevelUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevelUnsupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsgraphmessagelevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsgraphmessagelevel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
