{
  "abstract": [
    {
      "text": "Constants that describe relational operations.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSRelationalOperator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperator"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSRelationalOperator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/compare(_:_:using:output:)": {
      "abstract": [
        {
          "text": "Performs an elementwise comparison of two array descriptors using the specified relational operator.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO18RelationalOperatorV",
          "text": "RelationalOperator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/compare(_:_:using:output:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "compare(_:_:using:output:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/compare(_:_:using:output:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSCompareTensor(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a tensor of Boolean type by comparing or performing a logical operation between two inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSCompareTensor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSCompareTensor(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSCompareTensor"
        }
      ],
      "role": "symbol",
      "title": "BNNSCompareTensor(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnscomparetensor(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator": {
      "abstract": [
        {
          "text": "Constants that describe relational operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater": {
      "abstract": [
        {
          "text": "The operator that indicates the greater-than relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreater"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorGreater",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorgreater"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the greater-than or equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreaterEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreaterEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorGreaterEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorgreaterequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess": {
      "abstract": [
        {
          "text": "The operator that indicates the less-than relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLess"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLess",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorless"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the less-than or equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLessEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLessEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLessEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlessequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND": {
      "abstract": [
        {
          "text": "The operator that indicates the logical AND relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalAND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalAND"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalAND",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicaland"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NAND relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNAND"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNAND"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNAND",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnand"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NOR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT": {
      "abstract": [
        {
          "text": "The operator that indicates the logical NOT relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalNOT"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalNOT",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalnot"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical OR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR": {
      "abstract": [
        {
          "text": "The operator that indicates the logical XOR relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalXOR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLogicalXOR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLogicalXOR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlogicalxor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the not-equal relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorNotEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorNotEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorNotEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatornotequal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tensor-comparison-layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/compare(_:_:using:output:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSCompareTensor(_:_:_:_:)"
      ],
      "title": "Tensor comparison layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Relational-Operators",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual"
      ],
      "title": "Relational Operators"
    },
    {
      "anchor": "Logical-Operators",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR"
      ],
      "title": "Logical Operators"
    },
    {
      "anchor": "Raw-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator/rawValue"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSRelationalOperator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Relational-Operators",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual"
              ],
              "title": "Relational Operators"
            },
            {
              "anchor": "Logical-Operators",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalAND",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNAND",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOR",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalNOT",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalOR",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLogicalXOR"
              ],
              "title": "Logical Operators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tensor-comparison-layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSCompareTensor(_:_:_:_:)"
              ],
              "title": "Tensor comparison layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSRelationalOperator"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLessEqual/title",
          "value": "BNNSRelationalOperatorLessEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLessEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLessEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalAND/title",
          "value": "BNNSRelationalOperatorLogicalAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalOR/title",
          "value": "BNNSRelationalOperatorLogicalOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreater/title",
          "value": "BNNSRelationalOperatorGreater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorGreater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCompareTensor(_:_:_:_:)/title",
          "value": "BNNSCompareTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCompareTensor(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSCompareTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOR/title",
          "value": "BNNSRelationalOperatorLogicalNOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLess/title",
          "value": "BNNSRelationalOperatorLess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/title",
          "value": "BNNSRelationalOperator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreaterEqual/title",
          "value": "BNNSRelationalOperatorGreaterEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreaterEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorGreaterEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNAND/title",
          "value": "BNNSRelationalOperatorLogicalNAND"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNAND/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNAND"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorEqual/title",
          "value": "BNNSRelationalOperatorEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOT/title",
          "value": "BNNSRelationalOperatorLogicalNOT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalNOT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalNOT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorNotEqual/title",
          "value": "BNNSRelationalOperatorNotEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorNotEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorNotEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalXOR/title",
          "value": "BNNSRelationalOperatorLogicalXOR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLogicalXOR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLogicalXOR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
