{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP","identifier":"doc://com.externally.resolved.symbol/s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara","identifier":"doc://com.externally.resolved.symbol/s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shapes_count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shapes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","identifier":"doc://com.externally.resolved.symbol/s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"bnns_graph_shape_t","preciseIdentifier":"c:@SA@bnns_graph_shape_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The graph context."}]}]},{"name":"function","content":[{"type":"paragraph","inlineContent":[{"text":"The function. Specify as ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the graph only contains one function.","type":"text"}]}]},{"name":"shapes_count","content":[{"type":"paragraph","inlineContent":[{"text":"The number of elements in the ","type":"text"},{"code":"shapes","type":"codeVoice"},{"text":" array.","type":"text"}]}]},{"name":"shapes","content":[{"inlineContent":[{"text":"An array of input and output shapes in the same order as you pass to ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextExecute(_:_:_:_:_:_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"On input, this function reads input shapes with a nonzero rank, and uses the constant or default value from the source model for input shapes with a zero rank. The function generates an error for shapes with a nonzero value that doesn’t match the source model."}],"type":"paragraph"},{"inlineContent":[{"text":"On output, the function sets output shapes with a nonzero rank to the upper bounds of the expected output shape. If the function can’t deduce the output shape because it depends on the input data values, the value of ","type":"text"},{"code":"shapes[idx].size[d]","type":"codeVoice"},{"text":" is zero.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"- ","type":"text"},{"code":"0","type":"codeVoice"},{"text":" on success if all tensor shapes were exactly determined. That is, the workspace size is exact.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"1"},{"type":"text","text":" on success if one or more tensor shapes are merely bounds, but no tensor is unbounded. That is, the workspace size is bounded."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"2"},{"type":"text","text":" on success if one or more tensor shapes are unbounded and BNNS will allocate workspace memory during execution."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A negative value indicates an error."}],"type":"paragraph"}]}]},{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"Don’t call this function while existing calls to ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextExecute(_:_:_:_:_:_:)","type":"reference","isActive":true},{"text":" are running.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For example, the following code sets the dynamic shapes for an example graph context, specifies the output shape, and updates the context’s required workspace size."}],"type":"paragraph"},{"type":"codeListing","code":["var inputShape: [UInt64] = [1024, 1, 1]","let rank = inputShape.count","var outputShape = [UInt64](repeating: 0, count: rank)","","let result = outputShape.withUnsafeMutableBufferPointer { output in","    inputShape.withUnsafeMutableBufferPointer { input in","        ","        var shapes = [","            bnns_graph_shape_t(rank: rank, shape: output.baseAddress!),","            bnns_graph_shape_t(rank:rank, shape: input.baseAddress!)","        ]","        ","        return BNNSGraphContextSetDynamicShapes(context, nil,","                                                shapes.count, &shapes)","    }","}","    ","// Prints \"[1024, 1, 1]\".","print(outputShape)"],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"On return, the output shape contains the correct size for the input shape, and a subsequent call to "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)","isActive":true},{"type":"text","text":" returns the correct workspace size."}],"type":"paragraph"}]}],"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Specifying and querying a context’s properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)"],"anchor":"Specifying-and-querying-a-contexts-properties"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Specifies the dynamic shapes for a graph and, if possible, infers, the output shapes.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"Accelerate"}],"roleHeading":"Function","externalID":"c:@F@BNNSGraphContextSetDynamicShapes","navigatorTitle":[{"text":"BNNSGraphContextSetDynamicShapes","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextSetDynamicShapes","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_context_t","text":"bnns_graph_context_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_shape_t","text":"bnns_graph_shape_t","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"15.0","beta":false,"unavailable":false,"name":"macOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"tvOS"},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"2.0","deprecated":false},{"beta":false,"unavailable":false,"name":"watchOS","introducedAt":"11.0","deprecated":false}],"title":"BNNSGraphContextSetDynamicShapes(_:_:_:_:)","role":"symbol","symbolKind":"func"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsgraphcontextsetdynamicshapes(_:_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsgraphcontextsetdynamicshapes(_:_:_:_:)"]}],"references":{"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t":{"url":"/documentation/accelerate/bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","kind":"symbol","type":"topic","abstract":[{"text":"An object that wraps a compiled graph object.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_context_t"}],"role":"symbol","title":"bnns_graph_context_t","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_context_t"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","url":"/documentation/accelerate/bnnsgraphcontextsetbatchsize(_:_:_:)","kind":"symbol","navigatorTitle":[{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Sets the batch size for a graph.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphContextSetBatchSize(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_shape_t"}],"title":"bnns_graph_shape_t","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"abstract":[{"text":"The specification of the shape of an argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_shape_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextsetdynamicshapes(_:_:_:_:)","abstract":[{"text":"Specifies the dynamic shapes for a graph and, if possible, infers, the output shapes.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"BNNSGraphContextSetDynamicShapes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_shape_t","text":"bnns_graph_shape_t","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"}],"title":"BNNSGraphContextSetDynamicShapes(_:_:_:_:)","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetDynamicShapes(_:_:_:_:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"BNNSGraphContextEnableNanAndInfChecks(_:_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextEnableNanAndInfChecks"}],"abstract":[{"text":"Specifies that the context checks intermediate tensors for NaNs and infinities.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphcontextenablenanandinfchecks(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextsetstreamingadvancecount(_:_:)","abstract":[{"text":"Sets the streaming advancement amount for cases with dynamically shaped inputs.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextSetStreamingAdvanceCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetStreamingAdvanceCount"}],"title":"BNNSGraphContextSetStreamingAdvanceCount(_:_:)","beta":true,"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Int8","preciseIdentifier":"s:s4Int8V"}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"symbol","url":"/documentation/Swift/CChar","role":"symbol","abstract":[{"text":"The C ‘char’ type.","type":"text"}],"title":"CChar","type":"topic"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcontextgetworkspacesize(_:_:)","abstract":[{"text":"Returns the minimum size, in bytes, of the workspace that graph context execution requires.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextGetWorkspaceSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":", "},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"BNNSGraphContextGetWorkspaceSize","kind":"identifier"}],"title":"BNNSGraphContextGetWorkspaceSize(_:_:)","type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)":{"title":"BNNSGraphContextSetArgumentType(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextSetArgumentType"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextSetArgumentType"},{"text":"(","kind":"text"},{"text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentType","preciseIdentifier":"c:@EA@BNNSGraphArgumentType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"text":"Specifies the argument type for a graph context.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","url":"/documentation/accelerate/bnnsgraphcontextsetargumenttype(_:_:)"},"doc://com.externally.resolved.symbol/s:Sp":{"url":"/documentation/Swift/UnsafeMutablePointer","kind":"symbol","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:Sp","title":"UnsafeMutablePointer","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentType","kind":"identifier"}],"title":"BNNSGraphArgumentType","kind":"symbol","navigatorTitle":[{"text":"BNNSGraphArgumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that specify the argument type for a graph context."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphargumenttype"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextExecute(_:_:_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextExecute"}],"abstract":[{"type":"text","text":"Executes the specified function with the given context."}],"title":"BNNSGraphContextExecute(_:_:_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextExecute(_:_:_:_:_:_:)","url":"/documentation/accelerate/bnnsgraphcontextexecute(_:_:_:_:_:_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextExecute"},{"text":"(","kind":"text"},{"text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"bnns_graph_argument_t","preciseIdentifier":"c:@SA@bnns_graph_argument_t"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?) -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"url":"/documentation/Swift/Int32","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"kind":"symbol","type":"topic","title":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","introducedAt":"18.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"18.0","deprecated":false,"beta":false},{"deprecated":false,"introducedAt":"18.0","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"15.0","name":"macOS","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","introducedAt":"18.0","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","introducedAt":"2.0","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphContextSetDynamicShapes","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetStreamingAdvanceCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetArgumentType(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentType","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetBatchSize(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextEnableNanAndInfChecks(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetWorkspaceSize(_:_:)"],"title":"Specifying and querying a context’s properties","anchor":"Specifying-and-querying-a-contexts-properties","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"char","preciseIdentifier":"c:C"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"function"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","preciseIdentifier":"c:@T@size_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shapes_count"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"bnns_graph_shape_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_shape_t","preciseIdentifier":"c:@SA@bnns_graph_shape_t"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"shapes"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"context","content":[{"inlineContent":[{"text":"The graph context.","type":"text"}],"type":"paragraph"}]},{"name":"function","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The function. Specify as "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the graph only contains one function."}]}]},{"name":"shapes_count","content":[{"inlineContent":[{"type":"text","text":"The number of elements in the "},{"type":"codeVoice","code":"shapes"},{"type":"text","text":" array."}],"type":"paragraph"}]},{"name":"shapes","content":[{"inlineContent":[{"text":"An array of input and output shapes in the same order as you pass to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextExecute(_:_:_:_:_:_:)","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"On input, this function reads input shapes with a nonzero rank, and uses the constant or default value from the source model for input shapes with a zero rank. The function generates an error for shapes with a nonzero value that doesn’t match the source model.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"On output, the function sets output shapes with a nonzero rank to the upper bounds of the expected output shape. If the function can’t deduce the output shape because it depends on the input data values, the value of "},{"type":"codeVoice","code":"shapes[idx].size[d]"},{"type":"text","text":" is zero."}],"type":"paragraph"}]}]},"op":"replace"},{"value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"- "},{"type":"codeVoice","code":"0"},{"type":"text","text":" on success if all tensor shapes were exactly determined. That is, the workspace size is exact."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/title","value":"bnns_graph_context_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/fragments","value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/navigatorTitle","value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetBatchSize(_:_:_:)/title","value":"BNNSGraphContextSetBatchSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetBatchSize(_:_:_:)/fragments","value":[{"text":"BNNSGraphContextSetBatchSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/title","value":"bnns_graph_shape_t","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/fragments","value":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_shape_t/navigatorTitle","value":[{"kind":"identifier","text":"bnns_graph_shape_t"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetDynamicShapes(_:_:_:_:)/title","value":"BNNSGraphContextSetDynamicShapes","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetDynamicShapes(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphContextSetDynamicShapes"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextEnableNanAndInfChecks(_:_:)/title","value":"BNNSGraphContextEnableNanAndInfChecks","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextEnableNanAndInfChecks(_:_:)/fragments","value":[{"text":"BNNSGraphContextEnableNanAndInfChecks","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetStreamingAdvanceCount(_:_:)/title","value":"BNNSGraphContextSetStreamingAdvanceCount","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetStreamingAdvanceCount(_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphContextSetStreamingAdvanceCount"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetWorkspaceSize(_:_:)/title","value":"BNNSGraphContextGetWorkspaceSize","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetWorkspaceSize(_:_:)/fragments","value":[{"text":"BNNSGraphContextGetWorkspaceSize","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetArgumentType(_:_:)/title","value":"BNNSGraphContextSetArgumentType","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetArgumentType(_:_:)/fragments","value":[{"text":"BNNSGraphContextSetArgumentType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/title","value":"BNNSGraphArgumentType","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/fragments","value":[{"text":"BNNSGraphArgumentType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentType/navigatorTitle","value":[{"kind":"identifier","text":"BNNSGraphArgumentType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextExecute(_:_:_:_:_:_:)/title","value":"BNNSGraphContextExecute","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextExecute(_:_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphContextExecute"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}