{
  "abstract": [
    {
      "text": "Returns a new loss layer.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use BNNSGraph* APIs",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerPadding(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@BNNSFilterCreateLayerPadding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSFilterCreateLayerPadding"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSLayerParametersPadding",
        "text": "BNNSLayerParametersPadding"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@BNNSFilterParameters",
        "text": "BNNSFilterParameters"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BNNSFilter",
        "text": "BNNSFilter"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSFilterCreateLayerPadding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "Use BNNSGraph* APIs",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "14.0",
        "message": "Use BNNSGraph* APIs",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use BNNSGraph* APIs",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "7.0",
        "message": "Use BNNSGraph* APIs",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "BNNSFilterCreateLayerPadding(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateLayerPadding"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "layer_params"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSLayerParametersPadding",
              "text": "BNNSLayerParametersPadding"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "filter_params"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@BNNSFilterParameters",
              "text": "BNNSFilterParameters"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BNNSFilter",
              "text": "BNNSFilter"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Layer parameters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layer_params"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The filter runtime parameters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "filter_params"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a padding layer to add elements to an n-dimensional array before and after existing data. The padding can either contain a single value or a reflection of the existing data. For ",
              "type": "text"
            },
            {
              "code": "BNNSPaddingModeConstant",
              "type": "codeVoice"
            },
            {
              "text": ", pass the bit pattern of the padding value, for example, using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/Float/bitPattern",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to pass a single-precision value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to add two elements before, and four elements after a vector of ten values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let paddingSize = (2, 4)",
            "",
            "let source: [Float] = [ 0, 1, 2, 3, 4, 5, 7, 8, 9 ]",
            "",
            "var destination = [Float](repeating: 0,",
            "                          count: source.count + paddingSize.0 + paddingSize.1)",
            "",
            "let srcDescription = BNNSNDArrayDescriptor(flags: BNNSNDArrayFlags(0),",
            "                                           layout: BNNSDataLayoutVector,",
            "                                           size: (source.count, 0, 0, 0, 0, 0, 0, 0),",
            "                                           stride: (0, 0, 0, 0, 0, 0, 0, 0),",
            "                                           data: nil,",
            "                                           data_type: .float,",
            "                                           table_data: nil,",
            "                                           table_data_type: .float,",
            "                                           data_scale: 1,",
            "                                           data_bias: 0)",
            "",
            "let destDescription = BNNSNDArrayDescriptor(flags: BNNSNDArrayFlags(0),",
            "                                            layout: BNNSDataLayoutVector,",
            "                                            size: (destination.count, 0, 0, 0, 0, 0, 0, 0),",
            "                                            stride: (0, 0, 0, 0, 0, 0, 0, 0),",
            "                                            data: nil,",
            "                                            data_type: .float,",
            "                                            table_data: nil,",
            "                                            table_data_type: .float,",
            "                                            data_scale: 1,",
            "                                            data_bias: 0)",
            "",
            "let paddingValue: Float = 99",
            "",
            "var parameters = BNNSLayerParametersPadding(i_desc: srcDescription,",
            "                                            o_desc: destDescription,",
            "                                            padding_size: (paddingSize, (0, 0), (0, 0), (0, 0),",
            "                                                           (0, 0), (0, 0), (0, 0), (0, 0)),",
            "                                            padding_mode: BNNSPaddingModeConstant,",
            "                                            padding_value: paddingValue.bitPattern)",
            "",
            "var filterParams = BNNSFilterParameters()",
            "",
            "let filter = BNNSFilterCreateLayerPadding(&parameters, &filterParams)",
            "defer {",
            "    BNNSFilterDestroy(filter)",
            "}",
            "",
            "BNNSFilterApply(filter,",
            "                source,",
            "                &destination)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, ",
              "type": "text"
            },
            {
              "code": "destination",
              "type": "codeVoice"
            },
            {
              "text": " contains ",
              "type": "text"
            },
            {
              "code": "[99.0, 99.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 8.0, 9.0, 99.0, 99.0, 99.0, 99.0]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/PaddingLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a padding filter and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PaddingLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/PaddingLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PaddingLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.PaddingLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/paddinglayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter": {
      "abstract": [
        {
          "text": "An opaque type that represents a filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilter"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilter"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilter",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilter"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerPadding(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new loss layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateLayerPadding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSLayerParametersPadding",
          "text": "BNNSLayerParametersPadding"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerPadding(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateLayerPadding"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterCreateLayerPadding(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltercreatelayerpadding(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters": {
      "abstract": [
        {
          "text": "A structure that contains common filter parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding": {
      "abstract": [
        {
          "text": "A structure that contains the parameters of a padding layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSLayerParametersPadding"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSLayerParametersPadding"
        }
      ],
      "role": "symbol",
      "title": "BNNSLayerParametersPadding",
      "type": "topic",
      "url": "/documentation/accelerate/bnnslayerparameterspadding"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPaddingMode": {
      "abstract": [
        {
          "text": "Constants that define padding modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPaddingMode"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPaddingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPaddingMode"
        }
      ],
      "role": "symbol",
      "title": "BNNSPaddingMode",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspaddingmode"
    },
    "doc://com.apple.documentation/documentation/Swift/Float/bitPattern": {
      "abstract": [
        {
          "text": "The bit pattern of the value’s encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitPattern"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Float/bitPattern",
      "kind": "symbol",
      "role": "symbol",
      "title": "bitPattern",
      "type": "topic",
      "url": "/documentation/Swift/Float/bitPattern"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Padding-layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/PaddingLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPaddingMode",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding"
      ],
      "title": "Padding layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSFilterCreateLayerPadding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateLayerPadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Padding-layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPaddingMode",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding"
              ],
              "title": "Padding layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BNNSFilter",
                    "text": "BNNSFilter"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSFilterCreateLayerPadding"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersPadding",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@BNNSLayerParametersPadding",
                    "text": "BNNSLayerParametersPadding"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "layer_params"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@BNNSFilterParameters",
                    "text": "BNNSFilterParameters"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "filter_params"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Layer parameters.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "layer_params"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The filter runtime parameters.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "filter_params"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use BNNSGraph* APIs",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateLayerPadding(_:_:)/title",
          "value": "BNNSFilterCreateLayerPadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateLayerPadding(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateLayerPadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPaddingMode/title",
          "value": "BNNSPaddingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPaddingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPaddingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPaddingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPaddingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/title",
          "value": "BNNSFilterParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersPadding/title",
          "value": "BNNSLayerParametersPadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersPadding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerParametersPadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersPadding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerParametersPadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/title",
          "value": "BNNSFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsfiltercreatelayerpadding(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsfiltercreatelayerpadding(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
