{"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","interfaceLanguage":"swift"},"metadata":{"title":"bnns_graph_context_t","modules":[{"name":"Accelerate"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bnns_graph_context_t","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"bnns_graph_context_t","kind":"identifier"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"18.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"18.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"15.0","name":"macOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"18.0","name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"2.0","name":"visionOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"11.0","name":"watchOS"}],"roleHeading":"Structure","externalID":"c:@SA@bnns_graph_context_t","symbolKind":"struct"},"seeAlsoSections":[{"anchor":"Creating-and-destroying-a-context","title":"Creating and destroying a context","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMake(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMakeStreaming(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)"],"generated":true}],"abstract":[{"text":"An object that wraps a compiled graph object.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnns_graph_context_t"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnns_graph_context_t"]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"anchor":"Initializing-a-context","title":"Initializing a context","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init()","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init(data:size:)"]},{"anchor":"Specifying-a-contexts-properties","title":"Specifying a context’s properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_context_t"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","type":"reference"},{"text":" object wraps a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","type":"reference"},{"text":" instance and adds mutable data storage. BNNS requires mutability to support dynamic shapes and other execution objects.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You must ensure that the underlying "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t"},{"type":"text","text":" instance remains valid throughout the lifetime of the context."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"kind":"symbol","abstract":[{"text":"","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init(data:size:)":{"url":"/documentation/accelerate/bnns_graph_context_t/init(data:size:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init(data:size:)","role":"symbol","abstract":[{"type":"text","text":"Creates a graph context structure from the specified opaque graph context object."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(data:size:)","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data","role":"symbol","title":"data","url":"/documentation/accelerate/bnns_graph_context_t/data","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"data"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A pointer to the opaque graph context object."}]},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t":{"url":"/documentation/accelerate/bnns_graph_context_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t","kind":"symbol","type":"topic","abstract":[{"text":"An object that wraps a compiled graph object.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_context_t"}],"role":"symbol","title":"bnns_graph_context_t","navigatorTitle":[{"kind":"identifier","text":"bnns_graph_context_t"}]},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init()":{"url":"/documentation/accelerate/bnns_graph_context_t/init()","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/init()","role":"symbol","abstract":[{"text":"Creates an empty graph context structure.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)":{"url":"/documentation/accelerate/bnnsgraphcontextdestroy(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextDestroy"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextDestroy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Destroys the specified graph context."}],"title":"BNNSGraphContextDestroy(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t":{"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_t"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_t"}],"title":"bnns_graph_t","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","abstract":[{"text":"The compiled graph object.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMake(_:)":{"kind":"symbol","url":"/documentation/accelerate/bnnsgraphcontextmake(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphContextMake"}],"abstract":[{"text":"Returns an allocated and initialized graph context from the specified graph.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMake(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextMake"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"bnns_graph_context_t","preciseIdentifier":"c:@SA@bnns_graph_context_t"}],"title":"BNNSGraphContextMake(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"size"}],"title":"size","type":"topic","abstract":[{"type":"text","text":"The size, in bytes, of the opaque graph context object."}],"url":"/documentation/accelerate/bnns_graph_context_t/size","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size","role":"symbol","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMakeStreaming(_:_:_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMakeStreaming(_:_:_:_:)","role":"symbol","title":"BNNSGraphContextMakeStreaming(_:_:_:_:)","url":"/documentation/accelerate/bnnsgraphcontextmakestreaming(_:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"BNNSGraphContextMakeStreaming","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphContextMakeStreaming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"BNNSTensor","kind":"typeIdentifier","preciseIdentifier":"c:@SA@BNNSTensor"},{"text":">?) -> ","kind":"text"},{"text":"bnns_graph_context_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_context_t"}],"abstract":[{"type":"text","text":"Returns an allocated and initialized graph context with streaming support from the specified graph."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false},{"deprecated":false,"unavailable":false,"name":"watchOS","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Structure"},{"path":"/metadata/title","op":"replace","value":"bnns_graph_context_t"},{"path":"/metadata/symbolKind","op":"replace","value":"struct"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"bnns_graph_context_t","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"bnns_graph_context_t"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/data","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_context_t/size"],"anchor":"Specifying-a-contexts-properties","title":"Specifying a context’s properties"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMake(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextMakeStreaming(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextDestroy(_:)"],"title":"Creating and destroying a context","anchor":"Creating-and-destroying-a-context"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"bnns_graph_context_t","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}]}},{"value":"data","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1data/title"},{"value":[{"kind":"identifier","text":"data"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1data/fragments"},{"value":"bnns_graph_context_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/title"},{"value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/fragments"},{"value":[{"text":"bnns_graph_context_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t/navigatorTitle"},{"value":"BNNSGraphContextDestroy","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextDestroy(_:)/title"},{"value":[{"text":"BNNSGraphContextDestroy","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextDestroy(_:)/fragments"},{"value":"bnns_graph_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/title"},{"value":[{"text":"bnns_graph_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/fragments"},{"value":[{"text":"bnns_graph_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/navigatorTitle"},{"value":"BNNSGraphContextMake","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextMake(_:)/title"},{"value":[{"text":"BNNSGraphContextMake","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextMake(_:)/fragments"},{"value":"size","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1size/title"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_context_t~1size/fragments"},{"value":"BNNSGraphContextMakeStreaming","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextMakeStreaming(_:_:_:_:)/title"},{"value":[{"kind":"identifier","text":"BNNSGraphContextMakeStreaming"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextMakeStreaming(_:_:_:_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}