{
  "abstract": [
    {
      "text": "Constants that describe clipping functions.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSOptimizerClippingFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSOptimizerClippingFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSOptimizerClippingFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSOptimizerClippingFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1": {
      "abstract": [
        {
          "text": "A value that specifies the first moment constant in the range 0 to 1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta1"
        }
      ],
      "role": "symbol",
      "title": "beta1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2": {
      "abstract": [
        {
          "text": "A value that specifies the second moment constant in the range 0 to 1.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beta2"
        }
      ],
      "role": "symbol",
      "title": "beta2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/beta2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max": {
      "abstract": [
        {
          "text": "The maximum clipping value for clipping by value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_max"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_max",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_max"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm": {
      "abstract": [
        {
          "text": "The maximum Euclidean norm for clipping by norm and clipping by global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_max_norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_max_norm"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_max_norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_max_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min": {
      "abstract": [
        {
          "text": "The minimum clipping value for clipping by value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_min"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_min",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_min"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm": {
      "abstract": [
        {
          "text": "An optional value for a known Euclidean norm for clipping by global norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clip_gradients_use_norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clip_gradients_use_norm"
        }
      ],
      "role": "symbol",
      "title": "clip_gradients_use_norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clip_gradients_use_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func": {
      "abstract": [
        {
          "text": "The clipping function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipping_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipping_func"
        }
      ],
      "role": "symbol",
      "title": "clipping_func",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/clipping_func"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon": {
      "abstract": [
        {
          "text": "An addition for the division in the parameter update stage.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "epsilon"
        }
      ],
      "role": "symbol",
      "title": "epsilon",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/epsilon"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale": {
      "abstract": [
        {
          "text": "A value that specifies the gradient scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradient_scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradient_scale"
        }
      ],
      "role": "symbol",
      "title": "gradient_scale",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/gradient_scale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate": {
      "abstract": [
        {
          "text": "A value that specifies the learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learning_rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "learning_rate"
        }
      ],
      "role": "symbol",
      "title": "learning_rate",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/learning_rate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func": {
      "abstract": [
        {
          "text": "The variable that specifies the regularization function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularization_func"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerRegularizationFunction",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularization_func"
        }
      ],
      "role": "symbol",
      "title": "regularization_func",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/regularization_func"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale": {
      "abstract": [
        {
          "text": "A value that specifies the regularization scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularization_scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "regularization_scale"
        }
      ],
      "role": "symbol",
      "title": "regularization_scale",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/regularization_scale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step": {
      "abstract": [
        {
          "text": "A value that’s at least 1 and represents the optimizer’s current time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time_step"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "time_step"
        }
      ],
      "role": "symbol",
      "title": "time_step",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields/time_step"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByGlobalNorm": {
      "abstract": [
        {
          "text": "A constant that specifes clipping to a maximum global Euclidean norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByGlobalNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByGlobalNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByGlobalNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingByGlobalNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingbyglobalnorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByNorm": {
      "abstract": [
        {
          "text": "A constant that specifes clipping to a maximum Euclidean norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingByNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingbynorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByValue": {
      "abstract": [
        {
          "text": "A constant that specifes clipping to minimum and maximum values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingByValue"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingByValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingbyvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction": {
      "abstract": [
        {
          "text": "Constants that describe clipping functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingfunction/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingfunction/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/rawValue": {
      "abstract": [
        {
          "text": "The corresponding value of the raw type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingfunction/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingNone": {
      "abstract": [
        {
          "text": "A constant that specifes no clipping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerClippingFunction",
          "text": "BNNSOptimizerClippingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerClippingNone"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerClippingNone",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerclippingnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm"
      ],
      "title": "Instance Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Clipping-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingFunction/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingNone",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByGlobalNorm"
      ],
      "title": "Clipping Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSOptimizerClippingFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Clipping-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingNone",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByValue",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerClippingByGlobalNorm"
              ],
              "title": "Clipping Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/learning_rate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/beta2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/time_step",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/epsilon",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/gradient_scale",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_scale",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/regularization_func",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clipping_func",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_min",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_max_norm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields/clip_gradients_use_norm"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSOptimizerClippingFunction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByValue/title",
          "value": "BNNSOptimizerClippingByValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingByValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByGlobalNorm/title",
          "value": "BNNSOptimizerClippingByGlobalNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByGlobalNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingByGlobalNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1epsilon/title",
          "value": "epsilon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1epsilon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "epsilon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta2/title",
          "value": "beta2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_scale/title",
          "value": "regularization_scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularization_scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta1/title",
          "value": "beta1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1beta1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beta1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max_norm/title",
          "value": "clip_gradients_max_norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max_norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_max_norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clipping_func/title",
          "value": "clipping_func"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clipping_func/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipping_func"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingNone/title",
          "value": "BNNSOptimizerClippingNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByNorm/title",
          "value": "BNNSOptimizerClippingByNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingByNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingByNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_func/title",
          "value": "regularization_func"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1regularization_func/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "regularization_func"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_min/title",
          "value": "clip_gradients_min"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_min"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max/title",
          "value": "clip_gradients_max"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_max"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_use_norm/title",
          "value": "clip_gradients_use_norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1clip_gradients_use_norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clip_gradients_use_norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1gradient_scale/title",
          "value": "gradient_scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1gradient_scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradient_scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1learning_rate/title",
          "value": "learning_rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1learning_rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "learning_rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1time_step/title",
          "value": "time_step"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields~1time_step/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "time_step"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/title",
          "value": "BNNSOptimizerClippingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerClippingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerClippingFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizerclippingfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizerclippingfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
