{
  "abstract": [
    {
      "text": "Describes data associated with an input or output argument",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@bnns_graph_argument_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bnns_graph_argument_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bnns_graph_argument_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "bnns_graph_argument_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Exactly one of descriptor or data_ptr should be set based on the configuration specified with ",
              "type": "text"
            },
            {
              "code": "BNNSGraphContextSetArgumentType()",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType": {
      "abstract": [
        {
          "text": "BNNS Data Types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSImageStackDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSImageStackDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSImageStackDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsimagestackdescriptor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSSparsityParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSSparsityParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSSparsityParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnssparsityparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSSparsityType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSSparsityType"
        }
      ],
      "role": "symbol",
      "title": "BNNSSparsityType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnssparsitytype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSTargetSystem"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSTargetSystem"
        }
      ],
      "role": "symbol",
      "title": "BNNSTargetSystem",
      "type": "topic",
      "url": "/documentation/accelerate/bnnstargetsystem"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSVectorDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSVectorDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSVectorDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsvectordescriptor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t": {
      "abstract": [
        {
          "text": "Describes data associated with an input or output argument",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_argument_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_argument_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_argument_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-10vgq": {
      "abstract": [
        {
          "text": "Direct pointer to numerical data",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "data_ptr"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-10vgq",
      "kind": "symbol",
      "role": "symbol",
      "title": "data_ptr",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/data_ptr-10vgq"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-89cqn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data_ptr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-89cqn",
      "kind": "symbol",
      "role": "symbol",
      "title": "data_ptr",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/data_ptr-89cqn"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr_size": {
      "abstract": [
        {
          "text": "size in bytes of ",
          "type": "text"
        },
        {
          "code": "data_ptr",
          "type": "codeVoice"
        },
        {
          "text": ", if set",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data_ptr_size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr_size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data_ptr_size"
        }
      ],
      "role": "symbol",
      "title": "data_ptr_size",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/data_ptr_size"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-8d2bd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-8d2bd",
      "kind": "symbol",
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/descriptor-8d2bd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-jg2s": {
      "abstract": [
        {
          "text": "Pointer to BNNSNDArrayDescriptor (deprecated, use BNNSTensor instead)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "descriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-jg2s",
      "kind": "symbol",
      "role": "symbol",
      "title": "descriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/descriptor-jg2s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6224h": {
      "abstract": [
        {
          "text": "Pointer to BNNSTensor",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "tensor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6224h",
      "kind": "symbol",
      "role": "symbol",
      "title": "tensor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/tensor-6224h"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6l2lt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSTensor",
          "text": "BNNSTensor"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6l2lt",
      "kind": "symbol",
      "role": "symbol",
      "title": "tensor",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t/tensor-6l2lt"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-89cqn",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr_size",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-8d2bd",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6l2lt"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bnns_graph_argument_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr-10vgq",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/data_ptr_size",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/descriptor-jg2s",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t/tensor-6224h"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "bnns_graph_argument_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t~1data_ptr_size/title",
          "value": "data_ptr_size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t~1data_ptr_size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data_ptr_size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/title",
          "value": "bnns_graph_argument_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/title",
          "value": "BNNSSparsityParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title",
          "value": "BNNSDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/title",
          "value": "BNNSImageStackDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSImageStackDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSImageStackDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/title",
          "value": "BNNSSparsityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/title",
          "value": "BNNSVectorDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSVectorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSVectorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/title",
          "value": "BNNSTargetSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTargetSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTargetSystem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns_graph_argument_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnns_graph_argument_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
