{
  "abstract": [
    {
      "text": "A structure that contains common filter parameters.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@BNNSFilterParameters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSFilterParameters"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSFilterParameters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSFilterParameters"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryLayer": {
      "abstract": [
        {
          "text": "The base class for layers that accept two inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BinaryLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BinaryLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.BinaryLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/binarylayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Layer": {
      "abstract": [
        {
          "text": "The base class for layer objects that wrap filters and manage deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Layer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Layer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Layer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.Layer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/layer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/UnaryLayer": {
      "abstract": [
        {
          "text": "The base class for layers that accept a single input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnaryLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/UnaryLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UnaryLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.UnaryLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/unarylayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSAlloc": {
      "abstract": [
        {
          "text": "A type-alias for a user-provided memory allocation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSAlloc"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSAlloc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSAlloc"
        }
      ],
      "role": "symbol",
      "title": "BNNSAlloc",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsalloc"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter": {
      "abstract": [
        {
          "text": "An opaque type that represents a filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilter"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilter"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilter",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilter"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterDestroy(_:)": {
      "abstract": [
        {
          "text": "Destroys the specified filter, releasing all resources allocated for it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterDestroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterDestroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterDestroy"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterDestroy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterdestroy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters": {
      "abstract": [
        {
          "text": "A structure that contains common filter parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/alloc_memory": {
      "abstract": [
        {
          "text": "The function called to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alloc_memory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSAlloc",
          "text": "BNNSAlloc"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/alloc_memory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alloc_memory"
        }
      ],
      "role": "symbol",
      "title": "alloc_memory",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/alloc_memory"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/allocator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSAlloc",
          "text": "BNNSAlloc"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/allocator",
      "kind": "symbol",
      "role": "symbol",
      "title": "allocator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/allocator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/deallocator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFree",
          "text": "BNNSFree"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/deallocator",
      "kind": "symbol",
      "role": "symbol",
      "title": "deallocator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/deallocator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/flags": {
      "abstract": [
        {
          "text": "A logical OR of zero or more values from BNNS flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/free_memory": {
      "abstract": [
        {
          "text": "The function called to deallocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free_memory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFree",
          "text": "BNNSFree"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/free_memory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "free_memory"
        }
      ],
      "role": "symbol",
      "title": "free_memory",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/free_memory"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(flags:n_threads:alloc_memory:free_memory:)": {
      "abstract": [
        {
          "text": "Returns a new common filter parameters structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "n_threads"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alloc_memory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSAlloc",
          "text": "BNNSAlloc"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "free_memory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFree",
          "text": "BNNSFree"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(flags:n_threads:alloc_memory:free_memory:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(flags:n_threads:alloc_memory:free_memory:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/init(flags:n_threads:alloc_memory:free_memory:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(options:threadCount:allocator:deallocator:)": {
      "abstract": [
        {
          "text": "Returns a new common filter parameters structure using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFlags",
          "text": "BNNSFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "threadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSAlloc",
          "text": "BNNSAlloc"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "deallocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFree",
          "text": "BNNSFree"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(options:threadCount:allocator:deallocator:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(options:threadCount:allocator:deallocator:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/init(options:threadcount:allocator:deallocator:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/n_threads": {
      "abstract": [
        {
          "text": "The number of worker threads to execute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "n_threads"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/n_threads",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "n_threads"
        }
      ],
      "role": "symbol",
      "title": "n_threads",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/n_threads"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/options": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFlags",
          "text": "BNNSFlags"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/options",
      "kind": "symbol",
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/options"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/threadCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "threadCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/threadCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "threadCount",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfilterparameters/threadcount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFlags": {
      "abstract": [
        {
          "text": "Options that control the behavior of a filter parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFlags"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFlags"
        }
      ],
      "role": "symbol",
      "title": "BNNSFlags",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsflags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFree": {
      "abstract": [
        {
          "text": "A type-alias for a user-provided memory deallocation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFree"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFree"
        }
      ],
      "role": "symbol",
      "title": "BNNSFree",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfree"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-filters": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying Filters",
      "type": "topic",
      "url": "/documentation/accelerate/applying-filters"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/Layer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/UnaryLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/BinaryLayer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterDestroy(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSAlloc",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFree"
      ],
      "title": "General filters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(options:threadCount:allocator:deallocator:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init(flags:n_threads:alloc_memory:free_memory:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/flags",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/n_threads",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/alloc_memory",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/free_memory",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/allocator",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/deallocator",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/options",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/threadCount"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Filter-Flags",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFlags"
      ],
      "title": "Filter Flags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSFilterParameters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/flags",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/n_threads",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/alloc_memory",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterParameters/free_memory"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Filter-Flags",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFlags"
              ],
              "title": "Filter Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilter",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterDestroy(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSAlloc",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFree"
              ],
              "title": "General filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSFilterParameters"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSAlloc/title",
          "value": "BNNSAlloc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSAlloc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSAlloc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSAlloc/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSAlloc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1free_memory/title",
          "value": "free_memory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1free_memory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "free_memory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/title",
          "value": "BNNSFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1alloc_memory/title",
          "value": "alloc_memory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1alloc_memory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alloc_memory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFree/title",
          "value": "BNNSFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFree/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterDestroy(_:)/title",
          "value": "BNNSFilterDestroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterDestroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterDestroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFlags/title",
          "value": "BNNSFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1n_threads/title",
          "value": "n_threads"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters~1n_threads/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "n_threads"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/title",
          "value": "BNNSFilterParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsfilterparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsfilterparameters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
