{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"seeAlsoSections":[{"title":"Querying a graph’s properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"generated":true,"anchor":"Querying-a-graphs-properties"}],"topicSections":[{"title":"Argument intents","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut"],"anchor":"Argument-intents"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsgraphargumentintent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsgraphargumentintent"]}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Constants that describe argument intents."}],"metadata":{"navigatorTitle":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"roleHeading":"Structure","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false}],"role":"symbol","modules":[{"name":"Accelerate"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"externalID":"c:@EA@BNNSGraphArgumentIntent","symbolKind":"struct","title":"BNNSGraphArgumentIntent"},"references":{"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","title":"Sendable","kind":"symbol","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentIntents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","text":"BNNSGraphArgumentIntent","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"BNNSGraphGetArgumentIntents(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","abstract":[{"text":"Extracts the intents of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentintents(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue":{"kind":"symbol","url":"/documentation/accelerate/bnnsgraphargumentintent/rawvalue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"type":"topic","title":"rawValue","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue","role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"title":"Hashable","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"url":"/documentation/Swift/Hashable","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"kind":"text","text":" : "},{"text":"Equatable","preciseIdentifier":"s:SQ","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetOutputNames"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of output arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","title":"BNNSGraphGetOutputNames(_:_:_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut":{"type":"topic","url":"/documentation/accelerate/bnnsgraphargumentintentinout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut","title":"BNNSGraphArgumentIntentInOut","kind":"symbol","role":"symbol","abstract":[{"text":"A constant that specifies the argument is an in-place input and output tensor.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","abstract":[{"text":"Returns the number of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"url":"/documentation/accelerate/bnnsgraphargumentintent","abstract":[{"text":"Constants that describe argument intents.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","type":"topic","title":"BNNSGraphArgumentIntent"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"kind":"symbol","abstract":[{"text":"","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)":{"kind":"symbol","url":"/documentation/accelerate/bnnsgraphargumentintent/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a new instance with the specified raw value."}],"type":"topic","title":"init(rawValue:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)":{"title":"BNNSGraphGetFunctionNames(_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphGetFunctionNames"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/accelerate/bnnsgraphgetfunctionnames(_:_:_:)","navigatorTitle":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Extracts the names of callable functions in the graph.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)":{"navigatorTitle":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetFunctionCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetFunctionCount(_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","abstract":[{"type":"text","text":"Returns the number of callable functions in the specified graph."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetfunctioncount(_:)"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","role":"symbol","kind":"symbol","url":"/documentation/Swift/RawRepresentable","identifier":"doc://com.externally.resolved.symbol/s:SY","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"url":"/documentation/Swift/Equatable","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"title":"Equatable","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetOutputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetOutputCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","abstract":[{"text":"Returns the number of output arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)":{"type":"topic","url":"/documentation/accelerate/bnnsgraphargumentintent/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)","title":"init(_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Creates a new instance.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"url":"/documentation/accelerate/bnnsgraphgetargumentnames(_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","title":"BNNSGraphGetArgumentNames(_:_:_:_:)","abstract":[{"type":"text","text":"Extracts the names of arguments for the given function argument."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputNames"},{"kind":"text","text":"("},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"BNNSGraphGetInputNames(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of input arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut":{"kind":"symbol","navigatorTitle":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}],"url":"/documentation/accelerate/bnnsgraphargumentintentout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A constant that specifies the argument provides an output tensor."}],"type":"topic","title":"BNNSGraphArgumentIntentOut","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentPosition(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","abstract":[{"type":"text","text":"Returns the index into the arguments array for the given function argument."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","abstract":[{"text":"Returns the number of input arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputCount"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"BNNSGraphGetInputCount(_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntentIn"}],"url":"/documentation/accelerate/bnnsgraphargumentintentin","abstract":[{"text":"A constant that specifies the argument provides an input tensor.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntentIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","type":"topic","title":"BNNSGraphArgumentIntentIn"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":">?>, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","abstract":[{"text":"Returns the interleave factors for arguments, if present","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentinterleavefactors(_:_:_:_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration","path":"/metadata/roleHeading"},{"op":"replace","value":"BNNSGraphArgumentIntent","path":"/metadata/title"},{"op":"replace","value":"enum","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut"],"anchor":"Argument-intents","title":"Argument intents"}]},{"op":"replace","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Querying a graph’s properties","anchor":"Querying-a-graphs-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"BNNSGraphArgumentIntent","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/title","op":"replace","value":"BNNSGraphGetArgumentIntents"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/title","op":"replace","value":"BNNSGraphGetOutputNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetOutputNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentInOut/title","value":"BNNSGraphArgumentIntentInOut"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentInOut/fragments","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/title","value":"BNNSGraphGetArgumentCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/title","value":"BNNSGraphArgumentIntent"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/fragments","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/navigatorTitle","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/title","value":"BNNSGraphGetFunctionNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/fragments","value":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/title","value":"BNNSGraphGetFunctionCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/fragments","value":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/title","value":"BNNSGraphGetOutputCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/fragments","value":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/title","value":"BNNSGraphGetArgumentNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/title","value":"BNNSGraphGetInputNames"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentOut/title","value":"BNNSGraphArgumentIntentOut"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentOut/fragments","value":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/title","value":"BNNSGraphGetArgumentPosition"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/title","value":"BNNSGraphGetInputCount"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentIn/title","value":"BNNSGraphArgumentIntentIn"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentIn/fragments","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntentIn"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/title","value":"BNNSGraphGetArgumentInterleaveFactors"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/fragments","value":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}]}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]},"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}