{
  "abstract": [
    {
      "text": "A batch normalization filter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSFilterType@BNNSBatchNorm",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSBatchNorm"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSFilterType",
        "text": "BNNSFilterType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSBatchNorm"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSBatchNorm"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSBatchNorm"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSFilterType",
              "text": "BNNSFilterType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic": {
      "abstract": [
        {
          "text": "An arithmetic filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSArithmetic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSArithmetic"
        }
      ],
      "role": "symbol",
      "title": "BNNSArithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsarithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm": {
      "abstract": [
        {
          "text": "A batch normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSBatchNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSBatchNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSBatchNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSBatchNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsbatchnorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution": {
      "abstract": [
        {
          "text": "A convolution filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSConvolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSConvolution"
        }
      ],
      "role": "symbol",
      "title": "BNNSConvolution",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsconvolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType": {
      "abstract": [
        {
          "text": "Constants that define the component filters of a fused layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterType"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltertype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected": {
      "abstract": [
        {
          "text": "A fully connected filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFullyConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFullyConnected"
        }
      ],
      "role": "symbol",
      "title": "BNNSFullyConnected",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfullyconnected"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm": {
      "abstract": [
        {
          "text": "A group normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGroupNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGroupNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSGroupNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgroupnorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm": {
      "abstract": [
        {
          "text": "An instance normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSInstanceNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSInstanceNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSInstanceNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsinstancenorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm": {
      "abstract": [
        {
          "text": "A layer normalization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSLayerNorm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSLayerNorm"
        }
      ],
      "role": "symbol",
      "title": "BNNSLayerNorm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnslayernorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization": {
      "abstract": [
        {
          "text": "A quantization filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSQuantization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSQuantization"
        }
      ],
      "role": "symbol",
      "title": "BNNSQuantization",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsquantization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution": {
      "abstract": [
        {
          "text": "A transposed convolution filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSTransposedConvolution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSFilterType",
          "text": "BNNSFilterType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSTransposedConvolution"
        }
      ],
      "role": "symbol",
      "title": "BNNSTransposedConvolution",
      "type": "topic",
      "url": "/documentation/accelerate/bnnstransposedconvolution"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layer-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization"
      ],
      "title": "Layer Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSBatchNorm"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSBatchNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layer-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSArithmetic",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSConvolution",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSTransposedConvolution",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnected",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGroupNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSInstanceNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerNorm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSQuantization"
              ],
              "title": "Layer Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSBatchNorm"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSQuantization/title",
          "value": "BNNSQuantization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSQuantization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSQuantization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSBatchNorm/title",
          "value": "BNNSBatchNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSBatchNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSBatchNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTransposedConvolution/title",
          "value": "BNNSTransposedConvolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTransposedConvolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTransposedConvolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGroupNorm/title",
          "value": "BNNSGroupNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGroupNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGroupNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSConvolution/title",
          "value": "BNNSConvolution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSConvolution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSConvolution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSInstanceNorm/title",
          "value": "BNNSInstanceNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSInstanceNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSInstanceNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnected/title",
          "value": "BNNSFullyConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFullyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmetic/title",
          "value": "BNNSArithmetic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSArithmetic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSArithmetic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerNorm/title",
          "value": "BNNSLayerNorm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerNorm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerNorm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/title",
          "value": "BNNSFilterType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsbatchnorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsbatchnorm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
