{
  "abstract": [
    {
      "text": "Specifies a customized callback function that reports compile-time messages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@BNNSGraphCompileOptionsSetMessageLogCallback",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
        "text": "bnns_graph_compile_options_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
        "text": "bnns_graph_compile_message_fn_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
        "text": "bnns_user_message_data_t"
      },
      {
        "kind": "text",
        "text": ">?)"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
              "text": "bnns_graph_compile_options_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "log_callback"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
              "text": "bnns_graph_compile_message_fn_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "additional_logging_arguments"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
              "text": "bnns_user_message_data_t"
            },
            {
              "kind": "text",
              "text": ">?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The compilation options object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The message-logging callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "log_callback"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Additional data for the message-logging functions that BNNS passes unaltered to the callback function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "additional_logging_arguments"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t specify this callback, default callback functions log messages to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/os/os_log",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code adds a custom graph compile message callback function that prints ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " level messages to the console:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let options = BNNSGraphCompileOptionsMakeDefault()",
            "defer {",
            "    BNNSGraphCompileOptionsDestroy(options)",
            "}",
            "",
            "BNNSGraphCompileOptionsSetMessageLogMask(options, BNNSGraphMessageLevelInfo.rawValue)",
            "BNNSGraphCompileOptionsSetMessageLogCallback(options, messageLogCallback, nil)",
            "",
            "func messageLogCallback(msg_level: BNNSGraphMessageLevel,",
            "                        error_msg: UnsafePointer<CChar>,",
            "                        source_location: UnsafePointer<CChar>?,",
            "                        user_message_data_t:UnsafeMutablePointer<user_message_data_t>?) {",
            "    ",
            "    print(NSString(cString: error_msg, encoding: NSUTF8StringEncoding) ?? \"\")",
            "    if let source_location = source_location {",
            "        print(NSString(cString: source_location, encoding: NSUTF8StringEncoding) ?? \"\")",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies a customized callback function that reports compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
          "text": "bnns_graph_compile_message_fn_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
          "text": "bnns_user_message_data_t"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogcallback(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets mask for log messages that are logged (either via ",
          "type": "text"
        },
        {
          "code": "os_log",
          "type": "codeVoice"
        },
        {
          "text": " or the user specified callback)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_context_t",
          "text": "bnns_graph_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphContextSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcontextsetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel": {
      "abstract": [
        {
          "text": "Constants that specify the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevel",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo": {
      "abstract": [
        {
          "text": "A constant that specifies information message types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphMessageLevel",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevelInfo",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevelinfo"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t": {
      "abstract": [
        {
          "text": "The graph compile-message logging callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_compile_message_fn_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_message_fn_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t": {
      "abstract": [
        {
          "text": "The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_options_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_options_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_compile_options_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t": {
      "abstract": [
        {
          "text": "Additional user-defined logging argument for message-logging callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_user_message_data_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t"
    },
    "doc://com.apple.documentation/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "internalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "internalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ", ...)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-graphs-compile-time-message-callback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t"
      ],
      "title": "Specifying a graph’s compile-time message callback"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-graphs-compile-time-message-callback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t"
              ],
              "title": "Specifying a graph’s compile-time message callback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
                    "text": "bnns_graph_compile_options_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
                    "text": "bnns_graph_compile_message_fn_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "log_callback"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
                    "text": "bnns_user_message_data_t"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "additional_logging_arguments"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The compilation options object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The message-logging callback function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "log_callback"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Additional data for the message-logging functions that BNNS passes unaltered to the callback function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "additional_logging_arguments"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/title",
          "value": "bnns_user_message_data_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelInfo/title",
          "value": "BNNSGraphMessageLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/title",
          "value": "bnns_graph_compile_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphContextSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/title",
          "value": "BNNSGraphMessageLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/title",
          "value": "bnns_graph_compile_message_fn_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogcallback(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogcallback(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
