{
  "abstract": [
    {
      "text": "The operator that indicates the equal-to relationship.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSRelationalOperator@BNNSRelationalOperatorEqual",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperatorEqual"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
        "text": "BNNSRelationalOperator"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSRelationalOperatorEqual"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSRelationalOperatorEqual"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorEqual"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
              "text": "BNNSRelationalOperator"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator": {
      "abstract": [
        {
          "text": "Constants that describe relational operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperator"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater": {
      "abstract": [
        {
          "text": "The operator that indicates the greater-than relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreater"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorGreater",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorgreater"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the greater-than or equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreaterEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorGreaterEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorGreaterEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorgreaterequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess": {
      "abstract": [
        {
          "text": "The operator that indicates the less-than relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLess"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLess",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorless"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the less-than or equal-to relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLessEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorLessEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorLessEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatorlessequal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual": {
      "abstract": [
        {
          "text": "The operator that indicates the not-equal relationship.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorNotEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRelationalOperator",
          "text": "BNNSRelationalOperator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRelationalOperatorNotEqual"
        }
      ],
      "role": "symbol",
      "title": "BNNSRelationalOperatorNotEqual",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrelationaloperatornotequal"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Relational-Operators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual"
      ],
      "title": "Relational Operators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSRelationalOperatorEqual"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperator"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Relational-Operators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreater",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorGreaterEqual",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLess",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorLessEqual",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRelationalOperatorNotEqual"
              ],
              "title": "Relational Operators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSRelationalOperatorEqual"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorNotEqual/title",
          "value": "BNNSRelationalOperatorNotEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorNotEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorNotEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreaterEqual/title",
          "value": "BNNSRelationalOperatorGreaterEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreaterEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorGreaterEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLessEqual/title",
          "value": "BNNSRelationalOperatorLessEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLessEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLessEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorEqual/title",
          "value": "BNNSRelationalOperatorEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorEqual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/title",
          "value": "BNNSRelationalOperator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreater/title",
          "value": "BNNSRelationalOperatorGreater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorGreater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorGreater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLess/title",
          "value": "BNNSRelationalOperatorLess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRelationalOperatorLess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRelationalOperatorLess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperatorequal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsrelationaloperatorequal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
