{"sections":[],"abstract":[{"text":"Returns the option for the compiled graph’s output file descriptor.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"bnns_graph_compile_options_t","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The compilation options object.","type":"text"}]}],"name":"options"}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The file descriptor that the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)"},{"type":"text","text":" function defines, if any."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/accelerate/bnnsgraphcompileoptionsgetoutputfd(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnsgraphcompileoptionsgetoutputfd(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Specifying-and-querying-compilation-options","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"],"title":"Specifying and querying compilation options"}],"metadata":{"roleHeading":"Function","modules":[{"name":"Accelerate"}],"platforms":[{"name":"iOS","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"introducedAt":"15.0","deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"introducedAt":"18.0","deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false},{"name":"watchOS","beta":false,"introducedAt":"11.0","deprecated":false,"unavailable":false}],"role":"symbol","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","kind":"typeIdentifier","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"}],"externalID":"c:@F@BNNSGraphCompileOptionsGetOutputFD","title":"BNNSGraphCompileOptionsGetOutputFD(_:)"},"kind":"symbol","references":{"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t":{"url":"/documentation/accelerate/bnns_graph_compile_options_t","kind":"symbol","role":"symbol","type":"topic","title":"bnns_graph_compile_options_t","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_compile_options_t"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","abstract":[{"text":"The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_compile_options_t"}]},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoutputpath(_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputPath"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"Returns the option for the compiled graph’s output path."}],"title":"BNNSGraphCompileOptionsGetOutputPath(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgettargetsinglethread(_:)","type":"topic","abstract":[{"type":"text","text":"Returns the option for the compiled graph to execute on a single thread."}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"}],"title":"BNNSGraphCompileOptionsGetTargetSingleThread(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric":{"url":"/documentation/accelerate/bnnstargetsystemgeneric","navigatorTitle":[{"kind":"identifier","text":"BNNSTargetSystemGeneric"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTargetSystemGeneric","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@BNNSTargetSystem","text":"BNNSTargetSystem"}],"abstract":[],"title":"BNNSTargetSystemGeneric","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"}],"kind":"symbol","title":"BNNSGraphCompileOptionsGetOutputFD(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsGetOutputFD","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoutputfd(_:)","abstract":[{"text":"Returns the option for the compiled graph’s output file descriptor.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoptimizationpreference(_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@EA@BNNSGraphOptimizationPreference","kind":"typeIdentifier","text":"BNNSGraphOptimizationPreference"}],"abstract":[{"type":"text","text":"Returns the option for the compiled graph to optimize for either size or performance."}],"title":"BNNSGraphCompileOptionsGetOptimizationPreference(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionssettargetsinglethread(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the option for the compiled graph to execute on a single thread."}],"title":"BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"}],"kind":"symbol","title":"BNNSGraphCompileOptionsDestroy(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","abstract":[{"type":"text","text":"Destroys the specified compilation options object."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsdestroy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","kind":"typeIdentifier","text":"bnns_graph_compile_options_t"},{"kind":"text","text":")"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?)"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoutputpath(_:_:)","type":"topic","abstract":[{"type":"text","text":"Sets the option for graph compilation to generate the graph object directly to the specified file."}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputPath"}],"title":"BNNSGraphCompileOptionsSetOutputPath(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetGenerateDebugInfo"}],"kind":"symbol","title":"BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","abstract":[{"type":"text","text":"Returns the option for the compiled graph to include debugging information."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetgeneratedebuginfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsGetGenerateDebugInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}],"url":"/documentation/accelerate/bnnsgraphoptimizationpreference","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}],"abstract":[{"text":"Constants that describe the compilation optimization preference.","type":"text"}],"kind":"symbol","type":"topic","title":"BNNSGraphOptimizationPreference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoutputfd(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputFD"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputFD"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the option for graph compilation to generate the graph object directly to the specified file descriptor."}],"title":"BNNSGraphCompileOptionsSetOutputFD(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@EA@BNNSGraphOptimizationPreference","kind":"typeIdentifier","text":"BNNSGraphOptimizationPreference"},{"kind":"text","text":")"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoptimizationpreference(_:_:)","type":"topic","abstract":[{"text":"Sets the option for the compiled graph to optimize for either size or performance.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"}],"title":"BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsmakedefault()","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsMakeDefault"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsMakeDefault","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"}],"abstract":[{"text":"Returns an allocated compilation options object with default values.","type":"text"}],"title":"BNNSGraphCompileOptionsMakeDefault()","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetGenerateDebugInfo"}],"kind":"symbol","title":"BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","abstract":[{"type":"text","text":"Sets the option for the compiled graph to include debugging information."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetgeneratedebuginfo(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetGenerateDebugInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:s5Int32V":{"url":"/documentation/Swift/Int32","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"kind":"symbol","type":"topic","title":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"introducedAt":"15.0","unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"introducedAt":"11.0","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphCompileOptionsGetOutputFD","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"BNNSGraphCompileOptionsGetOutputFD","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Specifying-and-querying-compilation-options","generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"],"title":"Specifying and querying compilation options"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsGetOutputFD","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_compile_options_t","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The compilation options object."}]}]}]}},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The file descriptor that the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)","type":"reference"},{"text":" function defines, if any.","type":"text"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/title","value":"bnns_graph_compile_options_t"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/fragments","value":[{"text":"bnns_graph_compile_options_t","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/navigatorTitle","value":[{"kind":"identifier","text":"bnns_graph_compile_options_t"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/title","value":"BNNSGraphCompileOptionsGetOutputPath"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/fragments","value":[{"text":"BNNSGraphCompileOptionsGetOutputPath","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/title","value":"BNNSGraphCompileOptionsGetTargetSingleThread"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/title","value":"BNNSTargetSystemGeneric"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/fragments","value":[{"text":"BNNSTargetSystemGeneric","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/title","value":"BNNSGraphCompileOptionsGetOutputFD","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/title","value":"BNNSGraphCompileOptionsGetOptimizationPreference","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/title","value":"BNNSGraphCompileOptionsSetTargetSingleThread","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/fragments","value":[{"text":"BNNSGraphCompileOptionsSetTargetSingleThread","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/title","value":"BNNSGraphCompileOptionsDestroy","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/title","value":"BNNSGraphCompileOptionsSetOutputPath","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/fragments","value":[{"text":"BNNSGraphCompileOptionsSetOutputPath","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/title","value":"BNNSGraphCompileOptionsGetGenerateDebugInfo","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetGenerateDebugInfo"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/title","value":"BNNSGraphOptimizationPreference","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/fragments","value":[{"text":"BNNSGraphOptimizationPreference","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/navigatorTitle","value":[{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/title","value":"BNNSGraphCompileOptionsSetOutputFD","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/fragments","value":[{"text":"BNNSGraphCompileOptionsSetOutputFD","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/title","value":"BNNSGraphCompileOptionsSetOptimizationPreference","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/title","value":"BNNSGraphCompileOptionsMakeDefault","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/fragments","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsMakeDefault"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/title","value":"BNNSGraphCompileOptionsSetGenerateDebugInfo","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/fragments","value":[{"text":"BNNSGraphCompileOptionsSetGenerateDebugInfo","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}