{
  "abstract": [
    {
      "text": "A function for pooling that computes the average of each element in the pooling kernel, including zero-padding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountIncludePadding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSPoolingFunction@BNNSPoolingFunctionAverageCountIncludePadding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSPoolingFunctionAverageCountIncludePadding"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
        "text": "BNNSPoolingFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSPoolingFunctionAverageCountIncludePadding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSPoolingFunctionAverageCountIncludePadding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionAverageCountIncludePadding"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
              "text": "BNNSPoolingFunction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction": {
      "abstract": [
        {
          "text": "Constants that describe pooling functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionAverage": {
      "abstract": [
        {
          "text": "A function for pooling that computes the average of each element in the pooling kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionAverage"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionAverage",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSPoolingFunctionAverage",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction/bnnspoolingfunctionaverage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionMax": {
      "abstract": [
        {
          "text": "A function for pooling that computes the maximum of each element in the pooling kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionMax"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionMax",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSPoolingFunctionMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction/bnnspoolingfunctionmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunction/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountExcludePadding": {
      "abstract": [
        {
          "text": "A function for pooling that computes the average of each element in the pooling kernel, excluding zero-padding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionAverageCountExcludePadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountExcludePadding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionAverageCountExcludePadding"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingFunctionAverageCountExcludePadding",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunctionaveragecountexcludepadding"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountIncludePadding": {
      "abstract": [
        {
          "text": "A function for pooling that computes the average of each element in the pooling kernel, including zero-padding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionAverageCountIncludePadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountIncludePadding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionAverageCountIncludePadding"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingFunctionAverageCountIncludePadding",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunctionaveragecountincludepadding"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionL2Norm": {
      "abstract": [
        {
          "text": "A function for pooling that computes the square root of the sum of squares of each element in the pooling kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionL2Norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionL2Norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionL2Norm"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingFunctionL2Norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunctionl2norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionUnMax": {
      "abstract": [
        {
          "text": "A function for pooling that’s the partial inverse of max pooling and sets all nonmaximal values to zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionUnMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionUnMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingFunctionUnMax"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingFunctionUnMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolingfunctionunmax"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Raw-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionUnMax",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountExcludePadding",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionL2Norm"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSPoolingFunctionAverageCountIncludePadding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionAverageCountIncludePadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Raw-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionMax",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionUnMax",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunction/BNNSPoolingFunctionAverage",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionAverageCountExcludePadding",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingFunctionL2Norm"
              ],
              "title": "Raw Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSPoolingFunctionAverageCountIncludePadding"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionUnMax/title",
          "value": "BNNSPoolingFunctionUnMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionUnMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionUnMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionAverageCountIncludePadding/title",
          "value": "BNNSPoolingFunctionAverageCountIncludePadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionAverageCountIncludePadding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionAverageCountIncludePadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionL2Norm/title",
          "value": "BNNSPoolingFunctionL2Norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionL2Norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionL2Norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunction/title",
          "value": "BNNSPoolingFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionAverageCountExcludePadding/title",
          "value": "BNNSPoolingFunctionAverageCountExcludePadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingFunctionAverageCountExcludePadding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingFunctionAverageCountExcludePadding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnspoolingfunctionaveragecountincludepadding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnspoolingfunctionaveragecountincludepadding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
