{
  "abstract": [
    {
      "text": "A structure that contains optimizer functions.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSOptimizerFunction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSOptimizerFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSOptimizerFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSOptimizerFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the Adam optimization algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AdamOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdamOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.AdamOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the AdamW optimization algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AdamWOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdamWOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.AdamWOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamwoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the root mean square propagation (RMSProp) optimization method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RMSPropOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RMSPropOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RMSPropOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/rmspropoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the stochastic gradient descent (SGD) with the momentum optimization method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SGDMomentumOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SGDMomentumOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.SGDMomentumOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/sgdmomentumoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of an Adam optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerAdamFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of an Adam or AdamW optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerAdamWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction": {
      "abstract": [
        {
          "text": "A structure that contains optimizer functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunction/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunction/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunction/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdam": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the Adam algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdam"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdam"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdam",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadam"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGrad": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AMSGrad variant of the Adam algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamAMSGrad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGrad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamAMSGrad"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamAMSGrad",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamamsgrad"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGradWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AMSGrad variant of the Adam algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamAMSGradWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGradWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamAMSGradWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamAMSGradWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamamsgradwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamW": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AdamW algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamW"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGrad": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AMSGrad variant of the AdamW algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWAMSGrad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGrad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWAMSGrad"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamWAMSGrad",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamwamsgrad"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGradWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AMSGrad variant of the AdamW algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWAMSGradWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGradWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWAMSGradWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamWAMSGradWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamwamsgradwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the AdamW algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamWWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamwwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the Adam algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionAdamWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionAdamWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionadamwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSProp": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the root mean square propagation (RMSProp) algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionRMSProp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSProp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionRMSProp"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionRMSProp",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionrmsprop"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSPropWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the root mean square propagation (RMSProp) algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionRMSPropWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSPropWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionRMSPropWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionRMSPropWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionrmspropwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentum": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the stochastic gradient descent (SGD) with momentum algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionSGDMomentum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionSGDMomentum"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionSGDMomentum",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionsgdmomentum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentumWithClipping": {
      "abstract": [
        {
          "text": "An optimizer function that updates parameters according to the stochastic gradient descent (SGD) with momentum algorithm and optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionSGDMomentumWithClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentumWithClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunctionSGDMomentumWithClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunctionSGDMomentumWithClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunctionsgdmomentumwithclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a root mean square propagation (RMSProp) optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRMSPropFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerrmspropfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a root mean square propagation (RMSProp) optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRMSPropWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerrmspropwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction": {
      "abstract": [
        {
          "text": "A structure that contains optimizer regularization functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRegularizationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerregularizationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a stochastic gradient descent (SGD) with momentum optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant": {
      "abstract": [
        {
          "text": "Constants that define SGD momentum variants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumVariant"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumVariant"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumVariant",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumvariant"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a stochastic gradient descent (SGD) with momentum optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a single optimization step to one or more parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerStep"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerStep"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerStep(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerstep(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Optimizers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)"
      ],
      "title": "Optimizers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adam-Optimizer-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdam",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWithClipping",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGrad",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGradWithClipping"
      ],
      "title": "Adam Optimizer Functions"
    },
    {
      "anchor": "AdamW-Optimizer-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamW",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWWithClipping",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGrad",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGradWithClipping"
      ],
      "title": "AdamW Optimizer Functions"
    },
    {
      "anchor": "RMSProp-Optimizer-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSProp",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSPropWithClipping"
      ],
      "title": "RMSProp Optimizer Functions"
    },
    {
      "anchor": "SGD-Optimizer-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentum",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentumWithClipping"
      ],
      "title": "SGD  Optimizer Functions"
    },
    {
      "anchor": "Raw-Values",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction/init(rawValue:)"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSOptimizerFunction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adam-Optimizer-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdam",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWithClipping",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGrad",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamAMSGradWithClipping"
              ],
              "title": "Adam Optimizer Functions"
            },
            {
              "anchor": "AdamW-Optimizer-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamW",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWWithClipping",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGrad",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionAdamWAMSGradWithClipping"
              ],
              "title": "AdamW Optimizer Functions"
            },
            {
              "anchor": "RMSProp-Optimizer-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSProp",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionRMSPropWithClipping"
              ],
              "title": "RMSProp Optimizer Functions"
            },
            {
              "anchor": "SGD-Optimizer-Functions",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentum",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunctionSGDMomentumWithClipping"
              ],
              "title": "SGD  Optimizer Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Optimizers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)"
              ],
              "title": "Optimizers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSOptimizerFunction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/title",
          "value": "BNNSOptimizerAdamWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWWithClipping/title",
          "value": "BNNSOptimizerFunctionAdamWWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamWWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerStep(_:_:_:_:_:_:_:)/title",
          "value": "BNNSOptimizerStep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerStep(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerStep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionSGDMomentum/title",
          "value": "BNNSOptimizerFunctionSGDMomentum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionSGDMomentum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionSGDMomentum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/title",
          "value": "BNNSOptimizerRMSPropFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWAMSGrad/title",
          "value": "BNNSOptimizerFunctionAdamWAMSGrad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWAMSGrad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamWAMSGrad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/title",
          "value": "BNNSOptimizerSGDMomentumFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWithClipping/title",
          "value": "BNNSOptimizerFunctionAdamWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/title",
          "value": "BNNSOptimizerRegularizationFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRegularizationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRegularizationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/title",
          "value": "BNNSOptimizerRMSPropWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWAMSGradWithClipping/title",
          "value": "BNNSOptimizerFunctionAdamWAMSGradWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamWAMSGradWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamWAMSGradWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionRMSProp/title",
          "value": "BNNSOptimizerFunctionRMSProp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionRMSProp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionRMSProp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionSGDMomentumWithClipping/title",
          "value": "BNNSOptimizerFunctionSGDMomentumWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionSGDMomentumWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionSGDMomentumWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/title",
          "value": "BNNSOptimizerSGDMomentumVariant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumVariant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumVariant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/title",
          "value": "BNNSOptimizerFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamW/title",
          "value": "BNNSOptimizerFunctionAdamW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamAMSGrad/title",
          "value": "BNNSOptimizerFunctionAdamAMSGrad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamAMSGrad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamAMSGrad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/title",
          "value": "BNNSOptimizerAdamFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamAMSGradWithClipping/title",
          "value": "BNNSOptimizerFunctionAdamAMSGradWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdamAMSGradWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdamAMSGradWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/title",
          "value": "BNNSOptimizerSGDMomentumWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionRMSPropWithClipping/title",
          "value": "BNNSOptimizerFunctionRMSPropWithClipping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionRMSPropWithClipping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionRMSPropWithClipping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdam/title",
          "value": "BNNSOptimizerFunctionAdam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunctionAdam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunctionAdam"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizerfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsoptimizerfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
