{
  "abstract": [
    {
      "text": "The pixel unshuffle for the NCHW (batch, channels, height, width) format, equivalent to space-to-depth in Column Row Depth (CRD) mode.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelUnshuffleNCHW"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSShuffleType@BNNSShuffleTypePixelUnshuffleNCHW",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSShuffleTypePixelUnshuffleNCHW"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSShuffleType",
        "text": "BNNSShuffleType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSShuffleTypePixelUnshuffleNCHW"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSShuffleTypePixelUnshuffleNCHW"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypePixelUnshuffleNCHW"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSShuffleType",
              "text": "BNNSShuffleType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this shuffle type to reverse the pixel shuffle operation by rearranging elements in a tensor of shape ",
              "type": "text"
            },
            {
              "code": "(N,C,H×r,W×r)",
              "type": "codeVoice"
            },
            {
              "text": " to a tensor of shape ",
              "type": "text"
            },
            {
              "code": "(N,C×rxr,H,W)",
              "type": "codeVoice"
            },
            {
              "text": ", where ",
              "type": "text"
            },
            {
              "code": "r",
              "type": "codeVoice"
            },
            {
              "text": " is a downscale factor",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType": {
      "abstract": [
        {
          "text": "Constants that specify a shuffle type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSShuffleType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSShuffleType"
        }
      ],
      "role": "symbol",
      "title": "BNNSShuffleType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletype/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletype/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletype/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeDepthToSpaceNCHW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypeDepthToSpaceNCHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSShuffleType",
          "text": "BNNSShuffleType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeDepthToSpaceNCHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypeDepthToSpaceNCHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSShuffleTypeDepthToSpaceNCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletypedepthtospacenchw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelShuffleNCHW": {
      "abstract": [
        {
          "text": "The pixel shuffle for the NCHW (batch, channels, height, width) format, equivalent to depth-to-space in Column Row Depth (CRD) mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypePixelShuffleNCHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSShuffleType",
          "text": "BNNSShuffleType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelShuffleNCHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypePixelShuffleNCHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSShuffleTypePixelShuffleNCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletypepixelshufflenchw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelUnshuffleNCHW": {
      "abstract": [
        {
          "text": "The pixel unshuffle for the NCHW (batch, channels, height, width) format, equivalent to space-to-depth in Column Row Depth (CRD) mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypePixelUnshuffleNCHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSShuffleType",
          "text": "BNNSShuffleType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelUnshuffleNCHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypePixelUnshuffleNCHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSShuffleTypePixelUnshuffleNCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletypepixelunshufflenchw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeSpaceToDepthNCHW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypeSpaceToDepthNCHW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSShuffleType",
          "text": "BNNSShuffleType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeSpaceToDepthNCHW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSShuffleTypeSpaceToDepthNCHW"
        }
      ],
      "role": "symbol",
      "title": "BNNSShuffleTypeSpaceToDepthNCHW",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsshuffletypespacetodepthnchw"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelShuffleNCHW",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeDepthToSpaceNCHW",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeSpaceToDepthNCHW"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSShuffleTypePixelUnshuffleNCHW"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypePixelUnshuffleNCHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypePixelShuffleNCHW",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeDepthToSpaceNCHW",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSShuffleTypeSpaceToDepthNCHW"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSShuffleTypePixelUnshuffleNCHW"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypeDepthToSpaceNCHW/title",
          "value": "BNNSShuffleTypeDepthToSpaceNCHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypeDepthToSpaceNCHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypeDepthToSpaceNCHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleType/title",
          "value": "BNNSShuffleType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypePixelUnshuffleNCHW/title",
          "value": "BNNSShuffleTypePixelUnshuffleNCHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypePixelUnshuffleNCHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypePixelUnshuffleNCHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypeSpaceToDepthNCHW/title",
          "value": "BNNSShuffleTypeSpaceToDepthNCHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypeSpaceToDepthNCHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypeSpaceToDepthNCHW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypePixelShuffleNCHW/title",
          "value": "BNNSShuffleTypePixelShuffleNCHW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSShuffleTypePixelShuffleNCHW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSShuffleTypePixelShuffleNCHW"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsshuffletypepixelunshufflenchw"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsshuffletypepixelunshufflenchw"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
