{"abstract":[{"type":"text","text":"Extracts the names of output arguments for the given function argument."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetOutputNames","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"graph","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"function","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SP","text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"output_names_count","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"output_names","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sp","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:SP","text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5Int32V","text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"parameters":[{"name":"graph","content":[{"inlineContent":[{"text":"The compiled graph object.","type":"text"}],"type":"paragraph"}]},{"name":"function","content":[{"inlineContent":[{"type":"text","text":"The function. Specify as "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the graph only contains one function."}],"type":"paragraph"}]},{"name":"output_names_count","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The number of elements in the "},{"code":"output_names","type":"codeVoice"},{"type":"text","text":" array."}]}]},{"name":"output_names","content":[{"inlineContent":[{"type":"text","text":"On output, an array of pointers to strings that contain the input names."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"0"},{"type":"text","text":" on success, nonzero on failure."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"variants":[{"paths":["/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetOutputNames"}],"role":"symbol","symbolKind":"func","platforms":[{"introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"15.0","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"introducedAt":"18.0","unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"},{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"watchOS"}],"roleHeading":"Function","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_t","kind":"typeIdentifier","text":"bnns_graph_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?, "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?>) -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"modules":[{"name":"Accelerate"}],"externalID":"c:@F@BNNSGraphGetOutputNames","title":"BNNSGraphGetOutputNames(_:_:_:_:)"},"seeAlsoSections":[{"generated":true,"title":"Querying a graph’s properties","anchor":"Querying-a-graphs-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"]}],"references":{"doc://com.externally.resolved.symbol/s:s5CChara":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CChar"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"Int8","preciseIdentifier":"s:s4Int8V"}],"identifier":"doc://com.externally.resolved.symbol/s:s5CChara","kind":"symbol","url":"/documentation/Swift/CChar","role":"symbol","abstract":[{"text":"The C ‘char’ type.","type":"text"}],"title":"CChar","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetOutputCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetOutputCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","abstract":[{"text":"Returns the number of output arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t":{"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_t"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_t"}],"title":"bnns_graph_t","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","abstract":[{"text":"The compiled graph object.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnns_graph_t"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"url":"/documentation/accelerate/bnnsgraphgetargumentnames(_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","title":"BNNSGraphGetArgumentNames(_:_:_:_:)","abstract":[{"type":"text","text":"Extracts the names of arguments for the given function argument."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"url":"/documentation/accelerate/bnnsgraphargumentintent","abstract":[{"text":"Constants that describe argument intents.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","type":"topic","title":"BNNSGraphArgumentIntent"},"doc://com.externally.resolved.symbol/s:s5Int32V":{"url":"/documentation/Swift/Int32","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int32"}],"abstract":[{"text":"A 32-bit signed integer value type.","type":"text"}],"kind":"symbol","type":"topic","title":"Int32","identifier":"doc://com.externally.resolved.symbol/s:s5Int32V"},"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.externally.resolved.symbol/s:Sp":{"url":"/documentation/Swift/UnsafeMutablePointer","kind":"symbol","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:Sp","title":"UnsafeMutablePointer","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentCount","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentCount(_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","abstract":[{"text":"Returns the number of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentIntents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","text":"BNNSGraphArgumentIntent","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"BNNSGraphGetArgumentIntents(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","abstract":[{"text":"Extracts the intents of arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentintents(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt16V","text":"UInt16","kind":"typeIdentifier"},{"text":">?>, ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"title":"BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)","abstract":[{"text":"Returns the interleave factors for arguments, if present","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentinterleavefactors(_:_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)":{"navigatorTitle":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetFunctionCount"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetFunctionCount(_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","abstract":[{"type":"text","text":"Returns the number of callable functions in the specified graph."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetfunctioncount(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)":{"title":"BNNSGraphGetFunctionNames(_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphGetFunctionNames"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"url":"/documentation/accelerate/bnnsgraphgetfunctionnames(_:_:_:)","navigatorTitle":[{"text":"BNNSGraphGetFunctionNames","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Extracts the names of callable functions in the graph.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputNames"},{"kind":"text","text":"("},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"CChar","preciseIdentifier":"s:s5CChara","kind":"typeIdentifier"},{"text":">?>) -> ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"title":"BNNSGraphGetInputNames(_:_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of input arguments for the given function argument.","type":"text"}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputnames(_:_:_:_:)"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetInputCount"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","abstract":[{"text":"Returns the number of input arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetInputCount"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"BNNSGraphGetInputCount(_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetinputcount(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetArgumentPosition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_t","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">?, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">) -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"BNNSGraphGetArgumentPosition(_:_:_:)","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","abstract":[{"type":"text","text":"Returns the index into the arguments array for the given function argument."}],"type":"topic","role":"symbol","url":"/documentation/accelerate/bnnsgraphgetargumentposition(_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphGetOutputNames"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputNames(_:_:_:_:)","abstract":[{"text":"Extracts the names of output arguments for the given function argument.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"text":"(","kind":"text"},{"text":"bnns_graph_t","kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5CChara","text":"CChar"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5CChara","text":"CChar","kind":"typeIdentifier"},{"kind":"text","text":">?>) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"type":"topic","title":"BNNSGraphGetOutputNames(_:_:_:_:)","kind":"symbol","url":"/documentation/accelerate/bnnsgraphgetoutputnames(_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"18.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"18.0","beta":false,"unavailable":false},{"beta":false,"introducedAt":"18.0","name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"15.0","name":"macOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"18.0","name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"2.0","name":"visionOS","unavailable":false,"deprecated":false},{"beta":false,"introducedAt":"11.0","name":"watchOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphGetOutputNames","op":"replace","path":"/metadata/title"},{"op":"replace","value":"func","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"BNNSGraphGetOutputNames","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Querying a graph’s properties","anchor":"Querying-a-graphs-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentIntents(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionCount(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetFunctionNames(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetInputNames(_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetOutputCount(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentPosition(_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphGetOutputNames"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_t","text":"bnns_graph_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"graph"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:C","text":"char"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"function"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","text":"size_t"},{"kind":"text","text":" "},{"kind":"internalParam","text":"output_names_count"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:C","text":"char"},{"kind":"text","text":" * * "},{"kind":"internalParam","text":"output_names"},{"kind":"text","text":");"}],"languages":["occ"]}]}},{"op":"replace","value":{"parameters":[{"name":"graph","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The compiled graph object."}]}]},{"name":"function","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The function. Specify as "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the graph only contains one function."}]}]},{"name":"output_names_count","content":[{"type":"paragraph","inlineContent":[{"text":"The number of elements in the ","type":"text"},{"code":"output_names","type":"codeVoice"},{"text":" array.","type":"text"}]}]},{"name":"output_names","content":[{"type":"paragraph","inlineContent":[{"text":"On output, an array of pointers to strings that contain the input names.","type":"text"}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"0"},{"type":"text","text":" on success, nonzero on failure."}],"type":"paragraph"}]}},{"op":"replace","value":"BNNSGraphGetOutputCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetOutputCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputCount(_:_:)/fragments"},{"op":"replace","value":"bnns_graph_t","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/title"},{"op":"replace","value":[{"text":"bnns_graph_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/fragments"},{"op":"replace","value":[{"text":"bnns_graph_t","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_t/navigatorTitle"},{"op":"replace","value":"BNNSGraphGetArgumentNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentNames"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentNames(_:_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphArgumentIntent","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/fragments"},{"op":"replace","value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/navigatorTitle"},{"op":"replace","value":"BNNSGraphGetArgumentCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentCount"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentCount(_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetArgumentIntents","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSGraphGetArgumentIntents"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentIntents(_:_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetArgumentInterleaveFactors","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetArgumentInterleaveFactors","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentInterleaveFactors(_:_:_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetFunctionCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetFunctionCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionCount(_:)/fragments"},{"op":"replace","value":"BNNSGraphGetFunctionNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"BNNSGraphGetFunctionNames"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetFunctionNames(_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetInputNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetInputNames","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputNames(_:_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetInputCount","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetInputCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetInputCount(_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetArgumentPosition","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetArgumentPosition","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetArgumentPosition(_:_:_:)/fragments"},{"op":"replace","value":"BNNSGraphGetOutputNames","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/title"},{"op":"replace","value":[{"text":"BNNSGraphGetOutputNames","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphGetOutputNames(_:_:_:_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}