{
  "abstract": [
    {
      "text": "The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@bnns_graph_compile_options_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bnns_graph_compile_options_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bnns_graph_compile_options_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "bnns_graph_compile_options_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create a default options structure and then call functions such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to set indivual options.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)": {
      "abstract": [
        {
          "text": "Destroys the specified compilation options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsDestroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsDestroy"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsDestroy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsdestroy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)": {
      "abstract": [
        {
          "text": "Returns the option for the compiled graph to include debugging information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetGenerateDebugInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetGenerateDebugInfo"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgetgeneratedebuginfo(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)": {
      "abstract": [
        {
          "text": "Returns the option for the compiled graph to optimize for either size or performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOptimizationPreference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphOptimizationPreference",
          "text": "BNNSGraphOptimizationPreference"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOptimizationPreference"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetOptimizationPreference(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgetoptimizationpreference(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)": {
      "abstract": [
        {
          "text": "Returns the option for the compiled graph’s output file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOutputFD"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOutputFD"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetOutputFD(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgetoutputfd(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)": {
      "abstract": [
        {
          "text": "Returns the option for the compiled graph’s output path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOutputPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetOutputPath"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetOutputPath(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgetoutputpath(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)": {
      "abstract": [
        {
          "text": "Returns the option for the compiled graph to execute on a single thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetTargetSingleThread"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsGetTargetSingleThread"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsGetTargetSingleThread(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsgettargetsinglethread(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()": {
      "abstract": [
        {
          "text": "Returns an allocated compilation options object with default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsMakeDefault"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsMakeDefault"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsMakeDefault()",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionsmakedefault()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)": {
      "abstract": [
        {
          "text": "Sets the option for the compiled graph to include debugging information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetGenerateDebugInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetGenerateDebugInfo"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetgeneratedebuginfo(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)": {
      "abstract": [
        {
          "text": "Sets the option for the compiled graph to optimize for either size or performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOptimizationPreference"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSGraphOptimizationPreference",
          "text": "BNNSGraphOptimizationPreference"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOptimizationPreference"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetoptimizationpreference(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)": {
      "abstract": [
        {
          "text": "Sets the option for graph compilation to generate the graph object directly to the specified file descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOutputFD"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOutputFD"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetOutputFD(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetoutputfd(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)": {
      "abstract": [
        {
          "text": "Sets the option for graph compilation to generate the graph object directly to the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOutputPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetOutputPath"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetOutputPath(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetoutputpath(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)": {
      "abstract": [
        {
          "text": "Sets the option for the compiled graph to execute on a single thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetTargetSingleThread"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetTargetSingleThread"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssettargetsinglethread(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference": {
      "abstract": [
        {
          "text": "Constants that describe the compilation optimization preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphOptimizationPreference"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphOptimizationPreference"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphOptimizationPreference",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphoptimizationpreference"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSTargetSystemGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSTargetSystem",
          "text": "BNNSTargetSystem"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSTargetSystemGeneric"
        }
      ],
      "role": "symbol",
      "title": "BNNSTargetSystemGeneric",
      "type": "topic",
      "url": "/documentation/accelerate/bnnstargetsystemgeneric"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t": {
      "abstract": [
        {
          "text": "The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_options_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_options_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_compile_options_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/data": {
      "abstract": [
        {
          "text": "A pointer to the opaque compilation options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t/data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init()": {
      "abstract": [
        {
          "text": "Creates an empty compilation options structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init(data:size:)": {
      "abstract": [
        {
          "text": "Creates a compilation options structure from the specified opaque compilation options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init(data:size:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(data:size:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t/init(data:size:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/size": {
      "abstract": [
        {
          "text": "The size, in bytes, of the opaque compilation options object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_options_t/size"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-and-querying-compilation-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"
      ],
      "title": "Specifying and querying compilation options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-an-options-structure",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/init(data:size:)"
      ],
      "title": "Initializing an options structure"
    },
    {
      "anchor": "Specifying-an-options-structures-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/data",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/size"
      ],
      "title": "Specifying an options structure’s properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bnns_graph_compile_options_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-an-options-structures-properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/data",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t/size"
              ],
              "title": "Specifying an options structure’s properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-and-querying-compilation-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"
              ],
              "title": "Specifying and querying compilation options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "bnns_graph_compile_options_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetTargetSingleThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetTargetSingleThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/title",
          "value": "BNNSGraphCompileOptionsGetTargetSingleThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetTargetSingleThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/title",
          "value": "bnns_graph_compile_options_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_options_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetOutputPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetOutputPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/title",
          "value": "BNNSGraphOptimizationPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphOptimizationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphOptimizationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/title",
          "value": "BNNSTargetSystemGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTargetSystemGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetGenerateDebugInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetGenerateDebugInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/title",
          "value": "BNNSGraphCompileOptionsGetGenerateDebugInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetGenerateDebugInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/title",
          "value": "BNNSGraphCompileOptionsGetOutputFD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetOutputFD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/title",
          "value": "BNNSGraphCompileOptionsGetOutputPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetOutputPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetOutputFD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetOutputFD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/title",
          "value": "BNNSGraphCompileOptionsGetOptimizationPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsGetOptimizationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetOptimizationPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetOptimizationPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/title",
          "value": "BNNSGraphCompileOptionsDestroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsDestroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/title",
          "value": "BNNSGraphCompileOptionsMakeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsMakeDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns_graph_compile_options_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnns_graph_compile_options_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
