{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionReLU6"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSActivationFunction@BNNSActivationFunctionReLU6",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSActivationFunctionReLU6"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSActivationFunction",
        "text": "BNNSActivationFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSActivationFunctionReLU6"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSActivationFunctionReLU6"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionReLU6"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSActivationFunction",
              "text": "BNNSActivationFunction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction": {
      "abstract": [
        {
          "text": "Constants that describe activation functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp": {
      "abstract": [
        {
          "text": "An activation function that returns its input clamped to the specified range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClamp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionClamp",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionclamp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate": {
      "abstract": [
        {
          "text": "An activation function that returns an arithmetic shift, preserving sign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionIntegerLinearSaturate"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionIntegerLinearSaturate",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/bnnsactivationfunctionintegerlinearsaturate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunction/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionAbs": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionAbs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionAbs",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSActivationFunctionAbs",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionabs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU": {
      "abstract": [
        {
          "text": "An activation function that evaluates the continuously differentiable exponential linear units (CELU) on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionCELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionCELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionCELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctioncelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear": {
      "abstract": [
        {
          "text": "An activation function that returns its input clamped to beta when that is greater than or equal to zero, otherwise it returns its input multiplied by alpha clamped to beta.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionClampedLeakyRectifiedLinear",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionclampedleakyrectifiedlinear"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU": {
      "abstract": [
        {
          "text": "An activation function that evaluates the exponential linear units (ELU) on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionErf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionErf"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionErf",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionerf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELU"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELU",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongelu"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation": {
      "abstract": [
        {
          "text": "An activation function that evaluates the Gaussian error linear units (GELU) approximation on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximation",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2": {
      "abstract": [
        {
          "text": "An activation function that provides a fast evaluation of the Gaussian error linear units (GELU) approximation on its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximation2"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximation2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximation2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximationSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGELUApproximationSigmoid"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGELUApproximationSigmoid",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongeluapproximationsigmoid"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel": {
      "abstract": [
        {
          "text": "An activation function that returns random numbers from the Gumbel distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbel"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGumbel",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongumbel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax": {
      "abstract": [
        {
          "text": "An activation function that returns random numbers from the Gumbel distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbelMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionGumbelMax"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionGumbelMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctiongumbelmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink": {
      "abstract": [
        {
          "text": "An activation function that returns zero when the absolute input is less than alpha, otherwise it returns its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardShrink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardShrink"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardShrink",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardshrink"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid": {
      "abstract": [
        {
          "text": "An activation function that returns the hard sigmoid function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSigmoid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSigmoid"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardSigmoid",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardsigmoid"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish": {
      "abstract": [
        {
          "text": "An activation function that returns the hard swish function of its input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSwish"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionHardSwish"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionHardSwish",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionhardswish"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionReLU6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionReLU6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSActivationFunction",
          "text": "BNNSActivationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionReLU6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSActivationFunctionReLU6"
        }
      ],
      "role": "symbol",
      "title": "BNNSActivationFunctionReLU6",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsactivationfunctionrelu6"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Raw-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionAbs",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink"
      ],
      "title": "Raw Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.4",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSActivationFunctionReLU6"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionReLU6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Raw-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionCELU",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionClamp",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionClampedLeakyRectifiedLinear",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionELU",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionErf",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELU",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximation2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGELUApproximationSigmoid",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbel",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionGumbelMax",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardShrink",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSigmoid",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunctionHardSwish",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSActivationFunction/BNNSActivationFunctionIntegerLinearSaturate"
              ],
              "title": "Raw Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSActivationFunctionReLU6"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbel/title",
          "value": "BNNSActivationFunctionGumbel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGumbel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionELU/title",
          "value": "BNNSActivationFunctionELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/title",
          "value": "BNNSActivationFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSigmoid/title",
          "value": "BNNSActivationFunctionHardSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbelMax/title",
          "value": "BNNSActivationFunctionGumbelMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGumbelMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGumbelMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionCELU/title",
          "value": "BNNSActivationFunctionCELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionCELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionCELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximationSigmoid/title",
          "value": "BNNSActivationFunctionGELUApproximationSigmoid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximationSigmoid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximationSigmoid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardShrink/title",
          "value": "BNNSActivationFunctionHardShrink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardShrink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardShrink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionErf/title",
          "value": "BNNSActivationFunctionErf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionErf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionErf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation2/title",
          "value": "BNNSActivationFunctionGELUApproximation2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximation2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSwish/title",
          "value": "BNNSActivationFunctionHardSwish"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionHardSwish/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionHardSwish"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionClampedLeakyRectifiedLinear/title",
          "value": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionClampedLeakyRectifiedLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionClampedLeakyRectifiedLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionReLU6/title",
          "value": "BNNSActivationFunctionReLU6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionReLU6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionReLU6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELU/title",
          "value": "BNNSActivationFunctionGELU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation/title",
          "value": "BNNSActivationFunctionGELUApproximation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSActivationFunctionGELUApproximation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSActivationFunctionGELUApproximation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsactivationfunctionrelu6"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsactivationfunctionrelu6"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
