{
  "abstract": [
    {
      "text": "Additional user-defined logging argument for message-logging callbacks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@bnns_user_message_data_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bnns_user_message_data_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bnns_user_message_data_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "bnns_user_message_data_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Specifies a customized callback function that reports compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@bnns_graph_compile_message_fn_t",
          "text": "bnns_graph_compile_message_fn_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_user_message_data_t",
          "text": "bnns_user_message_data_t"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogcallback(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_compile_options_t",
          "text": "bnns_graph_compile_options_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphCompileOptionsSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcompileoptionssetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)": {
      "abstract": [
        {
          "text": "Sets mask for log messages that are logged (either via ",
          "type": "text"
        },
        {
          "code": "os_log",
          "type": "codeVoice"
        },
        {
          "text": " or the user specified callback)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@bnns_graph_context_t",
          "text": "bnns_graph_context_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphContextSetMessageLogMask"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphContextSetMessageLogMask(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphcontextsetmessagelogmask(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel": {
      "abstract": [
        {
          "text": "Constants that specify the mask for compile-time messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSGraphMessageLevel"
        }
      ],
      "role": "symbol",
      "title": "BNNSGraphMessageLevel",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsgraphmessagelevel"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t": {
      "abstract": [
        {
          "text": "The graph compile-message logging callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_compile_message_fn_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_compile_message_fn_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_compile_message_fn_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t": {
      "abstract": [
        {
          "text": "Additional user-defined logging argument for message-logging callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_user_message_data_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_user_message_data_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/data": {
      "abstract": [
        {
          "text": "A pointer to the additional logging data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t/data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init(size:data:)": {
      "abstract": [
        {
          "text": "Creates a logging argument structure from the pointer to the additional logging data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init(size:data:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(size:data:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t/init(size:data:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/size": {
      "abstract": [
        {
          "text": "The size of the additional logging data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_user_message_data_t/size"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-graphs-compile-time-message-callback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t"
      ],
      "title": "Specifying a graph’s compile-time message callback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/init(size:data:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/data",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/size"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bnns_user_message_data_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/data",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_user_message_data_t/size"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-graphs-compile-time-message-callback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextSetMessageLogMask(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphMessageLevel",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_message_fn_t"
              ],
              "title": "Specifying a graph’s compile-time message callback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "bnns_user_message_data_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/title",
          "value": "bnns_user_message_data_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_user_message_data_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/title",
          "value": "BNNSGraphContextSetMessageLogMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextSetMessageLogMask(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphContextSetMessageLogMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/title",
          "value": "BNNSGraphCompileOptionsSetMessageLogCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetMessageLogCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphCompileOptionsSetMessageLogCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_user_message_data_t~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/title",
          "value": "bnns_graph_compile_message_fn_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_message_fn_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_compile_message_fn_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/title",
          "value": "BNNSGraphMessageLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphMessageLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSGraphMessageLevel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns_user_message_data_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnns_user_message_data_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
