{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"metadata":{"externalID":"c:@EA@BNNSGraphArgumentIntent@BNNSGraphArgumentIntentOut","role":"symbol","platforms":[{"introducedAt":"18.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"18.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"18.0","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"15.0","name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"18.0","name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"2.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"11.0","name":"watchOS","unavailable":false,"deprecated":false,"beta":false}],"title":"BNNSGraphArgumentIntentOut","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","text":"BNNSGraphArgumentIntent","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"Accelerate"}],"roleHeading":"Global Variable"},"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsgraphargumentintentout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsgraphargumentintentout"]}],"abstract":[{"type":"text","text":"A constant that specifies the argument provides an output tensor."}],"seeAlsoSections":[{"generated":true,"anchor":"Argument-intents","title":"Argument intents","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSGraphArgumentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}],"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntentIn"}],"url":"/documentation/accelerate/bnnsgraphargumentintentin","abstract":[{"text":"A constant that specifies the argument provides an input tensor.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntentIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","type":"topic","title":"BNNSGraphArgumentIntentIn"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut":{"kind":"symbol","navigatorTitle":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}],"url":"/documentation/accelerate/bnnsgraphargumentintentout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A constant that specifies the argument provides an output tensor."}],"type":"topic","title":"BNNSGraphArgumentIntentOut","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentOut","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)":{"type":"topic","url":"/documentation/accelerate/bnnsgraphargumentintent/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(_:)","title":"init(_:)","kind":"symbol","role":"symbol","abstract":[{"text":"Creates a new instance.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"url":"/documentation/accelerate/bnnsgraphargumentintent","abstract":[{"text":"Constants that describe argument intents.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent","type":"topic","title":"BNNSGraphArgumentIntent"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue":{"kind":"symbol","url":"/documentation/accelerate/bnnsgraphargumentintent/rawvalue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The corresponding value of the raw type."}],"type":"topic","title":"rawValue","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/rawValue","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)":{"kind":"symbol","url":"/documentation/accelerate/bnnsgraphargumentintent/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a new instance with the specified raw value."}],"type":"topic","title":"init(rawValue:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent/init(rawValue:)","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut":{"type":"topic","url":"/documentation/accelerate/bnnsgraphargumentintentinout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BNNSGraphArgumentIntent","preciseIdentifier":"c:@EA@BNNSGraphArgumentIntent"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut","title":"BNNSGraphArgumentIntentInOut","kind":"symbol","role":"symbol","abstract":[{"text":"A constant that specifies the argument is an in-place input and output tensor.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"18.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"18.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"introducedAt":"18.0","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"15.0","deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"introducedAt":"18.0","deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"introducedAt":"2.0","deprecated":false,"beta":false,"name":"visionOS","unavailable":false},{"introducedAt":"11.0","deprecated":false,"beta":false,"name":"watchOS","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphArgumentIntentOut","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntent"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentIn","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphArgumentIntentInOut"],"title":"Argument intents","anchor":"Argument-intents"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"BNNSGraphArgumentIntentOut","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"BNNSGraphArgumentIntentIn","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentIn/title"},{"value":[{"text":"BNNSGraphArgumentIntentIn","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentIn/fragments"},{"value":"BNNSGraphArgumentIntentOut","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentOut/title"},{"value":[{"kind":"identifier","text":"BNNSGraphArgumentIntentOut"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentOut/fragments"},{"value":"BNNSGraphArgumentIntent","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/title"},{"value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/fragments"},{"value":[{"text":"BNNSGraphArgumentIntent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntent/navigatorTitle"},{"value":"BNNSGraphArgumentIntentInOut","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentInOut/title"},{"value":[{"kind":"identifier","text":"BNNSGraphArgumentIntentInOut"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphArgumentIntentInOut/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}