{
  "abstract": [
    {
      "text": "A reduction function that computes the sum of the natural logarithm of all values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumLog"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSReduceFunction@BNNSReduceFunctionSumLog",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSReduceFunctionSumLog"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSReduceFunction",
        "text": "BNNSReduceFunction"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSReduceFunctionSumLog"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSReduceFunctionSumLog"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionSumLog"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSReduceFunction",
              "text": "BNNSReduceFunction"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction": {
      "abstract": [
        {
          "text": "Constants that describe reduction functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunction/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunction/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunction/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAll": {
      "abstract": [
        {
          "text": "An alias of the logical AND reduction function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionAll"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionAll",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionall"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAny": {
      "abstract": [
        {
          "text": "An alias of the logical OR reduction function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionAny"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionAny",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionany"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMax": {
      "abstract": [
        {
          "text": "A reduction function that computes the index of the maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionArgMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionArgMax"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionArgMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionargmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMin": {
      "abstract": [
        {
          "text": "A reduction function that computes the index of the minimum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionArgMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionArgMin"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionArgMin",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionargmin"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL1Norm": {
      "abstract": [
        {
          "text": "A reduction function that computes the sum of the absolute value of each element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionL1Norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL1Norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionL1Norm"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionL1Norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionl1norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL2Norm": {
      "abstract": [
        {
          "text": "A reduction function that computes the Euclidean norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionL2Norm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL2Norm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionL2Norm"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionL2Norm",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionl2norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogSum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogSum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogSum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogSum"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionLogSum",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionlogsum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalAnd": {
      "abstract": [
        {
          "text": "A reduction function that reduces a tensor to true if all elements are true.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogicalAnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalAnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogicalAnd"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionLogicalAnd",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionlogicaland"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalOr": {
      "abstract": [
        {
          "text": "A reduction function that reduces a tensor to true if any element is true.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogicalOr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalOr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionLogicalOr"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionLogicalOr",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionlogicalor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMax": {
      "abstract": [
        {
          "text": "A reduction function that computes the maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMax"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionMax",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionmax"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMean": {
      "abstract": [
        {
          "text": "A reduction function that computes the mean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMean"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionMean",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionmean"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMeanNonZero": {
      "abstract": [
        {
          "text": "A reduction function that computes the mean value of nonzero elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMeanNonZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMeanNonZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMeanNonZero"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionMeanNonZero",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionmeannonzero"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMin": {
      "abstract": [
        {
          "text": "A reduction function that computes the minimum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionMin"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionMin",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionmin"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSum": {
      "abstract": [
        {
          "text": "A reduction function that computes the sum of all values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSum"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionSum",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionsum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumLog": {
      "abstract": [
        {
          "text": "A reduction function that computes the sum of the natural logarithm of all values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSumLog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSumLog"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionSumLog",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionsumlog"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumSquare": {
      "abstract": [
        {
          "text": "A reduction function that computes the sum of the square of all values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSumSquare"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSReduceFunction",
          "text": "BNNSReduceFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSReduceFunctionSumSquare"
        }
      ],
      "role": "symbol",
      "title": "BNNSReduceFunctionSumSquare",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsreducefunctionsumsquare"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reduction-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMax",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMin",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL1Norm",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalAnd",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAll",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalOr",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogSum",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAny",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMax",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMean",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMeanNonZero",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMin"
      ],
      "title": "Reduction Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSReduceFunctionSumLog"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionSumLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reduction-Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMax",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionArgMin",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL1Norm",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalAnd",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAll",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogicalOr",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionLogSum",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionAny",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMax",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMean",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMeanNonZero",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionMin",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSum",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionSumSquare",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSReduceFunctionL2Norm"
              ],
              "title": "Reduction Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSReduceFunctionSumLog"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogSum/title",
          "value": "BNNSReduceFunctionLogSum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogSum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionLogSum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogicalAnd/title",
          "value": "BNNSReduceFunctionLogicalAnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogicalAnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionLogicalAnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMeanNonZero/title",
          "value": "BNNSReduceFunctionMeanNonZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMeanNonZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionMeanNonZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSumSquare/title",
          "value": "BNNSReduceFunctionSumSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSumSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionSumSquare"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionAny/title",
          "value": "BNNSReduceFunctionAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSum/title",
          "value": "BNNSReduceFunctionSum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionSum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMin/title",
          "value": "BNNSReduceFunctionMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMean/title",
          "value": "BNNSReduceFunctionMean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionMean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionL1Norm/title",
          "value": "BNNSReduceFunctionL1Norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionL1Norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionL1Norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionL2Norm/title",
          "value": "BNNSReduceFunctionL2Norm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionL2Norm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionL2Norm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSumLog/title",
          "value": "BNNSReduceFunctionSumLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionSumLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionSumLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionArgMax/title",
          "value": "BNNSReduceFunctionArgMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionArgMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionArgMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogicalOr/title",
          "value": "BNNSReduceFunctionLogicalOr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionLogicalOr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionLogicalOr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMax/title",
          "value": "BNNSReduceFunctionMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionAll/title",
          "value": "BNNSReduceFunctionAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionArgMin/title",
          "value": "BNNSReduceFunctionArgMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunctionArgMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunctionArgMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunction/title",
          "value": "BNNSReduceFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSReduceFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSReduceFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsreducefunctionsumlog"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsreducefunctionsumlog"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
