{"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSImageStackDescriptor"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An image stack is a sequence of images with the same width and height. Each image in the sequence is called a channel."},{"type":"text","text":" "},{"type":"text","text":"For example, a RGB image will be stored as three separate channels. A pixel has only one scalar value, stored using the type"},{"type":"text","text":" "},{"type":"text","text":"described by "},{"type":"text","text":"data_type"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"Pixel ","type":"text"},{"text":"P(c,x,y)","type":"text"},{"text":" at position ","type":"text"},{"text":"(x,y)","type":"text"},{"text":" in channel ","type":"text"},{"text":"c","type":"text"},{"text":" is stored in","type":"text"},{"text":" ","type":"text"},{"text":"data[x + row_stride * y + image_stride * c]","type":"text"},{"text":", with","type":"text"},{"text":" ","type":"text"},{"text":"x=0..width-1","type":"text"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"y=0..height-1","type":"text"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"c=0..channels-1","type":"text"},{"text":". ","type":"text"},{"text":"row_stride ≥ width","type":"text"},{"text":", ","type":"text"},{"text":"image_stride ≥ row_stride * height","type":"text"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Int"},{"type":"text","text":" types are converted to floating point using float Y = DATA_SCALE * (float)X + DATA_BIAS, and back to integer using Int"},{"type":"text","text":" X = convert_and_saturate(Y / DATA_SCALE - DATA_BIAS)"}]}],"kind":"content"}],"seeAlsoSections":[{"title":"Structures","anchor":"Structures","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"],"generated":true}],"sections":[],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init()","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:data_scale:data_bias:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/channels","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_bias","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_scale","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_type","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/height","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/image_stride","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/row_stride","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships","type":"conformsTo"}],"kind":"symbol","metadata":{"platforms":[{"message":"BNNS switched to new Layer Parameters data structures","name":"iOS","deprecated":false,"deprecatedAt":"14.0","beta":false,"unavailable":false,"introducedAt":"10.0"},{"message":"BNNS switched to new Layer Parameters data structures","name":"iPadOS","deprecated":false,"deprecatedAt":"14.0","beta":false,"unavailable":false,"introducedAt":"10.0"},{"message":"BNNS switched to new Layer Parameters data structures","name":"Mac Catalyst","deprecated":false,"deprecatedAt":"14.0","beta":false,"unavailable":false,"introducedAt":"13.1"},{"message":"BNNS switched to new Layer Parameters data structures","name":"macOS","deprecated":false,"deprecatedAt":"11.0","beta":false,"unavailable":false,"introducedAt":"10.12"},{"message":"BNNS switched to new Layer Parameters data structures","name":"tvOS","deprecated":false,"deprecatedAt":"14.0","beta":false,"unavailable":false,"introducedAt":"10.0"},{"message":"BNNS switched to new Layer Parameters data structures","name":"visionOS","deprecated":false,"deprecatedAt":"1.0","beta":false,"unavailable":false,"introducedAt":"1.0"},{"message":"BNNS switched to new Layer Parameters data structures","name":"watchOS","deprecated":false,"deprecatedAt":"7.0","beta":false,"unavailable":false,"introducedAt":"3.0"}],"title":"BNNSImageStackDescriptor","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"role":"symbol","externalID":"c:@SA@BNNSImageStackDescriptor","navigatorTitle":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"symbolKind":"struct","modules":[{"name":"Accelerate"}],"roleHeading":"Structure"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"BNNS switched to new Layer Parameters data structures"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/accelerate/bnnsimagestackdescriptor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/accelerate/bnnsimagestackdescriptor"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/image_stride":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image_stride"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/image_stride","abstract":[],"navigatorTitle":[{"text":"image_stride","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/image_stride","title":"image_stride","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init()":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init()","abstract":[],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/init()","title":"init()","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSSparsityType"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSSparsityType"}],"title":"BNNSSparsityType","url":"/documentation/accelerate/bnnssparsitytype","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","abstract":[]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/row_stride":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"row_stride"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/row_stride","abstract":[],"navigatorTitle":[{"text":"row_stride","kind":"identifier"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/row_stride","title":"row_stride","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"row_stride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"image_stride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data_type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSDataType","text":"BNNSDataType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:)","abstract":[],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/init(width:height:channels:row_stride:image_stride:data_type:)","title":"init(width:height:channels:row_stride:image_stride:data_type:)","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/height":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/height","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"height"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/height","title":"height","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"BNNSImageStackDescriptor","url":"/documentation/accelerate/bnnsimagestackdescriptor","navigatorTitle":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor","role":"symbol","abstract":[],"deprecated":true},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t":{"type":"topic","abstract":[{"text":"Describes data associated with an input or output argument","type":"text"}],"title":"bnns_graph_argument_t","kind":"symbol","navigatorTitle":[{"text":"bnns_graph_argument_t","kind":"identifier"}],"url":"/documentation/accelerate/bnns_graph_argument_t","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bnns_graph_argument_t","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"kind":"symbol","abstract":[{"text":"","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","url":"/documentation/accelerate/bnnssparsityparameters","navigatorTitle":[{"kind":"identifier","text":"BNNSSparsityParameters"}],"title":"BNNSSparsityParameters","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSSparsityParameters"}],"role":"symbol","kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/channels":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"channels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/channels","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"channels"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/channels","title":"channels","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:data_scale:data_bias:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"channels","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"row_stride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"image_stride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data_type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@EA@BNNSDataType","text":"BNNSDataType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data_scale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data_bias","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/init(width:height:channels:row_stride:image_stride:data_type:data_scale:data_bias:)","abstract":[],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/init(width:height:channels:row_stride:image_stride:data_type:data_scale:data_bias:)","title":"init(width:height:channels:row_stride:image_stride:data_type:data_scale:data_bias:)","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_type":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data_type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BNNSDataType","kind":"typeIdentifier","preciseIdentifier":"c:@EA@BNNSDataType"}],"kind":"symbol","type":"topic","title":"data_type","url":"/documentation/accelerate/bnnsimagestackdescriptor/data_type","navigatorTitle":[{"text":"data_type","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_type","role":"symbol","abstract":[],"deprecated":true},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem":{"type":"topic","navigatorTitle":[{"text":"BNNSTargetSystem","kind":"identifier"}],"kind":"symbol","url":"/documentation/accelerate/bnnstargetsystem","title":"BNNSTargetSystem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTargetSystem","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem","abstract":[],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_scale":{"deprecated":true,"type":"topic","kind":"symbol","title":"data_scale","abstract":[],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_scale","url":"/documentation/accelerate/bnnsimagestackdescriptor/data_scale","navigatorTitle":[{"kind":"identifier","text":"data_scale"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"data_scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_bias":{"title":"data_bias","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data_bias","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"data_bias","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_bias","role":"symbol","type":"topic","abstract":[],"deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/data_bias","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","title":"Sendable","kind":"symbol","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"width"}],"kind":"symbol","role":"symbol","deprecated":true,"url":"/documentation/accelerate/bnnsimagestackdescriptor/width","title":"width","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType":{"abstract":[{"type":"text","text":"BNNS Data Types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSDataType"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSDataType"}],"type":"topic","url":"/documentation/accelerate/bnnsdatatype","title":"BNNSDataType"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor":{"title":"BNNSVectorDescriptor","navigatorTitle":[{"kind":"identifier","text":"BNNSVectorDescriptor"}],"type":"topic","kind":"symbol","url":"/documentation/accelerate/bnnsvectordescriptor","deprecated":true,"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSVectorDescriptor","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"deprecated":false},{"beta":false,"name":"watchOS","unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Structure"},{"path":"/metadata/title","op":"replace","value":"BNNSImageStackDescriptor"},{"path":"/metadata/symbolKind","op":"replace","value":"struct"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"BNNSImageStackDescriptor","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"BNNSImageStackDescriptor"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]}},{"path":"/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/channels","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_bias","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_scale","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/data_type","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/height","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/image_stride","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/row_stride","doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor/width"]}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters","doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem","doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"],"title":"Structures","anchor":"Structures"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"BNNSImageStackDescriptor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":[],"op":"replace","path":"/deprecationSummary"},{"value":"image_stride","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1image_stride/title"},{"value":[{"text":"image_stride","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1image_stride/fragments"},{"value":"BNNSSparsityType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/title"},{"value":[{"text":"BNNSSparsityType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/fragments"},{"value":[{"kind":"identifier","text":"BNNSSparsityType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/navigatorTitle"},{"value":"row_stride","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1row_stride/title"},{"value":[{"kind":"identifier","text":"row_stride"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1row_stride/fragments"},{"value":"height","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1height/title"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1height/fragments"},{"value":"BNNSImageStackDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/title"},{"value":[{"kind":"identifier","text":"BNNSImageStackDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/fragments"},{"value":[{"kind":"identifier","text":"BNNSImageStackDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/navigatorTitle"},{"value":"bnns_graph_argument_t","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/title"},{"value":[{"text":"bnns_graph_argument_t","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/fragments"},{"value":[{"kind":"identifier","text":"bnns_graph_argument_t"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/navigatorTitle"},{"value":"BNNSSparsityParameters","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/title"},{"value":[{"kind":"identifier","text":"BNNSSparsityParameters"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/fragments"},{"value":[{"text":"BNNSSparsityParameters","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/navigatorTitle"},{"value":"channels","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1channels/title"},{"value":[{"kind":"identifier","text":"channels"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1channels/fragments"},{"value":"data_type","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_type/title"},{"value":[{"kind":"identifier","text":"data_type"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_type/fragments"},{"value":"BNNSTargetSystem","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/title"},{"value":[{"text":"BNNSTargetSystem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/fragments"},{"value":[{"kind":"identifier","text":"BNNSTargetSystem"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/navigatorTitle"},{"value":"data_scale","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_scale/title"},{"value":[{"text":"data_scale","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_scale/fragments"},{"value":"data_bias","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_bias/title"},{"value":[{"text":"data_bias","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1data_bias/fragments"},{"value":"width","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1width/title"},{"value":[{"text":"width","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor~1width/fragments"},{"value":"BNNSDataType","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title"},{"value":[{"text":"BNNSDataType","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments"},{"value":[{"kind":"identifier","text":"BNNSDataType"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle"},{"value":"BNNSVectorDescriptor","op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/title"},{"value":[{"kind":"identifier","text":"BNNSVectorDescriptor"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/fragments"},{"value":[{"text":"BNNSVectorDescriptor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}