{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSDataType@BNNSDataTypeUInt4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSDataTypeUInt4"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BNNSDataType",
        "text": "BNNSDataType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSDataTypeUInt4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BNNSDataTypeUInt4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt4"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BNNSDataType",
              "text": "BNNSDataType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Common bit to floating point types, this constant is not a valid type",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "16-bit half precision floating point",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "32-bit single precision floating point",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "16-bit brain floating Point",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Common bit to signed integer types, this constant is not a valid type",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "8-bit signed integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "16-bit signed integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "32-bit signed integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "64-bit signed integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Common bit to unsigned integer types, this constant is not a valid type",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "8-bit unsigned integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "16-bit unsigned integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "32-bit unsigned integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "64-bit unsigned integer",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Common bit to indexed floating point types, this constant is not a valid type",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "2-bit unsigned indices into a floating point conversion table (4 values)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "4-bit unsigned indices into a floating point conversion table (16 values)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "8-bit unsigned indices into a floating point conversion table (256 values)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Common bit to miscellaneous types, this constant is not a valid type",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "bool value",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType": {
      "abstract": [
        {
          "text": "BNNS Data Types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBFloat16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBFloat16"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeBFloat16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypebfloat16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBoolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBoolean"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeBoolean",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeboolean"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt64"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt64",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint64"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeMiscellaneousBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeMiscellaneousBit"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeMiscellaneousBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypemiscellaneousbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt3"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt3",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt6"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt6",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt64"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt64",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint64"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSDataTypeUInt4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64"
              ],
              "title": "Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BNNSDataTypeUInt4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt4/title",
          "value": "BNNSDataTypeInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBFloat16/title",
          "value": "BNNSDataTypeBFloat16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBFloat16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeBFloat16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title",
          "value": "BNNSDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt1/title",
          "value": "BNNSDataTypeInt1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt4/title",
          "value": "BNNSDataTypeUInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeMiscellaneousBit/title",
          "value": "BNNSDataTypeMiscellaneousBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeMiscellaneousBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeMiscellaneousBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt64/title",
          "value": "BNNSDataTypeInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt2/title",
          "value": "BNNSDataTypeInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt2/title",
          "value": "BNNSDataTypeUInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBoolean/title",
          "value": "BNNSDataTypeBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBoolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt3/title",
          "value": "BNNSDataTypeUInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt64/title",
          "value": "BNNSDataTypeUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt1/title",
          "value": "BNNSDataTypeUInt1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed1/title",
          "value": "BNNSDataTypeIndexed1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed4/title",
          "value": "BNNSDataTypeIndexed4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed2/title",
          "value": "BNNSDataTypeIndexed2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt6/title",
          "value": "BNNSDataTypeUInt6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt6"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsdatatypeuint4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsdatatypeuint4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
