{
  "abstract": [
    {
      "text": "BNNS Data Types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSDataType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSDataType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSDataType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSDataType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType": {
      "abstract": [
        {
          "text": "BNNS Data Types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataType"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeFloat16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat16",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeFloat16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypefloat16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeFloat32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat32",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeFloat32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypefloat32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloatBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeFloatBit"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloatBit",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeFloatBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypefloatbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexed8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexed8",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeIndexed8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeindexed8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexedBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexedBit"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexedBit",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeIndexedBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeindexedbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt16",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeInt16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeint16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt32",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeInt32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeint32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt8",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeInt8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeint8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIntBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIntBit"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIntBit",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeIntBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeintbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt16",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeUInt16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeuint16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt32",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeUInt32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeuint32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt8",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeUInt8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeuint8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUIntBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUIntBit"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUIntBit",
      "kind": "symbol",
      "role": "symbol",
      "title": "BNNSDataTypeUIntBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/bnnsdatatypeuintbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float",
      "kind": "symbol",
      "role": "symbol",
      "title": "float",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "float16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float16",
      "kind": "symbol",
      "role": "symbol",
      "title": "float16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/float16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/indexed8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexed8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/indexed8",
      "kind": "symbol",
      "role": "symbol",
      "title": "indexed8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/indexed8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int16",
      "kind": "symbol",
      "role": "symbol",
      "title": "int16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/int16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int32",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/int32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int8",
      "kind": "symbol",
      "role": "symbol",
      "title": "int8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/int8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint16",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/uint16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint32": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint32",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/uint32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uint8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint8",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint8",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatype/uint8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBFloat16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBFloat16"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeBFloat16",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypebfloat16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBoolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeBoolean"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeBoolean",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeboolean"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeIndexed4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeIndexed4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeindexed4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeInt64"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeInt64",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeint64"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeMiscellaneousBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeMiscellaneousBit"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeMiscellaneousBit",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypemiscellaneousbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt1"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt1",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt2"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt2",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt3"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt3",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt4"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt4",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt6"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt6",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSDataType",
          "text": "BNNSDataType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDataTypeUInt64"
        }
      ],
      "role": "symbol",
      "title": "BNNSDataTypeUInt64",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdatatypeuint64"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSImageStackDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSImageStackDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSImageStackDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsimagestackdescriptor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSSparsityParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSSparsityParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSSparsityParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnssparsityparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSSparsityType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSSparsityType"
        }
      ],
      "role": "symbol",
      "title": "BNNSSparsityType",
      "type": "topic",
      "url": "/documentation/accelerate/bnnssparsitytype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSTargetSystem"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSTargetSystem"
        }
      ],
      "role": "symbol",
      "title": "BNNSTargetSystem",
      "type": "topic",
      "url": "/documentation/accelerate/bnnstargetsystem"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSVectorDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSVectorDescriptor"
        }
      ],
      "role": "symbol",
      "title": "BNNSVectorDescriptor",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsvectordescriptor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t": {
      "abstract": [
        {
          "text": "Describes data associated with an input or output argument",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bnns_graph_argument_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bnns_graph_argument_t"
        }
      ],
      "role": "symbol",
      "title": "bnns_graph_argument_t",
      "type": "topic",
      "url": "/documentation/accelerate/bnns_graph_argument_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
        "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64"
      ],
      "title": "Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/rawValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/float16",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/indexed8",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int16",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int32",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/int8",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint16",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint32",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/uint8"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSDataType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBFloat16",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeBoolean",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeIndexed4",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt4",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeInt64",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeMiscellaneousBit",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt1",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt2",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt3",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt4",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt6",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataTypeUInt64"
              ],
              "title": "Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat16",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloat32",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeFloatBit",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexed8",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIndexedBit",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt16",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt32",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeInt8",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeIntBit",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt16",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt32",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUInt8",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDataType/BNNSDataTypeUIntBit"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityParameters",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSSparsityType",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystem",
                "doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_argument_t",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSImageStackDescriptor",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSVectorDescriptor"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSDataType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBFloat16/title",
          "value": "BNNSDataTypeBFloat16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBFloat16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeBFloat16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt6/title",
          "value": "BNNSDataTypeUInt6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/title",
          "value": "BNNSSparsityType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt64/title",
          "value": "BNNSDataTypeUInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt2/title",
          "value": "BNNSDataTypeUInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed4/title",
          "value": "BNNSDataTypeIndexed4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt4/title",
          "value": "BNNSDataTypeUInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeMiscellaneousBit/title",
          "value": "BNNSDataTypeMiscellaneousBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeMiscellaneousBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeMiscellaneousBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/title",
          "value": "BNNSVectorDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSVectorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSVectorDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSVectorDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt4/title",
          "value": "BNNSDataTypeInt4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed2/title",
          "value": "BNNSDataTypeIndexed2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/title",
          "value": "BNNSSparsityParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSSparsityParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSSparsityParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt1/title",
          "value": "BNNSDataTypeUInt1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/title",
          "value": "BNNSTargetSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTargetSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSTargetSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/title",
          "value": "bnns_graph_argument_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_argument_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "bnns_graph_argument_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/title",
          "value": "BNNSDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt1/title",
          "value": "BNNSDataTypeInt1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/title",
          "value": "BNNSImageStackDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSImageStackDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSImageStackDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSImageStackDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt2/title",
          "value": "BNNSDataTypeInt2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed1/title",
          "value": "BNNSDataTypeIndexed1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeIndexed1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeIndexed1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt64/title",
          "value": "BNNSDataTypeInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBoolean/title",
          "value": "BNNSDataTypeBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeBoolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt3/title",
          "value": "BNNSDataTypeUInt3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDataTypeUInt3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDataTypeUInt3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsdatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsdatatype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
