{"variants":[{"paths":["/documentation/accelerate/bnnstensorgetallocationsize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnstensorgetallocationsize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSTensorGetAllocationSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tensor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@SA@BNNSTensor","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor","text":"BNNSTensor"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The tensor.","type":"text"}],"type":"paragraph"}],"name":"tensor"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The minimum allocation size, in bytes, of the specified tensor.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Returns the minimum allocation size, in bytes, of the specified tensor."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Function","platforms":[{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"15.0","beta":false,"unavailable":false,"name":"macOS"},{"deprecated":false,"introducedAt":"18.0","beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false,"name":"visionOS"},{"deprecated":false,"introducedAt":"11.0","beta":false,"unavailable":false,"name":"watchOS"}],"externalID":"c:@F@BNNSTensorGetAllocationSize","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSTensorGetAllocationSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"BNNSTensor","preciseIdentifier":"c:@SA@BNNSTensor"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"modules":[{"name":"Accelerate"}],"title":"BNNSTensorGetAllocationSize(_:)","role":"symbol","symbolKind":"func","navigatorTitle":[{"kind":"identifier","text":"BNNSTensorGetAllocationSize"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensorGetAllocationSize(_:)"},"seeAlsoSections":[{"generated":true,"anchor":"Specifying-and-querying-a-tensors-properties","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetTensor(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphTensorFillStrides(_:_:_:_:)"],"title":"Specifying and querying a tensor’s properties"}],"references":{"doc://com.externally.resolved.symbol/c:@T@size_t":{"abstract":[{"type":"text","text":""}],"title":"size_t","type":"topic","kind":"symbol","url":"/documentation/kernel/size_t","identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor":{"title":"BNNSTensor","url":"/documentation/accelerate/bnnstensor","abstract":[{"type":"text","text":"A structure that describes the shape, stride, data type, and, optionally, the memory location of an n-dimensional array."}],"type":"topic","navigatorTitle":[{"text":"BNNSTensor","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTensor","kind":"identifier"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensorGetAllocationSize(_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSTensorGetAllocationSize"}],"role":"symbol","title":"BNNSTensorGetAllocationSize(_:)","type":"topic","kind":"symbol","abstract":[{"text":"Returns the minimum allocation size, in bytes, of the specified tensor.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTensorGetAllocationSize","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@SA@BNNSTensor","kind":"typeIdentifier","text":"BNNSTensor"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensorGetAllocationSize(_:)","url":"/documentation/accelerate/bnnstensorgetallocationsize(_:)"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetTensor(_:_:_:_:_:)":{"navigatorTitle":[{"text":"BNNSGraphContextGetTensor","kind":"identifier"}],"role":"symbol","title":"BNNSGraphContextGetTensor(_:_:_:_:_:)","type":"topic","kind":"symbol","abstract":[{"text":"Sets the properties of a tensor for the specified function argument.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphContextGetTensor"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_context_t","kind":"typeIdentifier","text":"bnns_graph_context_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?, "},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"CChar","kind":"typeIdentifier","preciseIdentifier":"s:s5CChara"},{"text":">, ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"BNNSTensor","kind":"typeIdentifier","preciseIdentifier":"c:@SA@BNNSTensor"},{"text":">) -> ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetTensor(_:_:_:_:_:)","url":"/documentation/accelerate/bnnsgraphcontextgettensor(_:_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphTensorFillStrides(_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphTensorFillStrides"}],"role":"symbol","title":"BNNSGraphTensorFillStrides(_:_:_:_:)","type":"topic","kind":"symbol","abstract":[{"text":"Sets the stride of the specifed tensor for compatibility with the given model’s input or output argument based on its current shape.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphTensorFillStrides","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@bnns_graph_t","text":"bnns_graph_t","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@SA@BNNSTensor","kind":"typeIdentifier","text":"BNNSTensor"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphTensorFillStrides(_:_:_:_:)","url":"/documentation/accelerate/bnnsgraphtensorfillstrides(_:_:_:_:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","introducedAt":"18.0","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"18.0","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"18.0","beta":false,"deprecated":false},{"unavailable":false,"name":"macOS","introducedAt":"15.0","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","introducedAt":"18.0","beta":false,"deprecated":false},{"unavailable":false,"name":"visionOS","introducedAt":"2.0","beta":false,"deprecated":false},{"unavailable":false,"name":"watchOS","introducedAt":"11.0","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Function","op":"replace"},{"path":"/metadata/title","value":"BNNSTensorGetAllocationSize","op":"replace"},{"path":"/metadata/symbolKind","value":"func","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"BNNSTensorGetAllocationSize","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphContextGetTensor(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphTensorFillStrides(_:_:_:_:)"],"title":"Specifying and querying a tensor’s properties","anchor":"Specifying-and-querying-a-tensors-properties"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"identifier":"doc://com.externally.resolved.symbol/c:@T@size_t","text":"size_t","preciseIdentifier":"c:@T@size_t","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSTensorGetAllocationSize"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTensor","preciseIdentifier":"c:@SA@BNNSTensor","text":"BNNSTensor"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"tensor"},{"kind":"text","text":");"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"tensor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The tensor."}]}]}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The minimum allocation size, in bytes, of the specified tensor."}]}]},"op":"replace"},{"value":"BNNSTensor","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTensor/title","op":"replace"},{"value":[{"text":"BNNSTensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTensor/fragments","op":"replace"},{"value":[{"text":"BNNSTensor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTensor/navigatorTitle","op":"replace"},{"value":"BNNSTensorGetAllocationSize","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTensorGetAllocationSize(_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSTensorGetAllocationSize"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTensorGetAllocationSize(_:)/fragments","op":"replace"},{"value":"BNNSGraphContextGetTensor","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetTensor(_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphContextGetTensor"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphContextGetTensor(_:_:_:_:_:)/fragments","op":"replace"},{"value":"BNNSGraphTensorFillStrides","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphTensorFillStrides(_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"BNNSGraphTensorFillStrides"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphTensorFillStrides(_:_:_:_:)/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}