{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"variants":[{"paths":["/documentation/accelerate/bnnsgraphcompileoptionssettargetsinglethread(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/bnnsgraphcompileoptionssettargetsinglethread(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The compilation options object.","type":"text"}]}],"name":"options"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", the options specify single-threaded execution; otherwise, the options specify multi-threaded execution.","type":"text"}]}],"name":"value"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The default option is execution on multiple threads."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Sets the option for the compiled graph to execute on a single thread."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"],"title":"Specifying and querying compilation options","generated":true,"anchor":"Specifying-and-querying-compilation-options"}],"sections":[],"metadata":{"role":"symbol","title":"BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","symbolKind":"func","externalID":"c:@F@BNNSGraphCompileOptionsSetTargetSingleThread","modules":[{"name":"Accelerate"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","kind":"typeIdentifier","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"macOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"visionOS"},{"beta":false,"unavailable":false,"introducedAt":"11.0","deprecated":false,"name":"watchOS"}],"roleHeading":"Function","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"}]},"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric":{"url":"/documentation/accelerate/bnnstargetsystemgeneric","navigatorTitle":[{"kind":"identifier","text":"BNNSTargetSystemGeneric"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSTargetSystemGeneric","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@EA@BNNSTargetSystem","text":"BNNSTargetSystem"}],"abstract":[],"title":"BNNSTargetSystemGeneric","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@EA@BNNSGraphOptimizationPreference","kind":"typeIdentifier","text":"BNNSGraphOptimizationPreference"},{"kind":"text","text":")"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoptimizationpreference(_:_:)","type":"topic","abstract":[{"text":"Sets the option for the compiled graph to optimize for either size or performance.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"}],"title":"BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t":{"url":"/documentation/accelerate/bnns_graph_compile_options_t","kind":"symbol","role":"symbol","type":"topic","title":"bnns_graph_compile_options_t","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"bnns_graph_compile_options_t"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","abstract":[{"text":"The compilation options that BNNS uses when compiling a source mlmodelc file to a graph object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bnns_graph_compile_options_t"}]},"doc://com.externally.resolved.symbol/s:Sb":{"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"title":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","url":"/documentation/Swift/Bool","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?)"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoutputpath(_:_:)","type":"topic","abstract":[{"type":"text","text":"Sets the option for graph compilation to generate the graph object directly to the specified file."}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputPath"}],"title":"BNNSGraphCompileOptionsSetOutputPath(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoptimizationpreference(_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@EA@BNNSGraphOptimizationPreference","kind":"typeIdentifier","text":"BNNSGraphOptimizationPreference"}],"abstract":[{"type":"text","text":"Returns the option for the compiled graph to optimize for either size or performance."}],"title":"BNNSGraphCompileOptionsGetOptimizationPreference(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionssettargetsinglethread(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the option for the compiled graph to execute on a single thread."}],"title":"BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"}],"kind":"symbol","title":"BNNSGraphCompileOptionsGetOutputFD(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsGetOutputFD","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoutputfd(_:)","abstract":[{"text":"Returns the option for the compiled graph’s output file descriptor.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionssetoutputfd(_:_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputFD"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputFD"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the option for graph compilation to generate the graph object directly to the specified file descriptor."}],"title":"BNNSGraphCompileOptionsSetOutputFD(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsmakedefault()","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsMakeDefault"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsMakeDefault","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"}],"abstract":[{"text":"Returns an allocated compilation options object with default values.","type":"text"}],"title":"BNNSGraphCompileOptionsMakeDefault()","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)":{"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetoutputpath(_:)","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputPath"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5CChara","kind":"typeIdentifier","text":"CChar"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"Returns the option for the compiled graph’s output path."}],"title":"BNNSGraphCompileOptionsGetOutputPath(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetGenerateDebugInfo"}],"kind":"symbol","title":"BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","abstract":[{"type":"text","text":"Returns the option for the compiled graph to include debugging information."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgetgeneratedebuginfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BNNSGraphCompileOptionsGetGenerateDebugInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"}],"kind":"symbol","title":"BNNSGraphCompileOptionsDestroy(_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","abstract":[{"type":"text","text":"Destroys the specified compilation options object."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsdestroy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","kind":"typeIdentifier","text":"bnns_graph_compile_options_t"},{"kind":"text","text":")"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetGenerateDebugInfo"}],"kind":"symbol","title":"BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","abstract":[{"type":"text","text":"Sets the option for the compiled graph to include debugging information."}],"url":"/documentation/accelerate/bnnsgraphcompileoptionssetgeneratedebuginfo(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetGenerateDebugInfo"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference":{"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}],"url":"/documentation/accelerate/bnnsgraphoptimizationpreference","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}],"abstract":[{"text":"Constants that describe the compilation optimization preference.","type":"text"}],"kind":"symbol","type":"topic","title":"BNNSGraphOptimizationPreference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference"},"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t","text":"bnns_graph_compile_options_t"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/accelerate/bnnsgraphcompileoptionsgettargetsinglethread(_:)","type":"topic","abstract":[{"type":"text","text":"Returns the option for the compiled graph to execute on a single thread."}],"navigatorTitle":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"}],"title":"BNNSGraphCompileOptionsGetTargetSingleThread(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"macOS"},{"beta":false,"unavailable":false,"introducedAt":"18.0","deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"introducedAt":"2.0","deprecated":false,"name":"visionOS"},{"beta":false,"unavailable":false,"introducedAt":"11.0","deprecated":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"BNNSGraphCompileOptionsSetTargetSingleThread","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Specifying and querying compilation options","generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsMakeDefault()","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsDestroy(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputPath(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputPath(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOutputFD(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOutputFD(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetTargetSingleThread(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetOptimizationPreference(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphOptimizationPreference","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)","doc://com.apple.accelerate/documentation/Accelerate/BNNSTargetSystemGeneric"],"anchor":"Specifying-and-querying-compilation-options"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"bnns_graph_compile_options_t","identifier":"doc://com.apple.accelerate/documentation/Accelerate/bnns_graph_compile_options_t","preciseIdentifier":"c:@SA@bnns_graph_compile_options_t"},{"kind":"text","text":" "},{"text":"options","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"bool","preciseIdentifier":"c:b","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"options","content":[{"type":"paragraph","inlineContent":[{"text":"The compilation options object.","type":"text"}]}]},{"name":"value","content":[{"inlineContent":[{"type":"text","text":"If "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the options specify single-threaded execution; otherwise, the options specify multi-threaded execution."}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1","op":"replace"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/title","op":"replace","value":"BNNSTargetSystemGeneric"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSTargetSystemGeneric/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSTargetSystemGeneric"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/title","op":"replace","value":"BNNSGraphCompileOptionsSetOptimizationPreference"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOptimizationPreference(_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOptimizationPreference"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/title","op":"replace","value":"bnns_graph_compile_options_t"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/fragments","op":"replace","value":[{"text":"bnns_graph_compile_options_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1bnns_graph_compile_options_t/navigatorTitle","op":"replace","value":[{"text":"bnns_graph_compile_options_t","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/title","op":"replace","value":"BNNSGraphCompileOptionsSetOutputPath"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputPath(_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetOutputPath"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsGetOptimizationPreference"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOptimizationPreference(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOptimizationPreference"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/title","op":"replace","value":"BNNSGraphCompileOptionsSetTargetSingleThread"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetTargetSingleThread(_:_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsSetTargetSingleThread"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsGetOutputFD"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputFD(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputFD"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/title","op":"replace","value":"BNNSGraphCompileOptionsSetOutputFD"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetOutputFD(_:_:)/fragments","op":"replace","value":[{"text":"BNNSGraphCompileOptionsSetOutputFD","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/title","op":"replace","value":"BNNSGraphCompileOptionsMakeDefault"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsMakeDefault()/fragments","op":"replace","value":[{"text":"BNNSGraphCompileOptionsMakeDefault","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsGetOutputPath"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetOutputPath(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetOutputPath"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsGetGenerateDebugInfo"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetGenerateDebugInfo(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetGenerateDebugInfo"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsDestroy"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsDestroy(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsDestroy"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/title","op":"replace","value":"BNNSGraphCompileOptionsSetGenerateDebugInfo"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsSetGenerateDebugInfo(_:_:)/fragments","op":"replace","value":[{"text":"BNNSGraphCompileOptionsSetGenerateDebugInfo","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/title","op":"replace","value":"BNNSGraphOptimizationPreference"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphOptimizationPreference"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphOptimizationPreference/navigatorTitle","op":"replace","value":[{"text":"BNNSGraphOptimizationPreference","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/title","op":"replace","value":"BNNSGraphCompileOptionsGetTargetSingleThread"},{"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSGraphCompileOptionsGetTargetSingleThread(_:)/fragments","op":"replace","value":[{"kind":"identifier","text":"BNNSGraphCompileOptionsGetTargetSingleThread"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}