{
  "abstract": [
    {
      "text": "Constants that describe random number generation methods.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BNNSRandomGeneratorMethod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BNNSRandomGeneratorMethod"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BNNSRandomGeneratorMethod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNSRandomGeneratorMethod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator": {
      "abstract": [
        {
          "text": "A random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomGenerator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RandomGenerator",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgenerator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new random number generator using an internally generated random seed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGenerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRandomGeneratorMethod",
          "text": "BNNSRandomGeneratorMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSCreateRandomGenerator(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnscreaterandomgenerator(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new random number generator using the specified seed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGeneratorWithSeed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRandomGeneratorMethod",
          "text": "BNNSRandomGeneratorMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGeneratorWithSeed"
        }
      ],
      "role": "symbol",
      "title": "BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnscreaterandomgeneratorwithseed(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)": {
      "abstract": [
        {
          "text": "Destroys a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDestroyRandomGenerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDestroyRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSDestroyRandomGenerator(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdestroyrandomgenerator(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random values from the categorical distributions with the given event probabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillCategoricalFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillCategoricalFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillCategoricalFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfillcategoricalfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random floating-point values mapped to a normal distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillNormalFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillNormalFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillNormalFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfillnormalfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random floating-point values from the continuous uniform distribution within a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillUniformFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfilluniformfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random integer values from the continuous uniform distribution within a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformInt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformInt"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillUniformInt(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfilluniformint(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator": {
      "abstract": [
        {
          "text": "A pointer to a random number generator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGenerator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGenerator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgenerator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the state of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorGetState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorGetState"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorGetState(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorgetstate(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod": {
      "abstract": [
        {
          "text": "Constants that describe random number generation methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethod"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorMethod",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethod/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethod/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/rawValue": {
      "abstract": [
        {
          "text": "The corresponding value of the raw type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethod/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethodAES_CTR": {
      "abstract": [
        {
          "text": "A constant that specifes an implementation that’s based on the Advanced Encryption Standard (AES) hash of a counter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethodAES_CTR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRandomGeneratorMethod",
          "text": "BNNSRandomGeneratorMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethodAES_CTR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethodAES_CTR"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorMethodAES_CTR",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethodaes_ctr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the state of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorSetState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorSetState"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorSetState(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorsetstate(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)": {
      "abstract": [
        {
          "text": "Returns the state size, in bytes, of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorStateSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorStateSize"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorStateSize(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorstatesize(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Random-number-generation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)"
      ],
      "title": "Random number generation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Random-Number-Generation-Methods",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethodAES_CTR"
      ],
      "title": "Random Number Generation Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BNNSRandomGeneratorMethod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Random-Number-Generation-Methods",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethodAES_CTR"
              ],
              "title": "Random Number Generation Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Random-number-generation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)"
              ],
              "title": "Random number generation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BNNSRandomGeneratorMethod"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/title",
          "value": "BNNSRandomGeneratorMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillUniformFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillUniformFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDestroyRandomGenerator(_:)/title",
          "value": "BNNSDestroyRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDestroyRandomGenerator(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDestroyRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGeneratorWithSeed(_:_:_:)/title",
          "value": "BNNSCreateRandomGeneratorWithSeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGeneratorWithSeed(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSCreateRandomGeneratorWithSeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethodAES_CTR/title",
          "value": "BNNSRandomGeneratorMethodAES_CTR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethodAES_CTR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethodAES_CTR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/title",
          "value": "BNNSRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorStateSize(_:)/title",
          "value": "BNNSRandomGeneratorStateSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorStateSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorStateSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGenerator(_:_:)/title",
          "value": "BNNSCreateRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGenerator(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSCreateRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformInt(_:_:_:_:)/title",
          "value": "BNNSRandomFillUniformInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformInt(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillUniformInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorSetState(_:_:_:)/title",
          "value": "BNNSRandomGeneratorSetState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorSetState(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorSetState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillCategoricalFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillCategoricalFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillCategoricalFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillCategoricalFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorGetState(_:_:_:)/title",
          "value": "BNNSRandomGeneratorGetState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorGetState(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorGetState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillNormalFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillNormalFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillNormalFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillNormalFloat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnsrandomgeneratormethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnsrandomgeneratormethod"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
