{
  "abstract": [
    {
      "text": "Prints an error message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/cblas_errprn"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@cblas_errprn",
    "fragments": [
      {
        "kind": "identifier",
        "text": "cblas_errprn"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cblas_errprn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.4",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "cblas_errprn"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@__LAPACK_int",
              "text": "__LAPACK_int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cblas_errprn"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@__LAPACK_int",
              "text": "__LAPACK_int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ierr"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@__LAPACK_int",
              "text": "__LAPACK_int"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "info"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "form"
            },
            {
              "kind": "text",
              "text": ", ...);"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Error code number.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ierr"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Exit status returned by the function call. Negative values generally indicate the index of the offending parameter. Positive numbers generally indicate that an algorithm did not converge. Zero indicates success.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "info"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A printf-style format string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "form"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the minimum of ",
              "type": "text"
            },
            {
              "code": "ierr",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "info",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add any additional parameters required for the format string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple provides the BLAS and LAPACK libraries under the Accelerate framework to be in line with LAPACK 3.9.1. Starting with iOS 19, iPadOS 19, macOS 16, tvOS 19, watchOS 19, and visionOS 3, the libraries are in line with LAPACK 3.12.0. These new interfaces provide additional functionality, as well as a new ILP64 interface. To use the new interfaces, define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK",
                  "type": "codeVoice"
                },
                {
                  "text": " before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64",
                  "type": "codeVoice"
                },
                {
                  "text": ". For Swift projects, specify ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK=1",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64=1",
                  "type": "codeVoice"
                },
                {
                  "text": " as preprocessor macros in Xcode build settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SetBLASParamErrorProc": {
      "abstract": [
        {
          "text": "Sets an error handler function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SetBLASParamErrorProc"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SetBLASParamErrorProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetBLASParamErrorProc",
      "type": "topic",
      "url": "/documentation/accelerate/setblasparamerrorproc"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_errprn": {
      "abstract": [
        {
          "text": "Prints an error message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cblas_errprn"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_errprn",
      "kind": "symbol",
      "role": "symbol",
      "title": "cblas_errprn",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_errprn"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_icamax(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the index of the element with the largest absolute value in a vector (single-precision complex).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cblas_icamax"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_icamax(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cblas_icamax"
        }
      ],
      "role": "symbol",
      "title": "cblas_icamax(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_icamax(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_idamax(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the index of the element with the largest absolute value in a vector (double-precision).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cblas_idamax"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_idamax(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cblas_idamax"
        }
      ],
      "role": "symbol",
      "title": "cblas_idamax(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_idamax(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_isamax(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the index of the element with the largest absolute value in a vector (single-precision).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cblas_isamax"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_isamax(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cblas_isamax"
        }
      ],
      "role": "symbol",
      "title": "cblas_isamax(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_isamax(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_izamax(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the index of the element with the largest absolute value in a vector (double-precision complex).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cblas_izamax"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s13OpaquePointerV",
          "text": "OpaquePointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@__LAPACK_int",
          "text": "__LAPACK_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_izamax(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cblas_izamax"
        }
      ],
      "role": "symbol",
      "title": "cblas_izamax(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_izamax(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cblas_xerbla": {
      "abstract": [
        {
          "text": "The default error handler for BLAS routines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cblas_xerbla"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cblas_xerbla",
      "kind": "symbol",
      "role": "symbol",
      "title": "cblas_xerbla",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_xerbla"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SetBLASParamErrorProc",
        "doc://com.apple.accelerate/documentation/Accelerate/cblas_xerbla",
        "doc://com.apple.accelerate/documentation/Accelerate/cblas_icamax(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/cblas_idamax(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/cblas_isamax(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/cblas_izamax(_:_:_:)"
      ],
      "title": "General functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_isamax(_:_:_:)/title",
          "value": "cblas_isamax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_isamax(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cblas_isamax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_izamax(_:_:_:)/title",
          "value": "cblas_izamax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_izamax(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cblas_izamax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_idamax(_:_:_:)/title",
          "value": "cblas_idamax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_idamax(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cblas_idamax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_icamax(_:_:_:)/title",
          "value": "cblas_icamax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1cblas_icamax(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cblas_icamax"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/cblas_errprn"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
