{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/CblasNonUnit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CBLAS_DIAG@CblasNonUnit",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CblasNonUnit"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CBLAS_DIAG",
        "text": "CBLAS_DIAG"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CblasNonUnit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CblasNonUnit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CblasNonUnit"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CBLAS_DIAG",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CBLAS_DIAG",
              "text": "CBLAS_DIAG"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/AtlasConj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AtlasConj"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AtlasConj",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AtlasConj"
        }
      ],
      "role": "symbol",
      "title": "AtlasConj",
      "type": "topic",
      "url": "/documentation/accelerate/atlasconj"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CBLAS_DIAG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBLAS_DIAG"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CBLAS_DIAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBLAS_DIAG"
        }
      ],
      "role": "symbol",
      "title": "CBLAS_DIAG",
      "type": "topic",
      "url": "/documentation/accelerate/cblas_diag"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasColMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasColMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_ORDER",
          "text": "CBLAS_ORDER"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasColMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasColMajor"
        }
      ],
      "role": "symbol",
      "title": "CblasColMajor",
      "type": "topic",
      "url": "/documentation/accelerate/cblascolmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasConjTrans": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasConjTrans"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasConjTrans",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasConjTrans"
        }
      ],
      "role": "symbol",
      "title": "CblasConjTrans",
      "type": "topic",
      "url": "/documentation/accelerate/cblasconjtrans"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasLeft": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_SIDE",
          "text": "CBLAS_SIDE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasLeft"
        }
      ],
      "role": "symbol",
      "title": "CblasLeft",
      "type": "topic",
      "url": "/documentation/accelerate/cblasleft"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasLower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasLower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_UPLO",
          "text": "CBLAS_UPLO"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasLower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasLower"
        }
      ],
      "role": "symbol",
      "title": "CblasLower",
      "type": "topic",
      "url": "/documentation/accelerate/cblaslower"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasNoTrans": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasNoTrans"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasNoTrans",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasNoTrans"
        }
      ],
      "role": "symbol",
      "title": "CblasNoTrans",
      "type": "topic",
      "url": "/documentation/accelerate/cblasnotrans"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasNonUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasNonUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_DIAG",
          "text": "CBLAS_DIAG"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasNonUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasNonUnit"
        }
      ],
      "role": "symbol",
      "title": "CblasNonUnit",
      "type": "topic",
      "url": "/documentation/accelerate/cblasnonunit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasRight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_SIDE",
          "text": "CBLAS_SIDE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasRight"
        }
      ],
      "role": "symbol",
      "title": "CblasRight",
      "type": "topic",
      "url": "/documentation/accelerate/cblasright"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasRowMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasRowMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_ORDER",
          "text": "CBLAS_ORDER"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasRowMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasRowMajor"
        }
      ],
      "role": "symbol",
      "title": "CblasRowMajor",
      "type": "topic",
      "url": "/documentation/accelerate/cblasrowmajor"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasTrans": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasTrans"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasTrans",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasTrans"
        }
      ],
      "role": "symbol",
      "title": "CblasTrans",
      "type": "topic",
      "url": "/documentation/accelerate/cblastrans"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_DIAG",
          "text": "CBLAS_DIAG"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasUnit"
        }
      ],
      "role": "symbol",
      "title": "CblasUnit",
      "type": "topic",
      "url": "/documentation/accelerate/cblasunit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/CblasUpper": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CblasUpper"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_UPLO",
          "text": "CBLAS_UPLO"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/CblasUpper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CblasUpper"
        }
      ],
      "role": "symbol",
      "title": "CblasUpper",
      "type": "topic",
      "url": "/documentation/accelerate/cblasupper"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/CblasColMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasConjTrans",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasLeft",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasLower",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasNoTrans",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasRight",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasRowMajor",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasTrans",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasUnit",
        "doc://com.apple.accelerate/documentation/Accelerate/CblasUpper",
        "doc://com.apple.accelerate/documentation/Accelerate/AtlasConj"
      ],
      "title": "Variables"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CblasNonUnit"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasNonUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/CBLAS_DIAG"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/CblasColMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasConjTrans",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasLeft",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasLower",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasNoTrans",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasRight",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasRowMajor",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasTrans",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasUnit",
                "doc://com.apple.accelerate/documentation/Accelerate/CblasUpper",
                "doc://com.apple.accelerate/documentation/Accelerate/AtlasConj"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CblasNonUnit"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasRowMajor/title",
          "value": "CblasRowMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasRowMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasRowMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CBLAS_DIAG/title",
          "value": "CBLAS_DIAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CBLAS_DIAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBLAS_DIAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CBLAS_DIAG/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBLAS_DIAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasLower/title",
          "value": "CblasLower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasLower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasLower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasUpper/title",
          "value": "CblasUpper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasUpper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasUpper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasTrans/title",
          "value": "CblasTrans"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasTrans/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasTrans"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasConjTrans/title",
          "value": "CblasConjTrans"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasConjTrans/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasConjTrans"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1AtlasConj/title",
          "value": "AtlasConj"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1AtlasConj/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AtlasConj"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasUnit/title",
          "value": "CblasUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasNoTrans/title",
          "value": "CblasNoTrans"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasNoTrans/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasNoTrans"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasRight/title",
          "value": "CblasRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasColMajor/title",
          "value": "CblasColMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasColMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasColMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasNonUnit/title",
          "value": "CblasNonUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasNonUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasNonUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasLeft/title",
          "value": "CblasLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1CblasLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CblasLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/cblasnonunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/cblasnonunit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
