{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@COMPLEX_SPLIT",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COMPLEX_SPLIT"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COMPLEX_SPLIT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "COMPLEX_SPLIT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPSplitComplex",
              "text": "DSPSplitComplex"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPLEX_SPLIT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPLEX_SPLIT"
        }
      ],
      "role": "symbol",
      "title": "COMPLEX_SPLIT",
      "type": "topic",
      "url": "/documentation/accelerate/complex_split"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOUBLE_COMPLEX_SPLIT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOUBLE_COMPLEX_SPLIT"
        }
      ],
      "role": "symbol",
      "title": "DOUBLE_COMPLEX_SPLIT",
      "type": "topic",
      "url": "/documentation/accelerate/double_complex_split"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublecomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublesplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspsplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision real value for biquadratic filtering and discrete Fourier transforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VectorizableDouble"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VectorizableDouble"
        }
      ],
      "role": "symbol",
      "title": "vDSP.VectorizableDouble",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/vectorizabledouble"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision real value for biquadratic filtering and discrete Fourier transforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VectorizableFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VectorizableFloat"
        }
      ],
      "role": "symbol",
      "title": "vDSP.VectorizableFloat",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/vectorizablefloat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride": {
      "abstract": [
        {
          "text": "An integer value that represents the differences between indices of elements, including the lengths of strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Stride",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_stride"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat"
      ],
      "title": "Data types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COMPLEX_SPLIT"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
                "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
                "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
                "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT",
                "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
                "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@DSPSplitComplex",
                    "text": "DSPSplitComplex"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "COMPLEX_SPLIT"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/title",
          "value": "DSPSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/title",
          "value": "DSPComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/title",
          "value": "DSPDoubleSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/title",
          "value": "DSPDoubleComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/title",
          "value": "DOUBLE_COMPLEX_SPLIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOUBLE_COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOUBLE_COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/title",
          "value": "vDSP_Stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/title",
          "value": "COMPLEX_SPLIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/complex_split"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/complex_split"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
