{
  "abstract": [
    {
      "text": "Create, copy, and query Core Video image format descriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/core-video-image-format-utilities"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Video image format utilities"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability": {
      "abstract": [
        {
          "text": "Pass image data between Core Video and vImage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/core-video-interoperability",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video interoperability",
      "type": "topic",
      "url": "/documentation/accelerate/core-video-interoperability"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat": {
      "abstract": [
        {
          "text": "A mutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Copy(_:)": {
      "abstract": [
        {
          "text": "Returns a mutable copy of an immutable Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Copy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Copy"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_Copy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_copy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyChannelDescription(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies the channel description for a particular channel type to an image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyChannelDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageChannelDescription",
          "text": "vImageChannelDescription"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageBufferTypeCode",
          "text": "vImageBufferTypeCode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyChannelDescription(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_CopyChannelDescription(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_copychanneldescription(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies an RGB-to-YpCbCr conversion matrix to an image format’s internal matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyConversionMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageMatrixType",
          "text": "vImageMatrixType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_CopyConversionMatrix(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_copyconversionmatrix(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Create(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates the description of image encoding in a Core Video pixel buffer from the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Create(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Create"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_Create(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_create(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CreateWithCVPixelBuffer(_:)": {
      "abstract": [
        {
          "text": "Creates the description of the image encoding in an existing Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CreateWithCVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CreateWithCVPixelBuffer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CreateWithCVPixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_CreateWithCVPixelBuffer(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_createwithcvpixelbuffer(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetAlphaHint(_:)": {
      "abstract": [
        {
          "text": "Returns the alpha hint of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetAlphaHint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetAlphaHint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetAlphaHint"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetAlphaHint(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getalphahint(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelCount(_:)": {
      "abstract": [
        {
          "text": "Returns the number of channels, including alpha, for the Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelCount"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetChannelCount(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getchannelcount(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelDescription(_:_:)": {
      "abstract": [
        {
          "text": "Returns the channel description for a particular channel type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageBufferTypeCode",
          "text": "vImageBufferTypeCode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageChannelDescription",
          "text": "vImageChannelDescription"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelDescription(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetChannelDescription(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getchanneldescription(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelNames(_:)": {
      "abstract": [
        {
          "text": "Returns the names of the channels of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageBufferTypeCode",
          "text": "vImageBufferTypeCode"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelNames(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChannelNames"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetChannelNames(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getchannelnames(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChromaSiting(_:)": {
      "abstract": [
        {
          "text": "Returns the chrominance siting of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChromaSiting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChromaSiting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetChromaSiting"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetChromaSiting(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getchromasiting(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetColorSpace(_:)": {
      "abstract": [
        {
          "text": "Returns the color space of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetColorSpace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetColorSpace(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetColorSpace"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetColorSpace(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getcolorspace(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the RGB-to-YpCbCr conversion matrix of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetConversionMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageMatrixType",
          "text": "vImageMatrixType"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetConversionMatrix(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getconversionmatrix(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetFormatCode(_:)": {
      "abstract": [
        {
          "text": "Returns the four-character code that encodes the pixel format of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetFormatCode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetFormatCode(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetFormatCode"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetFormatCode(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getformatcode(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetUserData(_:)": {
      "abstract": [
        {
          "text": "Returns the user data of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetUserData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetUserData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetUserData"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetUserData(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getuserdata(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Release": {
      "abstract": [
        {
          "text": "Releases a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Release"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Release",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat_Release",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_release"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Retain": {
      "abstract": [
        {
          "text": "Retains a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_Retain"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Retain",
      "kind": "symbol",
      "role": "symbol",
      "title": "vImageCVImageFormat_Retain",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_retain"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetAlphaHint(_:_:)": {
      "abstract": [
        {
          "text": "Sets the alpha hint of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetAlphaHint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetAlphaHint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetAlphaHint"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_SetAlphaHint(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_setalphahint(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetChromaSiting(_:_:)": {
      "abstract": [
        {
          "text": "Sets the chrominance siting of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetChromaSiting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetChromaSiting(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetChromaSiting"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_SetChromaSiting(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_setchromasiting(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetColorSpace(_:_:)": {
      "abstract": [
        {
          "text": "Sets the color space of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetColorSpace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetColorSpace(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetColorSpace"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_SetColorSpace(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_setcolorspace(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetUserData(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the user data of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetUserData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetUserData(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_SetUserData"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_SetUserData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_setuserdata(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageChannelDescription": {
      "abstract": [
        {
          "text": "A description of the range and clamp limits for a pixel format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageChannelDescription"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageChannelDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageChannelDescription"
        }
      ],
      "role": "symbol",
      "title": "vImageChannelDescription",
      "type": "topic",
      "url": "/documentation/accelerate/vimagechanneldescription"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat": {
      "abstract": [
        {
          "text": "An immutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageConstCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconstcvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-Core-Video-image-formats",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CreateWithCVPixelBuffer(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Create(_:_:_:_:_:)"
      ],
      "title": "Creating Core Video image formats"
    },
    {
      "anchor": "Copying-Core-Video-image-formats",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Copy(_:)"
      ],
      "title": "Copying Core Video image formats"
    },
    {
      "anchor": "Querying-and-setting-the-alpha-hint",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetAlphaHint(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetAlphaHint(_:_:)"
      ],
      "title": "Querying and setting the alpha hint"
    },
    {
      "anchor": "Querying-and-setting-channel-information",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelCount(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelDescription(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyChannelDescription(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChannelNames(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageChannelDescription"
      ],
      "title": "Querying and setting channel information"
    },
    {
      "anchor": "Querying-and-setting-the-chrominance-siting",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetChromaSiting(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetChromaSiting(_:_:)"
      ],
      "title": "Querying and setting the chrominance siting"
    },
    {
      "anchor": "Querying-and-setting-the-color-space",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetColorSpace(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetColorSpace(_:_:)"
      ],
      "title": "Querying and setting the color space"
    },
    {
      "anchor": "Querying-and-setting-the-conversion-matrix",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)"
      ],
      "title": "Querying and setting the conversion matrix"
    },
    {
      "anchor": "Querying-the-image-format-code",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetFormatCode(_:)"
      ],
      "title": "Querying the image format code"
    },
    {
      "anchor": "Querying-and-setting-the-user-data",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetUserData(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_SetUserData(_:_:_:)"
      ],
      "title": "Querying and setting the user data"
    },
    {
      "anchor": "Image-format-memory-management",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Retain",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_Release"
      ],
      "title": "Image format memory management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelDescription(_:_:)/title",
          "value": "vImageCVImageFormat_GetChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelDescription(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CreateWithCVPixelBuffer(_:)/title",
          "value": "vImageCVImageFormat_CreateWithCVPixelBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CreateWithCVPixelBuffer(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CreateWithCVPixelBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_Create(_:_:_:_:_:)/title",
          "value": "vImageCVImageFormat_Create"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_Create(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_Create"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetColorSpace(_:)/title",
          "value": "vImageCVImageFormat_GetColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetColorSpace(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetChromaSiting(_:_:)/title",
          "value": "vImageCVImageFormat_SetChromaSiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetChromaSiting(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_SetChromaSiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetUserData(_:_:_:)/title",
          "value": "vImageCVImageFormat_SetUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetUserData(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_SetUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetConversionMatrix(_:_:)/title",
          "value": "vImageCVImageFormat_GetConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetConversionMatrix(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelNames(_:)/title",
          "value": "vImageCVImageFormat_GetChannelNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelNames(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetChannelNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetColorSpace(_:_:)/title",
          "value": "vImageCVImageFormat_SetColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetColorSpace(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_SetColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/title",
          "value": "vImageConstCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyConversionMatrix(_:_:_:)/title",
          "value": "vImageCVImageFormat_CopyConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyConversionMatrix(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CopyConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelCount(_:)/title",
          "value": "vImageCVImageFormat_GetChannelCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChannelCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetChannelCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/title",
          "value": "vImageCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyChannelDescription(_:_:_:)/title",
          "value": "vImageCVImageFormat_CopyChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyChannelDescription(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CopyChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_Copy(_:)/title",
          "value": "vImageCVImageFormat_Copy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_Copy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_Copy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageChannelDescription/title",
          "value": "vImageChannelDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageChannelDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageChannelDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageChannelDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetAlphaHint(_:_:)/title",
          "value": "vImageCVImageFormat_SetAlphaHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_SetAlphaHint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_SetAlphaHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChromaSiting(_:)/title",
          "value": "vImageCVImageFormat_GetChromaSiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetChromaSiting(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetChromaSiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetFormatCode(_:)/title",
          "value": "vImageCVImageFormat_GetFormatCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetFormatCode(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetFormatCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetAlphaHint(_:)/title",
          "value": "vImageCVImageFormat_GetAlphaHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetAlphaHint(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetAlphaHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetUserData(_:)/title",
          "value": "vImageCVImageFormat_GetUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetUserData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetUserData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
