{
  "abstract": [
    {
      "text": "A structure that contains a dense matrix of double-precision, floating-point values.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@DenseMatrix_Double",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DenseMatrix_Double"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DenseMatrix_Double"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "DenseMatrix_Double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You typically use dense matrices to represent the unknowns matrix, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "X",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", and the right-hand-side matrix, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "B",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", in the matrix equation ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "AX = B.",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure provides a pointer to its underlying data, and information about its structure and attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows an example of how to create a dense matrix structure from an array of double-precision values. In this case, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer/withUnsafeMutableBufferPointer(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to pass a pointer to your collection. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure is valid only during the execution of the closure. Don’t store or return the structure for later use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// An array of `rowCount` x `columnCount` single-precision values.",
            "var matrixValues = [...]",
            "let rowCount = Int32(5)",
            "let columnCount = Int32(5)",
            "",
            "matrixValues.withUnsafeMutableBufferPointer {",
            "    let matrix = DenseMatrix_Double(rowCount: rowCount,",
            "                                    columnCount: columnCount,",
            "                                    columnStride: rowCount,",
            "                                    attributes: SparseAttributes_t(),",
            "                                    data: $0.baseAddress!)",
            "    ",
            "    // Perform operations using `matrix`.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer/withUnsafeMutableBufferPointer(_:)": {
      "abstract": [
        {
          "text": "Calls the given closure with a pointer to the object’s mutable contiguous storage.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeMutableBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sr",
          "text": "UnsafeMutableBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate0A6BufferP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/AccelerateMutableBuffer/withUnsafeMutableBufferPointer(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "withUnsafeMutableBufferPointer(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/acceleratemutablebuffer/withunsafemutablebufferpointer(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double": {
      "abstract": [
        {
          "text": "A structure that contains a dense matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DenseMatrix_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DenseMatrix_Double"
        }
      ],
      "role": "symbol",
      "title": "DenseMatrix_Double",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/attributes": {
      "abstract": [
        {
          "text": "The attributes of the matrix, such as whether it’s symmetrical or triangular.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseAttributes_t",
          "text": "SparseAttributes_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "role": "symbol",
      "title": "attributes",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/attributes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnCount": {
      "abstract": [
        {
          "text": "The number of columns in the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnCount"
        }
      ],
      "role": "symbol",
      "title": "columnCount",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/columncount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnStride": {
      "abstract": [
        {
          "text": "The stride between matrix columns, in elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnStride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "columnStride"
        }
      ],
      "role": "symbol",
      "title": "columnStride",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/columnstride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/data": {
      "abstract": [
        {
          "text": "The array of double-precision, floating-point values in column-major order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/init(rowCount:columnCount:columnStride:attributes:data:)": {
      "abstract": [
        {
          "text": "Creates a new matrix of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rowCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columnCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "columnStride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseAttributes_t",
          "text": "SparseAttributes_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/init(rowCount:columnCount:columnStride:attributes:data:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rowCount:columnCount:columnStride:attributes:data:)",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/init(rowcount:columncount:columnstride:attributes:data:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/rowCount": {
      "abstract": [
        {
          "text": "The number of rows in the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rowCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/rowCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rowCount"
        }
      ],
      "role": "symbol",
      "title": "rowCount",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double/rowcount"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Float": {
      "abstract": [
        {
          "text": "A structure that contains a dense matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DenseMatrix_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DenseMatrix_Float"
        }
      ],
      "role": "symbol",
      "title": "DenseMatrix_Float",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Double": {
      "abstract": [
        {
          "text": "A structure that contains a dense vector of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DenseVector_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DenseVector_Double"
        }
      ],
      "role": "symbol",
      "title": "DenseVector_Double",
      "type": "topic",
      "url": "/documentation/accelerate/densevector_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Float": {
      "abstract": [
        {
          "text": "A structure that contains a dense vector of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DenseVector_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DenseVector_Float"
        }
      ],
      "role": "symbol",
      "title": "DenseVector_Float",
      "type": "topic",
      "url": "/documentation/accelerate/densevector_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t": {
      "abstract": [
        {
          "text": "A structure that represents the attributes of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseAttributes_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseAttributes_t"
        }
      ],
      "role": "symbol",
      "title": "SparseAttributes_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparseattributes_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-dense-matrices-and-dense-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Float",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Float"
      ],
      "title": "Creating dense matrices and dense vectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/init(rowCount:columnCount:columnStride:attributes:data:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Inspecting-a-Matrixs-Structure-and-Data",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/rowCount",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnCount",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnStride",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/attributes",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t",
        "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/data"
      ],
      "title": "Inspecting a Matrix’s Structure and Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DenseMatrix_Double"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-a-Matrixs-Structure-and-Data",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/rowCount",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnCount",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/columnStride",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/attributes",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseAttributes_t",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double/data"
              ],
              "title": "Inspecting a Matrix’s Structure and Data"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-dense-matrices-and-dense-vectors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Float",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Double",
                "doc://com.apple.accelerate/documentation/Accelerate/DenseVector_Float"
              ],
              "title": "Creating dense matrices and dense vectors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "DenseMatrix_Double"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Float/title",
          "value": "DenseVector_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseVector_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseVector_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1rowCount/title",
          "value": "rowCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1rowCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rowCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1columnStride/title",
          "value": "columnStride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1columnStride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnStride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1columnCount/title",
          "value": "columnCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1columnCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "columnCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/title",
          "value": "SparseAttributes_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseAttributes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseAttributes_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseAttributes_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Float/title",
          "value": "DenseMatrix_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1attributes/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Double/title",
          "value": "DenseVector_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseVector_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseVector_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseVector_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/title",
          "value": "DenseMatrix_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/densematrix_double"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/densematrix_double"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
