{
  "abstract": [
    {
      "text": "An opaque type that contains setup information for a double-precision FFT transform.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/FFTSetupD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@FFTSetupD",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FFTSetupD"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FFTSetupD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "FFTSetupD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FFTSetupD"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetupD",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to create a setup structure, and calll ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetupD",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to deallocate a setup structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFTRadix": {
      "abstract": [
        {
          "text": "The radix of the FFT decomposition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFTRadix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFTRadix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFTRadix"
        }
      ],
      "role": "symbol",
      "title": "FFTRadix",
      "type": "topic",
      "url": "/documentation/accelerate/fftradix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFTSetup": {
      "abstract": [
        {
          "text": "An opaque type that contains setup information for a single-precision FFT transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFTSetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFTSetup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFTSetup"
        }
      ],
      "role": "symbol",
      "title": "FFTSetup",
      "type": "topic",
      "url": "/documentation/accelerate/fftsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFTSetupD": {
      "abstract": [
        {
          "text": "An opaque type that contains setup information for a double-precision FFT transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFTSetupD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFTSetupD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFTSetupD"
        }
      ],
      "role": "symbol",
      "title": "FFTSetupD",
      "type": "topic",
      "url": "/documentation/accelerate/fftsetupd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_CreateSetup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_DFT_CreateSetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_CreateSetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_DFT_CreateSetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dft_createsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetup": {
      "abstract": [
        {
          "text": "Returns a setup structure that contains precalculated data for single-precision FFT functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_create_fftsetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_create_fftsetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_create_fftsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetupD": {
      "abstract": [
        {
          "text": "Returns a setup structure that contains precalculated data for double-precision FFT functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_create_fftsetupD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetupD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_create_fftsetupD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_create_fftsetupd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetup": {
      "abstract": [
        {
          "text": "Deallocates an existing single-precision FFT setup structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_destroy_fftsetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_destroy_fftsetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_destroy_fftsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetupD": {
      "abstract": [
        {
          "text": "Deallocates an existing double-precision FFT setup structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_destroy_fftsetupD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetupD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_destroy_fftsetupD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_destroy_fftsetupd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "FFT-Setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/FFTSetup",
        "doc://com.apple.accelerate/documentation/Accelerate/FFTRadix"
      ],
      "title": "FFT Setup"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "FFTSetupD"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetupD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetupD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "FFT-Setup",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetup",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_create_fftsetupD",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetup",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_destroy_fftsetupD",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_CreateSetup",
                "doc://com.apple.accelerate/documentation/Accelerate/FFTSetup",
                "doc://com.apple.accelerate/documentation/Accelerate/FFTRadix"
              ],
              "title": "FFT Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueFFTSetupD",
                    "text": "OpaqueFFTSetupD"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "FFTSetupD"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTRadix/title",
          "value": "FFTRadix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTRadix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTRadix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTRadix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTRadix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetup/title",
          "value": "FFTSetup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetupD/title",
          "value": "FFTSetupD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetupD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetupD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTSetupD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTSetupD"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/fftsetupd"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/fftsetupd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
