{
  "abstract": [
    {
      "text": "Manage and work with the properties of a sparse matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/blas-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/general-sparse-matrix-management-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "General Sparse Matrix Management Operations"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blas-library": {
      "abstract": [
        {
          "text": "Perform common linear algebra operations with Apple’s implementation of the Basic Linear Algebra Subprograms (BLAS).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blas-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "BLAS",
      "type": "topic",
      "url": "/documentation/accelerate/blas-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations": {
      "abstract": [
        {
          "text": "Create, insert values into, and extract values from a blockwise sparse matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Blockwise Matrix Operations",
      "type": "topic",
      "url": "/documentation/accelerate/blockwise-matrix-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations": {
      "abstract": [
        {
          "text": "Perform computations with matrices and vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matrix and Vector Operations",
      "type": "topic",
      "url": "/documentation/accelerate/matrix-and-vector-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations": {
      "abstract": [
        {
          "text": "Create, insert values into, and extract values from a pointwise sparse matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pointwise Matrix Operations",
      "type": "topic",
      "url": "/documentation/accelerate/pointwise-matrix-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-vector-utility-operations": {
      "abstract": [
        {
          "text": "Create and work with sparse vector structures.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-vector-utility-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Vector Utility Operations",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-vector-utility-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)": {
      "abstract": [
        {
          "text": "Puts values that you recently added to the matrix into the internal sparse storage format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_commit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_commit"
        }
      ],
      "role": "symbol",
      "title": "sparse_commit(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_commit(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension": {
      "abstract": [
        {
          "text": "The dimension type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "role": "symbol",
      "title": "sparse_dimension",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_dimension"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in a column of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_column"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_column"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count_for_column(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in a row of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_row"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_row"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count_for_row(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)": {
      "abstract": [
        {
          "text": "Returns the number of columns of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_columns"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_number_of_columns(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_number_of_columns(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)": {
      "abstract": [
        {
          "text": "Returns the number of rows of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_rows"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_number_of_rows(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_number_of_rows(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value of the given property name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_property(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_property(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_index": {
      "abstract": [
        {
          "text": "The index type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "role": "symbol",
      "title": "sparse_index",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_index"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)": {
      "abstract": [
        {
          "text": "Releases any memory associated with the matrix object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_destroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_destroy"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_destroy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_destroy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property": {
      "abstract": [
        {
          "text": "The matrix property type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_property",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_property"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)": {
      "abstract": [
        {
          "text": "Sets the given property for a matrix object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_set_matrix_property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_set_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_set_matrix_property(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_set_matrix_property(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sparse-computation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-vector-utility-operations"
      ],
      "title": "Sparse computation"
    }
  ],
  "topicSections": [
    {
      "anchor": "General-Sparse-Matrix-Management-Operations",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)"
      ],
      "title": "General Sparse Matrix Management Operations"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property"
      ],
      "title": "Supporting Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/title",
          "value": "sparse_dimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_set_matrix_property(_:_:)/title",
          "value": "sparse_set_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_set_matrix_property(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_set_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_rows(_:)/title",
          "value": "sparse_get_matrix_number_of_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_rows(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_number_of_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_property(_:_:)/title",
          "value": "sparse_get_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_property(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/title",
          "value": "sparse_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_column(_:_:)/title",
          "value": "sparse_get_matrix_nonzero_count_for_column"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_column(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count_for_column"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_commit(_:)/title",
          "value": "sparse_commit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_commit(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_commit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/title",
          "value": "sparse_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_destroy(_:)/title",
          "value": "sparse_matrix_destroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_destroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_destroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_row(_:_:)/title",
          "value": "sparse_get_matrix_nonzero_count_for_row"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_row(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count_for_row"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_columns(_:)/title",
          "value": "sparse_get_matrix_number_of_columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_columns(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_number_of_columns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count(_:)/title",
          "value": "sparse_get_matrix_nonzero_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
