{
  "abstract": [
    {
      "text": "Perform operations on matrices that contain half-precision floating-point elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/half-precision-floating-point-matrices"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Half-precision floating-point matrices"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A matrix is a 2D array of values arranged in rows and columns. The simd library provides support for matrices of up to four rows and four columns. It uses a column-major naming convention; for example, a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is a matrix that contains four columns and two rows.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/double-precision-floating-point-matrices": {
      "abstract": [
        {
          "text": "Perform operations on matrices that contain double-precision floating-point elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/double-precision-floating-point-matrices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Double-precision floating-point matrices",
      "type": "topic",
      "url": "/documentation/accelerate/double-precision-floating-point-matrices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/single-precision-floating-point-matrices": {
      "abstract": [
        {
          "text": "Perform operations on matrices that contain single-precision floating-point elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/single-precision-floating-point-matrices",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Single-precision floating-point matrices",
      "type": "topic",
      "url": "/documentation/accelerate/single-precision-floating-point-matrices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices": {
      "abstract": [
        {
          "text": "Solve simultaneous equations and transform points in space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
      "kind": "article",
      "role": "article",
      "title": "Working with Matrices",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-matrices"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x2": {
      "abstract": [
        {
          "text": "A matrix of two columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x3": {
      "abstract": [
        {
          "text": "A matrix of two columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half2x4": {
      "abstract": [
        {
          "text": "A matrix of two columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half2x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half2x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half2x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half2x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half2x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x2": {
      "abstract": [
        {
          "text": "A matrix of three columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x3": {
      "abstract": [
        {
          "text": "A matrix of three columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half3x4": {
      "abstract": [
        {
          "text": "A matrix of three columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half3x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half3x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half3x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half3x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half3x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x3": {
      "abstract": [
        {
          "text": "A matrix of four columns and three rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x3"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x3",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_half4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains half-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_half4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_half4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_half4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_half4x4"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
        "doc://com.apple.accelerate/documentation/Accelerate/single-precision-floating-point-matrices",
        "doc://com.apple.accelerate/documentation/Accelerate/double-precision-floating-point-matrices"
      ],
      "title": "Matrices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Matrix-structures",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_half2x2",
        "doc://com.apple.accelerate/documentation/simd/simd_half2x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half2x4",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x2",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half3x4",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x2",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x3",
        "doc://com.apple.accelerate/documentation/simd/simd_half4x4"
      ],
      "title": "Matrix structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/title",
          "value": "simd_half2x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/title",
          "value": "simd_half4x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/title",
          "value": "simd_half2x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/title",
          "value": "simd_half3x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/title",
          "value": "simd_half4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/title",
          "value": "simd_half4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/title",
          "value": "simd_half3x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/title",
          "value": "simd_half2x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half2x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half2x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/title",
          "value": "simd_half3x3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_half3x3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_half3x3"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
