{
  "abstract": [
    {
      "text": "Reflect images horizontally and vertically.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/image-reflection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image reflection"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images": {
      "abstract": [
        {
          "text": "Translate, rotate, and scale images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying affine transformations to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-affine-transformations-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images": {
      "abstract": [
        {
          "text": "Warp images in three dimensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying projective transformations to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-projective-transformations-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size": {
      "abstract": [
        {
          "text": "Calculate the size of the temporary buffer needed by a high-level geometry functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Getting the Buffer Size",
      "type": "topic",
      "url": "/documentation/accelerate/getting-the-buffer-size"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-rotation": {
      "abstract": [
        {
          "text": "Rotate images by arbitrary angles or by multiples of 90 degrees.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-rotation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image rotation",
      "type": "topic",
      "url": "/documentation/accelerate/image-rotation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-scaling": {
      "abstract": [
        {
          "text": "Scale interlaced and planar images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-scaling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image scaling",
      "type": "topic",
      "url": "/documentation/accelerate/image-scaling"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-shearing": {
      "abstract": [
        {
          "text": "Shear images horizontally and vertically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image shearing",
      "type": "topic",
      "url": "/documentation/accelerate/image-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage": {
      "abstract": [
        {
          "text": "Learn how vImage resamples image data during geometric operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
      "kind": "article",
      "role": "article",
      "title": "Resampling in vImage",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-in-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit-per-channel, 4-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16F"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_ARGB16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_argb16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16S(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a signed 16-bit-per-channel, 4-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16S"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16S(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16S"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_ARGB16S(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_argb16s(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16U(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an unsigned 16-bit-per-channel, 4-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16U"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16U(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB16U"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_ARGB16U(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_argb16u(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB8888(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an 8-bit-per-channel, 4-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB8888"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB8888(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGB8888"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_ARGB8888(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_argb8888(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGBFFFF(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a 32-bit-per-channel, 4-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGBFFFF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGBFFFF(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_ARGBFFFF"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_ARGBFFFF(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_argbffff(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_CbCr16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit-per-channel, 2-channel interleaved image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_CbCr16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_CbCr16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_CbCr16F"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_CbCr16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_cbcr16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit planar image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar16F"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_Planar16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_planar16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16U(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an unsigned 16-bit planar image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar16U"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16U(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar16U"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_Planar16U(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_planar16u(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar8(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an 8-bit planar image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar8(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_Planar8"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_Planar8(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_planar8(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_PlanarF(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a 32-bit planar image horizontally across the center vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_PlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_PlanarF(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageHorizontalReflect_PlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImageHorizontalReflect_PlanarF(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagehorizontalreflect_planarf(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit-per-channel, 4-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16F"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_ARGB16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_argb16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16S(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a signed 16-bit-per-channel, 4-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16S"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16S(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16S"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_ARGB16S(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_argb16s(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16U(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an unsigned 16-bit-per-channel, 4-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16U"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16U(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB16U"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_ARGB16U(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_argb16u(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB8888(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an 8-bit-per-channel, 4-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB8888"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB8888(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGB8888"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_ARGB8888(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_argb8888(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGBFFFF(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a 32-bit-per-channel, 4-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGBFFFF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGBFFFF(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_ARGBFFFF"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_ARGBFFFF(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_argbffff(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_CbCr16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit-per-channel, 2-channel interleaved image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_CbCr16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_CbCr16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_CbCr16F"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_CbCr16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_cbcr16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16F(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a floating-point 16-bit planar image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar16F"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16F(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar16F"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_Planar16F(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_planar16f(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16U(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an unsigned 16-bit planar image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar16U"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16U(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar16U"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_Planar16U(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_planar16u(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar8(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects an 8-bit planar image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar8(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_Planar8"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_Planar8(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_planar8(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_PlanarF(_:_:_:)": {
      "abstract": [
        {
          "text": "Reflects a 32-bit planar image vertically across the center horizontal line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_PlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_PlanarF(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageVerticalReflect_PlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImageVerticalReflect_PlanarF(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageverticalreflect_planarf(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPUs vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-geometric-transforms-to-image-buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/image-shearing",
        "doc://com.apple.accelerate/documentation/Accelerate/image-rotation",
        "doc://com.apple.accelerate/documentation/Accelerate/image-scaling",
        "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size"
      ],
      "title": "Applying geometric transforms to image buffers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Applying-horizontal-reflection-to-8-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar8(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB8888(_:_:_:)"
      ],
      "title": "Applying horizontal reflection to 8-bit-per-channel buffers"
    },
    {
      "anchor": "Applying-horizontal-reflection-to-16-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16U(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_Planar16F(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_CbCr16F(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16U(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16S(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGB16F(_:_:_:)"
      ],
      "title": "Applying horizontal reflection to 16-bit-per-channel buffers"
    },
    {
      "anchor": "Applying-horizontal-reflection-to-32-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_PlanarF(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageHorizontalReflect_ARGBFFFF(_:_:_:)"
      ],
      "title": "Applying horizontal reflection to 32-bit-per-channel buffers"
    },
    {
      "anchor": "Applying-vertical-reflection-to-8-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar8(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB8888(_:_:_:)"
      ],
      "title": "Applying vertical reflection to 8-bit-per-channel buffers"
    },
    {
      "anchor": "Applying-vertical-reflection-to-16-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16U(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_Planar16F(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_CbCr16F(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16U(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16S(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGB16F(_:_:_:)"
      ],
      "title": "Applying vertical reflection to 16-bit-per-channel buffers"
    },
    {
      "anchor": "Applying-vertical-reflection-to-32-bit-per-channel-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_PlanarF(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageVerticalReflect_ARGBFFFF(_:_:_:)"
      ],
      "title": "Applying vertical reflection to 32-bit-per-channel buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16U(_:_:_:)/title",
          "value": "vImageHorizontalReflect_ARGB16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16U(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_ARGB16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar16U(_:_:_:)/title",
          "value": "vImageVerticalReflect_Planar16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar16U(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_Planar16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_CbCr16F(_:_:_:)/title",
          "value": "vImageVerticalReflect_CbCr16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_CbCr16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_CbCr16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16S(_:_:_:)/title",
          "value": "vImageHorizontalReflect_ARGB16S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16S(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_ARGB16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB8888(_:_:_:)/title",
          "value": "vImageVerticalReflect_ARGB8888"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB8888(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_ARGB8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16F(_:_:_:)/title",
          "value": "vImageVerticalReflect_ARGB16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_ARGB16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar16F(_:_:_:)/title",
          "value": "vImageVerticalReflect_Planar16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_Planar16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16S(_:_:_:)/title",
          "value": "vImageVerticalReflect_ARGB16S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16S(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_ARGB16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar8(_:_:_:)/title",
          "value": "vImageHorizontalReflect_Planar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar8(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_Planar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16U(_:_:_:)/title",
          "value": "vImageVerticalReflect_ARGB16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGB16U(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_ARGB16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGBFFFF(_:_:_:)/title",
          "value": "vImageVerticalReflect_ARGBFFFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_ARGBFFFF(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_ARGBFFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB8888(_:_:_:)/title",
          "value": "vImageHorizontalReflect_ARGB8888"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB8888(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_ARGB8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar16F(_:_:_:)/title",
          "value": "vImageHorizontalReflect_Planar16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_Planar16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_PlanarF(_:_:_:)/title",
          "value": "vImageHorizontalReflect_PlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_PlanarF(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_PlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16F(_:_:_:)/title",
          "value": "vImageHorizontalReflect_ARGB16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGB16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_ARGB16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar16U(_:_:_:)/title",
          "value": "vImageHorizontalReflect_Planar16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_Planar16U(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_Planar16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_CbCr16F(_:_:_:)/title",
          "value": "vImageHorizontalReflect_CbCr16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_CbCr16F(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_CbCr16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_PlanarF(_:_:_:)/title",
          "value": "vImageVerticalReflect_PlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_PlanarF(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_PlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGBFFFF(_:_:_:)/title",
          "value": "vImageHorizontalReflect_ARGBFFFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageHorizontalReflect_ARGBFFFF(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageHorizontalReflect_ARGBFFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar8(_:_:_:)/title",
          "value": "vImageVerticalReflect_Planar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageVerticalReflect_Planar8(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageVerticalReflect_Planar8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
