{
  "abstract": [
    {
      "text": "Shear images horizontally and vertically.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/image-shearing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Image shearing"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/double-precision-horizontal-shearing": {
      "abstract": [
        {
          "text": "Apply double-precision horizontal shearing to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/double-precision-horizontal-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Double-precision horizontal shearing",
      "type": "topic",
      "url": "/documentation/accelerate/double-precision-horizontal-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/double-precision-vertical-shearing": {
      "abstract": [
        {
          "text": "Apply double-precision vertical shearing to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/double-precision-vertical-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Double-precision vertical shearing",
      "type": "topic",
      "url": "/documentation/accelerate/double-precision-vertical-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters": {
      "abstract": [
        {
          "text": "Implement custom linear interpolation to prevent the ringing effects associated with scaling an image with the default Lanczos algorithm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
      "kind": "article",
      "role": "sampleCode",
      "title": "Reducing artifacts with custom resampling filters",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-artifacts-with-custom-resampling-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage": {
      "abstract": [
        {
          "text": "Learn how vImage resamples image data during geometric operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
      "kind": "article",
      "role": "article",
      "title": "Resampling in vImage",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-in-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/single-precision-horizontal-shearing": {
      "abstract": [
        {
          "text": "Apply single-precision horizontal shearing to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/single-precision-horizontal-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Single-precision horizontal shearing",
      "type": "topic",
      "url": "/documentation/accelerate/single-precision-horizontal-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/single-precision-vertical-shearing": {
      "abstract": [
        {
          "text": "Apply single-precision vertical shearing to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/single-precision-vertical-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Single-precision vertical shearing",
      "type": "topic",
      "url": "/documentation/accelerate/single-precision-vertical-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyResamplingFilter(_:)": {
      "abstract": [
        {
          "text": "Disposes of a resampling filter object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageDestroyResamplingFilter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ResamplingFilter",
          "text": "ResamplingFilter"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyResamplingFilter(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageDestroyResamplingFilter"
        }
      ],
      "role": "symbol",
      "title": "vImageDestroyResamplingFilter(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagedestroyresamplingfilter(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterExtent(_:_:)": {
      "abstract": [
        {
          "text": "Returns the maximum sampling radius for a resampling filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGetResamplingFilterExtent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ResamplingFilter",
          "text": "ResamplingFilter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImagePixelCount",
          "text": "vImagePixelCount"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterExtent(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGetResamplingFilterExtent"
        }
      ],
      "role": "symbol",
      "title": "vImageGetResamplingFilterExtent(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegetresamplingfilterextent(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterSize(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the minimum size, in bytes, for the buffer needed by the new resampling filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGetResamplingFilterSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterSize(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGetResamplingFilterSize"
        }
      ],
      "role": "symbol",
      "title": "vImageGetResamplingFilterSize(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegetresamplingfiltersize(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilter(_:_:)": {
      "abstract": [
        {
          "text": "Creates a resampling filter object that corresponds to the default kernel supplied by the vImage framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageNewResamplingFilter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ResamplingFilter",
          "text": "ResamplingFilter"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilter(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageNewResamplingFilter"
        }
      ],
      "role": "symbol",
      "title": "vImageNewResamplingFilter(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagenewresamplingfilter(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a resampling filter object that encapsulates a resampling kernel function that you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageNewResamplingFilterForFunctionUsingBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ResamplingFilter",
          "text": "ResamplingFilter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageNewResamplingFilterForFunctionUsingBuffer"
        }
      ],
      "role": "symbol",
      "title": "vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagenewresamplingfilterforfunctionusingbuffer(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations": {
      "abstract": [
        {
          "text": "Apply image manipulation operations to vImage buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage Operations",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-operations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Resampling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters"
      ],
      "title": "Image Resampling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Shearing-an-image-horizontally",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/single-precision-horizontal-shearing",
        "doc://com.apple.accelerate/documentation/Accelerate/double-precision-horizontal-shearing"
      ],
      "title": "Shearing an image horizontally"
    },
    {
      "anchor": "Shearing-an-image-vertically",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/single-precision-vertical-shearing",
        "doc://com.apple.accelerate/documentation/Accelerate/double-precision-vertical-shearing"
      ],
      "title": "Shearing an image vertically"
    },
    {
      "anchor": "Resampling-filters",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilter(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterExtent(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGetResamplingFilterSize(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageDestroyResamplingFilter(_:)"
      ],
      "title": "Resampling filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageDestroyResamplingFilter(_:)/title",
          "value": "vImageDestroyResamplingFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageDestroyResamplingFilter(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageDestroyResamplingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetResamplingFilterExtent(_:_:)/title",
          "value": "vImageGetResamplingFilterExtent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetResamplingFilterExtent(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGetResamplingFilterExtent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageNewResamplingFilter(_:_:)/title",
          "value": "vImageNewResamplingFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageNewResamplingFilter(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageNewResamplingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)/title",
          "value": "vImageNewResamplingFilterForFunctionUsingBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageNewResamplingFilterForFunctionUsingBuffer(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageNewResamplingFilterForFunctionUsingBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetResamplingFilterSize(_:_:_:_:)/title",
          "value": "vImageGetResamplingFilterSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetResamplingFilterSize(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGetResamplingFilterSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
