{
  "abstract": [
    {
      "text": "A filter that predicts a pixel value by applying a linear function to the pixels located to the left, above, and to the upper-left of the predicted pixel location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kvImage_PNG_FILTER_VALUE_NONE@kvImage_PNG_FILTER_VALUE_PAETH",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kvImage_PNG_FILTER_VALUE_PAETH"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kvImage_PNG_FILTER_VALUE_PAETH"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kvImage_PNG_FILTER_VALUE_PAETH"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_PAETH"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG": {
      "abstract": [
        {
          "text": "A filter that predicts a pixel value from the average of the pixels to the left and above the predicted pixel location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_AVG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_AVG"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_AVG",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_avg"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE": {
      "abstract": [
        {
          "text": "No filtering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_NONE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_NONE"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_NONE",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_none"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH": {
      "abstract": [
        {
          "text": "A filter that predicts a pixel value by applying a linear function to the pixels located to the left, above, and to the upper-left of the predicted pixel location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_PAETH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_PAETH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_PAETH"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_PAETH",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_paeth"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB": {
      "abstract": [
        {
          "text": "A filter that computes the difference between each byte of a pixel and the value of the corresponding byte of the pixel located to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_SUB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_SUB"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_SUB",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_sub"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP": {
      "abstract": [
        {
          "text": "A filter that computes the difference between each byte of a pixel and the value of the corresponding byte of the pixel located above.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_UP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_PNG_FILTER_VALUE_UP"
        }
      ],
      "role": "symbol",
      "title": "kvImage_PNG_FILTER_VALUE_UP",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_png_filter_value_up"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kvImage_PNG_FILTER_VALUE_PAETH"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_PAETH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_NONE",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_SUB",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_UP",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_PNG_FILTER_VALUE_AVG"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kvImage_PNG_FILTER_VALUE_PAETH"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_UP/title",
          "value": "kvImage_PNG_FILTER_VALUE_UP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_UP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_UP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_SUB/title",
          "value": "kvImage_PNG_FILTER_VALUE_SUB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_SUB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_SUB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_PAETH/title",
          "value": "kvImage_PNG_FILTER_VALUE_PAETH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_PAETH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_PAETH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_NONE/title",
          "value": "kvImage_PNG_FILTER_VALUE_NONE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_NONE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_NONE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_AVG/title",
          "value": "kvImage_PNG_FILTER_VALUE_AVG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_PNG_FILTER_VALUE_AVG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_PNG_FILTER_VALUE_AVG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/kvimage_png_filter_value_paeth"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/kvimage_png_filter_value_paeth"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
