{
  "abstract": [
    {
      "text": "Any v410 (component Y’CbCr 10-bit 4:4:4) buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb10"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@vImageYpCbCrType@kvImage444CrYpCb10",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kvImage444CrYpCb10"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@vImageYpCbCrType",
        "text": "vImageYpCbCrType"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kvImage444CrYpCb10"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kvImage444CrYpCb10"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kvImage444CrYpCb10"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@vImageYpCbCrType",
              "text": "vImageYpCbCrType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_Cb8_Cr8": {
      "abstract": [
        {
          "text": "Any y420 or f420 (planar component Y’CbCr 8-bit 4:2:0) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage420Yp8_Cb8_Cr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_Cb8_Cr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage420Yp8_Cb8_Cr8"
        }
      ],
      "role": "symbol",
      "title": "kvImage420Yp8_Cb8_Cr8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage420yp8_cb8_cr8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_CbCr8": {
      "abstract": [
        {
          "text": "Any 420v or 420f (biplanar component Y’CbCr 8-bit 4:2:0, video-range) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage420Yp8_CbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_CbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage420Yp8_CbCr8"
        }
      ],
      "role": "symbol",
      "title": "kvImage420Yp8_CbCr8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage420yp8_cbcr8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp16": {
      "abstract": [
        {
          "text": "Any v216 (component Y’CbCr 10,12,14,16-bit 4:2:2) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp16"
        }
      ],
      "role": "symbol",
      "title": "kvImage422CbYpCrYp16",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage422cbypcryp16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8": {
      "abstract": [
        {
          "text": "Any 2vuy (component Y’CbCr 8-bit 4:2:2) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp8"
        }
      ],
      "role": "symbol",
      "title": "kvImage422CbYpCrYp8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage422cbypcryp8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8_AA8": {
      "abstract": [
        {
          "text": "Any a2vy (first plane: video-range component Y’CbCr 8-bit 4:2:2, ordered Cb Y’0 Cr Y’1; second plane: alpha 8-bit) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp8_AA8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8_AA8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage422CbYpCrYp8_AA8"
        }
      ],
      "role": "symbol",
      "title": "kvImage422CbYpCrYp8_AA8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage422cbypcryp8_aa8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10": {
      "abstract": [
        {
          "text": "Any v210 (component Y’CbCr 10-bit 4:2:2) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10"
        }
      ],
      "role": "symbol",
      "title": "kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage422crypcbypcbypcbypcrypcryp10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage422YpCbYpCr8": {
      "abstract": [
        {
          "text": "Any yuvs or yuvf (component Y’CbCr 8-bit 4:2:2, ordered Y’0 Cb Y’1 Cr) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage422YpCbYpCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage422YpCbYpCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage422YpCbYpCr8"
        }
      ],
      "role": "symbol",
      "title": "kvImage422YpCbYpCr8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage422ypcbypcr8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr16": {
      "abstract": [
        {
          "text": "Any y416 (component Y’CbCrA 16-bit 4:4:4:4, ordered A Y’ Cb Cr, full range alpha, video range Y’CbCr) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage444AYpCbCr16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage444AYpCbCr16"
        }
      ],
      "role": "symbol",
      "title": "kvImage444AYpCbCr16",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage444aypcbcr16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr8": {
      "abstract": [
        {
          "text": "Any r408 or y408 (component Y’CbCrA 8-bit 4:4:4:4, ordered A Y’ Cb Cr, full range alpha, video range Y’CbCr) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage444AYpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage444AYpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kvImage444AYpCbCr8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage444aypcbcr8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CbYpCrA8": {
      "abstract": [
        {
          "text": "Any v408 (component Y’CbCrA 8-bit 4:4:4:4) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage444CbYpCrA8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CbYpCrA8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage444CbYpCrA8"
        }
      ],
      "role": "symbol",
      "title": "kvImage444CbYpCrA8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage444cbypcra8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb10": {
      "abstract": [
        {
          "text": "Any v410 (component Y’CbCr 10-bit 4:4:4) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage444CrYpCb10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage444CrYpCb10"
        }
      ],
      "role": "symbol",
      "title": "kvImage444CrYpCb10",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage444crypcb10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb8": {
      "abstract": [
        {
          "text": "Any v308 (component Y’CbCr 8-bit 4:4:4) buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage444CrYpCb8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage444CrYpCb8"
        }
      ],
      "role": "symbol",
      "title": "kvImage444CrYpCb8",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage444crypcb8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType": {
      "abstract": [
        {
          "text": "Constants that describe the encoding of a YpCbCr image for conversions between RGB and YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "role": "symbol",
      "title": "vImageYpCbCrType",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new YpCbCr type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new YpCbCr type with an unsigned integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/rawValue": {
      "abstract": [
        {
          "text": "The unsigned integer raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype/rawvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_Cb8_Cr8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_CbCr8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp16",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8_AA8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage422YpCbYpCr8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr16",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CbYpCrA8",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb8"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kvImage444CrYpCb10"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444CrYpCb10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_Cb8_Cr8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage420Yp8_CbCr8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp16",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CbYpCrYp8_AA8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage422YpCbYpCr8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr16",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage444AYpCbCr8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CbYpCrA8",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage444CrYpCb8"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kvImage444CrYpCb10"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CbYpCrA8/title",
          "value": "kvImage444CbYpCrA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CbYpCrA8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444CbYpCrA8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CrYpCb10/title",
          "value": "kvImage444CrYpCb10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CrYpCb10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444CrYpCb10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444AYpCbCr8/title",
          "value": "kvImage444AYpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444AYpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444AYpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage420Yp8_CbCr8/title",
          "value": "kvImage420Yp8_CbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage420Yp8_CbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage420Yp8_CbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp8/title",
          "value": "kvImage422CbYpCrYp8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage422CbYpCrYp8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422YpCbYpCr8/title",
          "value": "kvImage422YpCbYpCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422YpCbYpCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage422YpCbYpCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10/title",
          "value": "kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage420Yp8_Cb8_Cr8/title",
          "value": "kvImage420Yp8_Cb8_Cr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage420Yp8_Cb8_Cr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage420Yp8_Cb8_Cr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp16/title",
          "value": "kvImage422CbYpCrYp16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage422CbYpCrYp16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444AYpCbCr16/title",
          "value": "kvImage444AYpCbCr16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444AYpCbCr16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444AYpCbCr16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/title",
          "value": "vImageYpCbCrType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CrYpCb8/title",
          "value": "kvImage444CrYpCb8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage444CrYpCb8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage444CrYpCb8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp8_AA8/title",
          "value": "kvImage422CbYpCrYp8_AA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage422CbYpCrYp8_AA8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage422CbYpCrYp8_AA8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/kvimage444crypcb10"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/kvimage444crypcb10"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
