{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedNoiseShapeMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kvImageConvert_DitherNone@kvImageConvert_OrderedNoiseShapeMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kvImageConvert_OrderedNoiseShapeMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kvImageConvert_OrderedNoiseShapeMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kvImageConvert_OrderedNoiseShapeMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kvImageConvert_OrderedNoiseShapeMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherAtkinson": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will add Atkinson dithering to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherAtkinson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherAtkinson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherAtkinson"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_DitherAtkinson",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_ditheratkinson"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherFloydSteinberg": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will add Floyd-Steinberg dithering to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherFloydSteinberg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherFloydSteinberg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherFloydSteinberg"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_DitherFloydSteinberg",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_ditherfloydsteinberg"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherNone": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will not apply dithering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherNone"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_DitherNone",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_dithernone"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrdered": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will add randomized, pre-computed blue noise to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherOrdered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrdered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherOrdered"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_DitherOrdered",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_ditherordered"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrderedReproducible": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will add reproducible, pre-computed blue noise to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherOrderedReproducible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrderedReproducible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_DitherOrderedReproducible"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_DitherOrderedReproducible",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_ditherorderedreproducible"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedGaussianBlue": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will distribute the noise according to a Gaussian distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedGaussianBlue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedGaussianBlue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedGaussianBlue"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_OrderedGaussianBlue",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_orderedgaussianblue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedNoiseShapeMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedNoiseShapeMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedNoiseShapeMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedNoiseShapeMask"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_OrderedNoiseShapeMask",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_orderednoiseshapemask"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedUniformBlue": {
      "abstract": [
        {
          "text": "A constant that indicates the conversion will distribute the noise uniformly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedUniformBlue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedUniformBlue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageConvert_OrderedUniformBlue"
        }
      ],
      "role": "symbol",
      "title": "kvImageConvert_OrderedUniformBlue",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageconvert_ordereduniformblue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherNone",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrdered",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrderedReproducible",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherFloydSteinberg",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherAtkinson",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedGaussianBlue",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedUniformBlue"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kvImageConvert_OrderedNoiseShapeMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_OrderedNoiseShapeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherNone",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrdered",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherOrderedReproducible",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherFloydSteinberg",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_DitherAtkinson",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedGaussianBlue",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageConvert_OrderedUniformBlue"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kvImageConvert_OrderedNoiseShapeMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherNone/title",
          "value": "kvImageConvert_DitherNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_DitherNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedGaussianBlue/title",
          "value": "kvImageConvert_OrderedGaussianBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedGaussianBlue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_OrderedGaussianBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherOrdered/title",
          "value": "kvImageConvert_DitherOrdered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherOrdered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_DitherOrdered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedNoiseShapeMask/title",
          "value": "kvImageConvert_OrderedNoiseShapeMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedNoiseShapeMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_OrderedNoiseShapeMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherOrderedReproducible/title",
          "value": "kvImageConvert_DitherOrderedReproducible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherOrderedReproducible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_DitherOrderedReproducible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedUniformBlue/title",
          "value": "kvImageConvert_OrderedUniformBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_OrderedUniformBlue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_OrderedUniformBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherFloydSteinberg/title",
          "value": "kvImageConvert_DitherFloydSteinberg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherFloydSteinberg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_DitherFloydSteinberg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherAtkinson/title",
          "value": "kvImageConvert_DitherAtkinson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageConvert_DitherAtkinson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageConvert_DitherAtkinson"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/kvimageconvert_orderednoiseshapemask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/kvimageconvert_orderednoiseshapemask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
