{
  "abstract": [
    {
      "text": "Invalid parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kvImageNoError@kvImageInvalidParameter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kvImageInvalidParameter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kvImageInvalidParameter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kvImageInvalidParameter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kvImageInvalidParameter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch": {
      "abstract": [
        {
          "text": "The function requires the source and destination buffers to have the same height and the same width, but they do not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferSizeMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferSizeMismatch"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferSizeMismatch",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffersizemismatch"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageColorSyncIsAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageColorSyncIsAbsent"
        }
      ],
      "role": "symbol",
      "title": "kvImageColorSyncIsAbsent",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecolorsyncisabsent"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageCoreVideoIsAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageCoreVideoIsAbsent"
        }
      ],
      "role": "symbol",
      "title": "kvImageCoreVideoIsAbsent",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagecorevideoisabsent"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError": {
      "abstract": [
        {
          "text": "A serious error occured inside vImage, which prevented vImage from continuing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInternalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInternalError"
        }
      ],
      "role": "symbol",
      "title": "kvImageInternalError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinternalerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidCVImageFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidcvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle": {
      "abstract": [
        {
          "text": "The edge style specified is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidEdgeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidEdgeStyle",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidedgestyle"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidImageFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize": {
      "abstract": [
        {
          "text": "Either the kernel height, the kernel width, or both, are even.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidKernelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidKernelSize"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidKernelSize",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidkernelsize"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_X",
          "type": "codeVoice"
        },
        {
          "text": " parameter that specifies the left edge of the region of interest is greater than the width of the source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_X"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_X"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidOffset_X",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidoffset_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_Y",
          "type": "codeVoice"
        },
        {
          "text": " parameter that specifies the top edge of the region of interest is greater than the height of the source image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_Y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidOffset_Y"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidOffset_Y",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidoffset_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter": {
      "abstract": [
        {
          "text": "Invalid parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kvImageInvalidParameter",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinvalidparameter"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError": {
      "abstract": [
        {
          "text": "An attempt to allocate memory failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageMemoryAllocationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageMemoryAllocationError"
        }
      ],
      "role": "symbol",
      "title": "kvImageMemoryAllocationError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagememoryallocationerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError": {
      "abstract": [
        {
          "text": "The vImage function completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageNoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenoerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument": {
      "abstract": [
        {
          "text": "A pointer parameter is ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": " and it must not be.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNullPointerArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNullPointerArgument"
        }
      ],
      "role": "symbol",
      "title": "kvImageNullPointerArgument",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenullpointerargument"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer": {
      "abstract": [
        {
          "text": "The region of interest, as specified by the ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_X",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "srcOffsetToROI_Y",
          "type": "codeVoice"
        },
        {
          "text": " parameters and the height and width of the destination buffer, extends beyond the bottom edge or right edge of the source buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageRoiLargerThanInputBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageRoiLargerThanInputBuffer"
        }
      ],
      "role": "symbol",
      "title": "kvImageRoiLargerThanInputBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageroilargerthaninputbuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit": {
      "abstract": [
        {
          "text": "The flag is not recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageUnknownFlagsBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageUnknownFlagsBit"
        }
      ],
      "role": "symbol",
      "title": "kvImageUnknownFlagsBit",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageunknownflagsbit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error": {
      "abstract": [
        {
          "text": "An error that occurs during a vImage operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "vImage.Error",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/error"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/Error",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kvImageInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageRoiLargerThanInputBuffer",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidKernelSize",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidEdgeStyle",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_X",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidOffset_Y",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageMemoryAllocationError",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageNullPointerArgument",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferSizeMismatch",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageUnknownFlagsBit",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageColorSyncIsAbsent",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageCoreVideoIsAbsent",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInternalError",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidCVImageFormat",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInvalidImageFormat"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kvImageInvalidParameter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidParameter/title",
          "value": "kvImageInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageMemoryAllocationError/title",
          "value": "kvImageMemoryAllocationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageMemoryAllocationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageMemoryAllocationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_Y/title",
          "value": "kvImageInvalidOffset_Y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_Y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidOffset_Y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageFormat/title",
          "value": "kvImageInvalidImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferSizeMismatch/title",
          "value": "kvImageBufferSizeMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferSizeMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferSizeMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInternalError/title",
          "value": "kvImageInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInternalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidEdgeStyle/title",
          "value": "kvImageInvalidEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageRoiLargerThanInputBuffer/title",
          "value": "kvImageRoiLargerThanInputBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageRoiLargerThanInputBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageRoiLargerThanInputBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageColorSyncIsAbsent/title",
          "value": "kvImageColorSyncIsAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageColorSyncIsAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageColorSyncIsAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnknownFlagsBit/title",
          "value": "kvImageUnknownFlagsBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUnknownFlagsBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageUnknownFlagsBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCoreVideoIsAbsent/title",
          "value": "kvImageCoreVideoIsAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageCoreVideoIsAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageCoreVideoIsAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidCVImageFormat/title",
          "value": "kvImageInvalidCVImageFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidCVImageFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title",
          "value": "kvImageNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_X/title",
          "value": "kvImageInvalidOffset_X"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidOffset_X/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidOffset_X"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNullPointerArgument/title",
          "value": "kvImageNullPointerArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNullPointerArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNullPointerArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidKernelSize/title",
          "value": "kvImageInvalidKernelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInvalidKernelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInvalidKernelSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/kvimageinvalidparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/kvimageinvalidparameter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
