{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageGetTempBufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"mentions":["doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images"],"kind":"mentions"},{"kind":"content","content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"When you set this flag, the function returns the number of bytes required for the temporary buffer instead of performing the operation. A negative value indicates an error, and if the function does not accept a temporary buffer, zero is returned.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"text":"A flag that returns the minimum temporary buffer size for the operation, given the parameters provided.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"kvImageGetTempBufferSize","kind":"identifier"}],"title":"kvImageGetTempBufferSize","externalID":"c:@Ea@kvImageNoFlags@kvImageGetTempBufferSize","modules":[{"name":"Accelerate"}],"symbolKind":"var","roleHeading":"Global Variable","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"5.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"5.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.4"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageGetTempBufferSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/kvImageGetTempBufferSize"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImage/Options","doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","doc://com.apple.accelerate/documentation/Accelerate/kvImageLeaveAlphaUnchanged","doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","doc://com.apple.accelerate/documentation/Accelerate/kvImageHighQualityResampling","doc://com.apple.accelerate/documentation/Accelerate/kvImagePrintDiagnosticsToConsole","doc://com.apple.accelerate/documentation/Accelerate/kvImageNoAllocate","doc://com.apple.accelerate/documentation/Accelerate/kvImageHDRContent","doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotClamp","doc://com.apple.accelerate/documentation/Accelerate/kvImageUseFP16Accumulator"],"title":"Constants","anchor":"Constants"}],"variants":[{"paths":["/documentation/accelerate/kvimagegettempbuffersize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/kvimagegettempbuffersize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoAllocate":{"navigatorTitle":[{"text":"kvImageNoAllocate","kind":"identifier"}],"title":"kvImageNoAllocate","url":"/documentation/accelerate/kvimagenoallocate","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoAllocate","abstract":[{"text":"A flag that prevents vImage from allocating additional storage.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageNoAllocate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotClamp":{"abstract":[{"type":"text","text":"A flag that disables clamping in some conversions to floating-point formats."}],"navigatorTitle":[{"kind":"identifier","text":"kvImageDoNotClamp"}],"title":"kvImageDoNotClamp","type":"topic","kind":"symbol","url":"/documentation/accelerate/kvimagedonotclamp","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotClamp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kvImageDoNotClamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.accelerate/documentation/Accelerate/kvImageHighQualityResampling":{"navigatorTitle":[{"kind":"identifier","text":"kvImageHighQualityResampling"}],"url":"/documentation/accelerate/kvimagehighqualityresampling","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageHighQualityResampling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"text":"A flag that uses a higher-quality, slower resampling filter for geometry operations.","type":"text"}],"kind":"symbol","type":"topic","title":"kvImageHighQualityResampling","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageHighQualityResampling"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageGetTempBufferSize":{"abstract":[{"text":"A flag that returns the minimum temporary buffer size for the operation, given the parameters provided.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"kvImageGetTempBufferSize","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageGetTempBufferSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"kvImageGetTempBufferSize","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageGetTempBufferSize","url":"/documentation/accelerate/kvimagegettempbuffersize"},"doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images":{"title":"Applying geometric transforms to images","identifier":"doc://com.apple.accelerate/documentation/Accelerate/applying-geometric-transforms-to-images","role":"article","kind":"article","url":"/documentation/accelerate/applying-geometric-transforms-to-images","abstract":[{"text":"Reflect, shear, rotate, and scale image buffers using vImage.","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageHDRContent":{"navigatorTitle":[{"kind":"identifier","text":"kvImageHDRContent"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageHDRContent","kind":"symbol","title":"kvImageHDRContent","type":"topic","url":"/documentation/accelerate/kvimagehdrcontent","abstract":[{"text":"A flag that uses HDR-aware methods.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kvImageHDRContent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags":{"abstract":[{"text":"A flag that sets the behavior to the default.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kvImageNoFlags"}],"title":"kvImageNoFlags","type":"topic","kind":"symbol","url":"/documentation/accelerate/kvimagenoflags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageNoFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"symbol","url":"/documentation/Swift/Int","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/kvImagePrintDiagnosticsToConsole":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kvImagePrintDiagnosticsToConsole","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"/documentation/accelerate/kvimageprintdiagnosticstoconsole","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImagePrintDiagnosticsToConsole","abstract":[{"type":"text","text":"A flag that prints a debug message if the operation fails."}],"navigatorTitle":[{"kind":"identifier","text":"kvImagePrintDiagnosticsToConsole"}],"title":"kvImagePrintDiagnosticsToConsole","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile":{"navigatorTitle":[{"kind":"identifier","text":"kvImageDoNotTile"}],"type":"topic","abstract":[{"text":"A flag that disables vImage internal tiling routines.","type":"text"}],"url":"/documentation/accelerate/kvimagedonottile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageDoNotTile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","title":"kvImageDoNotTile"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageUseFP16Accumulator":{"type":"topic","abstract":[{"text":"A flag that specifies vImage uses faster but lower-precision internal arithmetic for floating-point 16-bit operations.","type":"text"}],"role":"symbol","url":"/documentation/accelerate/kvimageusefp16accumulator","title":"kvImageUseFP16Accumulator","navigatorTitle":[{"kind":"identifier","text":"kvImageUseFP16Accumulator"}],"kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageUseFP16Accumulator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"kvImageUseFP16Accumulator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage/Options":{"abstract":[{"text":"Set flags on vImage operations to specify processing options.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Options","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Options","kind":"identifier"}],"title":"vImage.Options","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage/Options","url":"/documentation/accelerate/vimage/options"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageLeaveAlphaUnchanged":{"title":"kvImageLeaveAlphaUnchanged","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageLeaveAlphaUnchanged","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageLeaveAlphaUnchanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"kvImageLeaveAlphaUnchanged"}],"url":"/documentation/accelerate/kvimageleavealphaunchanged","abstract":[{"type":"text","text":"A flag that restricts the operation to red, green, and blue channels only."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"5.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"5.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.4"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"kvImageGetTempBufferSize","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"kvImageGetTempBufferSize","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Constants","title":"Constants","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","doc://com.apple.accelerate/documentation/Accelerate/kvImageLeaveAlphaUnchanged","doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","doc://com.apple.accelerate/documentation/Accelerate/kvImageHighQualityResampling","doc://com.apple.accelerate/documentation/Accelerate/kvImagePrintDiagnosticsToConsole","doc://com.apple.accelerate/documentation/Accelerate/kvImageNoAllocate","doc://com.apple.accelerate/documentation/Accelerate/kvImageHDRContent","doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotClamp","doc://com.apple.accelerate/documentation/Accelerate/kvImageUseFP16Accumulator"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"identifier","text":"kvImageGetTempBufferSize"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"kvImageNoAllocate","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoAllocate/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageNoAllocate"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoAllocate/fragments"},{"op":"replace","value":"kvImageDoNotClamp","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotClamp/title"},{"op":"replace","value":[{"text":"kvImageDoNotClamp","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotClamp/fragments"},{"op":"replace","value":"kvImageHighQualityResampling","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageHighQualityResampling/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageHighQualityResampling"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageHighQualityResampling/fragments"},{"op":"replace","value":"kvImageGetTempBufferSize","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGetTempBufferSize/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageGetTempBufferSize"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageGetTempBufferSize/fragments"},{"op":"replace","value":"kvImageHDRContent","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageHDRContent/title"},{"op":"replace","value":[{"text":"kvImageHDRContent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageHDRContent/fragments"},{"op":"replace","value":"kvImageNoFlags","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageNoFlags"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/fragments"},{"op":"replace","value":"kvImagePrintDiagnosticsToConsole","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImagePrintDiagnosticsToConsole/title"},{"op":"replace","value":[{"text":"kvImagePrintDiagnosticsToConsole","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImagePrintDiagnosticsToConsole/fragments"},{"op":"replace","value":"kvImageDoNotTile","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/title"},{"op":"replace","value":[{"text":"kvImageDoNotTile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/fragments"},{"op":"replace","value":"kvImageUseFP16Accumulator","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUseFP16Accumulator/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageUseFP16Accumulator"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageUseFP16Accumulator/fragments"},{"op":"replace","value":"kvImageLeaveAlphaUnchanged","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageLeaveAlphaUnchanged/title"},{"op":"replace","value":[{"kind":"identifier","text":"kvImageLeaveAlphaUnchanged"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageLeaveAlphaUnchanged/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}