{
  "abstract": [
    {
      "text": "If the image has a XYZ color model, the buffer contains the ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Z",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kvImageBufferTypeCode_EndOfList@kvImageBufferTypeCode_XYZ_Z",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kvImageBufferTypeCode_XYZ_Z"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kvImageBufferTypeCode_XYZ_Z"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kvImageBufferTypeCode_XYZ_Z"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_Z"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha": {
      "abstract": [
        {
          "text": "The buffer contains the alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Alpha"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Alpha",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_alpha"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat": {
      "abstract": [
        {
          "text": "The buffer contains data describable as a vImage Core Graphics image format as a single buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CGFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CGFormat"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CGFormat",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cgformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the black channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Black"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Black",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_black"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the cyan channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Cyan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Cyan"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Cyan",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_cyan"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the magenta channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Magenta"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Magenta",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_magenta"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow": {
      "abstract": [
        {
          "text": "If the image has a CMYK color model, the buffer contains the yellow channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CMYK_Yellow"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CMYK_Yellow",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cmyk_yellow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr": {
      "abstract": [
        {
          "text": "The buffer contains luminance and both chroma channels interleaved according to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " image type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cvpixelbuffer_ycbcr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb": {
      "abstract": [
        {
          "text": "The buffer contains the blue chrominance channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Cb"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma": {
      "abstract": [
        {
          "text": "The buffer contains both chrominance channels, interleaved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chroma"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chroma"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Chroma",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_chroma"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky": {
      "abstract": [
        {
          "text": "The buffer contains chunky data not describable as a vImage Core Graphics image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chunky"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_Chunky"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_Chunky",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_chunky"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel1",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel10",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel11",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel11"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel12",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel12"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_ColorSpaceChannel13",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_colorspacechannel13"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z": {
      "abstract": [
        {
          "text": "If the image has a XYZ color model, the buffer contains the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Z",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_XYZ_Z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageBufferTypeCode_XYZ_Z"
        }
      ],
      "role": "symbol",
      "title": "kvImageBufferTypeCode_XYZ_Z",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagebuffertypecode_xyz_z"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat": {
      "abstract": [
        {
          "text": "An immutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConstCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConstCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageConstCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconstcvimageformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kvImageBufferTypeCode_XYZ_Z"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_Z"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Alpha",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CGFormat",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Black",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Cyan",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Magenta",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CMYK_Yellow",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_CVPixelBuffer_YCbCr",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Cb",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chroma",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_Chunky",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel1",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel10",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel11",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel12",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageBufferTypeCode_ColorSpaceChannel13"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kvImageBufferTypeCode_XYZ_Z"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Cyan/title",
          "value": "kvImageBufferTypeCode_CMYK_Cyan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Cyan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Cyan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Black/title",
          "value": "kvImageBufferTypeCode_CMYK_Black"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Black/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Black"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Alpha/title",
          "value": "kvImageBufferTypeCode_Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Magenta/title",
          "value": "kvImageBufferTypeCode_CMYK_Magenta"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Magenta/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Magenta"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/title",
          "value": "vImageConstCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConstCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConstCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel10/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel1/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel11/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CVPixelBuffer_YCbCr/title",
          "value": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CVPixelBuffer_YCbCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CVPixelBuffer_YCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel13/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel13"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel13/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel13"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cb/title",
          "value": "kvImageBufferTypeCode_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Yellow/title",
          "value": "kvImageBufferTypeCode_CMYK_Yellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CMYK_Yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CMYK_Yellow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chroma/title",
          "value": "kvImageBufferTypeCode_Chroma"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chroma/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Chroma"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chunky/title",
          "value": "kvImageBufferTypeCode_Chunky"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_Chunky/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_Chunky"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Z/title",
          "value": "kvImageBufferTypeCode_XYZ_Z"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_XYZ_Z/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_XYZ_Z"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel12/title",
          "value": "kvImageBufferTypeCode_ColorSpaceChannel12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_ColorSpaceChannel12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_ColorSpaceChannel12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CGFormat/title",
          "value": "kvImageBufferTypeCode_CGFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageBufferTypeCode_CGFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageBufferTypeCode_CGFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/kvimagebuffertypecode_xyz_z"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/kvimagebuffertypecode_xyz_z"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
