{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@LA_NONNULL",
    "fragments": [
      {
        "kind": "identifier",
        "text": "LA_NONNULL"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LA_NONNULL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "LA_NONNULL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LA_NONNULL"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
        }
      ],
      "role": "symbol",
      "title": "LA_ATTRIBUTE_ENABLE_LOGGING",
      "type": "topic",
      "url": "/documentation/accelerate/la_attribute_enable_logging"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/accelerate/la_availability"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_CONST"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_CONST",
      "type": "topic",
      "url": "/documentation/accelerate/la_const"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_DEFAULT_ATTRIBUTES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_DEFAULT_ATTRIBUTES"
        }
      ],
      "role": "symbol",
      "title": "LA_DEFAULT_ATTRIBUTES",
      "type": "topic",
      "url": "/documentation/accelerate/la_default_attributes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_DIMENSION_MISMATCH_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_DIMENSION_MISMATCH_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_DIMENSION_MISMATCH_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_dimension_mismatch_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_EXPORT",
      "type": "topic",
      "url": "/documentation/accelerate/la_export"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_DIAGONALLY_DOMINANT",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_diagonally_dominant"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_POSITIVE_DEFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_POSITIVE_DEFINITE"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_POSITIVE_DEFINITE",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_positive_definite"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_SYMMETRIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_SYMMETRIC"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_SYMMETRIC",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_symmetric"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_FUNCTION"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_FUNCTION",
      "type": "topic",
      "url": "/documentation/accelerate/la_function"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_INTERNAL_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_INTERNAL_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_INTERNAL_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_internal_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_INVALID_PARAMETER_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_INVALID_PARAMETER_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_INVALID_PARAMETER_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_invalid_parameter_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_L1_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_L1_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_L1_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_l1_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_L2_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_L2_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_L2_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_l2_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_LINF_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_LINF_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_LINF_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_linf_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_NONNULL"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_NONNULL",
      "type": "topic",
      "url": "/documentation/accelerate/la_nonnull"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_DIAGONALLY_DOMINANT/title",
          "value": "LA_FEATURE_DIAGONALLY_DOMINANT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_DIAGONALLY_DOMINANT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DIMENSION_MISMATCH_ERROR/title",
          "value": "LA_DIMENSION_MISMATCH_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DIMENSION_MISMATCH_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_DIMENSION_MISMATCH_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_ATTRIBUTE_ENABLE_LOGGING/title",
          "value": "LA_ATTRIBUTE_ENABLE_LOGGING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_ATTRIBUTE_ENABLE_LOGGING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L2_NORM/title",
          "value": "LA_L2_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L2_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_L2_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_LINF_NORM/title",
          "value": "LA_LINF_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_LINF_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_LINF_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INTERNAL_ERROR/title",
          "value": "LA_INTERNAL_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INTERNAL_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_INTERNAL_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DEFAULT_ATTRIBUTES/title",
          "value": "LA_DEFAULT_ATTRIBUTES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DEFAULT_ATTRIBUTES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_DEFAULT_ATTRIBUTES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INVALID_PARAMETER_ERROR/title",
          "value": "LA_INVALID_PARAMETER_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INVALID_PARAMETER_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_INVALID_PARAMETER_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_SYMMETRIC/title",
          "value": "LA_FEATURE_SYMMETRIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_SYMMETRIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_SYMMETRIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L1_NORM/title",
          "value": "LA_L1_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L1_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_L1_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_POSITIVE_DEFINITE/title",
          "value": "LA_FEATURE_POSITIVE_DEFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_POSITIVE_DEFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_POSITIVE_DEFINITE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/la_nonnull"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
