{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/la_scalar_type_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@la_scalar_type_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "la_scalar_type_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "la_scalar_type_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "la_scalar_type_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "la_scalar_type_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/OS_la_object": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_la_object"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/OS_la_object",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_la_object"
        }
      ],
      "role": "symbol",
      "title": "OS_la_object",
      "type": "topic",
      "url": "/documentation/accelerate/os_la_object"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_attribute_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_attribute_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_attribute_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_attribute_t"
        }
      ],
      "role": "symbol",
      "title": "la_attribute_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_attribute_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_count_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_count_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_count_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_count_t"
        }
      ],
      "role": "symbol",
      "title": "la_count_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_count_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_deallocator_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_deallocator_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_deallocator_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_deallocator_t"
        }
      ],
      "role": "symbol",
      "title": "la_deallocator_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_deallocator_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_hint_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_hint_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_hint_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_hint_t"
        }
      ],
      "role": "symbol",
      "title": "la_hint_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_hint_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_index_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_index_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_index_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_index_t"
        }
      ],
      "role": "symbol",
      "title": "la_index_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_index_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_norm_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_norm_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_norm_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_norm_t"
        }
      ],
      "role": "symbol",
      "title": "la_norm_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_norm_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_object_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_object_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_object_t"
        }
      ],
      "role": "symbol",
      "title": "la_object_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_object_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_scalar_type_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_scalar_type_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_scalar_type_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_scalar_type_t"
        }
      ],
      "role": "symbol",
      "title": "la_scalar_type_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_scalar_type_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_status_t": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "la_status_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_status_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "la_status_t"
        }
      ],
      "role": "symbol",
      "title": "la_status_t",
      "type": "topic",
      "url": "/documentation/accelerate/la_status_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/la_attribute_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_count_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_deallocator_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_hint_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_index_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_norm_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_object_t",
        "doc://com.apple.accelerate/documentation/Accelerate/la_status_t",
        "doc://com.apple.accelerate/documentation/Accelerate/OS_la_object"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "la_scalar_type_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_scalar_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_scalar_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/la_attribute_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_count_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_deallocator_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_hint_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_index_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_norm_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_object_t",
                "doc://com.apple.accelerate/documentation/Accelerate/la_status_t",
                "doc://com.apple.accelerate/documentation/Accelerate/OS_la_object"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "la_scalar_type_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_scalar_type_t/title",
          "value": "la_scalar_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_scalar_type_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_scalar_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_scalar_type_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_scalar_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_hint_t/title",
          "value": "la_hint_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_hint_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_hint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_hint_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_hint_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_object_t/title",
          "value": "la_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_status_t/title",
          "value": "la_status_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_status_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_status_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_status_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_count_t/title",
          "value": "la_count_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_count_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_count_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_count_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_count_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_index_t/title",
          "value": "la_index_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_index_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_index_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_index_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_index_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1OS_la_object/title",
          "value": "OS_la_object"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1OS_la_object/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_la_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1OS_la_object/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_la_object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_deallocator_t/title",
          "value": "la_deallocator_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_deallocator_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_deallocator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_deallocator_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_deallocator_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_attribute_t/title",
          "value": "la_attribute_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_attribute_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_attribute_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_attribute_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_attribute_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_norm_t/title",
          "value": "la_norm_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_norm_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "la_norm_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1la_norm_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "la_norm_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/la_scalar_type_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/la_scalar_type_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
