{
  "abstract": [
    {
      "text": "A type for a planar, 8-bits-per-channel, unsigned pixel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@Pixel_8",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Pixel_8"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Pixel_8"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "Pixel_8"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Pixel_8"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16F"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16F",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16f"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F16F": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16F16F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F16F",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16F16F"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16F16F",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16f16f"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16Q12": {
      "abstract": [
        {
          "text": "A type for a signed 16-bit, fixed-point number with 12 bits of fractional precision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16Q12"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16Q12",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16Q12"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16Q12",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16q12"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S": {
      "abstract": [
        {
          "text": "A type for a planar, 16-bits-per-channel, signed pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16S"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16S"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16S",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S16S": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16S16S"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S16S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16S16S"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16S16S",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16s16s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U": {
      "abstract": [
        {
          "text": "A type for a planar, 16-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16U"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16U"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16U",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16u"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U16U": {
      "abstract": [
        {
          "text": "A type for a two-channel, 16-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_16U16U"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U16U",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_16U16U"
        }
      ],
      "role": "symbol",
      "title": "Pixel_16U16U",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_16u16u"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_32U": {
      "abstract": [
        {
          "text": "A type you use for the XRGB2101010 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_32U"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_32U",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_32U"
        }
      ],
      "role": "symbol",
      "title": "Pixel_32U",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_32u"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8": {
      "abstract": [
        {
          "text": "A type for a planar, 8-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_8"
        }
      ],
      "role": "symbol",
      "title": "Pixel_8",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_88": {
      "abstract": [
        {
          "text": "A type for a two-channel, 8-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_88"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_88",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_88"
        }
      ],
      "role": "symbol",
      "title": "Pixel_88",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_88"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8888": {
      "abstract": [
        {
          "text": "A type for a four-channel, 8-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_8888"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8888",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_8888"
        }
      ],
      "role": "symbol",
      "title": "Pixel_8888",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_8888"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16F"
        }
      ],
      "role": "symbol",
      "title": "Pixel_ARGB_16F",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_argb_16f"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16S": {
      "abstract": [
        {
          "text": "A type for a four-channel, 16-bits-per-channel, signed pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16S"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16S",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16S"
        }
      ],
      "role": "symbol",
      "title": "Pixel_ARGB_16S",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_argb_16s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16U": {
      "abstract": [
        {
          "text": "A type for a four-channel, 16-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16U"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16U",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_ARGB_16U"
        }
      ],
      "role": "symbol",
      "title": "Pixel_ARGB_16U",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_argb_16u"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_F": {
      "abstract": [
        {
          "text": "A type for a planar, 32-bits-per-channel, floating-point pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_F"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_F",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_F"
        }
      ],
      "role": "symbol",
      "title": "Pixel_F",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_f"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF": {
      "abstract": [
        {
          "text": "A type for a four-channel, 32-bits-per-channel, floating-point pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_FFFF"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_FFFF"
        }
      ],
      "role": "symbol",
      "title": "Pixel_FFFF",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_ffff"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5UInt8V": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5UInt8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt8",
      "type": "topic",
      "url": "/documentation/Swift/UInt8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pixel-Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_88",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8888",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_F",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_32U",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16U",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U16U",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16Q12",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16S",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F16F",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S16S",
        "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F"
      ],
      "title": "Pixel Formats"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "Pixel_8"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pixel-Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_88",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8888",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_F",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_FFFF",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_32U",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16U",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16U16U",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16Q12",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16S",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16F16F",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_16S16S",
                "doc://com.apple.accelerate/documentation/Accelerate/Pixel_ARGB_16F"
              ],
              "title": "Pixel Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "Pixel_8"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S/title",
          "value": "Pixel_16S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/title",
          "value": "Pixel_ARGB_16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16F/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8888/title",
          "value": "Pixel_8888"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8888/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8888/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8888"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/title",
          "value": "Pixel_8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_88/title",
          "value": "Pixel_88"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_88/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_88"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_88/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_88"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_32U/title",
          "value": "Pixel_32U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_32U/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_32U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_32U/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_32U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F16F/title",
          "value": "Pixel_16F16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F16F/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16F16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F16F/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16F16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U16U/title",
          "value": "Pixel_16U16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U16U/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16U16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U16U/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16U16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16S/title",
          "value": "Pixel_ARGB_16S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16S/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S16S/title",
          "value": "Pixel_16S16S"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S16S/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16S16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16S16S/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16S16S"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/title",
          "value": "Pixel_FFFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_FFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_FFFF/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_FFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16Q12/title",
          "value": "Pixel_16Q12"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16Q12/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16Q12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16Q12/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16Q12"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_F/title",
          "value": "Pixel_F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_F/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_F/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/title",
          "value": "Pixel_16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16U/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16U/title",
          "value": "Pixel_ARGB_16U"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16U/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_ARGB_16U/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_ARGB_16U"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F/title",
          "value": "Pixel_16F"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16F"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_16F/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_16F"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/pixel_8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/pixel_8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
