{
  "abstract": [
    {
      "text": "Constants that indicate the status of a quadrature operation.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@quadrature_status",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "quadrature_status"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "quadrature_status"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "quadrature_status"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quadrature_status"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ALLOC_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates that memory allocation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_ALLOC_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ALLOC_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_ALLOC_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_ALLOC_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_alloc_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates that a generic error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates bad integrand behaviour, or that an excessive roundoff error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_bad_behaviour_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_MAX_EVAL_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates that the requested accuracy limit could not be reached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_MAX_EVAL_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_MAX_EVAL_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_MAX_EVAL_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_MAX_EVAL_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_max_eval_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTERNAL_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates that an internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTERNAL_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTERNAL_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTERNAL_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTERNAL_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_internal_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INVALID_ARG_ERROR": {
      "abstract": [
        {
          "text": "A constant that indicates that an invalid argument was passed to the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INVALID_ARG_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INVALID_ARG_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INVALID_ARG_ERROR"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INVALID_ARG_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_invalid_arg_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_SUCCESS": {
      "abstract": [
        {
          "text": "A constant that indicates that the Quadrature operation was successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_SUCCESS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_status",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_SUCCESS",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_success"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Quadrature": {
      "abstract": [
        {
          "text": "A structure that approximates the definite integral of a function over a finite interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Quadrature"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Quadrature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Quadrature"
        }
      ],
      "role": "symbol",
      "title": "Quadrature",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrate": {
      "abstract": [
        {
          "text": "Computes an approximation to the definite integral of a function on a specified interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "quadrature_integrate"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrate",
      "kind": "symbol",
      "role": "symbol",
      "title": "quadrature_integrate",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator": {
      "abstract": [
        {
          "text": "Constants that specify integration algorithms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadrature_integrator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quadrature_integrator"
        }
      ],
      "role": "symbol",
      "title": "quadrature_integrator",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status": {
      "abstract": [
        {
          "text": "Constants that indicate the status of a quadrature operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadrature_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quadrature_status"
        }
      ],
      "role": "symbol",
      "title": "quadrature_status",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_status"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_status/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_status/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_status/rawvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Quadrature",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/Quadrature",
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator"
      ],
      "title": "Quadrature"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_status/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ALLOC_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_MAX_EVAL_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTERNAL_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INVALID_ARG_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_SUCCESS"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "quadrature_status"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ALLOC_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_MAX_EVAL_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTERNAL_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INVALID_ARG_ERROR",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_SUCCESS"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Quadrature",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrate",
                "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator"
              ],
              "title": "Quadrature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "quadrature_status"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_MAX_EVAL_ERROR/title",
          "value": "QUADRATURE_INTEGRATE_MAX_EVAL_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_MAX_EVAL_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_MAX_EVAL_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_SUCCESS/title",
          "value": "QUADRATURE_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR/title",
          "value": "QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_ERROR/title",
          "value": "QUADRATURE_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTERNAL_ERROR/title",
          "value": "QUADRATURE_INTERNAL_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTERNAL_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTERNAL_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INVALID_ARG_ERROR/title",
          "value": "QUADRATURE_INVALID_ARG_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INVALID_ARG_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INVALID_ARG_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_integrator/title",
          "value": "quadrature_integrator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_integrator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_integrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_integrator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_integrator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_status/title",
          "value": "quadrature_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1quadrature_status/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "quadrature_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_ALLOC_ERROR/title",
          "value": "QUADRATURE_ALLOC_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_ALLOC_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_ALLOC_ERROR"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/quadrature_status"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/quadrature_status"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
