{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG": {
      "abstract": [
        {
          "text": "A constant that specifies a simple globally adaptive integrator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_integrator",
          "text": "quadrature_integrator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAG"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_QAG",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_qag"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS": {
      "abstract": [
        {
          "text": "A constant that specifies global adaptive quadrature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAGS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_integrator",
          "text": "quadrature_integrator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAGS"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_QAGS",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_qags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_qags_workspace_per_interval"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_qag_workspace_per_interval"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QNG": {
      "abstract": [
        {
          "text": "A constant that specifies a simple non-adaptive automatic integrator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QNG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@quadrature_integrator",
          "text": "quadrature_integrator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QNG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QUADRATURE_INTEGRATE_QNG"
        }
      ],
      "role": "symbol",
      "title": "QUADRATURE_INTEGRATE_QNG",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrate_qng"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrator/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrator/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/quadrature_integrator/rawvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/quadrature_integrator/rawValue",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QNG",
        "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAG",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QNG",
                "doc://com.apple.accelerate/documentation/Accelerate/QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAG/title",
          "value": "QUADRATURE_INTEGRATE_QAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL/title",
          "value": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QNG/title",
          "value": "QUADRATURE_INTEGRATE_QNG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QNG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QNG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL/title",
          "value": "QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAGS/title",
          "value": "QUADRATURE_INTEGRATE_QAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1QUADRATURE_INTEGRATE_QAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QUADRATURE_INTEGRATE_QAGS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/quadrature_integrate_qag_workspace_per_interval"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/quadrature_integrate_qag_workspace_per_interval"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
