{
  "abstract": [
    {
      "text": "Rotate a cube through a series of keyframes using quaternion interpolation to transition between them.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/rotating-a-cube-by-transforming-its-vertices"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.3",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "14.3",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Rotating a cube by transforming its vertices"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Quaternions are fundamental to graphics programming and are often used as a compact representation of the rotation of an object in three dimensions. You can rotate a 3D object in space by applying unit quaternion actions to each of its vertices. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " module includes functions to interpolate between a series of rotational keyframes — defined by unit quaternions — with either the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_slerp(_:_:_:)-u2db",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (for linear interpolation) or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_spline(_:_:_:_:_:)-1ok51",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (for smooth, spline-based interpolation) functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample code project defines a cube using eight vertices and transforms it through a series of rotations. The sample app provides a SwiftUI ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Toggle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " control that switches between a series of discrete spherical linear interpolations (that is, a series of separate arcs between each keyframe) and a continuous spline (that is, a single, smooth path between each keyframe).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Define-a-cube-by-its-vertices",
          "level": 3,
          "text": "Define a cube by its vertices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample code defines a cube with eight ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " vectors. Each vector specifies the 3D position of one of the cube’s corners.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let cubeVertexOrigins: [simd_double3] = [",
            "    simd_double3(x: -0.5, y: -0.5, z: 0.5),",
            "    simd_double3(x: 0.5, y: -0.5, z: 0.5),",
            "    simd_double3(x: -0.5, y: -0.5, z: -0.5),",
            "    simd_double3(x: 0.5, y: -0.5, z: -0.5),",
            "    simd_double3(x: -0.5, y: 0.5, z: 0.5),",
            "    simd_double3(x: 0.5, y: 0.5, z: 0.5),",
            "    simd_double3(x: -0.5, y: 0.5, z: -0.5),",
            "    simd_double3(x: 0.5, y: 0.5, z: -0.5)",
            "    ]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The quaternion keyframes act upon the vertex origins and mutate ",
              "type": "text"
            },
            {
              "code": "cubeVertices",
              "type": "codeVoice"
            },
            {
              "text": " to rotate the cube.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var cubeVertices = cubeVertexOrigins"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This sample uses ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/scenekit/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to render the cube that vertices in the ",
              "type": "text"
            },
            {
              "code": "cubeVertices",
              "type": "codeVoice"
            },
            {
              "text": " array define. You can also use the technique that the sample code uses to rotate geometry in other technologies such as ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/metal/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The following image shows the cube, defined by the vertices above, rendered in SceneKit:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "cube_2x.jpg",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Define-the-quaternion-rotation-keyframes",
          "level": 3,
          "text": "Define the quaternion rotation keyframes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As discussed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", spline interpolation requires a quaternion before the current value and a quaternion after the next value to compute the interpolated value. To support this, the following code defines the series of rotations with additional values at the beginning and end. The following declaration duplicates the first and last elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let vertexRotations: [simd_quatd] = [",
            "    simd_quatd(angle: 0,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 0, z: 1))),",
            "    simd_quatd(angle: 0,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 0, z: 1))),",
            "    simd_quatd(angle: .pi * 0.05,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 1, z: 0))),",
            "    simd_quatd(angle: .pi * 0.1,",
            "               axis: simd_normalize(simd_double3(x: 1, y: 0, z: -1))),",
            "    simd_quatd(angle: .pi * 0.15,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 1, z: 0))),",
            "    simd_quatd(angle: .pi * 0.2,",
            "               axis: simd_normalize(simd_double3(x: -1, y: 0, z: 1))),",
            "    simd_quatd(angle: .pi * 0.15,",
            "               axis: simd_normalize(simd_double3(x: 0, y: -1, z: 0))),",
            "    simd_quatd(angle: .pi * 0.1,",
            "               axis: simd_normalize(simd_double3(x: 1, y: 0, z: -1))),",
            "    simd_quatd(angle: .pi * 0.05,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 1, z: 0))),",
            "    simd_quatd(angle: 0,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 0, z: 1))),",
            "    simd_quatd(angle: 0,",
            "               axis: simd_normalize(simd_double3(x: 0, y: 0, z: 1)))",
            "]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Animate-between-keyframes-with-spherical-interpolation",
          "level": 3,
          "text": "Animate between keyframes with spherical interpolation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample uses a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/cvdisplaylink-k0k",
              "isActive": true,
              "overridingTitle": "CVDisplayLink",
              "overridingTitleInlineContent": [
                {
                  "code": "CVDisplayLink",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instance to schedule updates to the cube’s vertices and calls the  ",
              "type": "text"
            },
            {
              "code": "vertexRotationStep()",
              "type": "codeVoice"
            },
            {
              "text": " function every frame.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CVDisplayLinkCreateWithCGDisplay(CGMainDisplayID(), &displayLink)",
            "",
            "let displayCallback: CVDisplayLinkOutputCallback = { _, _, _, _, _, displayLinkContext in",
            "    ",
            "    if let displayLinkContext = displayLinkContext {",
            "        DispatchQueue.main.async {",
            "            let cubeRotation = Unmanaged<CubeRotation>.fromOpaque(displayLinkContext).takeUnretainedValue()",
            "            cubeRotation.vertexRotationStep()",
            "        }",
            "    }",
            "    ",
            "    return kCVReturnSuccess",
            "}",
            "",
            "CVDisplayLinkSetOutputCallback(displayLink,",
            "                               displayCallback,",
            "                               Unmanaged.passUnretained(self).toOpaque())",
            "",
            "CVDisplayLinkStart(displayLink)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following variables define the current index in ",
              "type": "text"
            },
            {
              "code": "vertexRotations",
              "type": "codeVoice"
            },
            {
              "text": " and the time, between ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ", for the current interpolation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var vertexRotationIndex = 1",
            "var vertexRotationTime: Double = 0"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "With each display link notification, the ",
              "type": "text"
            },
            {
              "code": "vertexRotationStep",
              "type": "codeVoice"
            },
            {
              "text": " function increments the vertex rotation time variable by a small amount.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let increment: Double = 0.02",
            "vertexRotationTime += increment"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_slerp(_:_:_:)-u2db",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function returns a quaternion that’s spherically interpolated between the current and next quaternion keyframe at the specified time:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "quaternion = simd_slerp(",
            "    vertexRotations[vertexRotationIndex],",
            "    vertexRotations[vertexRotationIndex + 1],",
            "    vertexRotationTime)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The quaternion acts upon each of the cube’s vertices and rotates the cube around its center:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "cubeVertices = cubeVertexOrigins.map {",
            "    return quaternion.act($0)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the vertex rotation time is greater than or equal to one, the code progresses to the next keyframe, increments the index to the rotations array, and resets the rotation time to zero. When the code has reached the last usable quaternion in the array of rotations, it ends the animation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if vertexRotationTime >= 1 {",
            "    vertexRotationIndex += 1",
            "    vertexRotationTime = 0",
            "",
            "    if vertexRotationIndex > vertexRotations.count - 3 {",
            "        scene = setupSceneKit()",
            "",
            "        vertexRotationIndex = 1",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Over time, the cube animates through the series of keyframes. The following image shows the sharp change in direction as the cube rotates between the keyframes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "spherical_interpolation_2x.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Animate-between-keyframes-with-spline-interpolation",
          "level": 3,
          "text": "Animate between keyframes with spline interpolation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample code uses the identical code to the spherical interpolation sample for spline interpolation, apart from one difference: rather than generating the quaternion that acts upon the vertices with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_slerp(_:_:_:)-u2db",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", it uses the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_spline(_:_:_:_:_:)-1ok51",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "quaternion = simd_spline(",
            "    vertexRotations[vertexRotationIndex - 1],",
            "    vertexRotations[vertexRotationIndex],",
            "    vertexRotations[vertexRotationIndex + 1],",
            "    vertexRotations[vertexRotationIndex + 2],",
            "    vertexRotationTime)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The image below shows that the spline interpolation creates transitions between the quaternion keyframes that are smoother than the linear spherical interpolation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "spline_interpolation_2x.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "27ac5ce9cc0b/RotatingACubeByTransformingItsVertices.zip": {
      "checksum": "27ac5ce9cc0bd8a085e2a695ff2b174bc3eb8d21d9b74476c2853ac02e8b21082e0cad1a532cb3a3ac8c1d041703c7c1abb9afa4221493f3693350b293328fd2",
      "identifier": "27ac5ce9cc0b/RotatingACubeByTransformingItsVertices.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/27ac5ce9cc0b/RotatingACubeByTransformingItsVertices.zip"
    },
    "cube_2x.jpg": {
      "alt": "An image of a cube.",
      "identifier": "cube_2x.jpg",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d620197542839aaed7545f8a5e71ee2b/cube_2x.jpg"
        }
      ]
    },
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vforce-library": {
      "abstract": [
        {
          "text": "Perform transcendental and trigonometric functions on vectors of any length.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vforce-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vForce",
      "type": "topic",
      "url": "/documentation/accelerate/vforce-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices": {
      "abstract": [
        {
          "text": "Solve simultaneous equations and transform points in space.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
      "kind": "article",
      "role": "article",
      "title": "Working with Matrices",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-matrices"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions": {
      "abstract": [
        {
          "text": "Rotate points around the surface of a sphere, and interpolate between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
      "kind": "article",
      "role": "article",
      "title": "Working with Quaternions",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-quaternions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors": {
      "abstract": [
        {
          "text": "Use vectors to calculate geometric values, calculate dot products and cross products, and interpolate between values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors",
      "kind": "article",
      "role": "article",
      "title": "Working with Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/working-with-vectors"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit floating-point elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double3"
        }
      ],
      "role": "symbol",
      "title": "simd_double3",
      "type": "topic",
      "url": "/documentation/simd/simd_double3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_slerp(_:_:_:)-u2db": {
      "abstract": [
        {
          "text": "Returns a spherical linearly interpolated value along the shortest arc between two quaternions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_slerp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_slerp(_:_:_:)-u2db",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_slerp"
        }
      ],
      "role": "symbol",
      "title": "simd_slerp(_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_slerp(_:_:_:)-u2db"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_spline(_:_:_:_:_:)-1ok51": {
      "abstract": [
        {
          "text": "Returns an interpolated value between two quaternions along a spherical cubic spline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_spline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_quatf",
          "text": "simd_quatf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_spline(_:_:_:_:_:)-1ok51",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_spline"
        }
      ],
      "role": "symbol",
      "title": "simd_spline(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_spline(_:_:_:_:_:)-1ok51"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/cvdisplaylink-k0k": {
      "abstract": [
        {
          "text": "A high-priority thread that notifies your app when a given display will need each frame.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/cvdisplaylink-k0k",
      "kind": "article",
      "role": "article",
      "title": "CVDisplayLink",
      "type": "topic",
      "url": "/documentation/CoreVideo/cvdisplaylink-k0k"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Toggle": {
      "abstract": [
        {
          "text": "A control that toggles between on and off states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Toggle"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Toggle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Toggle",
      "type": "topic",
      "url": "/documentation/SwiftUI/Toggle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/metal/": {
      "identifier": "https://developer.apple.com/metal/",
      "title": "Metal",
      "titleInlineContent": [
        {
          "text": "Metal",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/metal/"
    },
    "https://developer.apple.com/scenekit/": {
      "identifier": "https://developer.apple.com/scenekit/",
      "title": "SceneKit",
      "titleInlineContent": [
        {
          "text": "SceneKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/scenekit/"
    },
    "spherical_interpolation_2x.png": {
      "alt": "An image of a cube with the path of one of its vertices rendered as a line after a series of spherical interpolated rotations.",
      "identifier": "spherical_interpolation_2x.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/923a4c2dedbf09a6148d0ff939f82dfd/spherical_interpolation_2x.png"
        }
      ]
    },
    "spline_interpolation_2x.png": {
      "alt": "An image of a cube with the path of one of its vertices rendered as a line after a series of spline interpolated rotations.",
      "identifier": "spline_interpolation_2x.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/118465d071bd0496ec42c80c99db4a0e/spline_interpolation_2x.png"
        }
      ]
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "27ac5ce9cc0b/RotatingACubeByTransformingItsVertices.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vectors-Matrices-and-Quaternions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-matrices",
        "doc://com.apple.accelerate/documentation/Accelerate/working-with-quaternions",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
        "doc://com.apple.accelerate/documentation/Accelerate/vforce-library"
      ],
      "title": "Vectors, Matrices, and Quaternions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_slerp(_:_:_:)-u2db/title",
          "value": "simd_slerp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_slerp(_:_:_:)-u2db/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_slerp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/title",
          "value": "simd_double3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_spline(_:_:_:_:_:)-1ok51/title",
          "value": "simd_spline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_spline(_:_:_:_:_:)-1ok51/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_spline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
