{
  "abstract": [
    {
      "text": "Use Model I/O and vImage to composite a photograph over a",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "computer-generated sky.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sharing-texture-data-between-the-model-io-framework-and-the-vimage-library"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Sharing texture data between the Model I/O framework and the vImage library"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO",
              "isActive": true,
              "overridingTitle": "Model I/O",
              "overridingTitleInlineContent": [
                {
                  "text": "Model I/O",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework provides the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLTexture",
              "isActive": true,
              "overridingTitle": "MDLTexture",
              "overridingTitleInlineContent": [
                {
                  "code": "MDLTexture",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "class and its subclasses to generate procedural textures",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "such as noise, normal maps, and realistic sky boxes.  This sample code",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "project uses an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture",
              "isActive": true,
              "overridingTitle": "MDLSkyCubeTexture",
              "overridingTitleInlineContent": [
                {
                  "code": "MDLSkyCubeTexture",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance to generate a physically realistic simulation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of a sunlit sky. The code uses the generated sky image as the background",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and a photograph of a building as the foreground.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The image below shows the final composition:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "img.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using the UI, someone can define the parameters that control",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the sky simulation such as upper atmosphere scattering and sun",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "elevation. Before exploring the code, try building and running the app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to get familiar with the effect of the different parameters on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-the-sky-texture-generator",
          "level": 3,
          "text": "Create the sky texture generator",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ImageProvider",
              "type": "codeVoice"
            },
            {
              "text": " class declares constants for the source image’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "dimensions and the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture",
              "isActive": true,
              "overridingTitle": "MDLSkyCubeTexture",
              "overridingTitleInlineContent": [
                {
                  "code": "MDLSkyCubeTexture",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " instance named ",
              "type": "text"
            },
            {
              "code": "skyGenerator",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let width: Int",
            "var height: Int",
            "",
            "let skyGenerator: MDLSkyCubeTexture"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The initializer creates the sky generator instance that’s the same size",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as the top layer image of the skyscraper:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "width = foregroundImage.width",
            "height = foregroundImage.height",
            "",
            "skyGenerator = MDLSkyCubeTexture(name: nil,",
            "                                 channelEncoding: .uInt8,",
            "                                 textureDimensions: .init(x: Int32(width),",
            "                                                          y: Int32(height)),",
            "                                 turbidity: 0,",
            "                                 sunElevation: 0,",
            "                                 upperAtmosphereScattering: 0,",
            "                                 groundAlbedo: 0)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Update-the-sky-texture-generator-parameters",
          "level": 3,
          "text": "Update the sky texture generator parameters",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With each change to the SwiftUI",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "controls that define the sky generator parameters, the app calls the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "renderSky()",
              "type": "codeVoice"
            },
            {
              "text": " function. The function sets the sky generator parameters",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and calls",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture/update()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to generate new texel data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "skyGenerator.turbidity = turbidity",
            "skyGenerator.sunElevation = sunElevation",
            "skyGenerator.upperAtmosphereScattering = upperAtmosphereScattering",
            "skyGenerator.groundAlbedo = groundAlbedo",
            "",
            "skyGenerator.update()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Create-the-composite-image",
          "level": 3,
          "text": "Create the composite image",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLTexture/texelDataWithTopLeftOrigin()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method returns the sky generator’s image data organized such that its first pixel",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "represents the top-left corner of the image. This layout matches the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " layout.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The code passes the texel data to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/data/3139154-withunsafebytes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "function to work with the underlying bytes of the data’s contiguous storage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let img = skyGenerator.texelDataWithTopLeftOrigin()?.withUnsafeBytes { skyData in"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture",
              "isActive": true,
              "overridingTitle": "MDLSkyCubeTexture",
              "overridingTitleInlineContent": [
                {
                  "code": "MDLSkyCubeTexture",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance generates a cube texture that’s represented as six sides, vertically stacked.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "cube.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code below calculates the range texels that correspond to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "selected side (one of ",
              "type": "text"
            },
            {
              "code": "[\"+X\", \"-X\", \"+Y\", \"-Y\", \"+Z\", \"-Z\"]",
              "type": "codeVoice"
            },
            {
              "text": ") and binds",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "those to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let imageIndex = ImageProvider.views.firstIndex(of: view) ?? 0",
            "let imagePixelCount = width * height * format.componentCount",
            "",
            "let range = imageIndex * imagePixelCount ..< (imageIndex + 1) * imagePixelCount",
            "",
            "let values = skyData.bindMemory(to: Pixel_8.self)[ range ]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The code below creates a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "structure from the values and, because the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/alphaComposite(_:topLayer:destination:)-fybo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method expects ARGB data, permutes the channel order so that alpha channel is first:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let buffer = vImage.PixelBuffer(pixelValues: values,",
            "                                size: .init(width: width, height: height),",
            "                                pixelFormat: vImage.Interleaved8x4.self)",
            "",
            "buffer.permuteChannels(to: (3, 0, 1, 2), destination: buffer)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, the sample code project composites the skyscraper image,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "represented by ",
              "type": "text"
            },
            {
              "code": "foregroundBuffer",
              "type": "codeVoice"
            },
            {
              "text": ", over the sky image and returns a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
              "isActive": true,
              "overridingTitle": "CGImage",
              "overridingTitleInlineContent": [
                {
                  "code": "CGImage",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance that contains the result:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    buffer.alphaComposite(.nonpremultiplied,",
            "                          topLayer: foregroundBuffer,",
            "                          destination: buffer)",
            "    ",
            "    return buffer.makeCGImage(cgImageFormat: format)",
            "} // Ends `skyGenerator.texelDataWithTopLeftOrigin()?.withUnsafeBytes`."
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "95d06baaab82/SharingTextureDataBetweenTheModelIOFrameworkAndTheVImageLibrary.zip": {
      "checksum": "95d06baaab8269f3bd52c97fbe55fb32dcbcd64fb6c9471c06725af1b1eb90c3c5f37dbf519f10723b6cac12ce6fe83877a6b8fffac7c9c556d2f31fa7da800b",
      "identifier": "95d06baaab82/SharingTextureDataBetweenTheModelIOFrameworkAndTheVImageLibrary.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/95d06baaab82/SharingTextureDataBetweenTheModelIOFrameworkAndTheVImageLibrary.zip"
    },
    "cube.png": {
      "alt": "A vertically stacked series of six images that represent the six sides of the sky texture cube.",
      "identifier": "cube.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/27bc615fbfad224159cfc5d2dd1115cc/cube.png"
        }
      ]
    },
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8": {
      "abstract": [
        {
          "text": "A type for a planar, 8-bits-per-channel, unsigned pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Pixel_8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/Pixel_8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Pixel_8"
        }
      ],
      "role": "symbol",
      "title": "Pixel_8",
      "type": "topic",
      "url": "/documentation/accelerate/pixel_8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image": {
      "abstract": [
        {
          "text": "Use a gamma function to apply a linear or exponential curve.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting the brightness and contrast of an image",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-the-brightness-and-contrast-of-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image": {
      "abstract": [
        {
          "text": "Convert an image to L*a*b* color space and apply hue adjustment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting the hue of an image",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-the-hue-of-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images": {
      "abstract": [
        {
          "text": "Use the vImage library’s polynomial transform to apply tone curve adjustments to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying tone curve adjustments to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-tone-curve-adjustments-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image": {
      "abstract": [
        {
          "text": "Find the main colors in an image by implementing k-means clustering using the Accelerate framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Calculating the dominant colors in an image",
      "type": "topic",
      "url": "/documentation/accelerate/calculating-the-dominant-colors-in-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects": {
      "abstract": [
        {
          "text": "Render real-time video effects with the vImage Pixel Buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using vImage pixel buffers to generate video effects",
      "type": "topic",
      "url": "/documentation/accelerate/using-vimage-pixel-buffers-to-generate-video-effects"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer": {
      "abstract": [
        {
          "text": "An image buffer that stores an image’s pixel data, dimensions, bit depth, and number of channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "vImage.PixelBuffer",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/alphaComposite(_:topLayer:destination:)-fybo": {
      "abstract": [
        {
          "text": "Performs alpha compositing of two 4-channel interleaved ARGB 8-bit pixel buffers using the specified composite mode.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Format",
            "type": "codeVoice"
          },
          {
            "text": " is ",
            "type": "text"
          },
          {
            "code": "vImage.Interleaved8x4",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaComposite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO13CompositeModeO",
          "text": "CompositeMode"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@Pixel_8",
          "text": "Pixel_8"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "topLayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
          "text": "PixelBuffer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Format"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO",
          "text": "vImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate6vImageO11PixelBufferV",
          "text": "PixelBuffer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Format"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer/alphaComposite(_:topLayer:destination:)-fybo",
      "kind": "symbol",
      "role": "symbol",
      "title": "alphaComposite(_:topLayer:destination:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage/pixelbuffer/alphacomposite(_:toplayer:destination:)-fybo"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/ModelIO"
    },
    "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture": {
      "abstract": [
        {
          "text": "A generator of texel data that creates cube textures using a physically realistic simulation of the sunlit sky.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLSkyCubeTexture"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MDLSkyCubeTexture",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLSkyCubeTexture"
    },
    "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture/update()": {
      "abstract": [
        {
          "text": "Generates new texel data matching the current sky parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLSkyCubeTexture/update()",
      "kind": "symbol",
      "role": "symbol",
      "title": "update()",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLSkyCubeTexture/update()"
    },
    "doc://com.apple.documentation/documentation/ModelIO/MDLTexture": {
      "abstract": [
        {
          "text": "A source of texel data to be used in rendering material surface appearances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLTexture"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MDLTexture",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLTexture"
    },
    "doc://com.apple.documentation/documentation/ModelIO/MDLTexture/texelDataWithTopLeftOrigin()": {
      "abstract": [
        {
          "text": "Returns the texture’s image data, organized such that its first pixel represents the top-left corner of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "texelDataWithTopLeftOrigin"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ModelIO/MDLTexture/texelDataWithTopLeftOrigin()",
      "kind": "symbol",
      "role": "symbol",
      "title": "texelDataWithTopLeftOrigin()",
      "type": "topic",
      "url": "/documentation/ModelIO/MDLTexture/texelDataWithTopLeftOrigin()"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Picker": {
      "abstract": [
        {
          "text": "A control for selecting from a set of mutually exclusive values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Picker"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Label"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "SelectionValue"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Picker",
      "kind": "symbol",
      "role": "symbol",
      "title": "Picker",
      "type": "topic",
      "url": "/documentation/SwiftUI/Picker"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgimage": {
      "abstract": [
        {
          "text": "A bitmap image or image mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImage",
      "type": "topic",
      "url": "/documentation/coregraphics/cgimage"
    },
    "doc://com.apple.documentation/documentation/foundation/data/3139154-withunsafebytes": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeBytes"
        },
        {
          "kind": "text",
          "text": "<ResultType>((UnsafeRawBufferPointer) -> ResultType) -> ResultType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/data/3139154-withunsafebytes",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeBytes(_:)",
      "type": "topic",
      "url": "/documentation/foundation/data/3139154-withunsafebytes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "img.png": {
      "alt": "A photograph of a skyscraper composited over a computer-generated",
      "identifier": "img.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fbdd4053ce12c328dd288776914fa149/img.png"
        }
      ]
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "95d06baaab82/SharingTextureDataBetweenTheModelIOFrameworkAndTheVImageLibrary.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "vImage-Pixel-Buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/using-vimage-pixel-buffers-to-generate-video-effects",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-brightness-and-contrast-of-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-the-hue-of-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/calculating-the-dominant-colors-in-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage/PixelBuffer"
      ],
      "title": "vImage Pixel Buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgimage/title",
          "value": "CGImageRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLTexture~1texelDataWithTopLeftOrigin()/title",
          "value": "texelDataWithTopLeftOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLTexture~1texelDataWithTopLeftOrigin()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSData",
              "text": "NSData"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "texelDataWithTopLeftOrigin"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/title",
          "value": "Pixel_8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Pixel_8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLSkyCubeTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLSkyCubeTexture"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MDLTexture",
              "text": "MDLTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MDLTexture"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLSkyCubeTexture~1update()/title",
          "value": "updateTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ModelIO~1MDLSkyCubeTexture~1update()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "updateTexture"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
