{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/simd-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "simd Macros"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_CFUNC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_CFUNC"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_CFUNC",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_CFUNC",
      "type": "topic",
      "url": "/documentation/simd/simd_cfunc"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_CONST"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_CONST",
      "type": "topic",
      "url": "/documentation/simd/simd_const"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_CPPFUNC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_CPPFUNC"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_CPPFUNC",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_CPPFUNC",
      "type": "topic",
      "url": "/documentation/simd/simd_cppfunc"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_CURRENT_LIBRARY_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SIMD_CURRENT_LIBRARY_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_CURRENT_LIBRARY_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SIMD_CURRENT_LIBRARY_VERSION"
        }
      ],
      "role": "symbol",
      "title": "SIMD_CURRENT_LIBRARY_VERSION",
      "type": "topic",
      "url": "/documentation/simd/simd_current_library_version"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_DEPRECATED",
      "type": "topic",
      "url": "/documentation/simd/simd_deprecated"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_INLINE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_INLINE",
      "type": "topic",
      "url": "/documentation/simd/simd_inline"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_NODEBUG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_NODEBUG"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_NODEBUG",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_NODEBUG",
      "type": "topic",
      "url": "/documentation/simd/simd_nodebug"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_NOINLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_NOINLINE"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_NOINLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_NOINLINE",
      "type": "topic",
      "url": "/documentation/simd/simd_noinline"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_NONCONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_NONCONST"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_NONCONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_NONCONST",
      "type": "topic",
      "url": "/documentation/simd/simd_nonconst"
    },
    "doc://com.apple.accelerate/documentation/simd/SIMD_OVERLOAD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SIMD_OVERLOAD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/SIMD_OVERLOAD",
      "kind": "symbol",
      "role": "symbol",
      "title": "SIMD_OVERLOAD",
      "type": "topic",
      "url": "/documentation/simd/simd_overload"
    },
    "doc://com.apple.accelerate/documentation/simd/carg": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "carg"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/carg",
      "kind": "symbol",
      "role": "symbol",
      "title": "carg",
      "type": "topic",
      "url": "/documentation/simd/carg"
    },
    "doc://com.apple.accelerate/documentation/simd/ceil": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ceil"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/ceil",
      "kind": "symbol",
      "role": "symbol",
      "title": "ceil",
      "type": "topic",
      "url": "/documentation/simd/ceil"
    },
    "doc://com.apple.accelerate/documentation/simd/cimag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cimag"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cimag",
      "kind": "symbol",
      "role": "symbol",
      "title": "cimag",
      "type": "topic",
      "url": "/documentation/simd/cimag"
    },
    "doc://com.apple.accelerate/documentation/simd/conj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "conj"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/conj",
      "kind": "symbol",
      "role": "symbol",
      "title": "conj",
      "type": "topic",
      "url": "/documentation/simd/conj"
    },
    "doc://com.apple.accelerate/documentation/simd/cproj": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cproj"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/cproj",
      "kind": "symbol",
      "role": "symbol",
      "title": "cproj",
      "type": "topic",
      "url": "/documentation/simd/cproj"
    },
    "doc://com.apple.accelerate/documentation/simd/creal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "creal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/creal",
      "kind": "symbol",
      "role": "symbol",
      "title": "creal",
      "type": "topic",
      "url": "/documentation/simd/creal"
    },
    "doc://com.apple.accelerate/documentation/simd/floor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "floor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/floor",
      "kind": "symbol",
      "role": "symbol",
      "title": "floor",
      "type": "topic",
      "url": "/documentation/simd/floor"
    },
    "doc://com.apple.accelerate/documentation/simd/fmax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fmax"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmax",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmax",
      "type": "topic",
      "url": "/documentation/simd/fmax"
    },
    "doc://com.apple.accelerate/documentation/simd/fmin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fmin"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/fmin",
      "kind": "symbol",
      "role": "symbol",
      "title": "fmin",
      "type": "topic",
      "url": "/documentation/simd/fmin"
    },
    "doc://com.apple.accelerate/documentation/simd/frexp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "frexp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/frexp",
      "kind": "symbol",
      "role": "symbol",
      "title": "frexp",
      "type": "topic",
      "url": "/documentation/simd/frexp"
    },
    "doc://com.apple.accelerate/documentation/simd/ilogb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ilogb"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/ilogb",
      "kind": "symbol",
      "role": "symbol",
      "title": "ilogb",
      "type": "topic",
      "url": "/documentation/simd/ilogb"
    },
    "doc://com.apple.accelerate/documentation/simd/isfinite": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isfinite"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isfinite",
      "kind": "symbol",
      "role": "symbol",
      "title": "isfinite",
      "type": "topic",
      "url": "/documentation/simd/isfinite"
    },
    "doc://com.apple.accelerate/documentation/simd/isinf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isinf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isinf",
      "kind": "symbol",
      "role": "symbol",
      "title": "isinf",
      "type": "topic",
      "url": "/documentation/simd/isinf"
    },
    "doc://com.apple.accelerate/documentation/simd/isnan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isnan"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isnan",
      "kind": "symbol",
      "role": "symbol",
      "title": "isnan",
      "type": "topic",
      "url": "/documentation/simd/isnan"
    },
    "doc://com.apple.accelerate/documentation/simd/isnormal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isnormal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/isnormal",
      "kind": "symbol",
      "role": "symbol",
      "title": "isnormal",
      "type": "topic",
      "url": "/documentation/simd/isnormal"
    },
    "doc://com.apple.accelerate/documentation/simd/ldexp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ldexp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/ldexp",
      "kind": "symbol",
      "role": "symbol",
      "title": "ldexp",
      "type": "topic",
      "url": "/documentation/simd/ldexp"
    },
    "doc://com.apple.accelerate/documentation/simd/lgamma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lgamma"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lgamma",
      "kind": "symbol",
      "role": "symbol",
      "title": "lgamma",
      "type": "topic",
      "url": "/documentation/simd/lgamma"
    },
    "doc://com.apple.accelerate/documentation/simd/llrint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "llrint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/llrint",
      "kind": "symbol",
      "role": "symbol",
      "title": "llrint",
      "type": "topic",
      "url": "/documentation/simd/llrint"
    },
    "doc://com.apple.accelerate/documentation/simd/llround": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "llround"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/llround",
      "kind": "symbol",
      "role": "symbol",
      "title": "llround",
      "type": "topic",
      "url": "/documentation/simd/llround"
    },
    "doc://com.apple.accelerate/documentation/simd/logb": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "logb"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/logb",
      "kind": "symbol",
      "role": "symbol",
      "title": "logb",
      "type": "topic",
      "url": "/documentation/simd/logb"
    },
    "doc://com.apple.accelerate/documentation/simd/lrint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lrint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lrint",
      "kind": "symbol",
      "role": "symbol",
      "title": "lrint",
      "type": "topic",
      "url": "/documentation/simd/lrint"
    },
    "doc://com.apple.accelerate/documentation/simd/lround": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lround"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/lround",
      "kind": "symbol",
      "role": "symbol",
      "title": "lround",
      "type": "topic",
      "url": "/documentation/simd/lround"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_add": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_add",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_add",
      "type": "topic",
      "url": "/documentation/simd/matrix_add"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_almost_equal_elements"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_almost_equal_elements",
      "type": "topic",
      "url": "/documentation/simd/matrix_almost_equal_elements"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements_relative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_almost_equal_elements_relative"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements_relative",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_almost_equal_elements_relative",
      "type": "topic",
      "url": "/documentation/simd/matrix_almost_equal_elements_relative"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_determinant": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_determinant"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_determinant",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_determinant",
      "type": "topic",
      "url": "/documentation/simd/matrix_determinant"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_equal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_equal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_equal",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_equal",
      "type": "topic",
      "url": "/documentation/simd/matrix_equal"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_columns": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_from_columns"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_columns",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_columns",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_columns"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_from_diagonal"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_diagonal",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_diagonal"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_from_rows": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_from_rows"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_from_rows",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_from_rows",
      "type": "topic",
      "url": "/documentation/simd/matrix_from_rows"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_invert": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_invert"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_invert",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_invert",
      "type": "topic",
      "url": "/documentation/simd/matrix_invert"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_linear_combination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_linear_combination"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_linear_combination",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_linear_combination",
      "type": "topic",
      "url": "/documentation/simd/matrix_linear_combination"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_sub": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_sub",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_sub",
      "type": "topic",
      "url": "/documentation/simd/matrix_sub"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_trace": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_trace"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_trace",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_trace",
      "type": "topic",
      "url": "/documentation/simd/matrix_trace"
    },
    "doc://com.apple.accelerate/documentation/simd/matrix_transpose": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "matrix_transpose"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/matrix_transpose",
      "kind": "symbol",
      "role": "symbol",
      "title": "matrix_transpose",
      "type": "topic",
      "url": "/documentation/simd/matrix_transpose"
    },
    "doc://com.apple.accelerate/documentation/simd/nearbyint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nearbyint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nearbyint",
      "kind": "symbol",
      "role": "symbol",
      "title": "nearbyint",
      "type": "topic",
      "url": "/documentation/simd/nearbyint"
    },
    "doc://com.apple.accelerate/documentation/simd/nexttoward": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "nexttoward"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/nexttoward",
      "kind": "symbol",
      "role": "symbol",
      "title": "nexttoward",
      "type": "topic",
      "url": "/documentation/simd/nexttoward"
    },
    "doc://com.apple.accelerate/documentation/simd/remquo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "remquo"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/remquo",
      "kind": "symbol",
      "role": "symbol",
      "title": "remquo",
      "type": "topic",
      "url": "/documentation/simd/remquo"
    },
    "doc://com.apple.accelerate/documentation/simd/scalbln": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "scalbln"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/scalbln",
      "kind": "symbol",
      "role": "symbol",
      "title": "scalbln",
      "type": "topic",
      "url": "/documentation/simd/scalbln"
    },
    "doc://com.apple.accelerate/documentation/simd/scalbn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "scalbn"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/scalbn",
      "kind": "symbol",
      "role": "symbol",
      "title": "scalbn",
      "type": "topic",
      "url": "/documentation/simd/scalbn"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_lerp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "simd_lerp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_lerp",
      "kind": "symbol",
      "role": "symbol",
      "title": "simd_lerp",
      "type": "topic",
      "url": "/documentation/simd/simd_lerp"
    },
    "doc://com.apple.accelerate/documentation/simd/sincos": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sincos"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/sincos",
      "kind": "symbol",
      "role": "symbol",
      "title": "sincos",
      "type": "topic",
      "url": "/documentation/simd/sincos"
    },
    "doc://com.apple.accelerate/documentation/simd/sincospi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sincospi"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/sincospi",
      "kind": "symbol",
      "role": "symbol",
      "title": "sincospi",
      "type": "topic",
      "url": "/documentation/simd/sincospi"
    },
    "doc://com.apple.accelerate/documentation/simd/trunc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "trunc"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/trunc",
      "kind": "symbol",
      "role": "symbol",
      "title": "trunc",
      "type": "topic",
      "url": "/documentation/simd/trunc"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_abs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_abs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_abs",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_abs",
      "type": "topic",
      "url": "/documentation/simd/vector_abs"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_all": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_all"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_all",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_all",
      "type": "topic",
      "url": "/documentation/simd/vector_all"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_any": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_any"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_any",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_any",
      "type": "topic",
      "url": "/documentation/simd/vector_any"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_bitselect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_bitselect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_bitselect",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_bitselect",
      "type": "topic",
      "url": "/documentation/simd/vector_bitselect"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_char": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_char"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_char",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_char",
      "type": "topic",
      "url": "/documentation/simd/vector_char"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_char_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_char_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_char_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_char_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_char_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_clamp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_clamp"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_clamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_clamp",
      "type": "topic",
      "url": "/documentation/simd/vector_clamp"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_cross": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_cross"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_cross",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_cross",
      "type": "topic",
      "url": "/documentation/simd/vector_cross"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_distance",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_distance",
      "type": "topic",
      "url": "/documentation/simd/vector_distance"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_distance_squared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_distance_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_distance_squared",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_distance_squared",
      "type": "topic",
      "url": "/documentation/simd/vector_distance_squared"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_dot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_dot"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_dot",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_dot",
      "type": "topic",
      "url": "/documentation/simd/vector_dot"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_double": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_double",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_double",
      "type": "topic",
      "url": "/documentation/simd/vector_double"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_distance",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_distance",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_distance"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_length": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_length",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_length",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_length"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_normalize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_normalize",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_normalize",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_normalize"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_project": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_project",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_project",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_project"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_recip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_recip"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_recip",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_recip",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_recip"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fast_rsqrt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fast_rsqrt"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fast_rsqrt",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fast_rsqrt",
      "type": "topic",
      "url": "/documentation/simd/vector_fast_rsqrt"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_float",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_float",
      "type": "topic",
      "url": "/documentation/simd/vector_float"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_fract": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_fract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_fract",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_fract",
      "type": "topic",
      "url": "/documentation/simd/vector_fract"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_int": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_int",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_int",
      "type": "topic",
      "url": "/documentation/simd/vector_int"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_int_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_int_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_int_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_int_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_int_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_length": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_length",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_length",
      "type": "topic",
      "url": "/documentation/simd/vector_length"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_length_squared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_length_squared"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_length_squared",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_length_squared",
      "type": "topic",
      "url": "/documentation/simd/vector_length_squared"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_long": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_long"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_long",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_long",
      "type": "topic",
      "url": "/documentation/simd/vector_long"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_long_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_long_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_long_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_long_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_long_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_max"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_max",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_max",
      "type": "topic",
      "url": "/documentation/simd/vector_max"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_min": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_min"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_min",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_min",
      "type": "topic",
      "url": "/documentation/simd/vector_min"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_mix": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_mix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_mix",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_mix",
      "type": "topic",
      "url": "/documentation/simd/vector_mix"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_norm_inf": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_norm_inf"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_norm_inf",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_norm_inf",
      "type": "topic",
      "url": "/documentation/simd/vector_norm_inf"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_norm_one": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_norm_one"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_norm_one",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_norm_one",
      "type": "topic",
      "url": "/documentation/simd/vector_norm_one"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_normalize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_normalize",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_normalize",
      "type": "topic",
      "url": "/documentation/simd/vector_normalize"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_distance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_distance"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_distance",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_distance",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_distance"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_length": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_length",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_length",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_length"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_normalize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_normalize"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_normalize",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_normalize",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_normalize"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_project": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_project",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_project",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_project"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_recip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_recip"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_recip",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_recip",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_recip"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_precise_rsqrt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_precise_rsqrt"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_precise_rsqrt",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_precise_rsqrt",
      "type": "topic",
      "url": "/documentation/simd/vector_precise_rsqrt"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_project": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_project"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_project",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_project",
      "type": "topic",
      "url": "/documentation/simd/vector_project"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_recip": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_recip"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_recip",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_recip",
      "type": "topic",
      "url": "/documentation/simd/vector_recip"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_reduce_add": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_reduce_add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_reduce_add",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_reduce_add",
      "type": "topic",
      "url": "/documentation/simd/vector_reduce_add"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_reduce_max": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_reduce_max"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_reduce_max",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_reduce_max",
      "type": "topic",
      "url": "/documentation/simd/vector_reduce_max"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_reduce_min": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_reduce_min"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_reduce_min",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_reduce_min",
      "type": "topic",
      "url": "/documentation/simd/vector_reduce_min"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_reflect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_reflect"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_reflect",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_reflect",
      "type": "topic",
      "url": "/documentation/simd/vector_reflect"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_refract": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_refract"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_refract",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_refract",
      "type": "topic",
      "url": "/documentation/simd/vector_refract"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_rsqrt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_rsqrt"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_rsqrt",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_rsqrt",
      "type": "topic",
      "url": "/documentation/simd/vector_rsqrt"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_select": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_select"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_select",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_select",
      "type": "topic",
      "url": "/documentation/simd/vector_select"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_short": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_short"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_short",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_short",
      "type": "topic",
      "url": "/documentation/simd/vector_short"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_short_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_short_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_short_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_short_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_short_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_sign": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_sign"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_sign",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_sign",
      "type": "topic",
      "url": "/documentation/simd/vector_sign"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_smoothstep": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_smoothstep"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_smoothstep",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_smoothstep",
      "type": "topic",
      "url": "/documentation/simd/vector_smoothstep"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_step": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_step"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_step",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_step",
      "type": "topic",
      "url": "/documentation/simd/vector_step"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uchar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_uchar"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uchar",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_uchar",
      "type": "topic",
      "url": "/documentation/simd/vector_uchar"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uchar_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_uchar_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uchar_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_uchar_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_uchar_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_uint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uint",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_uint",
      "type": "topic",
      "url": "/documentation/simd/vector_uint"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_uint_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_uint_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_uint_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_uint_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_uint_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ulong": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_ulong"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ulong",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_ulong",
      "type": "topic",
      "url": "/documentation/simd/vector_ulong"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ulong_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_ulong_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ulong_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_ulong_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_ulong_sat"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ushort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_ushort"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ushort",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_ushort",
      "type": "topic",
      "url": "/documentation/simd/vector_ushort"
    },
    "doc://com.apple.accelerate/documentation/simd/vector_ushort_sat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vector_ushort_sat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/vector_ushort_sat",
      "kind": "symbol",
      "role": "symbol",
      "title": "vector_ushort_sat",
      "type": "topic",
      "url": "/documentation/simd/vector_ushort_sat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/SIMD_CFUNC",
        "doc://com.apple.accelerate/documentation/simd/SIMD_CONST",
        "doc://com.apple.accelerate/documentation/simd/SIMD_CPPFUNC",
        "doc://com.apple.accelerate/documentation/simd/SIMD_CURRENT_LIBRARY_VERSION",
        "doc://com.apple.accelerate/documentation/simd/SIMD_DEPRECATED",
        "doc://com.apple.accelerate/documentation/simd/SIMD_INLINE",
        "doc://com.apple.accelerate/documentation/simd/SIMD_NODEBUG",
        "doc://com.apple.accelerate/documentation/simd/SIMD_NOINLINE",
        "doc://com.apple.accelerate/documentation/simd/SIMD_NONCONST",
        "doc://com.apple.accelerate/documentation/simd/SIMD_OVERLOAD",
        "doc://com.apple.accelerate/documentation/simd/carg",
        "doc://com.apple.accelerate/documentation/simd/ceil",
        "doc://com.apple.accelerate/documentation/simd/cimag",
        "doc://com.apple.accelerate/documentation/simd/conj",
        "doc://com.apple.accelerate/documentation/simd/cproj",
        "doc://com.apple.accelerate/documentation/simd/creal",
        "doc://com.apple.accelerate/documentation/simd/floor",
        "doc://com.apple.accelerate/documentation/simd/fmax",
        "doc://com.apple.accelerate/documentation/simd/fmin",
        "doc://com.apple.accelerate/documentation/simd/frexp",
        "doc://com.apple.accelerate/documentation/simd/ilogb",
        "doc://com.apple.accelerate/documentation/simd/isfinite",
        "doc://com.apple.accelerate/documentation/simd/isinf",
        "doc://com.apple.accelerate/documentation/simd/isnan",
        "doc://com.apple.accelerate/documentation/simd/isnormal",
        "doc://com.apple.accelerate/documentation/simd/ldexp",
        "doc://com.apple.accelerate/documentation/simd/lgamma",
        "doc://com.apple.accelerate/documentation/simd/llrint",
        "doc://com.apple.accelerate/documentation/simd/llround",
        "doc://com.apple.accelerate/documentation/simd/logb",
        "doc://com.apple.accelerate/documentation/simd/lrint",
        "doc://com.apple.accelerate/documentation/simd/lround",
        "doc://com.apple.accelerate/documentation/simd/matrix_add",
        "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements",
        "doc://com.apple.accelerate/documentation/simd/matrix_almost_equal_elements_relative",
        "doc://com.apple.accelerate/documentation/simd/matrix_determinant",
        "doc://com.apple.accelerate/documentation/simd/matrix_equal",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_columns",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_diagonal",
        "doc://com.apple.accelerate/documentation/simd/matrix_from_rows",
        "doc://com.apple.accelerate/documentation/simd/matrix_invert",
        "doc://com.apple.accelerate/documentation/simd/matrix_linear_combination",
        "doc://com.apple.accelerate/documentation/simd/matrix_sub",
        "doc://com.apple.accelerate/documentation/simd/matrix_trace",
        "doc://com.apple.accelerate/documentation/simd/matrix_transpose",
        "doc://com.apple.accelerate/documentation/simd/nearbyint",
        "doc://com.apple.accelerate/documentation/simd/nexttoward",
        "doc://com.apple.accelerate/documentation/simd/remquo",
        "doc://com.apple.accelerate/documentation/simd/scalbln",
        "doc://com.apple.accelerate/documentation/simd/scalbn",
        "doc://com.apple.accelerate/documentation/simd/simd_lerp",
        "doc://com.apple.accelerate/documentation/simd/sincos",
        "doc://com.apple.accelerate/documentation/simd/sincospi",
        "doc://com.apple.accelerate/documentation/simd/trunc",
        "doc://com.apple.accelerate/documentation/simd/vector_abs",
        "doc://com.apple.accelerate/documentation/simd/vector_all",
        "doc://com.apple.accelerate/documentation/simd/vector_any",
        "doc://com.apple.accelerate/documentation/simd/vector_bitselect",
        "doc://com.apple.accelerate/documentation/simd/vector_char",
        "doc://com.apple.accelerate/documentation/simd/vector_char_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_clamp",
        "doc://com.apple.accelerate/documentation/simd/vector_cross",
        "doc://com.apple.accelerate/documentation/simd/vector_distance",
        "doc://com.apple.accelerate/documentation/simd/vector_distance_squared",
        "doc://com.apple.accelerate/documentation/simd/vector_dot",
        "doc://com.apple.accelerate/documentation/simd/vector_double",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_distance",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_length",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_normalize",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_project",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_recip",
        "doc://com.apple.accelerate/documentation/simd/vector_fast_rsqrt",
        "doc://com.apple.accelerate/documentation/simd/vector_float",
        "doc://com.apple.accelerate/documentation/simd/vector_fract",
        "doc://com.apple.accelerate/documentation/simd/vector_int",
        "doc://com.apple.accelerate/documentation/simd/vector_int_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_length",
        "doc://com.apple.accelerate/documentation/simd/vector_length_squared",
        "doc://com.apple.accelerate/documentation/simd/vector_long",
        "doc://com.apple.accelerate/documentation/simd/vector_long_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_max",
        "doc://com.apple.accelerate/documentation/simd/vector_min",
        "doc://com.apple.accelerate/documentation/simd/vector_mix",
        "doc://com.apple.accelerate/documentation/simd/vector_norm_inf",
        "doc://com.apple.accelerate/documentation/simd/vector_norm_one",
        "doc://com.apple.accelerate/documentation/simd/vector_normalize",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_distance",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_length",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_normalize",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_project",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_recip",
        "doc://com.apple.accelerate/documentation/simd/vector_precise_rsqrt",
        "doc://com.apple.accelerate/documentation/simd/vector_project",
        "doc://com.apple.accelerate/documentation/simd/vector_recip",
        "doc://com.apple.accelerate/documentation/simd/vector_reduce_add",
        "doc://com.apple.accelerate/documentation/simd/vector_reduce_max",
        "doc://com.apple.accelerate/documentation/simd/vector_reduce_min",
        "doc://com.apple.accelerate/documentation/simd/vector_reflect",
        "doc://com.apple.accelerate/documentation/simd/vector_refract",
        "doc://com.apple.accelerate/documentation/simd/vector_rsqrt",
        "doc://com.apple.accelerate/documentation/simd/vector_select",
        "doc://com.apple.accelerate/documentation/simd/vector_short",
        "doc://com.apple.accelerate/documentation/simd/vector_short_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_sign",
        "doc://com.apple.accelerate/documentation/simd/vector_smoothstep",
        "doc://com.apple.accelerate/documentation/simd/vector_step",
        "doc://com.apple.accelerate/documentation/simd/vector_uchar",
        "doc://com.apple.accelerate/documentation/simd/vector_uchar_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_uint",
        "doc://com.apple.accelerate/documentation/simd/vector_uint_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_ulong",
        "doc://com.apple.accelerate/documentation/simd/vector_ulong_sat",
        "doc://com.apple.accelerate/documentation/simd/vector_ushort",
        "doc://com.apple.accelerate/documentation/simd/vector_ushort_sat"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1SIMD_CURRENT_LIBRARY_VERSION/title",
          "value": "SIMD_CURRENT_LIBRARY_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1SIMD_CURRENT_LIBRARY_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SIMD_CURRENT_LIBRARY_VERSION"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
