{
  "abstract": [
    {
      "text": "Extracts elements from the sparse vector ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "x",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " into the corresponding location in the dense vector ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "y",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ", with both vectors containing double-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@sparse_unpack_vector_double",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sparse_unpack_vector_double"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_index",
        "text": "sparse_index"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_stride",
        "text": "sparse_stride"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sparse_unpack_vector_double"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "N"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "nz"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "zero"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "x"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "indx"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_index",
              "text": "sparse_index"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "y"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "incy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_stride",
              "text": "sparse_stride"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of elements in the dense vector ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "N"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of nonzero entries in the sparse vector ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nz"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "When ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", zero the elements of ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " which do not have nonzero values written to them. When ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ignore the elements of ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "y",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " which do not have nonzero values written to them.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "zero"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pointer to the dense storage for the values of the sparse vector ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ". The corresponding entry in ",
                  "type": "text"
                },
                {
                  "code": "indx",
                  "type": "codeVoice"
                },
                {
                  "text": " holds the index of the value. Contains ",
                  "type": "text"
                },
                {
                  "code": "nz",
                  "type": "codeVoice"
                },
                {
                  "text": " values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "x"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pointer to the dense storage for the index values of the sparse vector ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ". The corresponding entry in ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "x",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " holds the values of the vector.  Contains ",
                  "type": "text"
                },
                {
                  "code": "nz",
                  "type": "codeVoice"
                },
                {
                  "text": " values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Indices are always assumed to be stored in ascending order. Additionally, indices are assumed to be unique.  Undefined behavior if either of these assumptions are not met.All indices are 0 based (the first element of a pointer is ",
                  "type": "text"
                },
                {
                  "code": "ptr[0]",
                  "type": "codeVoice"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Pointer to the dense vector y.  Expected to be of size ",
                  "type": "text"
                },
                {
                  "code": "N * abs(incy)",
                  "type": "codeVoice"
                },
                {
                  "text": " elements.  Negative strides are supported.  Note, unlike dense BLAS routines, the pointer points to the last element when stride is negative. On exit, the entries described by the indices in ",
                  "type": "text"
                },
                {
                  "code": "indx",
                  "type": "codeVoice"
                },
                {
                  "text": " will be filled with the corresponding values in ",
                  "type": "text"
                },
                {
                  "code": "x",
                  "type": "codeVoice"
                },
                {
                  "text": " and all other values will be unchanged if parameter zero is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/false",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or set to zero if parameter zero is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "y"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Increment between valid values in the dense vector y.  Negative strides are supported.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "incy"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function extracts elements from the sparse vector ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "x",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " into the corresponding location in the dense vector ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "y",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". It can optionally zero the unused values of ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "y",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " by setting the ",
              "type": "text"
            },
            {
              "code": "zero",
              "type": "codeVoice"
            },
            {
              "text": " parameter to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The function is equivalent to the following code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if (zero) ",
            "    for (i in 0 .. N-1) ",
            "        y[i*incy] = 0;",
            "for (i in 0 .. nz-1) ",
            "    if (indx[i] < N) ",
            "        y[indx[i]*incy] = x[i];"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On exit, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "y",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " has been updated with the nonzero values. If ",
              "type": "text"
            },
            {
              "code": "nz",
              "type": "codeVoice"
            },
            {
              "text": " is less than or equal to zero, ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "y",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is unchanged.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple provides the BLAS and LAPACK libraries under the Accelerate framework to be in line with LAPACK 3.9.1. Starting with iOS 19, iPadOS 19, macOS 16, tvOS 19, watchOS 19, and visionOS 3, the libraries are in line with LAPACK 3.12.0. These new interfaces provide additional functionality, as well as a new ILP64 interface. To use the new interfaces, define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK",
                  "type": "codeVoice"
                },
                {
                  "text": " before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64",
                  "type": "codeVoice"
                },
                {
                  "text": ". For Swift projects, specify ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK=1",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64=1",
                  "type": "codeVoice"
                },
                {
                  "text": " as preprocessor macros in Xcode build settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension": {
      "abstract": [
        {
          "text": "The dimension type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "role": "symbol",
      "title": "sparse_dimension",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_dimension"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in the double-precision dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_vector_nonzero_count_double(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in the single-precision dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_vector_nonzero_count_float(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_index": {
      "abstract": [
        {
          "text": "The index type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "role": "symbol",
      "title": "sparse_index",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_index"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Packs nonzero values from a double-precision dense vector to a destination array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_pack_vector_double(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Packs nonzero values from a single-precision dense vector to a destination array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_pack_vector_float(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride": {
      "abstract": [
        {
          "text": "The stride type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_stride"
        }
      ],
      "role": "symbol",
      "title": "sparse_stride",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Extracts elements from the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " into the corresponding location in the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both vectors containing double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_unpack_vector_double(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Extracts elements from the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " into the corresponding location in the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both vectors containing single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_unpack_vector_float(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sparse-Utility-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)"
      ],
      "title": "Sparse Utility Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sparse_unpack_vector_double"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sparse-Utility-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)"
              ],
              "title": "Sparse Utility Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparse_unpack_vector_double"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "N"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "nz"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "zero"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "restrict"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "x"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_index",
                    "text": "sparse_index"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "restrict"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indx"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "restrict"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "y"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_stride",
                    "text": "sparse_stride"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "incy"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of elements in the dense vector ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "y",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "N"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of nonzero entries in the sparse vector ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "nz"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "When ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", zero the elements of ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "y",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " which do not have nonzero values written to them. When ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " ignore the elements of ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "y",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " which do not have nonzero values written to them.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "zero"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pointer to the dense storage for the values of the sparse vector ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ". The corresponding entry in ",
                        "type": "text"
                      },
                      {
                        "code": "indx",
                        "type": "codeVoice"
                      },
                      {
                        "text": " holds the index of the value. Contains ",
                        "type": "text"
                      },
                      {
                        "code": "nz",
                        "type": "codeVoice"
                      },
                      {
                        "text": " values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "x"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pointer to the dense storage for the index values of the sparse vector ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ". The corresponding entry in ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "x",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " holds the values of the vector.  Contains ",
                        "type": "text"
                      },
                      {
                        "code": "nz",
                        "type": "codeVoice"
                      },
                      {
                        "text": " values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Indices are always assumed to be stored in ascending order. Additionally, indices are assumed to be unique.  Undefined behavior if either of these assumptions are not met.All indices are 0 based (the first element of a pointer is ",
                        "type": "text"
                      },
                      {
                        "code": "ptr[0]",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indx"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pointer to the dense vector y.  Expected to be of size ",
                        "type": "text"
                      },
                      {
                        "code": "N * abs(incy)",
                        "type": "codeVoice"
                      },
                      {
                        "text": " elements.  Negative strides are supported.  Note, unlike dense BLAS routines, the pointer points to the last element when stride is negative. On exit, the entries described by the indices in ",
                        "type": "text"
                      },
                      {
                        "code": "indx",
                        "type": "codeVoice"
                      },
                      {
                        "text": " will be filled with the corresponding values in ",
                        "type": "text"
                      },
                      {
                        "code": "x",
                        "type": "codeVoice"
                      },
                      {
                        "text": " and all other values will be unchanged if parameter zero is ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/false",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", or set to zero if parameter zero is ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "y"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Increment between valid values in the dense vector y.  Negative strides are supported.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "incy"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/title",
          "value": "sparse_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_double(_:_:_:)/title",
          "value": "sparse_get_vector_nonzero_count_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_double(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_vector_nonzero_count_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_double(_:_:_:_:_:_:)/title",
          "value": "sparse_pack_vector_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_double(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_pack_vector_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_float(_:_:_:_:_:_:_:)/title",
          "value": "sparse_unpack_vector_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_float(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_double(_:_:_:_:_:_:_:)/title",
          "value": "sparse_unpack_vector_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_double(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/title",
          "value": "sparse_dimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_float(_:_:_:)/title",
          "value": "sparse_get_vector_nonzero_count_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_float(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_vector_nonzero_count_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/title",
          "value": "sparse_stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_float(_:_:_:_:_:_:)/title",
          "value": "sparse_pack_vector_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_float(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_pack_vector_float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
