{
  "abstract": [
    {
      "text": "Returns a single-precision sparse matrix object that is stored in block-entry format with a fixed block size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_float(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@sparse_matrix_block_create_float",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sparse_matrix_block_create_float"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_dimension",
        "text": "sparse_dimension"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_matrix_float",
        "text": "sparse_matrix_float"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sparse_matrix_block_create_float"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "sparse_matrix_block_create_float(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sparse_matrix_block_create_float"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Mb"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Nb"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "k"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "l"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_dimension",
              "text": "sparse_dimension"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_float",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_matrix_float",
              "text": "sparse_matrix_float"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of rows in terms of blocks of the matrix. There are a total of ",
                  "type": "text"
                },
                {
                  "code": "Mb * k",
                  "type": "codeVoice"
                },
                {
                  "text": " rows in the matrix.  Must be greater than 0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Mb"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of columns in terms of blocks of the matrix.  There are a total of ",
                  "type": "text"
                },
                {
                  "code": "Nb * l",
                  "type": "codeVoice"
                },
                {
                  "text": " columns in the matrix.  Must be greater than 0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Nb"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The row dimension of a block in the sparse matrix.  Must be greater than 0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "k"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The column dimension of a block in the sparse matrix.  Must be greater than 0.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "l"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A matrix object that is ready for receiving entries.  If an error occurs, ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " is returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a sparse matrix object that is stored in block-entry format and is ready to receive values from the various block insert routines.  Blocks are are of fixed dimensions ",
              "type": "text"
            },
            {
              "code": "k * l",
              "type": "codeVoice"
            },
            {
              "text": ".  Block-entry format means blocks of dense regions will be stored at block indices ",
              "type": "text"
            },
            {
              "code": "i,j",
              "type": "codeVoice"
            },
            {
              "text": ".  For point wise format use non block version of create. See the various insert routines for details on inserting values into this matrix object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple provides the BLAS and LAPACK libraries under the Accelerate framework to be in line with LAPACK 3.9.1. Starting with iOS 19, iPadOS 19, macOS 16, tvOS 19, watchOS 19, and visionOS 3, the libraries are in line with LAPACK 3.12.0. These new interfaces provide additional functionality, as well as a new ILP64 interface. To use the new interfaces, define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK",
                  "type": "codeVoice"
                },
                {
                  "text": " before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64",
                  "type": "codeVoice"
                },
                {
                  "text": ". For Swift projects, specify ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK=1",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64=1",
                  "type": "codeVoice"
                },
                {
                  "text": " as preprocessor macros in Xcode build settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension": {
      "abstract": [
        {
          "text": "The dimension type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "role": "symbol",
      "title": "sparse_dimension",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_dimension"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_double(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Inserts a dense block of entries into a double-precision matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_insert_block_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_double(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_insert_block_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_insert_block_double(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_insert_block_double(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_float(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Inserts a dense block of entries into a single-precision matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_insert_block_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_float(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_insert_block_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_insert_block_float(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_insert_block_float(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_double(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a double-precision sparse matrix object that is stored in block-entry format with a fixed block size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_block_create_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_double(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_block_create_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_block_create_double(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_block_create_double(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_float(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a single-precision sparse matrix object that is stored in block-entry format with a fixed block size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_block_create_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_float(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_block_create_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_block_create_float(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_block_create_float(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_float": {
      "abstract": [
        {
          "text": "Sparse matrix opaque type for float.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_float",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_double(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a double-precision sparse matrix object that is stored in block-entry format with a variable block size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_variable_block_create_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_double(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_variable_block_create_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_variable_block_create_double(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_variable_block_create_double(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_float(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a single-precision sparse matrix object that is stored in block-entry format with a variable block size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_variable_block_create_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_float(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_variable_block_create_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_variable_block_create_float(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_variable_block_create_float(_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Creation-and-Population",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_double(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_double(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_float(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_double(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_float(_:_:_:_:_:_:)"
      ],
      "title": "Matrix Creation and Population"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sparse_matrix_block_create_float"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_block_create_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-Creation-and-Population",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_block_create_double(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_double(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_variable_block_create_float(_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_double(_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_insert_block_float(_:_:_:_:_:_:)"
              ],
              "title": "Matrix Creation and Population"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_float",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_matrix_float",
                    "text": "sparse_matrix_float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparse_matrix_block_create_float"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "Mb"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "Nb"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "k"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_dimension",
                    "text": "sparse_dimension"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "l"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of rows in terms of blocks of the matrix. There are a total of ",
                        "type": "text"
                      },
                      {
                        "code": "Mb * k",
                        "type": "codeVoice"
                      },
                      {
                        "text": " rows in the matrix.  Must be greater than 0.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "Mb"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of columns in terms of blocks of the matrix.  There are a total of ",
                        "type": "text"
                      },
                      {
                        "code": "Nb * l",
                        "type": "codeVoice"
                      },
                      {
                        "text": " columns in the matrix.  Must be greater than 0.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "Nb"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The row dimension of a block in the sparse matrix.  Must be greater than 0.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "k"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The column dimension of a block in the sparse matrix.  Must be greater than 0.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "l"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A matrix object that is ready for receiving entries.  If an error occurs, ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " is returned.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_block_create_float(_:_:_:_:)/title",
          "value": "sparse_matrix_block_create_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_block_create_float(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_block_create_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_block_create_double(_:_:_:_:)/title",
          "value": "sparse_matrix_block_create_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_block_create_double(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_block_create_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_variable_block_create_double(_:_:_:_:)/title",
          "value": "sparse_matrix_variable_block_create_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_variable_block_create_double(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_variable_block_create_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_variable_block_create_float(_:_:_:_:)/title",
          "value": "sparse_matrix_variable_block_create_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_variable_block_create_float(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_variable_block_create_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_insert_block_double(_:_:_:_:_:_:)/title",
          "value": "sparse_insert_block_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_insert_block_double(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_insert_block_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/title",
          "value": "sparse_dimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_float/title",
          "value": "sparse_matrix_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_insert_block_float(_:_:_:_:_:_:)/title",
          "value": "sparse_insert_block_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_insert_block_float(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_insert_block_float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_matrix_block_create_float(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_matrix_block_create_float(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
