{
  "abstract": [
    {
      "text": "Multiply sparse and dense matrices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-matrix-multiplication"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sparse Matrix and Dense Matrix Multiplication"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-8d9lh": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "= AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-8d9lh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiply(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiply(_:_:_:)-8d9lh"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-9kraw": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "= AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": "_ _on a sparse matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-9kraw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiply(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiply(_:_:_:)-9kraw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-2qh3a": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y = alpha * AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-2qh3a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiply(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiply(_:_:_:_:)-2qh3a"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-73ruq": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y = alpha * AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-73ruq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiply"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiply(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiply(_:_:_:_:)-73ruq"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-8pgpq": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y += AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-8pgpq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiplyAdd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiplyadd(_:_:_:)-8pgpq"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-lgm5": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y += AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-lgm5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiplyAdd(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiplyadd(_:_:_:)-lgm5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-86gfz": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y += alpha * AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-86gfz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiplyAdd(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiplyadd(_:_:_:_:)-86gfz"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-n61k": {
      "abstract": [
        {
          "text": "Performs the multiply operation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Y += alpha * AX",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " on a sparse matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-n61k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMultiplyAdd"
        }
      ],
      "role": "symbol",
      "title": "SparseMultiplyAdd(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsemultiplyadd(_:_:_:_:)-n61k"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication": {
      "abstract": [
        {
          "text": "Multiply sparse matrices and dense vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix and Dense Vector Multiplication",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-and-dense-vector-multiplication"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transposition": {
      "abstract": [
        {
          "text": "Transpose matrices, factorizations, and subfactors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transposition",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transposition",
      "type": "topic",
      "url": "/documentation/accelerate/transposition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiplying-and-transposing-sparse-matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication",
        "doc://com.apple.accelerate/documentation/Accelerate/transposition"
      ],
      "title": "Multiplying and transposing sparse matrices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Multiplication-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-8d9lh",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:)-9kraw",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-73ruq",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiply(_:_:_:_:)-2qh3a"
      ],
      "title": "Multiplication Functions"
    },
    {
      "anchor": "Multiply-Add-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-lgm5",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:)-8pgpq",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-86gfz",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseMultiplyAdd(_:_:_:_:)-n61k"
      ],
      "title": "Multiply-Add Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:)-9kraw/title",
          "value": "SparseMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:)-9kraw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:_:)-2qh3a/title",
          "value": "SparseMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:_:)-2qh3a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:_:)-n61k/title",
          "value": "SparseMultiplyAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:_:)-n61k/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiplyAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:_:)-86gfz/title",
          "value": "SparseMultiplyAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:_:)-86gfz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiplyAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:)-8pgpq/title",
          "value": "SparseMultiplyAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:)-8pgpq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiplyAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:)-8d9lh/title",
          "value": "SparseMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:)-8d9lh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:_:)-73ruq/title",
          "value": "SparseMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiply(_:_:_:_:)-73ruq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:)-lgm5/title",
          "value": "SparseMultiplyAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMultiplyAdd(_:_:_:)-lgm5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMultiplyAdd"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
