{
  "abstract": [
    {
      "text": "A structure that represents the factorization of a matrix of double-precision, floating-point values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseOpaqueFactorization_Double",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseOpaqueFactorization_Double"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseOpaqueFactorization_Double"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SparseOpaqueFactorization_Double"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-3cnxt",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to free resources that these objects hold.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An object can be in one of the following states:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Something is wrong with symbolic factorization, nothing is valid.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Indication: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float/symbolicFactorization",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "< 0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Symbolic factorization is good, but fails in numeric factorization initialization.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Indication: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float/symbolicFactorization",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": ">= 0 &&",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "< 0 &&",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "== NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " You can use symbolic factorization for future calls.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Symbolic factorization is good, factor allocation and initialization are correct, but numeric factorization fails.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " For example, the system attempts a Cholesky factorization of an indefinite matrix.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Indication: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float/symbolicFactorization",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": ">= 0 &&",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "< 0 &&",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "not NULL",
                      "type": "codeVoice"
                    },
                    {
                      "text": "  ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " You may pass this object to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRefactor(_:_:)-8vrf5",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " with a modified matrix.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Symbolic and numeric factorizations are both good.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Indication: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": ">= 0",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-3cnxt": {
      "abstract": [
        {
          "text": "Releases a factorization of a matrix of double-precision values’ references to any memory that the Sparse Solvers library allocates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCleanup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-3cnxt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCleanup"
        }
      ],
      "role": "symbol",
      "title": "SparseCleanup(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecleanup(_:)-3cnxt"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/attributes": {
      "abstract": [
        {
          "text": "The attributes of a factorization object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseAttributes_t",
          "text": "SparseAttributes_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "role": "symbol",
      "title": "attributes",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/attributes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init()": {
      "abstract": [
        {
          "text": "Creates a new opaque factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init(status:attributes:symbolicFactorization:userFactorStorage:numericFactorization:solveWorkspaceRequiredStatic:solveWorkspaceRequiredPerRHS:)": {
      "abstract": [
        {
          "text": "Creates a new opaque factorization with the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseStatus_t",
          "text": "SparseStatus_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseAttributes_t",
          "text": "SparseAttributes_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "symbolicFactorization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userFactorStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numericFactorization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "solveWorkspaceRequiredStatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "solveWorkspaceRequiredPerRHS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init(status:attributes:symbolicFactorization:userFactorStorage:numericFactorization:solveWorkspaceRequiredStatic:solveWorkspaceRequiredPerRHS:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(status:attributes:symbolicFactorization:userFactorStorage:numericFactorization:solveWorkspaceRequiredStatic:solveWorkspaceRequiredPerRHS:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/init(status:attributes:symbolicfactorization:userfactorstorage:numericfactorization:solveworkspacerequiredstatic:solveworkspacerequiredperrhs:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization": {
      "abstract": [
        {
          "text": "The pointer to a private internal representation of a numeric factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numericFactorization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numericFactorization"
        }
      ],
      "role": "symbol",
      "title": "numericFactorization",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/numericfactorization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredPerRHS": {
      "abstract": [
        {
          "text": "The required size of the per-right-hand-side workspace for a call to a sparse solve function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "solveWorkspaceRequiredPerRHS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredPerRHS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "solveWorkspaceRequiredPerRHS"
        }
      ],
      "role": "symbol",
      "title": "solveWorkspaceRequiredPerRHS",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/solveworkspacerequiredperrhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredStatic": {
      "abstract": [
        {
          "text": "The required size of the static workspace for a call to a sparse solve function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "solveWorkspaceRequiredStatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredStatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "solveWorkspaceRequiredStatic"
        }
      ],
      "role": "symbol",
      "title": "solveWorkspaceRequiredStatic",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/solveworkspacerequiredstatic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status": {
      "abstract": [
        {
          "text": "The status of the factorization object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseStatus_t",
          "text": "SparseStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/status"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/symbolicFactorization": {
      "abstract": [
        {
          "text": "The symbolic factorization that this numeric factorization depends on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicFactorization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/symbolicFactorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolicFactorization"
        }
      ],
      "role": "symbol",
      "title": "symbolicFactorization",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/symbolicfactorization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/userFactorStorage": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether user-provided storage backs this object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userFactorStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/userFactorStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userFactorStorage"
        }
      ],
      "role": "symbol",
      "title": "userFactorStorage",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double/userfactorstorage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float/symbolicFactorization": {
      "abstract": [
        {
          "text": "The symbolic factorization that this numeric factorization depends on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicFactorization"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float/symbolicFactorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolicFactorization"
        }
      ],
      "role": "symbol",
      "title": "symbolicFactorization",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_float/symbolicfactorization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization/status": {
      "abstract": [
        {
          "text": "The status of the factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseStatus_t",
          "text": "SparseStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesymbolicfactorization/status"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRefactor(_:_:)-8vrf5": {
      "abstract": [
        {
          "text": "Computes a factorization of the specified double-precision matrix using an existing factorization’s storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRefactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRefactor(_:_:)-8vrf5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRefactor"
        }
      ],
      "role": "symbol",
      "title": "SparseRefactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparserefactor(_:_:)-8vrf5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods": {
      "abstract": [
        {
          "text": "Use direct methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using direct methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-direct-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense matrix using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Matrix RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-matrix-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense vector using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Vector RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-vector-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions": {
      "abstract": [
        {
          "text": "Compute the factorization of a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix Factor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-factor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions": {
      "abstract": [
        {
          "text": "Recompute a factorization using the numerical data from a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Refactor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-refactor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions": {
      "abstract": [
        {
          "text": "Calculate the symbolic factorization of a matrix, and solve systems using precalculated symbolic factorizations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Symbolic Factorization Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-symbolic-factorization-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions": {
      "abstract": [
        {
          "text": "Extract and work with subfactors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subfactor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/subfactor-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Solving-systems-with-direct-sparse-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions"
      ],
      "title": "Solving systems with direct sparse methods"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Opaque-Factorization",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/init(status:attributes:symbolicFactorization:userFactorStorage:numericFactorization:solveWorkspaceRequiredStatic:solveWorkspaceRequiredPerRHS:)"
      ],
      "title": "Creating an Opaque Factorization"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/attributes",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredPerRHS",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredStatic",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/symbolicFactorization",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/userFactorStorage"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseOpaqueFactorization_Double"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/attributes",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/numericFactorization",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredPerRHS",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/solveWorkspaceRequiredStatic",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/status",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/symbolicFactorization",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double/userFactorStorage"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Solving-systems-with-direct-sparse-methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float"
              ],
              "title": "Solving systems with direct sparse methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseOpaqueFactorization_Double"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1symbolicFactorization/title",
          "value": "symbolicFactorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1symbolicFactorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolicFactorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1solveWorkspaceRequiredStatic/title",
          "value": "solveWorkspaceRequiredStatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1solveWorkspaceRequiredStatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "solveWorkspaceRequiredStatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/title",
          "value": "SparseOpaqueFactorization_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCleanup(_:)-3cnxt/title",
          "value": "SparseCleanup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCleanup(_:)-3cnxt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCleanup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1userFactorStorage/title",
          "value": "userFactorStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1userFactorStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userFactorStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1numericFactorization/title",
          "value": "numericFactorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1numericFactorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numericFactorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSymbolicFactorization~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSymbolicFactorization~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRefactor(_:_:)-8vrf5/title",
          "value": "SparseRefactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRefactor(_:_:)-8vrf5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRefactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/title",
          "value": "SparseOpaqueFactorization_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float~1symbolicFactorization/title",
          "value": "symbolicFactorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float~1symbolicFactorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolicFactorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1solveWorkspaceRequiredPerRHS/title",
          "value": "solveWorkspaceRequiredPerRHS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1solveWorkspaceRequiredPerRHS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "solveWorkspaceRequiredPerRHS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1attributes/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double~1attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparseopaquefactorization_double"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparseopaquefactorization_double"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
