{
  "abstract": [
    {
      "text": "A lower triangular matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_TRIANGULAR"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@sparse_matrix_property@SPARSE_LOWER_TRIANGULAR",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SPARSE_LOWER_TRIANGULAR"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@sparse_matrix_property",
        "text": "sparse_matrix_property"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SPARSE_LOWER_TRIANGULAR"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SPARSE_LOWER_TRIANGULAR"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SPARSE_LOWER_TRIANGULAR"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@sparse_matrix_property",
              "text": "sparse_matrix_property"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_SYMMETRIC": {
      "abstract": [
        {
          "text": "A symmetric matrix with values derived from the lower triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_LOWER_SYMMETRIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_SYMMETRIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_LOWER_SYMMETRIC"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_LOWER_SYMMETRIC",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_lower_symmetric"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_TRIANGULAR": {
      "abstract": [
        {
          "text": "A lower triangular matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_LOWER_TRIANGULAR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_TRIANGULAR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_LOWER_TRIANGULAR"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_LOWER_TRIANGULAR",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_lower_triangular"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_SYMMETRIC": {
      "abstract": [
        {
          "text": "A symmetric matrix with values derived from the upper triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_UPPER_SYMMETRIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_SYMMETRIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_UPPER_SYMMETRIC"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_UPPER_SYMMETRIC",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_upper_symmetric"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_TRIANGULAR": {
      "abstract": [
        {
          "text": "An upper triangular matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_UPPER_TRIANGULAR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_TRIANGULAR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_UPPER_TRIANGULAR"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_UPPER_TRIANGULAR",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_upper_triangular"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property": {
      "abstract": [
        {
          "text": "The matrix property type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_property"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_property",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_TRIANGULAR",
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_SYMMETRIC",
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_SYMMETRIC"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SPARSE_LOWER_TRIANGULAR"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_LOWER_TRIANGULAR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_property"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_TRIANGULAR",
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_UPPER_SYMMETRIC",
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_LOWER_SYMMETRIC"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SPARSE_LOWER_TRIANGULAR"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_UPPER_SYMMETRIC/title",
          "value": "SPARSE_UPPER_SYMMETRIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_UPPER_SYMMETRIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_UPPER_SYMMETRIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_UPPER_TRIANGULAR/title",
          "value": "SPARSE_UPPER_TRIANGULAR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_UPPER_TRIANGULAR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_UPPER_TRIANGULAR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_LOWER_TRIANGULAR/title",
          "value": "SPARSE_LOWER_TRIANGULAR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_LOWER_TRIANGULAR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_LOWER_TRIANGULAR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/title",
          "value": "sparse_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_property/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_LOWER_SYMMETRIC/title",
          "value": "SPARSE_LOWER_SYMMETRIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_LOWER_SYMMETRIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_LOWER_SYMMETRIC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_lower_triangular"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_lower_triangular"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
