{
  "abstract": [
    {
      "text": "A structure that contains options that affect the numerical stage of a sparse factorization.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseNumericFactorOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseNumericFactorOptions"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseNumericFactorOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SparseNumericFactorOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " supports the following types of scaling:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingDefault",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Default scaling — ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingEquilibriationInf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " if ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "LDLᵀ",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ", or no scaling if Cholesky.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "User scaling if ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is nonnull; otherwise, no scaling.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingEquilibriationInf",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Norm equilibration scaling using infinity norm.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Note that the system clamps ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to range ",
              "type": "text"
            },
            {
              "code": "[0,0.5]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t": {
      "abstract": [
        {
          "text": "Options that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseControl_t"
        }
      ],
      "role": "symbol",
      "title": "SparseControl_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecontrol_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t": {
      "abstract": [
        {
          "text": "Constants that define the factorization type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactorization_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactorization_t"
        }
      ],
      "role": "symbol",
      "title": "SparseFactorization_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactorization_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the numerical stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseNumericFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseNumericFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control": {
      "abstract": [
        {
          "text": "The flags that control the computation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseControl_t",
          "text": "SparseControl_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "control"
        }
      ],
      "role": "symbol",
      "title": "control",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/control"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()": {
      "abstract": [
        {
          "text": "Returns a new numeric factor options structure with default properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)": {
      "abstract": [
        {
          "text": "Returns a new numeric factor options structure with the specified properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "control"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseControl_t",
          "text": "SparseControl_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scalingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "pivotTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "zeroTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/init(control:scalingmethod:scaling:pivottolerance:zerotolerance:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance": {
      "abstract": [
        {
          "text": "The pivot tolerance that threshold partial pivoting uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pivotTolerance"
        }
      ],
      "role": "symbol",
      "title": "pivotTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/pivottolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling": {
      "abstract": [
        {
          "text": "An array that scales the matrix before factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaling"
        }
      ],
      "role": "symbol",
      "title": "scaling",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/scaling"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod": {
      "abstract": [
        {
          "text": "The scaling method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalingMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scalingMethod"
        }
      ],
      "role": "symbol",
      "title": "scalingMethod",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/scalingmethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance": {
      "abstract": [
        {
          "text": "The zero tolerance that some pivoting modes use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zeroTolerance"
        }
      ],
      "role": "symbol",
      "title": "zeroTolerance",
      "type": "topic",
      "url": "/documentation/accelerate/sparsenumericfactoroptions/zerotolerance"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingDefault": {
      "abstract": [
        {
          "text": "Default scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScalingDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScalingDefault"
        }
      ],
      "role": "symbol",
      "title": "SparseScalingDefault",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescalingdefault"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingEquilibriationInf": {
      "abstract": [
        {
          "text": "The norm equilibration scaling using infinity norm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScalingEquilibriationInf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingEquilibriationInf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScalingEquilibriationInf"
        }
      ],
      "role": "symbol",
      "title": "SparseScalingEquilibriationInf",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescalingequilibriationinf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser": {
      "abstract": [
        {
          "text": "User scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScalingUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseScaling_t",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScalingUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScalingUser"
        }
      ],
      "role": "symbol",
      "title": "SparseScalingUser",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescalinguser"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t": {
      "abstract": [
        {
          "text": "Options that define which scaling algorithm to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseScaling_t"
        }
      ],
      "role": "symbol",
      "title": "SparseScaling_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsescaling_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the symbolic stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseSymbolicFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures-that-Specify-Factorization-Type-and-Factorization-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions"
      ],
      "title": "Structures that Specify Factorization Type and Factorization Options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Numeric-Factor-Options-Stucture",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init(control:scalingMethod:scaling:pivotTolerance:zeroTolerance:)",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/init()"
      ],
      "title": "Creating a Numeric Factor Options Stucture"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseNumericFactorOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/control",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseControl_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scalingMethod",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/scaling",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseScaling_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/pivotTolerance",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseNumericFactorOptions/zeroTolerance"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures-that-Specify-Factorization-Type-and-Factorization-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions"
              ],
              "title": "Structures that Specify Factorization Type and Factorization Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseNumericFactorOptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/title",
          "value": "SparseControl_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseControl_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseControl_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1control/title",
          "value": "control"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1control/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/title",
          "value": "pivotTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1pivotTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pivotTolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingDefault/title",
          "value": "SparseScalingDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScalingDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scalingMethod/title",
          "value": "scalingMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scalingMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scalingMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/title",
          "value": "SparseSymbolicFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingEquilibriationInf/title",
          "value": "SparseScalingEquilibriationInf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingEquilibriationInf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScalingEquilibriationInf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/title",
          "value": "SparseScaling_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScaling_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScaling_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/title",
          "value": "zeroTolerance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1zeroTolerance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zeroTolerance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/title",
          "value": "SparseNumericFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseNumericFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/title",
          "value": "SparseFactorization_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactorization_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactorization_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingUser/title",
          "value": "SparseScalingUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseScalingUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseScalingUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scaling/title",
          "value": "scaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseNumericFactorOptions~1scaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scaling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsenumericfactoroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsenumericfactoroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
