{
  "abstract": [
    {
      "text": "Creates a preconditioner for the specified matrix of double-precision values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-4ysww"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SparseCreatePreconditioner#$@EA@SparsePreconditioner_t#$@SA@SparseMatrix_Double#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseCreatePreconditioner"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
        "text": "SparsePreconditioner_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseMatrix_Double",
        "text": "SparseMatrix_Double"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
        "text": "SparseOpaquePreconditioner_Double"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseCreatePreconditioner"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SparseCreatePreconditioner(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseCreatePreconditioner"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
              "text": "SparsePreconditioner_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "A"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseMatrix_Double",
              "text": "SparseMatrix_Double"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
              "text": "SparseOpaquePreconditioner_Double"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of preconditioner to create.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix to construct a preconditioner for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "A"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure. You must free the resource through a call to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-45lq7",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " after you finish with the object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-45lq7": {
      "abstract": [
        {
          "text": "Releases a double-precision preconditioner’s references to any memory that the Sparse Solvers library allocates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCleanup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
          "text": "SparseOpaquePreconditioner_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-45lq7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCleanup"
        }
      ],
      "role": "symbol",
      "title": "SparseCleanup(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecleanup(_:)-45lq7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-4ysww": {
      "abstract": [
        {
          "text": "Creates a preconditioner for the specified matrix of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCreatePreconditioner"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
          "text": "SparsePreconditioner_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
          "text": "SparseOpaquePreconditioner_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-4ysww",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCreatePreconditioner"
        }
      ],
      "role": "symbol",
      "title": "SparseCreatePreconditioner(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecreatepreconditioner(_:_:)-4ysww"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-59ql5": {
      "abstract": [
        {
          "text": "Creates a preconditioner for the specified matrix of single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCreatePreconditioner"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
          "text": "SparsePreconditioner_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Float",
          "text": "SparseOpaquePreconditioner_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-59ql5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCreatePreconditioner"
        }
      ],
      "role": "symbol",
      "title": "SparseCreatePreconditioner(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecreatepreconditioner(_:_:)-59ql5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double": {
      "abstract": [
        {
          "text": "A structure that contains a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMatrix_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMatrix_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseMatrix_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparsematrix_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaquePreconditioner_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaquePreconditioner_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaquePreconditioner_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquepreconditioner_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Float": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaquePreconditioner_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaquePreconditioner_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaquePreconditioner_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquepreconditioner_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t": {
      "abstract": [
        {
          "text": "Constants that define the preconditioner type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparsePreconditioner_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparsePreconditioner_t"
        }
      ],
      "role": "symbol",
      "title": "SparsePreconditioner_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsepreconditioner_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Preconditioners",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-59ql5",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Float"
      ],
      "title": "Preconditioners"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseCreatePreconditioner"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCreatePreconditioner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Preconditioners",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseCreatePreconditioner(_:_:)-59ql5",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Float"
              ],
              "title": "Preconditioners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
                    "text": "SparseOpaquePreconditioner_Double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseCreatePreconditioner"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
                    "text": "SparsePreconditioner_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseMatrix_Double",
                    "text": "SparseMatrix_Double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "A"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of preconditioner to create.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "type"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix to construct a preconditioner for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "A"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaquePreconditioner_Double",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " structure. You must free the resource through a call to ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCleanup(_:)-45lq7",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " after you finish with the object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreatePreconditioner(_:_:)-4ysww/title",
          "value": "SparseCreatePreconditioner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreatePreconditioner(_:_:)-4ysww/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCreatePreconditioner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/title",
          "value": "SparseMatrix_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCleanup(_:)-45lq7/title",
          "value": "SparseCleanup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCleanup(_:)-45lq7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCleanup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Double/title",
          "value": "SparseOpaquePreconditioner_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaquePreconditioner_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaquePreconditioner_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Float/title",
          "value": "SparseOpaquePreconditioner_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaquePreconditioner_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaquePreconditioner_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaquePreconditioner_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/title",
          "value": "SparsePreconditioner_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparsePreconditioner_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparsePreconditioner_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreatePreconditioner(_:_:)-59ql5/title",
          "value": "SparseCreatePreconditioner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreatePreconditioner(_:_:)-59ql5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCreatePreconditioner"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsecreatepreconditioner(_:_:)-4ysww"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsecreatepreconditioner(_:_:)-4ysww"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
