{
  "abstract": [
    {
      "text": "Options for creating a least squares minimum residual method.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SparseLSMROptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseLSMROptions"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseLSMROptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SparseLSMROptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseLSMROptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "LSMR is a minimal residual (MINRES) method for solving least squares. Use LSMR to solve equations of the form ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Ax = b",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " where an exact solution doesn’t exist. The returned solution minimizes ‖ ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "b-Ax",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " ‖₂.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Although LSMR is equivalent to applying MINRES to the normal equations ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A__ᵀ__Ax = A__ᵀ__b",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " in exact arithmetic, it has superior numerical behavior and is the preferred method. Due to the implicit squaring of the condition of ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " in the normal equations, LSMR may struggle to converge in single precision. Use double-precision arithmetic where possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For symmetric positive-definite systems, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseConjugateGradient(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For square, full-rank unsymmetric or indefinite equations, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRES(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseConjugateGradient(_:)": {
      "abstract": [
        {
          "text": "Returns a conjugate gradient (CG) method with specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseConjugateGradient"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseCGOptions",
          "text": "SparseCGOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseConjugateGradient(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseConjugateGradient"
        }
      ],
      "role": "symbol",
      "title": "SparseConjugateGradient(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseconjugategradient(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRES(_:)": {
      "abstract": [
        {
          "text": "Returns a generalized minimal residual (GMRES) method with specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGMRES"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseGMRESOptions",
          "text": "SparseGMRESOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGMRES(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGMRES"
        }
      ],
      "role": "symbol",
      "title": "SparseGMRES(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegmres(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR()": {
      "abstract": [
        {
          "text": "Returns a default least squares minimum residual (LSMR) method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseLSMR"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseLSMR"
        }
      ],
      "role": "symbol",
      "title": "SparseLSMR()",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmr()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR(_:)": {
      "abstract": [
        {
          "text": "Returns a least squares minimum residual method with specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseLSMR"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseLSMROptions",
          "text": "SparseLSMROptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseLSMR"
        }
      ],
      "role": "symbol",
      "title": "SparseLSMR(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmr(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMRConvergenceTest_t": {
      "abstract": [
        {
          "text": "Constants that specify the type of convergence test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseLSMRConvergenceTest_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMRConvergenceTest_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseLSMRConvergenceTest_t"
        }
      ],
      "role": "symbol",
      "title": "SparseLSMRConvergenceTest_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmrconvergencetest_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions": {
      "abstract": [
        {
          "text": "Options for creating a least squares minimum residual method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseLSMROptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseLSMROptions"
        }
      ],
      "role": "symbol",
      "title": "SparseLSMROptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/atol": {
      "abstract": [
        {
          "text": "The absolute tolerance (default test) or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " tolerance (Fong-Saunders test).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/atol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "atol"
        }
      ],
      "role": "symbol",
      "title": "atol",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/atol"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/btol": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " tolerance (Fong-Saunders test only).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "btol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/btol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "btol"
        }
      ],
      "role": "symbol",
      "title": "btol",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/btol"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/conditionLimit": {
      "abstract": [
        {
          "text": "The condition number limit (Fong-Saunders test only).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conditionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/conditionLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "conditionLimit"
        }
      ],
      "role": "symbol",
      "title": "conditionLimit",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/conditionlimit"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/convergenceTest": {
      "abstract": [
        {
          "text": "The convergence test to use for iterative solve methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convergenceTest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseLSMRConvergenceTest_t",
          "text": "SparseLSMRConvergenceTest_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/convergenceTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convergenceTest"
        }
      ],
      "role": "symbol",
      "title": "convergenceTest",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/convergencetest"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init()": {
      "abstract": [
        {
          "text": "Returns a new LSMR options structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init(reportError:lambda:nvec:convergenceTest:atol:rtol:btol:conditionLimit:maxIterations:reportStatus:)": {
      "abstract": [
        {
          "text": "Returns a new LSMR options structure using the specified parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "reportError"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "lambda"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nvec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "convergenceTest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseLSMRConvergenceTest_t",
          "text": "SparseLSMRConvergenceTest_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "atol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rtol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "btol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conditionLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxIterations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reportStatus"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init(reportError:lambda:nvec:convergenceTest:atol:rtol:btol:conditionLimit:maxIterations:reportStatus:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(reportError:lambda:nvec:convergenceTest:atol:rtol:btol:conditionLimit:maxIterations:reportStatus:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/init(reporterror:lambda:nvec:convergencetest:atol:rtol:btol:conditionlimit:maxiterations:reportstatus:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/lambda": {
      "abstract": [
        {
          "text": "The damping parameter lambda for regularized least squares.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lambda"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/lambda",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lambda"
        }
      ],
      "role": "symbol",
      "title": "lambda",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/lambda"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/maxIterations": {
      "abstract": [
        {
          "text": "The maximum number of iterations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxIterations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/maxIterations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxIterations"
        }
      ],
      "role": "symbol",
      "title": "maxIterations",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/maxiterations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/nvec": {
      "abstract": [
        {
          "text": "The number of vectors to use for local reorthogonalization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nvec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/nvec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nvec"
        }
      ],
      "role": "symbol",
      "title": "nvec",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/nvec"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportError": {
      "abstract": [
        {
          "text": "An optional error-reporting routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportError"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportError"
        }
      ],
      "role": "symbol",
      "title": "reportError",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/reporterror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportStatus": {
      "abstract": [
        {
          "text": "An optional status-reporting routine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reportStatus"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reportStatus"
        }
      ],
      "role": "symbol",
      "title": "reportStatus",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/reportstatus"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/rtol": {
      "abstract": [
        {
          "text": "The relative convergence tolerance (default test only).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rtol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/rtol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rtol"
        }
      ],
      "role": "symbol",
      "title": "rtol",
      "type": "topic",
      "url": "/documentation/accelerate/sparselsmroptions/rtol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sparse-Iterative-Methods-for-Overdetermined-and-Underdetermined-Systems",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR()",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR(_:)"
      ],
      "title": "Sparse Iterative Methods for Overdetermined and Underdetermined Systems"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/init(reportError:lambda:nvec:convergenceTest:atol:rtol:btol:conditionLimit:maxIterations:reportStatus:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Inspecting-LSMR-Options",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/atol",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/btol",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/conditionLimit",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/convergenceTest",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMRConvergenceTest_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/lambda",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/maxIterations",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/nvec",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportError",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportStatus",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/rtol"
      ],
      "title": "Inspecting LSMR Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseLSMROptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMROptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMROptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-LSMR-Options",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/atol",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/btol",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/conditionLimit",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/convergenceTest",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMRConvergenceTest_t",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/lambda",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/maxIterations",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/nvec",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportError",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/reportStatus",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMROptions/rtol"
              ],
              "title": "Inspecting LSMR Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sparse-Iterative-Methods-for-Overdetermined-and-Underdetermined-Systems",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR()",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseLSMR(_:)"
              ],
              "title": "Sparse Iterative Methods for Overdetermined and Underdetermined Systems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseLSMROptions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1maxIterations/title",
          "value": "maxIterations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1maxIterations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxIterations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGMRES(_:)/title",
          "value": "SparseGMRES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGMRES(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGMRES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseConjugateGradient(_:)/title",
          "value": "SparseConjugateGradient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseConjugateGradient(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseConjugateGradient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1nvec/title",
          "value": "nvec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1nvec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nvec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions/title",
          "value": "SparseLSMROptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMROptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMROptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1btol/title",
          "value": "btol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1btol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "btol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1reportStatus/title",
          "value": "reportStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1reportStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMRConvergenceTest_t/title",
          "value": "SparseLSMRConvergenceTest_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMRConvergenceTest_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMRConvergenceTest_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMRConvergenceTest_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMRConvergenceTest_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1reportError/title",
          "value": "reportError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1reportError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1lambda/title",
          "value": "lambda"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1lambda/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lambda"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1convergenceTest/title",
          "value": "convergenceTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1convergenceTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "convergenceTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMR()/title",
          "value": "SparseLSMR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMR()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMR(_:)/title",
          "value": "SparseLSMR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMR(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseLSMR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1conditionLimit/title",
          "value": "conditionLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1conditionLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "conditionLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1atol/title",
          "value": "atol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1atol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "atol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1rtol/title",
          "value": "rtol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseLSMROptions~1rtol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rtol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparselsmroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparselsmroptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
