{
  "abstract": [
    {
      "text": "Perform a single iteration of the specified iterative method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterate-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sparse Iterate Functions"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Double(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the size in bytes necessary for a call to the double-precision sparse iterate method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetStateSize_Double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Double(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetStateSize_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseGetStateSize_Double(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegetstatesize_double(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Float(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the size in bytes necessary for a call to the single-precision sparse iterate method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetStateSize_Float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Float(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetStateSize_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseGetStateSize_Float(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegetstatesize_float(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-1el7r": {
      "abstract": [
        {
          "text": "Performs a single iteration of the specified iterative method for single-precision matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-1el7r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterate"
        }
      ],
      "role": "symbol",
      "title": "SparseIterate(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterate(_:_:_:_:_:_:_:_:)-1el7r"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-c54n": {
      "abstract": [
        {
          "text": "Performs a single iteration of the specified iterative method for double-precision matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-c54n",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterate"
        }
      ],
      "role": "symbol",
      "title": "SparseIterate(_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterate(_:_:_:_:_:_:_:_:)-c54n"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-1anay": {
      "abstract": [
        {
          "text": "Performs a single iteration of the specified iterative method for single-precision matrices, applying a preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Float",
          "text": "SparseOpaquePreconditioner_Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-1anay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterate"
        }
      ],
      "role": "symbol",
      "title": "SparseIterate(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterate(_:_:_:_:_:_:_:_:_:)-1anay"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-99ji7": {
      "abstract": [
        {
          "text": "Performs a single iteration of the specified iterative method for double-precision matrices, applying a preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
          "text": "SparseOpaquePreconditioner_Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-99ji7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterate"
        }
      ],
      "role": "symbol",
      "title": "SparseIterate(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterate(_:_:_:_:_:_:_:_:_:)-99ji7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/preconditioners": {
      "abstract": [
        {
          "text": "Create preconditioners for iterative solves.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/preconditioners",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preconditioners",
      "type": "topic",
      "url": "/documentation/accelerate/preconditioners"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods": {
      "abstract": [
        {
          "text": "Use iterative methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using iterative methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-iterative-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-methods": {
      "abstract": [
        {
          "text": "Select a suitable iterative method to solve a system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-methods",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Iterative Methods",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-iterative-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-matrix-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense matrix using iterative methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-matrix-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Iterative Solving Functions (Matrix RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-iterative-solving-functions-matrix-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-vector-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense vector using iterative methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-vector-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Iterative Solving Functions (Vector RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-iterative-solving-functions-vector-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Solving-systems-with-iterative-sparse-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-iterative-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-matrix-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-solving-functions-vector-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-iterative-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/preconditioners"
      ],
      "title": "Solving systems with iterative sparse methods"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sparse-Iterate-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-c54n",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:)-1el7r"
      ],
      "title": "Sparse Iterate Functions"
    },
    {
      "anchor": "Sparse-Iterate-Functions-with-Preconditioner",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-99ji7",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseIterate(_:_:_:_:_:_:_:_:_:)-1anay"
      ],
      "title": "Sparse Iterate Functions with Preconditioner"
    },
    {
      "anchor": "Functions-that-Calculate-Iterate-State-Size",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Double(_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetStateSize_Float(_:_:_:_:_:)"
      ],
      "title": "Functions that Calculate Iterate State Size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:_:)-99ji7/title",
          "value": "SparseIterate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:_:)-99ji7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetStateSize_Double(_:_:_:_:_:)/title",
          "value": "SparseGetStateSize_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetStateSize_Double(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetStateSize_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetStateSize_Float(_:_:_:_:_:)/title",
          "value": "SparseGetStateSize_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetStateSize_Float(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetStateSize_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:)-c54n/title",
          "value": "SparseIterate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:)-c54n/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:_:)-1anay/title",
          "value": "SparseIterate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:_:)-1anay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:)-1el7r/title",
          "value": "SparseIterate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterate(_:_:_:_:_:_:_:_:)-1el7r/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
