{
  "abstract": [
    {
      "text": "Solves the equation ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "AX = B",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " for matrices of double-precision values using the specified iterative method and preconditioner type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5d7vf"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SparseSolve#$@SA@SparseIterativeMethod#$@SA@SparseMatrix_Double#$@SA@DenseMatrix_Double#S2_#$@EA@SparsePreconditioner_t#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseSolve"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseIterativeMethod",
        "text": "SparseIterativeMethod"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseMatrix_Double",
        "text": "SparseMatrix_Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@DenseMatrix_Double",
        "text": "DenseMatrix_Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@DenseMatrix_Double",
        "text": "DenseMatrix_Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
        "text": "SparsePreconditioner_t"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
        "text": "SparseIterativeStatus_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseSolve"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SparseSolve(_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseSolve"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "method"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseIterativeMethod",
              "text": "SparseIterativeMethod"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "A"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseMatrix_Double",
              "text": "SparseMatrix_Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "B"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@DenseMatrix_Double",
              "text": "DenseMatrix_Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "X"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@DenseMatrix_Double",
              "text": "DenseMatrix_Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Preconditioner"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
              "text": "SparsePreconditioner_t"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
              "text": "SparseIterativeStatus_t"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The iterative method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "method"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "A",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "A"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "B",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "B"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "X",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "X"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preconditioner to apply.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Preconditioner"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration that represents the status of the iterative solve.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to solve a system of linear equations using a factored coefficient matrix. Preconditioning the coefficient matrix can reduce the number of iterations the function requires to converge the system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows two systems of equations where the coefficient matrix is sparse:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3703917",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code solves this system by applying a diagonal scaling preconditioner and using the least squares minimum residual method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Create the coefficient matrix _A_.",
            "let rowIndices: [Int32] =    [ 0,  1, 1,  2]",
            "let columnIndices: [Int32] = [ 2,  0, 2,  1]",
            "let aValues: [Double] =      [10, 20, 5, 50]",
            "",
            "let A = SparseConvertFromCoordinate(3, 3,",
            "                                    4, 1,",
            "                                    SparseAttributes_t(),",
            "                                    rowIndices, columnIndices,",
            "                                    aValues)",
            "",
            "defer {",
            "    SparseCleanup(A)",
            "}",
            "",
            "/// Create the right-hand-side matrix, _B_.",
            "var bValues: [Double] = [30, 35, 100,",
            "                         300, 350, 1000]",
            "let n = bValues.count",
            "",
            "let xValues = [Double](unsafeUninitializedCapacity: n) {",
            "    buffer, count in",
            "    bValues.withUnsafeMutableBufferPointer { bPtr in",
            "        let B = DenseMatrix_Double(rowCount: 3,",
            "                                   columnCount: 2,",
            "                                   columnStride: 3,",
            "                                   attributes: SparseAttributes_t(),",
            "                                   data: bPtr.baseAddress!)",
            "        ",
            "        let X = DenseMatrix_Double(rowCount: 3,",
            "                                   columnCount: 2,",
            "                                   columnStride: 3,",
            "                                   attributes: SparseAttributes_t(),",
            "                                   data: buffer.baseAddress!)",
            "        ",
            "        SparseSolve(SparseLSMR(),",
            "                    A, B, X,",
            "                    SparsePreconditionerDiagScaling)",
            "        count = n",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, x",
              "type": "text"
            },
            {
              "code": "Values",
              "type": "codeVoice"
            },
            {
              "text": " contains the values ",
              "type": "text"
            },
            {
              "code": "[1.0, 2.0, 3.0, 10.0, 20.0, 30.0]",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double": {
      "abstract": [
        {
          "text": "A structure that contains a dense matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DenseMatrix_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DenseMatrix_Double"
        }
      ],
      "role": "symbol",
      "title": "DenseMatrix_Double",
      "type": "topic",
      "url": "/documentation/accelerate/densematrix_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod": {
      "abstract": [
        {
          "text": "The base type for all iterative methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterativeMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterativeMethod"
        }
      ],
      "role": "symbol",
      "title": "SparseIterativeMethod",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterativemethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t": {
      "abstract": [
        {
          "text": "Constants that define the status of the iterative solve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "role": "symbol",
      "title": "SparseIterativeStatus_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparseiterativestatus_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double": {
      "abstract": [
        {
          "text": "A structure that contains a sparse matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseMatrix_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseMatrix_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseMatrix_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparsematrix_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t": {
      "abstract": [
        {
          "text": "Constants that define the preconditioner type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparsePreconditioner_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparsePreconditioner_t"
        }
      ],
      "role": "symbol",
      "title": "SparsePreconditioner_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsepreconditioner_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5d7vf": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of double-precision values using the specified iterative method and preconditioner type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
          "text": "SparsePreconditioner_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5d7vf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-5d7vf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5yh8m": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of double-precision values using the specified iterative method and opaque preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
          "text": "SparseOpaquePreconditioner_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5yh8m",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-5yh8m"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7apig": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of single-precision values using the specified iterative method and preconditioner type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
          "text": "SparsePreconditioner_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7apig",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-7apig"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7vrh0": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of single-precision values using the specified iterative method and opaque preconditioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Float",
          "text": "SparseOpaquePreconditioner_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7vrh0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-7vrh0"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-80ri4": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of single-precision values, treating ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " as an operator and using the specified iterative method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Float",
          "text": "DenseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Float",
          "text": "SparseOpaquePreconditioner_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-80ri4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-80ri4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-8nfbc": {
      "abstract": [
        {
          "text": "Solves the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AX = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for matrices of double-precision values, treating ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " as an operator and using the specified iterative method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSolve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseIterativeMethod",
          "text": "SparseIterativeMethod"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@DenseMatrix_Double",
          "text": "DenseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaquePreconditioner_Double",
          "text": "SparseOpaquePreconditioner_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
          "text": "SparseIterativeStatus_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-8nfbc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSolve"
        }
      ],
      "role": "symbol",
      "title": "SparseSolve(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-8nfbc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3703917": {
      "alt": "A mathematical equation that has two stacked sets of three simultaneous equations on the left. Each equation has three unknowns. The same sets of simultaneous equations appear on the right as a single matrix equation, A x equals B. The single matrix equation consists of a three-by-three matrix multiplied by a three-by-two matrix that equals a three-by-two matrix.",
      "identifier": "media-3703917",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/f418105a3665a60546bc23d6a8dd3f50/media-3703917@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Iterative-Sparse-Solve-Functions-with-Preconditioner",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5yh8m",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7vrh0",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7apig",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-8nfbc",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-80ri4"
      ],
      "title": "Iterative Sparse Solve Functions with Preconditioner"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Iterative-Sparse-Solve-Functions-with-Preconditioner",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-5yh8m",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7vrh0",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-7apig",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-8nfbc",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSolve(_:_:_:_:_:)-80ri4"
              ],
              "title": "Iterative Sparse Solve Functions with Preconditioner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@SparseIterativeStatus_t",
                    "text": "SparseIterativeStatus_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseSolve"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeMethod",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseIterativeMethod",
                    "text": "SparseIterativeMethod"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "method"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseMatrix_Double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseMatrix_Double",
                    "text": "SparseMatrix_Double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "A"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@DenseMatrix_Double",
                    "text": "DenseMatrix_Double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "B"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DenseMatrix_Double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@DenseMatrix_Double",
                    "text": "DenseMatrix_Double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "X"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparsePreconditioner_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@SparsePreconditioner_t",
                    "text": "SparsePreconditioner_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "Preconditioner"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The iterative method.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "method"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "A",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "A"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "B",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "B"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "X",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "X"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The preconditioner to apply.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "Preconditioner"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseIterativeStatus_t",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " enumeration that represents the status of the iterative solve.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-5yh8m/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-5yh8m/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-5d7vf/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-5d7vf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/title",
          "value": "SparseMatrix_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseMatrix_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-7apig/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-7apig/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/title",
          "value": "SparsePreconditioner_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparsePreconditioner_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparsePreconditioner_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparsePreconditioner_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/title",
          "value": "SparseIterativeMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-7vrh0/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-7vrh0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/title",
          "value": "DenseMatrix_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DenseMatrix_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DenseMatrix_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-80ri4/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-80ri4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-8nfbc/title",
          "value": "SparseSolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSolve(_:_:_:_:_:)-8nfbc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeStatus_t/title",
          "value": "SparseIterativeStatus_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeStatus_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeStatus_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseIterativeStatus_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseIterativeStatus_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-5d7vf"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsesolve(_:_:_:_:_:)-5d7vf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
