{
  "abstract": [
    {
      "text": "A ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "D",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " factor subfactor that’s valid for ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "LDLᵀ",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "code": " ",
      "type": "codeVoice"
    },
    {
      "text": "only.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@SparseSubfactor_t@SparseSubfactorD",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseSubfactorD"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SparseSubfactor_t",
        "text": "SparseSubfactor_t"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseSubfactorD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SparseSubfactorD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseSubfactorD"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SparseSubfactor_t",
              "text": "SparseSubfactor_t"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorD": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "D",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " factor subfactor that’s valid for ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "LDLᵀ",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "code": " ",
          "type": "codeVoice"
        },
        {
          "text": "only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorD"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorD",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactord"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorInvalid": {
      "abstract": [
        {
          "text": "An invalid subfactor that indicates the requested type is incompatible with the supplied factorization or the system has destroyed it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorInvalid"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorInvalid",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorinvalid"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorL": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "L",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " factor subfactor that’s valid for Cholesky and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "LDLᵀ",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorL"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorL",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorl"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorP": {
      "abstract": [
        {
          "text": "A permutation subfactor that’s valid for all factorization types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorP"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorP",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorPLPS": {
      "abstract": [
        {
          "text": "A half-solve subfactor that’s valid for Cholesky and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "LDLᵀ",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorPLPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorPLPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorPLPS"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorPLPS",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorplps"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorQ": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Q",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " factor subfactor that’s valid for QR only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorQ"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorQ",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorq"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorR": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "R",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " factor subfactor that’s valid for QR and Cholesky ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AᵀA",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorR"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorR",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorRP": {
      "abstract": [
        {
          "text": "A half-solve subfactor that’s valid for QR and Cholesky ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "AᵀA",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorRP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorRP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorRP"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorRP",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactorrp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorS": {
      "abstract": [
        {
          "text": "A diagonal scaling subfactor that’s valid for Cholesky and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "LDLᵀ",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactorS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactorS"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactorS",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t": {
      "abstract": [
        {
          "text": "Constants that define the subfactor of a factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactor_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactor_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorInvalid",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorP",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorS",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorL",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorPLPS",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorQ",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorR",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorRP"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseSubfactorD"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorInvalid",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorP",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorS",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorL",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorPLPS",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorQ",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorR",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactorRP"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SparseSubfactorD"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorR/title",
          "value": "SparseSubfactorR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/title",
          "value": "SparseSubfactor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorPLPS/title",
          "value": "SparseSubfactorPLPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorPLPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorPLPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorS/title",
          "value": "SparseSubfactorS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorQ/title",
          "value": "SparseSubfactorQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorP/title",
          "value": "SparseSubfactorP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorInvalid/title",
          "value": "SparseSubfactorInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorD/title",
          "value": "SparseSubfactorD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorL/title",
          "value": "SparseSubfactorL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorRP/title",
          "value": "SparseSubfactorRP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactorRP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactorRP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparsesubfactord"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparsesubfactord"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
