{
  "abstract": [
    {
      "text": "Create and work with sparse vector structures.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/blas-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse-vector-utility-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sparse Vector Utility Operations"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blas-library": {
      "abstract": [
        {
          "text": "Perform common linear algebra operations with Apple’s implementation of the Basic Linear Algebra Subprograms (BLAS).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blas-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "BLAS",
      "type": "topic",
      "url": "/documentation/accelerate/blas-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations": {
      "abstract": [
        {
          "text": "Create, insert values into, and extract values from a blockwise sparse matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Blockwise Matrix Operations",
      "type": "topic",
      "url": "/documentation/accelerate/blockwise-matrix-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/general-sparse-matrix-management-operations": {
      "abstract": [
        {
          "text": "Manage and work with the properties of a sparse matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/general-sparse-matrix-management-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Sparse Matrix Management Operations",
      "type": "topic",
      "url": "/documentation/accelerate/general-sparse-matrix-management-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations": {
      "abstract": [
        {
          "text": "Perform computations with matrices and vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matrix and Vector Operations",
      "type": "topic",
      "url": "/documentation/accelerate/matrix-and-vector-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations": {
      "abstract": [
        {
          "text": "Create, insert values into, and extract values from a pointwise sparse matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pointwise Matrix Operations",
      "type": "topic",
      "url": "/documentation/accelerate/pointwise-matrix-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension": {
      "abstract": [
        {
          "text": "The dimension type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_dimension"
        }
      ],
      "role": "symbol",
      "title": "sparse_dimension",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_dimension"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in the double-precision dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_vector_nonzero_count_double(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in the single-precision dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_vector_nonzero_count_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_vector_nonzero_count_float(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_index": {
      "abstract": [
        {
          "text": "The index type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "role": "symbol",
      "title": "sparse_index",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_index"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Packs nonzero values from a double-precision dense vector to a destination array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_pack_vector_double(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Packs nonzero values from a single-precision dense vector to a destination array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_pack_vector_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_pack_vector_float(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride": {
      "abstract": [
        {
          "text": "The stride type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_stride"
        }
      ],
      "role": "symbol",
      "title": "sparse_stride",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Extracts elements from the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " into the corresponding location in the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both vectors containing double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_unpack_vector_double(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Extracts elements from the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " into the corresponding location in the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both vectors containing single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_unpack_vector_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_unpack_vector_float(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sparse-computation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-vector-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/pointwise-matrix-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/blockwise-matrix-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/general-sparse-matrix-management-operations"
      ],
      "title": "Sparse computation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sparse-Utility-Operations",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_double(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_vector_nonzero_count_float(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_double(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_pack_vector_float(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_double(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_unpack_vector_float(_:_:_:_:_:_:_:)"
      ],
      "title": "Sparse Utility Operations"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_dimension",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_stride"
      ],
      "title": "Supporting Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_double(_:_:_:_:_:_:)/title",
          "value": "sparse_pack_vector_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_double(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_pack_vector_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/title",
          "value": "sparse_dimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_dimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_dimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/title",
          "value": "sparse_stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_float(_:_:_:_:_:_:_:)/title",
          "value": "sparse_unpack_vector_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_float(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_float(_:_:_:_:_:_:)/title",
          "value": "sparse_pack_vector_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_pack_vector_float(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_pack_vector_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_double(_:_:_:_:_:_:_:)/title",
          "value": "sparse_unpack_vector_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_unpack_vector_double(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_unpack_vector_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_double(_:_:_:)/title",
          "value": "sparse_get_vector_nonzero_count_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_double(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_vector_nonzero_count_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/title",
          "value": "sparse_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_float(_:_:_:)/title",
          "value": "sparse_get_vector_nonzero_count_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_vector_nonzero_count_float(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_vector_nonzero_count_float"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
