{
  "abstract": [
    {
      "text": "Increases the reference count on a single-precision subfactor object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-6mr6d"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SparseRetain#$@SA@SparseOpaqueSubfactor_Float#",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SparseRetain"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
        "text": "SparseOpaqueSubfactor_Float"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
        "text": "SparseOpaqueSubfactor_Float"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SparseRetain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SparseRetain(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SparseRetain"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "Subfactor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
              "text": "SparseOpaqueSubfactor_Float"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
              "text": "SparseOpaqueSubfactor_Float"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The subfactor object to increase the reference count upon.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Subfactor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The supplied numeric subfactor object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueSubfactor_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesubfactor_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-2pmdl": {
      "abstract": [
        {
          "text": "Increases the reference count on a double-precision subfactor object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Double",
          "text": "SparseOpaqueSubfactor_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Double",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-2pmdl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRetain"
        }
      ],
      "role": "symbol",
      "title": "SparseRetain(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseretain(_:)-2pmdl"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-6mr6d": {
      "abstract": [
        {
          "text": "Increases the reference count on a single-precision subfactor object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
          "text": "SparseOpaqueSubfactor_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-6mr6d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRetain"
        }
      ],
      "role": "symbol",
      "title": "SparseRetain(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseretain(_:)-6mr6d"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-7onhr": {
      "abstract": [
        {
          "text": "Increases the reference count on a single-precision numeric factorization object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-7onhr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRetain"
        }
      ],
      "role": "symbol",
      "title": "SparseRetain(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseretain(_:)-7onhr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8943y": {
      "abstract": [
        {
          "text": "Increases the reference count on a double-precision numeric factorization object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8943y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRetain"
        }
      ],
      "role": "symbol",
      "title": "SparseRetain(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseretain(_:)-8943y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8r2dm": {
      "abstract": [
        {
          "text": "Increases the reference count on a symbolic factorization object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8r2dm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseRetain"
        }
      ],
      "role": "symbol",
      "title": "SparseRetain(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparseretain(_:)-8r2dm"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resource-Retention",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8r2dm",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8943y",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-7onhr",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-2pmdl"
      ],
      "title": "Resource Retention"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resource-Retention",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8r2dm",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-8943y",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-7onhr",
                "doc://com.apple.accelerate/documentation/Accelerate/SparseRetain(_:)-2pmdl"
              ],
              "title": "Resource Retention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
                    "text": "SparseOpaqueSubfactor_Float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SparseRetain"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
                    "text": "SparseOpaqueSubfactor_Float"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "NumericFactor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The subfactor object to increase the reference count upon.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "NumericFactor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The supplied numeric subfactor object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-8r2dm/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-8r2dm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-6mr6d/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-6mr6d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-8943y/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-8943y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-7onhr/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-7onhr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/title",
          "value": "SparseOpaqueSubfactor_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-2pmdl/title",
          "value": "SparseRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseRetain(_:)-2pmdl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseRetain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparseretain(_:)-6mr6d"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparseretain(_:)-6mr6d"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
