{
  "abstract": [
    {
      "text": "Calculate the symbolic factorization of a matrix, and solve systems using precalculated symbolic factorizations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sparse Symbolic Factorization Functions"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-1p6im": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of single-precision values that corresponds to the supplied symbolic factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-1p6im",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:)-1p6im"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-3697o": {
      "abstract": [
        {
          "text": "Returns a symbolic factorization of the requested type for a specified sparsity structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseFactorization_t",
          "text": "SparseFactorization_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrixStructure",
          "text": "SparseMatrixStructure"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-3697o",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:)-3697o"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-58oq8": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of double-precision values that corresponds to the supplied symbolic factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-58oq8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:)-58oq8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-3ddg": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of double-precision values that corresponds to the supplied symbolic factorization using specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseNumericFactorOptions",
          "text": "SparseNumericFactorOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-3ddg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:_:)-3ddg"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-45gsz": {
      "abstract": [
        {
          "text": "Returns a symbolic factorization of the requested type for a single-precision matrix with the specified structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseFactorization_t",
          "text": "SparseFactorization_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrixStructure",
          "text": "SparseMatrixStructure"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseSymbolicFactorOptions",
          "text": "SparseSymbolicFactorOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-45gsz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:_:)-45gsz"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-797fl": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of single-precision values that corresponds to the supplied symbolic factorization using specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseNumericFactorOptions",
          "text": "SparseNumericFactorOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-797fl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:_:)-797fl"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-68hki": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of double-precision values that corresponds to the supplied symbolic factorization using user-defined workspace and factor storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseNumericFactorOptions",
          "text": "SparseNumericFactorOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-68hki",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:_:_:_:)-68hki"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-8afz": {
      "abstract": [
        {
          "text": "Returns the factorization of a sparse matrix of single-precision values that corresponds to the supplied symbolic factorization using user-defined workspace and factor storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSymbolicFactorization",
          "text": "SparseOpaqueSymbolicFactorization"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseNumericFactorOptions",
          "text": "SparseNumericFactorOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-8afz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactor"
        }
      ],
      "role": "symbol",
      "title": "SparseFactor(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactor(_:_:_:_:_:)-8afz"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t": {
      "abstract": [
        {
          "text": "Constants that define the factorization type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseFactorization_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseFactorization_t"
        }
      ],
      "role": "symbol",
      "title": "SparseFactorization_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsefactorization_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization": {
      "abstract": [
        {
          "text": "A semi-opaque type that represents symbolic matrix factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueSymbolicFactorization"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueSymbolicFactorization",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesymbolicfactorization"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions": {
      "abstract": [
        {
          "text": "A structure that contains options that affect the symbolic stage of a sparse factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSymbolicFactorOptions"
        }
      ],
      "role": "symbol",
      "title": "SparseSymbolicFactorOptions",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesymbolicfactoroptions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods": {
      "abstract": [
        {
          "text": "Use direct methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using direct methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-direct-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense matrix using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Matrix RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-matrix-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense vector using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Vector RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-vector-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions": {
      "abstract": [
        {
          "text": "Compute the factorization of a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix Factor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-factor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions": {
      "abstract": [
        {
          "text": "Recompute a factorization using the numerical data from a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Refactor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-refactor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions": {
      "abstract": [
        {
          "text": "Extract and work with subfactors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subfactor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/subfactor-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Solving-systems-with-direct-sparse-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions"
      ],
      "title": "Solving systems with direct sparse methods"
    }
  ],
  "topicSections": [
    {
      "anchor": "Matrix-Symbolic-Factorization-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-3697o",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-45gsz"
      ],
      "title": "Matrix Symbolic Factorization Functions"
    },
    {
      "anchor": "Matrix-Factorizations-Using-Precalculated-Symbolic-Factorization",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-58oq8",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:)-1p6im",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-3ddg",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:)-797fl"
      ],
      "title": "Matrix Factorizations Using Precalculated Symbolic Factorization"
    },
    {
      "anchor": "Matrix-Factorizations-Using-Precalculated-Symbolic-Factorization-with-User-Defined-Workspace",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-68hki",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactor(_:_:_:_:_:)-8afz"
      ],
      "title": "Matrix Factorizations Using Precalculated Symbolic Factorization with User-Defined Workspace"
    },
    {
      "anchor": "Supporting-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSymbolicFactorization",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseFactorization_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSymbolicFactorOptions"
      ],
      "title": "Supporting Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/title",
          "value": "SparseSymbolicFactorOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSymbolicFactorOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSymbolicFactorOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-797fl/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-797fl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/title",
          "value": "SparseOpaqueFactorization_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-45gsz/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-45gsz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-3ddg/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:)-3ddg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:_:_:)-8afz/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:_:_:)-8afz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:_:_:)-68hki/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:_:_:_:)-68hki/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-58oq8/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-58oq8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/title",
          "value": "SparseOpaqueFactorization_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/title",
          "value": "SparseFactorization_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactorization_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactorization_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactorization_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-3697o/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-3697o/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-1p6im/title",
          "value": "SparseFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseFactor(_:_:)-1p6im/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSymbolicFactorization/title",
          "value": "SparseOpaqueSymbolicFactorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSymbolicFactorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSymbolicFactorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSymbolicFactorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSymbolicFactorization"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
