{
  "abstract": [
    {
      "text": "Operation was a success.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@sparse_status@SPARSE_SUCCESS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SPARSE_SUCCESS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@sparse_status",
        "text": "sparse_status"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SPARSE_SUCCESS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SPARSE_SUCCESS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SPARSE_SUCCESS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_status",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@sparse_status",
              "text": "sparse_status"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_CANNOT_SET_PROPERTY": {
      "abstract": [
        {
          "text": "A property was set after values were inserted into the matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_CANNOT_SET_PROPERTY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_CANNOT_SET_PROPERTY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_CANNOT_SET_PROPERTY"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_CANNOT_SET_PROPERTY",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_cannot_set_property"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_ILLEGAL_PARAMETER": {
      "abstract": [
        {
          "text": "Operation was not completed because one or more of the arguments had an illegal value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_ILLEGAL_PARAMETER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_ILLEGAL_PARAMETER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_ILLEGAL_PARAMETER"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_ILLEGAL_PARAMETER",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_illegal_parameter"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS": {
      "abstract": [
        {
          "text": "Operation was a success.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_SUCCESS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_SUCCESS",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_success"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SYSTEM_ERROR": {
      "abstract": [
        {
          "text": "An internal error has occured, such as non enough memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_SYSTEM_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SYSTEM_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_SYSTEM_ERROR"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_SYSTEM_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_system_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_status": {
      "abstract": [
        {
          "text": "The type reflecting the status of an operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_status"
        }
      ],
      "role": "symbol",
      "title": "sparse_status",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_status"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_ILLEGAL_PARAMETER",
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_CANNOT_SET_PROPERTY",
        "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SYSTEM_ERROR"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SPARSE_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_status"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_ILLEGAL_PARAMETER",
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_CANNOT_SET_PROPERTY",
                "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SYSTEM_ERROR"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SPARSE_SUCCESS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_CANNOT_SET_PROPERTY/title",
          "value": "SPARSE_CANNOT_SET_PROPERTY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_CANNOT_SET_PROPERTY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_CANNOT_SET_PROPERTY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_ILLEGAL_PARAMETER/title",
          "value": "SPARSE_ILLEGAL_PARAMETER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_ILLEGAL_PARAMETER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_ILLEGAL_PARAMETER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SYSTEM_ERROR/title",
          "value": "SPARSE_SYSTEM_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SYSTEM_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_SYSTEM_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SUCCESS/title",
          "value": "SPARSE_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/title",
          "value": "sparse_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_status"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_success"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_success"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
