{
  "abstract": [
    {
      "text": "Returns the number of nonzero values of a matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@sparse_get_matrix_nonzero_count",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sparse_get_matrix_nonzero_count"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sparse_get_matrix_nonzero_count"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "sparse_get_matrix_nonzero_count(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "A"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sparse matrix object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "A"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The number of nonzero values in the matrix.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple provides the BLAS and LAPACK libraries under the Accelerate framework to be in line with LAPACK 3.9.1. Starting with iOS 19, iPadOS 19, macOS 16, tvOS 19, watchOS 19, and visionOS 3, the libraries are in line with LAPACK 3.12.0. These new interfaces provide additional functionality, as well as a new ILP64 interface. To use the new interfaces, define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK",
                  "type": "codeVoice"
                },
                {
                  "text": " before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64",
                  "type": "codeVoice"
                },
                {
                  "text": ". For Swift projects, specify ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK=1",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64=1",
                  "type": "codeVoice"
                },
                {
                  "text": " as preprocessor macros in Xcode build settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)": {
      "abstract": [
        {
          "text": "Puts values that you recently added to the matrix into the internal sparse storage format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_commit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_commit"
        }
      ],
      "role": "symbol",
      "title": "sparse_commit(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_commit(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in a column of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_column"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_column"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count_for_column(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of nonzero values in a row of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_row"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_nonzero_count_for_row"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_nonzero_count_for_row(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)": {
      "abstract": [
        {
          "text": "Returns the number of columns of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_columns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_columns"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_number_of_columns(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_number_of_columns(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)": {
      "abstract": [
        {
          "text": "Returns the number of rows of a matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_rows"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_number_of_rows"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_number_of_rows(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_number_of_rows(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value of the given property name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_get_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_get_matrix_property(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_get_matrix_property(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)": {
      "abstract": [
        {
          "text": "Releases any memory associated with the matrix object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_destroy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_destroy"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_destroy(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_destroy(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)": {
      "abstract": [
        {
          "text": "Sets the given property for a matrix object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_set_matrix_property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_matrix_property",
          "text": "sparse_matrix_property"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_set_matrix_property"
        }
      ],
      "role": "symbol",
      "title": "sparse_set_matrix_property(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_set_matrix_property(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-Sparse-Matrix-Management-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)"
      ],
      "title": "General Sparse Matrix Management Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sparse_get_matrix_nonzero_count"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-Sparse-Matrix-Management-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_commit(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_destroy(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_set_matrix_property(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_property(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_rows(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_number_of_columns(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_row(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_get_matrix_nonzero_count_for_column(_:_:)"
              ],
              "title": "General Sparse Matrix Management Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:L",
                    "text": "long"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparse_get_matrix_nonzero_count"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "A"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sparse matrix object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "A"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The number of nonzero values in the matrix.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_row(_:_:)/title",
          "value": "sparse_get_matrix_nonzero_count_for_row"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_row(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count_for_row"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_commit(_:)/title",
          "value": "sparse_commit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_commit(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_commit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_property(_:_:)/title",
          "value": "sparse_get_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_property(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count(_:)/title",
          "value": "sparse_get_matrix_nonzero_count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_column(_:_:)/title",
          "value": "sparse_get_matrix_nonzero_count_for_column"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_nonzero_count_for_column(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_nonzero_count_for_column"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_destroy(_:)/title",
          "value": "sparse_matrix_destroy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_destroy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_destroy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_rows(_:)/title",
          "value": "sparse_get_matrix_number_of_rows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_rows(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_number_of_rows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_set_matrix_property(_:_:)/title",
          "value": "sparse_set_matrix_property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_set_matrix_property(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_set_matrix_property"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_columns(_:)/title",
          "value": "sparse_get_matrix_number_of_columns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_get_matrix_number_of_columns(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_get_matrix_number_of_columns"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_get_matrix_nonzero_count(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_get_matrix_nonzero_count(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
