{
  "abstract": [
    {
      "text": "Permutes the columns of the double-precision sparse matrix ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "A",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " based on the provided permutation array.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_double(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@sparse_permute_cols_double",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sparse_permute_cols_double"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_matrix_double",
        "text": "sparse_matrix_double"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@sparse_index",
        "text": "sparse_index"
      },
      {
        "kind": "text",
        "text": ">!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@sparse_status",
        "text": "sparse_status"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sparse_permute_cols_double"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "sparse_permute_cols_double(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sparse_permute_cols_double"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "A"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_double",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_matrix_double",
              "text": "sparse_matrix_double"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "perm"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@sparse_index",
              "text": "sparse_index"
            },
            {
              "kind": "text",
              "text": ">!) -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_status",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@sparse_status",
              "text": "sparse_status"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The sparse matrix, ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "A",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "A"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The permutation array. Holds number of columns in ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "A",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " values indicating the permutation of the matrix. The indices in ",
                  "type": "text"
                },
                {
                  "code": "perm",
                  "type": "codeVoice"
                },
                {
                  "text": " are expected to be 0 based (first element of pointer is ",
                  "type": "text"
                },
                {
                  "code": "ptr[0]",
                  "type": "codeVoice"
                },
                {
                  "text": ").  The indices in ",
                  "type": "text"
                },
                {
                  "code": "perm",
                  "type": "codeVoice"
                },
                {
                  "text": " are expected to be within bounds of the matrix. Undefined behavior if not met.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "perm"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On successful return, ",
              "type": "text"
            },
            {
              "code": "A",
              "type": "codeVoice"
            },
            {
              "text": " has been permuted and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is returned.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Permute the columns of the sparse matrix ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " based on the provided permutation array. For each column in ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", swap columns as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " tmp[:] = A[:,j];",
            " A[:,j] = A[:,perm[j]];",
            " A[:,perm[j]] = tmp[:];"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Apple provides the BLAS and LAPACK libraries under the Accelerate framework to be in line with LAPACK 3.9.1. Starting with iOS 19, iPadOS 19, macOS 16, tvOS 19, watchOS 19, and visionOS 3, the libraries are in line with LAPACK 3.12.0. These new interfaces provide additional functionality, as well as a new ILP64 interface. To use the new interfaces, define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK",
                  "type": "codeVoice"
                },
                {
                  "text": " before including the Accelerate or vecLib headers. For ILP64 interfaces, also define ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64",
                  "type": "codeVoice"
                },
                {
                  "text": ". For Swift projects, specify ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_NEW_LAPACK=1",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "ACCELERATE_LAPACK_ILP64=1",
                  "type": "codeVoice"
                },
                {
                  "text": " as preprocessor macros in Xcode build settings.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS": {
      "abstract": [
        {
          "text": "Operation was a success.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SPARSE_SUCCESS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SPARSE_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "SPARSE_SUCCESS",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_success"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_double(_:_:)": {
      "abstract": [
        {
          "text": "Computes the specified element-wise norm of the double-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_elementwise_norm_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_norm",
          "text": "sparse_norm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_elementwise_norm_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_elementwise_norm_double(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_elementwise_norm_double(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_float(_:_:)": {
      "abstract": [
        {
          "text": "Computes the specified element-wise norm of the single-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_elementwise_norm_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_norm",
          "text": "sparse_norm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_float(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_elementwise_norm_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_elementwise_norm_float(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_elementwise_norm_float(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_index": {
      "abstract": [
        {
          "text": "The index type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_index"
        }
      ],
      "role": "symbol",
      "title": "sparse_index",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_index"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_double": {
      "abstract": [
        {
          "text": "Sparse matrix opaque type for double.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_double",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_double(_:_:)": {
      "abstract": [
        {
          "text": "Computes the sum along the specified diagonal of the double-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_trace_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_trace_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_trace_double(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_trace_double(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_float(_:_:)": {
      "abstract": [
        {
          "text": "Computes the sum along the specified diagonal of the single-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_trace_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_float(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_trace_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_trace_float(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_trace_float(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " by the sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " and adds the result to the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with all operands containing double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_vector_product_dense_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_vector_product_dense_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Multiplies the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " by the sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " and adds the result to the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with all operands containing single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_matrix_vector_product_dense_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_matrix_vector_product_dense_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_double(_:_:)": {
      "abstract": [
        {
          "text": "Computes the specified operator norm of the double-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_operator_norm_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_norm",
          "text": "sparse_norm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_operator_norm_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_operator_norm_double(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_operator_norm_double(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_float(_:_:)": {
      "abstract": [
        {
          "text": "Computes the specified operator norm of the single-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_operator_norm_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_norm",
          "text": "sparse_norm"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_float(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_operator_norm_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_operator_norm_float(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_operator_norm_float(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Computes the outer product of the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " and the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both operands containing double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_outer_product_dense_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_outer_product_dense_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Computes the outer product of the dense vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " and the sparse vector ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "y",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", with both operands containing single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_outer_product_dense_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_dimension",
          "text": "sparse_dimension"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_outer_product_dense_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_double(_:_:)": {
      "abstract": [
        {
          "text": "Permutes the columns of the double-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " based on the provided permutation array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_permute_cols_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_permute_cols_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_permute_cols_double(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_permute_cols_double(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_float(_:_:)": {
      "abstract": [
        {
          "text": "Permutes the columns of the single-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " based on the provided permutation array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_permute_cols_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_float(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_permute_cols_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_permute_cols_float(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_permute_cols_float(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_double(_:_:)": {
      "abstract": [
        {
          "text": "Permutes the rows of the double-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " based on the provided permutation array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_permute_rows_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_double(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_permute_rows_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_permute_rows_double(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_permute_rows_double(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_float(_:_:)": {
      "abstract": [
        {
          "text": "Permutes the rows of the single-precision sparse matrix ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "A",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " based on the provided permutation array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_permute_rows_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_index",
          "text": "sparse_index"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_float(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_permute_rows_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_permute_rows_float(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_permute_rows_float(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_status": {
      "abstract": [
        {
          "text": "The type reflecting the status of an operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_status"
        }
      ],
      "role": "symbol",
      "title": "sparse_status",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_status"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Solves the system of equations ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x = alpha * T * x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for x where ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is a dense vector and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "T",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is a triangular sparse matrix, with all operands containing double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_vector_triangular_solve_dense_double"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_double",
          "text": "sparse_matrix_double"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_vector_triangular_solve_dense_double"
        }
      ],
      "role": "symbol",
      "title": "sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Solves the system of equations ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x = alpha * T * x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " for x where ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "x",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is a dense vector and ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "T",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " is a triangular sparse matrix, with all operands containing single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparse_vector_triangular_solve_dense_float"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CBLAS_TRANSPOSE",
          "text": "CBLAS_TRANSPOSE"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_matrix_float",
          "text": "sparse_matrix_float"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@sparse_stride",
          "text": "sparse_stride"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@sparse_status",
          "text": "sparse_status"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sparse_vector_triangular_solve_dense_float"
        }
      ],
      "role": "symbol",
      "title": "sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matrix-Vector-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_double(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_float(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_float(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_double(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_float(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_double(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_float(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_double(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_float(_:_:)"
      ],
      "title": "Matrix-Vector Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sparse_permute_cols_double"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_permute_cols_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matrix-Vector-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_double(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_rows_float(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_permute_cols_float(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_double(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_elementwise_norm_float(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_double(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_operator_norm_float(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_double(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_trace_float(_:_:)"
              ],
              "title": "Matrix-Vector Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_status",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@EA@sparse_status",
                    "text": "sparse_status"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sparse_permute_cols_double"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_matrix_double",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_matrix_double",
                    "text": "sparse_matrix_double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "A"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse_index",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@sparse_index",
                    "text": "sparse_index"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "restrict"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "perm"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The sparse matrix, ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "A",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "A"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The permutation array. Holds number of columns in ",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "A",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "text": " values indicating the permutation of the matrix. The indices in ",
                        "type": "text"
                      },
                      {
                        "code": "perm",
                        "type": "codeVoice"
                      },
                      {
                        "text": " are expected to be 0 based (first element of pointer is ",
                        "type": "text"
                      },
                      {
                        "code": "ptr[0]",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").  The indices in ",
                        "type": "text"
                      },
                      {
                        "code": "perm",
                        "type": "codeVoice"
                      },
                      {
                        "text": " are expected to be within bounds of the matrix. Undefined behavior if not met.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "perm"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "On successful return, ",
                    "type": "text"
                  },
                  {
                    "code": "A",
                    "type": "codeVoice"
                  },
                  {
                    "text": " has been permuted and ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SPARSE_SUCCESS",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " is returned.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_cols_double(_:_:)/title",
          "value": "sparse_permute_cols_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_cols_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_permute_cols_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_operator_norm_double(_:_:)/title",
          "value": "sparse_operator_norm_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_operator_norm_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_operator_norm_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)/title",
          "value": "sparse_outer_product_dense_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_outer_product_dense_double(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_outer_product_dense_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_cols_float(_:_:)/title",
          "value": "sparse_permute_cols_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_cols_float(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_permute_cols_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_elementwise_norm_float(_:_:)/title",
          "value": "sparse_elementwise_norm_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_elementwise_norm_float(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_elementwise_norm_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)/title",
          "value": "sparse_vector_triangular_solve_dense_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_vector_triangular_solve_dense_float(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_vector_triangular_solve_dense_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_trace_float(_:_:)/title",
          "value": "sparse_matrix_trace_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_trace_float(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_trace_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/title",
          "value": "sparse_index"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_index/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_index"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SUCCESS/title",
          "value": "SPARSE_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SPARSE_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SPARSE_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_operator_norm_float(_:_:)/title",
          "value": "sparse_operator_norm_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_operator_norm_float(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_operator_norm_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_trace_double(_:_:)/title",
          "value": "sparse_matrix_trace_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_trace_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_trace_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)/title",
          "value": "sparse_matrix_vector_product_dense_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_vector_product_dense_float(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_vector_product_dense_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/title",
          "value": "sparse_status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_status/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_rows_float(_:_:)/title",
          "value": "sparse_permute_rows_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_rows_float(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_permute_rows_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)/title",
          "value": "sparse_vector_triangular_solve_dense_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_vector_triangular_solve_dense_double(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_vector_triangular_solve_dense_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_rows_double(_:_:)/title",
          "value": "sparse_permute_rows_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_permute_rows_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_permute_rows_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_double/title",
          "value": "sparse_matrix_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)/title",
          "value": "sparse_outer_product_dense_float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_outer_product_dense_float(_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_outer_product_dense_float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)/title",
          "value": "sparse_matrix_vector_product_dense_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_matrix_vector_product_dense_double(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_matrix_vector_product_dense_double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_elementwise_norm_double(_:_:)/title",
          "value": "sparse_elementwise_norm_double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1sparse_elementwise_norm_double(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sparse_elementwise_norm_double"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/sparse_permute_cols_double(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/sparse_permute_cols_double(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
