{
  "abstract": [
    {
      "text": "Extract and work with subfactors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/subfactor-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Subfactor Functions"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-49d8w": {
      "abstract": [
        {
          "text": "Returns an opaque object that represents a subfactor of a factorization of a matrix of double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCreateSubfactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Double",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-49d8w",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCreateSubfactor"
        }
      ],
      "role": "symbol",
      "title": "SparseCreateSubfactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecreatesubfactor(_:_:)-49d8w"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-4renf": {
      "abstract": [
        {
          "text": "Returns an opaque object that represents a subfactor of a factorization of a matrix of single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseCreateSubfactor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SparseSubfactor_t",
          "text": "SparseSubfactor_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-4renf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseCreateSubfactor"
        }
      ],
      "role": "symbol",
      "title": "SparseCreateSubfactor(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsecreatesubfactor(_:_:)-4renf"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float": {
      "abstract": [
        {
          "text": "A structure that represents the factorization of a matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueFactorization_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquefactorization_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueSubfactor_Double",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesubfactor_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "role": "symbol",
      "title": "SparseOpaqueSubfactor_Float",
      "type": "topic",
      "url": "/documentation/accelerate/sparseopaquesubfactor_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t": {
      "abstract": [
        {
          "text": "Constants that define the subfactor of a factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseSubfactor_t"
        }
      ],
      "role": "symbol",
      "title": "SparseSubfactor_t",
      "type": "topic",
      "url": "/documentation/accelerate/sparsesubfactor_t"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods": {
      "abstract": [
        {
          "text": "Use direct methods to solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
      "kind": "article",
      "role": "article",
      "title": "Solving systems using direct methods",
      "type": "topic",
      "url": "/documentation/accelerate/solving-systems-using-direct-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense matrix using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Matrix RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-matrix-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs": {
      "abstract": [
        {
          "text": "Solve a system with a right-hand-side dense vector using a factored sparse coefficient matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Direct Solving Functions (Vector RHS)",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-direct-solving-functions-vector-rhs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions": {
      "abstract": [
        {
          "text": "Compute the factorization of a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix Factor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-factor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions": {
      "abstract": [
        {
          "text": "Recompute a factorization using the numerical data from a matrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Refactor Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-refactor-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions": {
      "abstract": [
        {
          "text": "Calculate the symbolic factorization of a matrix, and solve systems using precalculated symbolic factorizations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Symbolic Factorization Functions",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-symbolic-factorization-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/subfactor-multiplication-functions": {
      "abstract": [
        {
          "text": "Multiply subfactors by matrices and vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/subfactor-multiplication-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subfactor Multiplication Functions",
      "type": "topic",
      "url": "/documentation/accelerate/subfactor-multiplication-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/subfactor-solve-functions": {
      "abstract": [
        {
          "text": "Solve systems with the equation ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Subfactor * X = B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/subfactor-solve-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subfactor Solve Functions",
      "type": "topic",
      "url": "/documentation/accelerate/subfactor-solve-functions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Solving-systems-with-direct-sparse-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/solving-systems-using-direct-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-factor-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-matrix-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-direct-solving-functions-vector-rhs",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-symbolic-factorization-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-refactor-functions"
      ],
      "title": "Solving systems with direct sparse methods"
    }
  ],
  "topicSections": [
    {
      "anchor": "Subfactor-Extraction",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseSubfactor_t",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-49d8w",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseCreateSubfactor(_:_:)-4renf",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueFactorization_Float"
      ],
      "title": "Subfactor Extraction"
    },
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Double",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseOpaqueSubfactor_Float"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Subfactor-Solve-and-Operation-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/subfactor-solve-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/subfactor-multiplication-functions"
      ],
      "title": "Subfactor Solve and Operation Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/title",
          "value": "SparseOpaqueFactorization_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/title",
          "value": "SparseOpaqueSubfactor_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/title",
          "value": "SparseOpaqueFactorization_Float"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueFactorization_Float/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueFactorization_Float"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreateSubfactor(_:_:)-49d8w/title",
          "value": "SparseCreateSubfactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreateSubfactor(_:_:)-49d8w/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCreateSubfactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/title",
          "value": "SparseSubfactor_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseSubfactor_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseSubfactor_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/title",
          "value": "SparseOpaqueSubfactor_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseOpaqueSubfactor_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseOpaqueSubfactor_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreateSubfactor(_:_:)-4renf/title",
          "value": "SparseCreateSubfactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseCreateSubfactor(_:_:)-4renf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseCreateSubfactor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
