{
  "abstract": [
    {
      "text": "Transpose matrices, factorizations, and subfactors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/transposition"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Transposition"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-227ei": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified matrix of double-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Double",
          "text": "SparseMatrix_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-227ei",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-227ei"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-48t76": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified single-precision factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Float",
          "text": "SparseOpaqueFactorization_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-48t76",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-48t76"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-7no8k": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified matrix of single-precision, floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseMatrix_Float",
          "text": "SparseMatrix_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-7no8k",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-7no8k"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-827va": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified single-precision subfactor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
          "text": "SparseOpaqueSubfactor_Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Float",
          "text": "SparseOpaqueSubfactor_Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-827va",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-827va"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-90lxy": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified double-precision factorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueFactorization_Double",
          "text": "SparseOpaqueFactorization_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-90lxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-90lxy"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-9r7s5": {
      "abstract": [
        {
          "text": "Returns a transposed copy of the specified double-precision subfactor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Double",
          "text": "SparseOpaqueSubfactor_Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SparseOpaqueSubfactor_Double",
          "text": "SparseOpaqueSubfactor_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-9r7s5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SparseGetTranspose"
        }
      ],
      "role": "symbol",
      "title": "SparseGetTranspose(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/sparsegettranspose(_:)-9r7s5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-matrix-multiplication": {
      "abstract": [
        {
          "text": "Multiply sparse and dense matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-matrix-multiplication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix and Dense Matrix Multiplication",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-and-dense-matrix-multiplication"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication": {
      "abstract": [
        {
          "text": "Multiply sparse matrices and dense vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Matrix and Dense Vector Multiplication",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-matrix-and-dense-vector-multiplication"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library": {
      "abstract": [
        {
          "text": "Solve systems of equations where the coefficient matrix is sparse.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sparse-solvers-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sparse Solvers",
      "type": "topic",
      "url": "/documentation/accelerate/sparse-solvers-library"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtrans": {
      "abstract": [
        {
          "text": "Transposes a single-precision matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mtrans"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtrans",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mtrans",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mtrans"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtransD": {
      "abstract": [
        {
          "text": "Transposes a double-precision matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mtransD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtransD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mtransD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mtransd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiplying-and-transposing-sparse-matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-matrix-multiplication",
        "doc://com.apple.accelerate/documentation/Accelerate/sparse-matrix-and-dense-vector-multiplication"
      ],
      "title": "Multiplying and transposing sparse matrices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Matrix-Transpose-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-227ei",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-7no8k",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtrans",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mtransD"
      ],
      "title": "Matrix Transpose Functions"
    },
    {
      "anchor": "Factorization-Transpose-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-90lxy",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-48t76"
      ],
      "title": "Factorization Transpose Functions"
    },
    {
      "anchor": "Subfactor-Transpose-Functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-9r7s5",
        "doc://com.apple.accelerate/documentation/Accelerate/SparseGetTranspose(_:)-827va"
      ],
      "title": "Subfactor Transpose Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-827va/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-827va/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-9r7s5/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-9r7s5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-227ei/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-227ei/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-90lxy/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-90lxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-48t76/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-48t76/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-7no8k/title",
          "value": "SparseGetTranspose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1SparseGetTranspose(_:)-7no8k/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SparseGetTranspose"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
