{
  "abstract": [
    {
      "text": "Perform basic arithmetic operations and common digital signal processing (DSP) routines on large vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vdsp-library"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "vDSP"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The vDSP library contains a collection of highly optimized functions for DSP, type conversion, and general purpose arithmetic on large collections. The library includes DSP operations such as convolution and correlation, Fourier transformation, and biquadratic filtering. For arithmetic on large collections, vDSP includes functions such as multiply-add and reduction functions including sum, mean, and maximum.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following sequence of images illustrates an example of the vDSP library’s capabilities. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_vtmerg",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function combines two waveforms to produce a vector to create a smooth transition between two signals.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4310314",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Unless otherwise mentioned, vDSP functions with the same input and output sizes (in bytes) work in-place.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The majority of vDSP operations are single-threaded and run on a single core. However, the following functions may be multithreaded depending on the size of the data they’re operating on:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmma",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmaD",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmms",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmsD",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmul",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmulD",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsm",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsmD",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1d-correlation-and-convolution": {
      "abstract": [
        {
          "text": "Use correlation to compare and convolution to combine vectors of real or complex data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1d-correlation-and-convolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "1D correlation and convolution",
      "type": "topic",
      "url": "/documentation/accelerate/1d-correlation-and-convolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/2d-convolution": {
      "abstract": [
        {
          "text": "Perform convolution operations on matrices of real data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/2d-convolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "2D convolution",
      "type": "topic",
      "url": "/documentation/accelerate/2d-convolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COMPLEX_SPLIT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COMPLEX_SPLIT"
        }
      ],
      "role": "symbol",
      "title": "COMPLEX_SPLIT",
      "type": "topic",
      "url": "/documentation/accelerate/complex_split"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DOUBLE_COMPLEX_SPLIT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DOUBLE_COMPLEX_SPLIT"
        }
      ],
      "role": "symbol",
      "title": "DOUBLE_COMPLEX_SPLIT",
      "type": "topic",
      "url": "/documentation/accelerate/double_complex_split"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublecomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublesplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspsplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/absolute-and-negation-functions": {
      "abstract": [
        {
          "text": "Compute the absolute or negated value of each element in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/absolute-and-negation-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Absolute and negation functions",
      "type": "topic",
      "url": "/documentation/accelerate/absolute-and-negation-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/arithmetic-operations": {
      "abstract": [
        {
          "text": "Perform operations on large vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/arithmetic-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Arithmetic operations",
      "type": "topic",
      "url": "/documentation/accelerate/arithmetic-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/autospectrum-computation": {
      "abstract": [
        {
          "text": "Compute the element-wise sum of the squares of the real and imaginary parts of a complex vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/autospectrum-computation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Autospectrum computation",
      "type": "topic",
      "url": "/documentation/accelerate/autospectrum-computation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters": {
      "abstract": [
        {
          "text": "Apply biquadratic filters to single-channel and multichannel data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Biquadratic IIR filters",
      "type": "topic",
      "url": "/documentation/accelerate/biquadratic-iir-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/clipping-limit-and-threshold-operations": {
      "abstract": [
        {
          "text": "Apply clipping, limit, or threshold rules to the elements in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/clipping-limit-and-threshold-operations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipping, limit, and threshold operations",
      "type": "topic",
      "url": "/documentation/accelerate/clipping-limit-and-threshold-operations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/coherence-function-computation": {
      "abstract": [
        {
          "text": "Compute the coherence of two vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/coherence-function-computation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Coherence function computation",
      "type": "topic",
      "url": "/documentation/accelerate/coherence-function-computation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/complex-basic-arithmetic": {
      "abstract": [
        {
          "text": "Perform elementwise operations on vectors of complex values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/complex-basic-arithmetic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Complex basic arithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/complex-basic-arithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/complex-conjugation-functions": {
      "abstract": [
        {
          "text": "Calculate the complex conjugate of the elements in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/complex-conjugation-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Complex conjugation functions",
      "type": "topic",
      "url": "/documentation/accelerate/complex-conjugation-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/complex-vector-conversion": {
      "abstract": [
        {
          "text": "Perform element-wise split-complex to interleaved and interleaved to split-complex conversion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/complex-vector-conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Complex vector conversion",
      "type": "topic",
      "url": "/documentation/accelerate/complex-vector-conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/compression-and-gathering-functions": {
      "abstract": [
        {
          "text": "Compress vectors based on the nonzero elements in a gating vector, or gather vectors based on a separate vector that contains indices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/compression-and-gathering-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Compression and gathering functions",
      "type": "topic",
      "url": "/documentation/accelerate/compression-and-gathering-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride": {
      "abstract": [
        {
          "text": "Operate selectively on the elements of a vector at regular intervals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
      "kind": "article",
      "role": "article",
      "title": "Controlling vDSP operations with stride",
      "type": "topic",
      "url": "/documentation/accelerate/controlling-vdsp-operations-with-stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/conversion-to-decibel-equivalents": {
      "abstract": [
        {
          "text": "Convert vectors that contain power or amplitude data to decibels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/conversion-to-decibel-equivalents",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion to decibel equivalents",
      "type": "topic",
      "url": "/documentation/accelerate/conversion-to-decibel-equivalents"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/copying-element-swapping-and-merging-functions": {
      "abstract": [
        {
          "text": "Copy, swap, and merge the elements of two vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/copying-element-swapping-and-merging-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Copying, element swapping, and merging functions",
      "type": "topic",
      "url": "/documentation/accelerate/copying-element-swapping-and-merging-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/cross-spectrum-computation": {
      "abstract": [
        {
          "text": "Compute the element-wise product of a vector and the conjugate of a second vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/cross-spectrum-computation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Cross-spectrum computation",
      "type": "topic",
      "url": "/documentation/accelerate/cross-spectrum-computation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms": {
      "abstract": [
        {
          "text": "Transform vectors of temporal and spatial domain real values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Discrete Cosine transforms",
      "type": "topic",
      "url": "/documentation/accelerate/discrete-cosine-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms": {
      "abstract": [
        {
          "text": "Transform vectors of temporal and spatial domain complex values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Discrete Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/discrete-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/dot-product-calculation": {
      "abstract": [
        {
          "text": "Calculate the scalar product of two vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/dot-product-calculation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dot product calculation",
      "type": "topic",
      "url": "/documentation/accelerate/dot-product-calculation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/extrema-finding-functions": {
      "abstract": [
        {
          "text": "Extract the values from a vector that fall outside a range.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/extrema-finding-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extrema finding functions",
      "type": "topic",
      "url": "/documentation/accelerate/extrema-finding-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms": {
      "abstract": [
        {
          "text": "Transform vectors and matrices of temporal and spatial domain complex values to the frequency domain, and vice versa.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fast Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/fast-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/finite-impulse-response-filters": {
      "abstract": [
        {
          "text": "Perform finite impulse response filtering with decimation and antialiasing on vectors of real or complex values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/finite-impulse-response-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Finite impulse response filters",
      "type": "topic",
      "url": "/documentation/accelerate/finite-impulse-response-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/fractional-part-extraction": {
      "abstract": [
        {
          "text": "Truncate the elements of a vector to a fraction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/fractional-part-extraction",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Fractional part extraction",
      "type": "topic",
      "url": "/documentation/accelerate/fractional-part-extraction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/integer-arithmetic": {
      "abstract": [
        {
          "text": "Perform elementwise operations on vectors of integer values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/integer-arithmetic",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Integer arithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/integer-arithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/integration-functions": {
      "abstract": [
        {
          "text": "Compute the running sum, Simpson, or trapezoidal integration of a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/integration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Integration functions",
      "type": "topic",
      "url": "/documentation/accelerate/integration-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/linear-averaging-functions": {
      "abstract": [
        {
          "text": "Calculate the element-wise linear average of two vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/linear-averaging-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Linear averaging functions",
      "type": "topic",
      "url": "/documentation/accelerate/linear-averaging-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/linear-interpolation-functions": {
      "abstract": [
        {
          "text": "Compute the linear average between two vectors or between the neighboring elements in one vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/linear-interpolation-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Linear interpolation functions",
      "type": "topic",
      "url": "/documentation/accelerate/linear-interpolation-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-submatrix-copying-functions": {
      "abstract": [
        {
          "text": "Copy the contents of a submatrix to another submatrix.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-submatrix-copying-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Matrix and submatrix copying functions",
      "type": "topic",
      "url": "/documentation/accelerate/matrix-and-submatrix-copying-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/multichannel-biquadratic-filters": {
      "abstract": [
        {
          "text": "Filter a multichannel signal with a cascade of biquadratic sections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/multichannel-biquadratic-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multichannel biquadratic filters",
      "type": "topic",
      "url": "/documentation/accelerate/multichannel-biquadratic-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/multiplication": {
      "abstract": [
        {
          "text": "Multiply vectors that contain real or complex values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/multiplication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multiplication",
      "type": "topic",
      "url": "/documentation/accelerate/multiplication"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/normalization-functions": {
      "abstract": [
        {
          "text": "Compute the mean and standard deviation of a vector and calculate new elements to have a zero mean and a unit standard deviation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/normalization-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Normalization functions",
      "type": "topic",
      "url": "/documentation/accelerate/normalization-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/phase-computation-functions": {
      "abstract": [
        {
          "text": "Calculate the element-wise phase values, in radians, of a complex vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/phase-computation-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Phase computation functions",
      "type": "topic",
      "url": "/documentation/accelerate/phase-computation-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/polar-rectangular-conversion": {
      "abstract": [
        {
          "text": "Convert each element of a vector between radius-angle and Cartesian pairs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/polar-rectangular-conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Polar-rectangular conversion",
      "type": "topic",
      "url": "/documentation/accelerate/polar-rectangular-conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/polynomial-evaluation": {
      "abstract": [
        {
          "text": "Evaluate polynomials using coefficients and independent variables that you supply.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/polynomial-evaluation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Polynomial evaluation",
      "type": "topic",
      "url": "/documentation/accelerate/polynomial-evaluation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/quadratic-interpolation-functions": {
      "abstract": [
        {
          "text": "Compute the quadratic interpolation between the neighboring elements in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/quadratic-interpolation-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Quadratic interpolation functions",
      "type": "topic",
      "url": "/documentation/accelerate/quadratic-interpolation-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/recursive-filters": {
      "abstract": [
        {
          "text": "Perform two-pole two-zero recursive filtering on a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/recursive-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Recursive filters",
      "type": "topic",
      "url": "/documentation/accelerate/recursive-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation": {
      "abstract": [
        {
          "text": "Reduce the sample rate of a signal by specifying a decimation factor and applying a custom antialiasing filter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation",
      "kind": "article",
      "role": "article",
      "title": "Resampling a signal with decimation",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-a-signal-with-decimation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reversing-and-sorting-functions": {
      "abstract": [
        {
          "text": "Perform in-place reverse and sort operations on a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reversing-and-sorting-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reversing and sorting functions",
      "type": "topic",
      "url": "/documentation/accelerate/reversing-and-sorting-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/single-channel-biquadratic-filters": {
      "abstract": [
        {
          "text": "Filter a single-channel signal with a cascade of biquadratic sections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/single-channel-biquadratic-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Single-channel biquadratic filters",
      "type": "topic",
      "url": "/documentation/accelerate/single-channel-biquadratic-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/sliding-window-reduction-functions": {
      "abstract": [
        {
          "text": "Calculate maximum values and sums of values in a sliding window.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/sliding-window-reduction-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sliding-window reduction functions",
      "type": "topic",
      "url": "/documentation/accelerate/sliding-window-reduction-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transposition-vdsp": {
      "abstract": [
        {
          "text": "Tranpose vectors that contain real values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transposition-vdsp",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transposition",
      "type": "topic",
      "url": "/documentation/accelerate/transposition-vdsp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/type-conversion": {
      "abstract": [
        {
          "text": "Perform element-wise floating-point to integer and integer to floating-point conversion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/type-conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Type conversion",
      "type": "topic",
      "url": "/documentation/accelerate/type-conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points": {
      "abstract": [
        {
          "text": "Fill the gaps in arrays of numerical data using linear interpolation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points",
      "kind": "article",
      "role": "article",
      "title": "Using linear interpolation to construct new data points",
      "type": "topic",
      "url": "/documentation/accelerate/using-linear-interpolation-to-construct-new-data-points"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic": {
      "abstract": [
        {
          "text": "Increase the performance of common mathematical tasks with vDSP vector-vector and vector-scalar operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic",
      "kind": "article",
      "role": "article",
      "title": "Using vDSP for vector-based arithmetic",
      "type": "topic",
      "url": "/documentation/accelerate/using-vdsp-for-vector-based-arithmetic"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to vDSP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP"
        }
      ],
      "role": "symbol",
      "title": "vDSP",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision real value for biquadratic filtering and discrete Fourier transforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VectorizableDouble"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VectorizableDouble"
        }
      ],
      "role": "symbol",
      "title": "vDSP.VectorizableDouble",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/vectorizabledouble"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision real value for biquadratic filtering and discrete Fourier transforms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VectorizableFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VectorizableFloat"
        }
      ],
      "role": "symbol",
      "title": "vDSP.VectorizableFloat",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/vectorizablefloat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DeprecateTranslations": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_DeprecateTranslations"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DeprecateTranslations",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_DeprecateTranslations",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_deprecatetranslations"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ENUM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_ENUM"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ENUM",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_ENUM",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_enum"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride": {
      "abstract": [
        {
          "text": "An integer value that represents the differences between indices of elements, including the lengths of strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Stride",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two single-precision real matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mmul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mmul",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mmul"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two double-precision real matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mmulD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mmulD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mmuld"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_vtmerg": {
      "abstract": [
        {
          "text": "Performs a tapered merge between two single-precision vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_vtmerg"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_vtmerg",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_vtmerg",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_vtmerg"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmma": {
      "abstract": [
        {
          "text": "Adds a single-precision complex matrix to the product of two single-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmma"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmma",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmma",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmma"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmaD": {
      "abstract": [
        {
          "text": "Adds a double-precision complex matrix to the product of two double-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmmaD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmaD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmmaD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmmad"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmms": {
      "abstract": [
        {
          "text": "Subtracts a single-precision complex matrix from the product of two single-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmms"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmms",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmms",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmsD": {
      "abstract": [
        {
          "text": "Subtracts a double-precision complex matrix from the product of two double-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmmsD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmsD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmmsD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmmsd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmul": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two single-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmmul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmul",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmmul",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmmul"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmulD": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two double-precision complex matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmmulD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmmulD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmmulD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmmuld"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsm": {
      "abstract": [
        {
          "text": "Subtracts the product of two single-precision complex matrices from a single-precision complex matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmsm"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsm",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmsm",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmsm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsmD": {
      "abstract": [
        {
          "text": "Subtracts the product of two double-precision complex matrices from a double-precision complex matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zmsmD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zmsmD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zmsmD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zmsmd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsma": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zvsma"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsma",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zvsma",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zvsma"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsmaD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zvsmaD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsmaD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zvsmaD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zvsmad"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsml": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zvzsml"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsml",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zvzsml",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zvzsml"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsmlD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zvzsmlD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsmlD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zvzsmlD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zvzsmld"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vdsp-compile-time-version-information": {
      "abstract": [
        {
          "text": "The version of vDSP at compile time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vdsp-compile-time-version-information",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vDSP Compile-Time Version Information",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp-compile-time-version-information"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vdsp-protocols": {
      "abstract": [
        {
          "text": "Protocols that support Swift implementations of vDSP operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vdsp-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vDSP Protocols",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp-protocols"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-average-calculation": {
      "abstract": [
        {
          "text": "Calculate the average value in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-average-calculation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector average calculation",
      "type": "topic",
      "url": "/documentation/accelerate/vector-average-calculation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-clear-and-fill-functions": {
      "abstract": [
        {
          "text": "Populate vectors with zeros or a scalar value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-clear-and-fill-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector clear and fill functions",
      "type": "topic",
      "url": "/documentation/accelerate/vector-clear-and-fill-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-distance-and-pythagorean-computation": {
      "abstract": [
        {
          "text": "Calculate distance and hypotenuse of vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-distance-and-pythagorean-computation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector distance and Pythagorean computation",
      "type": "topic",
      "url": "/documentation/accelerate/vector-distance-and-pythagorean-computation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-extrema-calculation": {
      "abstract": [
        {
          "text": "Calculate the minimum and maximum values in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-extrema-calculation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector extrema calculation",
      "type": "topic",
      "url": "/documentation/accelerate/vector-extrema-calculation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-generation": {
      "abstract": [
        {
          "text": "Populate vectors with ramps, values from lookup tables, interpolated values, and window functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-generation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector generation",
      "type": "topic",
      "url": "/documentation/accelerate/vector-generation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-scalar-real-arithmetic-functions": {
      "abstract": [
        {
          "text": "Perform element-wise operations on combinations of vectors of real values and scalar values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-scalar-real-arithmetic-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector-scalar real arithmetic functions",
      "type": "topic",
      "url": "/documentation/accelerate/vector-scalar-real-arithmetic-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-squaring-functions": {
      "abstract": [
        {
          "text": "Compute the square, signed square, or squared magnitude of the elements in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-squaring-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector squaring functions",
      "type": "topic",
      "url": "/documentation/accelerate/vector-squaring-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-summation": {
      "abstract": [
        {
          "text": "Sum the values in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-summation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector summation",
      "type": "topic",
      "url": "/documentation/accelerate/vector-summation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-to-vector-minima-and-maxima": {
      "abstract": [
        {
          "text": "Compute the element-wise minimum or maximum values or magnitudes in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-to-vector-minima-and-maxima",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector-to-vector minima and maxima",
      "type": "topic",
      "url": "/documentation/accelerate/vector-to-vector-minima-and-maxima"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vector-vector-real-arithmetic-functions": {
      "abstract": [
        {
          "text": "Perform element-wise operations on vectors of real values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vector-vector-real-arithmetic-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Vector-vector real arithmetic functions",
      "type": "topic",
      "url": "/documentation/accelerate/vector-vector-real-arithmetic-functions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/zero-crossing-search": {
      "abstract": [
        {
          "text": "Count and find the zero crossings in a vector.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/zero-crossing-search",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Zero crossing search",
      "type": "topic",
      "url": "/documentation/accelerate/zero-crossing-search"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-4310314": {
      "alt": "A flow diagram that depicts how the tapered merge function combines two sine waves. The top row shows a low-frequency sine wave on the left and a high-frequency sine wave on the right. The bottom row shows the merged result. The resulting signal starts with a low-frequency wave and gradually transforms to a high-frequency wave.",
      "identifier": "media-4310314",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a3694216774f4879f22facd838b98c34/media-4310314@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e523026ce557d17fe79f1246fa07902f/media-4310314~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Signal-Processing-Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
        "doc://com.apple.accelerate/documentation/Accelerate/using-linear-interpolation-to-construct-new-data-points",
        "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-a-signal-with-decimation"
      ],
      "title": "Signal Processing Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Fundamentals",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
        "doc://com.apple.accelerate/documentation/Accelerate/using-vdsp-for-vector-based-arithmetic"
      ],
      "title": "Fundamentals"
    },
    {
      "anchor": "Swift-overlay",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP",
        "doc://com.apple.accelerate/documentation/Accelerate/vdsp-protocols"
      ],
      "title": "Swift overlay"
    },
    {
      "anchor": "Vector-generation-filling-and-clearing",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-generation",
        "doc://com.apple.accelerate/documentation/Accelerate/vector-clear-and-fill-functions"
      ],
      "title": "Vector generation, filling, and clearing"
    },
    {
      "anchor": "Vector-reduction",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-extrema-calculation",
        "doc://com.apple.accelerate/documentation/Accelerate/vector-average-calculation",
        "doc://com.apple.accelerate/documentation/Accelerate/vector-summation"
      ],
      "title": "Vector reduction"
    },
    {
      "anchor": "Vector-geometry-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-distance-and-pythagorean-computation",
        "doc://com.apple.accelerate/documentation/Accelerate/dot-product-calculation"
      ],
      "title": "Vector geometry functions"
    },
    {
      "abstract": [
        {
          "text": "Perform basic arithmetic operations on vectors that contain real and complex values.",
          "type": "text"
        }
      ],
      "anchor": "Element-wise-vector-arithmetic",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/arithmetic-operations"
      ],
      "title": "Element-wise vector arithmetic"
    },
    {
      "anchor": "Vector-scalar-arithmetic",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-scalar-real-arithmetic-functions"
      ],
      "title": "Vector-scalar arithmetic"
    },
    {
      "anchor": "Vector-vector-arithmetic",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-vector-real-arithmetic-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/complex-basic-arithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/integer-arithmetic",
        "doc://com.apple.accelerate/documentation/Accelerate/linear-averaging-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/polynomial-evaluation"
      ],
      "title": "Vector-vector arithmetic"
    },
    {
      "anchor": "Vector-operations",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/compression-and-gathering-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/copying-element-swapping-and-merging-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/reversing-and-sorting-functions"
      ],
      "title": "Vector operations"
    },
    {
      "anchor": "Vector-interpolation",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/linear-interpolation-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/quadratic-interpolation-functions"
      ],
      "title": "Vector interpolation"
    },
    {
      "anchor": "Vector-filtering",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/biquadratic-iir-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/single-channel-biquadratic-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/multichannel-biquadratic-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/finite-impulse-response-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/recursive-filters"
      ],
      "title": "Vector filtering"
    },
    {
      "anchor": "Vector-conversion-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/conversion-to-decibel-equivalents",
        "doc://com.apple.accelerate/documentation/Accelerate/type-conversion",
        "doc://com.apple.accelerate/documentation/Accelerate/complex-vector-conversion",
        "doc://com.apple.accelerate/documentation/Accelerate/polar-rectangular-conversion"
      ],
      "title": "Vector conversion functions"
    },
    {
      "anchor": "Single-vector-arithmetic-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/absolute-and-negation-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/integration-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/clipping-limit-and-threshold-operations",
        "doc://com.apple.accelerate/documentation/Accelerate/normalization-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/phase-computation-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/complex-conjugation-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/vector-squaring-functions",
        "doc://com.apple.accelerate/documentation/Accelerate/fractional-part-extraction",
        "doc://com.apple.accelerate/documentation/Accelerate/zero-crossing-search",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsma",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvsmaD",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsml",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zvzsmlD"
      ],
      "title": "Single-vector arithmetic functions"
    },
    {
      "anchor": "Single-vector-sliding-window-operations",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/sliding-window-reduction-functions"
      ],
      "title": "Single-vector sliding-window operations"
    },
    {
      "anchor": "Vector-to-vector-spectra-and-coherence-computation",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/autospectrum-computation",
        "doc://com.apple.accelerate/documentation/Accelerate/cross-spectrum-computation",
        "doc://com.apple.accelerate/documentation/Accelerate/coherence-function-computation"
      ],
      "title": "Vector-to-vector spectra and coherence computation"
    },
    {
      "anchor": "Vector-to-vector-extrema-functions",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vector-to-vector-minima-and-maxima",
        "doc://com.apple.accelerate/documentation/Accelerate/extrema-finding-functions"
      ],
      "title": "Vector-to-vector extrema functions"
    },
    {
      "anchor": "Matrix-operations",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/multiplication",
        "doc://com.apple.accelerate/documentation/Accelerate/transposition-vdsp",
        "doc://com.apple.accelerate/documentation/Accelerate/matrix-and-submatrix-copying-functions"
      ],
      "title": "Matrix operations"
    },
    {
      "anchor": "Vector-and-matrix-correlation-and-convolution",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/1d-correlation-and-convolution",
        "doc://com.apple.accelerate/documentation/Accelerate/2d-convolution"
      ],
      "title": "Vector and matrix correlation and convolution"
    },
    {
      "anchor": "Vector-and-matrix-Fourier-transforms",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/fast-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/discrete-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/discrete-cosine-transforms"
      ],
      "title": "Vector and matrix Fourier transforms"
    },
    {
      "anchor": "Data-types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/COMPLEX_SPLIT",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/DOUBLE_COMPLEX_SPLIT",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableDouble",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/VectorizableFloat"
      ],
      "title": "Data types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vdsp-compile-time-version-information"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DeprecateTranslations",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ENUM"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/title",
          "value": "DSPDoubleComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/title",
          "value": "vDSP_Stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/title",
          "value": "COMPLEX_SPLIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1COMPLEX_SPLIT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/title",
          "value": "DSPSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/title",
          "value": "DOUBLE_COMPLEX_SPLIT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DOUBLE_COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DOUBLE_COMPLEX_SPLIT/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DOUBLE_COMPLEX_SPLIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/title",
          "value": "DSPDoubleSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/title",
          "value": "DSPComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
