{
  "abstract": [
    {
      "text": "Performs a 16-element FFT on interleaved-complex data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_copv"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_FFT16_copv",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_FFT16_copv"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_FFT16_copv"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_FFT16_copv"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_FFT16_copv"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__Output"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__Input"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFTDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FFTDirection",
              "text": "FFTDirection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__Direction"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A vector-block-aligned output array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Output"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A vector-block-aligned input array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Input"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A flag that specifies the transform direction. Pass ",
                  "type": "text"
                },
                {
                  "text": "doc://com.apple.documentation/documentation/kernel/1645049-anonymous/kfftdirection_forward",
                  "type": "text"
                },
                {
                  "text": " to transform from the time domain to the frequency domain. Pass ",
                  "type": "text"
                },
                {
                  "text": "doc://com.apple.documentation/documentation/kernel/1645049-anonymous/kfftdirection_inverse",
                  "type": "text"
                },
                {
                  "text": " to transform from the frequency domain to the time domain.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Direction"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To learn how the vDSP library scales and arranges the FFT output, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/FFTDirection": {
      "abstract": [
        {
          "text": "Constants that specify whether to perform a forward or inverse FFT.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FFTDirection"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/FFTDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FFTDirection"
        }
      ],
      "role": "symbol",
      "title": "FFTDirection",
      "type": "topic",
      "url": "/documentation/accelerate/fftdirection"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_copv": {
      "abstract": [
        {
          "text": "Performs a 16-element FFT on interleaved-complex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_FFT16_copv"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_copv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_FFT16_copv",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_fft16_copv"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_zopv": {
      "abstract": [
        {
          "text": "Performs a 16-element FFT on split-complex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_FFT16_zopv"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_zopv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_FFT16_zopv",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_fft16_zopv"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_copv": {
      "abstract": [
        {
          "text": "Performs a 32-element FFT on interleaved-complex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_FFT32_copv"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_copv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_FFT32_copv",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_fft32_copv"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_zopv": {
      "abstract": [
        {
          "text": "Performs a 32-element FFT on split-complex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_FFT32_zopv"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_zopv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_FFT32_zopv",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_fft32_zopv"
    },
    "doc://com.apple.documentation/documentation/Accelerate/understanding-data-packing-for-fourier-transforms": {
      "abstract": [
        {
          "text": "Format source data for the vDSP Fourier functions, and interpret the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
      "kind": "article",
      "role": "article",
      "title": "Understanding data packing for Fourier transforms",
      "type": "topic",
      "url": "/documentation/Accelerate/understanding-data-packing-for-fourier-transforms"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fixed-Length-FFT-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_copv",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT16_zopv",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_FFT32_zopv"
      ],
      "title": "Fixed-Length FFT Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTDirection/title",
          "value": "FFTDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1FFTDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FFTDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_fft16_copv"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
