{
  "abstract": [
    {
      "text": "Builds a data structure that contains precalculated data for use by a double-precision, multichannel cascaded biquadratic filter function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetupD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_biquadm_CreateSetupD",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_biquadm_CreateSetupD"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_biquadm_CreateSetupD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_biquadm_CreateSetupD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_SetupD",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_biquadm_SetupD",
              "text": "vDSP_biquadm_SetupD"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_biquadm_CreateSetupD"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:d",
              "text": "double"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__coeffs"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__M"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__N"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The input array that contains the double-precision filter coefficients. The number of elements in the coefficients array must be ",
                  "type": "text"
                },
                {
                  "code": "5 * __M * __N",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__coeffs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of sections in the biquadratic filter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__M"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of input-output channels.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__N"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A pointer to an allocated and initialized biquadratic filter object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function constructs and returns a biquadratic filter object from the coefficients that you specify. This function initializes the internal state of the setup object with all delay elements set to zero.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You define the ",
              "type": "text"
            },
            {
              "code": "__Coefficients",
              "type": "codeVoice"
            },
            {
              "text": " array as a series of sections where each section contains a set of five coefficients for each channel. Specify the order of the coefficients as three feedforward coefficients followed by two feedback coefficients.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows an example of creating a biquadratic setup object that contains two sections:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let section0 = (b0: 0.984764420,",
            "                b1: -1.969528840,",
            "                b2: 0.984764420,",
            "                a1: -1.969331359,",
            "                a2: 0.969726321)",
            "",
            "let section1 = (b0: 0.984764420,",
            "                b1: -1.969528840,",
            "                b2: 0.984764420,",
            "                a1: -1.955243388,",
            "                a2: 0.969726321)",
            "",
            "let sectionCount = vDSP_Length(2)",
            "let channelCount = vDSP_Length(1)",
            "",
            "let setup = vDSP_biquadm_CreateSetupD([",
            "    section0.b0, section0.b1, section0.b2, section0.a1, section0.a2,",
            "    section1.b0, section1.b1, section1.b2, section1.a1, section1.a2",
            "],",
            "                                      sectionCount,",
            "                                      channelCount)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This function allocates memory for its own use. To free the allocated memory, call the ",
              "type": "text"
            },
            {
              "text": "doc://com.apple.documentation/documentation/kernel/1580013-vdsp_biquadm_destroysetupd",
              "type": "text"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetup": {
      "abstract": [
        {
          "text": "Builds a data structure that contains precalculated data for use by a single-precision, multichannel cascaded biquadratic filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_CreateSetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_biquadm_CreateSetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquadm_createsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetupD": {
      "abstract": [
        {
          "text": "Builds a data structure that contains precalculated data for use by a double-precision, multichannel cascaded biquadratic filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_CreateSetupD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetupD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_biquadm_CreateSetupD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquadm_createsetupd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_Setup": {
      "abstract": [
        {
          "text": "A data structure that contains precalculated data for use by a single-precision, multichannel cascaded biquadratic filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_Setup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_Setup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_Setup"
        }
      ],
      "role": "symbol",
      "title": "vDSP_biquadm_Setup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquadm_setup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_SetupD": {
      "abstract": [
        {
          "text": "A data structure that contains precalculated data for use by a double-precision, multichannel cascaded biquadratic filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_SetupD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_SetupD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_biquadm_SetupD"
        }
      ],
      "role": "symbol",
      "title": "vDSP_biquadm_SetupD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquadm_setupd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-multichannel-biquadratic-filter-setup",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_CreateSetup",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_Setup",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquadm_SetupD"
      ],
      "title": "Creating a multichannel biquadratic filter setup"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_SetupD/title",
          "value": "vDSP_biquadm_SetupD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_SetupD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquadm_SetupD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_SetupD/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquadm_SetupD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_Setup/title",
          "value": "vDSP_biquadm_Setup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_Setup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquadm_Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquadm_Setup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquadm_Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_biquadm_createsetupd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
