{
  "abstract": [
    {
      "text": "Builds a data structure that contains precalculated data to perform a discrete cosine transform.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_CreateSetup"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_DCT_CreateSetup",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_DCT_CreateSetup"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_DCT_CreateSetup"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_DCT_CreateSetup"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_DFT_Setup",
              "text": "vDSP_DFT_Setup"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_DCT_CreateSetup"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_DFT_Setup",
              "text": "vDSP_DFT_Setup"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__Previous"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__Length"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Type",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@vDSP_DCT_Type",
              "text": "vDSP_DCT_Type"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__Type"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An existing ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure that shares memory with the returned setup structure. Pass ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " to create an object with newly initialized and allocated memory.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Previous"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of real elements to transform. The supported values are ",
                  "type": "text"
                },
                {
                  "code": "Length",
                  "type": "codeVoice"
                },
                {
                  "text": " = ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "f",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " * 2**",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "n",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ", where ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "f",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " is 1, 3, 5, or 15 and ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "n",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " is at least 4.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Length"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A constant that defines which discrete cosine transform (DCT) variant to perform.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Type"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When successful, this function returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure. When unsuccessful, this function returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", either because of insufficient memory or because ",
              "type": "text"
            },
            {
              "code": "Length",
              "type": "codeVoice"
            },
            {
              "text": " doesn’t satisfy the requirements given above.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To prevent potential memory leaks, if the ",
                  "type": "text"
                },
                {
                  "code": "Previous",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter is not ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ", the return value and the ",
                  "type": "text"
                },
                {
                  "code": "Previous",
                  "type": "codeVoice"
                },
                {
                  "text": " value must be different variables.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to create a new setup structure. Don’t use the return value to reconfigure an existing setup structure passed to this function as the ",
              "type": "text"
            },
            {
              "code": "Previous",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code creates two setup structures that share the same memory. Note that you must call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_DestroySetup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for both setup structures. Destroying a setup with shared data is safe; the destroy function only releases memory that’s not needed by other undestroyed setups.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var signal = [ ... ]",
            "",
            "guard",
            "    // Create the first setup object.",
            "    let setupForward = vDSP_DCT_CreateSetup(nil,",
            "                                            vDSP_Length(signal.count),",
            "                                            .II),",
            "    // Create the second setup object that shares resources with `setupForward`.",
            "    let setupInverse = vDSP_DCT_CreateSetup(setupForward,",
            "                                            vDSP_Length(signal.count),",
            "                                            .III) else {",
            "    NSLog(\"Failed to create `vDSP_DCT_CreateSetup` setup structures.\")",
            "    return",
            "}",
            "",
            "// Perform DCT-II transform.",
            "vDSP_DCT_Execute(setupForward,",
            "                 signal,",
            "                 &signal)",
            "",
            "// `signal` contains frequency-domain representation of the original signal.",
            "",
            "// Perform DCT-III transform.",
            "vDSP_DCT_Execute(setupInverse,",
            "                 signal,",
            "                 &signal)",
            "",
            "// `signal` contains time-domain representation of the original signal.",
            "",
            "// Call `vDSP_DFT_DestroySetup` on both setup structures.",
            "vDSP_DFT_DestroySetup(setupForward)",
            "vDSP_DFT_DestroySetup(setupInverse)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You should only use the returned setup structure with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Execute",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using an input vector that contains ",
              "type": "text"
            },
            {
              "code": "Length",
              "type": "codeVoice"
            },
            {
              "text": " elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing": {
      "abstract": [
        {
          "text": "Multiply signal data by window sequence values when performing transforms with noninteger period signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
      "kind": "article",
      "role": "article",
      "title": "Reducing spectral leakage with windowing",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-spectral-leakage-with-windowing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms": {
      "abstract": [
        {
          "text": "Format source data for the vDSP Fourier functions, and interpret the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
      "kind": "article",
      "role": "article",
      "title": "Understanding data packing for Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/understanding-data-packing-for-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_CreateSetup": {
      "abstract": [
        {
          "text": "Builds a data structure that contains precalculated data to perform a discrete cosine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_DCT_CreateSetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_CreateSetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_DCT_CreateSetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dct_createsetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Execute": {
      "abstract": [
        {
          "text": "Calculates the discrete cosine transform for a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_DCT_Execute"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Execute",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_DCT_Execute",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dct_execute"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Type": {
      "abstract": [
        {
          "text": "Constants that indicate the type for a discrete cosine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_DCT_Type"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_DCT_Type"
        }
      ],
      "role": "symbol",
      "title": "vDSP_DCT_Type",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dct_type"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_DestroySetup": {
      "abstract": [
        {
          "text": "Releases a single-precision setup structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_DFT_DestroySetup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_DestroySetup",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_DFT_DestroySetup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dft_destroysetup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup": {
      "abstract": [
        {
          "text": "An opaque type that contains setup information for a single-precision discrete Fourier transform (DFT).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_DFT_Setup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DFT_Setup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_DFT_Setup"
        }
      ],
      "role": "symbol",
      "title": "vDSP_DFT_Setup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_dft_setup"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Discrete-Cosine-Transforms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Type",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_DCT_Execute"
      ],
      "title": "Discrete Cosine Transforms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DFT_Setup/title",
          "value": "vDSP_DFT_Setup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DFT_Setup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_DFT_Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DFT_Setup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_DFT_Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DCT_Type/title",
          "value": "vDSP_DCT_Type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DCT_Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_DCT_Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_DCT_Type/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_DCT_Type"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_dct_createsetup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
