{
  "abstract": [
    {
      "text": "Specifies a normalized Hann window",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_NORM"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@vDSP_HALF_WINDOW@vDSP_HANN_NORM",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vDSP_HANN_NORM"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_HANN_NORM"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "vDSP_HANN_NORM"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_HANN_NORM"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing": {
      "abstract": [
        {
          "text": "Multiply signal data by window sequence values when performing transforms with noninteger period signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
      "kind": "article",
      "role": "article",
      "title": "Reducing spectral leakage with windowing",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-spectral-leakage-with-windowing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/WindowSequence": {
      "abstract": [
        {
          "text": "Constants that specify window sequence functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WindowSequence"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/WindowSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WindowSequence"
        }
      ],
      "role": "symbol",
      "title": "vDSP.WindowSequence",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/windowsequence"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-6cmve": {
      "abstract": [
        {
          "text": "Populates a double-precision vector with a specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formWindow"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "usingSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO14WindowSequenceO",
          "text": "WindowSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isHalfWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-6cmve",
      "kind": "symbol",
      "role": "symbol",
      "title": "formWindow(usingSequence:result:isHalfWindow:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/formwindow(usingsequence:result:ishalfwindow:)-6cmve"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-9dls5": {
      "abstract": [
        {
          "text": "Populates a single-precision vector with a specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formWindow"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "usingSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO14WindowSequenceO",
          "text": "WindowSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "result"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isHalfWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-9dls5",
      "kind": "symbol",
      "role": "symbol",
      "title": "formWindow(usingSequence:result:isHalfWindow:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/formwindow(usingsequence:result:ishalfwindow:)-9dls5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP/window(ofType:usingSequence:count:isHalfWindow:)": {
      "abstract": [
        {
          "text": "Returns an array that contains the specified window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "window"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "usingSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO",
          "text": "vDSP"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4vDSPO14WindowSequenceO",
          "text": "WindowSequence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isHalfWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP/window(ofType:usingSequence:count:isHalfWindow:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "window(ofType:usingSequence:count:isHalfWindow:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp/window(oftype:usingsequence:count:ishalfwindow:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HALF_WINDOW": {
      "abstract": [
        {
          "text": "Specifies that the window should only contain the bottom half of the values (",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "(N+1)/2",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_HALF_WINDOW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HALF_WINDOW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_HALF_WINDOW"
        }
      ],
      "role": "symbol",
      "title": "vDSP_HALF_WINDOW",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_half_window"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_DENORM": {
      "abstract": [
        {
          "text": "Specifies a denormalized Hann window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_HANN_DENORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_DENORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_HANN_DENORM"
        }
      ],
      "role": "symbol",
      "title": "vDSP_HANN_DENORM",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hann_denorm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_NORM": {
      "abstract": [
        {
          "text": "Specifies a normalized Hann window",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_HANN_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_HANN_NORM"
        }
      ],
      "role": "symbol",
      "title": "vDSP_HANN_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hann_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_window": {
      "abstract": [
        {
          "text": "Creates a single-precision Blackman window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_blkman_window"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_window",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_blkman_window",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_blkman_window"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_windowD": {
      "abstract": [
        {
          "text": "Creates a double-precision Blackman window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_blkman_windowD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_windowD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_blkman_windowD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_blkman_windowd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_window": {
      "abstract": [
        {
          "text": "Creates a single-precision Hamming window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_hamm_window"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_window",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_hamm_window",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hamm_window"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_windowD": {
      "abstract": [
        {
          "text": "Creates a double-precision Hamming window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_hamm_windowD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_windowD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_hamm_windowD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hamm_windowd"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_window": {
      "abstract": [
        {
          "text": "Creates a single-precision Hann window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_hann_window"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_window",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_hann_window",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hann_window"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_windowD": {
      "abstract": [
        {
          "text": "Creates a double-precision Hann window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_hann_windowD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_windowD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_hann_windowD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_hann_windowd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Vector-generation-with-window-functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-spectral-leakage-with-windowing",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/window(ofType:usingSequence:count:isHalfWindow:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-6cmve",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/formWindow(usingSequence:result:isHalfWindow:)-9dls5",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP/WindowSequence",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HALF_WINDOW",
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_DENORM"
      ],
      "title": "Vector generation with window functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vDSP_HANN_NORM"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_HANN_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Vector-generation-with-window-functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_window",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_blkman_windowD",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_window",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hamm_windowD",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_window",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_hann_windowD",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HALF_WINDOW",
                "doc://com.apple.accelerate/documentation/Accelerate/vDSP_HANN_DENORM"
              ],
              "title": "Vector generation with window functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "vDSP_HANN_NORM"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HANN_NORM/title",
          "value": "vDSP_HANN_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HANN_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_HANN_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HALF_WINDOW/title",
          "value": "vDSP_HALF_WINDOW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HALF_WINDOW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_HALF_WINDOW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HANN_DENORM/title",
          "value": "vDSP_HANN_DENORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_HANN_DENORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_HANN_DENORM"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_hann_norm"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vdsp_hann_norm"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
