{
  "abstract": [
    {
      "text": "Copies the contents of an interleaved single-precision complex vector to a split complex vector.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctoz"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_ctoz",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_ctoz"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_ctoz"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_ctoz"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_ctoz"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPComplex",
              "text": "DSPComplex"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__C"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IC"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPSplitComplex",
              "text": "DSPSplitComplex"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__Z"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IZ"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__N"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The interleaved-complex input vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__C"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance between the real elements in the input vector. For example, a stride of ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": " corresponds to a single complex element.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IC"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The split-complex output vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__Z"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance between the elements in the ouput vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IZ"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of complex elements that the function processes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__N"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
        "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
        "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the following code converts the contents of an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structures to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " structure:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    let source: [DSPComplex] = [",
            "        DSPComplex(real: 1.0, imag: 10.0),",
            "        DSPComplex(real: 2.0, imag: 20.0),",
            "        DSPComplex(real: 3.0, imag: 30.0),",
            "        DSPComplex(real: 4.0, imag: 40.0),",
            "    ]",
            "    ",
            "    let destReal = UnsafeMutableBufferPointer<Float>.allocate(capacity: 4)",
            "    let destImag = UnsafeMutableBufferPointer<Float>.allocate(capacity: 4)",
            "    ",
            "    var destination = DSPSplitComplex(realp: destReal.baseAddress!,",
            "                                      imagp: destImag.baseAddress!)",
            "    ",
            "    vDSP_ctoz(source, 2,",
            "              &destination, 1,",
            "              4)",
            "    ",
            "    print(Array(destReal)) // Prints \"[1.0, 2.0, 3.0, 4.0]\".",
            "    print(Array(destImag)) // Prints \"[10.0, 20.0, 30.0, 40.0]\"."
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a single-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspsplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride": {
      "abstract": [
        {
          "text": "Operate selectively on the elements of a vector at regular intervals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/controlling-vdsp-operations-with-stride",
      "kind": "article",
      "role": "article",
      "title": "Controlling vDSP operations with stride",
      "type": "topic",
      "url": "/documentation/accelerate/controlling-vdsp-operations-with-stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data": {
      "abstract": [
        {
          "text": "Optimize discrete Fourier transform (DFT) performance with the vDSP interleaved DFT routines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/performing-fourier-transforms-on-interleaved-complex-data",
      "kind": "article",
      "role": "article",
      "title": "Performing Fourier transforms on interleaved-complex data",
      "type": "topic",
      "url": "/documentation/accelerate/performing-fourier-transforms-on-interleaved-complex-data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms": {
      "abstract": [
        {
          "text": "Format source data for the vDSP Fourier functions, and interpret the results.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/understanding-data-packing-for-fourier-transforms",
      "kind": "article",
      "role": "article",
      "title": "Understanding data packing for Fourier transforms",
      "type": "topic",
      "url": "/documentation/accelerate/understanding-data-packing-for-fourier-transforms"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride": {
      "abstract": [
        {
          "text": "An integer value that represents the differences between indices of elements, including the lengths of strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Stride",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctoz": {
      "abstract": [
        {
          "text": "Copies the contents of an interleaved single-precision complex vector to a split complex vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_ctoz"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctoz",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_ctoz",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_ctoz"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctozD": {
      "abstract": [
        {
          "text": "Copies the contents of an interleaved double-precision complex vector to a split complex vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_ctozD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctozD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_ctozD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_ctozd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Converting-interleaved-complex-vectors-to-split-complex-vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_ctozD"
      ],
      "title": "Converting interleaved-complex vectors to split-complex vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/title",
          "value": "DSPSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/title",
          "value": "vDSP_Stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/title",
          "value": "DSPComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPComplex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_ctoz"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
