{
  "abstract": [
    {
      "text": "Performs an out-of-place multiplication of two single-precision real matrices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_mmul",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_mmul"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_mmul"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_mmul"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_mmul"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__A"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IA"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__B"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IB"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__C"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IC"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__M"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__N"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__P"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "M",
                  "type": "codeVoice"
                },
                {
                  "text": " x ",
                  "type": "text"
                },
                {
                  "code": "P",
                  "type": "codeVoice"
                },
                {
                  "text": " left-hand side input matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__A"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance between the elements in the left-hand side input matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "P",
                  "type": "codeVoice"
                },
                {
                  "text": " x ",
                  "type": "text"
                },
                {
                  "code": "N",
                  "type": "codeVoice"
                },
                {
                  "text": " right-hand side input matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__B"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance between the elements in the right-hand side input matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IB"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "M",
                  "type": "codeVoice"
                },
                {
                  "text": " x ",
                  "type": "text"
                },
                {
                  "code": "N",
                  "type": "codeVoice"
                },
                {
                  "text": " output matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__C"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The distance between the elements in the output matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IC"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of rows in matrices ",
                  "type": "text"
                },
                {
                  "code": "A",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "C",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__M"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of columns in matrices ",
                  "type": "text"
                },
                {
                  "code": "B",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "C",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__N"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of columns in matrix ",
                  "type": "text"
                },
                {
                  "code": "A",
                  "type": "codeVoice"
                },
                {
                  "text": " and the number of rows in matrix ",
                  "type": "text"
                },
                {
                  "code": "B",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__P"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following code multiplies the matrices ",
              "type": "text"
            },
            {
              "code": "a",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "b",
              "type": "codeVoice"
            },
            {
              "text": ", and writes the result to matrix ",
              "type": "text"
            },
            {
              "code": "c",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    let m: vDSP_Length = 2",
            "    let n: vDSP_Length = 5",
            "    let p: vDSP_Length = 3",
            "    ",
            "    // `m` rows x `p` columns.",
            "    let a: [Float] = [ 1, 2, 3,",
            "                       4, 5, 6 ]",
            "    ",
            "    // `p` rows x `n` columns.",
            "    let b: [Float] = [ 10, 11, 12, 13, 14,",
            "                       15, 16, 17, 18, 19,",
            "                       20, 21, 22, 23, 24 ]",
            "    ",
            "    ",
            "    ",
            "    // `m` rows x `n` columns.",
            "    var c = [Float](repeating: 0,",
            "                    count: Int(m * n))",
            "    ",
            "    let stride = 1",
            "    ",
            "    vDSP_mmul(a, stride,",
            "              b, stride,",
            "              &c, stride,",
            "              m,",
            "              n,",
            "              p)",
            "    ",
            "    // Prints:",
            "    // \"[ 100.0, 106.0, 112.0, 118.0, 124.0,",
            "    //    235.0, 250.0, 265.0, 280.0, 295.0 ]\".",
            "    print(c)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride": {
      "abstract": [
        {
          "text": "An integer value that represents the differences between indices of elements, including the lengths of strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Stride",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two single-precision real matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mmul"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmul",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mmul",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mmul"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD": {
      "abstract": [
        {
          "text": "Performs an out-of-place multiplication of two double-precision real matrices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_mmulD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_mmulD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_mmuld"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Multiplying-real-matrices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_mmulD"
      ],
      "title": "Multiplying real matrices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/title",
          "value": "vDSP_Stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_mmul"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
