{
  "abstract": [
    {
      "text": "Performs either correlation or convolution on two complex double-precision vectors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconvD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_zconvD",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_zconvD"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_zconvD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_zconvD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_zconvD"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPDoubleSplitComplex",
              "text": "DSPDoubleSplitComplex"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__A"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IA"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPDoubleSplitComplex",
              "text": "DSPDoubleSplitComplex"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__F"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IF"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@DSPDoubleSplitComplex",
              "text": "DSPDoubleSplitComplex"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__C"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Stride",
              "text": "vDSP_Stride"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__IC"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__N"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__P"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The complex double-precision input signal vector. The length of this vector must be at least ",
                  "type": "text"
                },
                {
                  "code": "N + P - 1",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__A"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The stride through the input signal vector, ",
                  "type": "text"
                },
                {
                  "code": "A",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The complex double-precision filter vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__F"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The stride through the filter vector, ",
                  "type": "text"
                },
                {
                  "code": "F",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IF"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The complex double-precision output signal vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__C"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The stride through the output signal vector, ",
                  "type": "text"
                },
                {
                  "code": "C",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__IC"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of elements in the output signal vector, ",
                  "type": "text"
                },
                {
                  "code": "C",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__N"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of elements in the filter vector, ",
                  "type": "text"
                },
                {
                  "code": "F",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__P"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to compute either the convolution or the correlation of an input signal and a filter vector. Both operations compute the sliding dot product of the filter and the section of the input signal that the filter is over. Specify a positive stride through the filter to perform correlation and a negative stride through the filter to perform convolution. When you perform convolution, the ",
              "type": "text"
            },
            {
              "code": "__F",
              "type": "codeVoice"
            },
            {
              "text": " parameter must point to the last element in the filter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The function can run in place, but ",
              "type": "text"
            },
            {
              "code": "C",
              "type": "codeVoice"
            },
            {
              "text": " can’t be in place with ",
              "type": "text"
            },
            {
              "code": "F",
              "type": "codeVoice"
            },
            {
              "text": ". For example, the following code defines an input signal, a filter, and the number of output elements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let signalReal = UnsafeMutableBufferPointer<Double>.allocate(capacity: 8)",
            "_ = signalReal.initialize(from: [1, 2, 3, 4, 5, 6, 7, 8])",
            "",
            "let signalImag = UnsafeMutableBufferPointer<Double>.allocate(capacity: 8)",
            "_ = signalImag.initialize(from: [1, 2, 3, 4, 5, 6, 7, 8])",
            "",
            "var signal = DSPDoubleSplitComplex(realp: signalReal.baseAddress!,",
            "                                   imagp: signalImag.baseAddress!)",
            "",
            "let filterReal = UnsafeMutableBufferPointer<Double>.allocate(capacity: 3)",
            "_ = filterReal.initialize(from: [10, 20, 30])",
            "",
            "let filterImag = UnsafeMutableBufferPointer<Double>.allocate(capacity: 3)",
            "_ = filterImag.initialize(from: [10, 20, 30])",
            "",
            "var filter = DSPDoubleSplitComplex(realp: filterReal.baseAddress!,",
            "                                   imagp: filterImag.baseAddress!)",
            "let filterCount = filterReal.count",
            "",
            "let outputCount = signalReal.count - filterReal.count + 1",
            "",
            "defer {",
            "    signalReal.deallocate()",
            "    signalImag.deallocate()",
            "    filterReal.deallocate()",
            "    filterImag.deallocate()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Perform-Correlation",
          "level": 3,
          "text": "Perform Correlation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following code performs correlation. In this example, the stride through the filter is ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let correlationResultReal = UnsafeMutableBufferPointer<Double>.allocate(capacity: outputCount)",
            "let correlationResultImag = UnsafeMutableBufferPointer<Double>.allocate(capacity: outputCount)",
            "var correlationResult = DSPDoubleSplitComplex(realp: correlationResultReal.baseAddress!,",
            "                                              imagp: correlationResultImag.baseAddress!)",
            "",
            "defer {",
            "    correlationResultReal.deallocate()",
            "    correlationResultImag.deallocate()",
            "}",
            "",
            "vDSP_zconvD(&signal,",
            "            1,",
            "            &filter,",
            "            1, // The stride through the filter vector.",
            "            &correlationResult,",
            "            1,",
            "            vDSP_Length(outputCount),",
            "            vDSP_Length(filterCount))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, ",
              "type": "text"
            },
            {
              "code": "correlationResultReal",
              "type": "codeVoice"
            },
            {
              "text": " contains all zeroes and ",
              "type": "text"
            },
            {
              "code": "correlationResultImag",
              "type": "codeVoice"
            },
            {
              "text": " contains the values ",
              "type": "text"
            },
            {
              "code": "[280.0, 400.0, 520.0, 640.0, 760.0, 880.0]",
              "type": "codeVoice"
            },
            {
              "text": ". For example, the operation calculates the first element, ",
              "type": "text"
            },
            {
              "code": "280",
              "type": "codeVoice"
            },
            {
              "text": ", as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "(1 + 1i) * (10 + 10i) + (2 + 2i) * (20 + 20i) + (3 + 3i) * (30 + 30i) = 280"
          ],
          "syntax": "c",
          "type": "codeListing"
        },
        {
          "anchor": "Perform-Convolution",
          "level": 3,
          "text": "Perform Convolution",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following code performs convolution. In this example, the stride through the filter is ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " and the filter parameter points to the last element in the filter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let convolutionResultReal = UnsafeMutableBufferPointer<Double>.allocate(capacity: outputCount)",
            "let convolutionResultImag = UnsafeMutableBufferPointer<Double>.allocate(capacity: outputCount)",
            "var convolutionResult = DSPDoubleSplitComplex(realp: convolutionResultReal.baseAddress!,",
            "                                        imagp: convolutionResultImag.baseAddress!)",
            "",
            "defer {",
            "    convolutionResultReal.deallocate()",
            "    convolutionResultImag.deallocate()",
            "}",
            "",
            "var kernel = DSPDoubleSplitComplex(realp: filter.realp.advanced(by: filterCount - 1),",
            "                                   imagp: filter.imagp.advanced(by: filterCount - 1))",
            "",
            "vDSP_zconvD(&signal,",
            "            1,",
            "            &kernel,",
            "            -1, // The stride through the filter vector.",
            "            &convolutionResult,",
            "            1,",
            "            vDSP_Length(outputCount),",
            "            vDSP_Length(filterCount))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, ",
              "type": "text"
            },
            {
              "code": "correlationResultReal",
              "type": "codeVoice"
            },
            {
              "text": " contains all zeroes and ",
              "type": "text"
            },
            {
              "code": "correlationResultImag",
              "type": "codeVoice"
            },
            {
              "text": " contains the values ",
              "type": "text"
            },
            {
              "code": "[200.0, 320.0, 440.0, 560.0, 680.0, 800.0]",
              "type": "codeVoice"
            },
            {
              "text": ". For example, the operation calculates the first element, ",
              "type": "text"
            },
            {
              "code": "200",
              "type": "codeVoice"
            },
            {
              "text": ", as:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "(1 + 1i) * (30 + 30i) + (2 + 2i) * (20 + 20i) + (3 + 3i) * (10 + 10i) = 200"
          ],
          "syntax": "c",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex": {
      "abstract": [
        {
          "text": "A structure that represents a double-precision complex vector with the real and imaginary parts stored in separate arrays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/DSPDoubleSplitComplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DSPDoubleSplitComplex"
        }
      ],
      "role": "symbol",
      "title": "DSPDoubleSplitComplex",
      "type": "topic",
      "url": "/documentation/accelerate/dspdoublesplitcomplex"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride": {
      "abstract": [
        {
          "text": "An integer value that represents the differences between indices of elements, including the lengths of strides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Stride"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Stride",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconv": {
      "abstract": [
        {
          "text": "Performs either correlation or convolution on two complex single-precision vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zconv"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconv",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zconv",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zconv"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconvD": {
      "abstract": [
        {
          "text": "Performs either correlation or convolution on two complex double-precision vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_zconvD"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconvD",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_zconvD",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_zconvd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Complex-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_zconv"
      ],
      "title": "Complex Vectors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/title",
          "value": "vDSP_Stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Stride/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/title",
          "value": "DSPDoubleSplitComplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1DSPDoubleSplitComplex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DSPDoubleSplitComplex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_zconvd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
