{
  "abstract": [
    {
      "text": "Sets single-precision coefficients of the specified single-channel biquadratic filter setup object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsSingle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vDSP_biquad_SetCoefficientsSingle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "vDSP_biquad_SetCoefficientsSingle"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vDSP_biquad_SetCoefficientsSingle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vDSP_biquad_SetCoefficientsSingle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vDSP_biquad_SetCoefficientsSingle"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_Setup",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_biquad_Setup",
              "text": "vDSP_biquad_Setup"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__setup"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:f",
              "text": "float"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "__coeffs"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__start_sec"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vDSP_Length",
              "text": "vDSP_Length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "__nsec"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The biquadratic filter setup object that the function updates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__setup"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the new coefficients.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__coeffs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The first section that the function updates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__start_sec"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of sections that the function updates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "__nsec"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to update sections of coefficient values of a biquad setup structure. This function doesn’t allocate new memory. The range that you specify using ",
              "type": "text"
            },
            {
              "code": "__start_sec",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "__nsec",
              "type": "codeVoice"
            },
            {
              "text": " must be within the number of sections that you define in the create setup function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length": {
      "abstract": [
        {
          "text": "An unsigned-integer value that represents the size of vectors and the indices of elements in vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_Length",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_Length"
        }
      ],
      "role": "symbol",
      "title": "vDSP_Length",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_length"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsDouble": {
      "abstract": [
        {
          "text": "Sets double-precision coefficients of the specified single-channel biquadratic filter setup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_biquad_SetCoefficientsDouble"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsDouble",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_biquad_SetCoefficientsDouble",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquad_setcoefficientsdouble"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsSingle": {
      "abstract": [
        {
          "text": "Sets single-precision coefficients of the specified single-channel biquadratic filter setup object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vDSP_biquad_SetCoefficientsSingle"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsSingle",
      "kind": "symbol",
      "role": "symbol",
      "title": "vDSP_biquad_SetCoefficientsSingle",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquad_setcoefficientssingle"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_Setup": {
      "abstract": [
        {
          "text": "A data structure that contains precalculated data for use by the single-precision cascaded biquadratic IIR filter function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vDSP_biquad_Setup"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_Setup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vDSP_biquad_Setup"
        }
      ],
      "role": "symbol",
      "title": "vDSP_biquad_Setup",
      "type": "topic",
      "url": "/documentation/accelerate/vdsp_biquad_setup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-coefficients-of-a-single-channel-biquadratic-filter",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vDSP_biquad_SetCoefficientsDouble"
      ],
      "title": "Setting the coefficients of a single-channel biquadratic filter"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/title",
          "value": "vDSP_Length"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_Length/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_Length"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquad_Setup/title",
          "value": "vDSP_biquad_Setup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquad_Setup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquad_Setup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vDSP_biquad_Setup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vDSP_biquad_Setup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vdsp_biquad_setcoefficientssingle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
