{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/veclib"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/veclib-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
        }
      ],
      "role": "symbol",
      "title": "LA_ATTRIBUTE_ENABLE_LOGGING",
      "type": "topic",
      "url": "/documentation/accelerate/la_attribute_enable_logging"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/accelerate/la_availability"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_CONST"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_CONST",
      "type": "topic",
      "url": "/documentation/accelerate/la_const"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_DEFAULT_ATTRIBUTES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_DEFAULT_ATTRIBUTES"
        }
      ],
      "role": "symbol",
      "title": "LA_DEFAULT_ATTRIBUTES",
      "type": "topic",
      "url": "/documentation/accelerate/la_default_attributes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_DIMENSION_MISMATCH_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_DIMENSION_MISMATCH_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_DIMENSION_MISMATCH_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_dimension_mismatch_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_EXPORT",
      "type": "topic",
      "url": "/documentation/accelerate/la_export"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_DIAGONALLY_DOMINANT",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_diagonally_dominant"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_POSITIVE_DEFINITE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_POSITIVE_DEFINITE"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_POSITIVE_DEFINITE",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_positive_definite"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_FEATURE_SYMMETRIC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_FEATURE_SYMMETRIC"
        }
      ],
      "role": "symbol",
      "title": "LA_FEATURE_SYMMETRIC",
      "type": "topic",
      "url": "/documentation/accelerate/la_feature_symmetric"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_FUNCTION"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_FUNCTION",
      "type": "topic",
      "url": "/documentation/accelerate/la_function"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_INTERNAL_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_INTERNAL_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_INTERNAL_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_internal_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_INVALID_PARAMETER_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_INVALID_PARAMETER_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_INVALID_PARAMETER_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_invalid_parameter_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_L1_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_L1_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_L1_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_l1_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_L2_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_L2_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_L2_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_l2_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_LINF_NORM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_LINF_NORM"
        }
      ],
      "role": "symbol",
      "title": "LA_LINF_NORM",
      "type": "topic",
      "url": "/documentation/accelerate/la_linf_norm"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_NONNULL"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_NONNULL",
      "type": "topic",
      "url": "/documentation/accelerate/la_nonnull"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_NONNULL1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL1",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_NONNULL1",
      "type": "topic",
      "url": "/documentation/accelerate/la_nonnull1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_NOTHROW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_NOTHROW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_NOTHROW",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_NOTHROW",
      "type": "topic",
      "url": "/documentation/accelerate/la_nothrow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_NO_HINT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_NO_HINT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_NO_HINT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_NO_HINT"
        }
      ],
      "role": "symbol",
      "title": "LA_NO_HINT",
      "type": "topic",
      "url": "/documentation/accelerate/la_no_hint"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_PRECISION_MISMATCH_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_PRECISION_MISMATCH_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_PRECISION_MISMATCH_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_PRECISION_MISMATCH_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_PRECISION_MISMATCH_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_precision_mismatch_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LA_RETURNS_RETAINED"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_RETURNS_RETAINED",
      "kind": "symbol",
      "role": "symbol",
      "title": "LA_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/accelerate/la_returns_retained"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_DOUBLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SCALAR_TYPE_DOUBLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_DOUBLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SCALAR_TYPE_DOUBLE"
        }
      ],
      "role": "symbol",
      "title": "LA_SCALAR_TYPE_DOUBLE",
      "type": "topic",
      "url": "/documentation/accelerate/la_scalar_type_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_FLOAT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SCALAR_TYPE_FLOAT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_FLOAT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SCALAR_TYPE_FLOAT"
        }
      ],
      "role": "symbol",
      "title": "LA_SCALAR_TYPE_FLOAT",
      "type": "topic",
      "url": "/documentation/accelerate/la_scalar_type_float"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_DIAGONAL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SHAPE_DIAGONAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_DIAGONAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SHAPE_DIAGONAL"
        }
      ],
      "role": "symbol",
      "title": "LA_SHAPE_DIAGONAL",
      "type": "topic",
      "url": "/documentation/accelerate/la_shape_diagonal"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_LOWER_TRIANGULAR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SHAPE_LOWER_TRIANGULAR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_LOWER_TRIANGULAR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SHAPE_LOWER_TRIANGULAR"
        }
      ],
      "role": "symbol",
      "title": "LA_SHAPE_LOWER_TRIANGULAR",
      "type": "topic",
      "url": "/documentation/accelerate/la_shape_lower_triangular"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_UPPER_TRIANGULAR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SHAPE_UPPER_TRIANGULAR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_UPPER_TRIANGULAR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SHAPE_UPPER_TRIANGULAR"
        }
      ],
      "role": "symbol",
      "title": "LA_SHAPE_UPPER_TRIANGULAR",
      "type": "topic",
      "url": "/documentation/accelerate/la_shape_upper_triangular"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SINGULAR_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SINGULAR_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SINGULAR_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SINGULAR_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_SINGULAR_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_singular_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SLICE_OUT_OF_BOUNDS_ERROR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SLICE_OUT_OF_BOUNDS_ERROR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SLICE_OUT_OF_BOUNDS_ERROR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SLICE_OUT_OF_BOUNDS_ERROR"
        }
      ],
      "role": "symbol",
      "title": "LA_SLICE_OUT_OF_BOUNDS_ERROR",
      "type": "topic",
      "url": "/documentation/accelerate/la_slice_out_of_bounds_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_SUCCESS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_SUCCESS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_SUCCESS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_SUCCESS"
        }
      ],
      "role": "symbol",
      "title": "LA_SUCCESS",
      "type": "topic",
      "url": "/documentation/accelerate/la_success"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/LA_WARNING_POORLY_CONDITIONED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LA_WARNING_POORLY_CONDITIONED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/LA_WARNING_POORLY_CONDITIONED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LA_WARNING_POORLY_CONDITIONED"
        }
      ],
      "role": "symbol",
      "title": "LA_WARNING_POORLY_CONDITIONED",
      "type": "topic",
      "url": "/documentation/accelerate/la_warning_poorly_conditioned"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/USE_NON_APPLE_STANDARD_DATATYPES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "USE_NON_APPLE_STANDARD_DATATYPES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/USE_NON_APPLE_STANDARD_DATATYPES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "USE_NON_APPLE_STANDARD_DATATYPES"
        }
      ],
      "role": "symbol",
      "title": "USE_NON_APPLE_STANDARD_DATATYPES",
      "type": "topic",
      "url": "/documentation/accelerate/use_non_apple_standard_datatypes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_release-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_release"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_release-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_release",
      "type": "topic",
      "url": "/documentation/accelerate/la_release-c.macro"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_retain-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_retain"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_retain-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_retain",
      "type": "topic",
      "url": "/documentation/accelerate/la_retain-c.macro"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_vector_from_double_buffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_vector_from_double_buffer",
      "type": "topic",
      "url": "/documentation/accelerate/la_vector_from_double_buffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer_nocopy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_vector_from_double_buffer_nocopy"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer_nocopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_vector_from_double_buffer_nocopy",
      "type": "topic",
      "url": "/documentation/accelerate/la_vector_from_double_buffer_nocopy"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_vector_from_float_buffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_vector_from_float_buffer",
      "type": "topic",
      "url": "/documentation/accelerate/la_vector_from_float_buffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer_nocopy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_vector_from_float_buffer_nocopy"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer_nocopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_vector_from_float_buffer_nocopy",
      "type": "topic",
      "url": "/documentation/accelerate/la_vector_from_float_buffer_nocopy"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/la_vector_reverse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "la_vector_reverse"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/la_vector_reverse",
      "kind": "symbol",
      "role": "symbol",
      "title": "la_vector_reverse",
      "type": "topic",
      "url": "/documentation/accelerate/la_vector_reverse"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/veclib": {
      "abstract": [
        {
          "text": "Perform computations on large vectors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/veclib",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vecLib",
      "type": "topic",
      "url": "/documentation/accelerate/veclib"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/LA_ATTRIBUTE_ENABLE_LOGGING",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_AVAILABILITY",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_CONST",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_DEFAULT_ATTRIBUTES",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_DIMENSION_MISMATCH_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_EXPORT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_DIAGONALLY_DOMINANT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_POSITIVE_DEFINITE",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FEATURE_SYMMETRIC",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_FUNCTION",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_INTERNAL_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_INVALID_PARAMETER_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_L1_NORM",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_L2_NORM",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_LINF_NORM",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_NONNULL1",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_NOTHROW",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_NO_HINT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_PRECISION_MISMATCH_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_RETURNS_RETAINED",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_DOUBLE",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SCALAR_TYPE_FLOAT",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_DIAGONAL",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_LOWER_TRIANGULAR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SHAPE_UPPER_TRIANGULAR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SINGULAR_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SLICE_OUT_OF_BOUNDS_ERROR",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_SUCCESS",
        "doc://com.apple.accelerate/documentation/Accelerate/LA_WARNING_POORLY_CONDITIONED",
        "doc://com.apple.accelerate/documentation/Accelerate/USE_NON_APPLE_STANDARD_DATATYPES",
        "doc://com.apple.accelerate/documentation/Accelerate/la_release-c.macro",
        "doc://com.apple.accelerate/documentation/Accelerate/la_retain-c.macro",
        "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer",
        "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_double_buffer_nocopy",
        "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer",
        "doc://com.apple.accelerate/documentation/Accelerate/la_vector_from_float_buffer_nocopy",
        "doc://com.apple.accelerate/documentation/Accelerate/la_vector_reverse"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SLICE_OUT_OF_BOUNDS_ERROR/title",
          "value": "LA_SLICE_OUT_OF_BOUNDS_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SLICE_OUT_OF_BOUNDS_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SLICE_OUT_OF_BOUNDS_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_LOWER_TRIANGULAR/title",
          "value": "LA_SHAPE_LOWER_TRIANGULAR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_LOWER_TRIANGULAR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SHAPE_LOWER_TRIANGULAR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SCALAR_TYPE_FLOAT/title",
          "value": "LA_SCALAR_TYPE_FLOAT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SCALAR_TYPE_FLOAT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SCALAR_TYPE_FLOAT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DEFAULT_ATTRIBUTES/title",
          "value": "LA_DEFAULT_ATTRIBUTES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DEFAULT_ATTRIBUTES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_DEFAULT_ATTRIBUTES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INVALID_PARAMETER_ERROR/title",
          "value": "LA_INVALID_PARAMETER_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INVALID_PARAMETER_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_INVALID_PARAMETER_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_DIAGONALLY_DOMINANT/title",
          "value": "LA_FEATURE_DIAGONALLY_DOMINANT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_DIAGONALLY_DOMINANT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_DIAGONALLY_DOMINANT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SINGULAR_ERROR/title",
          "value": "LA_SINGULAR_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SINGULAR_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SINGULAR_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_WARNING_POORLY_CONDITIONED/title",
          "value": "LA_WARNING_POORLY_CONDITIONED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_WARNING_POORLY_CONDITIONED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_WARNING_POORLY_CONDITIONED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SCALAR_TYPE_DOUBLE/title",
          "value": "LA_SCALAR_TYPE_DOUBLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SCALAR_TYPE_DOUBLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SCALAR_TYPE_DOUBLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_DIAGONAL/title",
          "value": "LA_SHAPE_DIAGONAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_DIAGONAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SHAPE_DIAGONAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SUCCESS/title",
          "value": "LA_SUCCESS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SUCCESS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SUCCESS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_PRECISION_MISMATCH_ERROR/title",
          "value": "LA_PRECISION_MISMATCH_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_PRECISION_MISMATCH_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_PRECISION_MISMATCH_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INTERNAL_ERROR/title",
          "value": "LA_INTERNAL_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_INTERNAL_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_INTERNAL_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1USE_NON_APPLE_STANDARD_DATATYPES/title",
          "value": "USE_NON_APPLE_STANDARD_DATATYPES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1USE_NON_APPLE_STANDARD_DATATYPES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "USE_NON_APPLE_STANDARD_DATATYPES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L1_NORM/title",
          "value": "LA_L1_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L1_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_L1_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_UPPER_TRIANGULAR/title",
          "value": "LA_SHAPE_UPPER_TRIANGULAR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_SHAPE_UPPER_TRIANGULAR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_SHAPE_UPPER_TRIANGULAR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_ATTRIBUTE_ENABLE_LOGGING/title",
          "value": "LA_ATTRIBUTE_ENABLE_LOGGING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_ATTRIBUTE_ENABLE_LOGGING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_ATTRIBUTE_ENABLE_LOGGING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_NO_HINT/title",
          "value": "LA_NO_HINT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_NO_HINT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_NO_HINT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_POSITIVE_DEFINITE/title",
          "value": "LA_FEATURE_POSITIVE_DEFINITE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_POSITIVE_DEFINITE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_POSITIVE_DEFINITE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_LINF_NORM/title",
          "value": "LA_LINF_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_LINF_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_LINF_NORM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_SYMMETRIC/title",
          "value": "LA_FEATURE_SYMMETRIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_FEATURE_SYMMETRIC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_FEATURE_SYMMETRIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DIMENSION_MISMATCH_ERROR/title",
          "value": "LA_DIMENSION_MISMATCH_ERROR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_DIMENSION_MISMATCH_ERROR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_DIMENSION_MISMATCH_ERROR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L2_NORM/title",
          "value": "LA_L2_NORM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1LA_L2_NORM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LA_L2_NORM"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
