{
  "abstract": [
    {
      "text": "For each vector element, calculates the absolute value of ",
      "type": "text"
    },
    {
      "code": "v",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vfabf(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vfabf",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vfabf"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vFloat",
        "text": "vFloat"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vFloat",
        "text": "vFloat"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vfabf"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "name": "macOS",
        "renamed": "vfabsf(_:)",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vfabf(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vfabf"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vFloat",
              "text": "vFloat"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vFloat",
              "text": "vFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vFloat": {
      "abstract": [
        {
          "text": "A 128-bit vector packed with ",
          "type": "text"
        },
        {
          "code": "float",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vFloat"
        }
      ],
      "role": "symbol",
      "title": "vFloat",
      "type": "topic",
      "url": "/documentation/accelerate/vfloat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vceilf(_:)": {
      "abstract": [
        {
          "text": "Computes the ceiling of values in a vector of floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vceilf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vceilf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vceilf"
        }
      ],
      "role": "symbol",
      "title": "vceilf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vceilf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vcopysignf(_:_:)": {
      "abstract": [
        {
          "text": "For each vector element, produces a value with the magnitude of ",
          "type": "text"
        },
        {
          "code": "arg2",
          "type": "codeVoice"
        },
        {
          "text": " and sign ",
          "type": "text"
        },
        {
          "code": "arg1",
          "type": "codeVoice"
        },
        {
          "text": ".  Note that the order of the arguments matches the recommendation of the IEEE 754 floating-point standard, which is opposite from the SANE copysign function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vcopysignf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vcopysignf(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vcopysignf"
        }
      ],
      "role": "symbol",
      "title": "vcopysignf(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vcopysignf(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vdivf(_:_:)": {
      "abstract": [
        {
          "text": "For each vector element, calculates ",
          "type": "text"
        },
        {
          "code": "A",
          "type": "codeVoice"
        },
        {
          "text": "/",
          "type": "text"
        },
        {
          "code": "B",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vdivf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vdivf(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vdivf"
        }
      ],
      "role": "symbol",
      "title": "vdivf(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vdivf(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vfabf(_:)": {
      "abstract": [
        {
          "text": "For each vector element, calculates the absolute value of ",
          "type": "text"
        },
        {
          "code": "v",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vfabf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vfabf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vfabf"
        }
      ],
      "role": "symbol",
      "title": "vfabf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vfabf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vfabsf(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vfabsf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vfabsf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vfabsf"
        }
      ],
      "role": "symbol",
      "title": "vfabsf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vfabsf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vfloorf(_:)": {
      "abstract": [
        {
          "text": "Computes the floor of values in a vector of floating-point values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vfloorf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vfloorf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vfloorf"
        }
      ],
      "role": "symbol",
      "title": "vfloorf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vfloorf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vintf(_:)": {
      "abstract": [
        {
          "text": "Truncates the decimal portion of a vector of floating-point values.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vintf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vintf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vintf"
        }
      ],
      "role": "symbol",
      "title": "vintf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vintf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vnextafterf(_:_:)": {
      "abstract": [
        {
          "text": "For each vector element, calculates the next representable value after ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " in the direction of ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": ".  If ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " is equal to ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": ", then ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": " is returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vnextafterf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vnextafterf(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vnextafterf"
        }
      ],
      "role": "symbol",
      "title": "vnextafterf(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vnextafterf(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vnintf(_:)": {
      "abstract": [
        {
          "text": "Rounds to the nearest integer (nearest even for ties).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vnintf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vnintf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vnintf"
        }
      ],
      "role": "symbol",
      "title": "vnintf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vnintf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vrecf(_:)": {
      "abstract": [
        {
          "text": "Computes the reciprocal of values in a vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vrecf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vrecf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vrecf"
        }
      ],
      "role": "symbol",
      "title": "vrecf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vrecf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vrsqrtf(_:)": {
      "abstract": [
        {
          "text": "For each vector element, calculates the inverse of the square root of ",
          "type": "text"
        },
        {
          "code": "X",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vrsqrtf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vrsqrtf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vrsqrtf"
        }
      ],
      "role": "symbol",
      "title": "vrsqrtf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vrsqrtf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vsqrtf(_:)": {
      "abstract": [
        {
          "text": "For each vector element, calculates the square root of ",
          "type": "text"
        },
        {
          "code": "X",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vsqrtf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vsqrtf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vsqrtf"
        }
      ],
      "role": "symbol",
      "title": "vsqrtf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vsqrtf(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vtablelookup(_:_:)": {
      "abstract": [
        {
          "text": "For each vector element of ",
          "type": "text"
        },
        {
          "code": "Index_Vect",
          "type": "codeVoice"
        },
        {
          "text": ", returns the corresponding value from ",
          "type": "text"
        },
        {
          "code": "Table",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vtablelookup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vtablelookup(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vtablelookup"
        }
      ],
      "role": "symbol",
      "title": "vtablelookup(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vtablelookup(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vtruncf(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vtruncf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vFloat",
          "text": "vFloat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vtruncf(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vtruncf"
        }
      ],
      "role": "symbol",
      "title": "vtruncf(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vtruncf(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Floating-Point-Arithmetic-and-Auxiliary-Functions-from-vfph",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vceilf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vcopysignf(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vdivf(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vfabsf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vfloorf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vintf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vnintf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vnextafterf(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vrecf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vrsqrtf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vsqrtf(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vtablelookup(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vtruncf(_:)"
      ],
      "title": "Floating-Point Arithmetic and Auxiliary Functions (from vfp.h)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vfabf"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vfabf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Floating-Point-Arithmetic-and-Auxiliary-Functions-from-vfph",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vceilf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vcopysignf(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vdivf(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vfabsf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vfloorf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vintf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vnintf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vnextafterf(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vrecf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vrsqrtf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vsqrtf(_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vtablelookup(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vtruncf(_:)"
              ],
              "title": "Floating-Point Arithmetic and Auxiliary Functions (from vfp.h)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vFloat",
                    "text": "vFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vfabf"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vFloat",
                    "text": "vFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": ""
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vtruncf(_:)/title",
          "value": "vtruncf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vtruncf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vtruncf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vrsqrtf(_:)/title",
          "value": "vrsqrtf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vrsqrtf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vrsqrtf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfabf(_:)/title",
          "value": "vfabf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfabf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vfabf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vdivf(_:_:)/title",
          "value": "vdivf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vdivf(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vdivf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vceilf(_:)/title",
          "value": "vceilf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vceilf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vceilf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vintf(_:)/title",
          "value": "vintf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vintf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vintf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vFloat/title",
          "value": "vFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vFloat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vrecf(_:)/title",
          "value": "vrecf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vrecf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vrecf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vnintf(_:)/title",
          "value": "vnintf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vnintf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vnintf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vsqrtf(_:)/title",
          "value": "vsqrtf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vsqrtf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vsqrtf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vtablelookup(_:_:)/title",
          "value": "vtablelookup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vtablelookup(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vtablelookup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfloorf(_:)/title",
          "value": "vfloorf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfloorf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vfloorf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vcopysignf(_:_:)/title",
          "value": "vcopysignf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vcopysignf(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vcopysignf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfabsf(_:)/title",
          "value": "vfabsf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vfabsf(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vfabsf"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vnextafterf(_:_:)/title",
          "value": "vnextafterf"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vnextafterf(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vnextafterf"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vfabf(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vfabf(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
