{"sections":[],"variants":[{"paths":["/documentation/accelerate/vimageoverwritechannels_argb8888(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/vimageoverwritechannels_argb8888(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImageOverwriteChannels_ARGB8888"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"s:SP","text":"UnsafePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@vImage_Flags","text":"vImage_Flags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@vImage_Error","text":"vImage_Error","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"vImageOverwriteChannels_ARGB8888","kind":"identifier"}],"externalID":"c:@F@vImageOverwriteChannels_ARGB8888","title":"vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)","symbolKind":"func","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"5.0"},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"5.0"},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.4"},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"5.0"},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"},{"name":"watchOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0"}],"role":"symbol","roleHeading":"Function","modules":[{"name":"Accelerate"}]},"kind":"symbol","seeAlsoSections":[{"anchor":"Overwriting-with-another-buffer","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGB8888(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)"],"title":"Overwriting with another buffer","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImageOverwriteChannels_ARGB8888"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"origSrc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"copyMask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s5UInt8V","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags","text":"vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","preciseIdentifier":"c:@T@vImage_Error","text":"vImage_Error"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"parameters":[{"name":"newSrc","content":[{"inlineContent":[{"text":"The source vImage buffer that provides the new channel values.","type":"text"}],"type":"paragraph"}]},{"name":"origSrc","content":[{"inlineContent":[{"text":"The source vImage buffer that provides the original pixel values.","type":"text"}],"type":"paragraph"}]},{"name":"dest","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer to the destination vImage buffer structure. You’re responsible for filling out the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width"},{"type":"text","text":", and "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes"},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}]}]},{"name":"copyMask","content":[{"type":"paragraph","inlineContent":[{"text":"A bitmask that specifies the channel or channels that the function overwrites with the corresponding channel in the ","type":"text"},{"code":"newSrc","type":"codeVoice"},{"text":" parameter. The value ","type":"text"},{"code":"0x8","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"0","type":"codeVoice"},{"text":", the value ","type":"text"},{"code":"0x4","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"1","type":"codeVoice"},{"text":", the value ","type":"text"},{"code":"0x2","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"2","type":"codeVoice"},{"text":", and the value ","type":"text"},{"code":"0x2","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"3","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"flags","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile"},{"type":"text","text":"; otherwise, pass "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags"},{"type":"text","text":"."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","isActive":true,"type":"reference"},{"text":"; otherwise, one of the error codes in ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"kind":"content"},{"mentions":["doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending"],"kind":"mentions"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The following code overwrites channel "},{"code":"0","type":"codeVoice"},{"type":"text","text":" of the source pixels in "},{"code":"pixelBuffer","type":"codeVoice"},{"type":"text","text":" with the corresponding source pixels from "},{"code":"newSource","type":"codeVoice"},{"type":"text","text":":"}],"type":"paragraph"},{"syntax":"swift","code":["let pixelBuffer = vImage.PixelBuffer<vImage.Interleaved8x4>(","    pixelValues: [10, 20, 30, 40,","                  50, 60, 70, 80],","    size: .init(width: 1, height: 2))","","let newSource = vImage.PixelBuffer<vImage.Planar8>(","    pixelValues: [101,","                  105],","    size: .init(width: 1, height: 2))","","pixelBuffer.withUnsafePointerToVImageBuffer { buf in","    newSource.withUnsafePointerToVImageBuffer { new in","        _ = vImageOverwriteChannels_ARGB8888(new,","                                             buf,","                                             buf,","                                             0x8,","                                             vImage_Flags(kvImageNoFlags))","    }","}","","// Prints:","//      \"[101, 20, 30, 40,","//        105, 60, 70, 80]\"","print(pixelBuffer.array)"],"type":"codeListing"}],"kind":"content"}],"abstract":[{"type":"text","text":"Overwrites the channels of an 8-bit-per-channel, 4-channel interleaved buffer with the corresponding pixels of a planar buffer."}],"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGB8888(_:_:_:_:_:)":{"type":"topic","role":"symbol","url":"/documentation/accelerate/vimageselectchannels_argb8888(_:_:_:_:_:)","kind":"symbol","title":"vImageSelectChannels_ARGB8888(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageSelectChannels_ARGB8888","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@vImage_Flags","kind":"typeIdentifier","text":"vImage_Flags"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@vImage_Error","kind":"typeIdentifier","text":"vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImageSelectChannels_ARGB8888"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGB8888(_:_:_:_:_:)","abstract":[{"type":"text","text":"Overwrites the channels of an 8-bit-per-channel, 4-channel interleaved buffer with the specified channels of the corresponding pixels of a second buffer."}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s5UInt8V":{"abstract":[{"text":"An 8-bit unsigned integer value type.","type":"text"}],"type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt8"}],"title":"UInt8","identifier":"doc://com.externally.resolved.symbol/s:s5UInt8V","kind":"symbol","url":"/documentation/Swift/UInt8","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending":{"title":"Compositing images with alpha blending","identifier":"doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending","role":"article","kind":"article","url":"/documentation/accelerate/compositing-images-with-alpha-blending","abstract":[{"type":"text","text":"Combine two images by using alpha blending to create a single output."}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError":{"url":"/documentation/accelerate/kvimagenoerror","navigatorTitle":[{"text":"kvImageNoError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageNoError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"text":"The vImage function completed without error.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","title":"kvImageNoError","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)","title":"vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)","url":"/documentation/accelerate/vimageselectchannels_argbffff(_:_:_:_:_:)","abstract":[{"text":"Overwrites the channels of a floating-point 32-bit-per-channel, 4-channel interleaved buffer with the specified channels of the corresponding pixels of a second buffer.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageSelectChannels_ARGBFFFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImageSelectChannels_ARGBFFFF"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags":{"navigatorTitle":[{"kind":"identifier","text":"vImage_Flags"}],"type":"topic","abstract":[{"text":"A type for processing options.","type":"text"}],"url":"/documentation/accelerate/vimage_flags","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Flags"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","title":"vImage_Flags"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height":{"navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","kind":"symbol","role":"symbol","url":"/documentation/accelerate/vimage_buffer/height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vImagePixelCount","text":"vImagePixelCount"}],"type":"topic","title":"height","abstract":[{"type":"text","text":"The height of the image, in pixels."}]},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags":{"abstract":[{"text":"A flag that sets the behavior to the default.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kvImageNoFlags"}],"title":"kvImageNoFlags","type":"topic","kind":"symbol","url":"/documentation/accelerate/kvimagenoflags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageNoFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants":{"abstract":[{"text":"Look up type aliases, data types, and constants the vImage library uses.","type":"text"}],"role":"article","identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","kind":"article","type":"topic","url":"/documentation/Accelerate/data-types-and-constants","title":"Data Types and Constants"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImagePixelCount","preciseIdentifier":"c:@T@vImagePixelCount"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","url":"/documentation/accelerate/vimage_buffer/width","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"title":"width","role":"symbol","abstract":[{"text":"The width of the image, in pixels.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)":{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)","url":"/documentation/accelerate/vimageoverwritechannels_argb8888(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageOverwriteChannels_ARGB8888","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error"}],"type":"topic","kind":"symbol","abstract":[{"text":"Overwrites the channels of an 8-bit-per-channel, 4-channel interleaved buffer with the corresponding pixels of a planar buffer.","type":"text"}],"title":"vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"vImageOverwriteChannels_ARGB8888"}],"role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile":{"navigatorTitle":[{"kind":"identifier","text":"kvImageDoNotTile"}],"type":"topic","abstract":[{"text":"A flag that disables vImage internal tiling routines.","type":"text"}],"url":"/documentation/accelerate/kvimagedonottile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageDoNotTile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","title":"kvImageDoNotTile"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes":{"navigatorTitle":[{"text":"rowBytes","kind":"identifier"}],"type":"topic","abstract":[{"text":"The distance, in bytes, between the start of one pixel row and the next in an image, including any unused space between them.","type":"text"}],"url":"/documentation/accelerate/vimage_buffer/rowbytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","title":"rowBytes"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","url":"/documentation/accelerate/vimage_error","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImage_Error"}],"title":"vImage_Error","abstract":[{"text":"A type for image errors.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)":{"type":"topic","role":"symbol","url":"/documentation/accelerate/vimageoverwritechannels_argbffff(_:_:_:_:_:)","kind":"symbol","title":"vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageOverwriteChannels_ARGBFFFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":", "},{"text":"vImage_Flags","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"text":"vImageOverwriteChannels_ARGBFFFF","kind":"identifier"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)","abstract":[{"type":"text","text":"Overwrites the channels of a floating-point 32-bit-per-channel, 4-channel interleaved buffer with the corresponding pixels of a planar buffer."}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer":{"abstract":[{"text":"An image buffer that stores an image’s pixel data, dimensions, and row stride.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Buffer"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"vImage_Buffer"}],"type":"topic","url":"/documentation/accelerate/vimage_buffer","title":"vImage_Buffer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"5.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"5.0"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.4"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"5.0"},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0"},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Function","op":"replace"},{"path":"/metadata/title","value":"vImageOverwriteChannels_ARGB8888","op":"replace"},{"path":"/metadata/symbolKind","value":"func","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"vImageOverwriteChannels_ARGB8888"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Overwriting-with-another-buffer","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGB8888(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)"],"generated":true,"title":"Overwriting with another buffer"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"preciseIdentifier":"c:@T@vImage_Error","text":"vImage_Error","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error"},{"text":" ","kind":"text"},{"text":"vImageOverwriteChannels_ARGB8888","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"newSrc","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"origSrc","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"dest","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"copyMask","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@vImage_Flags","text":"vImage_Flags","kind":"typeIdentifier","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags"},{"text":" ","kind":"text"},{"text":"flags","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The source vImage buffer that provides the new channel values."}],"type":"paragraph"}],"name":"newSrc"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The source vImage buffer that provides the original pixel values.","type":"text"}]}],"name":"origSrc"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer to the destination vImage buffer structure. You’re responsible for filling out the "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","isActive":true,"type":"reference"},{"type":"text","text":", "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","isActive":true,"type":"reference"},{"type":"text","text":", and "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","isActive":true,"type":"reference"},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}]}],"name":"dest"},{"content":[{"inlineContent":[{"text":"A bitmask that specifies the channel or channels that the function overwrites with the corresponding channel in the ","type":"text"},{"code":"newSrc","type":"codeVoice"},{"text":" parameter. The value ","type":"text"},{"code":"0x8","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"0","type":"codeVoice"},{"text":", the value ","type":"text"},{"code":"0x4","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"1","type":"codeVoice"},{"text":", the value ","type":"text"},{"code":"0x2","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"2","type":"codeVoice"},{"text":", and the value ","type":"text"},{"code":"0x2","type":"codeVoice"},{"text":" represents channel ","type":"text"},{"code":"3","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"copyMask"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","type":"reference","isActive":true},{"type":"text","text":"; otherwise, pass "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","type":"reference","isActive":true},{"type":"text","text":"."}]}],"name":"flags"}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","type":"reference","isActive":true},{"type":"text","text":"; otherwise, one of the error codes in "},{"identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"kind":"content"}},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageSelectChannels_ARGB8888(_:_:_:_:_:)/title","value":"vImageSelectChannels_ARGB8888"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageSelectChannels_ARGB8888(_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"vImageSelectChannels_ARGB8888"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title","value":"kvImageNoError"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments","value":[{"kind":"identifier","text":"kvImageNoError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)/title","value":"vImageSelectChannels_ARGBFFFF"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageSelectChannels_ARGBFFFF(_:_:_:_:_:)/fragments","value":[{"text":"vImageSelectChannels_ARGBFFFF","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/title","value":"vImage_Flags"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/fragments","value":[{"kind":"identifier","text":"vImage_Flags"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/navigatorTitle","value":[{"text":"vImage_Flags","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/title","value":"height"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/title","value":"kvImageNoFlags"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/fragments","value":[{"text":"kvImageNoFlags","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/title","value":"width"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/fragments","value":[{"text":"width","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)/title","value":"vImageOverwriteChannels_ARGB8888"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageOverwriteChannels_ARGB8888(_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"vImageOverwriteChannels_ARGB8888"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/title","value":"kvImageDoNotTile"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/fragments","value":[{"kind":"identifier","text":"kvImageDoNotTile"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/title","value":"rowBytes"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/fragments","value":[{"kind":"identifier","text":"rowBytes"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/title","value":"vImage_Error"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/fragments","value":[{"text":"vImage_Error","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/navigatorTitle","value":[{"kind":"identifier","text":"vImage_Error"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)/title","value":"vImageOverwriteChannels_ARGBFFFF"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageOverwriteChannels_ARGBFFFF(_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"vImageOverwriteChannels_ARGBFFFF"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/title","value":"vImage_Buffer"},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/fragments","value":[{"kind":"identifier","text":"vImage_Buffer"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/navigatorTitle","value":[{"text":"vImage_Buffer","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}