{"identifier":{"url":"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Performs premultiplied alpha compositing of two 8-bit-per-channel, 4-channel interleaved buffers and applies an extra alpha value to the top buffer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGB8888"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"srcTop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","identifier":"doc://com.externally.resolved.symbol/s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"constAlpha"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8","identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_8","text":"Pixel_8"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"srcBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","identifier":"doc://com.externally.resolved.symbol/s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","text":"vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","text":"vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags","text":"vImage_Flags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error","text":"vImage_Error","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},{"kind":"parameters","parameters":[{"name":"srcTop","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The vImage buffer that provides the source top image."}]}]},{"name":"constAlpha","content":[{"inlineContent":[{"type":"text","text":"The constant alpha value that the function applies to the top image."}],"type":"paragraph"}]},{"name":"srcBottom","content":[{"inlineContent":[{"type":"text","text":"The vImage buffer that provides the source bottom image."}],"type":"paragraph"}]},{"name":"dest","content":[{"inlineContent":[{"text":"A pointer to the destination vImage buffer structure. You’re responsible for filling out the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","type":"reference"},{"text":", ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","type":"reference"},{"text":", and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","type":"reference"},{"text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks.","type":"text"}],"type":"paragraph"}]},{"name":"flags","content":[{"inlineContent":[{"text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","isActive":true,"type":"reference"},{"text":"; otherwise, pass ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","isActive":true,"type":"reference"},{"text":"; otherwise, one of the error codes in ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]},{"kind":"mentions","mentions":["doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending"]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"On return of this function, the value of each pixel in the destination buffer is:","type":"text"}],"type":"paragraph"},{"syntax":"objc","code":["uint8_t destAlpha =  (srcTopAlpha * constAlpha * 255 + (255*255 - srcTopAlpha * constAlpha) * srcBottomAlpha + 127*255 ) / (255*255);","uint8_t destColor = (srcTopColor * constAlpha * 255  + (255*255 - srcTopAlpha * constAlpha) * srcBottomColor + 127*255) / (255*255);"],"type":"codeListing"}]}],"sections":[],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending"]},{"generated":true,"anchor":"Performing-premultiplied-alpha-compositing-with-a-single-alpha-value","title":"Performing premultiplied alpha compositing with a single alpha value","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"vImagePremultipliedConstAlphaBlend_ARGB8888","kind":"identifier"}],"externalID":"c:@F@vImagePremultipliedConstAlphaBlend_ARGB8888","role":"symbol","roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImagePremultipliedConstAlphaBlend_ARGB8888","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"Pixel_8","preciseIdentifier":"c:@T@Pixel_8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error","kind":"typeIdentifier"}],"symbolKind":"func","title":"vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)","modules":[{"name":"Accelerate"}],"platforms":[{"name":"iOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"10.4","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false}]},"variants":[{"paths":["/documentation/accelerate/vimagepremultipliedconstalphablend_argb8888(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/vimagepremultipliedconstalphablend_argb8888(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"vImagePremultipliedConstAlphaBlend_ARGB8888","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"Pixel_8","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGB8888"}],"title":"vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)","role":"symbol","url":"/documentation/accelerate/vimagepremultipliedconstalphablend_argb8888(_:_:_:_:_:)","abstract":[{"text":"Performs premultiplied alpha compositing of two 8-bit-per-channel, 4-channel interleaved buffers and applies an extra alpha value to the top buffer.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/Pixel_8":{"abstract":[{"text":"A type for a planar, 8-bits-per-channel, unsigned pixel.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Pixel_8"}],"navigatorTitle":[{"kind":"identifier","text":"Pixel_8"}],"title":"Pixel_8","identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_8","kind":"symbol","url":"/documentation/accelerate/pixel_8","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height":{"navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","kind":"symbol","role":"symbol","url":"/documentation/accelerate/vimage_buffer/height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vImagePixelCount","text":"vImagePixelCount"}],"type":"topic","title":"height","abstract":[{"type":"text","text":"The height of the image, in pixels."}]},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError":{"url":"/documentation/accelerate/kvimagenoerror","navigatorTitle":[{"text":"kvImageNoError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageNoError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"text":"The vImage function completed without error.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","title":"kvImageNoError","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants":{"abstract":[{"text":"Look up type aliases, data types, and constants the vImage library uses.","type":"text"}],"role":"article","identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","kind":"article","type":"topic","url":"/documentation/Accelerate/data-types-and-constants","title":"Data Types and Constants"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer":{"abstract":[{"text":"An image buffer that stores an image’s pixel data, dimensions, and row stride.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Buffer"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"vImage_Buffer"}],"type":"topic","url":"/documentation/accelerate/vimage_buffer","title":"vImage_Buffer"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags":{"abstract":[{"text":"A flag that sets the behavior to the default.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kvImageNoFlags"}],"title":"kvImageNoFlags","type":"topic","kind":"symbol","url":"/documentation/accelerate/kvimagenoflags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageNoFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImagePixelCount","preciseIdentifier":"c:@T@vImagePixelCount"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","url":"/documentation/accelerate/vimage_buffer/width","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"title":"width","role":"symbol","abstract":[{"text":"The width of the image, in pixels.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"vImagePremultipliedConstAlphaBlend_ARGBFFFF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"Pixel_F","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_F"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"vImage_Flags","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"text":"vImagePremultipliedConstAlphaBlend_ARGBFFFF","kind":"identifier"}],"title":"vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)","role":"symbol","url":"/documentation/accelerate/vimagepremultipliedconstalphablend_argbffff(_:_:_:_:_:)","abstract":[{"text":"Performs premultiplied alpha compositing of two 32-bit-per-channel, 4-channel interleaved buffers and applies an extra alpha value to the top buffer.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes":{"navigatorTitle":[{"text":"rowBytes","kind":"identifier"}],"type":"topic","abstract":[{"text":"The distance, in bytes, between the start of one pixel row and the next in an image, including any unused space between them.","type":"text"}],"url":"/documentation/accelerate/vimage_buffer/rowbytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","title":"rowBytes"},"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"vImagePremultipliedConstAlphaBlend_PlanarF","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"Pixel_F","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_F"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"vImage_Flags","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"text":"vImagePremultipliedConstAlphaBlend_PlanarF","kind":"identifier"}],"title":"vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)","role":"symbol","url":"/documentation/accelerate/vimagepremultipliedconstalphablend_planarf(_:_:_:_:_:_:)","abstract":[{"text":"Performs premultiplied alpha compositing of two 32-bit planar buffers and applies an extra alpha value to the top buffer.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags":{"navigatorTitle":[{"kind":"identifier","text":"vImage_Flags"}],"type":"topic","abstract":[{"text":"A type for processing options.","type":"text"}],"url":"/documentation/accelerate/vimage_flags","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Flags"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","title":"vImage_Flags"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile":{"navigatorTitle":[{"kind":"identifier","text":"kvImageDoNotTile"}],"type":"topic","abstract":[{"text":"A flag that disables vImage internal tiling routines.","type":"text"}],"url":"/documentation/accelerate/kvimagedonottile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageDoNotTile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","title":"kvImageDoNotTile"},"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)":{"type":"topic","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"vImagePremultipliedConstAlphaBlend_Planar8","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"Pixel_8","kind":"typeIdentifier","preciseIdentifier":"c:@T@Pixel_8"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer"},{"text":">, ","kind":"text"},{"text":"vImage_Flags","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error"}],"navigatorTitle":[{"text":"vImagePremultipliedConstAlphaBlend_Planar8","kind":"identifier"}],"title":"vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)","role":"symbol","url":"/documentation/accelerate/vimagepremultipliedconstalphablend_planar8(_:_:_:_:_:_:)","abstract":[{"text":"Performs premultiplied alpha compositing of two 8-bit planar buffers and applies an extra alpha value to the top buffer.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","url":"/documentation/accelerate/vimage_error","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImage_Error"}],"title":"vImage_Error","abstract":[{"text":"A type for image errors.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending":{"title":"Compositing images with alpha blending","identifier":"doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending","role":"article","kind":"article","url":"/documentation/accelerate/compositing-images-with-alpha-blending","abstract":[{"type":"text","text":"Combine two images by using alpha blending to create a single output."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"10.4","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","introducedAt":"5.0","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Function"},{"op":"replace","path":"/metadata/title","value":"vImagePremultipliedConstAlphaBlend_ARGB8888"},{"op":"replace","path":"/metadata/symbolKind","value":"func"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGB8888"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/compositing-images-with-alpha-blending"]},{"title":"Performing premultiplied alpha compositing with a single alpha value","anchor":"Performing-premultiplied-alpha-compositing-with-a-single-alpha-value","generated":true,"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)","doc://com.apple.accelerate/documentation/Accelerate/vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","kind":"typeIdentifier","text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGB8888"},{"kind":"text","text":"("},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"srcTop"},{"kind":"text","text":", "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/Pixel_8","kind":"typeIdentifier","text":"Pixel_8","preciseIdentifier":"c:@T@Pixel_8"},{"kind":"text","text":" "},{"kind":"internalParam","text":"constAlpha"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"srcBottom"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"dest"},{"kind":"text","text":", "},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","kind":"typeIdentifier","text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flags"},{"kind":"text","text":");"}]}],"kind":"declarations"}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The vImage buffer that provides the source top image."}]}],"name":"srcTop"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The constant alpha value that the function applies to the top image."}]}],"name":"constAlpha"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The vImage buffer that provides the source bottom image.","type":"text"}]}],"name":"srcBottom"},{"name":"dest","content":[{"inlineContent":[{"type":"text","text":"A pointer to the destination vImage buffer structure. You’re responsible for filling out the "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","isActive":true},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}],"type":"paragraph"}]},{"name":"flags","content":[{"inlineContent":[{"type":"text","text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","isActive":true},{"type":"text","text":"; otherwise, pass "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError"},{"type":"text","text":"; otherwise, one of the error codes in "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}},{"value":"vImagePremultipliedConstAlphaBlend_ARGB8888","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGB8888"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_ARGB8888(_:_:_:_:_:)/fragments","op":"replace"},{"value":"Pixel_8","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/title","op":"replace"},{"value":[{"kind":"identifier","text":"Pixel_8"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/fragments","op":"replace"},{"value":[{"text":"Pixel_8","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1Pixel_8/navigatorTitle","op":"replace"},{"value":"height","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/title","op":"replace"},{"value":[{"kind":"identifier","text":"height"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/fragments","op":"replace"},{"value":"kvImageNoError","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title","op":"replace"},{"value":[{"kind":"identifier","text":"kvImageNoError"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments","op":"replace"},{"value":"vImage_Buffer","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/title","op":"replace"},{"value":[{"text":"vImage_Buffer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"vImage_Buffer"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/navigatorTitle","op":"replace"},{"value":"kvImageNoFlags","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/title","op":"replace"},{"value":[{"text":"kvImageNoFlags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/fragments","op":"replace"},{"value":"width","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/title","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/fragments","op":"replace"},{"value":"vImagePremultipliedConstAlphaBlend_ARGBFFFF","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)/title","op":"replace"},{"value":[{"kind":"identifier","text":"vImagePremultipliedConstAlphaBlend_ARGBFFFF"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_ARGBFFFF(_:_:_:_:_:)/fragments","op":"replace"},{"value":"rowBytes","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/title","op":"replace"},{"value":[{"kind":"identifier","text":"rowBytes"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/fragments","op":"replace"},{"value":"vImagePremultipliedConstAlphaBlend_PlanarF","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"text":"vImagePremultipliedConstAlphaBlend_PlanarF","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_PlanarF(_:_:_:_:_:_:)/fragments","op":"replace"},{"value":"vImage_Flags","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/title","op":"replace"},{"value":[{"kind":"identifier","text":"vImage_Flags"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"vImage_Flags"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/navigatorTitle","op":"replace"},{"value":"kvImageDoNotTile","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/title","op":"replace"},{"value":[{"kind":"identifier","text":"kvImageDoNotTile"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/fragments","op":"replace"},{"value":"vImagePremultipliedConstAlphaBlend_Planar8","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)/title","op":"replace"},{"value":[{"text":"vImagePremultipliedConstAlphaBlend_Planar8","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePremultipliedConstAlphaBlend_Planar8(_:_:_:_:_:_:)/fragments","op":"replace"},{"value":"vImage_Error","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/title","op":"replace"},{"value":[{"kind":"identifier","text":"vImage_Error"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/fragments","op":"replace"},{"value":[{"text":"vImage_Error","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}