{
  "abstract": [
    {
      "text": "Constants for selecting the interpolation mode",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@vImage_WarpInterpolation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImage_WarpInterpolation"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImage_WarpInterpolation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "vImage_WarpInterpolation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Video Image Format Errors",
      "type": "topic",
      "url": "/documentation/accelerate/1498271-core-video-image-format-errors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods": {
      "abstract": [
        {
          "text": "Specify the dithering method some vImage conversion functions use.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dithering Methods",
      "type": "topic",
      "url": "/documentation/accelerate/1533233-dithering-methods"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes": {
      "abstract": [
        {
          "text": "Error codes that vImage functions return when an operation fails.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Error codes",
      "type": "topic",
      "url": "/documentation/accelerate/1578972-error-codes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags": {
      "abstract": [
        {
          "text": "Set flags on vImage operations to specify processing options.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Processing Flags",
      "type": "topic",
      "url": "/documentation/accelerate/1578976-processing-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/availability-flags": {
      "abstract": [
        {
          "text": "Obtain the availability of particular vImage features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Availability Flags",
      "type": "topic",
      "url": "/documentation/accelerate/availability-flags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/buffer-types": {
      "abstract": [
        {
          "text": "Look up buffer type codes vImage conversions provide.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Buffer Types",
      "type": "topic",
      "url": "/documentation/accelerate/buffer-types"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays": {
      "abstract": [
        {
          "text": "Specify the decode array constant to use with 16Q12-formatted data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decode Arrays",
      "type": "topic",
      "url": "/documentation/accelerate/decode-arrays"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationLinear": {
      "abstract": [
        {
          "text": "Linear interpoation",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInterpolationLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInterpolationLinear"
        }
      ],
      "role": "symbol",
      "title": "kvImageInterpolationLinear",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinterpolationlinear"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationNearest": {
      "abstract": [
        {
          "text": "Nearest neigborhood",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageInterpolationNearest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationNearest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageInterpolationNearest"
        }
      ],
      "role": "symbol",
      "title": "kvImageInterpolationNearest",
      "type": "topic",
      "url": "/documentation/accelerate/kvimageinterpolationnearest"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType": {
      "abstract": [
        {
          "text": "An enumeration of RGB -> Y’CbCr conversion matrix types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "role": "symbol",
      "title": "vImageMatrixType",
      "type": "topic",
      "url": "/documentation/accelerate/vimagematrixtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation": {
      "abstract": [
        {
          "text": "Constants for selecting the interpolation mode",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_WarpInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_WarpInterpolation"
        }
      ],
      "role": "symbol",
      "title": "vImage_WarpInterpolation",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_warpinterpolation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/1578972-error-codes",
        "doc://com.apple.accelerate/documentation/Accelerate/1498271-core-video-image-format-errors",
        "doc://com.apple.accelerate/documentation/Accelerate/1578976-processing-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/1533233-dithering-methods",
        "doc://com.apple.accelerate/documentation/Accelerate/availability-flags",
        "doc://com.apple.accelerate/documentation/Accelerate/decode-arrays",
        "doc://com.apple.accelerate/documentation/Accelerate/buffer-types",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationLinear",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationNearest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImage_WarpInterpolation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationLinear",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImageInterpolationNearest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_WarpInterpolation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/title",
          "value": "vImageMatrixType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInterpolationLinear/title",
          "value": "kvImageInterpolationLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInterpolationLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInterpolationLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/title",
          "value": "vImage_WarpInterpolation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_WarpInterpolation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_WarpInterpolation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInterpolationNearest/title",
          "value": "kvImageInterpolationNearest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageInterpolationNearest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageInterpolationNearest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_warpinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_warpinterpolation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
