{
  "abstract": [
    {
      "text": "Applies a set of piecewise polynomials to transform an 8-bit planar image to a 32-bit planar image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vImagePiecewisePolynomial_Planar8toPlanarF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@vImage_Buffer",
        "text": "vImage_Buffer"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@vImage_Buffer",
        "text": "vImage_Buffer"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">?>, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sf",
        "text": "Float"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vImage_Flags",
        "text": "vImage_Flags"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vImage_Error",
        "text": "vImage_Error"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "src"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@vImage_Buffer",
              "text": "vImage_Buffer"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "dest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@vImage_Buffer",
              "text": "vImage_Buffer"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "coefficients"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">?>, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "boundaries"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sf",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sf",
              "text": "Float"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "order"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "log2segments"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vImage_Flags",
              "text": "vImage_Flags"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vImage_Error",
              "text": "vImage_Error"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The source vImage buffer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "src"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the destination vImage buffer structure. You’re responsible for filling out the ",
                  "type": "text"
                },
                {
                  "code": "height",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "width",
                  "type": "codeVoice"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "code": "rowBytes",
                  "type": "codeVoice"
                },
                {
                  "text": " fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dest"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an array of polynomial coefficient arrays. Each polynomial coefficient array contains the coefficients for one polynomial. A polynomial of order ",
                  "type": "text"
                },
                {
                  "code": "R",
                  "type": "codeVoice"
                },
                {
                  "text": " has ",
                  "type": "text"
                },
                {
                  "code": "R+1",
                  "type": "codeVoice"
                },
                {
                  "text": " coefficients, and all of the polynomials in this array must have the same order.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Order the coefficients from the zeroth-order term to the highest order term. For example, the function evaluates the coefficients ",
                  "type": "text"
                },
                {
                  "code": "[0.5, 0.6, 0.7]",
                  "type": "codeVoice"
                },
                {
                  "text": " as ",
                  "type": "text"
                },
                {
                  "code": "0.5 * x⁰ + 0.6 * x¹ + 0.7 * x²",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "coefficients"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to an array of boundary values, in increasing order, that separates adjacent ranges of pixel values. The first boundary value is the lowest in the range and the function clips input values lower than this to this value. The last boundary value is the highest in the range and the function clips input values higher than this to this value. The boundary values between the first and last separate the subranges from each other.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "boundaries"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The order of the polynomials.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "order"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of polynomials to represent as a base-2 logarithm. If you pass a noninteger power-of-two number of polynomials, round up to the next integer power of two, and repeat the last polynomial the appropriate number of times.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "log2segments"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": "; otherwise, pass ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; otherwise, one of the error codes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can approximate many different correction functions by carefully choosing the polynomials and the ranges of input values they operate on. For example, the sample code project ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " demonstrates how to apply tone curve adjustments to images using polynomial transforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code defines two sets of polynomial coefficients, ",
              "type": "text"
            },
            {
              "code": "coefficients0",
              "type": "codeVoice"
            },
            {
              "text": " as ",
              "type": "text"
            },
            {
              "code": "[0.0, 0.5, 0.0]",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "coefficients1",
              "type": "codeVoice"
            },
            {
              "text": " as ",
              "type": "text"
            },
            {
              "code": "[0.0, 0.0, 1.0].",
              "type": "codeVoice"
            },
            {
              "text": " The boundaries array, ",
              "type": "text"
            },
            {
              "code": "[0, 0.5, 1]",
              "type": "codeVoice"
            },
            {
              "text": ", specifies that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function applies ",
              "type": "text"
            },
            {
              "code": "coefficients0",
              "type": "codeVoice"
            },
            {
              "text": " to source pixels less than ",
              "type": "text"
            },
            {
              "code": "0.5",
              "type": "codeVoice"
            },
            {
              "text": ", and applies ",
              "type": "text"
            },
            {
              "code": "coefficients1",
              "type": "codeVoice"
            },
            {
              "text": " to other pixels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Note that the boundaries array contains three elements that define two ranges: ",
              "type": "text"
            },
            {
              "code": "0..<0.5",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "0.5...1",
              "type": "codeVoice"
            },
            {
              "text": ". The ",
              "type": "text"
            },
            {
              "code": "order",
              "type": "codeVoice"
            },
            {
              "text": " value equals the number of coefficients in each segment minus one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let source = vImage.PixelBuffer<vImage.Planar8>(",
            "    pixelValues: [0, 0.2, 0.4, 0.6, 0.8, 1].map { Pixel_8($0 * 255) },",
            "    size: vImage.Size(width: 6, height: 1))",
            "",
            "let destination = vImage.PixelBuffer<vImage.PlanarF>(",
            "    size: source.size)",
            "",
            "let coefficients0: [Float] = [0.0, 0.5, 0.0] // 0.0 * x⁰ + 0.5 * x¹ + 0.0 * x²",
            "let coefficients1: [Float] = [0.0, 0.0, 1.0] // 0.0 * x⁰ + 0.0 * x¹ + 1.0 * x²",
            "",
            "let boundaries: [Float] = [0, 0.5, 1]",
            "",
            "let order = UInt32(2)",
            "",
            "let log2segments = UInt32(1)",
            "",
            "coefficients0.withUnsafeBufferPointer { coefficients0Ptr in",
            "    coefficients1.withUnsafeBufferPointer { coefficients1Ptr in",
            "        source.withUnsafePointerToVImageBuffer { src in",
            "            destination.withUnsafePointerToVImageBuffer { dest in",
            "                ",
            "                var coeffs = [ coefficients0Ptr.baseAddress,",
            "                               coefficients1Ptr.baseAddress ]",
            "                ",
            "                vImagePiecewisePolynomial_Planar8toPlanarF(",
            "                    src,",
            "                    dest,",
            "                    &coeffs,",
            "                    boundaries,",
            "                    order,",
            "                    log2segments,",
            "                    vImage_Flags(kvImageNoFlags))",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "On return, the destination buffer contains the values ",
              "type": "text"
            },
            {
              "code": "[0.0, 0.1, 0.2, 0.36, 0.64, 1.0]",
              "type": "codeVoice"
            },
            {
              "text": ". This is equivalent to the following scalar code:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let result = source.array.map {",
            "    let x = Float($0) / 255",
            "    let coefficients = x < 0.5 ? coefficients0 : coefficients1",
            "    return coefficients[0] * pow(x, 0) +",
            "           coefficients[1] * pow(x, 1) +",
            "           coefficients[2] * pow(x, 2)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For best performance, choose a single higher-order polynomial over many lower-order polynomials. However, this function uses single-precision arithmetic, and large high-order coefficients may cause rounding errors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images": {
      "abstract": [
        {
          "text": "Use the vImage library’s polynomial transform to apply tone curve adjustments to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying tone curve adjustments to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-tone-curve-adjustments-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile": {
      "abstract": [
        {
          "text": "A flag that disables vImage internal tiling routines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageDoNotTile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageDoNotTile"
        }
      ],
      "role": "symbol",
      "title": "kvImageDoNotTile",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagedonottile"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError": {
      "abstract": [
        {
          "text": "The vImage function completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageNoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenoerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags": {
      "abstract": [
        {
          "text": "A flag that sets the behavior to the default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNoFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNoFlags"
        }
      ],
      "role": "symbol",
      "title": "kvImageNoFlags",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenoflags"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a set of piecewise polynomials to transform an 8-bit planar image to a 32-bit planar image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagepiecewisepolynomial_planar8toplanarf(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a set of piecewise polynomials to transform a 32-bit planar image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_PlanarF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_PlanarF"
        }
      ],
      "role": "symbol",
      "title": "vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagepiecewisepolynomial_planarf(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a set of piecewise polynomials to transform a 32-bit planar image to an 8-bit planar image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_PlanarFtoPlanar8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImagePiecewisePolynomial_PlanarFtoPlanar8"
        }
      ],
      "role": "symbol",
      "title": "vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagepiecewisepolynomial_planarftoplanar8(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer": {
      "abstract": [
        {
          "text": "An image buffer that stores an image’s pixel data, dimensions, and row stride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_Buffer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_Buffer"
        }
      ],
      "role": "symbol",
      "title": "vImage_Buffer",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_buffer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error": {
      "abstract": [
        {
          "text": "A type for image errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_Error"
        }
      ],
      "role": "symbol",
      "title": "vImage_Error",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_error"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags": {
      "abstract": [
        {
          "text": "A type for processing options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_Flags"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_Flags"
        }
      ],
      "role": "symbol",
      "title": "vImage_Flags",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_flags"
    },
    "doc://com.apple.documentation/documentation/Accelerate/applying-tone-curve-adjustments-to-images": {
      "abstract": [
        {
          "text": "Use the vImage library’s polynomial transform to apply tone curve adjustments to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Applying tone curve adjustments to images",
      "type": "topic",
      "url": "/documentation/Accelerate/applying-tone-curve-adjustments-to-images"
    },
    "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants": {
      "abstract": [
        {
          "text": "Look up type aliases, data types, and constants the vImage library uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
      "kind": "article",
      "role": "article",
      "title": "Data Types and Constants",
      "type": "topic",
      "url": "/documentation/Accelerate/data-types-and-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sf": {
      "abstract": [
        {
          "text": "A single-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sf",
      "kind": "symbol",
      "role": "symbol",
      "title": "Float",
      "type": "topic",
      "url": "/documentation/Swift/Float"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-a-polynomial",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/applying-tone-curve-adjustments-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)"
      ],
      "title": "Applying a polynomial"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImagePiecewisePolynomial_Planar8toPlanarF"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Applying-a-polynomial",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)"
              ],
              "title": "Applying a polynomial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vImage_Error",
                    "text": "vImage_Error"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@vImage_Buffer",
                    "text": "vImage_Buffer"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "src"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@vImage_Buffer",
                    "text": "vImage_Buffer"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dest"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " * * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "coefficients"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:f",
                    "text": "float"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "boundaries"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "order"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "log2segments"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vImage_Flags",
                    "text": "vImage_Flags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The source vImage buffer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "src"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to the destination vImage buffer structure. You’re responsible for filling out the ",
                        "type": "text"
                      },
                      {
                        "code": "height",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "code": "width",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", and ",
                        "type": "text"
                      },
                      {
                        "code": "rowBytes",
                        "type": "codeVoice"
                      },
                      {
                        "text": " fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dest"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an array of polynomial coefficient arrays. Each polynomial coefficient array contains the coefficients for one polynomial. A polynomial of order ",
                        "type": "text"
                      },
                      {
                        "code": "R",
                        "type": "codeVoice"
                      },
                      {
                        "text": " has ",
                        "type": "text"
                      },
                      {
                        "code": "R+1",
                        "type": "codeVoice"
                      },
                      {
                        "text": " coefficients, and all of the polynomials in this array must have the same order.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Order the coefficients from the zeroth-order term to the highest order term. For example, the function evaluates the coefficients ",
                        "type": "text"
                      },
                      {
                        "code": "[0.5, 0.6, 0.7]",
                        "type": "codeVoice"
                      },
                      {
                        "text": " as ",
                        "type": "text"
                      },
                      {
                        "code": "0.5 * x⁰ + 0.6 * x¹ + 0.7 * x²",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "coefficients"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to an array of boundary values, in increasing order, that separates adjacent ranges of pixel values. The first boundary value is the lowest in the range and the function clips input values lower than this to this value. The last boundary value is the highest in the range and the function clips input values higher than this to this value. The boundary values between the first and last separate the subranges from each other.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "boundaries"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The order of the polynomials.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "order"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of polynomials to represent as a base-2 logarithm. If you pass a noninteger power-of-two number of polynomials, round up to the next integer power of two, and repeat the last polynomial the appropriate number of times.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "log2segments"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": "; otherwise, pass ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "flags"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": "; otherwise, one of the error codes in ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/title",
          "value": "kvImageNoFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNoFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title",
          "value": "kvImageNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/title",
          "value": "kvImageDoNotTile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageDoNotTile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)/title",
          "value": "vImagePiecewisePolynomial_PlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_PlanarF(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImagePiecewisePolynomial_PlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)/title",
          "value": "vImagePiecewisePolynomial_PlanarFtoPlanar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_PlanarFtoPlanar8(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImagePiecewisePolynomial_PlanarFtoPlanar8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)/title",
          "value": "vImagePiecewisePolynomial_Planar8toPlanarF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImagePiecewisePolynomial_Planar8toPlanarF(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImagePiecewisePolynomial_Planar8toPlanarF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/title",
          "value": "vImage_Error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/title",
          "value": "vImage_Buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/title",
          "value": "vImage_Flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Flags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagepiecewisepolynomial_planar8toplanarf(_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimagepiecewisepolynomial_planar8toplanarf(_:_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
