{
  "abstract": [
    {
      "text": "Copies an RGB-to-YpCbCr conversion matrix to an image format’s internal matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vImageCVImageFormat_CopyConversionMatrix",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImageCVImageFormat_CopyConversionMatrix"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
        "text": "vImageCVImageFormat"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SV",
        "text": "UnsafeRawPointer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vImageMatrixType",
        "text": "vImageMatrixType"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vImage_Error",
        "text": "vImage_Error"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImageCVImageFormat_CopyConversionMatrix"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vImageCVImageFormat_CopyConversionMatrix(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CopyConversionMatrix"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "format"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
              "text": "vImageCVImageFormat"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "matrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vImageMatrixType",
              "text": "vImageMatrixType"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vImage_Error",
              "text": "vImage_Error"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The destination ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "format"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix that the function copies to the destination image format.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "matrix"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of the matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "; otherwise, one of the error codes in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError": {
      "abstract": [
        {
          "text": "The vImage function completed without error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImageNoError"
        }
      ],
      "role": "symbol",
      "title": "kvImageNoError",
      "type": "topic",
      "url": "/documentation/accelerate/kvimagenoerror"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat": {
      "abstract": [
        {
          "text": "A mutable description of image encoding in a Core Video pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies an RGB-to-YpCbCr conversion matrix to an image format’s internal matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyConversionMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
          "text": "vImageCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageMatrixType",
          "text": "vImageMatrixType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_CopyConversionMatrix(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_CopyConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_CopyConversionMatrix(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_copyconversionmatrix(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the RGB-to-YpCbCr conversion matrix of a Core Video image format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetConversionMatrix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageConstCVImageFormatRef",
          "text": "vImageConstCVImageFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImageMatrixType",
          "text": "vImageMatrixType"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCVImageFormat_GetConversionMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImageCVImageFormat_GetConversionMatrix(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecvimageformat_getconversionmatrix(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType": {
      "abstract": [
        {
          "text": "An enumeration of RGB -> Y’CbCr conversion matrix types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageMatrixType"
        }
      ],
      "role": "symbol",
      "title": "vImageMatrixType",
      "type": "topic",
      "url": "/documentation/accelerate/vimagematrixtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error": {
      "abstract": [
        {
          "text": "A type for image errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_Error"
        }
      ],
      "role": "symbol",
      "title": "vImage_Error",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_error"
    },
    "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants": {
      "abstract": [
        {
          "text": "Look up type aliases, data types, and constants the vImage library uses.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
      "kind": "article",
      "role": "article",
      "title": "Data Types and Constants",
      "type": "topic",
      "url": "/documentation/Accelerate/data-types-and-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-and-setting-the-conversion-matrix",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)"
      ],
      "title": "Querying and setting the conversion matrix"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImageCVImageFormat_CopyConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CopyConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Querying-and-setting-the-conversion-matrix",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat_GetConversionMatrix(_:_:)"
              ],
              "title": "Querying and setting the conversion matrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_Error",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vImage_Error",
                    "text": "vImage_Error"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImageCVImageFormat_CopyConversionMatrix"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vImageCVImageFormatRef",
                    "text": "vImageCVImageFormatRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "format"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "matrix"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageMatrixType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vImageMatrixType",
                    "text": "vImageMatrixType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inType"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The destination ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCVImageFormat",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " instance.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "format"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix that the function copies to the destination image format.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "matrix"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of the matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": "; otherwise, one of the error codes in ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetConversionMatrix(_:_:)/title",
          "value": "vImageCVImageFormat_GetConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_GetConversionMatrix(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_GetConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/title",
          "value": "vImageCVImageFormatRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormatRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyConversionMatrix(_:_:_:)/title",
          "value": "vImageCVImageFormat_CopyConversionMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCVImageFormat_CopyConversionMatrix(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCVImageFormat_CopyConversionMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/title",
          "value": "vImage_Error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_Error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/title",
          "value": "vImageMatrixType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageMatrixType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageMatrixType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title",
          "value": "kvImageNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImageNoError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagecvimageformat_copyconversionmatrix(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimagecvimageformat_copyconversionmatrix(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
