{
  "abstract": [
    {
      "text": "Apply image manipulation operations to vImage buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vimage-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vimage-operations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "title": "vImage Operations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A vImage function name includes the data type of the buffer it operates on. For example, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " works with 8-bit planar buffers, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " works with 32-bits-per-channel, four-channel interleaved buffers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images": {
      "abstract": [
        {
          "text": "Simulate a bokeh effect by applying dilation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding a bokeh effect to images",
      "type": "topic",
      "url": "/documentation/accelerate/adding-a-bokeh-effect-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping": {
      "abstract": [
        {
          "text": "Convert an RGB image to discrete luminance and chrominance channels, and apply color and contrast treatments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adjusting saturation and applying tone mapping",
      "type": "topic",
      "url": "/documentation/accelerate/adjusting-saturation-and-applying-tone-mapping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/alpha-compositing": {
      "abstract": [
        {
          "text": "Composite images together.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/alpha-compositing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Alpha compositing",
      "type": "topic",
      "url": "/documentation/accelerate/alpha-compositing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-a-flood-fill-to-an-image": {
      "abstract": [
        {
          "text": "Fill connected components of an image with a new color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-a-flood-fill-to-an-image",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying a flood fill to an image",
      "type": "topic",
      "url": "/documentation/accelerate/applying-a-flood-fill-to-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images": {
      "abstract": [
        {
          "text": "Translate, rotate, and scale images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying affine transformations to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-affine-transformations-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images": {
      "abstract": [
        {
          "text": "Warp images in three dimensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Applying projective transformations to images",
      "type": "topic",
      "url": "/documentation/accelerate/applying-projective-transformations-to-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image": {
      "abstract": [
        {
          "text": "Filter an image by convolving it with custom and high-speed kernels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image",
      "kind": "article",
      "role": "sampleCode",
      "title": "Blurring an image",
      "type": "topic",
      "url": "/documentation/accelerate/blurring-an-image"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow": {
      "abstract": [
        {
          "text": "Learn the fundamentals of the convert-any-to-any function by converting a CMYK image to an RGB image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
      "kind": "article",
      "role": "article",
      "title": "Building a basic image conversion workflow",
      "type": "topic",
      "url": "/documentation/accelerate/building-a-basic-image-conversion-workflow"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/clipping-data": {
      "abstract": [
        {
          "text": "Clip the pixel values of an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/clipping-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clipping data",
      "type": "topic",
      "url": "/documentation/accelerate/clipping-data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/conversion": {
      "abstract": [
        {
          "text": "Convert an image to a different format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/conversion",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conversion",
      "type": "topic",
      "url": "/documentation/accelerate/conversion"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale": {
      "abstract": [
        {
          "text": "Convert an RGB image to grayscale using matrix multiplication.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale",
      "kind": "article",
      "role": "sampleCode",
      "title": "Converting color images to grayscale",
      "type": "topic",
      "url": "/documentation/accelerate/converting-color-images-to-grayscale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/convolution": {
      "abstract": [
        {
          "text": "Apply a convolution kernel to an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/convolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Convolution",
      "type": "topic",
      "url": "/documentation/accelerate/convolution"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering": {
      "abstract": [
        {
          "text": "Filter data prior to decompression.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Decompression Filtering",
      "type": "topic",
      "url": "/documentation/accelerate/decompression-filtering"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation": {
      "abstract": [
        {
          "text": "Enhance and adjust the contrast of an image with histogram equalization and contrast stretching.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation",
      "kind": "article",
      "role": "article",
      "title": "Enhancing image contrast with histogram manipulation",
      "type": "topic",
      "url": "/documentation/accelerate/enhancing-image-contrast-with-histogram-manipulation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/extracting-channels": {
      "abstract": [
        {
          "text": "Extract one channel from a four-channel interleaved buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/extracting-channels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Extracting channels",
      "type": "topic",
      "url": "/documentation/accelerate/extracting-channels"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/filling-buffers": {
      "abstract": [
        {
          "text": "Fill a buffer with a specified color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/filling-buffers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Filling buffers",
      "type": "topic",
      "url": "/documentation/accelerate/filling-buffers"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images": {
      "abstract": [
        {
          "text": "Share image data between vDSP and vImage to compute the sharpest image from a bracketed photo sequence.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images",
      "kind": "article",
      "role": "sampleCode",
      "title": "Finding the sharpest image in a sequence of captured images",
      "type": "topic",
      "url": "/documentation/accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/flattening-data": {
      "abstract": [
        {
          "text": "Perform an alpha composite of a four-channel image over a solid background color.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/flattening-data",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Flattening data",
      "type": "topic",
      "url": "/documentation/accelerate/flattening-data"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size": {
      "abstract": [
        {
          "text": "Calculate the size of the temporary buffer needed by a high-level geometry functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Getting the Buffer Size",
      "type": "topic",
      "url": "/documentation/accelerate/getting-the-buffer-size"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/histogram": {
      "abstract": [
        {
          "text": "Calculate or manipulate an image’s histogram.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/histogram",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Histogram",
      "type": "topic",
      "url": "/documentation/accelerate/histogram"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-reflection": {
      "abstract": [
        {
          "text": "Reflect images horizontally and vertically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-reflection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image reflection",
      "type": "topic",
      "url": "/documentation/accelerate/image-reflection"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-rotation": {
      "abstract": [
        {
          "text": "Rotate images by arbitrary angles or by multiples of 90 degrees.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-rotation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image rotation",
      "type": "topic",
      "url": "/documentation/accelerate/image-rotation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-scaling": {
      "abstract": [
        {
          "text": "Scale interlaced and planar images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-scaling",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image scaling",
      "type": "topic",
      "url": "/documentation/accelerate/image-scaling"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/image-shearing": {
      "abstract": [
        {
          "text": "Shear images horizontally and vertically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/image-shearing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Image shearing",
      "type": "topic",
      "url": "/documentation/accelerate/image-shearing"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/morphology": {
      "abstract": [
        {
          "text": "Dilate and erode images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/morphology",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Morphology",
      "type": "topic",
      "url": "/documentation/accelerate/morphology"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/overwriting-channels": {
      "abstract": [
        {
          "text": "Overwrite the channels of a buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/overwriting-channels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Overwriting channels",
      "type": "topic",
      "url": "/documentation/accelerate/overwriting-channels"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/permuting-channels": {
      "abstract": [
        {
          "text": "Reorder the channels in an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/permuting-channels",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Permuting Channels",
      "type": "topic",
      "url": "/documentation/accelerate/permuting-channels"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters": {
      "abstract": [
        {
          "text": "Implement custom linear interpolation to prevent the ringing effects associated with scaling an image with the default Lanczos algorithm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
      "kind": "article",
      "role": "sampleCode",
      "title": "Reducing artifacts with custom resampling filters",
      "type": "topic",
      "url": "/documentation/accelerate/reducing-artifacts-with-custom-resampling-filters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage": {
      "abstract": [
        {
          "text": "Learn how vImage resamples image data during geometric operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
      "kind": "article",
      "role": "article",
      "title": "Resampling in vImage",
      "type": "topic",
      "url": "/documentation/accelerate/resampling-in-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage": {
      "abstract": [
        {
          "text": "Calculate the histogram of one image, and apply it to a second image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage",
      "kind": "article",
      "role": "sampleCode",
      "title": "Specifying histograms with vImage",
      "type": "topic",
      "url": "/documentation/accelerate/specifying-histograms-with-vimage"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/swapping-bytes": {
      "abstract": [
        {
          "text": "Byte-swap a buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/swapping-bytes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Swapping bytes",
      "type": "topic",
      "url": "/documentation/accelerate/swapping-bytes"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function": {
      "abstract": [
        {
          "text": "Use gamma functions to apply color transformations to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforming with a gamma function",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-with-a-gamma-function"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-lookup-tables": {
      "abstract": [
        {
          "text": "Use lookup tables to apply color transformations to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-lookup-tables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforming with lookup tables",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-with-lookup-tables"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-matrix-multiplication": {
      "abstract": [
        {
          "text": "Use matrix multiplication to apply color transformations to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-matrix-multiplication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforming with matrix multiplication",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-with-matrix-multiplication"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-polynomials": {
      "abstract": [
        {
          "text": "Use polynomials to apply color transformations to images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-polynomials",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transforming with polynomials",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-with-polynomials"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Convolves a floating-point 32-bit-per-channel, 4-channel interleaved image by a 2D kernel, then divides the pixel values by a divisor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConvolve_ARGBFFFF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImagePixelCount",
          "text": "vImagePixelCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImagePixelCount",
          "text": "vImagePixelCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConvolve_ARGBFFFF"
        }
      ],
      "role": "symbol",
      "title": "vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconvolve_argbffff(_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Convolves an 8-bit planar image by a 2D kernel and divides the pixel values by a divisor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConvolve_Planar8"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_Buffer",
          "text": "vImage_Buffer"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImagePixelCount",
          "text": "vImagePixelCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImagePixelCount",
          "text": "vImagePixelCount"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@Pixel_8",
          "text": "Pixel_8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConvolve_Planar8"
        }
      ],
      "role": "symbol",
      "title": "vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconvolve_planar8(_:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vimage-library": {
      "abstract": [
        {
          "text": "Manipulate large images using the CPU’s vector processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vimage-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "vImage",
      "type": "topic",
      "url": "/documentation/accelerate/vimage-library"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "vImage-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/adjusting-saturation-and-applying-tone-mapping",
        "doc://com.apple.accelerate/documentation/Accelerate/blurring-an-image",
        "doc://com.apple.accelerate/documentation/Accelerate/adding-a-bokeh-effect-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/converting-color-images-to-grayscale",
        "doc://com.apple.accelerate/documentation/Accelerate/building-a-basic-image-conversion-workflow",
        "doc://com.apple.accelerate/documentation/Accelerate/specifying-histograms-with-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/enhancing-image-contrast-with-histogram-manipulation",
        "doc://com.apple.accelerate/documentation/Accelerate/reducing-artifacts-with-custom-resampling-filters",
        "doc://com.apple.accelerate/documentation/Accelerate/finding-the-sharpest-image-in-a-sequence-of-captured-images"
      ],
      "title": "vImage Operations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Applying-color-transforms-to-images",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-lookup-tables",
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-polynomials",
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-matrix-multiplication",
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-with-a-gamma-function",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-a-flood-fill-to-an-image"
      ],
      "title": "Applying color transforms to images"
    },
    {
      "anchor": "Applying-geometric-transforms-to-image-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/resampling-in-vimage",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-affine-transformations-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/applying-projective-transformations-to-images",
        "doc://com.apple.accelerate/documentation/Accelerate/image-reflection",
        "doc://com.apple.accelerate/documentation/Accelerate/image-shearing",
        "doc://com.apple.accelerate/documentation/Accelerate/image-rotation",
        "doc://com.apple.accelerate/documentation/Accelerate/image-scaling",
        "doc://com.apple.accelerate/documentation/Accelerate/getting-the-buffer-size"
      ],
      "title": "Applying geometric transforms to image buffers"
    },
    {
      "anchor": "Applying-morphological-operations-to-images",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/morphology"
      ],
      "title": "Applying morphological operations to images"
    },
    {
      "anchor": "Calculating-and-modifying-an-images-histogram",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/histogram"
      ],
      "title": "Calculating and modifying an image’s histogram"
    },
    {
      "anchor": "Clipping-data",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/clipping-data"
      ],
      "title": "Clipping data"
    },
    {
      "anchor": "Compositing-images-using-alpha-information",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/alpha-compositing"
      ],
      "title": "Compositing images using alpha information"
    },
    {
      "anchor": "Converting-image-buffers-between-formats",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/conversion"
      ],
      "title": "Converting image buffers between formats"
    },
    {
      "anchor": "Convolving-images",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/convolution"
      ],
      "title": "Convolving images"
    },
    {
      "anchor": "Extracting-channels",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/extracting-channels"
      ],
      "title": "Extracting channels"
    },
    {
      "anchor": "Filling-buffers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/filling-buffers"
      ],
      "title": "Filling buffers"
    },
    {
      "anchor": "Filtering-data-prior-to-decompressing",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/decompression-filtering"
      ],
      "title": "Filtering data prior to decompressing"
    },
    {
      "anchor": "Flattening-data",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/flattening-data"
      ],
      "title": "Flattening data"
    },
    {
      "anchor": "Overwriting-channels",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/overwriting-channels"
      ],
      "title": "Overwriting channels"
    },
    {
      "anchor": "Permuting-channels",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/permuting-channels"
      ],
      "title": "Permuting channels"
    },
    {
      "anchor": "Swapping-bytes",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/swapping-bytes"
      ],
      "title": "Swapping bytes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "vImageConvolve_ARGBFFFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvolve_ARGBFFFF(_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConvolve_ARGBFFFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)/title",
          "value": "vImageConvolve_Planar8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvolve_Planar8(_:_:_:_:_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConvolve_Planar8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
