{
  "abstract": [
    {
      "text": "A representation of the chromaticity of primaries that define a color space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImageRGBPrimaries",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImageRGBPrimaries"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImageRGBPrimaries"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "vImageRGBPrimaries"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImageRGBPrimaries"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "x",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "y",
              "type": "codeVoice"
            },
            {
              "text": " values define the chromaticity of each color primary RGB and the white point according to the CIE 1931 color space. For example, the following code defines the RGB primaries for ITU-R BT.709-5:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var rgbPrimaries = vImageRGBPrimaries(",
            "    red_x: 0.64,",
            "    green_x: 0.3,",
            "    blue_x: 0.15,",
            "    white_x: 0.3127,",
            "    red_y: 0.33,",
            "    green_y: 0.6,",
            "    blue_y: 0.06,",
            "    white_y: 0.329)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a monochrome color space based on primitives from Y’CbCr specifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageWhitePoint",
          "text": "vImageWhitePoint"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageTransferFunction",
          "text": "vImageTransferFunction"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGColorRenderingIntent",
          "text": "CGColorRenderingIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecreatemonochromecolorspacewithwhitepointandtransferfunction(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an RGB color space based on primitives from Y’CbCr specifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageRGBPrimaries",
          "text": "vImageRGBPrimaries"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImageTransferFunction",
          "text": "vImageTransferFunction"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGColorRenderingIntent",
          "text": "CGColorRenderingIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorSpaceRef",
          "text": "CGColorSpace"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagecreatergbcolorspacewithprimariesandtransferfunction(_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries": {
      "abstract": [
        {
          "text": "A representation of the chromaticity of primaries that define a color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageRGBPrimaries"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageRGBPrimaries"
        }
      ],
      "role": "symbol",
      "title": "vImageRGBPrimaries",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_x": {
      "abstract": [
        {
          "text": "The blue ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blue_x"
        }
      ],
      "role": "symbol",
      "title": "blue_x",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/blue_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_y": {
      "abstract": [
        {
          "text": "The blue ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blue_y"
        }
      ],
      "role": "symbol",
      "title": "blue_y",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/blue_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_x": {
      "abstract": [
        {
          "text": "The green ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "green_x"
        }
      ],
      "role": "symbol",
      "title": "green_x",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/green_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_y": {
      "abstract": [
        {
          "text": "The green_ _",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "green_y"
        }
      ],
      "role": "symbol",
      "title": "green_y",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/green_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init()": {
      "abstract": [
        {
          "text": "Creates an empty RGB primaries structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init(red_x:green_x:blue_x:white_x:red_y:green_y:blue_y:white_y:)": {
      "abstract": [
        {
          "text": "Creates a structure that represents the specified chromaticity of primaries defining a color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "red_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "white_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "red_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "white_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init(red_x:green_x:blue_x:white_x:red_y:green_y:blue_y:white_y:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(red_x:green_x:blue_x:white_x:red_y:green_y:blue_y:white_y:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/init(red_x:green_x:blue_x:white_x:red_y:green_y:blue_y:white_y:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_x": {
      "abstract": [
        {
          "text": "The red ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "red_x"
        }
      ],
      "role": "symbol",
      "title": "red_x",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/red_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_y": {
      "abstract": [
        {
          "text": "The red ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "red_y"
        }
      ],
      "role": "symbol",
      "title": "red_y",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/red_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_x": {
      "abstract": [
        {
          "text": "The white point ",
          "type": "text"
        },
        {
          "code": "x",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white_x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "white_x"
        }
      ],
      "role": "symbol",
      "title": "white_x",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/white_x"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_y": {
      "abstract": [
        {
          "text": "The white point ",
          "type": "text"
        },
        {
          "code": "y",
          "type": "codeVoice"
        },
        {
          "text": " value according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "white_y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "white_y"
        }
      ],
      "role": "symbol",
      "title": "white_y",
      "type": "topic",
      "url": "/documentation/accelerate/vimagergbprimaries/white_y"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction": {
      "abstract": [
        {
          "text": "A transfer function to convert from linear to nonlinear RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageTransferFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "vImageTransferFunction",
      "type": "topic",
      "url": "/documentation/accelerate/vimagetransferfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageWhitePoint": {
      "abstract": [
        {
          "text": "A representation of a white point according to the CIE 1931 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageWhitePoint"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageWhitePoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageWhitePoint"
        }
      ],
      "role": "symbol",
      "title": "vImageWhitePoint",
      "type": "topic",
      "url": "/documentation/accelerate/vimagewhitepoint"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Core-Graphics-color-spaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageWhitePoint"
      ],
      "title": "Creating Core Graphics color spaces"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init(red_x:green_x:blue_x:white_x:red_y:green_y:blue_y:white_y:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/init()"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Color-primary-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_x",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_x",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_x",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_x",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_y",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_y",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_y",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_y"
      ],
      "title": "Color primary properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImageRGBPrimaries"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageRGBPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageRGBPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Color-primary-properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_x",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_x",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_x",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_x",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/red_y",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/green_y",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/blue_y",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageRGBPrimaries/white_y"
              ],
              "title": "Color primary properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Core-Graphics-color-spaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageTransferFunction",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageWhitePoint"
              ],
              "title": "Creating Core Graphics color spaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImageRGBPrimaries"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImageRGBPrimaries"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1blue_x/title",
          "value": "blue_x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1blue_x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blue_x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries/title",
          "value": "vImageRGBPrimaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageRGBPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageRGBPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1red_y/title",
          "value": "red_y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1red_y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "red_y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)/title",
          "value": "vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCreateMonochromeColorSpaceWithWhitePointAndTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1white_y/title",
          "value": "white_y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1white_y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "white_y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1white_x/title",
          "value": "white_x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1white_x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "white_x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1green_y/title",
          "value": "green_y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1green_y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "green_y"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/title",
          "value": "vImageTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageTransferFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageWhitePoint/title",
          "value": "vImageWhitePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageWhitePoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageWhitePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageWhitePoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageWhitePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1red_x/title",
          "value": "red_x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1red_x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "red_x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1green_x/title",
          "value": "green_x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1green_x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "green_x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)/title",
          "value": "vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageCreateRGBColorSpaceWithPrimariesAndTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1blue_y/title",
          "value": "blue_y"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageRGBPrimaries~1blue_y/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blue_y"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimagergbprimaries"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimagergbprimaries"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
