{
  "abstract": [
    {
      "text": "The 3 x 3 matrix that the vImage library uses to convert from RGB to YpCbCr.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImage_ARGBToYpCbCrMatrix",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImage_ARGBToYpCbCrMatrix"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImage_ARGBToYpCbCrMatrix"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "vImage_ARGBToYpCbCrMatrix"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The vImage library uses this matrix to convert from RGB to YpCbCr using the following multiplication:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "        | Y' |   | R_Yp        G_Yp   B_Yp      |   | R |",
            "        | Cb | = | R_Cb        G_Cb   B_Cb_R_Cr | * | G |",
            "        | Cr |   | B_Cb_R_Cr   G_Cr   B_Cr      |   | B |"
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4": {
      "abstract": [
        {
          "text": "RGB-to-Y’CbCr conversion matrix for ITU Recommendation BT.601-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
        }
      ],
      "role": "symbol",
      "title": "kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_argbtoypcbcrmatrix_itu_r_601_4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2": {
      "abstract": [
        {
          "text": "RGB-to-Y’CbCr conversion matrix for ITU Recommendation BT.709-2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_argbtoypcbcrmatrix_itu_r_709_2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType": {
      "abstract": [
        {
          "text": "Constants that describe the encoding of an ARGB image for conversions between RGB and YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageARGBType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageARGBType"
        }
      ],
      "role": "symbol",
      "title": "vImageARGBType",
      "type": "topic",
      "url": "/documentation/accelerate/vimageargbtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Generates the information that describes the conversion from ARGB to YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConvert_ARGBToYpCbCr_GenerateConversion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrPixelRange",
          "text": "vImage_YpCbCrPixelRange"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCr",
          "text": "vImage_ARGBToYpCbCr"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageARGBType",
          "text": "vImageARGBType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConvert_ARGBToYpCbCr_GenerateConversion"
        }
      ],
      "role": "symbol",
      "title": "vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconvert_argbtoypcbcr_generateconversion(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType": {
      "abstract": [
        {
          "text": "Constants that describe the encoding of a YpCbCr image for conversions between RGB and YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "role": "symbol",
      "title": "vImageYpCbCrType",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr": {
      "abstract": [
        {
          "text": "The information that describes the conversion from ARGB to YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCr"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCr"
        }
      ],
      "role": "symbol",
      "title": "vImage_ARGBToYpCbCr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix": {
      "abstract": [
        {
          "text": "The 3 x 3 matrix that the vImage library uses to convert from RGB to YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImage_ARGBToYpCbCrMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Cb_R_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Cb_R_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Cb_R_Cr"
        }
      ],
      "role": "symbol",
      "title": "B_Cb_R_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_cb_r_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Cr"
        }
      ],
      "role": "symbol",
      "title": "B_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "B_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "B_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "B_Yp"
        }
      ],
      "role": "symbol",
      "title": "B_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/b_yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Cb",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Cb"
        }
      ],
      "role": "symbol",
      "title": "G_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Cr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Cr"
        }
      ],
      "role": "symbol",
      "title": "G_Cr",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_cr"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "G_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "G_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "G_Yp"
        }
      ],
      "role": "symbol",
      "title": "G_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/g_yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "R_Cb",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "R_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "R_Cb"
        }
      ],
      "role": "symbol",
      "title": "R_Cb",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/r_cb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "R_Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "R_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "R_Yp"
        }
      ],
      "role": "symbol",
      "title": "R_Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/r_yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init()": {
      "abstract": [
        {
          "text": "Creates a 3 x 3 zero matrix for converting RGB to Y’CbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init(R_Yp:G_Yp:B_Yp:R_Cb:G_Cb:B_Cb_R_Cr:G_Cr:B_Cr:)": {
      "abstract": [
        {
          "text": "Creates a 3 x 3 matrix for converting RGB to Y’CbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "R_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "G_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "B_Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "R_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "G_Cb"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "B_Cb_R_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "G_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "B_Cr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init(R_Yp:G_Yp:B_Yp:R_Cb:G_Cb:B_Cb_R_Cr:G_Cr:B_Cr:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(R_Yp:G_Yp:B_Yp:R_Cb:G_Cb:B_Cb_R_Cr:G_Cr:B_Cr:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/init(r_yp:g_yp:b_yp:r_cb:g_cb:b_cb_r_cr:g_cr:b_cr:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_601_4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itu_R_601_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_601_4",
      "kind": "symbol",
      "role": "symbol",
      "title": "itu_R_601_4",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/itu_r_601_4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_709_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itu_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_ARGBToYpCbCrMatrix",
          "text": "vImage_ARGBToYpCbCrMatrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_709_2",
      "kind": "symbol",
      "role": "symbol",
      "title": "itu_R_709_2",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_argbtoypcbcrmatrix/itu_r_709_2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange": {
      "abstract": [
        {
          "text": "The description of range and clamping information for YpCbCr pixel formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrPixelRange"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrPixelRange"
        }
      ],
      "role": "symbol",
      "title": "vImage_YpCbCrPixelRange",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrpixelrange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generating-conversion-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange"
      ],
      "title": "Generating conversion information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-conversion-matrix",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init(R_Yp:G_Yp:B_Yp:R_Cb:G_Cb:B_Cb_R_Cr:G_Cr:B_Cr:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/init()"
      ],
      "title": "Creating a conversion matrix"
    },
    {
      "anchor": "Conversion-matrix-elements",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr"
      ],
      "title": "Conversion matrix elements"
    },
    {
      "anchor": "Conversion-matrices",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
      ],
      "title": "Conversion matrices"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_601_4",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/itu_R_709_2"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Conversion-matrix-elements",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/R_Cb",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cb",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cb_R_Cr",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/G_Cr",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCrMatrix/B_Cr"
              ],
              "title": "Conversion matrix elements"
            },
            {
              "anchor": "Conversion-matrices",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
              ],
              "title": "Conversion matrices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generating-conversion-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange"
              ],
              "title": "Generating conversion information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_ARGBToYpCbCrMatrix"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_ARGBToYpCbCrMatrix"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Yp/title",
          "value": "G_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cb/title",
          "value": "G_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/title",
          "value": "vImageARGBType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageARGBType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageARGBType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4/title",
          "value": "kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_601_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/title",
          "value": "vImage_YpCbCrPixelRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrPixelRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrPixelRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/title",
          "value": "vImage_ARGBToYpCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cb_R_Cr/title",
          "value": "B_Cb_R_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cb_R_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Cb_R_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Yp/title",
          "value": "B_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cr/title",
          "value": "G_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1G_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "G_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2/title",
          "value": "kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_ARGBToYpCbCrMatrix_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/title",
          "value": "vImageYpCbCrType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Cb/title",
          "value": "R_Cb"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Cb/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "R_Cb"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Yp/title",
          "value": "R_Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1R_Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "R_Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/title",
          "value": "vImage_ARGBToYpCbCrMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_ARGBToYpCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cr/title",
          "value": "B_Cr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCrMatrix~1B_Cr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "B_Cr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)/title",
          "value": "vImageConvert_ARGBToYpCbCr_GenerateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGBToYpCbCr_GenerateConversion(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConvert_ARGBToYpCbCr_GenerateConversion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_argbtoypcbcrmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_argbtoypcbcrmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
