{
  "abstract": [
    {
      "text": "A projective-transformation matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImage_PerpsectiveTransform",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImage_PerpsectiveTransform"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImage_PerpsectiveTransform"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "vImage_PerpsectiveTransform"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/transforming-an-image-in-three-dimensions": {
      "abstract": [
        {
          "text": "Create and use a projective transformation to apply a perspective warp to an image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/transforming-an-image-in-three-dimensions",
      "kind": "article",
      "role": "article",
      "title": "Transforming an image in three dimensions",
      "type": "topic",
      "url": "/documentation/accelerate/transforming-an-image-in-three-dimensions"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageGetPerspectiveWarp(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a projective-transformation structure that defines the mapping between a source quadrilateral and a destination quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageGetPerspectiveWarp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
          "text": "vImage_PerpsectiveTransform"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageGetPerspectiveWarp(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageGetPerspectiveWarp"
        }
      ],
      "role": "symbol",
      "title": "vImageGetPerspectiveWarp(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimagegetperspectivewarp(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform": {
      "abstract": [
        {
          "text": "A projective-transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_PerpsectiveTransform"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_PerpsectiveTransform"
        }
      ],
      "role": "symbol",
      "title": "vImage_PerpsectiveTransform",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/Interpolation": {
      "abstract": [
        {
          "text": "Constants that describe the projective-transformation interpolation method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Interpolation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/Interpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Interpolation"
        }
      ],
      "role": "symbol",
      "title": "vImage_PerpsectiveTransform.Interpolation",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/interpolation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints": {
      "abstract": [
        {
          "text": "A tuple of four points that define a quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QuadrilateralPoints"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QuadrilateralPoints"
        }
      ],
      "role": "symbol",
      "title": "vImage_PerpsectiveTransform.QuadrilateralPoints",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/quadrilateralpoints"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/a": {
      "abstract": [
        {
          "text": "The top-left cell in the 3 x 3 transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "a"
        }
      ],
      "role": "symbol",
      "title": "a",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/a"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/b": {
      "abstract": [
        {
          "text": "The top-middle cell in the 3 x 3 transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "b"
        }
      ],
      "role": "symbol",
      "title": "b",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/b"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/c": {
      "abstract": [
        {
          "text": "The middle-left cell in the 3 x 3 transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "c"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/c",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "c"
        }
      ],
      "role": "symbol",
      "title": "c",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/c"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/d": {
      "abstract": [
        {
          "text": "The middle-middle cell in the 3 x 3 transformation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "d"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/d",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "d"
        }
      ],
      "role": "symbol",
      "title": "d",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/d"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()": {
      "abstract": [
        {
          "text": "Creates a projective-transformation structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)": {
      "abstract": [
        {
          "text": "Creates a projective-transformation structure from the specified single-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "c"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "d"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "vx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "vy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(a:b:c:d:tx:ty:vx:vy:v:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init(a:b:c:d:tx:ty:vx:vy:v:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)": {
      "abstract": [
        {
          "text": "Returns a projective-transformation structure that defines the mapping between a source quadrilateral and a destination quadrilateral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
          "text": "vImage_PerpsectiveTransform"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
          "text": "QuadrilateralPoints"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_PerpsectiveTransform",
          "text": "vImage_PerpsectiveTransform"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So27vImage_PerpsectiveTransformV10AccelerateE19QuadrilateralPointsa",
          "text": "QuadrilateralPoints"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(source:destination:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/init(source:destination:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/tx": {
      "abstract": [
        {
          "text": "The x-coordinate translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/tx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tx"
        }
      ],
      "role": "symbol",
      "title": "tx",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/tx"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/ty": {
      "abstract": [
        {
          "text": "The y-coordinate translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/ty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ty"
        }
      ],
      "role": "symbol",
      "title": "ty",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/ty"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/v": {
      "abstract": [
        {
          "text": "The homogeneous scale factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "v"
        }
      ],
      "role": "symbol",
      "title": "v",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/v"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vx": {
      "abstract": [
        {
          "text": "The x-component of the projective vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vx"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vx",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vx"
        }
      ],
      "role": "symbol",
      "title": "vx",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/vx"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vy": {
      "abstract": [
        {
          "text": "The y-component of the projective vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vy"
        }
      ],
      "role": "symbol",
      "title": "vy",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_perpsectivetransform/vy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Computing-a-projective-transformation-from-source-and-destination-quadrilaterals",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/transforming-an-image-in-three-dimensions",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageGetPerspectiveWarp(_:_:_:_:)"
      ],
      "title": "Computing a projective transformation from source and destination quadrilaterals"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-projective-transformation-structure",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(a:b:c:d:tx:ty:vx:vy:v:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/init(source:destination:)"
      ],
      "title": "Creating a projective-transformation structure"
    },
    {
      "anchor": "Inspecting-a-projective-transformation-structures-properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/a",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/b",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/c",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/d",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/tx",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/ty",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vx",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vy",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/v"
      ],
      "title": "Inspecting a projective-transformation structure’s properties"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/QuadrilateralPoints"
      ],
      "title": "Type Aliases"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/Interpolation"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImage_PerpsectiveTransform"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-a-projective-transformation-structures-properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/a",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/b",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/c",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/d",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/tx",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/ty",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vx",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/vy",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_PerpsectiveTransform/v"
              ],
              "title": "Inspecting a projective-transformation structure’s properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Computing-a-projective-transformation-from-source-and-destination-quadrilaterals",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageGetPerspectiveWarp(_:_:_:_:)"
              ],
              "title": "Computing a projective transformation from source and destination quadrilaterals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_PerpsectiveTransform"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_PerpsectiveTransform"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1a/title",
          "value": "a"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "a"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetPerspectiveWarp(_:_:_:_:)/title",
          "value": "vImageGetPerspectiveWarp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageGetPerspectiveWarp(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageGetPerspectiveWarp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1vx/title",
          "value": "vx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1vx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1ty/title",
          "value": "ty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1ty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1d/title",
          "value": "d"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1d/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "d"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1tx/title",
          "value": "tx"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1tx/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tx"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1vy/title",
          "value": "vy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1vy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/title",
          "value": "vImage_PerpsectiveTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_PerpsectiveTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1b/title",
          "value": "b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1v/title",
          "value": "v"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "v"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1c/title",
          "value": "c"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_PerpsectiveTransform~1c/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "c"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_perpsectivetransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_perpsectivetransform"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
