{
  "abstract": [
    {
      "text": "The 3 x 3 matrix that the vImage library uses to convert from YpCbCr to RGB.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@vImage_YpCbCrToARGBMatrix",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vImage_YpCbCrToARGBMatrix"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vImage_YpCbCrToARGBMatrix"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "vImage_YpCbCrToARGBMatrix"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGBMatrix"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The vImage library uses this matrix to convert from YpCbCr to RGB using the following multiplication:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "                    | R |   | Yp    0     Cr_R |   | Y' |",
            "                    | G | = | Yp   Cb_G   Cr_G | * | Cb |",
            "                    | B |   | Yp   Cb_B     0  |   | Cr |"
          ],
          "syntax": null,
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_601_4": {
      "abstract": [
        {
          "text": "Y’CbCr-to-RGB conversion matrix for ITU Recommendation BT.601-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_601_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrToARGBMatrix",
          "text": "vImage_YpCbCrToARGBMatrix"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_601_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_601_4"
        }
      ],
      "role": "symbol",
      "title": "kvImage_YpCbCrToARGBMatrix_ITU_R_601_4",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_ypcbcrtoargbmatrix_itu_r_601_4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_709_2": {
      "abstract": [
        {
          "text": "Y’CbCr-to-RGB conversion matrix for ITU Recommendation BT.709-2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrToARGBMatrix",
          "text": "vImage_YpCbCrToARGBMatrix"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "kvImage_YpCbCrToARGBMatrix_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/accelerate/kvimage_ypcbcrtoargbmatrix_itu_r_709_2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType": {
      "abstract": [
        {
          "text": "Constants that describe the encoding of an ARGB image for conversions between RGB and YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageARGBType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageARGBType"
        }
      ],
      "role": "symbol",
      "title": "vImageARGBType",
      "type": "topic",
      "url": "/documentation/accelerate/vimageargbtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Generates the information that describes the conversion from YpCbCr to ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageConvert_YpCbCrToARGB_GenerateConversion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrToARGBMatrix",
          "text": "vImage_YpCbCrToARGBMatrix"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrPixelRange",
          "text": "vImage_YpCbCrPixelRange"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@vImage_YpCbCrToARGB",
          "text": "vImage_YpCbCrToARGB"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageYpCbCrType",
          "text": "vImageYpCbCrType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@vImageARGBType",
          "text": "vImageARGBType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Flags",
          "text": "vImage_Flags"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vImage_Error",
          "text": "vImage_Error"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageConvert_YpCbCrToARGB_GenerateConversion"
        }
      ],
      "role": "symbol",
      "title": "vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimageconvert_ypcbcrtoargb_generateconversion(_:_:_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType": {
      "abstract": [
        {
          "text": "Constants that describe the encoding of a YpCbCr image for conversions between RGB and YpCbCr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImageYpCbCrType"
        }
      ],
      "role": "symbol",
      "title": "vImageYpCbCrType",
      "type": "topic",
      "url": "/documentation/accelerate/vimageypcbcrtype"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange": {
      "abstract": [
        {
          "text": "The description of range and clamping information for YpCbCr pixel formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrPixelRange"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrPixelRange"
        }
      ],
      "role": "symbol",
      "title": "vImage_YpCbCrPixelRange",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrpixelrange"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB": {
      "abstract": [
        {
          "text": "The information that describes the conversion from YpCbCr to ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGB"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGB"
        }
      ],
      "role": "symbol",
      "title": "vImage_YpCbCrToARGB",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargb"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix": {
      "abstract": [
        {
          "text": "The 3 x 3 matrix that the vImage library uses to convert from YpCbCr to RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGBMatrix"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_YpCbCrToARGBMatrix"
        }
      ],
      "role": "symbol",
      "title": "vImage_YpCbCrToARGBMatrix",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_B": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Cb_B",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Cb_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_B",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Cb_B"
        }
      ],
      "role": "symbol",
      "title": "Cb_B",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/cb_b"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_G": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Cb_G",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Cb_G"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Cb_G"
        }
      ],
      "role": "symbol",
      "title": "Cb_G",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/cb_g"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_G": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Cr_G",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Cr_G"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_G",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Cr_G"
        }
      ],
      "role": "symbol",
      "title": "Cr_G",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/cr_g"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_R": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Cr_R",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Cr_R"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_R",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Cr_R"
        }
      ],
      "role": "symbol",
      "title": "Cr_R",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/cr_r"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Yp": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Yp",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " value in the conversion matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Yp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Yp"
        }
      ],
      "role": "symbol",
      "title": "Yp",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/yp"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init()": {
      "abstract": [
        {
          "text": "Creates a 3 x 3 zero matrix for converting Y’CbCr signals to RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init(Yp:Cr_R:Cr_G:Cb_G:Cb_B:)": {
      "abstract": [
        {
          "text": "Creates a 3 x 3 matrix for converting Y’CbCr signals to RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "Yp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "Cr_R"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "Cr_G"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "Cb_G"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "Cb_B"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init(Yp:Cr_R:Cr_G:Cb_G:Cb_B:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(Yp:Cr_R:Cr_G:Cb_G:Cb_B:)",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_ypcbcrtoargbmatrix/init(yp:cr_r:cr_g:cb_g:cb_b:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Generating-conversion-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange"
      ],
      "title": "Generating conversion information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-conversion-matrix",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init(Yp:Cr_R:Cr_G:Cb_G:Cb_B:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/init()"
      ],
      "title": "Creating a conversion matrix"
    },
    {
      "anchor": "Conversion-matrix-elements",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Yp",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_R",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_G",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_G",
        "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_B"
      ],
      "title": "Conversion matrix elements"
    },
    {
      "anchor": "Conversion-matrices",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_601_4",
        "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
      ],
      "title": "Conversion matrices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vImage_YpCbCrToARGBMatrix"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGBMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGBMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Conversion-matrix-elements",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Yp",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_R",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cr_G",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_G",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGBMatrix/Cb_B"
              ],
              "title": "Conversion matrix elements"
            },
            {
              "anchor": "Conversion-matrices",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_601_4",
                "doc://com.apple.accelerate/documentation/Accelerate/kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
              ],
              "title": "Conversion matrices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Generating-conversion-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageYpCbCrType",
                "doc://com.apple.accelerate/documentation/Accelerate/vImageARGBType",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrToARGB",
                "doc://com.apple.accelerate/documentation/Accelerate/vImage_YpCbCrPixelRange"
              ],
              "title": "Generating conversion information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_YpCbCrToARGBMatrix"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "vImage_YpCbCrToARGBMatrix"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cr_G/title",
          "value": "Cr_G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cr_G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Cr_G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/title",
          "value": "vImageYpCbCrType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageYpCbCrType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageYpCbCrType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Yp/title",
          "value": "Yp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Yp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Yp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/title",
          "value": "vImageARGBType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageARGBType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageARGBType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageARGBType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)/title",
          "value": "vImageConvert_YpCbCrToARGB_GenerateConversion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_YpCbCrToARGB_GenerateConversion(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImageConvert_YpCbCrToARGB_GenerateConversion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cb_G/title",
          "value": "Cb_G"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cb_G/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Cb_G"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix/title",
          "value": "vImage_YpCbCrToARGBMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGBMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGBMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/title",
          "value": "vImage_YpCbCrToARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGB/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrToARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cr_R/title",
          "value": "Cr_R"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cr_R/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Cr_R"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/title",
          "value": "vImage_YpCbCrPixelRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrPixelRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrPixelRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_YpCbCrPixelRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_YpCbCrToARGBMatrix_ITU_R_601_4/title",
          "value": "kvImage_YpCbCrToARGBMatrix_ITU_R_601_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_YpCbCrToARGBMatrix_ITU_R_601_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_601_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_YpCbCrToARGBMatrix_ITU_R_709_2/title",
          "value": "kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImage_YpCbCrToARGBMatrix_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kvImage_YpCbCrToARGBMatrix_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cb_B/title",
          "value": "Cb_B"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_YpCbCrToARGBMatrix~1Cb_B/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Cb_B"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_ypcbcrtoargbmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_ypcbcrtoargbmatrix"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
