{
  "abstract": [
    {
      "text": "Defined as ",
      "type": "text"
    },
    {
      "code": "1",
      "type": "codeVoice"
    },
    {
      "text": " if double-precision affine transforms and related functions are supported on the current architecture and in the current SDK, else undefined. See ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " for more information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE": {
      "abstract": [
        {
          "text": "Defined as ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " if double-precision affine transforms and related functions are supported on the current architecture and in the current SDK, else undefined. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_affinetransform_double_is_available"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE": {
      "abstract": [
        {
          "text": "Defined as ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " if Core Graphics affine transforms and related functions are supported on the current architecture and in the current SDK, else undefined. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for more information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        }
      ],
      "role": "symbol",
      "title": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_cgaffinetransform_is_available"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double": {
      "abstract": [
        {
          "text": "A structure for values that represent a double-precision affine transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_AffineTransform_Double"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_AffineTransform_Double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_AffineTransform_Double"
        }
      ],
      "role": "symbol",
      "title": "vImage_AffineTransform_Double",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_affinetransform_double"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform": {
      "abstract": [
        {
          "text": "A structure for values that represent a Core Graphics–compatible affine transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vImage_CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vImage_CGAffineTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vImage_CGAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "vImage_CGAffineTransform",
      "type": "topic",
      "url": "/documentation/accelerate/vimage_cgaffinetransform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE/title",
          "value": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/title",
          "value": "vImage_CGAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_CGAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_CGAffineTransform/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_CGAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/title",
          "value": "vImage_AffineTransform_Double"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_AffineTransform_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_AffineTransform_Double/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vImage_AffineTransform_Double"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE/title",
          "value": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vimage_affinetransform_double_is_available"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vimage_affinetransform_double_is_available"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
