{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_CbCr8"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"vImage_ARGBToYpCbCr","preciseIdentifier":"c:@S@vImage_ARGBToYpCbCr"},{"kind":"text","text":">, "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error"}],"roleHeading":"Function","role":"symbol","symbolKind":"func","navigatorTitle":[{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_CbCr8"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.10","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false},{"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"1.0","deprecated":false}],"title":"vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)","externalID":"c:@F@vImageConvert_ARGB8888To420Yp8_CbCr8","modules":[{"name":"Accelerate"}]},"abstract":[{"text":"Converts an 8-bit-per-channel, 4-channel ARGB buffer to a planar Yp buffer and a 2-channel CbCr buffer.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageConvert_ARGB8888To420Yp8_CbCr8","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"src","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destYp","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destCbCr","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_ARGBToYpCbCr","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr","preciseIdentifier":"c:@S@vImage_ARGBToYpCbCr","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"permuteMap","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","identifier":"doc://com.externally.resolved.symbol/s:s5UInt8V","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">!, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"flags","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"vImage_Flags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","preciseIdentifier":"c:@T@vImage_Error","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"src","content":[{"type":"paragraph","inlineContent":[{"text":"The source vImage buffer.","type":"text"}]}]},{"name":"destYp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer to the Yp destination vImage buffer structure. You’re responsible for filling out the "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","isActive":true},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the Yp destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}]}]},{"name":"destCbCr","content":[{"inlineContent":[{"type":"text","text":"A pointer to the CbCr destination vImage buffer structure. You’re responsible for filling out the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width"},{"type":"text","text":", and "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes"},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the CbCr destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}],"type":"paragraph"}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr"},{"text":" structure that describes the conversion matrix, the range of the input and output pixels from the matrix, and clamping information.","type":"text"}]}]},{"name":"permuteMap","content":[{"type":"paragraph","inlineContent":[{"text":"An array of four 8-bit integers with the values ","type":"text"},{"type":"codeVoice","code":"0"},{"text":", ","type":"text"},{"type":"codeVoice","code":"1"},{"text":", ","type":"text"},{"type":"codeVoice","code":"2"},{"text":", and 3, in some order. Each value specifies the channel from the source image that the function copies to the destination channel at the corresponding index.","type":"text"}]}]},{"name":"flags","content":[{"inlineContent":[{"text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","isActive":true,"type":"reference"},{"text":"; otherwise, pass ","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","isActive":true},{"type":"text","text":"; otherwise, one of the error codes in "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/accelerate/vimageconvert_argb8888to420yp8_cbcr8(_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/accelerate/vimageconvert_argb8888to420yp8_cbcr8(_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"seeAlsoSections":[{"title":"Converting to 4:2:0","generated":true,"anchor":"Converting-to-420","identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile":{"navigatorTitle":[{"kind":"identifier","text":"kvImageDoNotTile"}],"type":"topic","abstract":[{"text":"A flag that disables vImage internal tiling routines.","type":"text"}],"url":"/documentation/accelerate/kvimagedonottile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageDoNotTile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile","title":"kvImageDoNotTile"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error":{"role":"symbol","kind":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error","url":"/documentation/accelerate/vimage_error","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Error"}],"navigatorTitle":[{"kind":"identifier","text":"vImage_Error"}],"title":"vImage_Error","abstract":[{"text":"A type for image errors.","type":"text"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"vImage_ARGBToYpCbCr"}],"kind":"symbol","title":"vImage_ARGBToYpCbCr","abstract":[{"type":"text","text":"The information that describes the conversion from ARGB to YpCbCr."}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr","role":"symbol","url":"/documentation/accelerate/vimage_argbtoypcbcr","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_ARGBToYpCbCr"}]},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags":{"navigatorTitle":[{"kind":"identifier","text":"vImage_Flags"}],"type":"topic","abstract":[{"text":"A type for processing options.","type":"text"}],"url":"/documentation/accelerate/vimage_flags","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Flags"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags","title":"vImage_Flags"},"doc://com.apple.accelerate/documentation/Accelerate":{"abstract":[{"text":"Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.","type":"text"}],"type":"topic","title":"Accelerate","identifier":"doc://com.apple.accelerate/documentation/Accelerate","kind":"symbol","url":"/documentation/accelerate","role":"collection"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer":{"abstract":[{"text":"An image buffer that stores an image’s pixel data, dimensions, and row stride.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImage_Buffer"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"vImage_Buffer"}],"type":"topic","url":"/documentation/accelerate/vimage_buffer","title":"vImage_Buffer"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height":{"navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","kind":"symbol","role":"symbol","url":"/documentation/accelerate/vimage_buffer/height","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@vImagePixelCount","text":"vImagePixelCount"}],"type":"topic","title":"height","abstract":[{"type":"text","text":"The height of the image, in pixels."}]},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError":{"url":"/documentation/accelerate/kvimagenoerror","navigatorTitle":[{"text":"kvImageNoError","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kvImageNoError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"text":"The vImage function completed without error.","type":"text"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","title":"kvImageNoError","type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)":{"title":"vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)","abstract":[{"text":"Converts an 8-bit-per-channel, 4-channel ARGB buffer to a planar Yp buffer and a 2-channel CbCr buffer.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImageConvert_ARGB8888To420Yp8_CbCr8","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_ARGBToYpCbCr","preciseIdentifier":"c:@S@vImage_ARGBToYpCbCr","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">!, ","kind":"text"},{"text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"vImageConvert_ARGB8888To420Yp8_CbCr8","kind":"identifier"}],"type":"topic","url":"/documentation/accelerate/vimageconvert_argb8888to420yp8_cbcr8(_:_:_:_:_:_:)"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"vImagePixelCount","preciseIdentifier":"c:@T@vImagePixelCount"}],"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","url":"/documentation/accelerate/vimage_buffer/width","type":"topic","navigatorTitle":[{"kind":"identifier","text":"width"}],"title":"width","role":"symbol","abstract":[{"text":"The width of the image, in pixels.","type":"text"}],"kind":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)":{"kind":"symbol","abstract":[{"text":"Converts an 8-bit-per-channel, 4-channel ARGB buffer to planar Yp, Cb, and Cr buffers.","type":"text"}],"title":"vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_Cb8_Cr8"},{"kind":"text","text":"("},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_Buffer","preciseIdentifier":"c:@S@vImage_Buffer","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"vImage_ARGBToYpCbCr","preciseIdentifier":"c:@S@vImage_ARGBToYpCbCr","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">!, ","kind":"text"},{"text":"vImage_Flags","preciseIdentifier":"c:@T@vImage_Flags","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"vImage_Error","preciseIdentifier":"c:@T@vImage_Error","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"vImageConvert_ARGB8888To420Yp8_Cb8_Cr8","kind":"identifier"}],"url":"/documentation/accelerate/vimageconvert_argb8888to420yp8_cb8_cr8(_:_:_:_:_:_:_:)","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","kind":"technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags":{"abstract":[{"text":"A flag that sets the behavior to the default.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"kvImageNoFlags"}],"title":"kvImageNoFlags","type":"topic","kind":"symbol","url":"/documentation/accelerate/kvimagenoflags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kvImageNoFlags"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.externally.resolved.symbol/s:s5UInt8V":{"abstract":[{"text":"An 8-bit unsigned integer value type.","type":"text"}],"type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt8"}],"title":"UInt8","identifier":"doc://com.externally.resolved.symbol/s:s5UInt8V","kind":"symbol","url":"/documentation/Swift/UInt8","role":"symbol"},"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes":{"navigatorTitle":[{"text":"rowBytes","kind":"identifier"}],"type":"topic","abstract":[{"text":"The distance, in bytes, between the start of one pixel row and the next in an image, including any unused space between them.","type":"text"}],"url":"/documentation/accelerate/vimage_buffer/rowbytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","title":"rowBytes"},"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants":{"abstract":[{"text":"Look up type aliases, data types, and constants the vImage library uses.","type":"text"}],"role":"article","identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","kind":"article","type":"topic","url":"/documentation/Accelerate/data-types-and-constants","title":"Data Types and Constants"},"doc://com.externally.resolved.symbol/s:SP":{"type":"topic","abstract":[{"type":"text","text":"A pointer for accessing data of a specific type."}],"role":"symbol","url":"/documentation/Swift/UnsafePointer","title":"UnsafePointer","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SP","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnsafePointer","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Pointee","kind":"genericParameter"},{"kind":"text","text":"> "},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"name":"iPadOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false},{"name":"macOS","beta":false,"introducedAt":"10.10","unavailable":false,"deprecated":false},{"name":"tvOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false},{"name":"watchOS","beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"vImageConvert_ARGB8888To420Yp8_CbCr8","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_CbCr8"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.accelerate/documentation/Accelerate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.accelerate/documentation/Accelerate/vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)"],"generated":true,"anchor":"Converting-to-420","title":"Converting to 4:2:0"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"vImage_Error","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Error","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Error"},{"text":" ","kind":"text"},{"text":"vImageConvert_ARGB8888To420Yp8_CbCr8","kind":"identifier"},{"text":"(","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"src","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"destYp","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage_Buffer","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_Buffer","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer"},{"text":" * ","kind":"text"},{"text":"destCbCr","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vImage_ARGBToYpCbCr","kind":"typeIdentifier","preciseIdentifier":"c:@S@vImage_ARGBToYpCbCr","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr"},{"text":" * ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"text":" ","kind":"text"},{"text":"permuteMap","kind":"internalParam"},{"text":"[","kind":"text"},{"text":"4","kind":"number"},{"text":"], ","kind":"text"},{"text":"vImage_Flags","kind":"typeIdentifier","preciseIdentifier":"c:@T@vImage_Flags","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Flags"},{"text":" ","kind":"text"},{"text":"flags","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source vImage buffer."}]}],"name":"src"},{"content":[{"inlineContent":[{"type":"text","text":"A pointer to the Yp destination vImage buffer structure. You’re responsible for filling out the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width"},{"type":"text","text":", and "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes"},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the Yp destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}],"type":"paragraph"}],"name":"destYp"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A pointer to the CbCr destination vImage buffer structure. You’re responsible for filling out the "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/height","isActive":true},{"type":"text","text":", "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/width","isActive":true},{"type":"text","text":", and "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_Buffer/rowBytes","isActive":true},{"type":"text","text":" fields of this structure, and for allocating a data buffer of the appropriate size. On return, the data buffer this structure points to contains the CbCr destination image data. When you no longer need the data buffer, deallocate the memory to prevent memory leaks."}]}],"name":"destCbCr"},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/vImage_ARGBToYpCbCr","isActive":true},{"type":"text","text":" structure that describes the conversion matrix, the range of the input and output pixels from the matrix, and clamping information."}],"type":"paragraph"}],"name":"info"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An array of four 8-bit integers with the values ","type":"text"},{"type":"codeVoice","code":"0"},{"text":", ","type":"text"},{"type":"codeVoice","code":"1"},{"text":", ","type":"text"},{"type":"codeVoice","code":"2"},{"text":", and 3, in some order. Each value specifies the channel from the source image that the function copies to the destination channel at the corresponding index.","type":"text"}]}],"name":"permuteMap"},{"content":[{"inlineContent":[{"type":"text","text":"The options to use when performing the operation. If your code implements its own tiling or its own multithreading, pass "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageDoNotTile"},{"type":"text","text":"; otherwise, pass "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoFlags"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"flags"}]},"path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.accelerate/documentation/Accelerate/kvImageNoError","type":"reference","isActive":true},{"text":"; otherwise, one of the error codes in ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/Accelerate/data-types-and-constants","type":"reference","isActive":true},{"text":".","type":"text"}]}]},"op":"replace","path":"/primaryContentSections/2"},{"op":"replace","value":"kvImageDoNotTile","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/title"},{"op":"replace","value":[{"text":"kvImageDoNotTile","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageDoNotTile/fragments"},{"op":"replace","value":"vImage_Error","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/title"},{"op":"replace","value":[{"kind":"identifier","text":"vImage_Error"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"vImage_Error"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Error/navigatorTitle"},{"op":"replace","value":"vImage_ARGBToYpCbCr","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/title"},{"op":"replace","value":[{"kind":"identifier","text":"vImage_ARGBToYpCbCr"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/fragments"},{"op":"replace","value":[{"text":"vImage_ARGBToYpCbCr","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_ARGBToYpCbCr/navigatorTitle"},{"op":"replace","value":"vImage_Flags","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/title"},{"op":"replace","value":[{"text":"vImage_Flags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/fragments"},{"op":"replace","value":[{"text":"vImage_Flags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Flags/navigatorTitle"},{"op":"replace","value":"vImage_Buffer","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/title"},{"op":"replace","value":[{"kind":"identifier","text":"vImage_Buffer"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"vImage_Buffer"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer/navigatorTitle"},{"op":"replace","value":"height","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/title"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1height/fragments"},{"op":"replace","value":"kvImageNoError","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/title"},{"op":"replace","value":[{"text":"kvImageNoError","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoError/fragments"},{"op":"replace","value":"vImageConvert_ARGB8888To420Yp8_CbCr8","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_CbCr8"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGB8888To420Yp8_CbCr8(_:_:_:_:_:_:)/fragments"},{"op":"replace","value":"width","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/title"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1width/fragments"},{"op":"replace","value":"vImageConvert_ARGB8888To420Yp8_Cb8_Cr8","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)/title"},{"op":"replace","value":[{"kind":"identifier","text":"vImageConvert_ARGB8888To420Yp8_Cb8_Cr8"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImageConvert_ARGB8888To420Yp8_Cb8_Cr8(_:_:_:_:_:_:_:)/fragments"},{"op":"replace","value":"kvImageNoFlags","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/title"},{"op":"replace","value":[{"text":"kvImageNoFlags","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1kvImageNoFlags/fragments"},{"op":"replace","value":"rowBytes","path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/title"},{"op":"replace","value":[{"kind":"identifier","text":"rowBytes"}],"path":"/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vImage_Buffer~1rowBytes/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}