{
  "abstract": [
    {
      "text": "64-bit left rotate with two rotation factors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate2(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vL64Rotate2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vL64Rotate2"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vUInt32",
        "text": "vUInt32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vUInt8",
        "text": "vUInt8"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vUInt32",
        "text": "vUInt32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vL64Rotate2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vL64Rotate2(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vL64Rotate2"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vUInt32",
              "text": "vUInt32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vRotateFactor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt8",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vUInt8",
              "text": "vUInt8"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vUInt32",
              "text": "vUInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The vector to shift.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vA"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of bits to shift the vector.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vRotateFactor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the shifted vector.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function treats the vector as a pair of 64-bit values to rotate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vA128Shift(_:_:)": {
      "abstract": [
        {
          "text": "128-bit arithmetic (signed) shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vA128Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vA128Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vA128Shift"
        }
      ],
      "role": "symbol",
      "title": "vA128Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/va128shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift(_:_:)": {
      "abstract": [
        {
          "text": "64-bit arithmetic (signed) shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vA64Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vA64Shift"
        }
      ],
      "role": "symbol",
      "title": "vA64Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/va64shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift2(_:_:)": {
      "abstract": [
        {
          "text": "64-bit arithmetic (signed) shift with two shift factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vA64Shift2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vA64Shift2"
        }
      ],
      "role": "symbol",
      "title": "vA64Shift2(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/va64shift2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vL128Rotate(_:_:)": {
      "abstract": [
        {
          "text": "128-bit left rotate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vL128Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vL128Rotate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vL128Rotate"
        }
      ],
      "role": "symbol",
      "title": "vL128Rotate(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vl128rotate(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate(_:_:)": {
      "abstract": [
        {
          "text": "64-bit left rotate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vL64Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vL64Rotate"
        }
      ],
      "role": "symbol",
      "title": "vL64Rotate(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vl64rotate(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate2(_:_:)": {
      "abstract": [
        {
          "text": "64-bit left rotate with two rotation factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vL64Rotate2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vL64Rotate2"
        }
      ],
      "role": "symbol",
      "title": "vL64Rotate2(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vl64rotate2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLL128Shift(_:_:)": {
      "abstract": [
        {
          "text": "128-bit logical left shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLL128Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLL128Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLL128Shift"
        }
      ],
      "role": "symbol",
      "title": "vLL128Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vll128shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift(_:_:)": {
      "abstract": [
        {
          "text": "64-bit logical left shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLL64Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLL64Shift"
        }
      ],
      "role": "symbol",
      "title": "vLL64Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vll64shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift2(_:_:)": {
      "abstract": [
        {
          "text": "64-bit logical left shift with two shift factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLL64Shift2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLL64Shift2"
        }
      ],
      "role": "symbol",
      "title": "vLL64Shift2(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vll64shift2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLR128Shift(_:_:)": {
      "abstract": [
        {
          "text": "128-bit logical right shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLR128Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLR128Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLR128Shift"
        }
      ],
      "role": "symbol",
      "title": "vLR128Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vlr128shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift(_:_:)": {
      "abstract": [
        {
          "text": "64-bit logical right shift.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLR64Shift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLR64Shift"
        }
      ],
      "role": "symbol",
      "title": "vLR64Shift(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vlr64shift(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift2(_:_:)": {
      "abstract": [
        {
          "text": "64-bit logical right shift with two shift factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vLR64Shift2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vLR64Shift2"
        }
      ],
      "role": "symbol",
      "title": "vLR64Shift2(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vlr64shift2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vR128Rotate(_:_:)": {
      "abstract": [
        {
          "text": "128-bit right rotate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vR128Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vR128Rotate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vR128Rotate"
        }
      ],
      "role": "symbol",
      "title": "vR128Rotate(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vr128rotate(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate(_:_:)": {
      "abstract": [
        {
          "text": "64-bit right rotate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vR64Rotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vR64Rotate"
        }
      ],
      "role": "symbol",
      "title": "vR64Rotate(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vr64rotate(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate2(_:_:)": {
      "abstract": [
        {
          "text": "64-bit right rotate with two rotation factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vR64Rotate2"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate2(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vR64Rotate2"
        }
      ],
      "role": "symbol",
      "title": "vR64Rotate2(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vr64rotate2(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vUInt32": {
      "abstract": [
        {
          "text": "A 128-bit vector packed with ",
          "type": "text"
        },
        {
          "code": "unsigned int",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vUInt32"
        }
      ],
      "role": "symbol",
      "title": "vUInt32",
      "type": "topic",
      "url": "/documentation/accelerate/vuint32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vUInt8": {
      "abstract": [
        {
          "text": "A 128-bit vector packed with ",
          "type": "text"
        },
        {
          "code": "unsigned char",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vUInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vUInt8"
        }
      ],
      "role": "symbol",
      "title": "vUInt8",
      "type": "topic",
      "url": "/documentation/accelerate/vuint8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shift-and-Rotate-Functions-from-vBasicOpsh",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vLL128Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vLR128Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift2(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift2(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift2(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vA128Shift(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate2(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vL128Rotate(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vR128Rotate(_:_:)"
      ],
      "title": "Shift and Rotate Functions (from vBasicOps.h)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vL64Rotate2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vL64Rotate2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shift-and-Rotate-Functions-from-vBasicOpsh",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vLL128Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vLR128Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vLL64Shift2(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vLR64Shift2(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vA64Shift2(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vA128Shift(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vL64Rotate(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vR64Rotate2(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vL128Rotate(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vR128Rotate(_:_:)"
              ],
              "title": "Shift and Rotate Functions (from vBasicOps.h)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vUInt32",
                    "text": "vUInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vL64Rotate2"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vUInt32",
                    "text": "vUInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vA"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vUInt8",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vUInt8",
                    "text": "vUInt8"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vRotateFactor"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The vector to shift.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vA"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of bits to shift the vector.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vRotateFactor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns the shifted vector.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR64Shift2(_:_:)/title",
          "value": "vLR64Shift2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR64Shift2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLR64Shift2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL64Rotate(_:_:)/title",
          "value": "vL64Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL64Rotate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vL64Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL64Shift(_:_:)/title",
          "value": "vLL64Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL64Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLL64Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL128Shift(_:_:)/title",
          "value": "vLL128Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL128Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLL128Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL128Rotate(_:_:)/title",
          "value": "vL128Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL128Rotate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vL128Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR64Rotate2(_:_:)/title",
          "value": "vR64Rotate2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR64Rotate2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vR64Rotate2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR128Rotate(_:_:)/title",
          "value": "vR128Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR128Rotate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vR128Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR64Shift(_:_:)/title",
          "value": "vLR64Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR64Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLR64Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL64Shift2(_:_:)/title",
          "value": "vLL64Shift2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLL64Shift2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLL64Shift2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt8/title",
          "value": "vUInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vUInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vUInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL64Rotate2(_:_:)/title",
          "value": "vL64Rotate2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vL64Rotate2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vL64Rotate2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA64Shift(_:_:)/title",
          "value": "vA64Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA64Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vA64Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR64Rotate(_:_:)/title",
          "value": "vR64Rotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vR64Rotate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vR64Rotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR128Shift(_:_:)/title",
          "value": "vLR128Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vLR128Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vLR128Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA128Shift(_:_:)/title",
          "value": "vA128Shift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA128Shift(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vA128Shift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt32/title",
          "value": "vUInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vUInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vUInt32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vUInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA64Shift2(_:_:)/title",
          "value": "vA64Shift2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vA64Shift2(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vA64Shift2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vl64rotate2(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vl64rotate2(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
