{
  "abstract": [
    {
      "text": "Signed 16-bit division.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vS16Divide(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vS16Divide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vS16Divide"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt16",
        "text": "vSInt16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt16",
        "text": "vSInt16"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt16",
        "text": "vSInt16"
      },
      {
        "kind": "text",
        "text": ">?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt16",
        "text": "vSInt16"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vS16Divide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vS16Divide(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vS16Divide"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vN"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt16",
              "text": "vSInt16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vD"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt16",
              "text": "vSInt16"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vRemainder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt16",
              "text": "vSInt16"
            },
            {
              "kind": "text",
              "text": ">?) -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt16",
              "text": "vSInt16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS128Add(_:_:)": {
      "abstract": [
        {
          "text": "Signed 128-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS128Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS128Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS128Add"
        }
      ],
      "role": "symbol",
      "title": "vS128Add(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs128add(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS128AddS(_:_:)": {
      "abstract": [
        {
          "text": "Signed 128-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS128AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS128AddS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS128AddS"
        }
      ],
      "role": "symbol",
      "title": "vS128AddS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs128adds(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS128Sub(_:_:)": {
      "abstract": [
        {
          "text": "Signed 128-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS128Sub"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS128Sub(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS128Sub"
        }
      ],
      "role": "symbol",
      "title": "vS128Sub(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs128sub(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS128SubS(_:_:)": {
      "abstract": [
        {
          "text": "Signed 128-bit subtraction with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS128SubS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS128SubS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS128SubS"
        }
      ],
      "role": "symbol",
      "title": "vS128SubS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs128subs(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS16Divide(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 16-bit division.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS16Divide"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt16",
          "text": "vSInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt16",
          "text": "vSInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt16",
          "text": "vSInt16"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt16",
          "text": "vSInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS16Divide(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS16Divide"
        }
      ],
      "role": "symbol",
      "title": "vS16Divide(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs16divide(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS64Add": {
      "abstract": [
        {
          "text": "Signed 64-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vS64Add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS64Add",
      "kind": "symbol",
      "role": "symbol",
      "title": "vS64Add",
      "type": "topic",
      "url": "/documentation/accelerate/vs64add"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS64AddS(_:_:)": {
      "abstract": [
        {
          "text": "Signed 64-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS64AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS64AddS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS64AddS"
        }
      ],
      "role": "symbol",
      "title": "vS64AddS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs64adds(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS64Sub": {
      "abstract": [
        {
          "text": "Signed 64-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vS64Sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS64Sub",
      "kind": "symbol",
      "role": "symbol",
      "title": "vS64Sub",
      "type": "topic",
      "url": "/documentation/accelerate/vs64sub"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS64SubS(_:_:)": {
      "abstract": [
        {
          "text": "Signed 64-bit subtraction with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS64SubS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS64SubS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS64SubS"
        }
      ],
      "role": "symbol",
      "title": "vS64SubS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs64subs(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS8HalfMultiply(_:_:)": {
      "abstract": [
        {
          "text": "Signed 8-bit multiplication; results are same width as multiplicands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS8HalfMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt8",
          "text": "vSInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt8",
          "text": "vSInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt8",
          "text": "vSInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS8HalfMultiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS8HalfMultiply"
        }
      ],
      "role": "symbol",
      "title": "vS8HalfMultiply(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs8halfmultiply(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vSInt16": {
      "abstract": [
        {
          "text": "A 128-bit vector packed with ",
          "type": "text"
        },
        {
          "code": "signed short",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vSInt16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vSInt16"
        }
      ],
      "role": "symbol",
      "title": "vSInt16",
      "type": "topic",
      "url": "/documentation/accelerate/vsint16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128Add(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 128-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU128Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128Add(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU128Add"
        }
      ],
      "role": "symbol",
      "title": "vU128Add(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128add(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128AddS(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 128-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU128AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128AddS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU128AddS"
        }
      ],
      "role": "symbol",
      "title": "vU128AddS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128adds(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128Sub(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 128-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU128Sub"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128Sub(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU128Sub"
        }
      ],
      "role": "symbol",
      "title": "vU128Sub(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128sub(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128SubS(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 128-bit subtraction with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU128SubS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128SubS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU128SubS"
        }
      ],
      "role": "symbol",
      "title": "vU128SubS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128subs(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU32HalfMultiply(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 32-bit multiplication; results are same width as multiplicands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU32HalfMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU32HalfMultiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU32HalfMultiply"
        }
      ],
      "role": "symbol",
      "title": "vU32HalfMultiply(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu32halfmultiply(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU64Add": {
      "abstract": [
        {
          "text": "Unsigned 64-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vU64Add"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU64Add",
      "kind": "symbol",
      "role": "symbol",
      "title": "vU64Add",
      "type": "topic",
      "url": "/documentation/accelerate/vu64add"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU64AddS(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 64-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU64AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU64AddS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU64AddS"
        }
      ],
      "role": "symbol",
      "title": "vU64AddS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu64adds(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU64Sub": {
      "abstract": [
        {
          "text": "Unsigned 64-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "vU64Sub"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU64Sub",
      "kind": "symbol",
      "role": "symbol",
      "title": "vU64Sub",
      "type": "topic",
      "url": "/documentation/accelerate/vu64sub"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU64SubS(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 64-bit subtraction with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU64SubS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU64SubS(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU64SubS"
        }
      ],
      "role": "symbol",
      "title": "vU64SubS(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu64subs(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU8HalfMultiply(_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 8-bit multiplication; results are same width as multiplicands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU8HalfMultiply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt8",
          "text": "vUInt8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU8HalfMultiply(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU8HalfMultiply"
        }
      ],
      "role": "symbol",
      "title": "vU8HalfMultiply(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu8halfmultiply(_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Integer-Arithmetic-Functions-from-vBasicOpsh",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU64AddS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS64AddS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128Add(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128AddS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS128Add(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS128AddS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU64SubS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS64SubS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128Sub(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128SubS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS128Sub(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS128SubS(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU8HalfMultiply(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS8HalfMultiply(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU32HalfMultiply(_:_:)"
      ],
      "title": "Integer Arithmetic Functions (from vBasicOps.h)"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vS16Divide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS16Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Integer-Arithmetic-Functions-from-vBasicOpsh",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU64Add",
                "doc://com.apple.accelerate/documentation/Accelerate/vU64AddS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS64Add",
                "doc://com.apple.accelerate/documentation/Accelerate/vS64AddS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128Add(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128AddS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS128Add(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS128AddS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU64Sub",
                "doc://com.apple.accelerate/documentation/Accelerate/vU64SubS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS64Sub",
                "doc://com.apple.accelerate/documentation/Accelerate/vS64SubS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128Sub(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128SubS(_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS128Sub(_:_:)"
              ],
              "title": "Integer Arithmetic Functions (from vBasicOps.h)"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt16",
                    "text": "vSInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vS16Divide"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt16",
                    "text": "vSInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vN"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt16",
                    "text": "vSInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vD"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt16",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt16",
                    "text": "vSInt16"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vRemainder"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128SubS(_:_:)/title",
          "value": "vS128SubS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128SubS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128SubS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128Sub(_:_:)/title",
          "value": "vU128Sub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128Sub(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128Sub"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128AddS(_:_:)/title",
          "value": "vU128AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128AddS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS16Divide(_:_:_:)/title",
          "value": "vS16Divide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS16Divide(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS16Divide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU64AddS(_:_:)/title",
          "value": "vU64AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU64AddS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU64AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64SubS(_:_:)/title",
          "value": "vS64SubS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64SubS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS64SubS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64AddS(_:_:)/title",
          "value": "vS64AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64AddS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS64AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU32HalfMultiply(_:_:)/title",
          "value": "vU32HalfMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU32HalfMultiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU32HalfMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128AddS(_:_:)/title",
          "value": "vS128AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128AddS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128Add(_:_:)/title",
          "value": "vU128Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128Sub(_:_:)/title",
          "value": "vS128Sub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128Sub(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128Sub"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt16/title",
          "value": "vSInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vSInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vSInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU64SubS(_:_:)/title",
          "value": "vU64SubS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU64SubS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU64SubS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS8HalfMultiply(_:_:)/title",
          "value": "vS8HalfMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS8HalfMultiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS8HalfMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128Add(_:_:)/title",
          "value": "vS128Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128Add(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128SubS(_:_:)/title",
          "value": "vU128SubS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128SubS(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128SubS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU8HalfMultiply(_:_:)/title",
          "value": "vU8HalfMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU8HalfMultiply(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU8HalfMultiply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vs16divide(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vs16divide(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
