{
  "abstract": [
    {
      "text": "Signed 64-bit negation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vS64Neg(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@vS64Neg",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vS64Neg"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt32",
        "text": "vSInt32"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@vSInt32",
        "text": "vSInt32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vS64Neg"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "vS64Neg(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vS64Neg"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt32",
              "text": "vSInt32"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt32",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@vSInt32",
              "text": "vSInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The value to negate.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vA"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the negated value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS1024Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 1024-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS1024Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS1024Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS1024Add"
        }
      ],
      "role": "symbol",
      "title": "vS1024Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs1024add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS1024AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 1024-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS1024AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS1024",
          "text": "vS1024"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS1024AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS1024AddS"
        }
      ],
      "role": "symbol",
      "title": "vS1024AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs1024adds(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 256-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS256Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS256Add"
        }
      ],
      "role": "symbol",
      "title": "vS256Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs256add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 256-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS256AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS256AddS"
        }
      ],
      "role": "symbol",
      "title": "vS256AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs256adds(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256Sub(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 256-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS256Sub"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256Sub(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS256Sub"
        }
      ],
      "role": "symbol",
      "title": "vS256Sub(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs256sub(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS512Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 512-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS512Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS512Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS512Add"
        }
      ],
      "role": "symbol",
      "title": "vS512Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs512add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS512AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Signed 512-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS512AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS512",
          "text": "vS512"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS512AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS512AddS"
        }
      ],
      "role": "symbol",
      "title": "vS512AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs512adds(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS64Neg(_:)": {
      "abstract": [
        {
          "text": "Signed 64-bit negation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS64Neg"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vSInt32",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS64Neg(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS64Neg"
        }
      ],
      "role": "symbol",
      "title": "vS64Neg(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vs64neg(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vSInt32": {
      "abstract": [
        {
          "text": "A 128-bit vector packed with ",
          "type": "text"
        },
        {
          "code": "signed int",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vSInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vSInt32"
        }
      ],
      "role": "symbol",
      "title": "vSInt32",
      "type": "topic",
      "url": "/documentation/accelerate/vsint32"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 1024-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU1024Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU1024Add"
        }
      ],
      "role": "symbol",
      "title": "vU1024Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 1024-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU1024AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU1024AddS"
        }
      ],
      "role": "symbol",
      "title": "vU1024AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024adds(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU256Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 256-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU256Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU256Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU256Add"
        }
      ],
      "role": "symbol",
      "title": "vU256Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu256add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU256AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 256-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU256AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU256AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU256AddS"
        }
      ],
      "role": "symbol",
      "title": "vU256AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu256adds(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU256Sub(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 256-bit subtraction (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU256Sub"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU256Sub(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU256Sub"
        }
      ],
      "role": "symbol",
      "title": "vU256Sub(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu256sub(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU256SubS(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 256-bit subtraction with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU256SubS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU256",
          "text": "vU256"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU256SubS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU256SubS"
        }
      ],
      "role": "symbol",
      "title": "vU256SubS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu256subs(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU512Add(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 512-bit addition (modular arithmetic).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU512Add"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU512Add(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU512Add"
        }
      ],
      "role": "symbol",
      "title": "vU512Add(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu512add(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU512AddS(_:_:_:)": {
      "abstract": [
        {
          "text": "Unsigned 512-bit addition with saturation (clipping).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU512AddS"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU512",
          "text": "vU512"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU512AddS(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU512AddS"
        }
      ],
      "role": "symbol",
      "title": "vU512AddS(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu512adds(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Performing-arithmetic-operations-on-large-integers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU256Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU256AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU512Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU512AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS512Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS512AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS1024Add(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS1024AddS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU256Sub(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU256SubS(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256Sub(_:_:_:)"
      ],
      "title": "Performing arithmetic operations on large integers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vS64Neg"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS64Neg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Performing-arithmetic-operations-on-large-integers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU256Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU256AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU512Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU512AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS512Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS512AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS1024Add(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS1024AddS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU256Sub(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vU256SubS(_:_:_:)",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256Sub(_:_:_:)"
              ],
              "title": "Performing arithmetic operations on large integers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt32",
                    "text": "vSInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vS64Neg"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vSInt32",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@vSInt32",
                    "text": "vSInt32"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vA"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The value to negate.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vA"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns the negated value.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024Add(_:_:_:)/title",
          "value": "vS1024Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS1024Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024AddS(_:_:_:)/title",
          "value": "vS1024AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS1024AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256Sub(_:_:_:)/title",
          "value": "vU256Sub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256Sub(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256Sub"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512Add(_:_:_:)/title",
          "value": "vS512Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS512Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024Add(_:_:_:)/title",
          "value": "vU1024Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256Add(_:_:_:)/title",
          "value": "vU256Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256AddS(_:_:_:)/title",
          "value": "vU256AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512Add(_:_:_:)/title",
          "value": "vU512Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU512Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt32/title",
          "value": "vSInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vSInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vSInt32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vSInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024AddS(_:_:_:)/title",
          "value": "vU1024AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256SubS(_:_:_:)/title",
          "value": "vU256SubS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256SubS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256SubS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256AddS(_:_:_:)/title",
          "value": "vS256AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256Add(_:_:_:)/title",
          "value": "vS256Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256Add(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512AddS(_:_:_:)/title",
          "value": "vS512AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS512AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512AddS(_:_:_:)/title",
          "value": "vU512AddS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512AddS(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU512AddS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64Neg(_:)/title",
          "value": "vS64Neg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS64Neg(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS64Neg"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256Sub(_:_:_:)/title",
          "value": "vS256Sub"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256Sub(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256Sub"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vs64neg(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vs64neg(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
