{
  "abstract": [
    {
      "text": "A union containing one ",
      "type": "text"
    },
    {
      "code": "vUInt32",
      "type": "codeVoice"
    },
    {
      "text": " vector or four 32-bit integers, representing a 128-bit unsigned integer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vU128"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@U@vU128",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vU128"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vU128"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "vU128"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vU128"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS1024": {
      "abstract": [
        {
          "text": "A union containing an array or structure of eight ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or thirty-two 32-bit integers, representing a 1024-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS1024"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS1024",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS1024"
        }
      ],
      "role": "symbol",
      "title": "vS1024",
      "type": "topic",
      "url": "/documentation/accelerate/vs1024"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS128": {
      "abstract": [
        {
          "text": "A union containing one ",
          "type": "text"
        },
        {
          "code": "vSInt32",
          "type": "codeVoice"
        },
        {
          "text": " vector or four 32-bit integers, representing a 128-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS128"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS128"
        }
      ],
      "role": "symbol",
      "title": "vS128",
      "type": "topic",
      "url": "/documentation/accelerate/vs128"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256": {
      "abstract": [
        {
          "text": "A union containing an array or structure of two ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or eight 32-bit integers, representing a 256-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS256"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS256"
        }
      ],
      "role": "symbol",
      "title": "vS256",
      "type": "topic",
      "url": "/documentation/accelerate/vs256"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS512": {
      "abstract": [
        {
          "text": "A union containing an array or structure of four ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or sixteen 32-bit integers, representing a 256-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS512"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS512"
        }
      ],
      "role": "symbol",
      "title": "vS512",
      "type": "topic",
      "url": "/documentation/accelerate/vs512"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024": {
      "abstract": [
        {
          "text": "A union containing an array or structure of eight ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or thirty-two 32-bit integers, representing a 1024-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "role": "symbol",
      "title": "vU1024",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128": {
      "abstract": [
        {
          "text": "A union containing one ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vector or four 32-bit integers, representing a 128-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU128"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU128"
        }
      ],
      "role": "symbol",
      "title": "vU128",
      "type": "topic",
      "url": "/documentation/accelerate/vu128"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/init()"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(s:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "s"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU128",
          "text": "vU128"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_s"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(s:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(s:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/init(s:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(v:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(v:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(v:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/init(v:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(vs:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "vs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU128",
          "text": "vU128"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_vs"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(vs:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(vs:)",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/init(vs:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "s"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU128",
          "text": "vU128"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_s"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "s"
        }
      ],
      "role": "symbol",
      "title": "s",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/v": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "v"
        }
      ],
      "role": "symbol",
      "title": "v",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/v"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU128",
          "text": "vU128"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_vs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vs"
        }
      ],
      "role": "symbol",
      "title": "vs",
      "type": "topic",
      "url": "/documentation/accelerate/vu128/vs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU256": {
      "abstract": [
        {
          "text": "A union containing an array or structure of two ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or eight 32-bit integers, representing a 256-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU256"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU256"
        }
      ],
      "role": "symbol",
      "title": "vU256",
      "type": "topic",
      "url": "/documentation/accelerate/vu256"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU512": {
      "abstract": [
        {
          "text": "A union containing an array or structure of four ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or sixteen 32-bit integers, representing a 256-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU512"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU512"
        }
      ],
      "role": "symbol",
      "title": "vU512",
      "type": "topic",
      "url": "/documentation/accelerate/vu512"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vS128",
        "doc://com.apple.accelerate/documentation/Accelerate/vU256",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256",
        "doc://com.apple.accelerate/documentation/Accelerate/vU512",
        "doc://com.apple.accelerate/documentation/Accelerate/vS512",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
        "doc://com.apple.accelerate/documentation/Accelerate/vS1024"
      ],
      "title": "Data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/s",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/v",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/s",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/v"
      ],
      "title": "Miscellaneous"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/init()",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(s:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(v:)",
        "doc://com.apple.accelerate/documentation/Accelerate/vU128/init(vs:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Union"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vU128"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "union"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/s",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/v",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/s",
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/vs"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU128/v"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vS128",
                "doc://com.apple.accelerate/documentation/Accelerate/vU256",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256",
                "doc://com.apple.accelerate/documentation/Accelerate/vU512",
                "doc://com.apple.accelerate/documentation/Accelerate/vS512",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
                "doc://com.apple.accelerate/documentation/Accelerate/vS1024"
              ],
              "title": "Data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "union"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vU128"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128/title",
          "value": "vS128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS128/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vS128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1v/title",
          "value": "v"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "v"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512/title",
          "value": "vU512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU512/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256/title",
          "value": "vU256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU256/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/title",
          "value": "vS256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1vs/title",
          "value": "vs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1vs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/title",
          "value": "vU1024"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024/title",
          "value": "vS1024"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS1024/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vS1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1s/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128~1s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128/title",
          "value": "vU128"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU128/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU128"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512/title",
          "value": "vS512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS512/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vS512"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vu128"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vu128"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
