package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tmc/appledocs"
)

// TypeGenerator generates Go types from Apple documentation JSON files
type TypeGenerator struct {
	schemas      map[string]*Schema
	packageName  string
	outputPath   string
	scannedFiles int
}

// Schema represents a discovered JSON schema
type Schema struct {
	Name   string
	Fields map[string]*FieldInfo
}

// FieldInfo contains information about a JSON field
type FieldInfo struct {
	GoType     string
	JSONType   string
	IsOptional bool
	IsArray    bool
	Example    interface{}
}

// NewTypeGenerator creates a new type generator
func NewTypeGenerator(packageName, outputPath string) *TypeGenerator {
	return &TypeGenerator{
		schemas:     make(map[string]*Schema),
		packageName: packageName,
		outputPath:  outputPath,
	}
}

// ScanDirectory scans JSON files to discover schemas
func (g *TypeGenerator) ScanDirectory(docsPath string, maxFiles int) error {
	fsys, err := appledocs.Open(docsPath)
	if err != nil {
		return fmt.Errorf("open docs: %w", err)
	}

	log.Printf("Scanning %s for JSON schemas...", docsPath)

	count := 0
	err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			return nil
		}

		if !strings.HasSuffix(path, ".json") {
			return nil
		}

		if maxFiles > 0 && count >= maxFiles {
			return filepath.SkipDir
		}

		// Read and analyze the JSON file
		if err := g.analyzeJSONFile(fsys, path); err != nil {
			log.Printf("Warning: failed to analyze %s: %v", path, err)
		}

		count++
		if count%100 == 0 {
			log.Printf("Scanned %d files, found %d schemas", count, len(g.schemas))
		}

		return nil
	})

	g.scannedFiles = count
	log.Printf("Scanned %d JSON files, discovered %d unique schemas", count, len(g.schemas))

	return err
}

// analyzeJSONFile analyzes a single JSON file and updates schemas
func (g *TypeGenerator) analyzeJSONFile(fsys *appledocs.FS, path string) error {
	data, err := fsys.ReadFile(path)
	if err != nil {
		return err
	}

	var doc map[string]interface{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return err
	}

	// Analyze the root document schema
	g.analyzeObject("Document", doc, 0)

	return nil
}

// analyzeObject recursively analyzes an object and records its schema
func (g *TypeGenerator) analyzeObject(name string, obj map[string]interface{}, depth int) {
	if depth > 5 {
		return // Prevent infinite recursion
	}

	// Get or create schema
	schema, exists := g.schemas[name]
	if !exists {
		schema = &Schema{
			Name:   name,
			Fields: make(map[string]*FieldInfo),
		}
		g.schemas[name] = schema
	}

	// Analyze each field
	for key, value := range obj {
		fieldName := toGoFieldName(key)

		// Get or create field info
		field, fieldExists := schema.Fields[fieldName]
		if !fieldExists {
			field = &FieldInfo{
				JSONType:   key,
				IsOptional: true, // Assume optional until proven otherwise
			}
			schema.Fields[fieldName] = field
		}

		// Determine Go type from value
		goType, isArray := inferGoType(value)
		if goType != "" {
			if field.GoType == "" {
				field.GoType = goType
				field.IsArray = isArray
			} else if field.GoType != goType {
				// Type conflict - use interface{}
				field.GoType = "interface{}"
				field.IsArray = false
			}
		}

		// Save example
		field.Example = value

		// Recursively analyze nested objects
		if nestedMap, ok := value.(map[string]interface{}); ok {
			nestedName := name + toGoTypeName(key)
			g.analyzeObject(nestedName, nestedMap, depth+1)
		}

		// Analyze array elements
		if arr, ok := value.([]interface{}); ok && len(arr) > 0 {
			if elem, ok := arr[0].(map[string]interface{}); ok {
				elemName := name + toGoTypeName(key) + "Element"
				g.analyzeObject(elemName, elem, depth+1)
			}
		}
	}
}

// GenerateTypes generates Go type definitions
func (g *TypeGenerator) GenerateTypes() error {
	// Ensure output directory exists
	if err := os.MkdirAll(filepath.Dir(g.outputPath), 0755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	var buf strings.Builder

	// Package declaration
	fmt.Fprintf(&buf, "// Code generated by gentypes. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", g.packageName)

	// Get sorted schema names
	names := make([]string, 0, len(g.schemas))
	for name := range g.schemas {
		names = append(names, name)
	}
	sort.Strings(names)

	// Generate each type
	for _, name := range names {
		schema := g.schemas[name]
		g.generateType(&buf, schema)
		fmt.Fprintln(&buf)
	}

	// Format the generated code
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		// Write unformatted code for debugging
		return os.WriteFile(g.outputPath, []byte(buf.String()), 0644)
	}

	// Write formatted code
	return os.WriteFile(g.outputPath, formatted, 0644)
}

// generateType generates a single Go type definition
func (g *TypeGenerator) generateType(buf *strings.Builder, schema *Schema) {
	// Type comment with field count
	fmt.Fprintf(buf, "// %s contains %d fields\n", schema.Name, len(schema.Fields))
	fmt.Fprintf(buf, "type %s struct {\n", schema.Name)

	// Get sorted field names
	fieldNames := make([]string, 0, len(schema.Fields))
	for name := range schema.Fields {
		fieldNames = append(fieldNames, name)
	}
	sort.Strings(fieldNames)

	// Generate each field
	for _, fieldName := range fieldNames {
		field := schema.Fields[fieldName]

		// Field comment with JSON type
		if field.Example != nil {
			fmt.Fprintf(buf, "\t// %s example: %v\n", fieldName, truncateExample(field.Example))
		}

		// Field declaration
		goType := field.GoType
		if goType == "" {
			goType = "interface{}"
		}
		if field.IsArray {
			goType = "[]" + goType
		}

		jsonTag := fmt.Sprintf("`json:\"%s", field.JSONType)
		if field.IsOptional {
			jsonTag += ",omitempty"
		}
		jsonTag += "\"`"

		fmt.Fprintf(buf, "\t%s %s %s\n", fieldName, goType, jsonTag)
	}

	fmt.Fprintf(buf, "}\n")
}

// inferGoType infers the Go type from a JSON value
func inferGoType(value interface{}) (string, bool) {
	if value == nil {
		return "interface{}", false
	}

	switch v := value.(type) {
	case bool:
		return "bool", false
	case float64:
		// JSON numbers are always float64
		if v == float64(int64(v)) {
			return "int", false
		}
		return "float64", false
	case string:
		return "string", false
	case []interface{}:
		if len(v) == 0 {
			return "interface{}", true
		}
		// Infer type from first element
		elemType, _ := inferGoType(v[0])
		return elemType, true
	case map[string]interface{}:
		return "map[string]interface{}", false
	default:
		return "interface{}", false
	}
}

// toGoFieldName converts a JSON field name to a Go field name
func toGoFieldName(name string) string {
	return toGoTypeName(name)
}

// toGoTypeName converts a string to a Go type name (PascalCase)
func toGoTypeName(s string) string {
	if s == "" {
		return ""
	}

	// Split on underscores and hyphens
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})

	// Capitalize each part
	for i, part := range parts {
		if part == "" {
			continue
		}
		// Handle common acronyms
		switch strings.ToUpper(part) {
		case "ID", "URL", "URI", "JSON", "XML", "HTML", "API", "HTTP", "HTTPS":
			parts[i] = strings.ToUpper(part)
		default:
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}

	return strings.Join(parts, "")
}

// truncateExample truncates an example value for display
func truncateExample(v interface{}) string {
	s := fmt.Sprintf("%v", v)
	if len(s) > 50 {
		return s[:47] + "..."
	}
	return s
}

// generateTypes is the main entry point for type generation
func generateTypes(docsPath, outputPath string, maxFiles int) error {
	// Create type generator
	gen := NewTypeGenerator("appledocs", outputPath)

	// Scan directory to discover schemas
	if err := gen.ScanDirectory(docsPath, maxFiles); err != nil {
		return fmt.Errorf("scan directory: %w", err)
	}

	// Generate type definitions
	if err := gen.GenerateTypes(); err != nil {
		return fmt.Errorf("generate types: %w", err)
	}

	log.Printf("Generated %d types in %s", len(gen.schemas), outputPath)
	return nil
}
