{
  "abstract": [
    {
      "text": "Creates a new beacon identity condition with the identifier, and major and minor values you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corelocation/documentation/CoreLocation",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:minor:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLBeaconIdentityCondition(im)initWithUUID:major:minor:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithUUID:major:minor:"
      }
    ],
    "modules": [
      {
        "name": "Core Location"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithUUID:major:minor:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithUUID:major:minor:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithUUID:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUUID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSUUID",
              "text": "NSUUID"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "uuid"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "major:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMajorValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLBeaconMajorValue",
              "text": "CLBeaconMajorValue"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "major"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "minor:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMinorValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CLBeaconMinorValue",
              "text": "CLBeaconMinorValue"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "minor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/UUID",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to use as the beacon’s identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "uuid"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMajorValue",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to use as the beacon’s major value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "major"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMinorValue",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to use as the beacon’s minor value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "minor"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.corelocation/documentation/CoreLocation": {
      "abstract": [
        {
          "text": "Obtain the geographic location and orientation of a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Location",
      "type": "topic",
      "url": "/documentation/corelocation"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition": {
      "abstract": [
        {
          "text": "A condition that describes the identity characteristics of a beacon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CLBeaconIdentityCondition"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition",
      "kind": "symbol",
      "role": "symbol",
      "title": "CLBeaconIdentityCondition",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/UUID": {
      "abstract": [
        {
          "text": "A universally unique identifier that represent the beacon’s identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/UUID",
      "kind": "symbol",
      "role": "symbol",
      "title": "UUID",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition/uuid"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:": {
      "abstract": [
        {
          "text": "Creates a new beacon identity condition with the identifier you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithUUID:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUUID:"
        }
      ],
      "role": "symbol",
      "title": "initWithUUID:",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition/initwithuuid:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:": {
      "abstract": [
        {
          "text": "Creates a new beacon identity condition with the identifier and major value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithUUID:major:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUUID:major:"
        }
      ],
      "role": "symbol",
      "title": "initWithUUID:major:",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition/initwithuuid:major:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:minor:": {
      "abstract": [
        {
          "text": "Creates a new beacon identity condition with the identifier, and major and minor values you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithUUID:major:minor:"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:minor:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUUID:major:minor:"
        }
      ],
      "role": "symbol",
      "title": "initWithUUID:major:minor:",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconidentitycondition/initwithuuid:major:minor:"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMajorValue": {
      "abstract": [
        {
          "text": "The most significant value in a beacon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLBeaconMajorValue"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMajorValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLBeaconMajorValue"
        }
      ],
      "role": "symbol",
      "title": "CLBeaconMajorValue",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconmajorvalue"
    },
    "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMinorValue": {
      "abstract": [
        {
          "text": "The least significant value in a beacon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLBeaconMinorValue"
        }
      ],
      "identifier": "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconMinorValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLBeaconMinorValue"
        }
      ],
      "role": "symbol",
      "title": "CLBeaconMinorValue",
      "type": "topic",
      "url": "/documentation/corelocation/clbeaconminorvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSUUID": {
      "abstract": [
        {
          "text": "An object representing a universally unique value that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUUID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSUUID",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUUID",
      "type": "topic",
      "url": "/documentation/foundation/nsuuid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-beacon-identity-conditions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:",
        "doc://com.apple.corelocation/documentation/CoreLocation/CLBeaconIdentityCondition/initWithUUID:major:"
      ],
      "title": "Creating beacon identity conditions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMinorValue/title",
          "value": "CLBeaconMinorValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMinorValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconMinorValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMinorValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconMinorValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSUUID/abstract",
          "value": [
            {
              "text": "A universally unique value that can be used to identify types, interfaces, and other items.  ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMajorValue/title",
          "value": "CLBeaconMajorValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMajorValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconMajorValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corelocation~1documentation~1CoreLocation~1CLBeaconMajorValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLBeaconMajorValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocation/clbeaconidentitycondition/initwithuuid:major:minor:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
