{
  "abstract": [
    {
      "text": "The ovulation test detected a surge in estrogen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/estrogenSurge"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKCategoryValueOvulationTestResult@HKCategoryValueOvulationTestResultEstrogenSurge",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "estrogenSurge"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKCategoryValueOvulationTestResultEstrogenSurge"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKCategoryValueOvulationTestResult.estrogenSurge"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "estrogenSurge"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult": {
      "abstract": [
        {
          "text": "Categories that represent the result of an ovulation home test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResult"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResult"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/estrogenSurge": {
      "abstract": [
        {
          "text": "The ovulation test detected a surge in estrogen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estrogenSurge"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/estrogenSurge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResultEstrogenSurge"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult.estrogenSurge",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult/estrogensurge"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/indeterminate": {
      "abstract": [
        {
          "text": "The ovulation test is inconclusive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indeterminate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/indeterminate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResultIndeterminate"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult.indeterminate",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult/indeterminate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/luteinizingHormoneSurge": {
      "abstract": [
        {
          "text": "The ovulation test detected a surge in the luteinizing hormone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "luteinizingHormoneSurge"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/luteinizingHormoneSurge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResultLuteinizingHormoneSurge"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult.luteinizingHormoneSurge",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult/luteinizinghormonesurge"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/negative": {
      "abstract": [
        {
          "text": "The ovulation test is negative.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negative"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/negative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResultNegative"
        }
      ],
      "role": "symbol",
      "title": "HKCategoryValueOvulationTestResult.negative",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult/negative"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/positive": {
      "abstract": [
        {
          "text": "The ovulation test is positive.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HKCategoryValueOvulationTestResult",
          "text": "HKCategoryValueOvulationTestResult"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/positive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKCategoryValueOvulationTestResultPositive"
        }
      ],
      "role": "symbol",
      "title": "positive",
      "type": "topic",
      "url": "/documentation/healthkit/hkcategoryvalueovulationtestresult/positive"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Ovulation-Test-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/negative",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/luteinizingHormoneSurge",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/indeterminate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/positive"
      ],
      "title": "Ovulation Test Results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKCategoryValueOvulationTestResultEstrogenSurge"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultEstrogenSurge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Ovulation-Test-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/negative",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/luteinizingHormoneSurge",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/indeterminate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKCategoryValueOvulationTestResult/positive"
              ],
              "title": "Ovulation Test Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKCategoryValueOvulationTestResultEstrogenSurge"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1luteinizingHormoneSurge/title",
          "value": "HKCategoryValueOvulationTestResultLuteinizingHormoneSurge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1luteinizingHormoneSurge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultLuteinizingHormoneSurge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1negative/title",
          "value": "HKCategoryValueOvulationTestResultNegative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1negative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultNegative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/title",
          "value": "HKCategoryValueOvulationTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1indeterminate/title",
          "value": "HKCategoryValueOvulationTestResultIndeterminate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1indeterminate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultIndeterminate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1estrogenSurge/title",
          "value": "HKCategoryValueOvulationTestResultEstrogenSurge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1estrogenSurge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultEstrogenSurge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1positive/title",
          "value": "HKCategoryValueOvulationTestResultPositive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKCategoryValueOvulationTestResult~1positive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKCategoryValueOvulationTestResultPositive"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvalueovulationtestresult/estrogensurge"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkcategoryvalueovulationtestresult/estrogensurge"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
