{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coremidi/midiumpmutablefunctionblock/setname(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/coremidi/midiumpmutablefunctionblock/setname(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremidi/documentation/CoreMIDI","doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock"]]},"identifier":{"url":"doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock/setName(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setName"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"setName:error:"}],"title":"setName(_:)","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"Core MIDI"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"18.0","deprecated":false,"beta":false},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"18.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0"},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"15.0"},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"2.0"}],"externalID":"c:objc(cs)MIDIUMPMutableFunctionBlock(im)setName:error:"},"kind":"symbol","references":{"doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock/setName(_:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"setName:error:"}],"title":"setName(_:)","kind":"symbol","identifier":"doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock/setName(_:)","url":"/documentation/coremidi/midiumpmutablefunctionblock/setname(_:)","abstract":[]},"doc://com.apple.coremidi/documentation/CoreMIDI":{"type":"topic","url":"/documentation/coremidi","title":"Core MIDI","abstract":[{"type":"text","text":"Communicate with MIDI devices such as hardware keyboards and synthesizers."}],"role":"collection","identifier":"doc://com.apple.coremidi/documentation/CoreMIDI","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"url":"/documentation/Swift/String","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"type":"topic","title":"String","kind":"symbol"},"doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock":{"url":"/documentation/coremidi/midiumpmutablefunctionblock","navigatorTitle":[{"kind":"identifier","text":"MIDIUMPMutableFunctionBlock"}],"kind":"symbol","identifier":"doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MIDIUMPMutableFunctionBlock"}],"type":"topic","abstract":[],"title":"MIDIUMPMutableFunctionBlock"},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"type":"topic","title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"18.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"18.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"18.0"},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false,"introducedAt":"15.0"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"2.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"setName:error:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setName:error:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremidi/documentation/CoreMIDI","doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPMutableFunctionBlock"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"setName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock~1setName(_:)/title","op":"replace","value":"setName:error:"},{"path":"/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock~1setName(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setName:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/title","op":"replace","value":"MIDIUMPMutableFunctionBlock"},{"path":"/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/fragments","op":"replace","value":[{"text":"MIDIUMPMutableFunctionBlock","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPMutableFunctionBlock/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MIDIUMPMutableFunctionBlock"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}