{
  "abstract": [
    {
      "text": "Sets the text field’s semantic meaning.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)WKInterfaceTextField(im)setTextContentType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setTextContentType"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@WKTextContentType",
        "text": "WKTextContentType"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setTextContentType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setTextContentType(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setTextContentType"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "textContentType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text field’s content type. Passing ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " clears the content type. For a list of possible content types, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "textContentType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The text field’s content type modifies how the text input controller and Apple Continuity Keyboard behave.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The input controller provides suggestions for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " content types, when available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The input controller displays a number pad for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " content types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The input controller disables dictation for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " content types.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The Apple Continuity Keyboard autofills data based on the content type. To share login credentials from your web page, set up an associated domain for your watchOS app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField": {
      "abstract": [
        {
          "text": "An interface element that displays an editable text area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKInterfaceTextField"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKInterfaceTextField"
        }
      ],
      "role": "symbol",
      "title": "WKInterfaceTextField",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacetextfield"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)": {
      "abstract": [
        {
          "text": "Sets the text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTextContentType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField/setTextContentType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTextContentType:"
        }
      ],
      "role": "symbol",
      "title": "setTextContentType(_:)",
      "type": "topic",
      "url": "/documentation/watchkit/wkinterfacetextfield/settextcontenttype(_:)"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType": {
      "abstract": [
        {
          "text": "Constants that specify a text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "role": "symbol",
      "title": "WKTextContentType",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber": {
      "abstract": [
        {
          "text": "A credit card number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/creditCardNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeCreditCardNumber"
        }
      ],
      "role": "symbol",
      "title": "creditCardNumber",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/creditcardnumber"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword": {
      "abstract": [
        {
          "text": "A new password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/newPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeNewPassword"
        }
      ],
      "role": "symbol",
      "title": "newPassword",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/newpassword"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode": {
      "abstract": [
        {
          "text": "A one-time code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/oneTimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeOneTimeCode"
        }
      ],
      "role": "symbol",
      "title": "oneTimeCode",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/onetimecode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password": {
      "abstract": [
        {
          "text": "An existing password.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/password",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypePassword"
        }
      ],
      "role": "symbol",
      "title": "password",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/password"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode": {
      "abstract": [
        {
          "text": "A postal code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypePostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/postalcode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber": {
      "abstract": [
        {
          "text": "A telephone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "telephoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/telephoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeTelephoneNumber"
        }
      ],
      "role": "symbol",
      "title": "telephoneNumber",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/telephonenumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-Content-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType"
      ],
      "title": "Specifying the Content Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setTextContentType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTextContentType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceTextField"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-Content-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType"
              ],
              "title": "Specifying the Content Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setTextContentType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@WKTextContentType",
                    "text": "WKTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "textContentType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The text field’s content type. Passing ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " clears the content type. For a list of possible content types, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "textContentType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1newPassword/title",
          "value": "WKTextContentTypeNewPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1newPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeNewPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1password/title",
          "value": "WKTextContentTypePassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1password/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypePassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1creditCardNumber/title",
          "value": "WKTextContentTypeCreditCardNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1creditCardNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeCreditCardNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/title",
          "value": "WKTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/title",
          "value": "WKInterfaceTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKInterfaceTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/title",
          "value": "WKTextContentTypePostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypePostalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1telephoneNumber/title",
          "value": "WKTextContentTypeTelephoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1telephoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeTelephoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField~1setTextContentType(_:)/title",
          "value": "setTextContentType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceTextField~1setTextContentType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTextContentType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/title",
          "value": "WKTextContentTypeOneTimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1oneTimeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeOneTimeCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkinterfacetextfield/settextcontenttype(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkinterfacetextfield/settextcontenttype(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
