{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"albumArtistPersistentID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MPMediaEntityPersistentID","text":"MPMediaEntityPersistentID"}],"modules":[{"name":"Media Player"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)MPMediaItem(py)albumArtistPersistentID","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"albumArtistPersistentID"}],"title":"albumArtistPersistentID","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"14.0"},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}]},"identifier":{"url":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtistPersistentID","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Media-item-properties","identifiers":["doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtist","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumPersistentID","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTitle","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackCount","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackNumber","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artist","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artistPersistentID","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artwork","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/assetURL","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/beatsPerMinute","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/bookmarkTime","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCloudItem","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/comments","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCompilation","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isPreorder"],"generated":true,"title":"Media item properties"}],"kind":"symbol","abstract":[{"type":"text","text":"The persistent identifier for the primary performing artist for an album."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/mediaplayer/mpmediaitem/albumartistpersistentid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/mediaplayer/mpmediaitem/albumartistpersistentid"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mediaplayer/documentation/MediaPlayer","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"albumArtistPersistentID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMediaEntityPersistentID","preciseIdentifier":"c:@T@MPMediaEntityPersistentID","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntityPersistentID","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtist":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"albumArtist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/mediaplayer/mpmediaitem/albumartist","title":"albumArtist","abstract":[{"text":"The primary performing artist for an album.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"albumArtist","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtist","role":"symbol"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/bookmarkTime":{"url":"/documentation/mediaplayer/mpmediaitem/bookmarktime","kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/bookmarkTime","abstract":[{"text":"The time of the user’s most recent interaction with the bookmark in the media item.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"bookmarkTime","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bookmarkTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}],"role":"symbol","title":"bookmarkTime"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artist":{"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artist","abstract":[{"text":"The performing artists for a media item, which may vary from the primary artist for the album that a media item belongs to.","type":"text"}],"url":"/documentation/mediaplayer/mpmediaitem/artist","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"artist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","title":"artist","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"artist"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntityPersistentID":{"title":"MPMediaEntityPersistentID","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntityPersistentID","role":"symbol","url":"/documentation/mediaplayer/mpmediaentitypersistentid","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMediaEntityPersistentID","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Defines the type for storing a persistent identifier to a particular entity.","type":"text"}],"navigatorTitle":[{"text":"MPMediaEntityPersistentID","kind":"identifier"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/assetURL":{"navigatorTitle":[{"text":"assetURL","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/assetURL","type":"topic","url":"/documentation/mediaplayer/mpmediaitem/asseturl","title":"assetURL","abstract":[{"text":"The URL that points to the media item.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"assetURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/beatsPerMinute":{"title":"beatsPerMinute","navigatorTitle":[{"text":"beatsPerMinute","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beatsPerMinute","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"/documentation/mediaplayer/mpmediaitem/beatsperminute","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/beatsPerMinute","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The number of musical beats per minute for the media item.","type":"text"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackNumber":{"abstract":[{"text":"The track number of the media item, for a media item that’s part of an album.","type":"text"}],"title":"albumTrackNumber","type":"topic","navigatorTitle":[{"kind":"identifier","text":"albumTrackNumber"}],"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackNumber","role":"symbol","kind":"symbol","url":"/documentation/mediaplayer/mpmediaitem/albumtracknumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"albumTrackNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCloudItem":{"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCloudItem","url":"/documentation/mediaplayer/mpmediaitem/isclouditem","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCloudItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"A Boolean value that indicates whether the media item is an iCloud Music Library item.","type":"text"}],"role":"symbol","title":"isCloudItem","kind":"symbol","type":"topic","navigatorTitle":[{"text":"cloudItem","kind":"identifier"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTitle":{"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTitle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"albumTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","url":"/documentation/mediaplayer/mpmediaitem/albumtitle","navigatorTitle":[{"kind":"identifier","text":"albumTitle"}],"abstract":[{"text":"The title of an album, such as ","type":"text"},{"inlineContent":[{"type":"text","text":"Live on Mars"}],"type":"emphasis"},{"text":", rather than the title of an individual song on the album, such as “Crater Dance.”","type":"text"}],"title":"albumTitle"},"doc://com.apple.mediaplayer/documentation/MediaPlayer":{"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer","type":"topic","url":"/documentation/mediaplayer","title":"Media Player","abstract":[{"text":"Find and play songs, audio podcasts, audio books, and more from within your app.","type":"text"}],"role":"collection"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artistPersistentID":{"navigatorTitle":[{"text":"artistPersistentID","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artistPersistentID","type":"topic","url":"/documentation/mediaplayer/mpmediaitem/artistpersistentid","title":"artistPersistentID","abstract":[{"text":"The persistent identifier for an artist.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"artistPersistentID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMediaEntityPersistentID","kind":"typeIdentifier","preciseIdentifier":"c:@T@MPMediaEntityPersistentID"}],"role":"symbol"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackCount":{"url":"/documentation/mediaplayer/mpmediaitem/albumtrackcount","kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackCount","abstract":[{"type":"text","text":"The number of tracks for the album that contains the media item."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"albumTrackCount"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"albumTrackCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","title":"albumTrackCount"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtistPersistentID":{"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtistPersistentID","abstract":[{"text":"The persistent identifier for the primary performing artist for an album.","type":"text"}],"url":"/documentation/mediaplayer/mpmediaitem/albumartistpersistentid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"albumArtistPersistentID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMediaEntityPersistentID","preciseIdentifier":"c:@T@MPMediaEntityPersistentID","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"albumArtistPersistentID","role":"symbol","navigatorTitle":[{"text":"albumArtistPersistentID","kind":"identifier"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isPreorder":{"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isPreorder","type":"topic","role":"symbol","title":"isPreorder","url":"/documentation/mediaplayer/mpmediaitem/ispreorder","navigatorTitle":[{"kind":"identifier","text":"preorder"}],"abstract":[{"text":"A Boolean value that indicates whether the media item is a preorder.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreorder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/comments":{"abstract":[{"type":"text","text":"Textual information about the media item."}],"title":"comments","type":"topic","navigatorTitle":[{"kind":"identifier","text":"comments"}],"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/comments","role":"symbol","kind":"symbol","url":"/documentation/mediaplayer/mpmediaitem/comments","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comments"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MPMediaItem","kind":"identifier"}],"url":"/documentation/mediaplayer/mpmediaitem","title":"MPMediaItem","abstract":[{"text":"A collection of properties that represents a single item in the media library.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MPMediaItem","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","type":"topic"},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artwork":{"title":"artwork","navigatorTitle":[{"text":"artwork","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"artwork","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MPMediaItemArtwork","preciseIdentifier":"c:objc(cs)MPMediaItemArtwork","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/mediaplayer/mpmediaitem/artwork","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artwork","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The artwork image for the media item."}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumPersistentID":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"albumPersistentID","kind":"identifier"}],"role":"symbol","title":"albumPersistentID","url":"/documentation/mediaplayer/mpmediaitem/albumpersistentid","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumPersistentID","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"albumPersistentID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@MPMediaEntityPersistentID","text":"MPMediaEntityPersistentID","kind":"typeIdentifier"}],"abstract":[{"text":"The persistent identifier for an album.","type":"text"}]},"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCompilation":{"navigatorTitle":[{"text":"compilation","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCompilation","type":"topic","url":"/documentation/mediaplayer/mpmediaitem/iscompilation","title":"isCompilation","abstract":[{"text":"A Boolean value that indicates whether the media item is part of a compilation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isCompilation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"8.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1"},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"14.0"},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"albumArtistPersistentID","path":"/metadata/title","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"albumArtistPersistentID"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mediaplayer/documentation/MediaPlayer","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Media item properties","identifiers":["doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumArtist","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumPersistentID","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTitle","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackCount","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/albumTrackNumber","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artist","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artistPersistentID","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/artwork","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/assetURL","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/beatsPerMinute","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/bookmarkTime","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCloudItem","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/comments","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isCompilation","doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaItem/isPreorder"],"anchor":"Media-item-properties","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaEntityPersistentID","preciseIdentifier":"c:@T@MPMediaEntityPersistentID","kind":"typeIdentifier","text":"MPMediaEntityPersistentID"},{"kind":"text","text":" "},{"text":"albumArtistPersistentID","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumArtist/title","value":"albumArtist","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumArtist/fragments","value":[{"text":"albumArtist","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1bookmarkTime/title","value":"bookmarkTime","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1bookmarkTime/fragments","value":[{"text":"bookmarkTime","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artist/title","value":"artist","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artist/fragments","value":[{"kind":"identifier","text":"artist"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntityPersistentID/title","value":"MPMediaEntityPersistentID","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntityPersistentID/fragments","value":[{"kind":"identifier","text":"MPMediaEntityPersistentID"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaEntityPersistentID/navigatorTitle","value":[{"text":"MPMediaEntityPersistentID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1assetURL/title","value":"assetURL","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1assetURL/fragments","value":[{"text":"assetURL","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1beatsPerMinute/title","value":"beatsPerMinute","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1beatsPerMinute/fragments","value":[{"text":"beatsPerMinute","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTrackNumber/title","value":"albumTrackNumber","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTrackNumber/fragments","value":[{"kind":"identifier","text":"albumTrackNumber"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isCloudItem/title","value":"cloudItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isCloudItem/fragments","value":[{"text":"cloudItem","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTitle/title","value":"albumTitle","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTitle/fragments","value":[{"text":"albumTitle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artistPersistentID/title","value":"artistPersistentID","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artistPersistentID/fragments","value":[{"text":"artistPersistentID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTrackCount/title","value":"albumTrackCount","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumTrackCount/fragments","value":[{"text":"albumTrackCount","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumArtistPersistentID/title","value":"albumArtistPersistentID","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumArtistPersistentID/fragments","value":[{"text":"albumArtistPersistentID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isPreorder/title","value":"preorder","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isPreorder/fragments","value":[{"kind":"identifier","text":"preorder"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1comments/title","value":"comments","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1comments/fragments","value":[{"text":"comments","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/title","value":"MPMediaItem","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/fragments","value":[{"kind":"identifier","text":"MPMediaItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem/navigatorTitle","value":[{"kind":"identifier","text":"MPMediaItem"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artwork/title","value":"artwork","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1artwork/fragments","value":[{"text":"artwork","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumPersistentID/title","value":"albumPersistentID","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1albumPersistentID/fragments","value":[{"text":"albumPersistentID","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isCompilation/title","value":"compilation","op":"replace"},{"path":"/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaItem~1isCompilation/fragments","value":[{"kind":"identifier","text":"compilation"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}