{
  "abstract": [
    {
      "text": "The balance of color for highlights that appear only at glancing angles, between the light color (lower values) and the material’s base color (at higher values).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLMaterialSemantic@MDLMaterialSemanticSheenTint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sheenTint"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLMaterialSemanticSheenTint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLMaterialSemantic.sheenTint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sheenTint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Model I/O uses this semantic for the ",
              "type": "text"
            },
            {
              "code": "sheenTint",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "map_sheenTint",
              "type": "codeVoice"
            },
            {
              "text": " attributes when importing from the MTL file format (for assets in the OBJ file format).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic": {
      "abstract": [
        {
          "text": "The semantic meaning for the material property’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semantic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLMaterialSemantic",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "semantic"
        }
      ],
      "role": "symbol",
      "title": "semantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialproperty/semantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic": {
      "abstract": [
        {
          "text": "Options for the semantic use of a material property’s value in rendering a particular surface appearance; used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialProperty/semantic",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemantic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic": {
      "abstract": [
        {
          "text": "The degree to which specular highlights elongate in the direction of the local tangent basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anisotropic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAnisotropic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.anisotropic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/anisotropic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation": {
      "abstract": [
        {
          "text": "The angle at which anisotropic effects are rotated relative to the local tangent basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "anisotropicRotation"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticAnisotropicRotation"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.anisotropicRotation",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/anisotropicrotation"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor": {
      "abstract": [
        {
          "text": "The inherent color of a surface, to be used as a modulator during shading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseColor"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticBaseColor"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.baseColor",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/basecolor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump": {
      "abstract": [
        {
          "text": "The degree of perturbation in a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bump"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticBump"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.bump",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/bump"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat": {
      "abstract": [
        {
          "text": "The intensity of a second specular highlight, similar to the gloss that results from a clear coat on an automotive finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearcoat"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticClearcoat"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.clearcoat",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/clearcoat"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss": {
      "abstract": [
        {
          "text": "The spread of a second specular highlight, similar to the gloss that results from a clear coat on an automotive finish.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearcoatGloss"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticClearcoatGloss"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.clearcoatGloss",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/clearcoatgloss"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission": {
      "abstract": [
        {
          "text": "The color emitted as radiance from a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emission"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticEmission"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.emission",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/emission"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic": {
      "abstract": [
        {
          "text": "The degree to which a material appears as a dielectric surface (lower values) or as a metal (higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metallic"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticMetallic"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.metallic",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/metallic"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity": {
      "abstract": [
        {
          "text": "The opacity of a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticOpacity"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.opacity",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/opacity"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness": {
      "abstract": [
        {
          "text": "The degree to which a material appears smooth, affecting both diffuse and specular response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roughness"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticRoughness"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.roughness",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/roughness"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen": {
      "abstract": [
        {
          "text": "The intensity of highlights that appear only at glancing angles on a material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheen"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSheen"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.sheen",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/sheen"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint": {
      "abstract": [
        {
          "text": "The balance of color for highlights that appear only at glancing angles, between the light color (lower values) and the material’s base color (at higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheenTint"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheenTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSheenTint"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.sheenTint",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/sheentint"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular": {
      "abstract": [
        {
          "text": "The intensity of specular highlights that appear on the material’s surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specular"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecular"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specular",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/specular"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent": {
      "abstract": [
        {
          "text": "The exponent to be used in Blinn-Phong approximation of the material’s specular response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specularExponent"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecularExponent"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specularExponent",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/specularexponent"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint": {
      "abstract": [
        {
          "text": "The balance of color for specular highlights, between the light color (lower values) and the material’s base color (at higher values).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specularTint"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSpecularTint"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.specularTint",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/speculartint"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface": {
      "abstract": [
        {
          "text": "The degree to which light scatters under the surface of a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subsurface"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMaterialSemanticSubsurface"
        }
      ],
      "role": "symbol",
      "title": "MDLMaterialSemantic.subsurface",
      "type": "topic",
      "url": "/documentation/modelio/mdlmaterialsemantic/subsurface"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLMaterialSemanticSheenTint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSheenTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/baseColor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/subsurface",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/metallic",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specular",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularExponent",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/specularTint",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/roughness",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropic",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/anisotropicRotation",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/sheen",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoat",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/clearcoatGloss",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/emission",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/bump",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMaterialSemantic/opacity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLMaterialSemanticSheenTint"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1bump/title",
          "value": "MDLMaterialSemanticBump"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1bump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticBump"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoat/title",
          "value": "MDLMaterialSemanticClearcoat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticClearcoat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropic/title",
          "value": "MDLMaterialSemanticAnisotropic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAnisotropic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheenTint/title",
          "value": "MDLMaterialSemanticSheenTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheenTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSheenTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/title",
          "value": "MDLMaterialSemantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/title",
          "value": "semantic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialProperty~1semantic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "semantic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1roughness/title",
          "value": "MDLMaterialSemanticRoughness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1roughness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticRoughness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularTint/title",
          "value": "MDLMaterialSemanticSpecularTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecularTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1opacity/title",
          "value": "MDLMaterialSemanticOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1metallic/title",
          "value": "MDLMaterialSemanticMetallic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1metallic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticMetallic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1emission/title",
          "value": "MDLMaterialSemanticEmission"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1emission/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticEmission"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1subsurface/title",
          "value": "MDLMaterialSemanticSubsurface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1subsurface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSubsurface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropicRotation/title",
          "value": "MDLMaterialSemanticAnisotropicRotation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1anisotropicRotation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticAnisotropicRotation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheen/title",
          "value": "MDLMaterialSemanticSheen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1sheen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSheen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1baseColor/title",
          "value": "MDLMaterialSemanticBaseColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1baseColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticBaseColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specular/title",
          "value": "MDLMaterialSemanticSpecular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularExponent/title",
          "value": "MDLMaterialSemanticSpecularExponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1specularExponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticSpecularExponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoatGloss/title",
          "value": "MDLMaterialSemanticClearcoatGloss"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMaterialSemantic~1clearcoatGloss/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMaterialSemanticClearcoatGloss"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmaterialsemantic/sheentint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmaterialsemantic/sheentint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
