{
  "abstract": [
    {
      "text": "Creates a media query that matches the entire library and that groups and sorts collections by playlist name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/playlists()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPMediaQuery(cm)playlistsQuery",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "playlists"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MPMediaQuery",
        "text": "MPMediaQuery"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "playlistsQuery"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "playlists()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "playlists"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPMediaQuery",
              "text": "MPMediaQuery"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A media query that matches all media items and that has a grouping type of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist": {
      "abstract": [
        {
          "text": "Groups and sorts media item collections by playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlist"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaGroupingPlaylist"
        }
      ],
      "role": "symbol",
      "title": "MPMediaGrouping.playlist",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediagrouping/playlist"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery": {
      "abstract": [
        {
          "text": "A query that specifies a set of media items from the device’s media library using a filter and a grouping type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMediaQuery"
        }
      ],
      "role": "symbol",
      "title": "MPMediaQuery",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery-init": {
      "abstract": [
        {
          "text": "Initializes a generic media query.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery-init",
      "kind": "article",
      "role": "article",
      "title": "init",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery-init"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/albums()": {
      "abstract": [
        {
          "text": "Creates a media query that matches music items and that groups and sorts collections by album name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albums"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/albums()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "albumsQuery"
        }
      ],
      "role": "symbol",
      "title": "albums()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/albums()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/artists()": {
      "abstract": [
        {
          "text": "Creates a media query that matches music items and that groups and sorts collections by artist name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artists"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/artists()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artistsQuery"
        }
      ],
      "role": "symbol",
      "title": "artists()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/artists()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/audiobooks()": {
      "abstract": [
        {
          "text": "Creates a media query that matches audio book items and that groups and sorts collections by audio book name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audiobooks"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/audiobooks()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audiobooksQuery"
        }
      ],
      "role": "symbol",
      "title": "audiobooks()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/audiobooks()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/compilations()": {
      "abstract": [
        {
          "text": "Creates a media query that matches compilation items and that groups and sorts collections by album name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compilations"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/compilations()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compilationsQuery"
        }
      ],
      "role": "symbol",
      "title": "compilations()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/compilations()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/composers()": {
      "abstract": [
        {
          "text": "Creates a media query that matches all media items and that groups and sorts collections by composer name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "composers"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/composers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "composersQuery"
        }
      ],
      "role": "symbol",
      "title": "composers()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/composers()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/genres()": {
      "abstract": [
        {
          "text": "Creates a media query that matches all media items and that groups and sorts collections by genre name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genres"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/genres()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genresQuery"
        }
      ],
      "role": "symbol",
      "title": "genres()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/genres()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/init(filterPredicates:)": {
      "abstract": [
        {
          "text": "Initializes a media query with a set of media property predicates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "filterPredicates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaPredicate",
          "text": "MPMediaPredicate"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/init(filterPredicates:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFilterPredicates:"
        }
      ],
      "role": "symbol",
      "title": "init(filterPredicates:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/init(filterpredicates:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/playlists()": {
      "abstract": [
        {
          "text": "Creates a media query that matches the entire library and that groups and sorts collections by playlist name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlists"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/playlists()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playlistsQuery"
        }
      ],
      "role": "symbol",
      "title": "playlists()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/playlists()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/podcasts()": {
      "abstract": [
        {
          "text": "Creates a media query that matches podcast items and that groups and sorts collections by podcast name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcasts"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/podcasts()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "podcastsQuery"
        }
      ],
      "role": "symbol",
      "title": "podcasts()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/podcasts()"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/songs()": {
      "abstract": [
        {
          "text": "Creates a media query that matches music items and that groups and sorts collections by song name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "songs"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMediaQuery",
          "text": "MPMediaQuery"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/songs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "songsQuery"
        }
      ],
      "role": "symbol",
      "title": "songs()",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmediaquery/songs()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-media-queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/albums()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/artists()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/songs()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/podcasts()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/audiobooks()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/compilations()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/composers()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/genres()",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/init(filterPredicates:)"
      ],
      "title": "Creating media queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "playlistsQuery"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "playlistsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-media-queries",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/albums()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/artists()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/songs()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/podcasts()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/audiobooks()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/compilations()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/composers()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/genres()",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery-init",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery/init(filterPredicates:)"
              ],
              "title": "Creating media queries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaQuery",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MPMediaQuery",
                    "text": "MPMediaQuery"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "playlistsQuery"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A media query that matches all media items and that has a grouping type of ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMediaGrouping/playlist",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1podcasts()/title",
          "value": "podcastsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1podcasts()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "podcastsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1artists()/title",
          "value": "artistsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1artists()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "artistsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1init(filterPredicates:)/title",
          "value": "initWithFilterPredicates:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1init(filterPredicates:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFilterPredicates:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1compilations()/title",
          "value": "compilationsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1compilations()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "compilationsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery/title",
          "value": "MPMediaQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1songs()/title",
          "value": "songsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1songs()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "songsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1albums()/title",
          "value": "albumsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1albums()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "albumsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1composers()/title",
          "value": "composersQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1composers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "composersQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1genres()/title",
          "value": "genresQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1genres()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "genresQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1playlists()/title",
          "value": "playlistsQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1playlists()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "playlistsQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1playlist/title",
          "value": "MPMediaGroupingPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaGrouping~1playlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMediaGroupingPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1audiobooks()/title",
          "value": "audiobooksQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMediaQuery~1audiobooks()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "audiobooksQuery"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaquery/playlists()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmediaquery/playlists()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
