{
  "abstract": [
    {
      "text": "Tells the delegate when the user selects a point of interest.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate/pointOfInterestTemplate(_:didSelectPointOfInterest:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPPointOfInterestTemplateDelegate(im)pointOfInterestTemplate:didSelectPointOfInterest:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "pointOfInterestTemplate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPPointOfInterestTemplate",
        "text": "CPPointOfInterestTemplate"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didSelectPointOfInterest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPPointOfInterest",
        "text": "CPPointOfInterest"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "pointOfInterestTemplate:didSelectPointOfInterest:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "pointOfInterestTemplate(_:didSelectPointOfInterest:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "pointOfInterestTemplate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pointOfInterestTemplate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPPointOfInterestTemplate",
              "text": "CPPointOfInterestTemplate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didSelectPointOfInterest"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pointOfInterest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPPointOfInterest",
              "text": "CPPointOfInterest"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The template that displays the map that contains the points of interest.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pointOfInterestTemplate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The point of interest that the user selects.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pointOfInterest"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CarPlay calls this method whenever the user selects a point of interest from the template’s map. The template displays a detail card for the selection, which contains secondary information and optional actions the user can perform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest/userInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to attach a value that provides additional context for the point of interest. You can then reference that value in your implementation of this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest": {
      "abstract": [
        {
          "text": "An object that describes a point of interest on the template’s map and in its scrollable picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPPointOfInterest"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPointOfInterest"
        }
      ],
      "role": "symbol",
      "title": "CPPointOfInterest",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinterest"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest/userInfo": {
      "abstract": [
        {
          "text": "An opaque value for the point of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinterest/userinfo"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate": {
      "abstract": [
        {
          "text": "A template that displays a map with selectable points of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPPointOfInterestTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinteresttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate": {
      "abstract": [
        {
          "text": "The methods to handle a Point of Interest template’s events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplateDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplateDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPPointOfInterestTemplateDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinteresttemplatedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate/pointOfInterestTemplate(_:didSelectPointOfInterest:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user selects a point of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pointOfInterestTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPPointOfInterestTemplate",
          "text": "CPPointOfInterestTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPointOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPPointOfInterest",
          "text": "CPPointOfInterest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate/pointOfInterestTemplate(_:didSelectPointOfInterest:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pointOfInterestTemplate:didSelectPointOfInterest:"
        }
      ],
      "role": "symbol",
      "title": "pointOfInterestTemplate(_:didSelectPointOfInterest:)",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinteresttemplatedelegate/pointofinteresttemplate(_:didselectpointofinterest:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "pointOfInterestTemplate:didSelectPointOfInterest:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pointOfInterestTemplate:didSelectPointOfInterest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplateDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "pointOfInterestTemplate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPPointOfInterestTemplate",
                    "text": "CPPointOfInterestTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pointOfInterestTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didSelectPointOfInterest:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPPointOfInterest",
                    "text": "CPPointOfInterest"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pointOfInterest"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The template that displays the map that contains the points of interest.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pointOfInterestTemplate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The point of interest that the user selects.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pointOfInterest"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/title",
          "value": "CPPointOfInterestTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplateDelegate~1pointOfInterestTemplate(_:didSelectPointOfInterest:)/title",
          "value": "pointOfInterestTemplate:didSelectPointOfInterest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplateDelegate~1pointOfInterestTemplate(_:didSelectPointOfInterest:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pointOfInterestTemplate:didSelectPointOfInterest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterest~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterest~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterest/title",
          "value": "CPPointOfInterest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplateDelegate/title",
          "value": "CPPointOfInterestTemplateDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplateDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplateDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplateDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cppointofinteresttemplatedelegate/pointofinteresttemplate(_:didselectpointofinterest:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cppointofinteresttemplatedelegate/pointofinteresttemplate(_:didselectpointofinterest:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
