{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"newBufferFromZone:data:type:"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"MDLMeshBufferZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MDLMeshBufferZone"},{"text":")?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MDLMeshBufferType","text":"MDLMeshBufferType","kind":"typeIdentifier"},{"text":") -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MDLMeshBuffer","text":"MDLMeshBuffer","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"modules":[{"name":"Model I/O"}],"role":"symbol","platforms":[{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"13.1","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"10.11","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"title":"newBuffer(from:data:type:)","required":true,"externalID":"c:objc(pl)MDLMeshBufferAllocator(im)newBufferFromZone:data:type:","symbolKind":"method"},"identifier":{"url":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:data:type:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone","text":"MDLMeshBufferZone","preciseIdentifier":"c:objc(pl)MDLMeshBufferZone"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType","text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType"},{"kind":"text","text":") -> (any "},{"kind":"typeIdentifier","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer","text":"MDLMeshBuffer","preciseIdentifier":"c:objc(pl)MDLMeshBuffer"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"zone","content":[{"type":"paragraph","inlineContent":[{"text":"A pool of memory for related allocations, as returned by the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)","isActive":true,"type":"reference"},{"text":" method.","type":"text"}]}]},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"The initial data to store in the buffer. Implementations of this protocol typically copy this data."}],"type":"paragraph"}]},{"name":"type","content":[{"inlineContent":[{"text":"Use ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex","isActive":true,"type":"reference"},{"text":" to create a buffer for a mesh’s vertex attribute data, or ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index","isActive":true,"type":"reference"},{"text":" to create a buffer for a submesh’s index data.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A new memory buffer for mesh data."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"Use this method when making multiple related allocations that should share the same memory pool.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates a new buffer containing the specified data in the specified zone."}],"seeAlsoSections":[{"title":"Allocating Mesh Buffers","generated":true,"anchor":"Allocating-Mesh-Buffers","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZoneForBuffers(withSize:andType:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(_:type:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:length:type:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(with:type:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/modelio/mdlmeshbufferallocator/newbuffer(from:data:type:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/modelio/mdlmeshbufferallocator/newbuffer(from:data:type:)"]}],"references":{"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"role":"symbol","abstract":[{"type":"text","text":"A byte buffer in memory."}],"url":"/documentation/foundation/data","fragments":[{"text":"struct ","kind":"text"},{"kind":"identifier","text":"Data"}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","kind":"symbol","title":"Data"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZoneForBuffers(withSize:andType:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newZoneForBuffers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSize"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"andType"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"]) -> any "},{"preciseIdentifier":"c:objc(pl)MDLMeshBufferZone","kind":"typeIdentifier","text":"MDLMeshBufferZone"}],"url":"/documentation/modelio/mdlmeshbufferallocator/newzoneforbuffers(withsize:andtype:)","role":"symbol","title":"newZoneForBuffers(withSize:andType:)","required":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZoneForBuffers(withSize:andType:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a zone large enough to fit the specified group of allocation sizes."}],"navigatorTitle":[{"kind":"identifier","text":"newZoneForBuffersWithSize:andType:"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","abstract":[{"text":"","type":"text"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMeshBufferZone","kind":"identifier"}],"kind":"symbol","title":"MDLMeshBufferZone","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferZone","url":"/documentation/modelio/mdlmeshbufferzone","abstract":[{"type":"text","text":"The general interface for logical pools of memory used in allocation of related mesh data buffers."}],"role":"symbol","navigatorTitle":[{"text":"MDLMeshBufferZone","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex":{"url":"/documentation/modelio/mdlmeshbuffertype/vertex","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex","navigatorTitle":[{"text":"MDLMeshBufferTypeVertex","kind":"identifier"}],"type":"topic","abstract":[{"text":"The buffer contains per-vertex data for one or more vertex attributes of a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},{"type":"text","text":" object."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vertex","kind":"identifier"}],"role":"symbol","title":"MDLMeshBufferType.vertex","kind":"symbol"},"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh":{"abstract":[{"text":"A container for index buffer data and material information to be used in rendering all or part of a 3D object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MDLSubmesh"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLSubmesh"}],"kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh","title":"MDLSubmesh","url":"/documentation/modelio/mdlsubmesh"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator":{"abstract":[{"text":"The general interface for managing allocation of data buffers to be used in loading, processing, and rendering meshes.","type":"text"}],"navigatorTitle":[{"text":"MDLMeshBufferAllocator","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator","url":"/documentation/modelio/mdlmeshbufferallocator","title":"MDLMeshBufferAllocator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMeshBufferAllocator","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)":{"url":"/documentation/modelio/mdlmeshbufferallocator/newzone(_:)","abstract":[{"text":"Creates a zone for related memory allocations.","type":"text"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)","title":"newZone(_:)","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"newZone:"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"newZone"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(pl)MDLMeshBufferZone","kind":"typeIdentifier","text":"MDLMeshBufferZone"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(with:type:)":{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(with:type:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"text":"MDLMeshBuffer","preciseIdentifier":"c:objc(pl)MDLMeshBuffer","kind":"typeIdentifier"}],"url":"/documentation/modelio/mdlmeshbufferallocator/newbuffer(with:type:)","abstract":[{"text":"Creates a new buffer containing the specified data.","type":"text"}],"required":true,"navigatorTitle":[{"text":"newBufferWithData:type:","kind":"identifier"}],"kind":"symbol","title":"newBuffer(with:type:)","type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(_:type:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MDLMeshBufferType","kind":"typeIdentifier","preciseIdentifier":"c:@E@MDLMeshBufferType"},{"text":") -> any ","kind":"text"},{"text":"MDLMeshBuffer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MDLMeshBuffer"}],"url":"/documentation/modelio/mdlmeshbufferallocator/newbuffer(_:type:)","abstract":[{"type":"text","text":"Creates a new buffer of the specified length."}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(_:type:)","type":"topic","required":true,"role":"symbol","kind":"symbol","title":"newBuffer(_:type:)","navigatorTitle":[{"text":"newBuffer:type:","kind":"identifier"}]},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MDLMeshBufferType"}],"url":"/documentation/modelio/mdlmeshbuffertype","abstract":[{"type":"text","text":"Options for the content of a mesh buffer, used by the "},{"type":"reference","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type","isActive":true},{"type":"text","text":" property and by "},{"type":"reference","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator","isActive":true},{"type":"text","text":" methods for creating buffers."}],"title":"MDLMeshBufferType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MDLMeshBufferType"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMeshBuffer","kind":"identifier"}],"kind":"symbol","title":"MDLMeshBuffer","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer","url":"/documentation/modelio/mdlmeshbuffer","abstract":[{"type":"text","text":"The general interface for managing storage of vertex and index data used in loading, processing, and rendering meshes."}],"role":"symbol","navigatorTitle":[{"text":"MDLMeshBuffer","kind":"identifier"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMesh":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MDLMesh","kind":"identifier"}],"type":"topic","abstract":[{"text":"A container for vertex buffer data to be used in rendering a 3D object.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MDLMesh","kind":"identifier"}],"title":"MDLMesh","url":"/documentation/modelio/mdlmesh","kind":"symbol","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMesh"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"type":"topic","url":"/documentation/modelio/mdlmeshbuffer/type","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBuffer/type","title":"type","abstract":[{"type":"text","text":"The type of data contained in a buffer."}],"required":true},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index":{"type":"topic","navigatorTitle":[{"text":"MDLMeshBufferTypeIndex","kind":"identifier"}],"title":"MDLMeshBufferType.index","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index","url":"/documentation/modelio/mdlmeshbuffertype/index","kind":"symbol","role":"symbol","abstract":[{"text":"The buffer contains index data for a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLSubmesh"},{"type":"text","text":" object."}]},"doc://com.apple.modelio/documentation/ModelIO":{"identifier":"doc://com.apple.modelio/documentation/ModelIO","title":"Model I/O","role":"collection","kind":"symbol","abstract":[{"text":"Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.","type":"text"}],"type":"topic","url":"/documentation/modelio"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:length:type:)":{"navigatorTitle":[{"text":"newBufferFromZone:length:type:","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a new buffer of the specified length in the specified zone."}],"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:length:type:)","title":"newBuffer(from:length:type:)","role":"symbol","url":"/documentation/modelio/mdlmeshbufferallocator/newbuffer(from:length:type:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"MDLMeshBufferZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MDLMeshBufferZone"},{"text":")?, ","kind":"text"},{"text":"length","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType"},{"kind":"text","text":") -> (any "},{"kind":"typeIdentifier","text":"MDLMeshBuffer","preciseIdentifier":"c:objc(pl)MDLMeshBuffer"},{"kind":"text","text":")?"}],"type":"topic"},"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:data:type:)":{"url":"/documentation/modelio/mdlmeshbufferallocator/newbuffer(from:data:type:)","role":"symbol","abstract":[{"type":"text","text":"Creates a new buffer containing the specified data in the specified zone."}],"kind":"symbol","title":"newBuffer(from:data:type:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newBuffer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MDLMeshBufferZone","text":"MDLMeshBufferZone","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MDLMeshBufferType","text":"MDLMeshBufferType","kind":"typeIdentifier"},{"text":") -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MDLMeshBuffer","text":"MDLMeshBuffer","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"newBufferFromZone:data:type:"}],"type":"topic","identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:data:type:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.11","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"newBufferFromZone:data:type:"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"newBufferFromZone:data:type:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.modelio/documentation/ModelIO","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Allocating Mesh Buffers","identifiers":["doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZoneForBuffers(withSize:andType:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(_:type:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(from:length:type:)","doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newBuffer(with:type:)"],"anchor":"Allocating-Mesh-Buffers","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qoobjc(pl)MDLMeshBuffer","kind":"typeIdentifier","text":"id<MDLMeshBuffer>"},{"kind":"text","text":") "},{"kind":"identifier","text":"newBufferFromZone:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)MDLMeshBufferZone","kind":"typeIdentifier","text":"id<MDLMeshBufferZone>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"zone"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType","preciseIdentifier":"c:@E@MDLMeshBufferType","kind":"typeIdentifier","text":"MDLMeshBufferType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"zone","content":[{"inlineContent":[{"text":"A pool of memory for related allocations, as returned by the ","type":"text"},{"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferAllocator/newZone(_:)","isActive":true,"type":"reference"},{"text":" method.","type":"text"}],"type":"paragraph"}]},{"name":"data","content":[{"inlineContent":[{"text":"The initial data to store in the buffer. Implementations of this protocol typically copy this data.","type":"text"}],"type":"paragraph"}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"Use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/vertex"},{"text":" to create a buffer for a mesh’s vertex attribute data, or ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.modelio/documentation/ModelIO/MDLMeshBufferType/index"},{"text":" to create a buffer for a submesh’s index data.","type":"text"}]}]}]},"path":"/primaryContentSections/1"},{"op":"replace","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A new memory buffer for mesh data.","type":"text"}]}],"kind":"content"},"path":"/primaryContentSections/2"},{"op":"replace","value":"newZoneForBuffersWithSize:andType:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newZoneForBuffers(withSize:andType:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"newZoneForBuffersWithSize:andType:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newZoneForBuffers(withSize:andType:)/fragments"},{"op":"replace","value":"MDLMeshBufferZone","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/title"},{"op":"replace","value":[{"text":"MDLMeshBufferZone","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBufferZone"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferZone/navigatorTitle"},{"op":"replace","value":"MDLMeshBufferTypeVertex","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/title"},{"op":"replace","value":[{"text":"MDLMeshBufferTypeVertex","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1vertex/fragments"},{"op":"replace","value":"MDLSubmesh","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/title"},{"op":"replace","value":[{"kind":"identifier","text":"MDLSubmesh"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/fragments"},{"op":"replace","value":[{"text":"MDLSubmesh","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLSubmesh/navigatorTitle"},{"op":"replace","value":"MDLMeshBufferAllocator","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/title"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBufferAllocator"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/fragments"},{"op":"replace","value":[{"text":"MDLMeshBufferAllocator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator/navigatorTitle"},{"op":"replace","value":"newZone:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newZone(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"newZone:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newZone(_:)/fragments"},{"op":"replace","value":"newBufferWithData:type:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(with:type:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"newBufferWithData:type:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(with:type:)/fragments"},{"op":"replace","value":"newBuffer:type:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(_:type:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"newBuffer:type:"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(_:type:)/fragments"},{"op":"replace","value":"MDLMeshBufferType","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/title"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBufferType"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBufferType"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType/navigatorTitle"},{"op":"replace","value":"MDLMeshBuffer","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/title"},{"op":"replace","value":[{"text":"MDLMeshBuffer","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBuffer"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer/navigatorTitle"},{"op":"replace","value":"MDLMesh","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title"},{"op":"replace","value":[{"text":"MDLMesh","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMesh"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle"},{"op":"replace","value":"type","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/title"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBuffer~1type/fragments"},{"op":"replace","value":"MDLMeshBufferTypeIndex","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/title"},{"op":"replace","value":[{"kind":"identifier","text":"MDLMeshBufferTypeIndex"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferType~1index/fragments"},{"op":"replace","value":"newBufferFromZone:length:type:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(from:length:type:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"newBufferFromZone:length:type:"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(from:length:type:)/fragments"},{"op":"replace","value":"newBufferFromZone:data:type:","path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(from:data:type:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"newBufferFromZone:data:type:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMeshBufferAllocator~1newBuffer(from:data:type:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}