{
  "abstract": [
    {
      "text": "Create and modify events and reminders in a person’s database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating events and reminders"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once you have permission to access a person’s Calendar and Reminder data, you can create, display, and edit events and reminders.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-Events",
          "level": 3,
          "text": "Create Events",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a new event with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can edit the details of a new event or an event you previously fetched from the Calendar database by setting the event’s corresponding properties. Some of the details you can edit include:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The event’s title with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The event’s start and end dates with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The calendar with which the event is associated with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/calendar",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The alarms associated with the event with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/alarms",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property (see “",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "” for more details).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The event’s recurrence rule, if it is a repeating event, with the ",
                      "type": "text"
                    },
                    {
                      "code": "recurrenceRules",
                      "type": "codeVoice"
                    },
                    {
                      "text": " property (see “",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": "” for more details).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In iOS, you have the option of letting users modify event data with the event view controllers provided in the EventKit UI framework. For information on how to use these event view controllers, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/EventKitUI",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Save-and-Delete-Events",
          "level": 4,
          "text": "Save and Delete Events",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your app modifies a user’s Calendar database, it must get confirmation from the user before doing so. An app should never modify the Calendar database without specific instruction from the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Save your changes to the Calendar database with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:span:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If you want to remove an event from the Calendar database, use the ",
              "type": "text"
            },
            {
              "code": "EKEventStore",
              "type": "codeVoice"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:span:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Whether you are saving or removing an event, implementing the respective method automatically syncs your changes with the calendar the event belongs to (CalDAV, Exchange, and so on).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you are saving a recurring event, your changes can apply to all future occurrences of the event by specifying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSpan/futureEvents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the span parameter of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:span:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Likewise, you can remove all future occurrences of an event by specifying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSpan/futureEvents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the ",
              "type": "text"
            },
            {
              "code": "span",
              "type": "codeVoice"
            },
            {
              "text": " parameter of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:span:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you pass ",
                  "type": "text"
                },
                {
                  "code": "NO",
                  "type": "codeVoice"
                },
                {
                  "text": " to the ",
                  "type": "text"
                },
                {
                  "code": "commit",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter, make sure that you later invoke the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/commit()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method to permanently save your changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Create-Reminders",
          "level": 3,
          "text": "Create Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Reminders are tasks that may be tied to a specific time or location. They are similar to calendar events, but can be marked complete and may not necessarily span an exact period of time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " inherits from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can perform the same methods on a reminder as you would on an event, such as adding an alarm with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addAlarm(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or setting a recurrence rule with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addRecurrenceRule(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your iOS app links on macOS and you need to access Reminders data, be sure to include the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW16",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key in your ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "You can create reminders using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/init(eventStore:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/title",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/calendar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties are required. The calendar for a reminder is the list with which it is grouped.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Like events, reminders can trigger time-based or location-based alarms to alert the user of a certain task. Read “",
              "type": "text"
            },
            {
              "code": "Setting an Alarm",
              "type": "codeVoice"
            },
            {
              "text": "” for more information on how to attach alarms to calendar items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Save-and-Delete-Reminders",
          "level": 4,
          "text": "Save and Delete Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To save a reminder to the Calendar database, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. To remove an event, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:commit:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/calendars",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties must explicitly be set before you save the reminder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Just like when saving or removing events, make sure that if you pass ",
                  "type": "text"
                },
                {
                  "code": "NO",
                  "type": "codeVoice"
                },
                {
                  "text": " to the ",
                  "type": "text"
                },
                {
                  "code": "commit",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter, you later invoke the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/commit()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method to save your changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Edit-Reminders",
          "level": 4,
          "text": "Edit Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To associate a start date or due date with a reminder, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/startDateComponents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/dueDateComponents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. To complete a reminder, set the completed property to ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", which automatically sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/completionDate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to the current date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your app modifies a user’s Calendar database, it must get confirmation from the user before doing so. An app should never modify the Calendar database without specific instruction from the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/EventKitUI"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKAlarm": {
      "abstract": [
        {
          "text": "A class that represents an alarm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKAlarm"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKAlarm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKAlarm"
        }
      ],
      "role": "symbol",
      "title": "EKAlarm",
      "type": "topic",
      "url": "/documentation/eventkit/ekalarm"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title": {
      "abstract": [
        {
          "text": "The calendar’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/title"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem": {
      "abstract": [
        {
          "text": "An abstract superclass for calendar events and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarItem",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addAlarm(_:)": {
      "abstract": [
        {
          "text": "Adds an alarm to the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAlarm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKAlarm",
          "text": "EKAlarm"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addAlarm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAlarm:"
        }
      ],
      "role": "symbol",
      "title": "addAlarm(_:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem/addalarm(_:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addRecurrenceRule(_:)": {
      "abstract": [
        {
          "text": "Adds a recurrence rule to the recurrence rule array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addRecurrenceRule"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKRecurrenceRule",
          "text": "EKRecurrenceRule"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/addRecurrenceRule(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addRecurrenceRule:"
        }
      ],
      "role": "symbol",
      "title": "addRecurrenceRule(_:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem/addrecurrencerule(_:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/alarms": {
      "abstract": [
        {
          "text": "The alarms associated with the calendar item, as an array of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKAlarm",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarms"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKAlarm",
          "text": "EKAlarm"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/alarms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alarms"
        }
      ],
      "role": "symbol",
      "title": "alarms",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem/alarms"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/calendar": {
      "abstract": [
        {
          "text": "The calendar for the calendar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKCalendar",
          "text": "EKCalendar"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/calendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calendar"
        }
      ],
      "role": "symbol",
      "title": "calendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem/calendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/title": {
      "abstract": [
        {
          "text": "The title for the calendar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem/title"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent": {
      "abstract": [
        {
          "text": "A class that represents an event in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "role": "symbol",
      "title": "EKEvent",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate": {
      "abstract": [
        {
          "text": "The end date for the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/enddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)": {
      "abstract": [
        {
          "text": "Creates and returns a new event belonging to a specified event store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "eventStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventStore",
          "text": "EKEventStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventWithEventStore:"
        }
      ],
      "role": "symbol",
      "title": "init(eventStore:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/init(eventstore:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate": {
      "abstract": [
        {
          "text": "The start date of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/startdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore": {
      "abstract": [
        {
          "text": "An object that accesses a person’s calendar events and reminders and supports the scheduling of new events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "role": "symbol",
      "title": "EKEventStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/calendars": {
      "abstract": [
        {
          "text": "The calendars associated with the event store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendars"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKCalendar",
          "text": "EKCalendar"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/calendars",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calendars"
        }
      ],
      "role": "symbol",
      "title": "calendars",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/calendars"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/commit()": {
      "abstract": [
        {
          "text": "Commits all unsaved changes to the event store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/commit()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commit:"
        }
      ],
      "role": "symbol",
      "title": "commit()",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/commit()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:commit:)": {
      "abstract": [
        {
          "text": "Removes a reminder from the event store by either committing or batching the changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKReminder",
          "text": "EKReminder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:commit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeReminder:commit:error:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:commit:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/remove(_:commit:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:span:commit:)": {
      "abstract": [
        {
          "text": "Removes an event or recurring events from the event store by either committing or batching the changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEvent",
          "text": "EKEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "span"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKSpan",
          "text": "EKSpan"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/remove(_:span:commit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeEvent:span:commit:error:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:span:commit:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/remove(_:span:commit:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:commit:)": {
      "abstract": [
        {
          "text": "Saves changes to a reminder by either committing or batching the changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKReminder",
          "text": "EKReminder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:commit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveReminder:commit:error:"
        }
      ],
      "role": "symbol",
      "title": "save(_:commit:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/save(_:commit:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:span:commit:)": {
      "abstract": [
        {
          "text": "Saves an event or recurring events to the event store by either committing or batching the changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEvent",
          "text": "EKEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "span"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKSpan",
          "text": "EKSpan"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/save(_:span:commit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveEvent:span:commit:error:"
        }
      ],
      "role": "symbol",
      "title": "save(_:span:commit:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/save(_:span:commit:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder": {
      "abstract": [
        {
          "text": "A class that represents a reminder in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "role": "symbol",
      "title": "EKReminder",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder/completionDate": {
      "abstract": [
        {
          "text": "The date on which the reminder was completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/completionDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionDate"
        }
      ],
      "role": "symbol",
      "title": "completionDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder/completiondate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder/dueDateComponents": {
      "abstract": [
        {
          "text": "The date by which the reminder should be completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dueDateComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/dueDateComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dueDateComponents"
        }
      ],
      "role": "symbol",
      "title": "dueDateComponents",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder/duedatecomponents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder/init(eventStore:)": {
      "abstract": [
        {
          "text": "Creates and returns a new reminder in the given event store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "eventStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventStore",
          "text": "EKEventStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/init(eventStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reminderWithEventStore:"
        }
      ],
      "role": "symbol",
      "title": "init(eventStore:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder/init(eventstore:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder/startDateComponents": {
      "abstract": [
        {
          "text": "The start date of the task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder/startDateComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDateComponents"
        }
      ],
      "role": "symbol",
      "title": "startDateComponents",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder/startdatecomponents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKSpan/futureEvents": {
      "abstract": [
        {
          "text": "Modifications to this event instance should also affect future instances of this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "futureEvents"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKSpan/futureEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKSpanFutureEvents"
        }
      ],
      "role": "symbol",
      "title": "EKSpan.futureEvents",
      "type": "topic",
      "url": "/documentation/eventkit/ekspan/futureevents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event": {
      "abstract": [
        {
          "text": "Set up an event or reminder that repeats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-a-recurring-event",
      "kind": "article",
      "role": "article",
      "title": "Creating a recurring event",
      "type": "topic",
      "url": "/documentation/eventkit/creating-a-recurring-event"
    },
    "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders": {
      "abstract": [
        {
          "text": "Add, fetch, complete, remove, and sort location-based reminders in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
      "kind": "article",
      "role": "sampleCode",
      "title": "Managing Location-Based Reminders",
      "type": "topic",
      "url": "/documentation/eventkit/managing-location-based-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders": {
      "abstract": [
        {
          "text": "Fetch events and reminders from the Calendar database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Retrieving events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/retrieving-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm": {
      "abstract": [
        {
          "text": "Alert users of events and reminders with an alarm.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/setting-an-alarm",
      "kind": "article",
      "role": "article",
      "title": "Setting an alarm",
      "type": "topic",
      "url": "/documentation/eventkit/setting-an-alarm"
    },
    "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications": {
      "abstract": [
        {
          "text": "Register for notifications about changes and keep your app up to date.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Updating with notifications",
      "type": "topic",
      "url": "/documentation/eventkit/updating-with-notifications"
    },
    "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW16": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW16",
      "title": "NSRemindersUsageDescription",
      "titleInlineContent": [
        {
          "text": "NSRemindersUsageDescription",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Events-and-reminders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
        "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
        "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
      ],
      "title": "Events and reminders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Events-and-reminders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
                "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
                "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
              ],
              "title": "Events and reminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1save(_:span:commit:)/title",
          "value": "saveEvent:span:commit:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1save(_:span:commit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveEvent:span:commit:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/title",
          "value": "EKEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1startDateComponents/title",
          "value": "startDateComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1startDateComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDateComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1completionDate/title",
          "value": "completionDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1completionDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSpan~1futureEvents/title",
          "value": "EKSpanFutureEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKSpan~1futureEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKSpanFutureEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1calendars/title",
          "value": "calendars"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1calendars/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calendars"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1alarms/title",
          "value": "alarms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1alarms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alarms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1addAlarm(_:)/title",
          "value": "addAlarm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1addAlarm(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAlarm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1remove(_:span:commit:)/title",
          "value": "removeEvent:span:commit:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1remove(_:span:commit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeEvent:span:commit:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1dueDateComponents/title",
          "value": "dueDateComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1dueDateComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dueDateComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1addRecurrenceRule(_:)/title",
          "value": "addRecurrenceRule:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1addRecurrenceRule(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addRecurrenceRule:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1init(eventStore:)/title",
          "value": "reminderWithEventStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder~1init(eventStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "reminderWithEventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/title",
          "value": "EKReminder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1save(_:commit:)/title",
          "value": "saveReminder:commit:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1save(_:commit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveReminder:commit:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/title",
          "value": "EKAlarm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKAlarm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKAlarm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1commit()/title",
          "value": "commit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1commit()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1calendar/title",
          "value": "calendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem~1calendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1init(eventStore:)/title",
          "value": "eventWithEventStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1init(eventStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "eventWithEventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1remove(_:commit:)/title",
          "value": "removeReminder:commit:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1remove(_:commit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeReminder:commit:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/title",
          "value": "EKEventStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/title",
          "value": "EKCalendarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/creating-events-and-reminders"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/creating-events-and-reminders"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
