{
  "abstract": [
    {
      "text": "A bitmask indicating the event availability settings that the calendar can support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKCalendarEventAvailabilityMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKCalendarEventAvailabilityMask"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKCalendarEventAvailabilityMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "EKCalendarEventAvailabilityMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()": {
      "abstract": [
        {
          "text": "A deprecated function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DATETIME_COMPONENTS_DO_NOT_USE"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DATETIME_COMPONENTS_DO_NOT_USE"
        }
      ],
      "role": "symbol",
      "title": "DATETIME_COMPONENTS_DO_NOT_USE()",
      "type": "topic",
      "url": "/documentation/eventkit/datetime_components_do_not_use()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()": {
      "abstract": [
        {
          "text": "A deprecated function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DATE_COMPONENTS_DO_NOT_USE"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DATE_COMPONENTS_DO_NOT_USE"
        }
      ],
      "role": "symbol",
      "title": "DATE_COMPONENTS_DO_NOT_USE()",
      "type": "topic",
      "url": "/documentation/eventkit/date_components_do_not_use()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes": {
      "abstract": [
        {
          "text": "The entity types this calendar can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowedEntityTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEntityMask",
          "text": "EKEntityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowedEntityTypes"
        }
      ],
      "role": "symbol",
      "title": "allowedEntityTypes",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/allowedentitytypes"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can add, edit, and delete items in the calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentModifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsContentModifications"
        }
      ],
      "role": "symbol",
      "title": "allowsContentModifications",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/allowscontentmodifications"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for the calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calendarIdentifier"
        }
      ],
      "role": "symbol",
      "title": "calendarIdentifier",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/calendaridentifier"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor": {
      "abstract": [
        {
          "text": "The calendar’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGColor"
        }
      ],
      "role": "symbol",
      "title": "cgColor",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/cgcolor"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color": {
      "abstract": [
        {
          "text": "The calendar’s color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/color"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the calendar’s properties can be edited or deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isImmutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "immutable"
        }
      ],
      "role": "symbol",
      "title": "isImmutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/isimmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the calendar is a subscribed calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubscribed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribed"
        }
      ],
      "role": "symbol",
      "title": "isSubscribed",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/issubscribed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source": {
      "abstract": [
        {
          "text": "The source object representing the account to which this calendar belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKSource",
          "text": "EKSource"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "source"
        }
      ],
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/source"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities": {
      "abstract": [
        {
          "text": "The event availability settings supported by this calendar, as indicated by a bitmask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedEventAvailabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedEventAvailabilities"
        }
      ],
      "role": "symbol",
      "title": "supportedEventAvailabilities",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/supportedeventavailabilities"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title": {
      "abstract": [
        {
          "text": "The calendar’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/title"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type": {
      "abstract": [
        {
          "text": "The calendar’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarType",
          "text": "EKCalendarType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendar/type"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask": {
      "abstract": [
        {
          "text": "A bitmask indicating the event availability settings that the calendar can support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarEventAvailabilityMask",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone": {
      "abstract": [
        {
          "text": "The calendar does not support event availability settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityNone"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKCalendarEventAvailabilityNone",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/ekcalendareventavailabilitynone"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy": {
      "abstract": [
        {
          "text": "The calendar supports the busy event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityBusy"
        }
      ],
      "role": "symbol",
      "title": "busy",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/busy"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free": {
      "abstract": [
        {
          "text": "The calendar supports the free event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityFree"
        }
      ],
      "role": "symbol",
      "title": "free",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/free"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a calendar event availability mask with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/init(rawvalue:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative": {
      "abstract": [
        {
          "text": "The calendar supports the tentative event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tentative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityTentative"
        }
      ],
      "role": "symbol",
      "title": "tentative",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/tentative"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable": {
      "abstract": [
        {
          "text": "The calendar supports the unavailable event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityUnavailable"
        }
      ],
      "role": "symbol",
      "title": "unavailable",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/unavailable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType": {
      "abstract": [
        {
          "text": "Possible calendar types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarType"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarType",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendartype"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Calendar-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
        "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
        "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()"
      ],
      "title": "Accessing Calendar Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKCalendarEventAvailabilityMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Calendar-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarType",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowsContentModifications",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/cgColor",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/color",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isImmutable",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/title",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/type",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/allowedEntityTypes",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/source",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/isSubscribed",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/supportedEventAvailabilities",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendar/calendarIdentifier",
                "doc://com.apple.eventkit/documentation/EventKit/DATETIME_COMPONENTS_DO_NOT_USE()",
                "doc://com.apple.eventkit/documentation/EventKit/DATE_COMPONENTS_DO_NOT_USE()"
              ],
              "title": "Accessing Calendar Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EKCalendarEventAvailabilityMask"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1color/title",
          "value": "color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1unavailable/title",
          "value": "EKCalendarEventAvailabilityUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1free/title",
          "value": "EKCalendarEventAvailabilityFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1free/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1tentative/title",
          "value": "EKCalendarEventAvailabilityTentative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1tentative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityTentative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/title",
          "value": "EKCalendarEventAvailabilityMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1calendarIdentifier/title",
          "value": "calendarIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1calendarIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calendarIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1supportedEventAvailabilities/title",
          "value": "supportedEventAvailabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1supportedEventAvailabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedEventAvailabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowsContentModifications/title",
          "value": "allowsContentModifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowsContentModifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsContentModifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isSubscribed/title",
          "value": "subscribed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isSubscribed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscribed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1source/title",
          "value": "source"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1source/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATETIME_COMPONENTS_DO_NOT_USE()/title",
          "value": "DATETIME_COMPONENTS_DO_NOT_USE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATETIME_COMPONENTS_DO_NOT_USE()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DATETIME_COMPONENTS_DO_NOT_USE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1busy/title",
          "value": "EKCalendarEventAvailabilityBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowedEntityTypes/title",
          "value": "allowedEntityTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1allowedEntityTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowedEntityTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATE_COMPONENTS_DO_NOT_USE()/title",
          "value": "DATE_COMPONENTS_DO_NOT_USE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1DATE_COMPONENTS_DO_NOT_USE()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DATE_COMPONENTS_DO_NOT_USE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isImmutable/title",
          "value": "immutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1isImmutable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "immutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1cgColor/title",
          "value": "CGColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendar~1cgColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/title",
          "value": "EKCalendarType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekcalendareventavailabilitymask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekcalendareventavailabilitymask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
