{
  "abstract": [
    {
      "text": "An EventKit error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11EKErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKError"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "EKError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError": {
      "abstract": [
        {
          "text": "An EventKit error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKError"
        }
      ],
      "role": "symbol",
      "title": "EKError",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/Code": {
      "abstract": [
        {
          "text": "Error codes for EventKit errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "EKError.Code",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/code"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The alarm interval is greater than the recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmGreaterThanRecurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "alarmGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/alarmgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmProximityNotSupported": {
      "abstract": [
        {
          "text": "The source doesn’t allow geofences on alarms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alarmProximityNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmProximityNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "alarmProximityNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/alarmproximitynotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowEvents": {
      "abstract": [
        {
          "text": "The calendar doesn’t allow you to add events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarDoesNotAllowEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowEvents",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarDoesNotAllowEvents",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendardoesnotallowevents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowReminders": {
      "abstract": [
        {
          "text": "The calendar doesn’t allow you to add reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarDoesNotAllowReminders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowReminders",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarDoesNotAllowReminders",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendardoesnotallowreminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource": {
      "abstract": [
        {
          "text": "You can’t save the calendar without setting a source first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarHasNoSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarHasNoSource",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarhasnosource"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarIsImmutable": {
      "abstract": [
        {
          "text": "The calendar is immutable and you can’t modify or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarIsImmutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarIsImmutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarIsImmutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarisimmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly": {
      "abstract": [
        {
          "text": "The calendar is read-only and you can’t add events to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarReadOnly",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarreadonly"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified": {
      "abstract": [
        {
          "text": "You can’t move the calendar to another source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarSourceCannotBeModified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarSourceCannotBeModified",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/calendarsourcecannotbemodified"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted": {
      "abstract": [
        {
          "text": "The event’s end date occurs before its start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "datesInverted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted",
      "kind": "symbol",
      "role": "symbol",
      "title": "datesInverted",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/datesinverted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence": {
      "abstract": [
        {
          "text": "The duration of an event is greater than its recurrence interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationGreaterThanRecurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "durationGreaterThanRecurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/durationgreaterthanrecurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/errordomain"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable": {
      "abstract": [
        {
          "text": "The event isn’t mutable and you can’t save or delete it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventNotMutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "eventNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/eventnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/eventStoreNotAuthorized": {
      "abstract": [
        {
          "text": "The user hasn’t authorized your app to access events or reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventStoreNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/eventStoreNotAuthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "eventStoreNotAuthorized",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/eventstorenotauthorized"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure": {
      "abstract": [
        {
          "text": "An internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "internalFailure",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/internalfailure"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidEntityType": {
      "abstract": [
        {
          "text": "The entity type is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEntityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidEntityType",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidEntityType",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invalidentitytype"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidInviteReplyCalendar": {
      "abstract": [
        {
          "text": "The calendar is invalid or nil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidInviteReplyCalendar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidInviteReplyCalendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidInviteReplyCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invalidinvitereplycalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan": {
      "abstract": [
        {
          "text": "The system encountered an invalid span during a save or deletion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSpan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidSpan",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invalidspan"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved": {
      "abstract": [
        {
          "text": "You can’t move the event because it’s an invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invitesCannotBeMoved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "invitesCannotBeMoved",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/invitescannotbemoved"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/last": {
      "abstract": [
        {
          "text": "This error is for internal use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "last"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/last",
      "kind": "symbol",
      "role": "symbol",
      "title": "last",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/last"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar": {
      "abstract": [
        {
          "text": "The event isn’t associated with a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCalendar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar",
      "kind": "symbol",
      "role": "symbol",
      "title": "noCalendar",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/nocalendar"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate": {
      "abstract": [
        {
          "text": "The event has no start date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noEndDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "noEndDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/noenddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate": {
      "abstract": [
        {
          "text": "The event has no end date set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "noStartDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/nostartdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationCollectionMismatch": {
      "abstract": [
        {
          "text": "The notification collection that contains this notification doesn’t match the collection the system is trying to save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationCollectionMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationCollectionMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationCollectionMismatch",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/notificationcollectionmismatch"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationSavedWithoutCollection": {
      "abstract": [
        {
          "text": "The notification can’t save because you haven’t added it to a notification collection and saved the collection first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationSavedWithoutCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationSavedWithoutCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationSavedWithoutCollection",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/notificationsavedwithoutcollection"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationsCollectionFlagNotSet": {
      "abstract": [
        {
          "text": "The notification collection doesn’t have the notifications collection flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationsCollectionFlagNotSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationsCollectionFlagNotSet",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationsCollectionFlagNotSet",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/notificationscollectionflagnotset"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore": {
      "abstract": [
        {
          "text": "The object belongs to a different calendar store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectBelongsToDifferentStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectBelongsToDifferentStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/objectbelongstodifferentstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/osNotSupported": {
      "abstract": [
        {
          "text": "The action isn’t supported on the current operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "osNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/osNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "osNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/osnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/priorityIsInvalid": {
      "abstract": [
        {
          "text": "The priority number for the reminder is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "priorityIsInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/priorityIsInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "priorityIsInvalid",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/priorityisinvalid"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/procedureAlarmsNotMutable": {
      "abstract": [
        {
          "text": "You can’t create or modify procedure alarms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "procedureAlarmsNotMutable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/procedureAlarmsNotMutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "procedureAlarmsNotMutable",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/procedurealarmsnotmutable"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/recurringReminderRequiresDueDate": {
      "abstract": [
        {
          "text": "The recurring reminder requires a due date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurringReminderRequiresDueDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/recurringReminderRequiresDueDate",
      "kind": "symbol",
      "role": "symbol",
      "title": "recurringReminderRequiresDueDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/recurringreminderrequiresduedate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderAlarmContainsEmailOrUrl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminderAlarmContainsEmailOrUrl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderAlarmContainsEmailOrUrl",
      "kind": "symbol",
      "role": "symbol",
      "title": "reminderAlarmContainsEmailOrUrl",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/reminderalarmcontainsemailorurl"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderLocationsNotSupported": {
      "abstract": [
        {
          "text": "The source doesn’t support locations on reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminderLocationsNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderLocationsNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "reminderLocationsNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/reminderlocationsnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowCalendarAddDelete": {
      "abstract": [
        {
          "text": "The source doesn’t allow you to add or delete calendars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowCalendarAddDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowCalendarAddDelete",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceDoesNotAllowCalendarAddDelete",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/sourcedoesnotallowcalendaradddelete"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowEvents": {
      "abstract": [
        {
          "text": "The source doesn’t allow calendars supporting event entity types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowEvents",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceDoesNotAllowEvents",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/sourcedoesnotallowevents"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowReminders": {
      "abstract": [
        {
          "text": "The source doesn’t allow calendars supporting reminder entity types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceDoesNotAllowReminders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowReminders",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceDoesNotAllowReminders",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/sourcedoesnotallowreminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceMismatch": {
      "abstract": [
        {
          "text": "The object’s source doesn’t match its container’s source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceMismatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceMismatch",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceMismatch",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/sourcemismatch"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence": {
      "abstract": [
        {
          "text": "The event’s start date collides with another occurrence of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateCollidesWithOtherOccurrence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence",
      "kind": "symbol",
      "role": "symbol",
      "title": "startDateCollidesWithOtherOccurrence",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/startdatecollideswithotheroccurrence"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture": {
      "abstract": [
        {
          "text": "The start date is further into the future than the calendar can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDateTooFarInFuture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture",
      "kind": "symbol",
      "role": "symbol",
      "title": "startDateTooFarInFuture",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/startdatetoofarinfuture"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKError/structuredLocationsNotSupported": {
      "abstract": [
        {
          "text": "The source to which this calendar belongs doesn’t support structured locations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "structuredLocationsNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11EKErrorCodeLeV",
          "text": "EKError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKError/structuredLocationsNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "structuredLocationsNotSupported",
      "type": "topic",
      "url": "/documentation/eventkit/ekerror/structuredlocationsnotsupported"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the EventKit error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "EKErrorDomain",
      "type": "topic",
      "url": "/documentation/eventkit/ekerrordomain"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/Code",
        "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/eventNotMutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noEndDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/noStartDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/datesInverted",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/internalFailure",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarReadOnly",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/durationGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmGreaterThanRecurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateTooFarInFuture",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/startDateCollidesWithOtherOccurrence",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/objectBelongsToDifferentStore",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invitesCannotBeMoved",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidSpan",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarHasNoSource",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarSourceCannotBeModified",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarIsImmutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowCalendarAddDelete",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/recurringReminderRequiresDueDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/structuredLocationsNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderLocationsNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/alarmProximityNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowEvents",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/calendarDoesNotAllowReminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowReminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceDoesNotAllowEvents",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/priorityIsInvalid",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidEntityType",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/procedureAlarmsNotMutable",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/eventStoreNotAuthorized",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/osNotSupported",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/invalidInviteReplyCalendar",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationsCollectionFlagNotSet",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/sourceMismatch",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationCollectionMismatch",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/notificationSavedWithoutCollection",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/last"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKError/errorDomain",
        "doc://com.apple.eventkit/documentation/EventKit/EKError/reminderAlarmContainsEmailOrUrl"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/title",
          "value": "EKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/title",
          "value": "EKErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKErrorDomain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
