{
  "abstract": [
    {
      "text": "A class that represents an event in a calendar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EKEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKEvent"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "EKEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create a new event. Use the properties in the class to get and modify certain information about an event. Other properties, such as the event’s title and calendar, are inherited from the parent class ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem": {
      "abstract": [
        {
          "text": "An abstract superclass for calendar events and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarItem"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarItem",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendaritem"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent": {
      "abstract": [
        {
          "text": "A class that represents an event in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "role": "symbol",
      "title": "EKEvent",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/availability": {
      "abstract": [
        {
          "text": "The availability setting for the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEventAvailability",
          "text": "EKEventAvailability"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/availability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availability"
        }
      ],
      "role": "symbol",
      "title": "availability",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/availability"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayContactIdentifier": {
      "abstract": [
        {
          "text": "The contact identifier of the person for this birthday event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdayContactIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayContactIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "birthdayContactIdentifier"
        }
      ],
      "role": "symbol",
      "title": "birthdayContactIdentifier",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/birthdaycontactidentifier"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonID": {
      "abstract": [
        {
          "text": "The Address Book framework record identifier of the person for this birthday event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdayPersonID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "birthdayPersonID"
        }
      ],
      "role": "symbol",
      "title": "birthdayPersonID",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/birthdaypersonid"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonUniqueID": {
      "abstract": [
        {
          "text": "The Address Book framework record identifier of the person for this birthday event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdayPersonUniqueID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonUniqueID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "birthdayPersonUniqueID"
        }
      ],
      "role": "symbol",
      "title": "birthdayPersonUniqueID",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/birthdaypersonuniqueid"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/compareStartDate(with:)": {
      "abstract": [
        {
          "text": "Compares the start date of the receiving event with the start date of another event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compareStartDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEvent",
          "text": "EKEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSComparisonResult",
          "text": "ComparisonResult"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/compareStartDate(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareStartDateWithEvent:"
        }
      ],
      "role": "symbol",
      "title": "compareStartDate(with:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/comparestartdate(with:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate": {
      "abstract": [
        {
          "text": "The end date for the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/enddate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/eventIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/eventIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventIdentifier"
        }
      ],
      "role": "symbol",
      "title": "eventIdentifier",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/eventidentifier"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)": {
      "abstract": [
        {
          "text": "Creates and returns a new event belonging to a specified event store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "eventStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventStore",
          "text": "EKEventStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventWithEventStore:"
        }
      ],
      "role": "symbol",
      "title": "init(eventStore:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/init(eventstore:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isAllDay": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the event is an all-day event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAllDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isAllDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allDay"
        }
      ],
      "role": "symbol",
      "title": "isAllDay",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/isallday"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isDetached": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an event is a detached instance of a repeating event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDetached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isDetached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isDetached"
        }
      ],
      "role": "symbol",
      "title": "isDetached",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/isdetached"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/occurrenceDate": {
      "abstract": [
        {
          "text": "The original occurrence date of an event if it is part of a recurring series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "occurrenceDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/occurrenceDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "occurrenceDate"
        }
      ],
      "role": "symbol",
      "title": "occurrenceDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/occurrencedate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/organizer": {
      "abstract": [
        {
          "text": "The organizer associated with the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "organizer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKParticipant",
          "text": "EKParticipant"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/organizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "organizer"
        }
      ],
      "role": "symbol",
      "title": "organizer",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/organizer"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/refresh()": {
      "abstract": [
        {
          "text": "Updates the event’s data with the current information in the Calendar database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refresh"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/refresh()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refresh"
        }
      ],
      "role": "symbol",
      "title": "refresh()",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/refresh()"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate": {
      "abstract": [
        {
          "text": "The start date of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/startdate"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/status": {
      "abstract": [
        {
          "text": "The status of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEventStatus",
          "text": "EKEventStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/status"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent/structuredLocation": {
      "abstract": [
        {
          "text": "The event’s location with a potential geocoordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "structuredLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKStructuredLocation",
          "text": "EKStructuredLocation"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent/structuredLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "structuredLocation"
        }
      ],
      "role": "symbol",
      "title": "structuredLocation",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent/structuredlocation"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability": {
      "abstract": [
        {
          "text": "The event’s availability setting for scheduling purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventAvailability"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventAvailability"
        }
      ],
      "role": "symbol",
      "title": "EKEventAvailability",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventavailability"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStatus": {
      "abstract": [
        {
          "text": "The event’s status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventStatus"
        }
      ],
      "role": "symbol",
      "title": "EKEventStatus",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstatus"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder": {
      "abstract": [
        {
          "text": "A class that represents a reminder in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "role": "symbol",
      "title": "EKReminder",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders": {
      "abstract": [
        {
          "text": "Create and modify events and reminders in a person’s database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Creating events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/creating-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders": {
      "abstract": [
        {
          "text": "Add, fetch, complete, remove, and sort location-based reminders in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
      "kind": "article",
      "role": "sampleCode",
      "title": "Managing Location-Based Reminders",
      "type": "topic",
      "url": "/documentation/eventkit/managing-location-based-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders": {
      "abstract": [
        {
          "text": "Fetch events and reminders from the Calendar database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Retrieving events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/retrieving-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications": {
      "abstract": [
        {
          "text": "Register for notifications about changes and keep your app up to date.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Updating with notifications",
      "type": "topic",
      "url": "/documentation/eventkit/updating-with-notifications"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Events-and-reminders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
        "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
      ],
      "title": "Events and reminders"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Events",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)"
      ],
      "title": "Creating Events"
    },
    {
      "anchor": "Scheduling-Events",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEventStatus",
        "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability"
      ],
      "title": "Scheduling Events"
    },
    {
      "anchor": "Comparing-Events",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/compareStartDate(with:)"
      ],
      "title": "Comparing Events"
    },
    {
      "anchor": "Accessing-Event-Properties",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/eventIdentifier",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/availability",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isAllDay",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/occurrenceDate",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isDetached",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/organizer",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/status",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayContactIdentifier",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/structuredLocation",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonID",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonUniqueID"
      ],
      "title": "Accessing Event Properties"
    },
    {
      "anchor": "Refreshing-Event-Data",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent/refresh()"
      ],
      "title": "Refreshing Event Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Events",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/init(eventStore:)"
              ],
              "title": "Creating Events"
            },
            {
              "anchor": "Scheduling-Events",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEventStatus",
                "doc://com.apple.eventkit/documentation/EventKit/EKEventAvailability"
              ],
              "title": "Scheduling Events"
            },
            {
              "anchor": "Comparing-Events",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/compareStartDate(with:)"
              ],
              "title": "Comparing Events"
            },
            {
              "anchor": "Accessing-Event-Properties",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/eventIdentifier",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/availability",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/startDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/endDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isAllDay",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/occurrenceDate",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/isDetached",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/organizer",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/status",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayContactIdentifier",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/structuredLocation",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonID",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/birthdayPersonUniqueID"
              ],
              "title": "Accessing Event Properties"
            },
            {
              "anchor": "Refreshing-Event-Data",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent/refresh()"
              ],
              "title": "Refreshing Event Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Events-and-reminders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
                "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
              ],
              "title": "Events and reminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EKEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EKCalendarItem",
                    "text": "EKCalendarItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStatus/title",
          "value": "EKEventStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayPersonUniqueID/title",
          "value": "birthdayPersonUniqueID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayPersonUniqueID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "birthdayPersonUniqueID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1refresh()/title",
          "value": "refresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1refresh()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "refresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1organizer/title",
          "value": "organizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1organizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "organizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayPersonID/title",
          "value": "birthdayPersonID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayPersonID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "birthdayPersonID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1isAllDay/title",
          "value": "allDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1isAllDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/title",
          "value": "EKEventAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventAvailability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1eventIdentifier/title",
          "value": "eventIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1eventIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eventIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1structuredLocation/title",
          "value": "structuredLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1structuredLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "structuredLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/title",
          "value": "EKCalendarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1compareStartDate(with:)/title",
          "value": "compareStartDateWithEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1compareStartDate(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "compareStartDateWithEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1init(eventStore:)/title",
          "value": "eventWithEventStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1init(eventStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "eventWithEventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1isDetached/title",
          "value": "isDetached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1isDetached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isDetached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayContactIdentifier/title",
          "value": "birthdayContactIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1birthdayContactIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "birthdayContactIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/title",
          "value": "EKEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1occurrenceDate/title",
          "value": "occurrenceDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1occurrenceDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "occurrenceDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1availability/title",
          "value": "availability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1availability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/title",
          "value": "EKReminder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
