{
  "abstract": [
    {
      "text": "The participant’s attendance status for an event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKParticipantStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EKParticipantStatus"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKParticipantStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "EKParticipantStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole": {
      "abstract": [
        {
          "text": "The participant’s role for an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantRole"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantRole"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantRole",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantrole"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus": {
      "abstract": [
        {
          "text": "The participant’s scheduled status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantScheduleStatus"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantScheduleStatus",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantschedulestatus"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus": {
      "abstract": [
        {
          "text": "The participant’s attendance status for an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatus"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted": {
      "abstract": [
        {
          "text": "The participant has accepted the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accepted"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusAccepted"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.accepted",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/accepted"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed": {
      "abstract": [
        {
          "text": "The participant’s event has completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusCompleted"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.completed",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/completed"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined": {
      "abstract": [
        {
          "text": "The participant has declined the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declined"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusDeclined"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.declined",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/declined"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated": {
      "abstract": [
        {
          "text": "The participant has delegated attendance to another participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegated"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusDelegated"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.delegated",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/delegated"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess": {
      "abstract": [
        {
          "text": "The participant’s event is currently in process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProcess"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusInProcess"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.inProcess",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/inprocess"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/init(rawvalue:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending": {
      "abstract": [
        {
          "text": "The participant has yet to respond to the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pending"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusPending"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.pending",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/pending"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative": {
      "abstract": [
        {
          "text": "The participant’s attendance status is tentative.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tentative"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusTentative"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.tentative",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/tentative"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown": {
      "abstract": [
        {
          "text": "The participant’s attendance status is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantStatus.unknown",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipantstatus/unknown"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKParticipantType": {
      "abstract": [
        {
          "text": "The type of participant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKParticipantType"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKParticipantType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKParticipantType"
        }
      ],
      "role": "symbol",
      "title": "EKParticipantType",
      "type": "topic",
      "url": "/documentation/eventkit/ekparticipanttype"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-Participants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantType",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus"
      ],
      "title": "Defining Participants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKParticipantStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/unknown",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/pending",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/accepted",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/declined",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/tentative",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/delegated",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/completed",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantStatus/inProcess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-Participants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantRole",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantType",
                "doc://com.apple.eventkit/documentation/EventKit/EKParticipantScheduleStatus"
              ],
              "title": "Defining Participants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "EKParticipantStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1tentative/title",
          "value": "EKParticipantStatusTentative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1tentative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusTentative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/title",
          "value": "EKParticipantRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantType/title",
          "value": "EKParticipantType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1pending/title",
          "value": "EKParticipantStatusPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1pending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1accepted/title",
          "value": "EKParticipantStatusAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1accepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1completed/title",
          "value": "EKParticipantStatusCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1delegated/title",
          "value": "EKParticipantStatusDelegated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1delegated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusDelegated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1inProcess/title",
          "value": "EKParticipantStatusInProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1inProcess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusInProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/title",
          "value": "EKParticipantScheduleStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantScheduleStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantScheduleStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/title",
          "value": "EKParticipantStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1declined/title",
          "value": "EKParticipantStatusDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1declined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1unknown/title",
          "value": "EKParticipantStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKParticipantStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKParticipantStatusUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekparticipantstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekparticipantstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
