{
  "abstract": [
    {
      "text": "Add, fetch, complete, remove, and sort location-based reminders in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/managing-location-based-reminders"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Managing Location-Based Reminders"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With the Reminders app, users can create reminders with attachments, and alarms based on time and location. When Location Services is turned on, users receive location-based reminders when entering or leaving a specified geographic area or geofence. This sample demonstrates how to add, fetch, complete, remove, and sort location-based reminders.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-a-Purpose-String",
          "level": 3,
          "text": "Provide a Purpose String",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample first requests and receives authorization from the user before the app attempts to access their reminder data. It provides a purpose string or usage description that describes how the app intends to use the user’s reminder data. It then adds the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersusagedescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key to the app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": ". The sample sets its value to a string that explains why the app needs access to reminder data. The system displays the string when prompting the user for authorization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This ",
                  "type": "text"
                },
                {
                  "code": "NSRemindersUsageDescription",
                  "type": "codeVoice"
                },
                {
                  "text": " key is required for apps that access the user’s reminder data. Apps crash when the key is absent.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Request-Authorization",
          "level": 3,
          "text": "Request Authorization",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set up your app to instantiate and use a single instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that manages all reminder-related tasks. An ",
              "type": "text"
            },
            {
              "code": "EKEventStore",
              "type": "codeVoice"
            },
            {
              "text": " object requires a significant amount of time to initialize and release. The user might add, remove, or update reminders while your app is running. Register for an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/foundation/nsnotification/name/ekeventstorechanged",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification to be notified about changes to the Calendar database. When you receive this notification, refresh all your reminder data. It’s possible that your current data is stale or invalid. For more information on change notification, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/updating_with_notifications",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The user grants or denies permission when apps request access to their reminder data. Because the user can change the app’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "authorization status later in the Settings app ( Settings > Privacy > Reminders) on their device, the sample calls ",
              "type": "text"
            },
            {
              "code": "EKEventStore",
              "type": "codeVoice"
            },
            {
              "text": "’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/authorizationStatus(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEntityType/reminder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " entity type",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "before attempting to access their reminder data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "guard EKEventStore.authorizationStatus(for: .reminder) == .notDetermined else {",
            "    // The user may have already granted, denied, or restricted access to Reminders.",
            "    verifyAuthorizationStatus()",
            "    return",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the authorization status is ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/notDetermined",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", create an instance of ",
              "type": "text"
            },
            {
              "code": "EKEventStore",
              "type": "codeVoice"
            },
            {
              "text": ", then store a strong reference to it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private var store = EKEventStore()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, call its ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/requestaccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to prompt the user for access.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "store.requestAccess(to: .reminder, completion: {(granted, error) in",
            "    if granted { self.accessGranted() }",
            "})"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The system remembers the user’s answer, so that subsequent calls to ",
              "type": "text"
            },
            {
              "code": "requestAccess(to:completion:)",
              "type": "codeVoice"
            },
            {
              "text": " don’t again prompt the user.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information on user’s reminder data access, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/accessing_the_event_store",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Map-Annotations",
          "level": 3,
          "text": "Map Annotations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app uses the current user location and location-specific data saved in the ",
              "type": "text"
            },
            {
              "code": "MapData.plist",
              "type": "codeVoice"
            },
            {
              "text": " file to create annotations for the map. It defines a ",
              "type": "text"
            },
            {
              "code": "MapData",
              "type": "codeVoice"
            },
            {
              "text": " data type to represent each point of interest. ",
              "type": "text"
            },
            {
              "code": "MapData.plist",
              "type": "codeVoice"
            },
            {
              "text": " contains three ",
              "type": "text"
            },
            {
              "code": "MapData",
              "type": "codeVoice"
            },
            {
              "text": " entries. To test reminders around other locations, duplicate and update a ",
              "type": "text"
            },
            {
              "code": "MapData",
              "type": "codeVoice"
            },
            {
              "text": " entry in ",
              "type": "text"
            },
            {
              "code": "MapData.plist",
              "type": "codeVoice"
            },
            {
              "text": " with other data as needed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Creating location-based reminders doesn’t require location services.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The sample app uses location services to display the user’s current location on the map. As such, it includes and configures the ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " key in its ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": ". This key is required for apps that access the user’s location services. For more information on user’s location services access, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Check-for-the-Existence-of-a-Default-List",
          "level": 3,
          "text": "Check for the Existence of a Default List",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creating a reminder requires a list, which is a calendar for these items. Use ",
              "type": "text"
            },
            {
              "code": "EKEventStore",
              "type": "codeVoice"
            },
            {
              "text": "’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/defaultcalendarfornewreminders",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to check whether the user has specified a default list for reminders. If ",
              "type": "text"
            },
            {
              "code": "defaultCalendarForNewReminders()",
              "type": "codeVoice"
            },
            {
              "text": " returns no value, prompt the user to create a list in the Reminders app or provide a mechanism that lets them create it from within the app. The app provides an ",
              "type": "text"
            },
            {
              "code": "Add List",
              "type": "codeVoice"
            },
            {
              "text": " button that allows users to create a new list.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-Location-Based-Reminders",
          "level": 3,
          "text": "Create Location-Based Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A location-based reminder is a reminder created with a geofence-enabled alarm. A geofence-enabled alarm has a structured location and proximity configured. The structured",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "location consists of a location object and radius. The ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/radius",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is defined in meters and uses the system’s default radius when its value is 0. When the user provides a value for ",
              "type": "text"
            },
            {
              "code": "radius",
              "type": "codeVoice"
            },
            {
              "text": " in a unit other than meters such as miles, convert this value before using it. The sample uses the following steps to create a location-based reminder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "First, it creates an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekreminder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object using ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekreminder/init",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", then it sets its ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/title",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/calendar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "guard let calendar = store.defaultCalendarForNewReminders() else { throw LocationBasedRemindersError.missingDefaultRemindersList }",
            "let reminder = EKReminder(eventStore: store)",
            "reminder.calendar = calendar",
            "reminder.title = title"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "code": "title",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "calendar",
                  "type": "codeVoice"
                },
                {
                  "text": " properties are required and must be set before saving the reminder.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Next, it creates a structured location by using either ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/init",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/init",
              "isActive": true,
              "overridingTitle": "init(mapItem:)",
              "overridingTitleInlineContent": [
                {
                  "code": "init(mapItem:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". When the location object has latitude and longitude coordinates, it uses ",
              "type": "text"
            },
            {
              "code": "init(title:)",
              "type": "codeVoice"
            },
            {
              "text": " to create the structured location. The sample initializes an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/corelocation/cllocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with the specified latitude and longitude, then assigns it to the created structured location’s ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/geolocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let structuredLocation = EKStructuredLocation(title: geofence.title)",
            "structuredLocation.geoLocation = CLLocation(latitude: coordinate.latitude, longitude: coordinate.longitude)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the location object is an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/mapkit/mkmapitem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, the sample uses ",
              "type": "text"
            },
            {
              "code": "init(mapItem:)",
              "type": "codeVoice"
            },
            {
              "text": " to create the structured",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let structuredLocation = EKStructuredLocation(mapItem: mapItem)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, it sets the structured location’s ",
              "type": "text"
            },
            {
              "code": "radius",
              "type": "codeVoice"
            },
            {
              "text": " property to a value in meters:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// The app displays the radius's value in miles. Let's convert it from miles to meters before assigning it to the radius property.",
            "structuredLocation.radius = 1609.344 * geofence.radius"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After that, it creates an ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, then sets its ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm/structuredlocation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the created structured location object. The sample then sets the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm/proximity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to a value to finish configuring the alarm’s geofence:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let alarm = EKAlarm()",
            "alarm.structuredLocation = structuredLocation",
            "alarm.proximity = geofence.proximity"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample adds the created alarm to the reminder. For more information on adding alarms, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/setting_an_alarm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "reminder.addAlarm(alarm)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, it saves the reminder to the user’s Calendar database:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "do {",
            "    try store.save(reminder, commit: true)",
            "} catch {",
            "    handleError(error, with: reminder.title)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Fetch-Location-Based-Reminders",
          "level": 3,
          "text": "Fetch Location-Based Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/fetchreminders",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method asynchronously fetches all reminders matching a given predicate. When successful, ",
              "type": "text"
            },
            {
              "code": "fetchReminders(matching:completion:)",
              "type": "codeVoice"
            },
            {
              "text": " returns an array that contains both time-based and location-based reminders.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Predicate that fetches all reminders in all of the user's calendars.",
            "let predicate = store.predicateForReminders(in: nil)",
            "var result = [EKReminder]()",
            "store.fetchReminders(matching: predicate, completion: {(reminders: [Any]?) in",
            "    if let reminders = reminders as? [EKReminder] {",
            "        // Filter reminders for the location ones.",
            "        result = reminders.filter({ (item: EKReminder) in item.isLocation })",
            "    }",
            "    ",
            "    DispatchQueue.main.async {",
            "        completion(result)",
            "    }",
            "})"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To retrieve location-based reminders, the sample parses this array for reminders defined with an existing alarm that has a ",
              "type": "text"
            },
            {
              "code": "structuredlocation",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "proximity",
              "type": "codeVoice"
            },
            {
              "text": " value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "/// Indicates whether a reminder is a location-based one.",
            "var isLocation: Bool {",
            "    guard let alarms = self.alarms else { return false }",
            "    ",
            "    return !alarms.filter({(alarm: EKAlarm) in",
            "        return (alarm.structuredLocation != nil) && ((alarm.proximity == .enter) || (alarm.proximity == .leave))",
            "    }).isEmpty",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Sort-Reminders",
          "level": 3,
          "text": "Sort Reminders",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Retrieving reminders from the Calendar database returns reminders sorted by creation date. To sort an array of ",
              "type": "text"
            },
            {
              "code": "EKReminder",
              "type": "codeVoice"
            },
            {
              "text": " objects by title, or any other property, the sample",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "implements ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/documentation/swift/array/sorted",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the array with a predicate that uses the property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " /// - Returns: An array of reminders sorted by title in an ascending order.",
            "func sortedByTitle() -> [EKReminder] {",
            "    return self.sorted(by: { (first: EKReminder, second: EKReminder) in",
            "        first.title.localizedCaseInsensitiveCompare(second.title) == .orderedAscending",
            "    })",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "80a0475a4ca8/ManagingLocationBasedReminders.zip": {
      "checksum": "80a0475a4ca8e512a0c5ebf7ca3706ef94931f66fae3cd402a50a0cd61e8cfbab2c1eb88f0377e4b448a41b271064ecd176bc7495dad18694d9e034aac460258",
      "identifier": "80a0475a4ca8/ManagingLocationBasedReminders.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/80a0475a4ca8/ManagingLocationBasedReminders.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEntityType/reminder": {
      "abstract": [
        {
          "text": "Represents a reminder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reminder"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEntityType/reminder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEntityTypeReminder"
        }
      ],
      "role": "symbol",
      "title": "EKEntityType.reminder",
      "type": "topic",
      "url": "/documentation/eventkit/ekentitytype/reminder"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEvent": {
      "abstract": [
        {
          "text": "A class that represents an event in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEvent"
        }
      ],
      "role": "symbol",
      "title": "EKEvent",
      "type": "topic",
      "url": "/documentation/eventkit/ekevent"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore": {
      "abstract": [
        {
          "text": "An object that accesses a person’s calendar events and reminders and supports the scheduling of new events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "role": "symbol",
      "title": "EKEventStore",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/authorizationStatus(for:)": {
      "abstract": [
        {
          "text": "Determines the authorization status for the given entity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEntityType",
          "text": "EKEntityType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKAuthorizationStatus",
          "text": "EKAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKEventStore/authorizationStatus(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatusForEntityType:"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus(for:)",
      "type": "topic",
      "url": "/documentation/eventkit/ekeventstore/authorizationstatus(for:)"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKReminder": {
      "abstract": [
        {
          "text": "A class that represents a reminder in a calendar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKReminder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKReminder"
        }
      ],
      "role": "symbol",
      "title": "EKReminder",
      "type": "topic",
      "url": "/documentation/eventkit/ekreminder"
    },
    "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders": {
      "abstract": [
        {
          "text": "Create and modify events and reminders in a person’s database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Creating events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/creating-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders": {
      "abstract": [
        {
          "text": "Fetch events and reminders from the Calendar database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
      "kind": "article",
      "role": "article",
      "title": "Retrieving events and reminders",
      "type": "topic",
      "url": "/documentation/eventkit/retrieving-events-and-reminders"
    },
    "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications": {
      "abstract": [
        {
          "text": "Register for notifications about changes and keep your app up to date.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Updating with notifications",
      "type": "topic",
      "url": "/documentation/eventkit/updating-with-notifications"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription",
      "title": "NSLocationWhenInUseUsageDescription",
      "titleInlineContent": [
        {
          "code": "NSLocationWhenInUseUsageDescription",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationwheninuseusagedescription"
    },
    "https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersusagedescription": {
      "identifier": "https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersusagedescription",
      "title": "NSRemindersUsageDescription",
      "titleInlineContent": [
        {
          "code": "NSRemindersUsageDescription",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersusagedescription"
    },
    "https://developer.apple.com/documentation/corelocation/cllocation": {
      "identifier": "https://developer.apple.com/documentation/corelocation/cllocation",
      "title": "CLLocation",
      "titleInlineContent": [
        {
          "code": "CLLocation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/corelocation/cllocation"
    },
    "https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services": {
      "identifier": "https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services",
      "title": "Requesting Authorization for Location Services",
      "titleInlineContent": [
        {
          "code": "Requesting Authorization for Location Services",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/corelocation/requesting_authorization_for_location_services"
    },
    "https://developer.apple.com/documentation/eventkit/accessing_the_event_store": {
      "identifier": "https://developer.apple.com/documentation/eventkit/accessing_the_event_store",
      "title": "Accessing the Event Store",
      "titleInlineContent": [
        {
          "code": "Accessing the Event Store",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/accessing_the_event_store"
    },
    "https://developer.apple.com/documentation/eventkit/ekalarm": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm",
      "title": "EKAlarm",
      "titleInlineContent": [
        {
          "code": "EKAlarm",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekalarm"
    },
    "https://developer.apple.com/documentation/eventkit/ekalarm/proximity": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm/proximity",
      "title": "proximity",
      "titleInlineContent": [
        {
          "code": "proximity",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekalarm/proximity"
    },
    "https://developer.apple.com/documentation/eventkit/ekalarm/structuredlocation": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekalarm/structuredlocation",
      "title": "structuredLocation",
      "titleInlineContent": [
        {
          "code": "structuredLocation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekalarm/structuredlocation"
    },
    "https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/notDetermined": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/notDetermined",
      "title": ".notDetermined",
      "titleInlineContent": [
        {
          "code": ".notDetermined",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekauthorizationstatus/notDetermined"
    },
    "https://developer.apple.com/documentation/eventkit/ekcalendaritem/calendar": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/calendar",
      "title": "calendar",
      "titleInlineContent": [
        {
          "code": "calendar",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/calendar"
    },
    "https://developer.apple.com/documentation/eventkit/ekcalendaritem/title": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/title",
      "title": "title",
      "titleInlineContent": [
        {
          "code": "title",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekcalendaritem/title"
    },
    "https://developer.apple.com/documentation/eventkit/ekeventstore/defaultcalendarfornewreminders": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/defaultcalendarfornewreminders",
      "title": "defaultCalendarForNewReminders()",
      "titleInlineContent": [
        {
          "code": "defaultCalendarForNewReminders()",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekeventstore/defaultcalendarfornewreminders"
    },
    "https://developer.apple.com/documentation/eventkit/ekeventstore/fetchreminders": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/fetchreminders",
      "title": "fetchReminders(matching:completion:)",
      "titleInlineContent": [
        {
          "code": "fetchReminders(matching:completion:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekeventstore/fetchreminders"
    },
    "https://developer.apple.com/documentation/eventkit/ekeventstore/requestaccess": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekeventstore/requestaccess",
      "title": "requestAccess(to:completion:)",
      "titleInlineContent": [
        {
          "code": "requestAccess(to:completion:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekeventstore/requestaccess"
    },
    "https://developer.apple.com/documentation/eventkit/ekreminder": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekreminder",
      "title": "EKReminder",
      "titleInlineContent": [
        {
          "code": "EKReminder",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekreminder"
    },
    "https://developer.apple.com/documentation/eventkit/ekreminder/init": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekreminder/init",
      "title": "init(eventStore:)",
      "titleInlineContent": [
        {
          "code": "init(eventStore:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekreminder/init"
    },
    "https://developer.apple.com/documentation/eventkit/ekstructuredlocation": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation",
      "title": "EKStructuredLocation",
      "titleInlineContent": [
        {
          "code": "EKStructuredLocation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation"
    },
    "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/geolocation": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/geolocation",
      "title": "geoLocation",
      "titleInlineContent": [
        {
          "code": "geoLocation",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/geolocation"
    },
    "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/init": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/init",
      "title": "init(title:)",
      "titleInlineContent": [
        {
          "code": "init(title:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/init"
    },
    "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/radius": {
      "identifier": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/radius",
      "title": "radius",
      "titleInlineContent": [
        {
          "code": "radius",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/ekstructuredlocation/radius"
    },
    "https://developer.apple.com/documentation/eventkit/setting_an_alarm": {
      "identifier": "https://developer.apple.com/documentation/eventkit/setting_an_alarm",
      "title": "Setting an Alarm",
      "titleInlineContent": [
        {
          "code": "Setting an Alarm",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/setting_an_alarm"
    },
    "https://developer.apple.com/documentation/eventkit/updating_with_notifications": {
      "identifier": "https://developer.apple.com/documentation/eventkit/updating_with_notifications",
      "title": "Updating with Notifications",
      "titleInlineContent": [
        {
          "code": "Updating with Notifications",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/eventkit/updating_with_notifications"
    },
    "https://developer.apple.com/documentation/foundation/nsnotification/name/ekeventstorechanged": {
      "identifier": "https://developer.apple.com/documentation/foundation/nsnotification/name/ekeventstorechanged",
      "title": "EKEventStoreChanged",
      "titleInlineContent": [
        {
          "code": "EKEventStoreChanged",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/foundation/nsnotification/name/ekeventstorechanged"
    },
    "https://developer.apple.com/documentation/mapkit/mkmapitem": {
      "identifier": "https://developer.apple.com/documentation/mapkit/mkmapitem",
      "title": "MKMapItem",
      "titleInlineContent": [
        {
          "code": "MKMapItem",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/mapkit/mkmapitem"
    },
    "https://developer.apple.com/documentation/swift/array/sorted": {
      "identifier": "https://developer.apple.com/documentation/swift/array/sorted",
      "title": "sorted(by:)",
      "titleInlineContent": [
        {
          "code": "sorted(by:)",
          "type": "codeVoice"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/documentation/swift/array/sorted"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "80a0475a4ca8/ManagingLocationBasedReminders.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Events-and-reminders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
        "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
        "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
        "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
      ],
      "title": "Events and reminders"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Events-and-reminders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/creating-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/retrieving-events-and-reminders",
                "doc://com.apple.eventkit/documentation/EventKit/updating-with-notifications",
                "doc://com.apple.eventkit/documentation/EventKit/EKEvent",
                "doc://com.apple.eventkit/documentation/EventKit/EKReminder"
              ],
              "title": "Events and reminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1authorizationStatus(for:)/title",
          "value": "authorizationStatusForEntityType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore~1authorizationStatus(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatusForEntityType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/title",
          "value": "EKReminder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKReminder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/title",
          "value": "EKEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEntityType~1reminder/title",
          "value": "EKEntityTypeReminder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEntityType~1reminder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEntityTypeReminder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/title",
          "value": "EKEventStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKEventStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/managing-location-based-reminders"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/managing-location-based-reminders"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
