{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"platforms":[{"name":"iOS","introducedAt":"14.6","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"14.6","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"14.6","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"11.4","deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"introducedAt":"14.6","deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"introducedAt":"7.5","deprecated":false,"name":"watchOS","beta":false}],"title":"AVError.Code.contentKeyRequestCancelled","externalID":"c:@E@AVError@AVErrorContentKeyRequestCancelled","modules":[{"name":"AVFoundation"}],"role":"symbol","symbolKind":"case"},"abstract":[{"type":"text","text":"The app canceled a request to retrieve a content key."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","seeAlsoSections":[{"anchor":"Error-Codes","title":"Error Codes","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/deviceAlreadyUsedByAnotherSession"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled"]},{"paths":["/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"abstract":[{"type":"text","text":"The app canceled a request to retrieve a content key."}],"type":"topic","title":"AVError.Code.contentKeyRequestCancelled","url":"/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentisunavailable","title":"AVError.Code.contentIsUnavailable","abstract":[{"text":"The captured content is unavailable.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentIsUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsNotAuthorized"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}],"abstract":[{"type":"text","text":"The user isn’t authorized to play the media."}],"type":"topic","title":"AVError.Code.contentIsNotAuthorized","url":"/documentation/avfoundation/averror-swift.struct/code/contentisnotauthorized","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayControllerRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay controller requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayControllerRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplaycontrollerrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentnotupdated","title":"AVError.Code.contentNotUpdated","abstract":[{"text":"The system couldn’t update the captured content.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentNotUpdated","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentNotUpdated","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createContentKeyRequestFailed"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}],"abstract":[{"type":"text","text":"The app couldn’t create a content key request."}],"type":"topic","title":"AVError.Code.createContentKeyRequestFailed","url":"/documentation/avfoundation/averror-swift.struct/code/createcontentkeyrequestfailed","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodernotfound","title":"AVError.Code.decoderNotFound","abstract":[{"text":"The system can’t find a suitable decoder for the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderNotFound","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay receiver requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayReceiverRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceiverrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code":{"url":"/documentation/avfoundation/averror-swift.struct/code","title":"AVError.Code","abstract":[{"text":"An enumeration that defines the errors that framework operations can generate.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsProtected"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"abstract":[{"type":"text","text":"The app isn’t authorized to open the media."}],"type":"topic","title":"AVError.Code.contentIsProtected","url":"/documentation/avfoundation/averror-swift.struct/code/contentisprotected","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodefailed","title":"AVError.Code.decodeFailed","abstract":[{"text":"The system failed to decode the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecodeFailed","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFailed","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodertemporarilyunavailable","title":"AVError.Code.decoderTemporarilyUnavailable","abstract":[{"text":"A suitable decoder for the media is temporarily available.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderTemporarilyUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverTemporarilyUnavailable"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}],"abstract":[{"type":"text","text":"An AirPlay receiver is temporarily unavailable."}],"type":"topic","title":"AVError.Code.airPlayReceiverTemporarilyUnavailable","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceivertemporarilyunavailable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorizedtousedevice","title":"AVError.Code.applicationIsNotAuthorizedToUseDevice","abstract":[{"text":"The user denied this app permission to capture media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/deviceAlreadyUsedByAnotherSession":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVErrorDeviceAlreadyUsedByAnotherSession"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/deviceAlreadyUsedByAnotherSession","type":"topic","abstract":[{"type":"text","text":"Your app can’t access the device because another session is currently using it."}],"url":"/documentation/avfoundation/averror-swift.struct/code/devicealreadyusedbyanothersession","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceAlreadyUsedByAnotherSession"}],"title":"AVError.Code.deviceAlreadyUsedByAnotherSession"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorized","title":"AVError.Code.applicationIsNotAuthorized","abstract":[{"text":"The app isn’t authorized to play media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorized","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVError"}],"navigatorTitle":[{"kind":"identifier","text":"AVError"}],"abstract":[{"type":"text","text":"A structure that defines the errors that framework operations can generate."}],"type":"topic","title":"AVError","url":"/documentation/avfoundation/averror-swift.struct","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositionTrackSegmentsNotContiguous"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCompositionTrackSegmentsNotContiguous"}],"abstract":[{"type":"text","text":"The composition can’t add the source media because it contains gaps."}],"type":"topic","title":"AVError.Code.compositionTrackSegmentsNotContiguous","url":"/documentation/avfoundation/averror-swift.struct/code/compositiontracksegmentsnotcontiguous","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"14.6","deprecated":false},{"deprecated":false,"name":"iPadOS","introducedAt":"14.6","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.6","unavailable":false,"beta":false},{"deprecated":false,"name":"macOS","introducedAt":"11.4","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","introducedAt":"14.6","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","beta":false,"unavailable":false},{"introducedAt":"7.5","deprecated":false,"name":"watchOS","beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"AVErrorContentKeyRequestCancelled","op":"replace","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/deviceAlreadyUsedByAnotherSession"],"generated":true,"anchor":"Error-Codes","title":"Error Codes"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"AVErrorContentKeyRequestCancelled","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/title","op":"replace"},{"value":[{"text":"AVErrorContentKeyRequestCancelled","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/fragments","op":"replace"},{"value":"AVErrorContentIsUnavailable","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVErrorContentIsUnavailable"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/fragments","op":"replace"},{"value":"AVErrorContentIsNotAuthorized","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/fragments","op":"replace"},{"value":"AVErrorAirPlayControllerRequiresInternet","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/title","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/fragments","value":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/title","value":"AVErrorContentNotUpdated","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/fragments","value":[{"kind":"identifier","text":"AVErrorContentNotUpdated"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/title","value":"AVErrorCreateContentKeyRequestFailed","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/fragments","value":[{"text":"AVErrorCreateContentKeyRequestFailed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/title","value":"AVErrorDecoderNotFound","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/fragments","value":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/title","value":"AVErrorAirPlayReceiverRequiresInternet","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/fragments","value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title","value":"AVError","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments","value":[{"kind":"identifier","text":"AVError"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle","value":[{"kind":"identifier","text":"AVError"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/title","value":"AVErrorContentIsProtected","op":"replace"},{"value":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/fragments"},{"value":"AVErrorDecodeFailed","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/title"},{"value":[{"kind":"identifier","text":"AVErrorDecodeFailed"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/fragments"},{"value":"AVErrorDecoderTemporarilyUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/title"},{"value":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/fragments"},{"value":"AVErrorAirPlayReceiverTemporarilyUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/title"},{"value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/fragments"},{"value":"AVErrorApplicationIsNotAuthorizedToUseDevice","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/title"},{"value":[{"kind":"identifier","text":"AVErrorApplicationIsNotAuthorizedToUseDevice"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/fragments"},{"value":"AVErrorDeviceAlreadyUsedByAnotherSession","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1deviceAlreadyUsedByAnotherSession/title"},{"value":[{"kind":"identifier","text":"AVErrorDeviceAlreadyUsedByAnotherSession"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1deviceAlreadyUsedByAnotherSession/fragments"},{"value":"AVErrorApplicationIsNotAuthorized","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/title"},{"value":[{"kind":"identifier","text":"AVErrorApplicationIsNotAuthorized"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/fragments"},{"value":"AVErrorCompositionTrackSegmentsNotContiguous","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/title"},{"value":[{"kind":"identifier","text":"AVErrorCompositionTrackSegmentsNotContiguous"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}