{
  "abstract": [
    {
      "text": "Screen capture failed because the display was inactive.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/displayWasDisabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVError@AVErrorDisplayWasDisabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "displayWasDisabled"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVErrorDisplayWasDisabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVError.Code.displayWasDisabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "displayWasDisabled"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "role": "symbol",
      "title": "AVError",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code": {
      "abstract": [
        {
          "text": "An enumeration that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet": {
      "abstract": [
        {
          "text": "The AirPlay controller requires an internet connection to function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayControllerRequiresInternet"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorAirPlayControllerRequiresInternet"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.airPlayControllerRequiresInternet",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/airplaycontrollerrequiresinternet"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet": {
      "abstract": [
        {
          "text": "The AirPlay receiver requires an internet connection to function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayReceiverRequiresInternet"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorAirPlayReceiverRequiresInternet"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.airPlayReceiverRequiresInternet",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/airplayreceiverrequiresinternet"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An AirPlay receiver is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayReceiverTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorAirPlayReceiverTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.airPlayReceiverTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/airplayreceivertemporarilyunavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized": {
      "abstract": [
        {
          "text": "The app isn’t authorized to play media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIsNotAuthorized"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorApplicationIsNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.applicationIsNotAuthorized",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorized"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice": {
      "abstract": [
        {
          "text": "The user denied this app permission to capture media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIsNotAuthorizedToUseDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorApplicationIsNotAuthorizedToUseDevice"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.applicationIsNotAuthorizedToUseDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorizedtousedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous": {
      "abstract": [
        {
          "text": "The composition can’t add the source media because it contains gaps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositionTrackSegmentsNotContiguous"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorCompositionTrackSegmentsNotContiguous"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.compositionTrackSegmentsNotContiguous",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/compositiontracksegmentsnotcontiguous"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized": {
      "abstract": [
        {
          "text": "The user isn’t authorized to play the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsNotAuthorized"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorContentIsNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.contentIsNotAuthorized",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/contentisnotauthorized"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected": {
      "abstract": [
        {
          "text": "The app isn’t authorized to open the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsProtected"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorContentIsProtected"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.contentIsProtected",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/contentisprotected"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable": {
      "abstract": [
        {
          "text": "The captured content is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsUnavailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorContentIsUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.contentIsUnavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/contentisunavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled": {
      "abstract": [
        {
          "text": "The app canceled a request to retrieve a content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeyRequestCancelled"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorContentKeyRequestCancelled"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.contentKeyRequestCancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated": {
      "abstract": [
        {
          "text": "The system couldn’t update the captured content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentNotUpdated"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorContentNotUpdated"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.contentNotUpdated",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/contentnotupdated"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed": {
      "abstract": [
        {
          "text": "The app couldn’t create a content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createContentKeyRequestFailed"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorCreateContentKeyRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.createContentKeyRequestFailed",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/createcontentkeyrequestfailed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed": {
      "abstract": [
        {
          "text": "The system failed to decode the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeFailed"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorDecodeFailed"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.decodeFailed",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/decodefailed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound": {
      "abstract": [
        {
          "text": "The system can’t find a suitable decoder for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decoderNotFound"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorDecoderNotFound"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.decoderNotFound",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/decodernotfound"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "A suitable decoder for the media is temporarily available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decoderTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorDecoderTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.decoderTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/decodertemporarilyunavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/displayWasDisabled": {
      "abstract": [
        {
          "text": "Screen capture failed because the display was inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayWasDisabled"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/displayWasDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVErrorDisplayWasDisabled"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code.displayWasDisabled",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code/displaywasdisabled"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVErrorDisplayWasDisabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorDisplayWasDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVErrorDisplayWasDisabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/title",
          "value": "AVErrorDecoderTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorDecoderTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/title",
          "value": "AVErrorContentNotUpdated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorContentNotUpdated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/title",
          "value": "AVErrorAirPlayControllerRequiresInternet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorAirPlayControllerRequiresInternet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/title",
          "value": "AVErrorCreateContentKeyRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorCreateContentKeyRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/title",
          "value": "AVErrorContentKeyRequestCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorContentKeyRequestCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/title",
          "value": "AVErrorDecodeFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorDecodeFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1displayWasDisabled/title",
          "value": "AVErrorDisplayWasDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1displayWasDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorDisplayWasDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/title",
          "value": "AVErrorAirPlayReceiverTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorAirPlayReceiverTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/title",
          "value": "AVErrorApplicationIsNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorApplicationIsNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/title",
          "value": "AVErrorContentIsNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorContentIsNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/title",
          "value": "AVErrorContentIsProtected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorContentIsProtected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/title",
          "value": "AVErrorDecoderNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorDecoderNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/title",
          "value": "AVErrorApplicationIsNotAuthorizedToUseDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorApplicationIsNotAuthorizedToUseDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/title",
          "value": "AVErrorContentIsUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorContentIsUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/title",
          "value": "AVErrorCompositionTrackSegmentsNotContiguous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorCompositionTrackSegmentsNotContiguous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/title",
          "value": "AVErrorAirPlayReceiverRequiresInternet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVErrorAirPlayReceiverRequiresInternet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title",
          "value": "AVError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/averror-swift.struct/code/displaywasdisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/averror-swift.struct/code/displaywasdisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
