{"metadata":{"title":"AVError.Code.encoderTemporarilyUnavailable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVErrorEncoderTemporarilyUnavailable"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","unavailable":false,"deprecated":false,"beta":false},{"name":"watchOS","unavailable":false,"deprecated":false,"beta":false}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoderTemporarilyUnavailable"}],"modules":[{"name":"AVFoundation"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@E@AVError@AVErrorEncoderTemporarilyUnavailable"},"abstract":[{"text":"An appropriate encoder isn’t currently available.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encoderTemporarilyUnavailable"}]}]}],"kind":"symbol","seeAlsoSections":[{"anchor":"Error-Codes","title":"Error Codes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/averror-swift.struct/code/encodertemporarilyunavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/averror-swift.struct/code/encodertemporarilyunavailable"]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/encoderTemporarilyUnavailable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositionTrackSegmentsNotContiguous"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCompositionTrackSegmentsNotContiguous"}],"abstract":[{"type":"text","text":"The composition can’t add the source media because it contains gaps."}],"type":"topic","title":"AVError.Code.compositionTrackSegmentsNotContiguous","url":"/documentation/avfoundation/averror-swift.struct/code/compositiontracksegmentsnotcontiguous","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsNotAuthorized"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}],"abstract":[{"type":"text","text":"The user isn’t authorized to play the media."}],"type":"topic","title":"AVError.Code.contentIsNotAuthorized","url":"/documentation/avfoundation/averror-swift.struct/code/contentisnotauthorized","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverTemporarilyUnavailable"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}],"abstract":[{"type":"text","text":"An AirPlay receiver is temporarily unavailable."}],"type":"topic","title":"AVError.Code.airPlayReceiverTemporarilyUnavailable","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceivertemporarilyunavailable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createContentKeyRequestFailed"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}],"abstract":[{"type":"text","text":"The app couldn’t create a content key request."}],"type":"topic","title":"AVError.Code.createContentKeyRequestFailed","url":"/documentation/avfoundation/averror-swift.struct/code/createcontentkeyrequestfailed","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorized","title":"AVError.Code.applicationIsNotAuthorized","abstract":[{"text":"The app isn’t authorized to play media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorized","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVError"}],"navigatorTitle":[{"kind":"identifier","text":"AVError"}],"abstract":[{"type":"text","text":"A structure that defines the errors that framework operations can generate."}],"type":"topic","title":"AVError","url":"/documentation/avfoundation/averror-swift.struct","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentnotupdated","title":"AVError.Code.contentNotUpdated","abstract":[{"text":"The system couldn’t update the captured content.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentNotUpdated","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentNotUpdated","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code":{"url":"/documentation/avfoundation/averror-swift.struct/code","title":"AVError.Code","abstract":[{"text":"An enumeration that defines the errors that framework operations can generate.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayControllerRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay controller requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayControllerRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplaycontrollerrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodertemporarilyunavailable","title":"AVError.Code.decoderTemporarilyUnavailable","abstract":[{"text":"A suitable decoder for the media is temporarily available.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderTemporarilyUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentisunavailable","title":"AVError.Code.contentIsUnavailable","abstract":[{"text":"The captured content is unavailable.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentIsUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay receiver requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayReceiverRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceiverrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsProtected"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"abstract":[{"type":"text","text":"The app isn’t authorized to open the media."}],"type":"topic","title":"AVError.Code.contentIsProtected","url":"/documentation/avfoundation/averror-swift.struct/code/contentisprotected","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorizedtousedevice","title":"AVError.Code.applicationIsNotAuthorizedToUseDevice","abstract":[{"text":"The user denied this app permission to capture media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodernotfound","title":"AVError.Code.decoderNotFound","abstract":[{"text":"The system can’t find a suitable decoder for the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderNotFound","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/encoderTemporarilyUnavailable":{"type":"topic","abstract":[{"text":"An appropriate encoder isn’t currently available.","type":"text"}],"url":"/documentation/avfoundation/averror-swift.struct/code/encodertemporarilyunavailable","role":"symbol","title":"AVError.Code.encoderTemporarilyUnavailable","navigatorTitle":[{"text":"AVErrorEncoderTemporarilyUnavailable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encoderTemporarilyUnavailable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/encoderTemporarilyUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"abstract":[{"type":"text","text":"The app canceled a request to retrieve a content key."}],"type":"topic","title":"AVError.Code.contentKeyRequestCancelled","url":"/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodefailed","title":"AVError.Code.decodeFailed","abstract":[{"text":"The system failed to decode the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecodeFailed","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFailed","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"AVErrorEncoderTemporarilyUnavailable","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AVErrorEncoderTemporarilyUnavailable"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"anchor":"Error-Codes","title":"Error Codes","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"identifier","text":"AVErrorEncoderTemporarilyUnavailable"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/title","op":"replace","value":"AVErrorCompositionTrackSegmentsNotContiguous"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/fragments","op":"replace","value":[{"text":"AVErrorCompositionTrackSegmentsNotContiguous","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/title","op":"replace","value":"AVErrorContentIsNotAuthorized"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/title","op":"replace","value":"AVErrorAirPlayReceiverTemporarilyUnavailable"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/title","op":"replace","value":"AVErrorCreateContentKeyRequestFailed"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/title","op":"replace","value":"AVErrorApplicationIsNotAuthorized"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/fragments","op":"replace","value":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}]},{"value":"AVErrorContentNotUpdated","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/title"},{"value":[{"text":"AVErrorContentNotUpdated","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/fragments"},{"value":"AVError","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title"},{"value":[{"text":"AVError","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments"},{"value":[{"text":"AVError","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle"},{"value":"AVErrorAirPlayControllerRequiresInternet","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/title"},{"value":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/fragments"},{"value":"AVErrorDecoderTemporarilyUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/title"},{"value":[{"kind":"identifier","text":"AVErrorDecoderTemporarilyUnavailable"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/fragments"},{"value":"AVErrorContentIsUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/title"},{"value":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/fragments"},{"value":"AVErrorAirPlayReceiverRequiresInternet","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/title"},{"value":[{"text":"AVErrorAirPlayReceiverRequiresInternet","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/fragments"},{"value":"AVErrorContentIsProtected","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/title"},{"value":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/fragments"},{"value":"AVErrorApplicationIsNotAuthorizedToUseDevice","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/title"},{"value":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/fragments"},{"value":"AVErrorDecoderNotFound","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/title"},{"value":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/fragments"},{"value":"AVErrorEncoderTemporarilyUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1encoderTemporarilyUnavailable/title"},{"value":[{"text":"AVErrorEncoderTemporarilyUnavailable","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1encoderTemporarilyUnavailable/fragments"},{"value":"AVErrorContentKeyRequestCancelled","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/title"},{"value":[{"text":"AVErrorContentKeyRequestCancelled","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/fragments"},{"value":"AVErrorDecodeFailed","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/title"},{"value":[{"text":"AVErrorDecodeFailed","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}