{"abstract":[{"type":"text","text":"The system can’t load the requested sample data."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/averror-swift.struct/code/failedtoloadsampledata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/averror-swift.struct/code/failedtoloadsampledata"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/failedToLoadSampleData"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSampleData","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Error-Codes","title":"Error Codes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"generated":true}],"metadata":{"externalID":"c:@E@AVError@AVErrorFailedToLoadSampleData","navigatorTitle":[{"text":"AVErrorFailedToLoadSampleData","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSampleData","kind":"identifier"}],"role":"symbol","title":"AVError.Code.failedToLoadSampleData","modules":[{"name":"AVFoundation"}],"roleHeading":"Case","symbolKind":"case","platforms":[{"name":"iOS","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"16.0","unavailable":false,"beta":false,"deprecated":false},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false,"introducedAt":"13.0"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"16.0"},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0"},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false,"introducedAt":"9.0"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"kind":"symbol","references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"abstract":[{"type":"text","text":"The app canceled a request to retrieve a content key."}],"type":"topic","title":"AVError.Code.contentKeyRequestCancelled","url":"/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodernotfound","title":"AVError.Code.decoderNotFound","abstract":[{"text":"The system can’t find a suitable decoder for the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderNotFound","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverTemporarilyUnavailable"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}],"abstract":[{"type":"text","text":"An AirPlay receiver is temporarily unavailable."}],"type":"topic","title":"AVError.Code.airPlayReceiverTemporarilyUnavailable","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceivertemporarilyunavailable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsNotAuthorized"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}],"abstract":[{"type":"text","text":"The user isn’t authorized to play the media."}],"type":"topic","title":"AVError.Code.contentIsNotAuthorized","url":"/documentation/avfoundation/averror-swift.struct/code/contentisnotauthorized","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodertemporarilyunavailable","title":"AVError.Code.decoderTemporarilyUnavailable","abstract":[{"text":"A suitable decoder for the media is temporarily available.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderTemporarilyUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsProtected"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"abstract":[{"type":"text","text":"The app isn’t authorized to open the media."}],"type":"topic","title":"AVError.Code.contentIsProtected","url":"/documentation/avfoundation/averror-swift.struct/code/contentisprotected","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createContentKeyRequestFailed"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}],"abstract":[{"type":"text","text":"The app couldn’t create a content key request."}],"type":"topic","title":"AVError.Code.createContentKeyRequestFailed","url":"/documentation/avfoundation/averror-swift.struct/code/createcontentkeyrequestfailed","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayControllerRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay controller requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayControllerRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplaycontrollerrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVError"}],"navigatorTitle":[{"kind":"identifier","text":"AVError"}],"abstract":[{"type":"text","text":"A structure that defines the errors that framework operations can generate."}],"type":"topic","title":"AVError","url":"/documentation/avfoundation/averror-swift.struct","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorized","title":"AVError.Code.applicationIsNotAuthorized","abstract":[{"text":"The app isn’t authorized to play media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorized","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodefailed","title":"AVError.Code.decodeFailed","abstract":[{"text":"The system failed to decode the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecodeFailed","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFailed","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/failedToLoadSampleData":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSampleData","kind":"identifier"}],"url":"/documentation/avfoundation/averror-swift.struct/code/failedtoloadsampledata","title":"AVError.Code.failedToLoadSampleData","navigatorTitle":[{"text":"AVErrorFailedToLoadSampleData","kind":"identifier"}],"type":"topic","abstract":[{"text":"The system can’t load the requested sample data.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/failedToLoadSampleData"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorizedtousedevice","title":"AVError.Code.applicationIsNotAuthorizedToUseDevice","abstract":[{"text":"The user denied this app permission to capture media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentisunavailable","title":"AVError.Code.contentIsUnavailable","abstract":[{"text":"The captured content is unavailable.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentIsUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositionTrackSegmentsNotContiguous"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCompositionTrackSegmentsNotContiguous"}],"abstract":[{"type":"text","text":"The composition can’t add the source media because it contains gaps."}],"type":"topic","title":"AVError.Code.compositionTrackSegmentsNotContiguous","url":"/documentation/avfoundation/averror-swift.struct/code/compositiontracksegmentsnotcontiguous","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentnotupdated","title":"AVError.Code.contentNotUpdated","abstract":[{"text":"The system couldn’t update the captured content.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentNotUpdated","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentNotUpdated","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay receiver requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayReceiverRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceiverrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code":{"url":"/documentation/avfoundation/averror-swift.struct/code","title":"AVError.Code","abstract":[{"text":"An enumeration that defines the errors that framework operations can generate.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"16.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"16.0","unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"introducedAt":"16.0","unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"macOS","deprecated":false},{"beta":false,"introducedAt":"16.0","unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","deprecated":false},{"beta":false,"introducedAt":"9.0","unavailable":false,"name":"watchOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"AVErrorFailedToLoadSampleData","op":"replace","path":"/metadata/title"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AVErrorFailedToLoadSampleData"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"title":"Error Codes","generated":true,"anchor":"Error-Codes"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"identifier","text":"AVErrorFailedToLoadSampleData"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/title","value":"AVErrorContentKeyRequestCancelled"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/fragments","value":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/title","value":"AVErrorDecoderNotFound"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/fragments","value":[{"kind":"identifier","text":"AVErrorDecoderNotFound"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/title","value":"AVErrorAirPlayReceiverTemporarilyUnavailable"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/fragments","value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/title","value":"AVErrorContentIsNotAuthorized"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/fragments","value":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/title","value":"AVErrorDecoderTemporarilyUnavailable"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/fragments","value":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/title","value":"AVErrorContentIsProtected"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/fragments","value":[{"kind":"identifier","text":"AVErrorContentIsProtected"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/title","value":"AVErrorCreateContentKeyRequestFailed"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/fragments","value":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/title","value":"AVErrorAirPlayControllerRequiresInternet"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/fragments","value":[{"text":"AVErrorAirPlayControllerRequiresInternet","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/title","value":"AVErrorApplicationIsNotAuthorized"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/fragments","value":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/title","value":"AVErrorDecodeFailed"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/fragments","value":[{"text":"AVErrorDecodeFailed","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1failedToLoadSampleData/title","value":"AVErrorFailedToLoadSampleData"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1failedToLoadSampleData/fragments","value":[{"text":"AVErrorFailedToLoadSampleData","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/title","value":"AVErrorApplicationIsNotAuthorizedToUseDevice"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/fragments","value":[{"kind":"identifier","text":"AVErrorApplicationIsNotAuthorizedToUseDevice"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/title","value":"AVErrorContentIsUnavailable"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/fragments","value":[{"kind":"identifier","text":"AVErrorContentIsUnavailable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/title","value":"AVErrorCompositionTrackSegmentsNotContiguous"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/fragments","value":[{"text":"AVErrorCompositionTrackSegmentsNotContiguous","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/title","value":"AVErrorContentNotUpdated"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/fragments","value":[{"kind":"identifier","text":"AVErrorContentNotUpdated"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/title","value":"AVErrorAirPlayReceiverRequiresInternet"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/fragments","value":[{"text":"AVErrorAirPlayReceiverRequiresInternet","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title","value":"AVError"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments","value":[{"kind":"identifier","text":"AVError"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle","value":[{"kind":"identifier","text":"AVError"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}