{"abstract":[{"type":"text","text":"You can’t add the source media because its start time in the destination is invalid."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]},"variants":[{"paths":["/documentation/avfoundation/averror-swift.struct/code/invalidcompositiontracksegmentsourcestarttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/averror-swift.struct/code/invalidcompositiontracksegmentsourcestarttime"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCompositionTrackSegmentSourceStartTime","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}],"metadata":{"modules":[{"name":"AVFoundation"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCompositionTrackSegmentSourceStartTime"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AVErrorInvalidCompositionTrackSegmentSourceStartTime"}],"externalID":"c:@E@AVError@AVErrorInvalidCompositionTrackSegmentSourceStartTime","symbolKind":"case","title":"AVError.Code.invalidCompositionTrackSegmentSourceStartTime","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","beta":false,"deprecated":false,"unavailable":false}],"role":"symbol"},"sections":[],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"generated":true,"title":"Error Codes","anchor":"Error-Codes"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/invalidCompositionTrackSegmentSourceStartTime"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay receiver requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayReceiverRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceiverrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodernotfound","title":"AVError.Code.decoderNotFound","abstract":[{"text":"The system can’t find a suitable decoder for the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderNotFound","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderNotFound","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayReceiverTemporarilyUnavailable"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}],"abstract":[{"type":"text","text":"An AirPlay receiver is temporarily unavailable."}],"type":"topic","title":"AVError.Code.airPlayReceiverTemporarilyUnavailable","url":"/documentation/avfoundation/averror-swift.struct/code/airplayreceivertemporarilyunavailable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositionTrackSegmentsNotContiguous"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCompositionTrackSegmentsNotContiguous"}],"abstract":[{"type":"text","text":"The composition can’t add the source media because it contains gaps."}],"type":"topic","title":"AVError.Code.compositionTrackSegmentsNotContiguous","url":"/documentation/avfoundation/averror-swift.struct/code/compositiontracksegmentsnotcontiguous","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsProtected"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsProtected"}],"abstract":[{"type":"text","text":"The app isn’t authorized to open the media."}],"type":"topic","title":"AVError.Code.contentIsProtected","url":"/documentation/avfoundation/averror-swift.struct/code/contentisprotected","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodertemporarilyunavailable","title":"AVError.Code.decoderTemporarilyUnavailable","abstract":[{"text":"A suitable decoder for the media is temporarily available.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecoderTemporarilyUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoderTemporarilyUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorized","title":"AVError.Code.applicationIsNotAuthorized","abstract":[{"text":"The app isn’t authorized to play media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorized","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorized","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentisunavailable","title":"AVError.Code.contentIsUnavailable","abstract":[{"text":"The captured content is unavailable.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentIsUnavailable","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/invalidCompositionTrackSegmentSourceStartTime":{"abstract":[{"type":"text","text":"You can’t add the source media because its start time in the destination is invalid."}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorInvalidCompositionTrackSegmentSourceStartTime"}],"role":"symbol","url":"/documentation/avfoundation/averror-swift.struct/code/invalidcompositiontracksegmentsourcestarttime","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCompositionTrackSegmentSourceStartTime"}],"title":"AVError.Code.invalidCompositionTrackSegmentSourceStartTime","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/invalidCompositionTrackSegmentSourceStartTime"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentIsNotAuthorized"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}],"abstract":[{"type":"text","text":"The user isn’t authorized to play the media."}],"type":"topic","title":"AVError.Code.contentIsNotAuthorized","url":"/documentation/avfoundation/averror-swift.struct/code/contentisnotauthorized","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated":{"url":"/documentation/avfoundation/averror-swift.struct/code/contentnotupdated","title":"AVError.Code.contentNotUpdated","abstract":[{"text":"The system couldn’t update the captured content.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorContentNotUpdated","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentNotUpdated","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"createContentKeyRequestFailed"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorCreateContentKeyRequestFailed"}],"abstract":[{"type":"text","text":"The app couldn’t create a content key request."}],"type":"topic","title":"AVError.Code.createContentKeyRequestFailed","url":"/documentation/avfoundation/averror-swift.struct/code/createcontentkeyrequestfailed","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"airPlayControllerRequiresInternet"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}],"abstract":[{"type":"text","text":"The AirPlay controller requires an internet connection to function."}],"type":"topic","title":"AVError.Code.airPlayControllerRequiresInternet","url":"/documentation/avfoundation/averror-swift.struct/code/airplaycontrollerrequiresinternet","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentKeyRequestCancelled"}],"navigatorTitle":[{"kind":"identifier","text":"AVErrorContentKeyRequestCancelled"}],"abstract":[{"type":"text","text":"The app canceled a request to retrieve a content key."}],"type":"topic","title":"AVError.Code.contentKeyRequestCancelled","url":"/documentation/avfoundation/averror-swift.struct/code/contentkeyrequestcancelled","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice":{"url":"/documentation/avfoundation/averror-swift.struct/code/applicationisnotauthorizedtousedevice","title":"AVError.Code.applicationIsNotAuthorizedToUseDevice","abstract":[{"text":"The user denied this app permission to capture media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIsNotAuthorizedToUseDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code":{"url":"/documentation/avfoundation/averror-swift.struct/code","title":"AVError.Code","abstract":[{"text":"An enumeration that defines the errors that framework operations can generate.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed":{"url":"/documentation/avfoundation/averror-swift.struct/code/decodefailed","title":"AVError.Code.decodeFailed","abstract":[{"text":"The system failed to decode the media.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVErrorDecodeFailed","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFailed","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVError"}],"navigatorTitle":[{"kind":"identifier","text":"AVError"}],"abstract":[{"type":"text","text":"A structure that defines the errors that framework operations can generate."}],"type":"topic","title":"AVError","url":"/documentation/avfoundation/averror-swift.struct","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"AVErrorInvalidCompositionTrackSegmentSourceStartTime"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"AVErrorInvalidCompositionTrackSegmentSourceStartTime"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Error Codes","anchor":"Error-Codes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayControllerRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverRequiresInternet","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/airPlayReceiverTemporarilyUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/applicationIsNotAuthorizedToUseDevice","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/compositionTrackSegmentsNotContiguous","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsNotAuthorized","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsProtected","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentIsUnavailable","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentKeyRequestCancelled","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/contentNotUpdated","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/createContentKeyRequestFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decodeFailed","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderNotFound","doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code/decoderTemporarilyUnavailable"],"generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"text":"AVErrorInvalidCompositionTrackSegmentSourceStartTime","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/title","value":"AVErrorAirPlayReceiverRequiresInternet"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverRequiresInternet/fragments","value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverRequiresInternet"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/title","value":"AVErrorDecoderNotFound"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderNotFound/fragments","value":[{"kind":"identifier","text":"AVErrorDecoderNotFound"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/title","value":"AVErrorAirPlayReceiverTemporarilyUnavailable"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayReceiverTemporarilyUnavailable/fragments","value":[{"kind":"identifier","text":"AVErrorAirPlayReceiverTemporarilyUnavailable"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/title","value":"AVErrorCompositionTrackSegmentsNotContiguous"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1compositionTrackSegmentsNotContiguous/fragments","value":[{"text":"AVErrorCompositionTrackSegmentsNotContiguous","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/title","value":"AVErrorContentIsProtected"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsProtected/fragments","value":[{"kind":"identifier","text":"AVErrorContentIsProtected"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/title","op":"replace","value":"AVErrorDecoderTemporarilyUnavailable"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decoderTemporarilyUnavailable/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorDecoderTemporarilyUnavailable"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/title","op":"replace","value":"AVErrorApplicationIsNotAuthorized"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorized/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorApplicationIsNotAuthorized"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/title","op":"replace","value":"AVErrorContentIsUnavailable"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsUnavailable/fragments","op":"replace","value":[{"text":"AVErrorContentIsUnavailable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1invalidCompositionTrackSegmentSourceStartTime/title","op":"replace","value":"AVErrorInvalidCompositionTrackSegmentSourceStartTime"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1invalidCompositionTrackSegmentSourceStartTime/fragments","op":"replace","value":[{"text":"AVErrorInvalidCompositionTrackSegmentSourceStartTime","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/title","op":"replace","value":"AVErrorContentIsNotAuthorized"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentIsNotAuthorized/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorContentIsNotAuthorized"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/title","op":"replace","value":"AVErrorContentNotUpdated"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentNotUpdated/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorContentNotUpdated"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/title","op":"replace","value":"AVErrorCreateContentKeyRequestFailed"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1createContentKeyRequestFailed/fragments","op":"replace","value":[{"text":"AVErrorCreateContentKeyRequestFailed","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/title","op":"replace","value":"AVErrorAirPlayControllerRequiresInternet"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1airPlayControllerRequiresInternet/fragments","op":"replace","value":[{"kind":"identifier","text":"AVErrorAirPlayControllerRequiresInternet"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/title","op":"replace","value":"AVErrorContentKeyRequestCancelled"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1contentKeyRequestCancelled/fragments","op":"replace","value":[{"text":"AVErrorContentKeyRequestCancelled","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/title","op":"replace","value":"AVErrorApplicationIsNotAuthorizedToUseDevice"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1applicationIsNotAuthorizedToUseDevice/fragments","op":"replace","value":[{"text":"AVErrorApplicationIsNotAuthorizedToUseDevice","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title","op":"replace","value":"AVError"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments","op":"replace","value":[{"text":"AVError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVError"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/title","op":"replace","value":"AVErrorDecodeFailed"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code~1decodeFailed/fragments","op":"replace","value":[{"text":"AVErrorDecodeFailed","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}