{
  "abstract": [
    {
      "text": "A channel error that indicates an unknown error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTChannelError@PTChannelErrorUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PTChannelErrorUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PTChannelError.Code.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a channel error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for channel operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/appNotForeground": {
      "abstract": [
        {
          "text": "A channel error that indicates the operation failed because the app isn’t in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appNotForeground"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/appNotForeground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorAppNotForeground"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.appNotForeground",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/appnotforeground"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/callActive": {
      "abstract": [
        {
          "text": "A channel error that indicates there’s an active call that prevents the channel action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callActive"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/callActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorCallActive"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.callActive",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/callactive"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelLimitReached": {
      "abstract": [
        {
          "text": "A channel error that indicates you reached the maximum of one active channel at a time for the entire device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelLimitReached"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelLimitReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorChannelLimitReached"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.channelLimitReached",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/channellimitreached"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelNotFound": {
      "abstract": [
        {
          "text": "A channel error that indicates the system can’t perform the action because there’s no active channel with the UUID you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelNotFound"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorChannelNotFound"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.channelNotFound",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/channelnotfound"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/deviceManagementRestriction": {
      "abstract": [
        {
          "text": "A channel error that indicates a device-management policy or profile forbids joining the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceManagementRestriction"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/deviceManagementRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorDeviceManagementRestriction"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.deviceManagementRestriction",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/devicemanagementrestriction"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/screenTimeRestriction": {
      "abstract": [
        {
          "text": "A channel error that indicates a Screen Time restriction prevents the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenTimeRestriction"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/screenTimeRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorScreenTimeRestriction"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.screenTimeRestriction",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/screentimerestriction"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionInProgress": {
      "abstract": [
        {
          "text": "A channel error that indicates a transmission is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionInProgress"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorTransmissionInProgress"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.transmissionInProgress",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/transmissioninprogress"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotAllowed": {
      "abstract": [
        {
          "text": "A channel error that indicates the current transmission mode of the channel doesn’t allow the mode you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorTransmissionNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.transmissionNotAllowed",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/transmissionnotallowed"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotFound": {
      "abstract": [
        {
          "text": "A channel error that indicates there’s no transmission to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionNotFound"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorTransmissionNotFound"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.transmissionNotFound",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/transmissionnotfound"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "A channel error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code.unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/appNotForeground",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelNotFound",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelLimitReached",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/callActive",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionInProgress",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotFound",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/deviceManagementRestriction",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/screenTimeRestriction",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotAllowed"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTChannelErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/appNotForeground",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelNotFound",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/channelLimitReached",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/callActive",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionInProgress",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotFound",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/deviceManagementRestriction",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/screenTimeRestriction",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code/transmissionNotAllowed"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PTChannelErrorUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1channelNotFound/title",
          "value": "PTChannelErrorChannelNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1channelNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorChannelNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1deviceManagementRestriction/title",
          "value": "PTChannelErrorDeviceManagementRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1deviceManagementRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorDeviceManagementRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/title",
          "value": "PTChannelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionNotAllowed/title",
          "value": "PTChannelErrorTransmissionNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorTransmissionNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1screenTimeRestriction/title",
          "value": "PTChannelErrorScreenTimeRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1screenTimeRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorScreenTimeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionNotFound/title",
          "value": "PTChannelErrorTransmissionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorTransmissionNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1appNotForeground/title",
          "value": "PTChannelErrorAppNotForeground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1appNotForeground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorAppNotForeground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1callActive/title",
          "value": "PTChannelErrorCallActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1callActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorCallActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1channelLimitReached/title",
          "value": "PTChannelErrorChannelLimitReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1channelLimitReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorChannelLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1unknown/title",
          "value": "PTChannelErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionInProgress/title",
          "value": "PTChannelErrorTransmissionInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code~1transmissionInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelErrorTransmissionInProgress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptchannelerror-swift.struct/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/ptchannelerror-swift.struct/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
