{
  "abstract": [
    {
      "text": "The content is positioned in the bottom-right corner of the bounds rectangle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSView",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomRight"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSViewLayerContentsPlacement@NSViewLayerContentsPlacementBottomRight",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomRight"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSViewLayerContentsPlacementBottomRight"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSView.LayerContentsPlacement.bottomRight"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomRight"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify the location of the layer content when the content is not rerendered in response to view resizing. For more information, see the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottom": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the bottom-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementBottom"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.bottom",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.bottomLeft",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/bottomleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomRight": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementBottomRight"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.bottomRight",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/bottomright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/center": {
      "abstract": [
        {
          "text": "The content is horizontally and vertically centered in the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementCenter"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.center",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/center"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/left": {
      "abstract": [
        {
          "text": "The content is vertically centered at the left-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementLeft"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.left",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/right": {
      "abstract": [
        {
          "text": "The content is vertically centered at the right-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementRight"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.right",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleAxesIndependently": {
      "abstract": [
        {
          "text": "The content is resized to fit the entire bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAxesIndependently"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleAxesIndependently",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementScaleAxesIndependently"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.scaleAxesIndependently",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/scaleaxesindependently"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFill": {
      "abstract": [
        {
          "text": "The content is resized to completely fill the bounds rectangle, while still preserving the aspect of the content. The content is centered in the axis it exceeds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleProportionallyToFill"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementScaleProportionallyToFill"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.scaleProportionallyToFill",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/scaleproportionallytofill"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFit": {
      "abstract": [
        {
          "text": "The content is resized to fit the bounds rectangle, preserving the aspect of the content. If the content does not completely fill the bounds rectangle, the content is centered in the partial axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleProportionallyToFit"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementScaleProportionallyToFit"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.scaleProportionallyToFit",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/scaleproportionallytofit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/top": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the top-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementTop"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.top",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the top-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementTopLeft"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.topLeft",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/topleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topRight": {
      "abstract": [
        {
          "text": "The content is positioned in the top-right corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewLayerContentsPlacementTopRight"
        }
      ],
      "role": "symbol",
      "title": "NSView.LayerContentsPlacement.topRight",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.enum/topright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property": {
      "abstract": [
        {
          "text": "The current layer contents placement policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSViewLayerContentsPlacement",
          "text": "LayerContentsPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/layerContentsPlacement-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerContentsPlacement"
        }
      ],
      "role": "symbol",
      "title": "layerContentsPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nsview/layercontentsplacement-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleAxesIndependently",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFit",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFill",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/center",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/top",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topRight",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/right",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/left",
        "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topLeft"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSViewLayerContentsPlacementBottomRight"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleAxesIndependently",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFit",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/scaleProportionallyToFill",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/center",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/top",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topRight",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/right",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/bottomLeft",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/left",
                "doc://com.apple.appkit/documentation/AppKit/NSView/LayerContentsPlacement-swift.enum/topLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSViewLayerContentsPlacementBottomRight"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1left/title",
          "value": "NSViewLayerContentsPlacementLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/title",
          "value": "layerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1layerContentsPlacement-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottomLeft/title",
          "value": "NSViewLayerContentsPlacementBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1top/title",
          "value": "NSViewLayerContentsPlacementTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/title",
          "value": "NSViewLayerContentsPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottom/title",
          "value": "NSViewLayerContentsPlacementBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottomRight/title",
          "value": "NSViewLayerContentsPlacementBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1topRight/title",
          "value": "NSViewLayerContentsPlacementTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleProportionallyToFit/title",
          "value": "NSViewLayerContentsPlacementScaleProportionallyToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleProportionallyToFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementScaleProportionallyToFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1topLeft/title",
          "value": "NSViewLayerContentsPlacementTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1right/title",
          "value": "NSViewLayerContentsPlacementRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1center/title",
          "value": "NSViewLayerContentsPlacementCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleAxesIndependently/title",
          "value": "NSViewLayerContentsPlacementScaleAxesIndependently"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleAxesIndependently/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementScaleAxesIndependently"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleProportionallyToFill/title",
          "value": "NSViewLayerContentsPlacementScaleProportionallyToFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1LayerContentsPlacement-swift.enum~1scaleProportionallyToFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSViewLayerContentsPlacementScaleProportionallyToFill"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsview/layercontentsplacement-swift.enum/bottomright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsview/layercontentsplacement-swift.enum/bottomright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
