{
  "abstract": [
    {
      "text": "A style indicating that the toolbar appears next to the window title and with reduced margins to allow more focus on the window’s contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unifiedCompact"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowToolbarStyle@NSWindowToolbarStyleUnifiedCompact",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unifiedCompact"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowToolbarStyleUnifiedCompact"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWindow.ToolbarStyle.unifiedCompact"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unifiedCompact"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow": {
      "abstract": [
        {
          "text": "A window that an app displays on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindow"
        }
      ],
      "role": "symbol",
      "title": "NSWindow",
      "type": "topic",
      "url": "/documentation/appkit/nswindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum": {
      "abstract": [
        {
          "text": "Styles that determine the appearance and location of the toolbar in relation to the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ToolbarStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ToolbarStyle"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system determines the toolbar’s appearance and location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/expanded": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears below the window title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expanded"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/expanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarStyleExpanded"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle.expanded",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum/expanded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/preference": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears below the window title with toolbar items centered in the toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preference"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/preference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarStylePreference"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle.preference",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum/preference"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unified": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears next to the window title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unified"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarStyleUnified"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle.unified",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum/unified"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unifiedCompact": {
      "abstract": [
        {
          "text": "A style indicating that the toolbar appears next to the window title and with reduced margins to allow more focus on the window’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unifiedCompact"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unifiedCompact",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowToolbarStyleUnifiedCompact"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.ToolbarStyle.unifiedCompact",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/toolbarstyle-swift.enum/unifiedcompact"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/automatic",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/expanded",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/preference",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unified"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWindowToolbarStyleUnifiedCompact"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyleUnifiedCompact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/automatic",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/expanded",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/preference",
                "doc://com.apple.appkit/documentation/AppKit/NSWindow/ToolbarStyle-swift.enum/unified"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWindowToolbarStyleUnifiedCompact"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1automatic/title",
          "value": "NSWindowToolbarStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/title",
          "value": "NSWindowToolbarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1unified/title",
          "value": "NSWindowToolbarStyleUnified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1unified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyleUnified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title",
          "value": "NSWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1unifiedCompact/title",
          "value": "NSWindowToolbarStyleUnifiedCompact"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1unifiedCompact/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyleUnifiedCompact"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1expanded/title",
          "value": "NSWindowToolbarStyleExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1expanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStyleExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1preference/title",
          "value": "NSWindowToolbarStylePreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1ToolbarStyle-swift.enum~1preference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowToolbarStylePreference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindow/toolbarstyle-swift.enum/unifiedcompact"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswindow/toolbarstyle-swift.enum/unifiedcompact"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
