{
  "abstract": [
    {
      "text": "The color space associated with the color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpace"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColor(py)colorSpace",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "colorSpace"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSColorSpace",
        "text": "NSColorSpace"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "colorSpace"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "colorSpace"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "colorSpace"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSColorSpace",
              "text": "NSColorSpace"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access this property only for colors that have an associated color space—specifically, colors not created by name or using a pattern image. Accessing it for other color types raises an exception. If you are unsure about a color object, convert it to an equivalent ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "-based object before calling this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It is safe to access this property for color objects created with the color space names ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "—or with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class methods corresponding to these names.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace": {
      "abstract": [
        {
          "text": "Calibrated color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCalibratedBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalibratedBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscalibratedblackcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/ColorType": {
      "abstract": [
        {
          "text": "Constants that indicate the color’s type, and which methods may be called on the color object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ColorType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/ColorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ColorType"
        }
      ],
      "role": "symbol",
      "title": "NSColor.ColorType",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/colortype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpace": {
      "abstract": [
        {
          "text": "The color space associated with the color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpace"
        }
      ],
      "role": "symbol",
      "title": "colorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/colorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpaceName": {
      "abstract": [
        {
          "text": "The name of the color space associated with the color.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpaceName"
        }
      ],
      "role": "symbol",
      "title": "colorSpaceName",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/colorspacename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)": {
      "abstract": [
        {
          "text": "Returns the components of the color as an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getComponents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getComponents:"
        }
      ],
      "role": "symbol",
      "title": "getComponents(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/getcomponents(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents": {
      "abstract": [
        {
          "text": "The number of components in the color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfComponents"
        }
      ],
      "role": "symbol",
      "title": "numberOfComponents",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/numberofcomponents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/type": {
      "abstract": [
        {
          "text": "The type of the color object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorType",
          "text": "ColorType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/type"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/usingType(_:)": {
      "abstract": [
        {
          "text": "Returns a version of the color object that is compatible with the specified color type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usingType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSColorType",
          "text": "ColorType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/usingType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorUsingType:"
        }
      ],
      "role": "symbol",
      "title": "usingType(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/usingtype(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpace": {
      "abstract": [
        {
          "text": "An object that represents a custom color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpace"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName": {
      "abstract": [
        {
          "text": "Constants that specify color space names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColorSpaceName"
        }
      ],
      "role": "symbol",
      "title": "NSColorSpaceName",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB": {
      "abstract": [
        {
          "text": "Calibrated color space with red, green, blue, and alpha components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCalibratedRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "calibratedRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/calibratedrgb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite": {
      "abstract": [
        {
          "text": "Calibrated color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCalibratedWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "calibratedWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/calibratedwhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom": {
      "abstract": [
        {
          "text": "Custom ",
          "type": "text"
        },
        {
          "code": "NSColorSpace",
          "type": "codeVoice"
        },
        {
          "text": " object and floating-point components describing a color in that space",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/custom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomColorSpace"
        }
      ],
      "role": "symbol",
      "title": "custom",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/custom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK": {
      "abstract": [
        {
          "text": "Device-dependent color space with cyan, magenta, yellow, black, and alpha components",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceCMYK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceCMYK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceCMYKColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceCMYK",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicecmyk"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB": {
      "abstract": [
        {
          "text": "Device-dependent color space with red, green, blue, and alpha components.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceRGBColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceRGB",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicergb"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite": {
      "abstract": [
        {
          "text": "Device-dependent color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicewhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace": {
      "abstract": [
        {
          "text": "Device-dependent color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDeviceBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDeviceBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsdeviceblackcolorspace"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Working-with-the-Color-Space",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/type",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/usingType(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/ColorType",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpaceName",
        "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName"
      ],
      "title": "Working with the Color Space"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "colorSpace"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Working-with-the-Color-Space",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/type",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/usingType(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/ColorType",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/colorSpaceName",
                "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName"
              ],
              "title": "Working with the Color Space"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpace",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSColorSpace",
                    "text": "NSColorSpace"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "colorSpace"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceRGB/title",
          "value": "NSDeviceRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/title",
          "value": "NSDeviceWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1colorSpace/title",
          "value": "colorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1colorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedRGB/title",
          "value": "NSCalibratedRGBColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCalibratedRGBColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/title",
          "value": "NSColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1usingType(_:)/title",
          "value": "colorUsingType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1usingType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorUsingType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getComponents(_:)/title",
          "value": "getComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getComponents(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getComponents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceCMYK/title",
          "value": "NSDeviceCMYKColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceCMYK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceCMYKColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/title",
          "value": "NSCalibratedWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCalibratedWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1custom/title",
          "value": "NSCustomColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1custom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1numberOfComponents/title",
          "value": "numberOfComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1numberOfComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1colorSpaceName/title",
          "value": "colorSpaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1colorSpaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1ColorType/title",
          "value": "NSColorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1ColorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1ColorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/title",
          "value": "NSColorSpaceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColorSpaceName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolor/colorspace"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolor/colorspace"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
