{
  "abstract": [
    {
      "text": "Returns the grayscale and alpha values of the color.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColor/getWhite(_:alpha:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColor(im)getWhite:alpha:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "getWhite"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": ">?, "
      },
      {
        "kind": "externalParam",
        "text": "alpha"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": ">?)"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "getWhite:alpha:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "getWhite(_:alpha:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "getWhite"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "white"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ">?, "
            },
            {
              "kind": "externalParam",
              "text": "alpha"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ">?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Upon return, contains the grayscale value of the color object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "white"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Upon return, contains the opacity value of the color object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "alpha"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " is passed in as an argument, the method doesn’t set that value. This method works only with objects representing colors in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " color space. Sending it to other objects raises an exception.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace": {
      "abstract": [
        {
          "text": "Calibrated color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCalibratedBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCalibratedBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCalibratedBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nscalibratedblackcolorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)": {
      "abstract": [
        {
          "text": "Returns the components of the color as an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getComponents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getComponents:"
        }
      ],
      "role": "symbol",
      "title": "getComponents(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/getcomponents(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getCyan(_:magenta:yellow:black:alpha:)": {
      "abstract": [
        {
          "text": "Returns the color object’s CMYK and opacity values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getCyan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "magenta"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "yellow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "black"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getCyan(_:magenta:yellow:black:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCyan:magenta:yellow:black:alpha:"
        }
      ],
      "role": "symbol",
      "title": "getCyan(_:magenta:yellow:black:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/getcyan(_:magenta:yellow:black:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getHue(_:saturation:brightness:alpha:)": {
      "abstract": [
        {
          "text": "Returns the color object’s HSB component and opacity values in the respective arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getHue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "saturation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getHue(_:saturation:brightness:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getHue:saturation:brightness:alpha:"
        }
      ],
      "role": "symbol",
      "title": "getHue(_:saturation:brightness:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/gethue(_:saturation:brightness:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getRed(_:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Returns the color object’s RGB component and opacity values in the respective arguments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getRed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getRed(_:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getRed:green:blue:alpha:"
        }
      ],
      "role": "symbol",
      "title": "getRed(_:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/getred(_:green:blue:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/getWhite(_:alpha:)": {
      "abstract": [
        {
          "text": "Returns the grayscale and alpha values of the color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getWhite"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/getWhite(_:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getWhite:alpha:"
        }
      ],
      "role": "symbol",
      "title": "getWhite(_:alpha:)",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/getwhite(_:alpha:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents": {
      "abstract": [
        {
          "text": "The number of components in the color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfComponents"
        }
      ],
      "role": "symbol",
      "title": "numberOfComponents",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/numberofcomponents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite": {
      "abstract": [
        {
          "text": "Calibrated color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/calibratedWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCalibratedWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "calibratedWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/calibratedwhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite": {
      "abstract": [
        {
          "text": "Device-dependent color space with white and alpha components (pure white is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceWhite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColorSpaceName/deviceWhite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceWhiteColorSpace"
        }
      ],
      "role": "symbol",
      "title": "deviceWhite",
      "type": "topic",
      "url": "/documentation/appkit/nscolorspacename/devicewhite"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace": {
      "abstract": [
        {
          "text": "Device-dependent color space with black and alpha components (pure black is 1.0)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDeviceBlackColorSpace"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceBlackColorSpace",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDeviceBlackColorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsdeviceblackcolorspace"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Retrieving-Component-Values-from-Color-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/getCyan(_:magenta:yellow:black:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/getHue(_:saturation:brightness:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/getRed(_:green:blue:alpha:)",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)"
      ],
      "title": "Retrieving Component Values from Color Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "getWhite:alpha:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getWhite:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Retrieving-Component-Values-from-Color-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/getCyan(_:magenta:yellow:black:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/getHue(_:saturation:brightness:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/getRed(_:green:blue:alpha:)",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/numberOfComponents",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/getComponents(_:)"
              ],
              "title": "Retrieving Component Values from Color Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "getWhite:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "white"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "alpha:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "alpha"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Upon return, contains the grayscale value of the color object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "white"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Upon return, contains the opacity value of the color object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "alpha"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1numberOfComponents/title",
          "value": "numberOfComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1numberOfComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getCyan(_:magenta:yellow:black:alpha:)/title",
          "value": "getCyan:magenta:yellow:black:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getCyan(_:magenta:yellow:black:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCyan:magenta:yellow:black:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getHue(_:saturation:brightness:alpha:)/title",
          "value": "getHue:saturation:brightness:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getHue(_:saturation:brightness:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getHue:saturation:brightness:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getComponents(_:)/title",
          "value": "getComponents:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getComponents(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getComponents:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/title",
          "value": "NSDeviceWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1deviceWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getRed(_:green:blue:alpha:)/title",
          "value": "getRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getRed(_:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/title",
          "value": "NSCalibratedWhiteColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorSpaceName~1calibratedWhite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCalibratedWhiteColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getWhite(_:alpha:)/title",
          "value": "getWhite:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1getWhite(_:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getWhite:alpha:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolor/getwhite(_:alpha:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolor/getwhite(_:alpha:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
