{
  "abstract": [
    {
      "text": "The color to use for text in a selected control—that is, a control being clicked or dragged.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlTextColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSColor(cpy)selectedControlTextColor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selectedControlTextColor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSColor",
        "text": "NSColor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "selectedControlTextColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "selectedControlTextColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selectedControlTextColor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSColor",
              "text": "NSColor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For general information about system colors, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DrawColor/Tasks/SystemColors.html#//apple_ref/doc/uid/20000790",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/alternateSelectedControlTextColor": {
      "abstract": [
        {
          "text": "The color to use for text in a selected control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alternateSelectedControlTextColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/alternateSelectedControlTextColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alternateSelectedControlTextColor"
        }
      ],
      "role": "symbol",
      "title": "alternateSelectedControlTextColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/alternateselectedcontroltextcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/controlAccentColor": {
      "abstract": [
        {
          "text": "The user’s current accent color preference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlAccentColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/controlAccentColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlAccentColor"
        }
      ],
      "role": "symbol",
      "title": "controlAccentColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/controlaccentcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/controlBackgroundColor": {
      "abstract": [
        {
          "text": "The color to use for the background of large controls, such as scroll views or table views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/controlBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "controlBackgroundColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/controlbackgroundcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/controlColor": {
      "abstract": [
        {
          "text": "The color to use for the flat surfaces of a control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/controlColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlColor"
        }
      ],
      "role": "symbol",
      "title": "controlColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/controlcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/controlTextColor": {
      "abstract": [
        {
          "text": "The color to use for text on enabled controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlTextColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/controlTextColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlTextColor"
        }
      ],
      "role": "symbol",
      "title": "controlTextColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/controltextcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/currentControlTint": {
      "abstract": [
        {
          "text": "The current system control tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentControlTint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlTint",
          "text": "NSControlTint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/currentControlTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentControlTint"
        }
      ],
      "role": "symbol",
      "title": "currentControlTint",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/currentcontroltint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/disabledControlTextColor": {
      "abstract": [
        {
          "text": "The color to use for text on disabled controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabledControlTextColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/disabledControlTextColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disabledControlTextColor"
        }
      ],
      "role": "symbol",
      "title": "disabledControlTextColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/disabledcontroltextcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/scrubberTexturedBackground": {
      "abstract": [
        {
          "text": "The patterned color to use for the background of a scrubber control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrubberTexturedBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/scrubberTexturedBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrubberTexturedBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "scrubberTexturedBackground",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/scrubbertexturedbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlColor": {
      "abstract": [
        {
          "text": "The color to use for the face of a selected control—that is, a control that has been clicked or is being dragged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedControlColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedControlColor"
        }
      ],
      "role": "symbol",
      "title": "selectedControlColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/selectedcontrolcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlTextColor": {
      "abstract": [
        {
          "text": "The color to use for text in a selected control—that is, a control being clicked or dragged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedControlTextColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlTextColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedControlTextColor"
        }
      ],
      "role": "symbol",
      "title": "selectedControlTextColor",
      "type": "topic",
      "url": "/documentation/appkit/nscolor/selectedcontroltextcolor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DrawColor/Tasks/SystemColors.html#//apple_ref/doc/uid/20000790": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DrawColor/Tasks/SystemColors.html#//apple_ref/doc/uid/20000790",
      "title": "Accessing System Colors",
      "titleInlineContent": [
        {
          "text": "Accessing System Colors",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DrawColor/Tasks/SystemColors.html#//apple_ref/doc/uid/20000790"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Control-Colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSColor/controlAccentColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/controlColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/controlBackgroundColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/controlTextColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/disabledControlTextColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/currentControlTint",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/alternateSelectedControlTextColor",
        "doc://com.apple.appkit/documentation/AppKit/NSColor/scrubberTexturedBackground"
      ],
      "title": "Control Colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "selectedControlTextColor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedControlTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Control-Colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSColor/controlAccentColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/controlColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/controlBackgroundColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/controlTextColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/disabledControlTextColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/currentControlTint",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/selectedControlColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/alternateSelectedControlTextColor",
                "doc://com.apple.appkit/documentation/AppKit/NSColor/scrubberTexturedBackground"
              ],
              "title": "Control Colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSColor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSColor",
                    "text": "NSColor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "selectedControlTextColor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlBackgroundColor/title",
          "value": "controlBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1currentControlTint/title",
          "value": "currentControlTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1currentControlTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentControlTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1selectedControlTextColor/title",
          "value": "selectedControlTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1selectedControlTextColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedControlTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/title",
          "value": "NSColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1selectedControlColor/title",
          "value": "selectedControlColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1selectedControlColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedControlColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlTextColor/title",
          "value": "controlTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlTextColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1scrubberTexturedBackground/title",
          "value": "scrubberTexturedBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1scrubberTexturedBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrubberTexturedBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlAccentColor/title",
          "value": "controlAccentColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlAccentColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlAccentColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1disabledControlTextColor/title",
          "value": "disabledControlTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1disabledControlTextColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "disabledControlTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlColor/title",
          "value": "controlColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1controlColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1alternateSelectedControlTextColor/title",
          "value": "alternateSelectedControlTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColor~1alternateSelectedControlTextColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alternateSelectedControlTextColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscolor/selectedcontroltextcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscolor/selectedcontroltextcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
