{
  "abstract": [
    {
      "text": "These constants specify the different parts of the scroller:",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSScrollerPart",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Part"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Part"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSScroller.Part"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Part"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue": {
      "abstract": [
        {
          "text": "The value of the receiver’s cell as a single-precision floating-point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "floatValue"
        }
      ],
      "role": "symbol",
      "title": "floatValue",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/floatvalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller": {
      "abstract": [
        {
          "text": "An object that controls scrolling of a document view within a scroll view or other type of container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScroller"
        }
      ],
      "role": "symbol",
      "title": "NSScroller",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Arrow": {
      "abstract": [
        {
          "text": "These constants describe the two scroller buttons and are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/drawArrow(_:highlight:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Arrow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Arrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Arrow"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Arrow",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition": {
      "abstract": [
        {
          "text": "These constants specify where the scroller’s buttons appear and are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ArrowPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ArrowPosition"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.ArrowPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/KnobStyle-swift.enum": {
      "abstract": [
        {
          "text": "Specify different knob styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KnobStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/KnobStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KnobStyle"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.KnobStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/knobstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part": {
      "abstract": [
        {
          "text": "These constants specify the different parts of the scroller:",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Part"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Part"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine": {
      "abstract": [
        {
          "text": "Up or left by a small amount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerDecrementLine"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.decrementLine",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/decrementline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage": {
      "abstract": [
        {
          "text": "Up or left by a large amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decrementPage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerDecrementPage"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.decrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/decrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine": {
      "abstract": [
        {
          "text": "Down or right by a small amount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementLine"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerIncrementLine"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.incrementLine",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/incrementline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage": {
      "abstract": [
        {
          "text": "Down or right by a large amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incrementPage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerIncrementPage"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.incrementPage",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/incrementpage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob": {
      "abstract": [
        {
          "text": "Directly to the scroller’s value, as given by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knob"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerKnob"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.knob",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/knob"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot": {
      "abstract": [
        {
          "text": "Directly to the scroller’s value, as given by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/floatValue",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "knobSlot"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerKnobSlot"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.knobSlot",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/knobslot"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart": {
      "abstract": [
        {
          "text": "Don’t scroll at all.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noPart"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScrollerNoPart"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Part.noPart",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/part/nopart"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/Style": {
      "abstract": [
        {
          "text": "Constants to specify the scroller style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/Style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.Style",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/style"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum": {
      "abstract": [
        {
          "text": "These constants specify which parts of the scroller are visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UsableParts"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UsableParts"
        }
      ],
      "role": "symbol",
      "title": "NSScroller.UsableParts",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/usableparts-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition": {
      "abstract": [
        {
          "text": "The location of the scroll buttons within the scroller, as described in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowsPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScroller",
          "text": "NSScroller"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSScrollArrowPosition",
          "text": "ArrowPosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/arrowsPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrowsPosition"
        }
      ],
      "role": "symbol",
      "title": "arrowsPosition",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/arrowsposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScroller/drawArrow(_:highlight:)": {
      "abstract": [
        {
          "text": "Draws the scroll button indicated by ",
          "type": "text"
        },
        {
          "code": "arrow",
          "type": "codeVoice"
        },
        {
          "text": ", which is either ",
          "type": "text"
        },
        {
          "code": "NSScrollerIncrementArrow",
          "type": "codeVoice"
        },
        {
          "text": " (the down or right scroll button) or ",
          "type": "text"
        },
        {
          "code": "NSScrollerDecrementArrow",
          "type": "codeVoice"
        },
        {
          "text": " (up or left).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawArrow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSScroller",
          "text": "NSScroller"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSScrollerArrow",
          "text": "Arrow"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScroller/drawArrow(_:highlight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawArrow:highlight:"
        }
      ],
      "role": "symbol",
      "title": "drawArrow(_:highlight:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscroller/drawarrow(_:highlight:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Style",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/KnobStyle-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Arrow",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage",
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSScrollerPart"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knob",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/knobSlot",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementLine",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/decrementPage",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementLine",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/incrementPage",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Part/noPart"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Style",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/KnobStyle-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/Arrow",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/ArrowPosition",
                "doc://com.apple.appkit/documentation/AppKit/NSScroller/UsableParts-swift.enum"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSScrollerPart"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/title",
          "value": "NSScroller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScroller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/title",
          "value": "NSScrollArrowPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollArrowPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1ArrowPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollArrowPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1drawArrow(_:highlight:)/title",
          "value": "drawArrow:highlight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1drawArrow(_:highlight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawArrow:highlight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementLine/title",
          "value": "NSScrollerDecrementLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerDecrementLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Style/title",
          "value": "NSScrollerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Style/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementLine/title",
          "value": "NSScrollerIncrementLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerIncrementLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/title",
          "value": "NSScrollerPart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knobSlot/title",
          "value": "NSScrollerKnobSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knobSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnobSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/title",
          "value": "NSUsableScrollerParts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUsableScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1UsableParts-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUsableScrollerParts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1floatValue/title",
          "value": "floatValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1floatValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "floatValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1noPart/title",
          "value": "NSScrollerNoPart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1noPart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerNoPart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1arrowsPosition/title",
          "value": "arrowsPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1arrowsPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrowsPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knob/title",
          "value": "NSScrollerKnob"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1knob/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnob"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementPage/title",
          "value": "NSScrollerIncrementPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1incrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerIncrementPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementPage/title",
          "value": "NSScrollerDecrementPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Part~1decrementPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerDecrementPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1KnobStyle-swift.enum/title",
          "value": "NSScrollerKnobStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1KnobStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnobStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1KnobStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerKnobStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Arrow/title",
          "value": "NSScrollerArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Arrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScroller~1Arrow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScrollerArrow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscroller/part"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscroller/part"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
