{
  "abstract": [
    {
      "text": "An object that defines the period for the product discount.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Product.SubscriptionOffer.period",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SKProductDiscount(py)subscriptionPeriod",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subscriptionPeriod"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
        "text": "SKProductSubscriptionPeriod"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "subscriptionPeriod"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.13.2",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use Product.SubscriptionOffer.period",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "subscriptionPeriod"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subscriptionPeriod"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
              "text": "SKProductSubscriptionPeriod"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This object represents the duration of a single subscription period. A period is described as a number of units, where a unit can be a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To calculate the total amount of time that the discount price is available to the user, multiply the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The subscription period for the discount is independent of the product’s regular subscription period, and does not have to match in units or duration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day": {
      "abstract": [
        {
          "text": "An interval lasting one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitDay"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.day",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/day"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month": {
      "abstract": [
        {
          "text": "An interval lasting one month.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "month"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitMonth"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.month",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/month"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week": {
      "abstract": [
        {
          "text": "An interval lasting one week.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "week"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitWeek"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.week",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/week"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year": {
      "abstract": [
        {
          "text": "An interval lasting one year.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "year"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitYear"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.year",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/year"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount": {
      "abstract": [
        {
          "text": "The details of an introductory offer or a promotional offer for an auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductDiscount"
        }
      ],
      "role": "symbol",
      "title": "SKProductDiscount",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods": {
      "abstract": [
        {
          "text": "An integer that indicates the number of periods the product discount is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfPeriods"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfPeriods"
        }
      ],
      "role": "symbol",
      "title": "numberOfPeriods",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/numberofperiods"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod": {
      "abstract": [
        {
          "text": "An object that defines the period for the product discount.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/subscriptionPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionPeriod"
        }
      ],
      "role": "symbol",
      "title": "subscriptionPeriod",
      "type": "topic",
      "url": "/documentation/storekit/skproductdiscount/subscriptionperiod"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod": {
      "abstract": [
        {
          "text": "An object containing the subscription period duration information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductSubscriptionPeriod"
        }
      ],
      "role": "symbol",
      "title": "SKProductSubscriptionPeriod",
      "type": "topic",
      "url": "/documentation/storekit/skproductsubscriptionperiod"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Discount-Duration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods"
      ],
      "title": "Getting the Discount Duration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "subscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Discount-Duration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProductDiscount/numberOfPeriods"
              ],
              "title": "Getting the Discount Duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProductSubscriptionPeriod",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SKProductSubscriptionPeriod",
                    "text": "SKProductSubscriptionPeriod"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "subscriptionPeriod"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Product.SubscriptionOffer.period",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1subscriptionPeriod/title",
          "value": "subscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1subscriptionPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1day/title",
          "value": "SKProductPeriodUnitDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/title",
          "value": "SKProductDiscount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductDiscount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1month/title",
          "value": "SKProductPeriodUnitMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1month/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/title",
          "value": "SKProductSubscriptionPeriod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductSubscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductSubscriptionPeriod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductSubscriptionPeriod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1week/title",
          "value": "SKProductPeriodUnitWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1week/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1year/title",
          "value": "SKProductPeriodUnitYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1numberOfPeriods/title",
          "value": "numberOfPeriods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProductDiscount~1numberOfPeriods/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfPeriods"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skproductdiscount/subscriptionperiod"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skproductdiscount/subscriptionperiod"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
