{
  "abstract": [
    {
      "text": "The device’s axes as key-value pairs for lookup by name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-5u1xr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "GameController",
    "externalID": "s:So26GCDevicePhysicalInputStateP14GameControllerE4axesAC010GCPhysicalC17ElementCollectionVySo06GCAxisI0_pGvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "axes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
        "text": "GCPhysicalInputElementCollection"
      },
      {
        "kind": "text",
        "text": "<any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)GCAxisElement",
        "text": "GCAxisElement"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "axes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "axes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
              "text": "GCPhysicalInputElementCollection"
            },
            {
              "kind": "text",
              "text": "<any "
            },
            {
              "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)GCAxisElement",
              "text": "GCAxisElement"
            },
            {
              "kind": "text",
              "text": "> { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement": {
      "abstract": [
        {
          "text": "The common properties for an element that represents an absolute or relative input value along an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCAxisElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCAxisElement"
        }
      ],
      "role": "symbol",
      "title": "GCAxisElement",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcaxiselement"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState": {
      "abstract": [
        {
          "text": "The common properties for physical devices with elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputState"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputState"
        }
      ],
      "role": "symbol",
      "title": "GCDevicePhysicalInputState",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-5u1xr": {
      "abstract": [
        {
          "text": "The device’s axes as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
          "text": "GCPhysicalInputElementCollection"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCAxisElement",
          "text": "GCAxisElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-5u1xr",
      "kind": "symbol",
      "role": "symbol",
      "title": "axes",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/axes-5u1xr"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-2ovae": {
      "abstract": [
        {
          "text": "The device’s buttons as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
          "text": "GCPhysicalInputElementCollection"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCButtonElement",
          "text": "GCButtonElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-2ovae",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttons",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/buttons-2ovae"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-7b4o3": {
      "abstract": [
        {
          "text": "The device’s directional pads as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dpads"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
          "text": "GCPhysicalInputElementCollection"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCDirectionPadElement",
          "text": "GCDirectionPadElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-7b4o3",
      "kind": "symbol",
      "role": "symbol",
      "title": "dpads",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/dpads-7b4o3"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-46hgy": {
      "abstract": [
        {
          "text": "The device’s elements as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
          "text": "GCPhysicalInputElementCollection"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-46hgy",
      "kind": "symbol",
      "role": "symbol",
      "title": "elements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/elements-46hgy"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the element that the key specifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/subscript(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6dcny": {
      "abstract": [
        {
          "text": "The device’s switches as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14GameController32GCPhysicalInputElementCollectionV",
          "text": "GCPhysicalInputElementCollection"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCSwitchElement",
          "text": "GCSwitchElement"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6dcny",
      "kind": "symbol",
      "role": "symbol",
      "title": "switches",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/switches-6dcny"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct": {
      "abstract": [
        {
          "text": "A collection of physical input elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCPhysicalInputElementCollection-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCPhysicalInputElementCollection"
        }
      ],
      "role": "symbol",
      "title": "GCPhysicalInputElementCollection",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcphysicalinputelementcollection-swift.struct"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-46hgy",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-2ovae",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-7b4o3",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6dcny",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)"
      ],
      "title": "Accessing elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/title",
          "value": "GCDevicePhysicalInputState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/title",
          "value": "GCAxisElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCAxisElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCAxisElement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdevicephysicalinputstate/axes-5u1xr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
