{"abstract":[{"text":"The device’s axes as key-value pairs for lookup by name.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gamecontroller/gcdevicephysicalinputstate/axes-80rx"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)GCPhysicalInputElementCollection","text":"GCPhysicalInputElementCollection<NSString<GCAxisElementName> *,id<GCAxisElement>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"axes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gamecontroller/documentation/GameController","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState"]]},"identifier":{"url":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"Game Controller"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"16.0","beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"16.0","beta":false},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"16.0","beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"13.0","beta":false},{"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"16.0","beta":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"externalID":"c:objc(pl)GCDevicePhysicalInputState(py)axes","navigatorTitle":[{"text":"axes","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"axes","kind":"identifier"}],"title":"axes"},"seeAlsoSections":[{"anchor":"Accessing-elements","identifiers":["doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)"],"title":"Accessing elements","generated":true}],"references":{"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g":{"kind":"symbol","role":"symbol","title":"buttons","abstract":[{"text":"The device’s buttons as key-value pairs for lookup by name.","type":"text"}],"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g","fragments":[{"text":"buttons","kind":"identifier"}],"type":"topic","url":"/documentation/gamecontroller/gcdevicephysicalinputstate/buttons-3257g"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x":{"fragments":[{"text":"dpads","kind":"identifier"}],"url":"/documentation/gamecontroller/gcdevicephysicalinputstate/dpads-5yr9x","identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x","kind":"symbol","type":"topic","abstract":[{"text":"The device’s directional pads as key-value pairs for lookup by name.","type":"text"}],"role":"symbol","title":"dpads"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2":{"kind":"symbol","role":"symbol","title":"switches","abstract":[{"text":"The device’s switches as key-value pairs for lookup by name.","type":"text"}],"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2","fragments":[{"text":"switches","kind":"identifier"}],"type":"topic","url":"/documentation/gamecontroller/gcdevicephysicalinputstate/switches-6bws2"},"doc://com.apple.gamecontroller/documentation/GameController":{"url":"/documentation/gamecontroller","title":"Game Controller","type":"topic","role":"collection","identifier":"doc://com.apple.gamecontroller/documentation/GameController","abstract":[{"type":"text","text":"Support hardware game controllers in your game."}],"kind":"symbol"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)":{"required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"objectForKeyedSubscript:"}],"role":"symbol","title":"subscript(_:)","abstract":[{"text":"Returns the element that the key specifies.","type":"text"}],"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)","fragments":[{"text":"subscript","kind":"keyword"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> (any "},{"preciseIdentifier":"c:objc(pl)GCPhysicalInputElement","kind":"typeIdentifier","text":"GCPhysicalInputElement"},{"kind":"text","text":")?"}],"type":"topic","url":"/documentation/gamecontroller/gcdevicephysicalinputstate/subscript(_:)"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState":{"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState","abstract":[{"type":"text","text":"The common properties for physical devices with elements."}],"url":"/documentation/gamecontroller/gcdevicephysicalinputstate","type":"topic","title":"GCDevicePhysicalInputState","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GCDevicePhysicalInputState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GCDevicePhysicalInputState","kind":"identifier"}]},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2":{"kind":"symbol","role":"symbol","title":"elements","abstract":[{"text":"The device’s elements as key-value pairs for lookup by name.","type":"text"}],"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2","fragments":[{"text":"elements","kind":"identifier"}],"type":"topic","url":"/documentation/gamecontroller/gcdevicephysicalinputstate/elements-1shp2"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx":{"kind":"symbol","role":"symbol","title":"axes","abstract":[{"text":"The device’s axes as key-value pairs for lookup by name.","type":"text"}],"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx","fragments":[{"text":"axes","kind":"identifier"}],"type":"topic","url":"/documentation/gamecontroller/gcdevicephysicalinputstate/axes-80rx"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/title","op":"replace","value":"objectForKeyedSubscript:"},{"path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"objectForKeyedSubscript:"}]},{"path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/title","op":"replace","value":"GCDevicePhysicalInputState"},{"path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/fragments","op":"replace","value":[{"kind":"identifier","text":"GCDevicePhysicalInputState"}]},{"path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/navigatorTitle","op":"replace","value":[{"text":"GCDevicePhysicalInputState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}