{"abstract":[{"type":"text","text":"The physical device that this profile represents."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gamecontroller/documentation/GameController","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/gamecontroller/gcdevicephysicalinputstate/device"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/gamecontroller/gcdevicephysicalinputstate/device"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GCDevice","identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevice","text":"GCDevice"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/device"},"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"16.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"16.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"16.0","name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"macOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"16.0","name":"tvOS","beta":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}],"externalID":"c:objc(pl)GCDevicePhysicalInputState(py)device","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"device"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)GCDevice","text":"GCDevice"},{"kind":"text","text":")?"}],"roleHeading":"Instance Property","modules":[{"name":"Game Controller"}],"required":true,"title":"device","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"device"}]},"references":{"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/device":{"type":"topic","title":"device","abstract":[{"text":"The physical device that this profile represents.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"device","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)GCDevice","text":"GCDevice","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"/documentation/gamecontroller/gcdevicephysicalinputstate/device","required":true,"role":"symbol","navigatorTitle":[{"text":"device","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/device"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevice":{"abstract":[{"type":"text","text":"A protocol that defines a common interface for game input devices."}],"kind":"symbol","identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevice","type":"topic","url":"/documentation/gamecontroller/gcdevice","navigatorTitle":[{"text":"GCDevice","kind":"identifier"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GCDevice","kind":"identifier"}],"title":"GCDevice"},"doc://com.apple.gamecontroller/documentation/GameController":{"url":"/documentation/gamecontroller","title":"Game Controller","type":"topic","role":"collection","identifier":"doc://com.apple.gamecontroller/documentation/GameController","abstract":[{"type":"text","text":"Support hardware game controllers in your game."}],"kind":"symbol"},"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState":{"identifier":"doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState","abstract":[{"type":"text","text":"The common properties for physical devices with elements."}],"url":"/documentation/gamecontroller/gcdevicephysicalinputstate","type":"topic","title":"GCDevicePhysicalInputState","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GCDevicePhysicalInputState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GCDevicePhysicalInputState","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","role":"overview","title":"Technologies"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"16.0"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"device","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"device"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.gamecontroller/documentation/GameController","doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)GCDevice","text":"id<GCDevice>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"device","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"device","op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1device/title"},{"value":[{"kind":"identifier","text":"device"}],"op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1device/fragments"},{"value":"GCDevice","op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/title"},{"value":[{"text":"GCDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/fragments"},{"value":[{"text":"GCDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevice/navigatorTitle"},{"value":"GCDevicePhysicalInputState","op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/title"},{"value":[{"text":"GCDevicePhysicalInputState","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/fragments"},{"value":[{"text":"GCDevicePhysicalInputState","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}