{
  "abstract": [
    {
      "text": "The device’s elements as key-value pairs for lookup by name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamecontroller/documentation/GameController",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)GCDevicePhysicalInputState(py)elements",
    "fragments": [
      {
        "kind": "identifier",
        "text": "elements"
      }
    ],
    "modules": [
      {
        "name": "Game Controller"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "elements"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "elements"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)GCPhysicalInputElementCollection",
              "text": "GCPhysicalInputElementCollection<NSString<GCPhysicalInputElementName> *,id<GCPhysicalInputElement>>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "elements"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamecontroller/documentation/GameController": {
      "abstract": [
        {
          "text": "Support hardware game controllers in your game.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController",
      "kind": "symbol",
      "role": "collection",
      "title": "Game Controller",
      "type": "topic",
      "url": "/documentation/gamecontroller"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState": {
      "abstract": [
        {
          "text": "The common properties for physical devices with elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputState"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GCDevicePhysicalInputState"
        }
      ],
      "role": "symbol",
      "title": "GCDevicePhysicalInputState",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx": {
      "abstract": [
        {
          "text": "The device’s axes as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "axes"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx",
      "kind": "symbol",
      "role": "symbol",
      "title": "axes",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/axes-80rx"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g": {
      "abstract": [
        {
          "text": "The device’s buttons as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "buttons"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttons",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/buttons-3257g"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x": {
      "abstract": [
        {
          "text": "The device’s directional pads as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "dpads"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x",
      "kind": "symbol",
      "role": "symbol",
      "title": "dpads",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/dpads-5yr9x"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2": {
      "abstract": [
        {
          "text": "The device’s elements as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "elements"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/elements-1shp2",
      "kind": "symbol",
      "role": "symbol",
      "title": "elements",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/elements-1shp2"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the element that the key specifies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)GCPhysicalInputElement",
          "text": "GCPhysicalInputElement"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/subscript(_:)"
    },
    "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2": {
      "abstract": [
        {
          "text": "The device’s switches as key-value pairs for lookup by name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "switches"
        }
      ],
      "identifier": "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2",
      "kind": "symbol",
      "role": "symbol",
      "title": "switches",
      "type": "topic",
      "url": "/documentation/gamecontroller/gcdevicephysicalinputstate/switches-6bws2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/axes-80rx",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/buttons-3257g",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/dpads-5yr9x",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/switches-6bws2",
        "doc://com.apple.gamecontroller/documentation/GameController/GCDevicePhysicalInputState/subscript(_:)"
      ],
      "title": "Accessing elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/title",
          "value": "GCDevicePhysicalInputState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GCDevicePhysicalInputState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamecontroller~1documentation~1GameController~1GCDevicePhysicalInputState~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamecontroller/gcdevicephysicalinputstate/elements-1shp2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
