{"abstract":[{"text":"Tells the delegate that a document has been successfully imported.","type":"text"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(pl)UIDocumentBrowserViewControllerDelegate(im)documentBrowser:didImportDocumentAtURL:toDestinationURL:","navigatorTitle":[{"text":"documentBrowser:didImportDocumentAtURL:toDestinationURL:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentBrowser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentBrowserViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"text":", ","kind":"text"},{"text":"didImportDocumentAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"toDestinationURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"modules":[{"name":"UIKit"}],"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"11.0","beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","beta":false}],"role":"symbol","title":"documentBrowser(_:didImportDocumentAt:toDestinationURL:)"},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController/ImportMode","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:failedToImportDocumentAt:error:)"],"anchor":"Creating-new-documents","title":"Creating new documents"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentBrowser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIDocumentBrowserViewController","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"text":", ","kind":"text"},{"text":"didImportDocumentAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sourceURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"toDestinationURL","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"destinationURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The document browser that performed the import action.","type":"text"}],"type":"paragraph"}]},{"name":"sourceURL","content":[{"type":"paragraph","inlineContent":[{"text":"The document’s original URL.","type":"text"}]}]},{"name":"destinationURL","content":[{"inlineContent":[{"type":"text","text":"The document’s URL after the import."}],"type":"paragraph"}]}]},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing"]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"To open the document as soon as it’s imported:","type":"text"}]},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Open a new ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocument","type":"reference","isActive":true},{"text":" subclass for the document (or use a file presenter and file coordination to access the document).","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Create a view controller to display the document."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Present that view controller modally."}],"type":"paragraph"}]}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didImportDocumentAt:toDestinationURL:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:didimportdocumentat:todestinationurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:didimportdocumentat:todestinationurl:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"documentBrowser:didRequestDocumentCreationWithHandler:","kind":"identifier"}],"url":"/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:didrequestdocumentcreationwithhandler:)","type":"topic","title":"documentBrowser(_:didRequestDocumentCreationWithHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentBrowser","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController","text":"UIDocumentBrowserViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRequestDocumentCreationWithHandler"},{"text":": (","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"UIDocumentBrowserViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ImportMode","preciseIdentifier":"c:@E@UIDocumentBrowserImportMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)","abstract":[{"type":"text","text":"Asks the delegate to create a new document."}]},"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController/ImportMode":{"navigatorTitle":[{"text":"ImportMode","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The document browser’s import modes."}],"kind":"symbol","type":"topic","title":"UIDocumentBrowserViewController.ImportMode","url":"/documentation/uikit/uidocumentbrowserviewcontroller/importmode","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController/ImportMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImportMode","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:10Foundation3URLV":{"title":"URL","type":"topic","fragments":[{"text":"struct ","kind":"text"},{"text":"URL","kind":"identifier"}],"abstract":[{"text":"A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation3URLV","url":"/documentation/foundation/url","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSURL":{"title":"NSURL","url":"/documentation/foundation/nsurl","abstract":[{"text":"An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSURL","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didImportDocumentAt:toDestinationURL:)":{"url":"/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:didimportdocumentat:todestinationurl:)","abstract":[{"text":"Tells the delegate that a document has been successfully imported.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentBrowser"},{"text":"(","kind":"text"},{"text":"UIDocumentBrowserViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"text":", ","kind":"text"},{"text":"didImportDocumentAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toDestinationURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"documentBrowser:didImportDocumentAtURL:toDestinationURL:"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didImportDocumentAt:toDestinationURL:)","type":"topic","title":"documentBrowser(_:didImportDocumentAt:toDestinationURL:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:failedToImportDocumentAt:error:)":{"type":"topic","kind":"symbol","title":"documentBrowser(_:failedToImportDocumentAt:error:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:failedToImportDocumentAt:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentBrowser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIDocumentBrowserViewController","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failedToImportDocumentAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"documentBrowser:failedToImportDocumentAtURL:error:"}],"role":"symbol","abstract":[{"text":"Tells the delegate that the document browser failed to import the specified document.","type":"text"}],"url":"/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:failedtoimportdocumentat:error:)"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController":{"navigatorTitle":[{"text":"UIDocumentBrowserViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentBrowserViewController","kind":"identifier"}],"url":"/documentation/uikit/uidocumentbrowserviewcontroller","abstract":[{"text":"A view controller for browsing and performing actions on documents that you store locally and in the cloud.","type":"text"}],"title":"UIDocumentBrowserViewController","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDocumentBrowserViewControllerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate","title":"UIDocumentBrowserViewControllerDelegate","url":"/documentation/uikit/uidocumentbrowserviewcontrollerdelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UIDocumentBrowserViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"The protocol you implement to respond as the user interacts with the document browser.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing":{"kind":"article","abstract":[{"type":"text","text":"Give users the ability to import and export documents from your app."}],"url":"/documentation/uikit/enabling-document-sharing","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing","title":"Enabling document sharing","role":"article"},"doc://com.apple.uikit/documentation/UIKit/UIDocument":{"navigatorTitle":[{"kind":"identifier","text":"UIDocument"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocument","abstract":[{"type":"text","text":"An abstract base class for managing discrete portions of your app’s data."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIDocument"}],"url":"/documentation/uikit/uidocument","title":"UIDocument","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"11.0","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"documentBrowser:didImportDocumentAtURL:toDestinationURL:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentBrowser:didImportDocumentAtURL:toDestinationURL:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController/ImportMode","doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:failedToImportDocumentAt:error:)"],"title":"Creating new documents","generated":true,"anchor":"Creating-new-documents"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentBrowser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController","text":"UIDocumentBrowserViewController","preciseIdentifier":"c:objc(cs)UIDocumentBrowserViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didImportDocumentAtURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"sourceURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"toDestinationURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSURL","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"destinationURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The document browser that performed the import action.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The document’s original URL.","type":"text"}]}],"name":"sourceURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The document’s URL after the import.","type":"text"}]}],"name":"destinationURL"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didRequestDocumentCreationWithHandler:)/title","op":"replace","value":"documentBrowser:didRequestDocumentCreationWithHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didRequestDocumentCreationWithHandler:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentBrowser:didRequestDocumentCreationWithHandler:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController~1ImportMode/title","op":"replace","value":"UIDocumentBrowserImportMode"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController~1ImportMode/fragments","op":"replace","value":[{"text":"UIDocumentBrowserImportMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController~1ImportMode/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIDocumentBrowserImportMode"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract","op":"replace","value":[{"type":"text","text":"An object that represents the location of a resource, such as an item on a remote server or the path to a local file. "}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didImportDocumentAt:toDestinationURL:)/title","op":"replace","value":"documentBrowser:didImportDocumentAtURL:toDestinationURL:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didImportDocumentAt:toDestinationURL:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentBrowser:didImportDocumentAtURL:toDestinationURL:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:failedToImportDocumentAt:error:)/title","op":"replace","value":"documentBrowser:failedToImportDocumentAtURL:error:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:failedToImportDocumentAt:error:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentBrowser:failedToImportDocumentAtURL:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/title","op":"replace","value":"UIDocumentBrowserViewController"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/fragments","op":"replace","value":[{"text":"UIDocumentBrowserViewController","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/navigatorTitle","op":"replace","value":[{"text":"UIDocumentBrowserViewController","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/title","op":"replace","value":"UIDocumentBrowserViewControllerDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/fragments","op":"replace","value":[{"text":"UIDocumentBrowserViewControllerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/navigatorTitle","op":"replace","value":[{"text":"UIDocumentBrowserViewControllerDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title","op":"replace","value":"UIDocument"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments","op":"replace","value":[{"text":"UIDocument","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIDocument"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}