{
  "abstract": [
    {
      "text": "The effect to apply to the view with this style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/effect-12r83"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIHoverStyle(py)effect",
    "fragments": [
      {
        "kind": "identifier",
        "text": "effect"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "effect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "effect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)UIHoverEffect",
              "text": "id<UIHoverEffect>"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "effect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to apply a system-default effect to the view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-c.class": {
      "abstract": [
        {
          "text": "A system-default hover effect that automatically selects the appropriate effect based on the view to which it applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIHoverAutomaticEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIHoverAutomaticEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihoverautomaticeffect-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-swift.struct": {
      "abstract": [
        {
          "text": "A system-default hover effect that automatically selects the appropriate effect based on the view to which it applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverAutomaticEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverAutomaticEffect"
        }
      ],
      "role": "symbol",
      "title": "UIHoverAutomaticEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihoverautomaticeffect-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-ukid": {
      "abstract": [
        {
          "text": "A hover effect that can apply to a view through a hover style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIHoverEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-ukid",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIHoverEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihovereffect-ukid"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverHighlightEffect-c.class": {
      "abstract": [
        {
          "text": "An effect that applies a highlight to the view on hover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIHoverHighlightEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverHighlightEffect-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIHoverHighlightEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihoverhighlighteffect-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverLiftEffect-c.class": {
      "abstract": [
        {
          "text": "An effect that can visually lift the view on hover where appropriate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIHoverLiftEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverLiftEffect-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIHoverLiftEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihoverlifteffect-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle": {
      "abstract": [
        {
          "text": "The hover style to apply to a view, including an effect and a shape to use for displaying that effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverStyle"
        }
      ],
      "role": "symbol",
      "title": "UIHoverStyle",
      "type": "topic",
      "url": "/documentation/uikit/uihoverstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/effect-12r83": {
      "abstract": [
        {
          "text": "The effect to apply to the view with this style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "effect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/effect-12r83",
      "kind": "symbol",
      "role": "symbol",
      "title": "effect",
      "type": "topic",
      "url": "/documentation/uikit/uihoverstyle/effect-12r83"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-hover-effect",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIHoverAutomaticEffect-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverHighlightEffect-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverLiftEffect-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-ukid"
      ],
      "title": "Specifying a hover effect"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/title",
          "value": "UIHoverStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uihoverstyle/effect-12r83"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
