{
  "abstract": [
    {
      "text": "Open Directory node types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Node Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497623-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497721-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579651-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579652-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeAuthentication": {
      "abstract": [
        {
          "text": "A node used for authentication or record lookups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODNodeTypeAuthentication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODNodeTypeAuthentication"
        }
      ],
      "role": "symbol",
      "title": "kODNodeTypeAuthentication",
      "type": "topic",
      "url": "/documentation/opendirectory/kodnodetypeauthentication"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeConfigure": {
      "abstract": [
        {
          "text": "A node that specifically refers to the Directory Services configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODNodeTypeConfigure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeConfigure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODNodeTypeConfigure"
        }
      ],
      "role": "symbol",
      "title": "kODNodeTypeConfigure",
      "type": "topic",
      "url": "/documentation/opendirectory/kodnodetypeconfigure"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeContacts": {
      "abstract": [
        {
          "text": "A node used for applications that handle contact data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODNodeTypeContacts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeContacts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODNodeTypeContacts"
        }
      ],
      "role": "symbol",
      "title": "kODNodeTypeContacts",
      "type": "topic",
      "url": "/documentation/opendirectory/kodnodetypecontacts"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeLocalNodes": {
      "abstract": [
        {
          "text": "A node that specifically looks at the local directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODNodeTypeLocalNodes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeLocalNodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODNodeTypeLocalNodes"
        }
      ],
      "role": "symbol",
      "title": "kODNodeTypeLocalNodes",
      "type": "topic",
      "url": "/documentation/opendirectory/kodnodetypelocalnodes"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeNetwork": {
      "abstract": [
        {
          "text": "A node used for looking up network resource type data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODNodeTypeNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODNodeTypeNetwork"
        }
      ],
      "role": "symbol",
      "title": "kODNodeTypeNetwork",
      "type": "topic",
      "url": "/documentation/opendirectory/kodnodetypenetwork"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Enumerations",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-enumerations"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions": {
      "abstract": [
        {
          "text": "This document describes the functions, constants, and data types used to interact with Open Directory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Functions",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeAuthentication",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeContacts",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeNetwork",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeLocalNodes",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeConfigure"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeAuthentication",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeContacts",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeNetwork",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeLocalNodes",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODNodeTypeConfigure"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeContacts/title",
          "value": "kODNodeTypeContacts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeContacts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODNodeTypeContacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeNetwork/title",
          "value": "kODNodeTypeNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODNodeTypeNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeConfigure/title",
          "value": "kODNodeTypeConfigure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeConfigure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODNodeTypeConfigure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeAuthentication/title",
          "value": "kODNodeTypeAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODNodeTypeAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeLocalNodes/title",
          "value": "kODNodeTypeLocalNodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODNodeTypeLocalNodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODNodeTypeLocalNodes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/1497602-node-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/1497602-node-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
