{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types": {
      "abstract": [
        {
          "text": "Open Directory node types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Node Types",
      "type": "topic",
      "url": "/documentation/opendirectory/1497602-node-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497721-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579651-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579652-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchAny"
        }
      ],
      "role": "symbol",
      "title": "kODMatchAny",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchany"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchBeginsWith": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchBeginsWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchBeginsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchBeginsWith"
        }
      ],
      "role": "symbol",
      "title": "kODMatchBeginsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchbeginswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchContains": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchContains"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchContains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchContains"
        }
      ],
      "role": "symbol",
      "title": "kODMatchContains",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchcontains"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEndsWith": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchEndsWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEndsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchEndsWith"
        }
      ],
      "role": "symbol",
      "title": "kODMatchEndsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchendswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEqualTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEqualTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchEqualTo"
        }
      ],
      "role": "symbol",
      "title": "kODMatchEqualTo",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchequalto"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchGreaterThan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchGreaterThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchGreaterThan"
        }
      ],
      "role": "symbol",
      "title": "kODMatchGreaterThan",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchgreaterthan"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveBeginsWith": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveBeginsWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveBeginsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveBeginsWith"
        }
      ],
      "role": "symbol",
      "title": "kODMatchInsensitiveBeginsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitivebeginswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveContains": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveContains"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveContains",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveContains"
        }
      ],
      "role": "symbol",
      "title": "kODMatchInsensitiveContains",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitivecontains"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEndsWith": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveEndsWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEndsWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveEndsWith"
        }
      ],
      "role": "symbol",
      "title": "kODMatchInsensitiveEndsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitiveendswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEqualTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEqualTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchInsensitiveEqualTo"
        }
      ],
      "role": "symbol",
      "title": "kODMatchInsensitiveEqualTo",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitiveequalto"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchLessThan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODMatchLessThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchLessThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODMatchLessThan"
        }
      ],
      "role": "symbol",
      "title": "kODMatchLessThan",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchlessthan"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Enumerations",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchAny",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchBeginsWith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchContains",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEndsWith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEqualTo",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchGreaterThan",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveBeginsWith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveContains",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEndsWith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEqualTo",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchLessThan"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchAny",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchBeginsWith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchContains",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEndsWith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchEqualTo",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchGreaterThan",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveBeginsWith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveContains",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEndsWith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchInsensitiveEqualTo",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODMatchLessThan"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchGreaterThan/title",
          "value": "kODMatchGreaterThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchGreaterThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchGreaterThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchAny/title",
          "value": "kODMatchAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchEndsWith/title",
          "value": "kODMatchEndsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchEndsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchEndsWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchLessThan/title",
          "value": "kODMatchLessThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchLessThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchLessThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveEndsWith/title",
          "value": "kODMatchInsensitiveEndsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveEndsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchInsensitiveEndsWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveEqualTo/title",
          "value": "kODMatchInsensitiveEqualTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveEqualTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchInsensitiveEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchEqualTo/title",
          "value": "kODMatchEqualTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchEqualTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchContains/title",
          "value": "kODMatchContains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchContains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchContains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveContains/title",
          "value": "kODMatchInsensitiveContains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveContains/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchInsensitiveContains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveBeginsWith/title",
          "value": "kODMatchInsensitiveBeginsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchInsensitiveBeginsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchInsensitiveBeginsWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchBeginsWith/title",
          "value": "kODMatchBeginsWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODMatchBeginsWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODMatchBeginsWith"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/1497623-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/1497623-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
