{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types": {
      "abstract": [
        {
          "text": "Open Directory node types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Node Types",
      "type": "topic",
      "url": "/documentation/opendirectory/1497602-node-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497623-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497721-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579652-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningAllow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPacketSigningAllow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningAllow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPacketSigningAllow"
        }
      ],
      "role": "symbol",
      "title": "ODPacketSigningAllow",
      "type": "topic",
      "url": "/documentation/opendirectory/odpacketsigningallow"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningDisabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPacketSigningDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPacketSigningDisabled"
        }
      ],
      "role": "symbol",
      "title": "ODPacketSigningDisabled",
      "type": "topic",
      "url": "/documentation/opendirectory/odpacketsigningdisabled"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPacketSigningRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPacketSigningRequired"
        }
      ],
      "role": "symbol",
      "title": "ODPacketSigningRequired",
      "type": "topic",
      "url": "/documentation/opendirectory/odpacketsigningrequired"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Enumerations",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningAllow",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningDisabled",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningRequired"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningAllow",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningDisabled",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPacketSigningRequired"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningRequired/title",
          "value": "ODPacketSigningRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPacketSigningRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningDisabled/title",
          "value": "ODPacketSigningDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPacketSigningDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningAllow/title",
          "value": "ODPacketSigningAllow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPacketSigningAllow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPacketSigningAllow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/1579651-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/1579651-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
