{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsServerTimeout","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The authentication server timed out."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory"]]},"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"externalID":"c:@E@ODFrameworkErrors@kODErrorCredentialsServerTimeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Global Variable","navigatorTitle":[{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"}],"symbolKind":"var","modules":[{"name":"Open Directory"}],"title":"kODErrorCredentialsServerTimeout"},"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/opendirectory/koderrorcredentialsservertimeout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/opendirectory/koderrorcredentialsservertimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Constants","generated":true,"identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit"],"title":"Constants"}],"references":{"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","kind":"symbol","title":"kODErrorCredentialsInvalid","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalid","abstract":[{"type":"text","text":"The provided credentials are invalid with the current node."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalid"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","kind":"symbol","title":"kODErrorCredentialsNotAuthorized","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsnotauthorized","abstract":[{"type":"text","text":"The operation, such as changing a password, is not permitted with current privileges."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError":{"title":"kODErrorCredentialsParameterError","role":"symbol","abstract":[{"type":"text","text":"An invalid parameter was provided."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsParameterError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","url":"/documentation/opendirectory/koderrorcredentialsparametererror","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsParameterError"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsServerTimeout":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsServerTimeout","url":"/documentation/opendirectory/koderrorcredentialsservertimeout","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsServerTimeout"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"title":"kODErrorCredentialsServerTimeout","abstract":[{"text":"The authentication server timed out.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","kind":"symbol","title":"kODErrorCredentialsPasswordChangeRequired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangerequired","abstract":[{"type":"text","text":"The password must be changed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive":{"title":"kODErrorCredentialsAccountInactive","role":"symbol","abstract":[{"type":"text","text":"The account is inactive."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","url":"/documentation/opendirectory/koderrorcredentialsaccountinactive","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","kind":"symbol","title":"kODErrorCredentialsContactMaster","type":"topic","url":"/documentation/opendirectory/odframeworkerrors/koderrorcredentialscontactmaster","abstract":[{"type":"text","text":"The authentication server contacted is not the primary server, and the requested operation requires the primary server."}],"fragments":[{"kind":"identifier","text":"kODErrorCredentialsContactMaster"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","kind":"symbol","title":"kODErrorCredentialsAccountExpired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountexpired","abstract":[{"type":"text","text":"The account is expired."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","kind":"symbol","title":"kODErrorCredentialsOperationFailed","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsoperationfailed","abstract":[{"type":"text","text":"The requested operation failed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","kind":"symbol","title":"kODErrorCredentialsInvalidLogonHours","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidlogonhours","abstract":[{"type":"text","text":"The logon attempt was not within set logon hours."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","kind":"symbol","title":"kODErrorCredentialsAccountNotFound","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountnotfound","abstract":[{"type":"text","text":"The authentication server could not find the provided account."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","kind":"symbol","title":"kODErrorCredentialsInvalidComputer","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidcomputer","abstract":[{"type":"text","text":"The account is not permitted to log into this computer."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported":{"title":"kODErrorCredentialsMethodNotSupported","role":"symbol","abstract":[{"type":"text","text":"The extended authentication method is not supported."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","url":"/documentation/opendirectory/koderrorcredentialsmethodnotsupported","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","kind":"symbol","title":"kODErrorCredentialsPasswordChangeTooSoon","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangetoosoon","abstract":[{"type":"text","text":"The password was changed too recently to be changed again."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired":{"title":"kODErrorCredentialsPasswordExpired","role":"symbol","abstract":[{"type":"text","text":"The password has expired and must be changed."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","url":"/documentation/opendirectory/koderrorcredentialspasswordexpired","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","kind":"symbol","title":"ODFrameworkErrors","type":"topic","url":"/documentation/opendirectory/odframeworkerrors","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ODFrameworkErrors"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","kind":"symbol","title":"kODErrorCredentialsAccountDisabled","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountdisabled","abstract":[{"type":"text","text":"The account is disabled."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit":{"title":"kODErrorCredentialsPasswordNeedsDigit","role":"symbol","abstract":[{"type":"text","text":"The provided password needs at least one digit."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit","url":"/documentation/opendirectory/koderrorcredentialspasswordneedsdigit","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}]},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"/metadata/title","value":"kODErrorCredentialsServerTimeout","op":"replace"},{"path":"/metadata/symbolKind","value":"case","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsServerTimeout"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired"],"anchor":"Constants","generated":true,"title":"Constants"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/title","value":"kODErrorCredentialsInvalid","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalid"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/title","value":"kODErrorCredentialsNotAuthorized","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/fragments","value":[{"text":"kODErrorCredentialsNotAuthorized","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/title","value":"kODErrorCredentialsParameterError","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsParameterError"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsServerTimeout/title","value":"kODErrorCredentialsServerTimeout","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsServerTimeout/fragments","value":[{"text":"kODErrorCredentialsServerTimeout","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/title","value":"kODErrorCredentialsPasswordChangeRequired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/title","value":"kODErrorCredentialsAccountInactive","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/title","value":"kODErrorCredentialsAccountExpired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/fragments","value":[{"text":"kODErrorCredentialsAccountExpired","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/title","value":"kODErrorCredentialsOperationFailed","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/fragments","value":[{"text":"kODErrorCredentialsOperationFailed","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/title","value":"kODErrorCredentialsInvalidLogonHours","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/title","value":"kODErrorCredentialsAccountNotFound","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/fragments","value":[{"text":"kODErrorCredentialsAccountNotFound","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/title","value":"kODErrorCredentialsInvalidComputer","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/fragments","value":[{"text":"kODErrorCredentialsInvalidComputer","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/title","value":"kODErrorCredentialsMethodNotSupported","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/fragments","value":[{"text":"kODErrorCredentialsMethodNotSupported","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/title","value":"kODErrorCredentialsPasswordChangeTooSoon","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/title","value":"kODErrorCredentialsPasswordExpired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/fragments","value":[{"text":"kODErrorCredentialsPasswordExpired","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/title","value":"ODFrameworkErrors","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/fragments","value":[{"kind":"identifier","text":"ODFrameworkErrors"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/navigatorTitle","value":[{"text":"ODFrameworkErrors","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/title","value":"kODErrorCredentialsAccountDisabled","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/fragments","value":[{"text":"kODErrorCredentialsAccountDisabled","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/title","value":"kODErrorCredentialsPasswordNeedsDigit","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/fragments","value":[{"text":"kODErrorCredentialsPasswordNeedsDigit","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}