{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Open Directory"}],"title":"kODErrorCredentialsInvalidLogonHours","navigatorTitle":[{"text":"kODErrorCredentialsInvalidLogonHours","kind":"identifier"}],"roleHeading":"Global Variable","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kODErrorCredentialsInvalidLogonHours","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ODFrameworkErrors","kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"externalID":"c:@E@ODFrameworkErrors@kODErrorCredentialsInvalidLogonHours","platforms":[{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"var","role":"symbol"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory"]]},"seeAlsoSections":[{"generated":true,"title":"Constants","identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter"],"anchor":"Constants"}],"sections":[],"identifier":{"url":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The logon attempt was not within set logon hours."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opendirectory/koderrorcredentialsinvalidlogonhours"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opendirectory/koderrorcredentialsinvalidlogonhours"]}],"references":{"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","kind":"symbol","title":"kODErrorCredentialsPasswordChangeRequired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangerequired","abstract":[{"type":"text","text":"The password must be changed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","kind":"symbol","title":"kODErrorCredentialsInvalid","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalid","abstract":[{"type":"text","text":"The provided credentials are invalid with the current node."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalid"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","kind":"symbol","title":"kODErrorCredentialsAccountExpired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountexpired","abstract":[{"type":"text","text":"The account is expired."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","kind":"symbol","title":"kODErrorCredentialsContactMaster","type":"topic","url":"/documentation/opendirectory/odframeworkerrors/koderrorcredentialscontactmaster","abstract":[{"type":"text","text":"The authentication server contacted is not the primary server, and the requested operation requires the primary server."}],"fragments":[{"kind":"identifier","text":"kODErrorCredentialsContactMaster"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive":{"title":"kODErrorCredentialsAccountInactive","role":"symbol","abstract":[{"type":"text","text":"The account is inactive."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","url":"/documentation/opendirectory/koderrorcredentialsaccountinactive","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","kind":"symbol","title":"kODErrorCredentialsOperationFailed","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsoperationfailed","abstract":[{"type":"text","text":"The requested operation failed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","kind":"symbol","title":"kODErrorCredentialsInvalidComputer","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidcomputer","abstract":[{"type":"text","text":"The account is not permitted to log into this computer."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired":{"title":"kODErrorCredentialsPasswordExpired","role":"symbol","abstract":[{"type":"text","text":"The password has expired and must be changed."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","url":"/documentation/opendirectory/koderrorcredentialspasswordexpired","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported":{"title":"kODErrorCredentialsMethodNotSupported","role":"symbol","abstract":[{"type":"text","text":"The extended authentication method is not supported."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","url":"/documentation/opendirectory/koderrorcredentialsmethodnotsupported","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","kind":"symbol","title":"kODErrorCredentialsAccountNotFound","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountnotfound","abstract":[{"type":"text","text":"The authentication server could not find the provided account."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","kind":"symbol","title":"kODErrorCredentialsInvalidLogonHours","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidlogonhours","abstract":[{"type":"text","text":"The logon attempt was not within set logon hours."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","kind":"symbol","title":"ODFrameworkErrors","type":"topic","url":"/documentation/opendirectory/odframeworkerrors","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ODFrameworkErrors"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError":{"title":"kODErrorCredentialsParameterError","role":"symbol","abstract":[{"type":"text","text":"An invalid parameter was provided."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsParameterError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","url":"/documentation/opendirectory/koderrorcredentialsparametererror","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsParameterError"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","kind":"symbol","title":"kODErrorCredentialsAccountDisabled","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountdisabled","abstract":[{"type":"text","text":"The account is disabled."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","kind":"symbol","title":"kODErrorCredentialsPasswordChangeTooSoon","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangetoosoon","abstract":[{"type":"text","text":"The password was changed too recently to be changed again."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit":{"title":"kODErrorCredentialsPasswordNeedsDigit","role":"symbol","abstract":[{"type":"text","text":"The provided password needs at least one digit."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit","url":"/documentation/opendirectory/koderrorcredentialspasswordneedsdigit","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsLetter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"title":"kODErrorCredentialsPasswordNeedsLetter","url":"/documentation/opendirectory/koderrorcredentialspasswordneedsletter","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The provided password needs at least one letter."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsLetter"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","kind":"symbol","title":"kODErrorCredentialsNotAuthorized","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsnotauthorized","abstract":[{"type":"text","text":"The operation, such as changing a password, is not permitted with current privileges."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"kODErrorCredentialsInvalidLogonHours","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit"],"anchor":"Constants","title":"Constants"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"platforms":["macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/title","value":"kODErrorCredentialsPasswordChangeRequired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/fragments","value":[{"text":"kODErrorCredentialsPasswordChangeRequired","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/title","value":"kODErrorCredentialsInvalid","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalid"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/title","value":"kODErrorCredentialsAccountExpired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/title","value":"kODErrorCredentialsAccountInactive","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/fragments","value":[{"text":"kODErrorCredentialsAccountInactive","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/title","value":"kODErrorCredentialsOperationFailed","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/title","value":"kODErrorCredentialsInvalidComputer","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/title","value":"kODErrorCredentialsPasswordExpired","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/title","value":"kODErrorCredentialsMethodNotSupported","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/fragments","value":[{"text":"kODErrorCredentialsMethodNotSupported","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/title","value":"kODErrorCredentialsAccountNotFound","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/fragments","value":[{"text":"kODErrorCredentialsAccountNotFound","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/title","value":"kODErrorCredentialsInvalidLogonHours","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/fragments","value":[{"text":"kODErrorCredentialsInvalidLogonHours","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/title","value":"ODFrameworkErrors","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/fragments","value":[{"kind":"identifier","text":"ODFrameworkErrors"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/navigatorTitle","value":[{"text":"ODFrameworkErrors","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/title","value":"kODErrorCredentialsParameterError","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/fragments","value":[{"text":"kODErrorCredentialsParameterError","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/title","value":"kODErrorCredentialsAccountDisabled","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/title","value":"kODErrorCredentialsPasswordChangeTooSoon","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/title","value":"kODErrorCredentialsPasswordNeedsDigit","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsLetter/title","value":"kODErrorCredentialsPasswordNeedsLetter","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsLetter/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsLetter"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/title","value":"kODErrorCredentialsNotAuthorized","op":"replace"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/fragments","value":[{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}