{"metadata":{"roleHeading":"Global Variable","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"modules":[{"name":"Open Directory"}],"externalID":"c:@E@ODFrameworkErrors@kODErrorCredentialsAccountExpired","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol","title":"kODErrorCredentialsAccountExpired","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}],"symbolKind":"var"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired"},"seeAlsoSections":[{"title":"Constants","generated":true,"anchor":"Constants","identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter"]}],"abstract":[{"type":"text","text":"The account is expired."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@ODFrameworkErrors","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","kind":"typeIdentifier","text":"ODFrameworkErrors"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opendirectory/koderrorcredentialsaccountexpired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opendirectory/koderrorcredentialsaccountexpired"]}],"sections":[],"references":{"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive":{"title":"kODErrorCredentialsAccountInactive","role":"symbol","abstract":[{"type":"text","text":"The account is inactive."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","url":"/documentation/opendirectory/koderrorcredentialsaccountinactive","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountInactive"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","kind":"symbol","title":"kODErrorCredentialsInvalid","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalid","abstract":[{"type":"text","text":"The provided credentials are invalid with the current node."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalid"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired","kind":"symbol","title":"kODErrorCredentialsAccountExpired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountexpired","abstract":[{"type":"text","text":"The account is expired."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsLetter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"title":"kODErrorCredentialsPasswordNeedsLetter","url":"/documentation/opendirectory/koderrorcredentialspasswordneedsletter","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The provided password needs at least one letter."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsLetter"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsLetter"},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","kind":"symbol","title":"kODErrorCredentialsInvalidComputer","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidcomputer","abstract":[{"type":"text","text":"The account is not permitted to log into this computer."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","kind":"symbol","title":"kODErrorCredentialsPasswordChangeRequired","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangerequired","abstract":[{"type":"text","text":"The password must be changed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","kind":"symbol","title":"kODErrorCredentialsAccountNotFound","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountnotfound","abstract":[{"type":"text","text":"The authentication server could not find the provided account."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported":{"title":"kODErrorCredentialsMethodNotSupported","role":"symbol","abstract":[{"type":"text","text":"The extended authentication method is not supported."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","url":"/documentation/opendirectory/koderrorcredentialsmethodnotsupported","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsMethodNotSupported"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","kind":"symbol","title":"kODErrorCredentialsPasswordChangeTooSoon","type":"topic","url":"/documentation/opendirectory/koderrorcredentialspasswordchangetoosoon","abstract":[{"type":"text","text":"The password was changed too recently to be changed again."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","kind":"symbol","title":"kODErrorCredentialsOperationFailed","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsoperationfailed","abstract":[{"type":"text","text":"The requested operation failed."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","kind":"symbol","title":"kODErrorCredentialsNotAuthorized","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsnotauthorized","abstract":[{"type":"text","text":"The operation, such as changing a password, is not permitted with current privileges."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit":{"title":"kODErrorCredentialsPasswordNeedsDigit","role":"symbol","abstract":[{"type":"text","text":"The provided password needs at least one digit."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit","url":"/documentation/opendirectory/koderrorcredentialspasswordneedsdigit","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordNeedsDigit"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors","kind":"symbol","title":"ODFrameworkErrors","type":"topic","url":"/documentation/opendirectory/odframeworkerrors","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ODFrameworkErrors"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","kind":"symbol","title":"kODErrorCredentialsContactMaster","type":"topic","url":"/documentation/opendirectory/odframeworkerrors/koderrorcredentialscontactmaster","abstract":[{"type":"text","text":"The authentication server contacted is not the primary server, and the requested operation requires the primary server."}],"fragments":[{"kind":"identifier","text":"kODErrorCredentialsContactMaster"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError":{"title":"kODErrorCredentialsParameterError","role":"symbol","abstract":[{"type":"text","text":"An invalid parameter was provided."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsParameterError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","url":"/documentation/opendirectory/koderrorcredentialsparametererror","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsParameterError"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","kind":"symbol","title":"kODErrorCredentialsInvalidLogonHours","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsinvalidlogonhours","abstract":[{"type":"text","text":"The logon attempt was not within set logon hours."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled":{"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","kind":"symbol","title":"kODErrorCredentialsAccountDisabled","type":"topic","url":"/documentation/opendirectory/koderrorcredentialsaccountdisabled","abstract":[{"type":"text","text":"The account is disabled."}],"navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ODFrameworkErrors","text":"ODFrameworkErrors"}],"role":"symbol"},"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired":{"title":"kODErrorCredentialsPasswordExpired","role":"symbol","abstract":[{"type":"text","text":"The password has expired and must be changed."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ODFrameworkErrors","preciseIdentifier":"c:@E@ODFrameworkErrors"}],"type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","url":"/documentation/opendirectory/koderrorcredentialspasswordexpired","navigatorTitle":[{"kind":"identifier","text":"kODErrorCredentialsPasswordExpired"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"path":"/metadata/title","op":"replace","value":"kODErrorCredentialsAccountExpired"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountExpired"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors"]]}},{"path":"/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound","doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired","doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit"],"generated":true,"anchor":"Constants","title":"Constants"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"kODErrorCredentialsAccountExpired","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"kODErrorCredentialsAccountInactive","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/title"},{"op":"replace","value":[{"text":"kODErrorCredentialsAccountInactive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/fragments"},{"op":"replace","value":"kODErrorCredentialsInvalid","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/title"},{"op":"replace","value":[{"text":"kODErrorCredentialsInvalid","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/fragments"},{"op":"replace","value":"kODErrorCredentialsAccountExpired","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/title"},{"op":"replace","value":[{"text":"kODErrorCredentialsAccountExpired","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/fragments"},{"op":"replace","value":"kODErrorCredentialsPasswordNeedsLetter","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsLetter/title"},{"op":"replace","value":[{"text":"kODErrorCredentialsPasswordNeedsLetter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsLetter/fragments"},{"op":"replace","value":"kODErrorCredentialsInvalidComputer","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/title"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalidComputer"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/title","op":"replace","value":"kODErrorCredentialsPasswordChangeRequired"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeRequired"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/title","op":"replace","value":"kODErrorCredentialsAccountNotFound"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountNotFound"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/title","op":"replace","value":"kODErrorCredentialsMethodNotSupported"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/fragments","op":"replace","value":[{"text":"kODErrorCredentialsMethodNotSupported","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/title","op":"replace","value":"kODErrorCredentialsPasswordChangeTooSoon"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsPasswordChangeTooSoon"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/title","op":"replace","value":"kODErrorCredentialsOperationFailed"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsOperationFailed"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/title","op":"replace","value":"kODErrorCredentialsNotAuthorized"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsNotAuthorized"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/title","op":"replace","value":"kODErrorCredentialsPasswordNeedsDigit"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/fragments","op":"replace","value":[{"text":"kODErrorCredentialsPasswordNeedsDigit","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/title","op":"replace","value":"ODFrameworkErrors"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/fragments","op":"replace","value":[{"text":"ODFrameworkErrors","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/navigatorTitle","op":"replace","value":[{"text":"ODFrameworkErrors","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/title","op":"replace","value":"kODErrorCredentialsParameterError"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/fragments","op":"replace","value":[{"text":"kODErrorCredentialsParameterError","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/title","op":"replace","value":"kODErrorCredentialsInvalidLogonHours"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsInvalidLogonHours"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/title","op":"replace","value":"kODErrorCredentialsAccountDisabled"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/fragments","op":"replace","value":[{"kind":"identifier","text":"kODErrorCredentialsAccountDisabled"}]},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/title","op":"replace","value":"kODErrorCredentialsPasswordExpired"},{"path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/fragments","op":"replace","value":[{"text":"kODErrorCredentialsPasswordExpired","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}