{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorNodeDisabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ODFrameworkErrors@kODErrorNodeDisabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kODErrorNodeDisabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ODFrameworkErrors",
        "text": "ODFrameworkErrors"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kODErrorNodeDisabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kODErrorNodeDisabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kODErrorNodeDisabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ODFrameworkErrors",
              "text": "ODFrameworkErrors"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODFrameworkErrors"
        }
      ],
      "role": "symbol",
      "title": "ODFrameworkErrors",
      "type": "topic",
      "url": "/documentation/opendirectory/odframeworkerrors"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster": {
      "abstract": [
        {
          "text": "The authentication server contacted is not the primary server, and the requested operation requires the primary server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsContactMaster"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster",
      "kind": "symbol",
      "role": "symbol",
      "title": "kODErrorCredentialsContactMaster",
      "type": "topic",
      "url": "/documentation/opendirectory/odframeworkerrors/koderrorcredentialscontactmaster"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled": {
      "abstract": [
        {
          "text": "The account is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountDisabled"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsAccountDisabled",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsaccountdisabled"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired": {
      "abstract": [
        {
          "text": "The account is expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountExpired"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsAccountExpired",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsaccountexpired"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive": {
      "abstract": [
        {
          "text": "The account is inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountInactive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountInactive"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsAccountInactive",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsaccountinactive"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound": {
      "abstract": [
        {
          "text": "The authentication server could not find the provided account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsAccountNotFound"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsAccountNotFound",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsaccountnotfound"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid": {
      "abstract": [
        {
          "text": "The provided credentials are invalid with the current node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalid"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsInvalid",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsinvalid"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer": {
      "abstract": [
        {
          "text": "The account is not permitted to log into this computer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalidComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalidComputer"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsInvalidComputer",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsinvalidcomputer"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours": {
      "abstract": [
        {
          "text": "The logon attempt was not within set logon hours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalidLogonHours"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsInvalidLogonHours"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsInvalidLogonHours",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsinvalidlogonhours"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported": {
      "abstract": [
        {
          "text": "The extended authentication method is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsMethodNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsMethodNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsMethodNotSupported",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsmethodnotsupported"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized": {
      "abstract": [
        {
          "text": "The operation, such as changing a password, is not permitted with current privileges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsNotAuthorized",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsnotauthorized"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed": {
      "abstract": [
        {
          "text": "The requested operation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsOperationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsOperationFailed"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsOperationFailed",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsoperationfailed"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError": {
      "abstract": [
        {
          "text": "An invalid parameter was provided.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsParameterError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsParameterError"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsParameterError",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialsparametererror"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired": {
      "abstract": [
        {
          "text": "The password must be changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordChangeRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordChangeRequired"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsPasswordChangeRequired",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialspasswordchangerequired"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon": {
      "abstract": [
        {
          "text": "The password was changed too recently to be changed again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordChangeTooSoon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordChangeTooSoon"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsPasswordChangeTooSoon",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialspasswordchangetoosoon"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired": {
      "abstract": [
        {
          "text": "The password has expired and must be changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordExpired"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsPasswordExpired",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialspasswordexpired"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit": {
      "abstract": [
        {
          "text": "The provided password needs at least one digit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordNeedsDigit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorCredentialsPasswordNeedsDigit"
        }
      ],
      "role": "symbol",
      "title": "kODErrorCredentialsPasswordNeedsDigit",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrorcredentialspasswordneedsdigit"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorNodeDisabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODErrorNodeDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ODFrameworkErrors",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorNodeDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODErrorNodeDisabled"
        }
      ],
      "role": "symbol",
      "title": "kODErrorNodeDisabled",
      "type": "topic",
      "url": "/documentation/opendirectory/koderrornodedisabled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordNeedsDigit"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kODErrorNodeDisabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorNodeDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountDisabled",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountExpired",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountInactive",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsAccountNotFound",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors/kODErrorCredentialsContactMaster",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalid",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidComputer",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsInvalidLogonHours",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsMethodNotSupported",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsNotAuthorized",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsOperationFailed",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsParameterError",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeRequired",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordChangeTooSoon",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODErrorCredentialsPasswordExpired"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kODErrorNodeDisabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/title",
          "value": "kODErrorCredentialsAccountExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsAccountExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/title",
          "value": "kODErrorCredentialsInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/title",
          "value": "kODErrorCredentialsInvalidComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsInvalidComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/title",
          "value": "kODErrorCredentialsAccountNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsAccountNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/title",
          "value": "ODFrameworkErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODFrameworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODFrameworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/title",
          "value": "kODErrorCredentialsNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsNotAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/title",
          "value": "kODErrorCredentialsOperationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsOperationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsOperationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/title",
          "value": "kODErrorCredentialsInvalidLogonHours"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsInvalidLogonHours/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsInvalidLogonHours"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorNodeDisabled/title",
          "value": "kODErrorNodeDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorNodeDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorNodeDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/title",
          "value": "kODErrorCredentialsAccountInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountInactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsAccountInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/title",
          "value": "kODErrorCredentialsMethodNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsMethodNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsMethodNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/title",
          "value": "kODErrorCredentialsPasswordChangeRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsPasswordChangeRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/title",
          "value": "kODErrorCredentialsParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsParameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/title",
          "value": "kODErrorCredentialsAccountDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsAccountDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsAccountDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/title",
          "value": "kODErrorCredentialsPasswordExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsPasswordExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/title",
          "value": "kODErrorCredentialsPasswordChangeTooSoon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordChangeTooSoon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsPasswordChangeTooSoon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/title",
          "value": "kODErrorCredentialsPasswordNeedsDigit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODErrorCredentialsPasswordNeedsDigit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODErrorCredentialsPasswordNeedsDigit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/koderrornodedisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/koderrornodedisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
