{
  "abstract": [
    {
      "text": "A match that returns records that contain a certain value. This match is case sensitive.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/match-types"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchcontains"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "kODMatchContains"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchany": {
      "abstract": [
        {
          "text": "A match that returns all records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchany",
      "kind": "article",
      "role": "article",
      "title": "kODMatchAny",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchany"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchbeginswith": {
      "abstract": [
        {
          "text": "A match that returns records that begin with a certain value. This match is case sensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchbeginswith",
      "kind": "article",
      "role": "article",
      "title": "kODMatchBeginsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchbeginswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchendswith": {
      "abstract": [
        {
          "text": "A match that returns records that end with a certain value. This match is case sensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchendswith",
      "kind": "article",
      "role": "article",
      "title": "kODMatchEndsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchendswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchequalto": {
      "abstract": [
        {
          "text": "A match that returns records that are equal to a certain value. This match is case sensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchequalto",
      "kind": "article",
      "role": "article",
      "title": "kODMatchEqualTo",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchequalto"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchgreaterthan": {
      "abstract": [
        {
          "text": "A match that returns records that are greater than a certain value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchgreaterthan",
      "kind": "article",
      "role": "article",
      "title": "kODMatchGreaterThan",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchgreaterthan"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivebeginswith": {
      "abstract": [
        {
          "text": "A match that returns records that begin with a certain value. This match is case insensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivebeginswith",
      "kind": "article",
      "role": "article",
      "title": "kODMatchInsensitiveBeginsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitivebeginswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivecontains": {
      "abstract": [
        {
          "text": "A match that returns records that contain a certain value. This match is case insensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivecontains",
      "kind": "article",
      "role": "article",
      "title": "kODMatchInsensitiveContains",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitivecontains"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveendswith": {
      "abstract": [
        {
          "text": "A match that returns records that end with a certain value. This match is case insensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveendswith",
      "kind": "article",
      "role": "article",
      "title": "kODMatchInsensitiveEndsWith",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitiveendswith"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveequalto": {
      "abstract": [
        {
          "text": "A match that returns records that are equal to a certain value. This match is case insensitive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveequalto",
      "kind": "article",
      "role": "article",
      "title": "kODMatchInsensitiveEqualTo",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchinsensitiveequalto"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchlessthan": {
      "abstract": [
        {
          "text": "A match that returns records that are less than a certain value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchlessthan",
      "kind": "article",
      "role": "article",
      "title": "kODMatchLessThan",
      "type": "topic",
      "url": "/documentation/opendirectory/kodmatchlessthan"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/match-types": {
      "abstract": [
        {
          "text": "Types of matches used for searches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/match-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Match Types",
      "type": "topic",
      "url": "/documentation/opendirectory/match-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions": {
      "abstract": [
        {
          "text": "This document describes the functions, constants, and data types used to interact with Open Directory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Functions",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchany",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchequalto",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchbeginswith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchendswith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchgreaterthan",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchlessthan",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveequalto",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivebeginswith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveendswith",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivecontains"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchany",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchequalto",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchbeginswith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchendswith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchgreaterthan",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchlessthan",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveequalto",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivebeginswith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitiveendswith",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kodmatchinsensitivecontains"
              ],
              "title": "Constants"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/kodmatchcontains"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/kodmatchcontains"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
