{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODPolicyTypePasswordSelfModification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kODPolicyTypePasswordSelfModification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kODPolicyTypePasswordSelfModification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kODPolicyTypePasswordSelfModification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kODPolicyTypePasswordSelfModification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kODPolicyTypePasswordSelfModification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODFrameworkErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODFrameworkErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ODFrameworkErrorDomain",
      "type": "topic",
      "url": "/documentation/opendirectory/odframeworkerrordomain"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPolicyType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPolicyType"
        }
      ],
      "role": "symbol",
      "title": "ODPolicyType",
      "type": "topic",
      "url": "/documentation/opendirectory/odpolicytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyAddress": {
      "abstract": [
        {
          "text": "The address to connect to via proxy. The value is of type ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionProxyAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionProxyAddress"
        }
      ],
      "role": "symbol",
      "title": "ODSessionProxyAddress",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionproxyaddress"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPassword": {
      "abstract": [
        {
          "text": "The password to connect with via proxy. The value is of type ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionProxyPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPassword",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionProxyPassword"
        }
      ],
      "role": "symbol",
      "title": "ODSessionProxyPassword",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionproxypassword"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPort": {
      "abstract": [
        {
          "text": "The port to connect to via proxy. The value is of type ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionProxyPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionProxyPort"
        }
      ],
      "role": "symbol",
      "title": "ODSessionProxyPort",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionproxyport"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyUsername": {
      "abstract": [
        {
          "text": "The username to connect with via proxy. The value is of type ",
          "type": "text"
        },
        {
          "code": "NSString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionProxyUsername"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyUsername",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionProxyUsername"
        }
      ],
      "role": "symbol",
      "title": "ODSessionProxyUsername",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionproxyusername"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeAnonymous": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODTrustTypeAnonymous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeAnonymous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODTrustTypeAnonymous"
        }
      ],
      "role": "symbol",
      "title": "ODTrustTypeAnonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/odtrusttypeanonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeJoined": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODTrustTypeJoined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeJoined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODTrustTypeJoined"
        }
      ],
      "role": "symbol",
      "title": "ODTrustTypeJoined",
      "type": "topic",
      "url": "/documentation/opendirectory/odtrusttypejoined"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeUsingCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODTrustTypeUsingCredentials"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeUsingCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODTrustTypeUsingCredentials"
        }
      ],
      "role": "symbol",
      "title": "ODTrustTypeUsingCredentials",
      "type": "topic",
      "url": "/documentation/opendirectory/odtrusttypeusingcredentials"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeAltSecurityIdentities": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeAltSecurityIdentities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeAltSecurityIdentities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeAltSecurityIdentities"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeAltSecurityIdentities",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypealtsecurityidentities"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeHardwareUUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeHardwareUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeHardwareUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeHardwareUUID"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeHardwareUUID",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypehardwareuuid"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAmbiguousName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaAmbiguousName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAmbiguousName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaAmbiguousName"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeMetaAmbiguousName",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypemetaambiguousname"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAugmentedAttributes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaAugmentedAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAugmentedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaAugmentedAttributes"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeMetaAugmentedAttributes",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypemetaaugmentedattributes"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaRecordName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaRecordName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaRecordName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeMetaRecordName"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeMetaRecordName",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypemetarecordname"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeNodeOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeNodeOptions"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeNodeOptions",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypenodeoptions"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeSASLRealm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODAttributeTypeNodeSASLRealm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeSASLRealm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODAttributeTypeNodeSASLRealm"
        }
      ],
      "role": "symbol",
      "title": "kODAttributeTypeNodeSASLRealm",
      "type": "topic",
      "url": "/documentation/opendirectory/kodattributetypenodesaslrealm"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/kODPolicyTypePasswordSelfModification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kODPolicyTypePasswordSelfModification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/kODPolicyTypePasswordSelfModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kODPolicyTypePasswordSelfModification"
        }
      ],
      "role": "symbol",
      "title": "kODPolicyTypePasswordSelfModification",
      "type": "topic",
      "url": "/documentation/opendirectory/kodpolicytypepasswordselfmodification"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrorDomain",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyAddress",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPassword",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPort",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyUsername",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeAnonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeJoined",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeUsingCredentials",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeAltSecurityIdentities",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeHardwareUUID",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAmbiguousName",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAugmentedAttributes",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaRecordName",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeOptions",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeSASLRealm"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kODPolicyTypePasswordSelfModification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODPolicyTypePasswordSelfModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrorDomain",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyAddress",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPassword",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyPort",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionProxyUsername",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeAnonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeJoined",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODTrustTypeUsingCredentials",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeAltSecurityIdentities",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeHardwareUUID",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAmbiguousName",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaAugmentedAttributes",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeMetaRecordName",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeOptions",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/kODAttributeTypeNodeSASLRealm"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ODPolicyType",
                    "text": "ODPolicyType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kODPolicyTypePasswordSelfModification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyPassword/title",
          "value": "ODSessionProxyPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyPassword/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionProxyPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeNodeOptions/title",
          "value": "kODAttributeTypeNodeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeNodeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeNodeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaRecordName/title",
          "value": "kODAttributeTypeMetaRecordName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaRecordName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeMetaRecordName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODPolicyTypePasswordSelfModification/title",
          "value": "kODPolicyTypePasswordSelfModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODPolicyTypePasswordSelfModification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODPolicyTypePasswordSelfModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrorDomain/title",
          "value": "ODFrameworkErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODFrameworkErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeHardwareUUID/title",
          "value": "kODAttributeTypeHardwareUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeHardwareUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeHardwareUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeNodeSASLRealm/title",
          "value": "kODAttributeTypeNodeSASLRealm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeNodeSASLRealm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeNodeSASLRealm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeJoined/title",
          "value": "ODTrustTypeJoined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeJoined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODTrustTypeJoined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeAnonymous/title",
          "value": "ODTrustTypeAnonymous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeAnonymous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODTrustTypeAnonymous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyUsername/title",
          "value": "ODSessionProxyUsername"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyUsername/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionProxyUsername"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeAltSecurityIdentities/title",
          "value": "kODAttributeTypeAltSecurityIdentities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeAltSecurityIdentities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeAltSecurityIdentities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyAddress/title",
          "value": "ODSessionProxyAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionProxyAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/title",
          "value": "ODPolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeUsingCredentials/title",
          "value": "ODTrustTypeUsingCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODTrustTypeUsingCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODTrustTypeUsingCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaAugmentedAttributes/title",
          "value": "kODAttributeTypeMetaAugmentedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaAugmentedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeMetaAugmentedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyPort/title",
          "value": "ODSessionProxyPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionProxyPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionProxyPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaAmbiguousName/title",
          "value": "kODAttributeTypeMetaAmbiguousName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1kODAttributeTypeMetaAmbiguousName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kODAttributeTypeMetaAmbiguousName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/kodpolicytypepasswordselfmodification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/kodpolicytypepasswordselfmodification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
