{
  "abstract": [
    {
      "text": "An Open Directory attribute type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ODAttributeType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ODAttributeType"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ODAttributeType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "ODAttributeType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/odattributetype"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/general-attribute-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/configuration-attribute-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for recognized attribute type values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType": {
      "abstract": [
        {
          "text": "An Open Directory attribute type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODAttributeType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODAttributeType"
        }
      ],
      "role": "symbol",
      "title": "ODAttributeType",
      "type": "topic",
      "url": "/documentation/opendirectory/odattributetype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAuthenticationType": {
      "abstract": [
        {
          "text": "An Open Directory authentication type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODAuthenticationType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAuthenticationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODAuthenticationType"
        }
      ],
      "role": "symbol",
      "title": "ODAuthenticationType",
      "type": "topic",
      "url": "/documentation/opendirectory/odauthenticationtype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext": {
      "abstract": [
        {
          "text": "An Open Directory context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "role": "symbol",
      "title": "ODContext",
      "type": "topic",
      "url": "/documentation/opendirectory/odcontext"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType": {
      "abstract": [
        {
          "text": "An Open Directory match type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODMatchType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODMatchType"
        }
      ],
      "role": "symbol",
      "title": "ODMatchType",
      "type": "topic",
      "url": "/documentation/opendirectory/odmatchtype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef": {
      "abstract": [
        {
          "text": "An Open Directory node type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "role": "symbol",
      "title": "ODNodeRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odnoderef"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeType": {
      "abstract": [
        {
          "text": "An Open Directory node type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNodeType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNodeType"
        }
      ],
      "role": "symbol",
      "title": "ODNodeType",
      "type": "topic",
      "url": "/documentation/opendirectory/odnodetype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryCallback": {
      "abstract": [
        {
          "text": "A callback function called as results from a scheduled query are returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQueryCallback"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQueryCallback"
        }
      ],
      "role": "symbol",
      "title": "ODQueryCallback",
      "type": "topic",
      "url": "/documentation/opendirectory/odquerycallback"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef": {
      "abstract": [
        {
          "text": "An Open Directory query type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "role": "symbol",
      "title": "ODQueryRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odqueryref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef": {
      "abstract": [
        {
          "text": "An Open Directory record type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "role": "symbol",
      "title": "ODRecordRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordType": {
      "abstract": [
        {
          "text": "An Open Directory record type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordType"
        }
      ],
      "role": "symbol",
      "title": "ODRecordType",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordtype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef": {
      "abstract": [
        {
          "text": "An Open Directory session type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "role": "symbol",
      "title": "ODSessionRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/configuration-attribute-types": {
      "abstract": [
        {
          "text": "Types of Open Directory attributes specifically for use with configure nodes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/configuration-attribute-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Configuration Attribute Types",
      "type": "topic",
      "url": "/documentation/opendirectory/configuration-attribute-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/general-attribute-types": {
      "abstract": [
        {
          "text": "Types of Open Directory attributes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/general-attribute-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "General Attribute Types",
      "type": "topic",
      "url": "/documentation/opendirectory/general-attribute-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/odattributetype": {
      "abstract": [
        {
          "text": "An Open Directory attribute type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/odattributetype",
      "kind": "article",
      "role": "article",
      "title": "_ODAttributeType",
      "type": "topic",
      "url": "/documentation/opendirectory/odattributetype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/odauthenticationtype": {
      "abstract": [
        {
          "text": "An Open Directory authentication type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/odauthenticationtype",
      "kind": "article",
      "role": "article",
      "title": "_ODAuthenticationType",
      "type": "topic",
      "url": "/documentation/opendirectory/odauthenticationtype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/odrecordtype": {
      "abstract": [
        {
          "text": "An Open Directory record type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/odrecordtype",
      "kind": "article",
      "role": "article",
      "title": "_ODRecordType",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordtype"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAuthenticationType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryCallback",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/odattributetype",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/odauthenticationtype",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/odrecordtype"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ODAttributeType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAuthenticationType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMatchType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryCallback",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/odattributetype",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/odauthenticationtype",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/odrecordtype"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "ODAttributeType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryCallback/title",
          "value": "ODQueryCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/title",
          "value": "ODContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/title",
          "value": "ODQueryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordType/title",
          "value": "ODRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/title",
          "value": "ODNodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeType/title",
          "value": "ODNodeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/title",
          "value": "ODAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/title",
          "value": "ODMatchType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMatchType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMatchType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/title",
          "value": "ODSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/title",
          "value": "ODRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAuthenticationType/title",
          "value": "ODAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAuthenticationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAuthenticationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAuthenticationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/odattributetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
