{
  "abstract": [
    {
      "text": "An Open Directory context type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@ODContextRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ODContext"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ODContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ODContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ODContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODAttributeMap"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODAttributeMap"
        }
      ],
      "role": "symbol",
      "title": "ODAttributeMap",
      "type": "topic",
      "url": "/documentation/opendirectory/odattributemap"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ODConfiguration",
      "type": "topic",
      "url": "/documentation/opendirectory/odconfiguration"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext": {
      "abstract": [
        {
          "text": "An Open Directory context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "role": "symbol",
      "title": "ODContext",
      "type": "topic",
      "url": "/documentation/opendirectory/odcontext"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODMappings"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODMappings"
        }
      ],
      "role": "symbol",
      "title": "ODMappings",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODModuleEntry"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODModuleEntry"
        }
      ],
      "role": "symbol",
      "title": "ODModuleEntry",
      "type": "topic",
      "url": "/documentation/opendirectory/odmoduleentry"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODNode",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "role": "symbol",
      "title": "ODNode",
      "type": "topic",
      "url": "/documentation/opendirectory/odnode"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef": {
      "abstract": [
        {
          "text": "An Open Directory node type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "role": "symbol",
      "title": "ODNodeRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odnoderef"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODQuery",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "role": "symbol",
      "title": "ODQuery",
      "type": "topic",
      "url": "/documentation/opendirectory/odquery"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef": {
      "abstract": [
        {
          "text": "An Open Directory query type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "role": "symbol",
      "title": "ODQueryRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odqueryref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODRecord",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "role": "symbol",
      "title": "ODRecord",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecord"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordMap"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordMap"
        }
      ],
      "role": "symbol",
      "title": "ODRecordMap",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordmap"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef": {
      "abstract": [
        {
          "text": "An Open Directory record type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "role": "symbol",
      "title": "ODRecordRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODSession",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSession"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSession"
        }
      ],
      "role": "symbol",
      "title": "ODSession",
      "type": "topic",
      "url": "/documentation/opendirectory/odsession"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef": {
      "abstract": [
        {
          "text": "An Open Directory session type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "role": "symbol",
      "title": "ODSessionRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionref"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef"
      ],
      "title": "Classes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ODContextRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@__ODContext",
                    "text": "__ODContext"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "ODContextRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/title",
          "value": "ODRecordMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/title",
          "value": "ODMappings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/title",
          "value": "ODContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/title",
          "value": "ODRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/title",
          "value": "ODQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/title",
          "value": "ODModuleEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODModuleEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODModuleEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/title",
          "value": "ODSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/title",
          "value": "ODAttributeMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/title",
          "value": "ODNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/title",
          "value": "ODQueryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/title",
          "value": "ODSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/title",
          "value": "ODNodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/title",
          "value": "ODRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/title",
          "value": "ODConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/odcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
