{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ODMappings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ODMappings"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ODMappings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ODMappings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODAttributeMap"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODAttributeMap"
        }
      ],
      "role": "symbol",
      "title": "ODAttributeMap",
      "type": "topic",
      "url": "/documentation/opendirectory/odattributemap"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ODConfiguration",
      "type": "topic",
      "url": "/documentation/opendirectory/odconfiguration"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext": {
      "abstract": [
        {
          "text": "An Open Directory context type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODContext"
        }
      ],
      "role": "symbol",
      "title": "ODContext",
      "type": "topic",
      "url": "/documentation/opendirectory/odcontext"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODMappings"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODMappings"
        }
      ],
      "role": "symbol",
      "title": "ODMappings",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "comment"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "comment",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/comment-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comment"
        }
      ],
      "role": "symbol",
      "title": "comment",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/comment-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "function"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "function",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/function-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "function"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "function"
        }
      ],
      "role": "symbol",
      "title": "function",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/function-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "functionAttributes"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "functionAttributes",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/functionattributes-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "functionAttributes"
        }
      ],
      "role": "symbol",
      "title": "functionAttributes",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/functionattributes-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/identifier-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/identifier-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/mappings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "mappings"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/mappings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mappings"
        }
      ],
      "role": "symbol",
      "title": "mappings",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/mappings"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordMap(forStandardRecordType:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forStandardRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ODRecordMap",
          "text": "ODRecordMap"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordMap(forStandardRecordType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordMapForStandardRecordType:"
        }
      ],
      "role": "symbol",
      "title": "recordMap(forStandardRecordType:)",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/recordmap(forstandardrecordtype:)"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "recordTypes"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "recordTypes",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/recordtypes-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordTypes"
        }
      ],
      "role": "symbol",
      "title": "recordTypes",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/recordtypes-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRecordMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ODRecordMap",
          "text": "ODRecordMap"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "forStandardRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setRecordMap:forStandardRecordType:"
        }
      ],
      "role": "symbol",
      "title": "setRecordMap(_:forStandardRecordType:)",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/setrecordmap(_:forstandardrecordtype:)"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-c.ivar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "templateName"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-c.ivar",
      "kind": "symbol",
      "role": "symbol",
      "title": "templateName",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/templatename-c.ivar"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-swift.property": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateName"
        }
      ],
      "role": "symbol",
      "title": "templateName",
      "type": "topic",
      "url": "/documentation/opendirectory/odmappings/templatename-swift.property"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODModuleEntry"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODModuleEntry"
        }
      ],
      "role": "symbol",
      "title": "ODModuleEntry",
      "type": "topic",
      "url": "/documentation/opendirectory/odmoduleentry"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODNode",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNode"
        }
      ],
      "role": "symbol",
      "title": "ODNode",
      "type": "topic",
      "url": "/documentation/opendirectory/odnode"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef": {
      "abstract": [
        {
          "text": "An Open Directory node type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODNodeRef"
        }
      ],
      "role": "symbol",
      "title": "ODNodeRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odnoderef"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODQuery",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQuery"
        }
      ],
      "role": "symbol",
      "title": "ODQuery",
      "type": "topic",
      "url": "/documentation/opendirectory/odquery"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef": {
      "abstract": [
        {
          "text": "An Open Directory query type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODQueryRef"
        }
      ],
      "role": "symbol",
      "title": "ODQueryRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odqueryref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODRecord",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "role": "symbol",
      "title": "ODRecord",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecord"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordMap"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordMap"
        }
      ],
      "role": "symbol",
      "title": "ODRecordMap",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordmap"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef": {
      "abstract": [
        {
          "text": "An Open Directory record type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecordRef"
        }
      ],
      "role": "symbol",
      "title": "ODRecordRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecordref"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODSession",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSession"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSession"
        }
      ],
      "role": "symbol",
      "title": "ODSession",
      "type": "topic",
      "url": "/documentation/opendirectory/odsession"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef": {
      "abstract": [
        {
          "text": "An Open Directory session type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODSessionRef"
        }
      ],
      "role": "symbol",
      "title": "ODSessionRef",
      "type": "topic",
      "url": "/documentation/opendirectory/odsessionref"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-swift.property",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-swift.property",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-swift.property",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-swift.property",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-swift.property",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-swift.property"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordMap(forStandardRecordType:)",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ODMappings"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-c.ivar",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-c.ivar",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-c.ivar",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-c.ivar",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-c.ivar",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-c.ivar"
              ],
              "title": "Instance Variables"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/comment-swift.property",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/function-swift.property",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/functionAttributes-swift.property",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/identifier-swift.property",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordTypes-swift.property",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/templateName-swift.property"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/recordMap(forStandardRecordType:)",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/setRecordMap(_:forStandardRecordType:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODMappings/mappings"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODAttributeMap",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODConfiguration",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODContext",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODModuleEntry",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNode",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODNodeRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQuery",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODQueryRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordRef",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSession",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODSessionRef"
              ],
              "title": "Classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ODMappings"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1setRecordMap(_:forStandardRecordType:)/title",
          "value": "setRecordMap:forStandardRecordType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1setRecordMap(_:forStandardRecordType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setRecordMap:forStandardRecordType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1recordMap(forStandardRecordType:)/title",
          "value": "recordMapForStandardRecordType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1recordMap(forStandardRecordType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordMapForStandardRecordType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1templateName-swift.property/title",
          "value": "templateName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1templateName-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "templateName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/title",
          "value": "ODQueryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQueryRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQueryRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/title",
          "value": "ODNodeRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNodeRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNodeRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/title",
          "value": "ODRecordMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/title",
          "value": "ODSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/title",
          "value": "ODSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODSessionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1function-swift.property/title",
          "value": "function"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1function-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "function"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1identifier-swift.property/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1identifier-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/title",
          "value": "ODModuleEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODModuleEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODModuleEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODModuleEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/title",
          "value": "ODRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/title",
          "value": "ODNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/title",
          "value": "ODMappings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODMappings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1comment-swift.property/title",
          "value": "comment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1comment-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "comment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1functionAttributes-swift.property/title",
          "value": "functionAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1functionAttributes-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "functionAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/title",
          "value": "ODConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/title",
          "value": "ODQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/title",
          "value": "ODRecordRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecordRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1recordTypes-swift.property/title",
          "value": "recordTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODMappings~1recordTypes-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/title",
          "value": "ODAttributeMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODAttributeMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODAttributeMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/title",
          "value": "ODContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODContextRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odmappings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/odmappings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
