{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "collectionGroup",
    "title": "OpenDirectory Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types": {
      "abstract": [
        {
          "text": "Open Directory node types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Node Types",
      "type": "topic",
      "url": "/documentation/opendirectory/1497602-node-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497623-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1497721-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579651-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Anonymous",
      "type": "topic",
      "url": "/documentation/opendirectory/1579652-anonymous"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Constants",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-constants"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Data Types",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-data-types"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions": {
      "abstract": [
        {
          "text": "This document describes the functions, constants, and data types used to interact with Open Directory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Functions",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497602-node-types",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579651-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1579652-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497623-anonymous",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/1497721-anonymous"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-data-types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/opendirectory-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/opendirectory-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
