{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "OpenDirectory Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODErrorUserInfoKeyType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODErrorUserInfoKeyType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODErrorUserInfoKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODErrorUserInfoKeyType"
        }
      ],
      "role": "symbol",
      "title": "ODErrorUserInfoKeyType",
      "type": "topic",
      "url": "/documentation/opendirectory/oderroruserinfokeytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODFrameworkErrors"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODFrameworkErrors"
        }
      ],
      "role": "symbol",
      "title": "ODFrameworkErrors",
      "type": "topic",
      "url": "/documentation/opendirectory/odframeworkerrors"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODOptionKeyType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODOptionKeyType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODOptionKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODOptionKeyType"
        }
      ],
      "role": "symbol",
      "title": "ODOptionKeyType",
      "type": "topic",
      "url": "/documentation/opendirectory/odoptionkeytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyAttributeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPolicyAttributeType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPolicyAttributeType"
        }
      ],
      "role": "symbol",
      "title": "ODPolicyAttributeType",
      "type": "topic",
      "url": "/documentation/opendirectory/odpolicyattributetype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPolicyCategoryType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPolicyCategoryType"
        }
      ],
      "role": "symbol",
      "title": "ODPolicyCategoryType",
      "type": "topic",
      "url": "/documentation/opendirectory/odpolicycategorytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyKeyType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPolicyKeyType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPolicyKeyType"
        }
      ],
      "role": "symbol",
      "title": "ODPolicyKeyType",
      "type": "topic",
      "url": "/documentation/opendirectory/odpolicykeytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODPolicyType"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODPolicyType"
        }
      ],
      "role": "symbol",
      "title": "ODPolicyType",
      "type": "topic",
      "url": "/documentation/opendirectory/odpolicytype"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Constants",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-constants"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Enumerations",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-enumerations"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions": {
      "abstract": [
        {
          "text": "This document describes the functions, constants, and data types used to interact with Open Directory.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OpenDirectory Functions",
      "type": "topic",
      "url": "/documentation/opendirectory/opendirectory-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyAttributeType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyKeyType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODErrorUserInfoKeyType",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODOptionKeyType"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyAttributeType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyCategoryType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyKeyType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODPolicyType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODErrorUserInfoKeyType",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODFrameworkErrors",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODOptionKeyType"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-functions",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-enumerations",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/opendirectory-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODErrorUserInfoKeyType/title",
          "value": "ODErrorUserInfoKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODErrorUserInfoKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODErrorUserInfoKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODErrorUserInfoKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODErrorUserInfoKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/title",
          "value": "ODFrameworkErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODFrameworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODFrameworkErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODFrameworkErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyKeyType/title",
          "value": "ODPolicyKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyAttributeType/title",
          "value": "ODPolicyAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/title",
          "value": "ODPolicyCategoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyCategoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyCategoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/title",
          "value": "ODPolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODPolicyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODPolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODOptionKeyType/title",
          "value": "ODOptionKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODOptionKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODOptionKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODOptionKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODOptionKeyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/opendirectory-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/opendirectory-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
