{
  "abstract": [
    {
      "text": "A satellite image of the area with road and road name information layered on top.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MKMapType@MKMapTypeHybrid",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hybrid"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MKMapTypeHybrid"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MKMapType.hybrid"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hybrid"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType": {
      "abstract": [
        {
          "text": "The type of map to display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapType"
        }
      ],
      "role": "symbol",
      "title": "MKMapType",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid": {
      "abstract": [
        {
          "text": "A satellite image of the area with road and road name information layered on top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hybrid"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybrid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeHybrid"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.hybrid",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/hybrid"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover": {
      "abstract": [
        {
          "text": "A hybrid satellite image with flyover data where available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hybridFlyover"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeHybridFlyover"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.hybridFlyover",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/hybridflyover"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard": {
      "abstract": [
        {
          "text": "A street map where MapKit emphasizes your data over the underlying map details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mutedStandard"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeMutedStandard"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.mutedStandard",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/mutedstandard"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite": {
      "abstract": [
        {
          "text": "Satellite imagery of the area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "satellite"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeSatellite"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.satellite",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/satellite"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover": {
      "abstract": [
        {
          "text": "A satellite image of the area with flyover data where available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "satelliteFlyover"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeSatelliteFlyover"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.satelliteFlyover",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/satelliteflyover"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard": {
      "abstract": [
        {
          "text": "A street map that shows the position of all roads and some road names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standard"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKMapTypeStandard"
        }
      ],
      "role": "symbol",
      "title": "MKMapType.standard",
      "type": "topic",
      "url": "/documentation/mapkit/mkmaptype/standard"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKMapTypeHybrid"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeHybrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/standard",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satellite",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/satelliteFlyover",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/hybridFlyover",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapType/mutedStandard"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MKMapTypeHybrid"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satellite/title",
          "value": "MKMapTypeSatellite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satellite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeSatellite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satelliteFlyover/title",
          "value": "MKMapTypeSatelliteFlyover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1satelliteFlyover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeSatelliteFlyover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1mutedStandard/title",
          "value": "MKMapTypeMutedStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1mutedStandard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeMutedStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybrid/title",
          "value": "MKMapTypeHybrid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybrid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeHybrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/title",
          "value": "MKMapType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1standard/title",
          "value": "MKMapTypeStandard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1standard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeStandard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybridFlyover/title",
          "value": "MKMapTypeHybridFlyover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapType~1hybridFlyover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapTypeHybridFlyover"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkmaptype/hybrid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkmaptype/hybrid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
