{
  "abstract": [
    {
      "text": "A flag that indicates the time is negative infinity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/negativeInfinity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMTimeFlags@kCMTimeFlags_NegativeInfinity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "negativeInfinity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CMTimeFlags",
        "text": "CMTimeFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTimeFlags_NegativeInfinity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "negativeInfinity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "negativeInfinity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMTimeFlags",
              "text": "CMTimeFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags": {
      "abstract": [
        {
          "text": "A structure that defines the flags for a time value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTimeFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/hasBeenRounded": {
      "abstract": [
        {
          "text": "A flag that indicates a previous time calculation rounded the result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasBeenRounded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/hasBeenRounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_HasBeenRounded"
        }
      ],
      "role": "symbol",
      "title": "hasBeenRounded",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/hasbeenrounded"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/impliedValueFlagsMask": {
      "abstract": [
        {
          "text": "A flag that indicates the time is positive or negative infinity, or indefinite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "impliedValueFlagsMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/impliedValueFlagsMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_ImpliedValueFlagsMask"
        }
      ],
      "role": "symbol",
      "title": "impliedValueFlagsMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/impliedvalueflagsmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/indefinite": {
      "abstract": [
        {
          "text": "A flag that indicates the time is indefinite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indefinite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/indefinite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_Indefinite"
        }
      ],
      "role": "symbol",
      "title": "indefinite",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/indefinite"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/negativeInfinity": {
      "abstract": [
        {
          "text": "A flag that indicates the time is negative infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negativeInfinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/negativeInfinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_NegativeInfinity"
        }
      ],
      "role": "symbol",
      "title": "negativeInfinity",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/negativeinfinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/positiveInfinity": {
      "abstract": [
        {
          "text": "A flag that indicates the time is positive infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positiveInfinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/positiveInfinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_PositiveInfinity"
        }
      ],
      "role": "symbol",
      "title": "positiveInfinity",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/positiveinfinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/valid": {
      "abstract": [
        {
          "text": "A flag that indicates a time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeFlags",
          "text": "CMTimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/valid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlags_Valid"
        }
      ],
      "role": "symbol",
      "title": "valid",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeflags/valid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/valid",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/hasBeenRounded",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/positiveInfinity",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/indefinite",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/impliedValueFlagsMask"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTimeFlags_NegativeInfinity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_NegativeInfinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/valid",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/hasBeenRounded",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/positiveInfinity",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/indefinite",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeFlags/impliedValueFlagsMask"
              ],
              "title": "Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMTimeFlags_NegativeInfinity"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1indefinite/title",
          "value": "kCMTimeFlags_Indefinite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1indefinite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_Indefinite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1positiveInfinity/title",
          "value": "kCMTimeFlags_PositiveInfinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1positiveInfinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_PositiveInfinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags/title",
          "value": "CMTimeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1valid/title",
          "value": "kCMTimeFlags_Valid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1valid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_Valid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1impliedValueFlagsMask/title",
          "value": "kCMTimeFlags_ImpliedValueFlagsMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1impliedValueFlagsMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_ImpliedValueFlagsMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1negativeInfinity/title",
          "value": "kCMTimeFlags_NegativeInfinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1negativeInfinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_NegativeInfinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1hasBeenRounded/title",
          "value": "kCMTimeFlags_HasBeenRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeFlags~1hasBeenRounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlags_HasBeenRounded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimeflags/negativeinfinity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimeflags/negativeinfinity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
