{
  "abstract": [
    {
      "text": "The source blend factor (SBF) used by the RGB blend operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceRGBBlendFactor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTLRenderPipelineColorAttachmentDescriptor(py)sourceRGBBlendFactor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sourceRGBBlendFactor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLBlendFactor",
        "text": "MTLBlendFactor"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sourceRGBBlendFactor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "sourceRGBBlendFactor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sourceRGBBlendFactor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLBlendFactor",
              "text": "MTLBlendFactor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor": {
      "abstract": [
        {
          "text": "The source and destination blend factors are often needed to complete specification of a blend operation. In most cases, the blend factor for both RGB values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(rgb)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") and alpha values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(a)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") are similar to one another, but in some cases, such as ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorSourceAlphaSaturated",
          "type": "codeVoice"
        },
        {
          "text": ", the blend factor is slightly different. Four blend factors (",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ") refer to a constant blend color value that is set by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "code": "MTLRenderCommandEncoder",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one": {
      "abstract": [
        {
          "text": "Blend factor of one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOne"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.one",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/one"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Configures each pixel component value, including alpha, for the render pipeline’s constant blend color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBlendColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBlendColorRed:green:blue:alpha:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setBlendColor(red:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setblendcolor(red:green:blue:alpha:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor": {
      "abstract": [
        {
          "text": "A color render target that specifies the color configuration and color operations for a render pipeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineColorAttachmentDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLRenderPipelineColorAttachmentDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLRenderPipelineColorAttachmentDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationAlphaBlendFactor": {
      "abstract": [
        {
          "text": "The destination blend factor (DBF) used by the alpha blend operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationAlphaBlendFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBlendFactor",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationAlphaBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destinationAlphaBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "destinationAlphaBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/destinationalphablendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationRGBBlendFactor": {
      "abstract": [
        {
          "text": "The destination blend factor (DBF) used by the RGB blend operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationRGBBlendFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBlendFactor",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationRGBBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destinationRGBBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "destinationRGBBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/destinationrgbblendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceAlphaBlendFactor": {
      "abstract": [
        {
          "text": "The source blend factor (SBF) used by the alpha blend operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAlphaBlendFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBlendFactor",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceAlphaBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceAlphaBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "sourceAlphaBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/sourcealphablendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceRGBBlendFactor": {
      "abstract": [
        {
          "text": "The source blend factor (SBF) used by the RGB blend operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceRGBBlendFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLBlendFactor",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceRGBBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceRGBBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "sourceRGBBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/sourcergbblendfactor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Blend-Factors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationAlphaBlendFactor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationRGBBlendFactor",
        "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceAlphaBlendFactor"
      ],
      "title": "Specifying Blend Factors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sourceRGBBlendFactor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceRGBBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Blend-Factors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationAlphaBlendFactor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/destinationRGBBlendFactor",
                "doc://com.apple.metal/documentation/Metal/MTLRenderPipelineColorAttachmentDescriptor/sourceAlphaBlendFactor"
              ],
              "title": "Specifying Blend Factors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLBlendFactor",
                    "text": "MTLBlendFactor"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "sourceRGBBlendFactor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/title",
          "value": "MTLBlendFactorOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1sourceAlphaBlendFactor/title",
          "value": "sourceAlphaBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1sourceAlphaBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceAlphaBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1sourceRGBBlendFactor/title",
          "value": "sourceRGBBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1sourceRGBBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceRGBBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1destinationRGBBlendFactor/title",
          "value": "destinationRGBBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1destinationRGBBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destinationRGBBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/title",
          "value": "MTLBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/title",
          "value": "setBlendColorRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBlendColorRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1destinationAlphaBlendFactor/title",
          "value": "destinationAlphaBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor~1destinationAlphaBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destinationAlphaBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor/title",
          "value": "MTLRenderPipelineColorAttachmentDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineColorAttachmentDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderPipelineColorAttachmentDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLRenderPipelineColorAttachmentDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/sourcergbblendfactor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/sourcergbblendfactor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
