{
  "abstract": [
    {
      "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So6UIViewC5UIKitE12InvalidatingV12wrappedValue____AEy_xAbCE13InvalidationsO5TupleVy__AJy__qd__qd_0_GAJy__qd_1_qd_2_GGGx_qd__qd_0_qd_1_qd_2_tcAMRs_AC0aC0Rd__AcORd_0_AcORd_1_AcORd_2_r2_lufc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "InvalidationType1"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "genericParameter",
        "text": "InvalidationType2"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "genericParameter",
        "text": "InvalidationType3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "genericParameter",
        "text": "InvalidationType4"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "externalParam",
        "text": "wrappedValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "Value"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "InvalidationType1"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "InvalidationType2"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "InvalidationType3"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "InvalidationType4"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.1",
        "name": "Swift",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(wrappedValue:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "InvalidationType1"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "genericParameter",
              "text": "InvalidationType2"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "genericParameter",
              "text": "InvalidationType3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "genericParameter",
              "text": "InvalidationType4"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "wrappedValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "Value"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "invalidation1"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType1"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "invalidation2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType2"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "invalidation3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "invalidation4"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType4"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType"
            },
            {
              "kind": "text",
              "text": " == "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO",
              "text": "Invalidations"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations/Tuple",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO5TupleV",
              "text": "Tuple"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO",
              "text": "Invalidations"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations/Tuple",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO5TupleV",
              "text": "Tuple"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType1"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType2"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO",
              "text": "Invalidations"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations/Tuple",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So6UIViewC5UIKitE13InvalidationsO5TupleV",
              "text": "Tuple"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType3"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType4"
            },
            {
              "kind": "text",
              "text": ">>, "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType1"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit18UIViewInvalidatingP",
              "text": "UIViewInvalidating"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType2"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit18UIViewInvalidatingP",
              "text": "UIViewInvalidating"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType3"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit18UIViewInvalidatingP",
              "text": "UIViewInvalidating"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "InvalidationType4"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit18UIViewInvalidatingP",
              "text": "UIViewInvalidating"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The underlying value referenced by the invalidating variable.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "wrappedValue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A type of invalidation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "invalidation1"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A type of invalidation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "invalidation2"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A type of invalidation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "invalidation3"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A type of invalidation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "invalidation4"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating": {
      "abstract": [
        {
          "text": "A property wrapper that notifies the system that a property value change has invalidated an aspect of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Invalidating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Invalidating"
        }
      ],
      "role": "symbol",
      "title": "UIView.Invalidating",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates an aspect of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a property wrapper that notifies the system when a change in the property value invalidates aspects of the containing view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "InvalidationType10"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "wrappedValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType1"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType3"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType4"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType5"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType6"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType7"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType9"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "InvalidationType10"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations": {
      "abstract": [
        {
          "text": "Changes that cause an aspect of a view to be invalid and require an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Invalidations"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Invalidations"
        }
      ],
      "role": "symbol",
      "title": "UIView.Invalidations",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidations"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations/Tuple": {
      "abstract": [
        {
          "text": "A change that invalidates a combination of factors covered by the other invalidation types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Tuple"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidations/Tuple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Tuple"
        }
      ],
      "role": "symbol",
      "title": "UIView.Invalidations.Tuple",
      "type": "topic",
      "url": "/documentation/uikit/uiview/invalidations/tuple"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating": {
      "abstract": [
        {
          "text": "Implements a type of invalidation that can occur on a view that requires an update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewInvalidating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewInvalidating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewInvalidating"
        }
      ],
      "role": "symbol",
      "title": "UIViewInvalidating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewinvalidating"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Invalidating-Property-Wrapper",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/Invalidating/init(wrappedValue:_:_:_:_:_:_:_:_:_:_:)"
      ],
      "title": "Creating an Invalidating Property Wrapper"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/invalidating/init(wrappedvalue:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
