{
  "abstract": [
    {
      "text": "Creates a popup menu system accessory with the specified menu, display state, configuration options, and optional selection handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit15UICellAccessoryV9popUpMenu_9displayed7options31selectedElementDidChangeHandlerACSo6UIMenuC_AC14DisplayedStateOAC03PopeF7OptionsVyAIcSgtFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "popUpMenu"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIMenu",
        "text": "UIMenu"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "displayed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
        "text": "UICellAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
        "text": "DisplayedState"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
        "text": "UICellAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV16PopUpMenuOptionsV",
        "text": "PopUpMenuOptions"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "selectedElementDidChangeHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
        "text": "UICellAccessory"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV35MenuSelectedElementDidChangeHandlera",
        "text": "MenuSelectedElementDidChangeHandler"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
        "text": "UICellAccessory"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "popUpMenu"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "menu"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIMenu",
              "text": "UIMenu"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "displayed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
              "text": "UICellAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
              "text": "DisplayedState"
            },
            {
              "kind": "text",
              "text": " = .always, "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
              "text": "UICellAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV16PopUpMenuOptionsV",
              "text": "PopUpMenuOptions"
            },
            {
              "kind": "text",
              "text": " = PopUpMenuOptions(), "
            },
            {
              "kind": "externalParam",
              "text": "selectedElementDidChangeHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
              "text": "UICellAccessory"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV35MenuSelectedElementDidChangeHandlera",
              "text": "MenuSelectedElementDidChangeHandler"
            },
            {
              "kind": "text",
              "text": "? = nil) -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
              "text": "UICellAccessory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The menu to display when a user taps the popup menu accessory.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "menu"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The cell-editing states that the popup menu accessory appears in. This parameter has a default value of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState/always",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayed"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Configuration options for the popup menu accessory. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible configuration options.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional closure that the system calls when a user selects an element in the menu.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "selectedElementDidChangeHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A configured popup menu cell accessory that appears as a pair of chevrons that point upward and downward. This accessory indicates that tapping anywhere in the cell presents a popup menu. This accessory appears on the trailing edge of the cell.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct": {
      "abstract": [
        {
          "text": "An accessory in a collection view list cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState": {
      "abstract": [
        {
          "text": "Constants that describe the cell-editing states that the accessory appears in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayedState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayedState"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.DisplayedState",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/displayedstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState/always": {
      "abstract": [
        {
          "text": "The accessory always displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "always"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState/always",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICellAccessory.DisplayedState.always",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/displayedstate/always"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler": {
      "abstract": [
        {
          "text": "A closure type that defines a handler to perform when a user selects an element in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MenuSelectedElementDidChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MenuSelectedElementDidChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.MenuSelectedElementDidChangeHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/menuselectedelementdidchangehandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions": {
      "abstract": [
        {
          "text": "Configuration options for a popup menu accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PopUpMenuOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PopUpMenuOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.PopUpMenuOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/popupmenuoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)": {
      "abstract": [
        {
          "text": "Creates a popup menu system accessory with the specified menu, display state, configuration options, and optional selection handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUpMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV16PopUpMenuOptionsV",
          "text": "PopUpMenuOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedElementDidChangeHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV35MenuSelectedElementDidChangeHandlera",
          "text": "MenuSelectedElementDidChangeHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/popupmenu(_:displayed:options:selectedelementdidchangehandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenu": {
      "abstract": [
        {
          "text": "A container for grouping related menu elements in an app menu or contextual menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenu"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenu"
        }
      ],
      "role": "symbol",
      "title": "UIMenu",
      "type": "topic",
      "url": "/documentation/uikit/uimenu"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-popup-menu-accessory",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions"
      ],
      "title": "Creating a popup menu accessory"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/title",
          "value": "UIMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenu"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicellaccessory-swift.struct/popupmenu(_:displayed:options:selectedelementdidchangehandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
